### ISSUE TITLE
픽시브도 히토미처럼 폴더명 형식을 통한 폴더별 분류가 가능하면 좋을듯 합니다.

### ISSUE THREAD

**Issue by Dumbisted** [KurtBestor/Hitomi-Downloader-issues#1000]
제목 그대로입니다. 히토미는 # artist / blabla 등의 형식으로 폴더를 생성하는게 가능해서 몹시 편리한데 픽시브는 그런게 없어서 폴더별로 분류가 되질 않는지라 정렬시 조금 불편하더군요. 죄송한 얘기지만 부탁드리겠습니다.

**Comment by KurtBestor** [comment]
픽시브도 다음과 같이 작품 목록 주소를 입력하면 폴더로 받아져요:
https://www.pixiv.net/member.php?id=11
