### ISSUE TITLE
검색기 응답없음 후 자동으로 종료되는 문제

### ISSUE THREAD

**Issue by Madistaken** [KurtBestor/Hitomi-Downloader-issues#1001]
600개 정도의 파일들을 찾으면 프로그램이 멈추고 응답없음이 뜨더니 그대로 종료됩니다.
몇 달 동안 잘 사용하다 갑자기 이러네요.
기본, 삭제된 데이터는 잘 받아집니다.

**Comment by KurtCobane** [comment]
저도 같은증상이라 일주일넘게 여기에 글쓰고 별별 방법을 다해봤습니다.
개발자님도 해결못하셨는지 답도 안달리고.. ㅜㅜ

cmd 열고 netstat -i 치고 MTU값이 1500 밑으로 되어있는지 확인한번 해보세요
제 패킷값은 500으로 잡혀있더라구요...
1500 으로 바꾸니까 해결되었습니다.

**Comment by Madistaken** [comment]
> 저도 같은증상이라 일주일넘게 여기에 글쓰고 별별 방법을 다해봤습니다.
> 개발자님도 해결못하셨는지 답도 안달리고.. ㅜㅜ
> 
> cmd 열고 netstat -i 치고 MTU값이 1500 밑으로 되어있는지 확인한번 해보세요
> 제 패킷값은 500으로 잡혀있더라구요...
> 1500 으로 바꾸니까 해결되었습니다.

**Comment by Madistaken** [comment]
> 저도 같은증상이라 일주일넘게 여기에 글쓰고 별별 방법을 다해봤습니다.
> 개발자님도 해결못하셨는지 답도 안달리고.. ㅜㅜ
> 
> cmd 열고 netstat -i 치고 MTU값이 1500 밑으로 되어있는지 확인한번 해보세요
> 제 패킷값은 500으로 잡혀있더라구요...
> 1500 으로 바꾸니까 해결되었습니다.

**Comment by Madistaken** [comment]
전 MTU 값 이미 1500인데도 안되네요 ㅠ
답변은 감사합니다.

**Comment by KurtBestor** [comment]
다운로드 작업 목록에 몇 개나 있나요?

**Comment by Madistaken** [comment]
새로 다운받아서 하나도 없습니다.
