### ISSUE TITLE
lhscan.net 작동이 되던 사이트인데 갑자기 안되네요?

### ISSUE THREAD

**Issue by als0001** [KurtBestor/Hitomi-Downloader-issues#1002]
https://lhscan.net/ 

에서 어떤 것을 다운하려고 해도 응답이 없습니다. 

예> https://lhscan.net/read-neun-takahashi-tsutomu-raw-chapter-36.html

나머지도 마찬가지네요.

**Comment by KurtBestor** [comment]
다음과 같이 목록 주소를 입력해주세요:
https://lhscan.net/manga-neun-takahashi-tsutomu-raw.html
