### ISSUE TITLE
히토미 파일 다운로드시 익헨으로 전환됩니다.

### ISSUE THREAD

**Issue by Kor-RoseInn** [KurtBestor/Hitomi-Downloader-issues#1004]
모든 파일 빠짐없이 익헨 다운로드로 전환되어 매우 느리게 되거나 종종 다운로드 실패가 됩니다. 해결 방법이 있나요?

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/856
