### ISSUE TITLE
목록에서 미리보기 이미지가 안나옵니다. 

### ISSUE THREAD

**Issue by FRT222** [KurtBestor/Hitomi-Downloader-issues#1005]
안녕하세요 프로그램 항상 애용하고 있습니다.

다름이 아니라 검색창에서 미리보기(섬네일)이 보이지 않는 문제를 겪고 있어 이렇게 글을 올리게 되었습니다. 

다운 받은 목록에서는 미리보기가 정상적으로 보이는데 검색 기능을 사용할때만 현재 미리보기가 보이지 않고 있습니다. 이 곳에서 게시글을 검색해보니 저와 유사한 문제를 겪고 있던 분이 고급옵션에서 DPI 우회 설정을 키고 문제가 해결되었다는 사례를 보고 해보았지만 
![K-001](https://user-images.githubusercontent.com/43725719/61186777-1f362400-a6a4-11e9-885c-ac0ea911c336.png) 사진과 같은 에러창이 뜨면서 DPI 우회 설정이 풀립니다. 
해결 방법을 알고 계시다면 댓글 부탁드립니다.
감사합니다

**Comment by KurtBestor** [comment]
재부팅하고 다음 걸로 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview
