### ISSUE TITLE
C드라이브 용량 사라짐

### ISSUE THREAD

**Issue by GH6** [KurtBestor/Hitomi-Downloader-issues#1007]
프로그램을 D드라이브에 놓고 Pixiv에서 받고 있습니다.
근데 사용하면 할수록 (D드라이브에서 사라지는 용량보다는 적지만) 왜 C드라이브의 용량이 사라지는 걸까요.
벌써 10GB나 사라졌어요.
어디서 차는건지도 보이지가 않아요.
Temp 폴더? 거기도 보이지가 않고요.

**Comment by KurtBestor** [comment]
하드디스크 모니터 툴을 사용해서 확인해보세요.
