### ISSUE TITLE
작품들 중 몇 개가 검색되지 않습니다.

### ISSUE THREAD

**Issue by SolarStadium** [KurtBestor/Hitomi-Downloader-issues#1008]
fuyu mikan의 최근 작품 1446777, 1446779
tairame의 최근 작품 1446780 등

몇 개가 삭제된 데이터에서도 일반 데이터에서도 나오지 않고 있습니다.

직접 링크로 다운받는건 가능하나 목록에서 나오지 않아, 사이트로 직접 들어가지 않고
프로그램으로만 확인하던 입장에서 아쉬운 부분이라 문의 드립니다.

**Comment by KurtBestor** [comment]
기본데이터에서 보이네요.
