### ISSUE TITLE
관리자님 질문!

### ISSUE THREAD

**Issue by kikinet88** [KurtBestor/Hitomi-Downloader-issues#101]
일단 이전 버젼에서
테그 선별 할때
- 붙여서 했어는대

지금은.. - 입력하고 나서 female 치면 뒤에 문자열이 안나오는경우가 있습니다.

이전에는 -female: ??? 로 리스트 쫙 뜨는대
이제는 -만 붙여도 리스트가 안떠요...

**Comment by KurtBestor** [comment]
"-" 들어가는 태그도 검색되게 하려다가 그렇게 됐네요.

고친 버전입니다:
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview
테스트 부탁드려요.

**Comment by kikinet88** [comment]
건의 한 내용이 고쳐져 아주 좋네요
감사합니다.
