### ISSUE TITLE
익헨 자료검색 추가가능할까요?

### ISSUE THREAD

**Issue by buntail** [KurtBestor/Hitomi-Downloader-issues#1012]
image set / misc / western 

세가지는 검색이 안되는데 검색되게 추가가 가능했으면 좋겠습니다.

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/983

**Comment by shopinclude** [comment]
저 개인적으로도 건의드립니다! 온갖 방법을 동원해도 판다를 뚫을 수 없는 경우가 종종 있어서, 익헨 관련 자료들을 구경을 못 해봤네요. 익헨 자료들이 검색에 노출되는 키라던가 있으면 좋을 것도 같습니다!
