### ISSUE TITLE
다운받은 만화 리스트 안에서 검색 혹은 소팅 기능이 있으면 좋겠습니다

### ISSUE THREAD

**Issue by Laser-Cho** [KurtBestor/Hitomi-Downloader-issues#1015]
프로그램 감사합니다.

다만, 다운받은 만화들이 많아지면 잘 못찾고 한 만화를 두번 다운받는 경우가 있습니다.

이름순 소팅 혹은 검색 기능이 있으면 그 문제를 극복할 수 있을 것 같습니다.

**Comment by KurtBestor** [comment]
- `도움말` - `사용법... (F1)` - `다운로더 목록 필터링` 을 보거나,
- 다운로더 좌측 하단의 `정렬 기준...` - `제목`을 눌러보세요.
