### ISSUE TITLE
겔보루 다운받다가 하나 건의를 드려봅니다.

### ISSUE THREAD

**Issue by UzinSG** [KurtBestor/Hitomi-Downloader-issues#1017]
겔보루 계열에서 이미지를 긁는데요.

예를 들어 겔보루에서 remilia_scarlet 이라는 태그로 검색해서 링크를 걸어두게 되면
 - remilia_scarlet 이 태그에 걸린 총 파일수는 약 5만개 입니다.

그래서 페이지 지정 다운수를 ~50000 으로 하여 다운을 걸었지만 10000개만 다운이 되드라고요.

https://gelbooru.com/index.php?page=dapi&s=post&q=index&tags=remilia_scarlet&pid=99&limit=100

여기서 링크가 멈췄습니다. 그렇게 되면 제가 다시 10000개쯤 이미지 링크로 가서 다시 다운을 거는대요.

여기서 문제가 발생 합니다. 10000개 위치에서 다시 해줫는데 정보 부분은 위에 링크처럼 다시 0 ~ 99로 하여 같은 파일이 다운이 된다는 점 입니다.

그래서 임의적으로 

https://gelbooru.com/index.php?page=dapi&s=post&q=index&tags=remilia_scarlet&pid=100&limit=100

으로 다운을 걸었는대도 같은 증상이더군요.

프로그램 카운터가 총 10000개만 걸리게 끔되어있는거같은데

보통 보류 계열 사이트 긁으면 양이 너무 많은지라 제한을 좀 늘려줄수 있을가요?

아니면 10000개에서 걸리면 10000개 다운 받고 그 뒤에 다시 카운트가 자동으로 걸려서

그 태그에 있는 이미지를 전체 다운받을때 멈추게끔

remilia_scarlet 태그로 예를 들면 총 갯수가 5만개 쯤이니 1만개씩 사이클을 돈다면 총 5번 정도 반복해야합니다.

다운받다보니 빠르게되서 좋긴하나 끝난 위치부터 재다운이 안되드라고요.

그래서 정리 및 요약

이미지가 10000개가 제한인거 같다는 제 의견 // 늘리는게 안되다면

해당 1만개까지의 위치를 기억했다가 1만개 다운 끝날시 바로 이어서 다운
 - 해당 태그의 이미지가 다 다운될때까지 반복

이정도의 건의를 드려봅니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview
제한을 50,000 개로 늘리긴 했지만 사이트 자체에서 20,100 개 까지만 제한하네요.

**Comment by UzinSG** [comment]
제한이 있다면 이어서 다운로드도 가능하지않을가요?

**Comment by UzinSG** [comment]
20100개 다운은 되는데 그 이후가 다운이 안되는거 같네요. 그 이후 다운 기능도 있었으면 좋겠어요.

동인지 검색할때 1000개씩 검색하겠기요.(이어서 검색)

**Comment by KurtBestor** [comment]
사이트에서 직접 보시면 아시겠지만 20100 개 이상은 볼 수 없어요.

**Comment by UzinSG** [comment]
그렇군요....

**Comment by UzinSG** [comment]
결국은 해당 태그에 저장된 갯수가 아무리 많다도 서버에서 지원하는 20100개만 공개되는건가요.

**Comment by UzinSG** [comment]
아무튼 감사드립니다! 즐거운 하루되세요!

**Comment by KurtBestor** [comment]
사이트에서 직접 페이지 넘겨서 보시면 아시겠지만 20100개 이상은 볼 수 없어요..
다음 링크 들어가서 478 페이지 눌러보세요: https://gelbooru.com/index.php?page=post&s=list&tags=remilia_scarlet&pid=19992

**Comment by UzinSG** [comment]
확인했습니다. 겔보루 디코 가서 물어봤는데 숫자가 제데로 측정되지 않는것이라고 합니다.

카운트가 5만개던 뭐던 (이미 삭제된것들이 ...있던 게시물 데이터라고 합니다.)

즉 예를들어 5만개로 찍혀있던 게시물이 삭제된게 2만개라 3만개 일수도 있다고합니다.

그리고 20000개 이상으로 데이터가 왜 안되냐고 물었는데 그부분은 모른다고 하네요.

**Comment by UzinSG** [comment]
혹시 가능하시면 겔보루의 어미급인 단보루도 추가해주셨으면 합니다!

**Comment by KurtBestor** [comment]
단부루에 있는 건 갤부루에도 있기 때문에 넣지 않을거예요.
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/155

**Comment by KurtBestor** [comment]
https://github.com/KurtBestor/Hitomi-Downloader/issues/2074#issuecomment-654589343
