### ISSUE TITLE
마나모아 다운로드 안될때 참고하세요

### ISSUE THREAD

**Issue by kikinet88** [KurtBestor/Hitomi-Downloader-issues#1018]
1. 마나모아 웹은 정상 작동 하나 읽어들이다 멈춤
-> 특정 부분 부터 외부 웹을 사용합니다 , 즉 해당 링크는 임시 서버라서 다운로드가
     강제로 하더라도 막혀있습니다, 업로드 된지 최소 5~6일이 지나면 풀리니
     그때다시 받으시면 됩니다. 히토미다운로더 자체 문제는 아닙니다.

2. 다운로드가 완료되지 않는다
-> 링크가 사망한걸로 생각됩니다. 마나모아 자체 웹 들어가서 해당링크 들어가보세요
     그럼 접속이 되지 않거나 엑박 으로 나올겁니다.
      복구가 되지 않는 구형 링크이므로 포기하는게 좋습니다
      그래도 받으셔야 한다면 구글링 하시는게 정신건강에 좋습니다.

**Comment by nightow** [comment]
업로드 일자가 4/2일 자인 작품인데도 다운로드가 안됩니다.
한참을 로딩되다가 invalid 표시됩니다.
https://manamoa.net/bbs/board.php?bo_table=manga&wr_id=837393
