### ISSUE TITLE
다운로드 에러

### ISSUE THREAD

**Issue by jpdecade** [KurtBestor/Hitomi-Downloader-issues#1019]
저번과 동일한 증상이 또 나타나네요.

![image](https://user-images.githubusercontent.com/49438209/61873640-654f7b00-af21-11e9-8ce5-02bdf8e9183e.png)

스샷 확인 부탁드립니다.

히토미 링크를 붙여넣기 했을때 제목과 정보들은 가져오지만 다운로드는 0에서 멈춰있습니다.
유투브는 정상적으로 다운로드가 되지만 히토미는 스샷과 같은 에러가 발생하면서 다운로드가 안되네요.

그리고 저번에 문의드렸던 건인데 역시 갑자기 다운로더 종료시 백그라운드 프로세스가 여전히 남아있습니다.
증상이나 스샷은 저번것과 동일합니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by jpdecade** [comment]
> 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

해당 링크 파일로는 다운로드 잘됩니다. 감사합니다.
다운로더는 종료 후에도 백그라운드 프로세스는 여전히 활성화 되어있는데
방법이 없을까요?
