### ISSUE TITLE
클립보드 자동 추가 기능이 먹통이 됩니다.

### ISSUE THREAD

**Issue by aperie** [KurtBestor/Hitomi-Downloader-issues#1021]
정확한 조건은 모르겠는데 다운로더를 켜놓고 사용하다 보면 작동을 안 하는 경우가 있네요. 일단 한번 증상이 발생하면 옵션의 '클립보드에서 자동 추가'를 껐다 켜도 여전히 반응이 없고, 일단 프로그램을 종료했다가 다시 실행해야 제대로 동작하기 시작합니다. 그러다 시간이 지나면 어느새 또 반응이 없구요.

혹시 설정 관련해서 꼬인게 있나 싶어서 파일을 전부 다 지우고 다시 해 봐도 똑같더군요.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by aperie** [comment]
윗 버전 받아서 해 봤는데 마찬가지입니다.

**Comment by KurtBestor** [comment]
[v2.6b](https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/v2.6b) 는 어떤가요?

**Comment by aperie** [comment]
2.6b 버전은 문제 없는 것 같습니다. 테크니컬 프리뷰 버전 올라오면 매번 다운받아 사용하고 있는지라 정확하게 언제부터 그랬는지는 기억이 잘 안 나네요.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by aperie** [comment]
일단 현재까지 문제없이 잘 작동합니다. 빠르게 수정해주셔서 감사해요.
