### ISSUE TITLE
자꾸 파일 받을때 깨지는 파일이 나옵니다

### ISSUE THREAD

**Issue by gitwwwf** [KurtBestor/Hitomi-Downloader-issues#1024]
![rqwrafsfas](https://user-images.githubusercontent.com/53341711/61952469-e32d8800-afee-11e9-80df-81d28abc8eee.PNG)

지우고 다시 해봐도 자꾸 사진처럼 엑박뜨는 껍데기파일나옵니다..

해당 파일만 지우고 다시받기 누르면 인식을 못하는것고.. 해결방법없을까요?

**Comment by osmium-76** [comment]
혹시 히토미에서 받으셨나요? 서버상태가 안좋으면 저렇게 깨져서 다운받아지는데 폴더 지우고 다시하셔야해요. 지금 히토미에 사람 엄청몰려서 저도 파일 왕창 깨지네요

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview
