### ISSUE TITLE
Download finished but some pics are not yet.

### ISSUE THREAD

**Issue by LeonPride** [KurtBestor/Hitomi-Downloader-issues#1025]
I download dojinshi from hitomi, but when it finished I check the file, many pics are still not downloaded. Is there anything wrong with my setting? or just restart the download again and again?

**Comment by KurtBestor** [comment]
Try the test version: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by sellsell** [comment]
Having the same issue, going to try the test version and report back.

**Comment by nikin78** [comment]
Now crashed files never occur after using the test version. However, I can't assure but it seems like download speed is getting slower than before using it.

**Comment by sellsell** [comment]
The test version fixed the downloading of corrupted images for me as well, thank you.

**Comment by LeonPride** [comment]
Thx!  the problem seems solved.
