### ISSUE TITLE
파일 깨짐 + 속도 저하 문제

### ISSUE THREAD

**Issue by nikin78** [KurtBestor/Hitomi-Downloader-issues#1026]
늦은 밤중에도 노고가 많으십니다...

파일 깨짐에 대한 테스트 버전은 다른 스레드에서 다운 받아 현재 테스트 중입니다.

아직 완전히 테스트하진 못했으나, 다운 시 여전히 깨진 파일이 다운로드 되지만, 거의 동시에 새로이 정상 파일로 대체되는 것을 확인했습니다.

다만 속도가 26일 익헨 문제 터지기 전에 비해 시간이 갈 수록 많이 느려지고 있다보니 저용량의 파일도 다운 받는데 시간이 많이 걸립니다. 
(25일 당시 다운로드 속도 평균 2~4MB/s. 현재 0.1MB/s대 유지, 서버 셋팅은 '자동'으로 설정)

서버 문제로 생각해서 어쩔 수 없다 생각했는데, 모바일 어플 중 HitomiExplorer 앱의 경우 다운로드 속도는 번역작이 아니어도 약 2MB/s 정도로 크게 변함이 없더군요.

일부 작품의 경우 Ex/E-hen server로 설정하는 경우 오류가 나서 다시 hitomi 서버로 자동 설정해서 다운로드 중이긴 한데, 속도를 이전처럼 높일 수 있는 방법이 현재로선 없는지 궁금합니다.
 
항상 감사하게 생각하고 있습니다.

**Comment by kikinet88** [comment]
서버를 히요비로 바꾸시면 정상속도 나옵니다
히토미는 볼래가 미러서버라서 데이터 저장 이 일정량만 됩니다
그래서 속도가 떨어지고 익헨이 터져서 더 느린거죠

**Comment by nikin78** [comment]
조언 감사합니다. 혹시 히요비 쪽은 번역작만 다운로드가 가능하던가요?

**Comment by kikinet88** [comment]
히요비는 언어 - 코리아 만 될겁니다.
다른언어는  아마 404 뜰겁니다

**Comment by KurtBestor** [comment]
테스트 해봤는데, HitomiExplorer 도 속도 다르지 않던데요..
히토미 서버 자체가 느린거라 어쩔 수 없네요.
