### ISSUE TITLE
건의는 아니고 그냥 프로그램 칭찬하려구요.

### ISSUE THREAD

**Issue by e50gun** [KurtBestor/Hitomi-Downloader-issues#1027]
센세 정말 신세 많이 지고있습니다

픽시브 겔부루 다운받는기능 너무 너무 편리합니다 진짜

프로그램 발견하기 전까지 일일이 우클릭으로 저장해왔었는데....

오래 건강하게 장수하십쇼 선생님...

**Comment by KurtBestor** [comment]
감사합니다!
