### ISSUE TITLE
깨진 파일 체크 하는 방법 없나요?

### ISSUE THREAD

**Issue by wooeorbs** [KurtBestor/Hitomi-Downloader-issues#1029]
어제부터 방주 세우려고 1600개 다운 받았는데
파일 깨졌다는걸 방금 알았는데요.
이거 전부 다 압축파일이에요.
파일검수하려면 노가다 해야할 것 같은데

걍 다 지우고 받는 수밖에 없나요?

저장 폴더에 있는 모든 갤러리 넘버 복사하면 되는데 그러면 히토미 서버에 압박될거같아서 부담스럽네요.

**Comment by nikin78** [comment]
어차피 다운로더는 IP밴 방지 차원에서 최대 4개씩만 다운로드를 해서 큰 문제는 없을 것 같습니다

**Comment by KurtBestor** [comment]
압축파일 전부 폴더명으로 압축 풀고 다시 다운로드하면 알아서 받을거예요.
