### ISSUE TITLE
한번에 대량으로 다운로드 받기 불가능 문제

### ISSUE THREAD

**Issue by tipytipytipy** [KurtBestor/Hitomi-Downloader-issues#103]
전체 목록에서 한국어로 검색을하면 검색 결과가 몇만개 이상이다 보니,한번에 다운로드를 하면 튕기는 현상이 있어서 지금 검색범위를 쪼개서 하고있는데 너무 힘드네요.....

혹시 검색 결과를 지정된 개수단위로 짤라서 보여준다거나,검색범위응 지금처럼 드래그가 아닌 숫자로 입력하는 방법이 있다면 좀더 수월하게 받을수 있을거같은데 ....

아니면 혹시 제가 방볍을 모르는걸까요?

또한 한번 받은 파일이 검색 결과에 안걸리는 기능도 있으면 너무 좋을것같습니다 흑흑

**Comment by KurtBestor** [comment]
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

검색 범위 직접 입력할 수 있도록 바꿨습니다.
테스트 부탁드려요.

**Comment by tipytipytipy** [comment]
테스트 하고싶은데 자꾸 백신에서 걸리네요 백신에서 차단하고 실행해도 실행자체가 안되고있습니다....

**Comment by KurtBestor** [comment]
https://www.virustotal.com/#/file/943d3d655ab4239b4a2b42abfcbd29d6124b0e1997a92b00456d4b3ba73d372c/detection

VirusTotal 모두 Clean인데 무슨 백신 쓰시나요?

**Comment by tipytipytipy** [comment]
윈도우 디펜더 입니다,다른분들 말씀 없으신걸로 봐서 파일에 문제 없는거같긴한데 예외설정하고 해도 막히네요.....훅훅

**Comment by KurtBestor** [comment]
![defender](https://user-images.githubusercontent.com/14768120/40213657-8be441dc-5a91-11e8-935f-e1ed41038581.png)

혹시 이런 식으로 뜨나요?

**Comment by tipytipytipy** [comment]
파일에 바이러스 또는 기타 사용자 동의 없이 설치된 소프트웨어가 있기 때문에 작업이 완료되지 않았습니다

라고 뜹니다 저 화면이면 추가정보 누르고 실행 누르면 되는거같은데 이건 그냥 확인밖에 없네요
