### ISSUE TITLE
기능 개선 요청

### ISSUE THREAD

**Issue by meloncafe** [KurtBestor/Hitomi-Downloader-issues#1032]
![mstsc_2019-07-27_22-25-42](https://user-images.githubusercontent.com/6157093/61995054-299de800-b0be-11e9-8546-1ba48bd23033.png)

현재 저장폴더에서 선택할 수 있는 사이트와 아래의 폴더명 형식이 모든 사이트에 대해서 적용되고 있는데, 각 사이트별로 저장이 되었으면 합니다.
각 사이트별로 형식을 달리하고 싶은데 모든 사이트가 같은 형식으로 저장되어 버리네요.
시간되실때 한번 확인 부탁드리겠습니다.

감사합니다.

**Comment by kikinet88** [comment]
음 저같은경우 히토미 / 마나모아 등등 사이트별로 따로 설정이 되던걸요
클라이언트가 설치된 폴더 말고 다른 루트로 설정해서 해보시길 바랍니다
즉 예시로 C:\ lll \ 식으로

**Comment by KurtBestor** [comment]
사이트마다 artist 나 id가 없거나 하는 경우가 많고 유튜브 같은 단일 파일 다운로드 같은 경우 폴더가 없기 때문에 폴더명 형식을 대부분의 사이트에 일괄적으로 적용할 수 없어요.
그래서 히토미, 이헨, 마나모아 등 몇몇 사이트 빼고는 폴더명 형식을 따르지 않아요.
