### ISSUE TITLE
다운로드가 0에서 멈춰서 진행이 안됩니다

### ISSUE THREAD

**Issue by afaofpabwe** [KurtBestor/Hitomi-Downloader-issues#1033]
![진행안댐](https://user-images.githubusercontent.com/53374788/61995941-8f43a180-b0c9-11e9-9117-13d214720529.PNG)

용량이 없어서 그런가해서 삭제도 해서 최소 1기가 이상의 용량은 남아있는데 더이상 진행이 안됩니다.

**Comment by kikinet88** [comment]
익헨 터졌습니다... 정보가 느리시군요...
지금은 히요비 로 서버 지정해서 사용하셔야 할겁니다
참고로 원어 작품은 구하기가..

**Comment by afaofpabwe** [comment]
히토미로 해도 안되나여???

**Comment by lcm9026** [comment]
저도 잘되다가 갑자기 저래요

**Comment by lcm9026** [comment]
> 익헨 터졌습니다... 정보가 느리시군요...
> 지금은 히요비 로 서버 지정해서 사용하셔야 할겁니다
> 참고로 원어 작품은 구하기가..

히요비로 해도 안되는건 못받는건가요 히토미 사이트에 직접 들어가서 받아도 너무 느리네요

**Comment by KurtBestor** [comment]
`옵션` - `설정` - `고급 설정` - `DPI 우회`를 키세요.
