### ISSUE TITLE
익펀된 자료들은 서치가 안되나요?

### ISSUE THREAD

**Issue by rsef1234** [KurtBestor/Hitomi-Downloader-issues#1034]
868757나 1409612처럼 이헨에 검색은 되지만 익펀돼있는 작품들이 히토미 서치에는 검색되지 않습니다. 히토미사이트 리더로도 못보는 작품이라 그런건가요?

**Comment by kikinet88** [comment]
익헨 과 링크가 된자료라면 현제 링크가 풀렸거나 익헨이 터져서 더이상 검색이 안될수도 있습니다
문제는 히토미 자체가 미러서버 이기때문에 앞머리가 터지면 몸통도 같이 터진다고 보시면될듯
현제 히토미 로 검색은 되지만 링크가 터져서 다운로드가 안되는게 많습니다

**Comment by nikin78** [comment]
예시로 들어주신 두 작품 모두 히토미 사이트에선 검색되지 않으나, 다운로더를 이용 시 이헨 쪽을 경유하여 정상적으로 다운로드 되는 것을 확인했습니다.

**Comment by kiriaricon** [comment]
d

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/983

**Comment by rsef1234** [comment]
> 참고해주세요: #983

아 답변 감사합니다
