### ISSUE TITLE
why does it want admin rights?

### ISSUE THREAD

**Issue by ticktickMOF** [KurtBestor/Hitomi-Downloader-issues#1036]
why does this want to run with elevated privileges?

**Comment by KurtBestor** [comment]
It needs elevated privileges to run [GoodbyeDPI](https://github.com/ValdikSS/GoodbyeDPI).
Please press `No` if you don't want:
![image](https://user-images.githubusercontent.com/14768120/62020979-15fa9a80-b200-11e9-917c-3b65b232e8bd.png)
