### ISSUE TITLE
히토미 모두 다운로드 받기 할 수 있나요?

### ISSUE THREAD

**Issue by JJJu9952** [KurtBestor/Hitomi-Downloader-issues#1037]
HDoujin Dowmloader는 히토미 모두 다운로드 받기 가능한대
Hitomi-Downloader는 히토미 모두 다운로드 받기 지금 불가능해
그리고 마나모아는 모두 다운로드 받기 됐어요ㅠㅜ
내년 히토미 멸망 오겠네

히토미 모두 다운로드 받기 만들 수 있나요?
HDoujin Dowmloader처럼 
https://hitomi.la/artist/kiyokawa%20nijiko-all-1.html 25개까지 만들면 되지.

**Comment by JJJu9952** [comment]
https://hitomi.la/artist/kiyokawa%20nijiko-all-1.html 검색 쓰면 25개 목록 나옵니다

**Comment by JJJu9952** [comment]
HDoujin Dowmloader는 다운로드 속도 느립니다. 매우 실망했다
Hitomi-Downloader는 다운로드 속도 괜찮은것치고 평이 좋네요

**Comment by nikin78** [comment]
말씀하시는 '히토미 모두 다운로드 받기'가 히토미 서버 DB 내 모든 데이터를 다운 받는 기능을 말씀하시는게 아니라, 단순히 자기가 찾고자 하는 작가, 그룹 등을 검색해 나온 작품들을 일괄 다운로드할 수 있는지에 대해 여쭈어보시는 것이라면 방법은 단순합니다.
검색기 기준 우클릭 후 뜨는 창 하단에 모두 선택을 누르신 뒤, 재차 우클릭 버튼을 눌러 다운로드를 선택해 내려받기 진행하시면 됩니다.

그게 아니라면...

**Comment by JJJu9952** [comment]
베리 굿~!베리 떙큐~!
도움 잘되네요
