### ISSUE TITLE
검색기에서 오프라인상태일시(or dpi우회 안된상태) 이미 다운받아진 파일들은 썸네일(미리보기이미지)을 나오게 할 수는 없나요?

### ISSUE THREAD

**Issue by jinjins7** [KurtBestor/Hitomi-Downloader-issues#1038]
검색기에서 오프라인상태일시(또는 dpi우회가 안되어서 접속불가 상태일 시) 이미 다운받아진 파일들은 썸네일(미리보기이미지)을 나오게 할 수는 없나요?
저장된 폴더의 첫번째 이미지를 로드해서 썸네일에 띄워준다는 식으로....

아 그리고 사족으로 이미 받은것을 제외하고 안받은것만 검색하는 필터는 설정 못하나요?

**Comment by KurtBestor** [comment]
`도움말` - `사용법... (F1)` - `검색기 목록 필터링` 을 보세요.
