### ISSUE TITLE
작가명 폴더 분류 다운로드 불가

### ISSUE THREAD

**Issue by YTOAA** [KurtBestor/Hitomi-Downloader-issues#104]
이전 버전들은 폴더명을
# artist / title (id) 로 했으면 각 작품의 작가명 이름별로 폴더생성후 그 작가명 폴더안에다가 다운로드 
되었으나 최근버전은 # artist / title (id) 자체로 폴더명이 되어버립니다 예를들어
예전에는 #작가이름 폴더 안에 title (id)폴더가 생성됬던 반면
지금은 #작가이름 / title (id) 가 폴더명 자체가 되어버립니다

**Comment by KurtBestor** [comment]
참고해주세요: #92

**Comment by YTOAA** [comment]
테스트 버전 결과 작가명 폴더 분류가 잘 되네요
아직 다른 문제는 발견하지 못했습니다.
