### ISSUE TITLE
무한 로딩 오류

### ISSUE THREAD

**Issue by naninore** [KurtBestor/Hitomi-Downloader-issues#1040]
업데이트 이후 저장폴더를 찾을 수 없습니다 라는 메시지가 뜨고 로딩창에서 넘어가지 않습니다.
저장했던 목록도 불러오지 못하고 로딩만 반복하과 있는데 어떻게 해결해야 할까요?

**Comment by KurtBestor** [comment]
어떻게 뜨는지 스크린샷 찍어서 보여주세요.
