### ISSUE TITLE
다운로드가 않됩니다.

### ISSUE THREAD

**Issue by apple1367** [KurtBestor/Hitomi-Downloader-issues#1041]
익헨은 터졌지만 이헨은 안터진걸로 알고있습니다... 불과 3시간 전만해도 잘 되었는데요
한번 벤 걸리고 풀렸는데 다운로드가 않됩니다.
서버는 익헨/이헨서버로 했고요.
재시작해봐도 해결이 않됩니다.
다운받는중에 다운받을 폴더 디렉토리를 바꾸긴 했습니다.

**Comment by KurtBestor** [comment]
재시작 해보시고 서버는 자동으로 해주세요.
