### ISSUE TITLE
가끔 이런 오류가 뜨는데 왜 이런가요?

### ISSUE THREAD

**Issue by sz1ah2** [KurtBestor/Hitomi-Downloader-issues#1042]
![20190728_154242](https://user-images.githubusercontent.com/53392118/62003220-dfb11280-b14e-11e9-9a37-74a627ca1a48.jpg)
이러면서 팅기네요.

**Comment by KurtBestor** [comment]
목록에 작업이 몇 개 있나요?

**Comment by sz1ah2** [comment]
> 목록에 작업이 몇 개 있나요?

처음 1000개 받아서 다운받다가
어떨 때는 오류 안뜨는데
어떨 때는 100개 남았을 쯤 오류뜨면서 팅기는데
작업 양에 따라 오류도 나고 그러나요?
