### ISSUE TITLE
안녕하세요 수고가 많으십니다 dpi가 계속 꺼지네요

### ISSUE THREAD

**Issue by lcm9026** [KurtBestor/Hitomi-Downloader-issues#1043]
![제목 없음](https://user-images.githubusercontent.com/53392669/62003466-5b608e80-b152-11e9-882f-0e9624c16808.png)
dpi를 켜도 저절로 꺼집니다. 핫스팟 쉴드를 꺼봐도 계속 설정해둔게  off로 바뀌듯이 자동으로 꺼져요.

**Comment by lcm9026** [comment]
그 테스트 버전의 다운로더로도 해봤는데 안되네요 게다가 지금은 0에서 다운이 시작도 안돼요

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/546#issuecomment-464473160
