### ISSUE TITLE
다운로드 목록을 불러오다가 꺼져 버립니다

### ISSUE THREAD

**Issue by HGNeonPenzer** [KurtBestor/Hitomi-Downloader-issues#1044]
![오류](https://user-images.githubusercontent.com/48048395/62003951-d9746380-b159-11e9-9912-ab8a3cb37e67.png)
잘 돌리고 있다가 메모리 1GB 먹은 시점에서 터져버리더니
다시 키면 처음에는 엄청 빨리 불러오다가 불러오는 속도가 조금씩 느려지더니 저기에서 꺼져 버리네요
키면 꺼져 버리니 실행을 못하고 있습니다, 다 못 받은 상태에서 꺼져버려서 재설치 하기도 꺼려지네요 ㅠㅠ

혹시 몰라 CPU 하고 ram용량 적어봅니다
Ryzen 5 2600X
ram 16GB

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/789
