### ISSUE TITLE
히토미 망가 다운 받았는데 파일을 사라집니다.

### ISSUE THREAD

**Issue by JJJu9952** [KurtBestor/Hitomi-Downloader-issues#1046]
![001](https://user-images.githubusercontent.com/51252422/62009202-90db9b00-b197-11e9-96c0-eb53fc4ad6a7.jpg)
![002](https://user-images.githubusercontent.com/51252422/62009203-90db9b00-b197-11e9-8314-2b61244bd0bb.jpg)
184페이지 - 526페이지 = 342페이지는 파일 사라진다. 
히토미 뭔가 문제 있는 것 같은데

**Comment by JJJu9952** [comment]
다운받고 끝난 후에 
뷰어 열어보고 상태는 184페이지였어요
342페이지가 데이터 날아가버렸어요(사라진다) 
삭제 안했어요

**Comment by KurtBestor** [comment]
컴퓨터 재부팅한 다음 작 다시 시작해보세요.
