### ISSUE TITLE
페이지수 필터링이 작동하지 않습니다

### ISSUE THREAD

**Issue by c47007** [KurtBestor/Hitomi-Downloader-issues#1047]
2.6d 버전에서 페이지수 필터링이 작동하지 않습니다
p>100
p<100

확인부탁드립니다

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by c47007** [comment]
> 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

문제없습니다
