### ISSUE TITLE
히토미 다운받다보면 분류해서 정리해야하는데 건의해봐요

### ISSUE THREAD

**Issue by wooeorbs** [KurtBestor/Hitomi-Downloader-issues#1049]
검색하면 제목과 작가, 태그가 나오잖아요
히토미 다운로더 기본 데이터로 참고해서 나오는 것 같은데

그러면 그 저장된 폴더 내에 작가, 제목, 번호 추출하고 번호 검색해서 태그를 추출하고 예를 들어 저장 폴더에 있는 모든 갤러리 넘버 복사가 그건데 그것처럼 활용해서 작가폴더, 태그폴더 등등 간단하게 정리할 수 있는 기능을 넣어보면 어떨까요?

원래대로라면 태그 검색해서 다운받고 정리해도 되지만 방주 세우려고 막 다운받다보면 태그가 어떤지 모르잖아요 그래서 이 기능을 넣어주실 수 있는지 건의해봐요.

**Comment by KurtBestor** [comment]
무슨 말인지 모르겠는데 좀 더 명확하게 설명해주실 수 있나요?

**Comment by Kuluin** [comment]
저분이 말씀하시는게 제가보기엔 다운로더에서 받은 파일에 info.txt를 참조하여

탐색기처럼 분류해서 장르나 작가별로 분류할수 있는 뷰어형 탐색기를 만들어달라는것 같네요

뭐 예를들어  female:unusual pupils일 경우 다운받은 목록에서 자동색인 되게 해달라는거 아닐까요

웹에 있는걸 제외하고 오프라인에서의 얘기인듯 합니다.

파일정리가 좀더 원할하게 되도록 말이죠
현재는 [작가] 제목 (갤러리번호) 이형태지만 이형태를 유지하면서 
작가별 폴더를 따로 두거나 하는것도 나쁘진 않아보이네요.

확실히 지금 다운로드받은 파일의 색인이 찾기 힘든게 
저는 언어도 각기 다른걸쓰는지라 확인이 어렵더군요.

위의 의견에 더불어 탐색기처럼 바로바로 분류되고 별도 뷰어도 있으면 좋을것 같습니다.
거기에 현재 중복이미지 찾기가 한폴더에 너무 많이 들어가있으면 다운되버릴수도 있기에
작가 폴더마다 중복검색하도록 폴더 분류가 되있는것도 괜찮구요.

그리고 작가즐겨찾기가 너무 많아져서

아래처럼 화면이 꽉차버립니다. 이점은 조금 어떻게 해야할것 같습니다.

![dwqdqw](https://user-images.githubusercontent.com/53428361/62038652-18c1b380-b231-11e9-9136-515da5ce6055.png)

**Comment by Kuluin** [comment]
![2121](https://user-images.githubusercontent.com/53428361/62039252-4eb36780-b232-11e9-917c-50aa017993f5.png)
![21321](https://user-images.githubusercontent.com/53428361/62039253-4f4bfe00-b232-11e9-97bf-1ce30c51e4d8.png)

추가 설명 사진 올립니다.

**Comment by Kuluin** [comment]
![1515](https://user-images.githubusercontent.com/53428361/62040156-fed5a000-b233-11e9-97a8-a870076f42d1.png)

**Comment by DevSejin** [comment]
다운경로 설정 잘 세팅 하시면 "#작가폴더 / 제목 (갤러리넘버)"의 형식으로 저장하는 옵션이 있을텐데요.
이미 그 설정없이 받은 자료를 저 규칙대로 분류할수 있도록 하는것을 원하시는걸까요?
