### ISSUE TITLE
마루마루 중복스킵

### ISSUE THREAD

**Issue by arsia13** [KurtBestor/Hitomi-Downloader-issues#105]
마루마루 주소를 가지고 한번에 넣어서 다운로드하는데 해당 만화가 업데이트가 되었으면 새로운 화가 추가되어 있을 텐데 그냥 전체 다운로드를 했을 시에 앞에 이미 다운로드된 화를 모두 스킵하고 최신 화만 다운받도록 하고 싶은데요 가능한가요?

**Comment by KurtBestor** [comment]
전에도 생각했던 기능인데요, 실제로 구현도 했지만 비활성화해두었어요.
다음과 같은 상황일 때 해당 파일들을 놓칠 가능성이 있기 때문에 보류해두었습니다:
1. 다운로드 중 오류로 일부 파일이 빠짐
2. 다운로드 중 사용자의 중단으로 일부 파일이 빠짐

일부 화만 다운로드하려면 다음 기능을 써주세요:
![maru](https://user-images.githubusercontent.com/14768120/40266417-96dcc7d6-5b85-11e8-8ccb-648eb9d39d7a.png)

**Comment by arsia13** [comment]
욕심이지만 제가 많은 양의 만화 주소를 가지고 있고 한번에 다운로드를 하는데... 코드가 없어 개인적으로 손봐서 쓸 수도 없고.... 혹시 기능을 활성화한 프로그램을 개인적인 요청으로 받는건.... 욕심이겠죠 ㅠㅠ? 아쉽네요.... 사실 리캡챠만 없으면 다시 다운로드해도 그냥 기다리면 되는데 리캡챠때문에 힘드네요 ㅜㅜ

**Comment by KurtBestor** [comment]
[이거](https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/download/Utils/hitomi_downloader_GUI_maru_skip.zip) 쓰세요

**Comment by arsia13** [comment]
아.... 정말 감사합니다! 항상 감사하게 생각하고 있어요 ㅠㅠ

**Comment by arsia13** [comment]
중복스킵은 잘 되는데 리캡챠 기능을 오픈하면 invalid에러가 나는데 이건 왜 그런거죠?

**Comment by KurtBestor** [comment]
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

고쳤습니다.
다음 버전부턴 이 기능을 활성화하려고 해요.

**Comment by arsia13** [comment]
아 감사합니다~
