### ISSUE TITLE
미러링관련

### ISSUE THREAD

**Issue by qiiiiiib** [KurtBestor/Hitomi-Downloader-issues#1051]
미러링 or 백업

**Comment by nikin78** [comment]
미러링은 백업이 아니라서, 원본 소스가 담긴 익헨 서버가 사라지면 자연스레 다운이 불가능해진다고 보시면 됩니다... 
이헨에도 등재된 소스들은 히토미에도 미러링되어 있기에 멀쩡하지만, 이헨엔 없고 익헨에만 있던 건 히요비나 N헨 같은 곳에 극소수만 특별히 따로 백업된 게 아닌 이상 그냥 더이상 구할 수 없는 거죠

**Comment by enflers** [comment]
그럼 hitomi downloader에서 검색은 되지만 다운이 안되는건가요
아니면 검색조차 안되고 있는건가요?

**Comment by KurtBestor** [comment]
특별한 이유 없으면 히토미 서버에 남아있어요.
그리고 익헨 잘 되네요.

**Comment by supermekadeathstalin** [comment]
익헨이 죽은자 가운데서 다시 살아나셧거든요
