### ISSUE TITLE
다운로드 목록 이미지가 나오질 않습니다

### ISSUE THREAD

**Issue by vkdlsjf55** [KurtBestor/Hitomi-Downloader-issues#1052]
![오류 파일](https://user-images.githubusercontent.com/53468862/62114108-e37c9a80-b2f0-11e9-970b-15a123a3a3c7.PNG)

히토미 다운로더 잘 쓰고 있는 사람입니다 오늘 오류가 나오기 시작했는데 버전은 2.6d 입니다 어제 쯤 다운로드를 받고 저장 & 종료를 눌렀으나 오류 소리와 함께 영어 문장이 나왔으나 신경 쓰지 않고 꺼진 다음 오늘 히토미 다운로드를 켰으나 위 이미지와 같은 오류가 발생함과 동시에 다운 받았지 않았던 이미지 목록의 파일들도 자동으로 다운 받아집니다 1650개 중 596개 정도 다운 받았습니다만. 더운 날에도 고생 많아 죄송스럽지만 도와주시면 감사하겠습니다 선생님

**Comment by KurtBestor** [comment]
작업 900개 이상은 권장하지 않아요. 참고해주세요: #170
