### ISSUE TITLE
검색기능이 고장난거같습니다

### ISSUE THREAD

**Issue by cul9** [KurtBestor/Hitomi-Downloader-issues#1054]
hoyoyodou 작가 등 검색하면 안나오는게 좀 많습니다
Tachibana Omina 작가 같은건 중간중간 몇개씩 안보이는게 있습니다
아마도 같은 원인이지 않을까요?
히토미 서버엔 살아있습니다. 정상적으로 볼수도 있고요

그리고 언어설정에 n/a랑 japanese 를 같이 검색할수있을까요?
n/a가 꽤많고 그게 거의 다 일본어입니다.

**Comment by KurtBestor** [comment]
검색에서 안 나오는 작품 알려주세요.

언어에 `Japanese + N/A` 라고 쓰면 돼요.
