### ISSUE TITLE
sankaku 5000장 다운로드가 안됩니다

### ISSUE THREAD

**Issue by Krib59** [KurtBestor/Hitomi-Downloader-issues#1055]
페이지 ~ 5132 도 해보고 1 ~ 5132 도 해봤는데 1999장만 받아지는데 살려주세요
버전은 2.6d 쓰고 있습니다

**Comment by KurtBestor** [comment]
해당 작업 `마우스 우 클릭` - `정보... (I)` 눌러서 나온 내용 보여주세요.
