### ISSUE TITLE
유튜브 음원 다운로드가 안됩니다.

### ISSUE THREAD

**Issue by gksduf11** [KurtBestor/Hitomi-Downloader-issues#1056]
옵션에서 유튜브 설정에 들어가 파일 형식을 mp3 로 변환후 다운로드 하면 
다운로드 후 변환 과정에서 '이 앱을 실행할 수 없습니다' 라는 오류가 뜨고 변환이 안 됩니다.

**Comment by KurtBestor** [comment]
해당 작업 `마우스 우 클릭` - `정보... (I)` 눌러서 나온 내용 보여주세요.
