### ISSUE TITLE
다운로드 오류? 실패?

### ISSUE THREAD

**Issue by aksghkqhrl** [KurtBestor/Hitomi-Downloader-issues#1057]
![0001](https://user-images.githubusercontent.com/47558641/62148459-b7830880-b334-11e9-946a-154ed8e4fcb2.png)

외장하드에 프로그램을 넣어서 다운받아서 어디서든 볼수있도록 넣어다니는데 이번에 항상 집에서만 다운받다가 친구집에 외장하드를 가지고가서 다운을 받았었는데 집에와서 확인해보니 친구 집에서 다운받은 만화는 오류로 확인됩니다.

일부 만화는 저 오류가 뜬 후 파일이 사라지구요.

![0002](https://user-images.githubusercontent.com/47558641/62148844-76d7bf00-b335-11e9-853c-70115dc3c4f8.png)

그리고 친구 컴퓨터에서 사용한 이후 제 컴퓨터로 왔을때는 히토미 다운로더가 아예 저런 문구가 나오면서 실행이 안되서 다른걸로 따로 받아서 다시 사용중입니다 ㅠㅠ

**Comment by KurtBestor** [comment]
제 쪽에선 재현할 수가 없네요..ㅠ
