### ISSUE TITLE
내장 dpi도 굿바이dpi도 안먹히네요

### ISSUE THREAD

**Issue by kdwkdwkdw** [KurtBestor/Hitomi-Downloader-issues#1058]
어제까지만 해도 문제없이 다운이 됐었는데 지금은 읽는중이라고만 표시되고 vpn을 켜서 우회를 하지 않으면 다운이 되질 않습니다. 참고로 일단 읽는중을 마치고 다운을 시작하면 vpn을 꺼도 다운이 되던데, 혹시 뭐가 문젠지 알 수 있을까요?

**Comment by DevSejin** [comment]
재부팅하시고 모든 vpn과 dpi우회 프로그램 켜지 마시고 내장만 켜고 해보세요.
여러 우회 프로그램들을 열어서 켯다껏다 하면 충돌오류가 나서 네트워크 문제가 생기기도 하더라구요
