### ISSUE TITLE
작품 네이밍 시 적용되는 토큰 종류가 궁금합니다

### ISSUE THREAD

**Issue by nikin78** [KurtBestor/Hitomi-Downloader-issues#1059]
현재는 다운로드 시 네이밍을 

(id) [artist][group] title [lang][series]

이와 같이 설정하여 쓰고 있는데,

작품번호, 작가, 그룹, 제목, 언어, 시리즈 외에 추가할 수 있는 토큰은 어떻게 되는지,

혹시 '작품 종류'를 추가할 수 있는지 문의드리고 싶습니다.

예를 들어 해당 작품이 히토미나 이헨 상에서 Artist CG로 분류되어 있다면, 

이를 설정할 경우 어떤 토큰으로 입력하면 되는 지에 대해서요

**Comment by KurtBestor** [comment]
`type` 이라고 입력하면 돼요.
우측 화살표 누르시면 예제들이 나와있어요.
