### ISSUE TITLE
작품단위로 필터링 걸수없을까요?

### ISSUE THREAD

**Issue by sizz12** [KurtBestor/Hitomi-Downloader-issues#106]
중복된 만화도 많이 올라오는경우도 있고
잘은 모르겠지만 갤러링넘버로 세세하게 차단못할까요?

**Comment by KurtBestor** [comment]
갤러리 넘버는 다르지만 같은 작품일 경우에 그 중 하나만 표시한다는 건가요?

**Comment by sizz12** [comment]
네  그밖에도  
작가,그룹,시리즈,캐릭터,태그:N/A 전부 불명인 작품들 걸러낼수있을거같아요 
-

**Comment by sizz12** [comment]
네 그밖에도
작가,그룹,시리즈,캐릭터,태그:N/A 전부 불명인 작품들 걸러낼수있을거같아요

**Comment by KurtBestor** [comment]
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

테스트 부탁드려요.

검색기 - 메뉴 - 중복 제거에서 설정할 수 있습니다.

**Comment by sizz12** [comment]
바이러스때매 설치가 안되요

**Comment by KurtBestor** [comment]
@sizz12 
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/128

**Comment by sizz12** [comment]
![default](https://user-images.githubusercontent.com/39451201/41533689-9eaf63ec-7336-11e8-88b8-7fdca927d576.jpg)
타이틀이 정확하게 일치하는 작품들은 제거가되는데 
틀린애들은 여전히있더라구요  
이부분은 해당작품을 검색에서 제외하는옵션이 나와야 할거같아요
