### ISSUE TITLE
검색기가 다중실행이 됬으면 좋겠습니다.

### ISSUE THREAD

**Issue by Kuluin** [KurtBestor/Hitomi-Downloader-issues#1060]
지금 hitomi searcher로 검색할경우

장르로 검색하다가 내용중에 마음의 드는 작가가 있어
작가로 검색할경우 기존에 장르로 검색한 내용을 버리고 다시 검색해야 하는데요

다시 장르로 검색하려니 번거로움을 느끼게 됩니다.

크롬 탭형식처럼 검색기가 여러개 시동되게 할수는 없을까요

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/117
