### ISSUE TITLE
기본 DB데이터에 대하여 질문드립니다.

### ISSUE THREAD

**Issue by sonson0118** [KurtBestor/Hitomi-Downloader-issues#1061]
히토미 다운로더 잘 쓰고있습니다. 
감사합니다.

현재 히토미사이트가 없어질지도 몰라서 틈틈히 다운로드 중인데 가끔  다운 대기가 천개가 넘어가면 프로그램자체가 사라지거나 멈추는 등의 모습을 보여 TXT파일이나 엑셀로
다운 내역을 관리하고 싶습니다.

보니까 기본 DB데이터파일이 JSON으로 가져오는거 같은데 이걸 엑셀로 변환하는 방법같은건 없을까요?

**Comment by KurtBestor** [comment]
다음 기능들을 써서 HDT 파일로 관리하세요:
- `파일` - `선택된 작업들 내보내기...`
- `파일` - `작업들 가져오기...`
