### ISSUE TITLE
중복 만화를 걸러낼 방법은 없을까요?

### ISSUE THREAD

**Issue by aksghkqhrl** [KurtBestor/Hitomi-Downloader-issues#1062]
https://manamoa10.net/bbs/page.php?hid=manga_detail&manga_id=9955

https://manamoa8.net/bbs/page.php?hid=manga_detail&manga_id=9955

둘다 같은 만화지만 다운로더에서 [클립보드 자동 추가]를 사용할때 같은 만화로 인식하여 걸러내지않고 다른 인식하여 목록에 자동으로 추가됩니다. 한두개정도의 만화라면 직접 걸러내겠지만 만화목록이 조금 있다보니 하나하나 걸러내기가 너무 힘듭니다 ...

사이트가 계속 유지된다면 모르겠지만 언제든지 바뀔수가 있다보니 .. 그런 기능이 있으면 좋겠습니다.

**Comment by KurtBestor** [comment]
`도움말` - `사용법... (F1)` - `다운로더 목록 필터링` 을 보세요.
