### ISSUE TITLE
히요비 다운로드가 안됩니다

### ISSUE THREAD

**Issue by nikin78** [KurtBestor/Hitomi-Downloader-issues#1063]
https://히요비.asia/reader/10000031

다음과 같은 작품을 다운로드 하고자 하는데, 

![오류 메세지](https://user-images.githubusercontent.com/53351465/62279035-3f2b5d00-b484-11e9-853a-809338f4ef54.PNG)

다음과 같이 invaild 하다면서 다운로드가 안되네요.

히요비 주소가 이젠 영문이 아니라, 위와 같이 부분적으로 한글로 바뀐 것으로

알고 있는데, 그렇다면 다운로더에서 따로 취해줘야 할 작업이 있는 것인가요?

아님 다운이 안되는 건 단순한 버그인 건가요?

**Comment by KurtBestor** [comment]
해당 작업 `마우스 우 클릭` - `정보... (I)` 눌러서 나온 내용 보여주세요.

**Comment by nikin78** [comment]
재시도한 결과 정상적으로 다운로드되었기에 당장은 쓰레드를 닫겠습니다. 혹시 문제가 반복된다면 말씀하신 방법대로 로그 크롤링해서 개제하겠습니다. 감사합니다.
