### ISSUE TITLE
검색 목록을 저장할 수는 없나요?

### ISSUE THREAD

**Issue by mnkycj** [KurtBestor/Hitomi-Downloader-issues#1064]
![이미지 003](https://user-images.githubusercontent.com/53565399/62290211-c0421e80-b49b-11e9-8d43-8872ebfbfe59.png)

예를들어 지금 최신순으로 8천개를 검색했는데 

이상태에서 프로그램을 껐다 켜면 검색 히스토리가 날아가서 다시 8천개를 검색해야 합니다

현재 검색한 상태를 내보내서 다시 프로그램을 켰을때 불러올수 있게 해주실수 있나요?

**Comment by KurtBestor** [comment]
`옵션` - `고급 검색` 을 키고

다운로더 끄기 전에 해당 검색 마지막 갤러리 넘버를 기록했다가 `검색 범위`에 넣고 검색하세요.
