### ISSUE TITLE
히토미에서 내려간 걸 삭제된 데이터로 검색해도 안 보입니다

### ISSUE THREAD

**Issue by starspeargirl** [KurtBestor/Hitomi-Downloader-issues#1065]
https://hitomi.la/galleries/1451761.html

나중에 웹에서 다시 볼 땐 404 Not Found만 뜨길래

다운로더로 삭제된 데이터를 갱신하고 검색했더니 가장 최근이 1450084로 나오고 이건 안 보입니다

갤러리 넘버 치면 다운은 되긴 하는데 검색기에선 안 보이네요

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/752#issuecomment-484909383
