### ISSUE TITLE
만화가 일부 다운로드 되지 않습니다.

### ISSUE THREAD

**Issue by dukr28ejd** [KurtBestor/Hitomi-Downloader-issues#1066]
마나모아 친구게임 - 읽기에서 67화까지 읽은 후 invalid
데드 튜브 49~50-2화 까지 읽지 못하고 invalid

이렇게 뜨는데 SNI우회 DPI우회 번갈아가면서도 해보고 이것저것 해봤는데 안되네요.

**Comment by KurtBestor** [comment]
![image](https://user-images.githubusercontent.com/14768120/62414572-45723280-b658-11e9-8cd6-55c69513c238.png)
테스트 해봤는데 잘 되네요. 해당 작업 `마우스 우 클릭` - `정보... (I)` 눌러서 나온 내용 보여주세요.

**Comment by dukr28ejd** [comment]
확인했습니다. 며칠간 그 부분만 먹통이었다가 해당 페이지 내에서 오류가 고쳐진 것 같습니다. 감사합니다.
