### ISSUE TITLE
범위 검색시 내림차순이 안되는 버그

### ISSUE THREAD

**Issue by mnkycj** [KurtBestor/Hitomi-Downloader-issues#1067]
![이미지 001](https://user-images.githubusercontent.com/53565399/62336455-56f9f400-b50b-11e9-8c58-963595045a1e.png)
![이미지 003](https://user-images.githubusercontent.com/53565399/62335927-ddf99d00-b508-11e9-8125-cefd34c86a99.png)

간단검색으로도 버그가 발생하는걸 확인함

범위 검색으로 검색하면 예를 들어 100 99 98 97 ---- 이렇게 되는게 정상인데

76 55 100 98 97 ---- 이런식으로 내림차순이 무시되는 경우가 있음 

백업중인데 갤러리 번호가 섞이면 돌이킬수가 없음

**Comment by KurtBestor** [comment]
히토미 자체에서 번호 순서가 달라서 그래요.
