### ISSUE TITLE
소설가가 되자 파일명을 대체 어떻게 바꾸나요??

### ISSUE THREAD

**Issue by homagood** [KurtBestor/Hitomi-Downloader-issues#1068]
https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/863
여기 나온대로 하라 하셨는데 전혀 병합이 안 되네요...
어찌어찌 옵션 들가서 바꾼 파일명으로 다운받으려 해도 고집스럽게 원래 설정대로 나오는데... 어떻게 해야 할지 모르겠습니다. 좀 더 찾아보니 일부 사이트 외에는 파일명 설정을 따르지 않고 다운이 된다고 하는데 이럴 때는 어떻게 해야 하나요??

**Comment by KurtBestor** [comment]
소설가가 되자 폴더명은 못 바꿔요.

**Comment by homagood** [comment]
음... 그럼 https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/993 이건 어떻게 해결해야하나요 ㅠㅠ

**Comment by KurtBestor** [comment]
해당 작업 `마우스 우 클릭` - `정보... (I)` 눌러서 나온 내용 보여주세요.
