### ISSUE TITLE
유투브 영상을 리스트로 받을수는 없을까요?

### ISSUE THREAD

**Issue by catheart123** [KurtBestor/Hitomi-Downloader-issues#107]
항상 쩡받는 프로그램으로 잘 쓰고 있습니다. 개발자님께 감사드립니다.

다름아니라, 유투브 영상 받기가 되던데, 이게 단일파일만 가능하고 리스트로 받기는 안되더라고요.

그래서 리스트로 받을수 있게 업그레이드? 할수 없을까 해서 글 남겨봅니다.

비슷한 프로그램은 https://www.4kdownload.com/ko/howto/howto-download-youtube-playlist

입니다.

**Comment by KurtBestor** [comment]
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

테스트 부탁드려요.

**Comment by catheart123** [comment]
잘 받아집니다. ㅜ 정말 감사합니다.
