### ISSUE TITLE
연속된 갤러리 넘버 다운로드 기능 넣어주실수 있으신가요?

### ISSUE THREAD

**Issue by matthewsongdev** [KurtBestor/Hitomi-Downloader-issues#1070]
현재 갤러리 넘버로 받으려면 10 11 12 13 이런식으로 한 숫자씩 쳐서 받아야 하는데 10-100 이렇게 하이픈기호를 붙여서 연속된 숫자에 해당하는 갤러리를 모조리 한꺼번에 받을수는 없는지 건의드립니다.

**Comment by KurtBestor** [comment]
검색기 `검색 범위`에 입력해서 검색한다음 다운로드하세요.
