### ISSUE TITLE
사이트 추가 건의 드립니다 - zh.hentai-image.com 및 hentai-comic.com

### ISSUE THREAD

**Issue by nikin78** [KurtBestor/Hitomi-Downloader-issues#1073]
익헨이 터진 이후로, 태그나 저작권 문제로 삭제된 작품들 대부분이 히토미 다운로더에서도 검색이 안되거나, 다운로드가 불가능해졌습니다.

그러다 우연히 구글링으로 다음과 같은 사이트를 찾았는데, 히토미나 이헨에는 없는 자료들이 잔존되어 있더군요. 

https://zh.hentai-image.com   (zh헨타이 사이트 주소)
https://hentai-comic.com/   (헨타이 코믹 주소)

동일한 사이트로, 접속 경로에 따라 주소가 조금 달라지는 것 같습니다.

[예시]
https://e-hentaidb.com/?id=202025
익펀 및 DB상으로 삭제된 특정 작품. 다운로더에서 제목 검색으로도 탐색 불가

https://(zh 헨타이 사이트 주소)/image/tiramisu-suki-darake-obasan-to-yari-makuri-eroero-dkyo-sei-katsu-tiramisu-/
위와 같이 zh.hentai-image hentai-comic 사이트에선 열람 가능.

기존 미러링 사이트나 이헨과는 사이트 방식이 다른 듯 보여 가능할 지는 모르겠으나, 가능하다면 주소 입력으로 이 두 사이트에서도 자료 다운로드가 가능하게끔 기능을 추가하시면 좋을 것 같습니다.

**Comment by yttrium11** [comment]
익헨 부활함

**Comment by nikin78** [comment]
익헨 부활 확인했습니다
여전히 검색 안되는 자료들은 다운할 방도가 없지만요...

**Comment by KurtBestor** [comment]
익헨 주소 넣으면 다운로드해요.
