### ISSUE TITLE
익헨다운받을 시 이름옵션 관련 문의

### ISSUE THREAD

**Issue by de12** [KurtBestor/Hitomi-Downloader-issues#1074]
1. 익헨에서 받을 때 익헨에 적혀진 이름 그대로 받을 수 있는 방법이 없을까요?
현재 지원중인 옵션으로 해서 받을 경우 
[artist][group][series] title [lang], 코미케 번호나 번역팀등?이 표기 되지 않아서요 ㅠㅠ

2. 이미지 저장될 시 규칙성을 적용할 수 있을까요? 경험상 1부터 저장이 되거나, 자릿수 맞춰서 01부터 되는 경우 등 있는데 이런 부분도 혹시 옵션적용 가능할까요?

**Comment by KurtBestor** [comment]
1. `옵션` - `설정` - `히토미 / E-Hentai / ExHentai / 히요비 설정` - `서버` 를 `수동`, `E-Hentai / ExHentai Server` 로 바꿔주세요.
1. `옵션` - `설정` - `히토미 / E-Hentai / ExHentai / 히요비 설정` - `파일명 형식` 을 `숫자` 로 바꿔주세요.

**Comment by de12** [comment]
감사합니다! 1번 설정 후, title만 하니 익헨 올라온 제목 그대로 다운받아지네요 감사합니다.
