### ISSUE TITLE
안녕하세요. 쓰레드는 1로 해놔도 수학프로그램이라며, 방금 1시간 사이트 정지먹었습니다.

### ISSUE THREAD

**Issue by exist90** [KurtBestor/Hitomi-Downloader-issues#1075]
안녕하세요. 쓰레드는 1로 해놔도 수학프로그램이라며, 방금 1시간 사이트 정지먹었습니다.
1달전에는 쓰레드2로 해놔서 사용했는데 1시간 정지, 1일 정지, 3일 정지, 7일정지 당해서

요번에는 쓰레드 1로 해놓고 사용했는데, 1시간 정지 먹었습니다...

+추가
 쓰레드 1개로 사용하다가 수학프로그램 감지되었다고 또  1일 정지 먹었습니다.

밴 안당하시는분들 쓰레드 말고 다른 설정 뭐 하셨나요?

**Comment by KurtBestor** [comment]
해당 작업 `마우스 우 클릭` - `정보... (I)` 눌러서 나온 내용 보여주세요.
