### ISSUE TITLE
저장 폴더명 히토미 아티스트명이 없고 그룹명은 있을경우

### ISSUE THREAD

**Issue by ansrhkd000** [KurtBestor/Hitomi-Downloader-issues#1076]
폴더명 현재 이렇게 사용중입니다.
[artist] title (id)

하지만 그룹명은 있는데 아티스트 명은 없거나
아티스트 명은 있는데 그룹명이 없거나 하는 경우가 있습니다

아티스트명이 없는 경우 현재 [N/A] 타이틀 (id) 이렇게 저장되는데요

이 경우 아티스트명 대신에 그룹명이 들어가게 할 수는 없을까요?

[artist?artist:group] 이런식으로 동작할 수 있으면 좋지 않을까 싶습니다

**Comment by KurtBestor** [comment]
현재도 작가명이 없고 그룹명만 있는 경우엔 그룹명이 대신 들어가요.

**Comment by ansrhkd000** [comment]
아 그러면 N / A 로 저장되는 경우는 둘 다 없는 경우였나보군요 감사합니다
