### ISSUE TITLE
브라우저 다운로드 관련 문의 및 건의

### ISSUE THREAD

**Issue by nikin78** [KurtBestor/Hitomi-Downloader-issues#1077]
이헨이나 히토미에서 검색 안되는 자료들을 익헨에서 받으려면 크레딧을 소모하거나 갤러리 링크를 복사해 본 다운로더로 다운로드 받아야 합니다.

하지만 많은 양의 자료를 받고자 하면 후자의 경우 링크를 하나씩 일일히 다운로더로 복붙해야 하는 불편함이 있습니다.

https://blog.naver.com/PostView.nhn?blogId=wlswls5849&logNo=221175713166&categoryNo=7&parentCategoryNo=0&viewDate=&currentPage=1&postListTopCurrentPage=1&from=postView

위 링크에서 소개된 프로그램이 본 다운로더의 구버전인지는 모르겠으나, 

위와 같은 경우 스크립트를 실행시켜주는 크롬 확장 프로그램과 유저 스크립트를 이용해 해당 갤러리 자료를 바로 다운로드 가능했던 걸로 압니다.

혹시 본 다운로더의 경우 위와 같은 방식처럼 브라우저와 다운로더를 연동해 링크 복붙 없이 다운로드가 가능하게 할 수 있는 유저 스크립트나 기능 추가를 하실 의향이 있으신 지 문의 드립니다.

예를 들어, 본인이 열람하고자 하는 익헨, 이헨 등의 사이트 갤러리가 나타나 있는 경우, 갤러리 페이지 링크를 직접 복사할 필요 없이 특정 액션만으로 바로 다운로더로 해당 링크가 넘어가 다운로드가 가능하게끔 하게요.

**Comment by KurtBestor** [comment]
`옵션` - `클립보드에서 자동 추가` 를 키세요.
