### ISSUE TITLE
또 여러가지 생각난 게 있어서 건의해요

### ISSUE THREAD

**Issue by wooeorbs** [KurtBestor/Hitomi-Downloader-issues#1078]
https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/1049
여기 못본 것 같아서 한번 봐주세요. Kuluin님이 말씀하신 것처럼 하는 것이 어떨까요.

추가로 말씀드릴게
첫번째로 그 다운받은거 초록색으로 체크표시 뜨잖아요
그런데 저장폴더 내에 받은 것을 정리해서 따로 폴더에 넣으면 없어지잖아요.
저장폴더 내에 있는 모든 폴더도 다운받은 것으로 표시하거나 체크리스트처럼 폴더를 추가하는 식으로 하는게 어떨까요.

두번째로 중복제거해도 자잘한 중복이 남잖아요. 그러면 더이상 검색기에 안뜨게 하는 것도 어떨까요? 그 중복이 필요하면 작가 또는 그룹으로 중복 제거한 것을 풀고요.

세번째로 북마크한 게 매우 많으면 더이상 못보잖아요. 1/2페이지로 해놓던지 하고 그걸 2페이지에서 작가 골랐으면 다시 작가로 갈 때 2페이지로 최근에 기억한다든지.. 아니면 A~Z, 0~9 이런 식으로 정렬하고 YD를 보고싶으면 Y로 가서 보고
예를 들어서
작가>A
          B
          C>C~하고 C가 많으면 1/2페이지 식으로 하고요.

또 건의할게 있으면 올게요 ㅎㅎ

**Comment by KurtBestor** [comment]
봤어요. 새로 이슈 만들지 마시고 그 쪽에 달아주세요.
