### ISSUE TITLE
트위터 다운로드 시 파일이름 저장 양식을 선택할 수 없을까요?

### ISSUE THREAD

**Issue by sky112475** [KurtBestor/Hitomi-Downloader-issues#1079]
지금 현재 트위터 다운로드는

https://twitter.com/(사용자명)/status/(게시글번호)
의 URL이 있다면

[트윗작성날짜] (게시글번호)_p(사진번호 : 0~3).(확장자)

의 형식으로 저장됩니다.

그런데  아시다시피 트위터는 트윗에서는 이미지를 압축/축소해서 보여주고 원본이미지는 url을 살짝 변경해야 보이는 등 이래저래 불편한점이 많습니다.

예를들어 트위터에 첨부된 이미지에서 우클릭을 한 뒤 '새탭에서 이미지 열기'

를 클릭하면
https://pbs.twimg.com/media/(특정 해쉬값).jpg

이라는 URL이 나오고
확장자 뒤에 :orig 라는 글자를 붙여주면 비로소 압축되지 않은 이미지가 나오는 방식이지요.

여기에서 이미지를 저장하려 시도하면 파일이름이 자동으로 (특정 해쉬값).jpg_orig 혹은 .png_orig가 지정되었는데요

여기서 뒷부분의 _orig를 지우거나, 이 과정조차 생략해주는 크롬 확장프로그램을 사용해서 저장하면 파일이름은 자연스레 저 해쉬값을 따르게 되었습니다.

이 습관은 나중에 파일 원 주인을 추적할때 매우 편리하게 이용되어서 히토미다운로더로 다운받을때도 이것을 같이 긁을 수 있으면 좋겠다는 생각을 했는데요

이렇게 파일 네이밍 양식 추가 혹은 수정이 가능할까요?

읽어주셔서 감사합니다.

**Comment by KurtBestor** [comment]
해시값보다 게시글 번호로 추적하는 게 쉽지 않나요?

**Comment by sky112475** [comment]
저도 그렇게 생각했는데, 업로더가 사진을 삭제해버리는 경우가 발생하면 게시글번호로 접근했을 때 없는 자료라고 나오지만 해쉬값을 직접 URL에 쳐서 들어가면 얼마간 보존이 되는경우가 있더라구요. 이게 은근히 유용한 경우가 있어서 해쉬값을 파일이름으로 저장하는 습관이 들었습니다.

**Comment by KurtBestor** [comment]
사진은 이미 저장되어있는데 사진 자체를 봐야할 필요가 있나요?

**Comment by sky112475** [comment]
보통은 필요없는데 가끔가다 파일을 깨먹거나 실수해서 복구프로그램 등을 돌리는 경우에 파일은 복구안되고 파일 이름만 남는 경우에 유용하게 사용한적이 있습니다.
