### ISSUE TITLE
MTP 형식의 마운트 디바이스에서 목록을 가져오는 기능을 추가할 수 있나요?

### ISSUE THREAD

**Issue by aria1th** [KurtBestor/Hitomi-Downloader-issues#108]
드라이브의 경우에는 논리적 드라이브라서 파이썬의 win32api 에서 논리 드라이브 확인 함수로 로드해서 목록을 가져올 수 있는데, MTP의 경우에는 그렇게 txt를 짜는 보조스크립트를 파이썬으로 구현하는게 힘드네요

혹시 개발자 기능처럼 MTP로 마운트된 디바이스들의 디렉토리 구조를 따와서 번호들을 추출하는 기능을 추가하실 수 있나요?

대략적인 개요가

최상위 폴더에 속한 디렉토리 구조에서 폴더 이름들만 모두 로드 -> 조건에 맞는 이름이면 번호를 추출 -> txt로 저장 (또는 폴더를 새로 생성)

인데 논리드라이브에만 되고 MTP에서 안되서 도움을 요청드립니다

**Comment by KurtBestor** [comment]
제 폰이 MTP 지원이 안돼서 해드릴 수가 없네요. 죄송합니다.
