### ISSUE TITLE
파일명 글자 길이 제한이 있나요?

### ISSUE THREAD

**Issue by de12** [KurtBestor/Hitomi-Downloader-issues#1082]
옵션 - 설정 - 히토미 / E-Hentai / ExHentai / 히요비 설정 - 서버 를 수동, E-Hentai / ExHentai Server 로 바꿔주세요.

해당옵션으로 익헨 다운을 하게 되면 폴더명이 띄워쓰기 등 포함해서 100자까지만 되는데, 글자수를 좀 더 늘리는 방법이 없을까요?

**Comment by KurtBestor** [comment]
없어요. 참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/272
