### ISSUE TITLE
애니메이션 사이트 추가 문의

### ISSUE THREAD

**Issue by sz1ah2** [KurtBestor/Hitomi-Downloader-issues#1083]
http://hentai.animeholics.org/
https://members.hanime.tv/
https://muchohentai.com/

사이트 목록을 보니 애니메이션 사이트가 없던데
혹시 가능하다면 해주시면 감사하겠습니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

[hanime.tv](https://hanime.tv) 만 추가했어요.

**Comment by sz1ah2** [comment]
아주 잘 됩니다 감사합니다 ^^
