### ISSUE TITLE
익헨, 히요비 다운로드 안되는 현상 #1080 증상 동일

### ISSUE THREAD

**Issue by matthewsongdev** [KurtBestor/Hitomi-Downloader-issues#1085]
정보창 내역입니다.

[info.txt](https://github.com/KurtBestor/Hitomi-Downloader-issues/files/3467423/info.txt)

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/900#issuecomment-498958770
