### ISSUE TITLE
다운로더 내 필터 기능에 특정 사이트 필터기능도 추가 가능할까요?

### ISSUE THREAD

**Issue by mirusu400** [KurtBestor/Hitomi-Downloader-issues#1086]
현재 필터에는 단순히 이름만 검색이 가능합니다.
물론 정렬에서 사이트 순으로 정렬이 가능하지만 사이트 순 정렬과 이름 검색만으론 가끔 검색이 힘든 경우도 있습니다
EH 에서 긁어온 이미지들만 보여준다던가 트위터에서 긁어온 이미지만 보여준다던가 하는 기능이 추가된다면 좋을듯 싶습니다

**Comment by KurtBestor** [comment]
`도움말` - `사용법... (F1)` - `다운로더 목록 필터링` 을 참고해주세요.

**Comment by mirusu400** [comment]
이미 있는기능이었네요 죄송합니다..
