### ISSUE TITLE
Pinterest 핀터레스트 다운로드 안됨.

### ISSUE THREAD

**Issue by GH6** [KurtBestor/Hitomi-Downloader-issues#1087]
사용자이름／보드이름

version: 2.6d
platform: Windows-7-6.1.7601-SP1
gal_num: 주소
dir: hitomi_downloaded_pinter\사용자이름／보드이름
zip: 
type: pinter
artist: None
url: 주소
valid: False
done: True
range: None
range_p: None
single: False
time: 1565070259.57 (Aug 6)
tags: []
goodbyedpi: False
lock: False

[Gallery]
None

[File Names]
[0001] hitomi_downloaded_pinter\사용자이름／보드이름\lazy
[0002] hitomi_downloaded_pinter\사용자이름／보드이름\lazy

[URLs]
[0001] LazyUrl(https://pinterest.com/pin/주소/) ---> https://pinterest.com/pin/주소/
[0002] LazyUrl(https://pinterest.com/pin/주소/) ---> https://pinterest.com/pin/주소/

[Messages]
valid=False 1
done : https://www.pinterest.co.kr/사용자이름/보드이름/

하나만 그러는 게 아니라 전부 다 그러니 사용자이름과 보드이름은 가렸습니다.
주소입력하고 나면 크롬이 켜집니다. 뭐 원격어쩌구.. 그러고요. 프로그램에서는 사진을 세고 있습니다. 전체 사진이 표시가 되고 나면 이제 받아져야 하는데 그러지를 않고 주황색으로 변하면서 멈춥니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by GH6** [comment]
Invalid : [pinter] https://www.pinterest.com / bsheppard0097

version: 2.6d
platform: Windows-7-6.1.7601-SP1
gal_num: https://www.pinterest.com/bsheppard0097
dir: 
zip: 
type: pinter
artist: None
url: https://www.pinterest.com/bsheppard0097
valid: False
done: False
range: None
range_p: None
single: True
time: 1565194319.37 (Aug 8)
tags: []
goodbyedpi: True
lock: False


[Gallery]
None


[File Names]



[URLs]



[Messages]
stop
Traceback (most recent call last):
File "utils", line 425, in __init__
File "pinter_downloader", line 25, in init
AttributeError: 'NoneType' object has no attribute 'groups'

Fail: pinter

stop
done : https://www.pinterest.com/bsheppard0097

1. 답댓 주신 링크로는 아예 시도조차 안됩니다. 붉은색 글씨로 invalid : [printer] Https://www.pinterest.com / bsheppard0097 이렇게 나와요.

2. 혹시 보드만 따로는 안되나요?

**Comment by KurtBestor** [comment]
보드만 지원해요. 다음과 같이 보드 주소를 입력해주세요: https://www.pinterest.co.kr/bsheppard0097/nelson-and-royal-navy/

**Comment by GH6** [comment]
아, 문제가 뭔지 알겠습니다.
말슴해주신 링크는 잘 작동합니다.
근데 보드 이름이 한글이면 주소가 이렇게 됩니다. /%EA%B2
그래서 인식을 못하고 있는 것 같아요.

**Comment by GH6** [comment]
그리고 보드안에 또 다른 보드로 분류되어 있는 경우도 있는데 그건 인식을 못하는 것 같습니다.
예를 들어서 /사용자이름/보드이름/또다른보드이름 이렇게 되어 있는 경우인데 /보드이름 까지만 인식하는 것 같아요. 
/%EA%B2 이 문제는 방금 확인해봤는데 주소를 직접 복사하지 않고 한글로 일일이 입력해주면 잘됩니다.

**Comment by KurtBestor** [comment]
해당 주소 알려주세요.

**Comment by GH6** [comment]
보드 안의 또다른 보드 : 
-https://www.pinterest.com/pgh74705002/lego/bionicle/
"/bionicle" 인식안됨
한글 일일이 입력 :
-https://www.pinterest.com/ss0135b/%EC%98%88%EC%88%A0/
-https://www.pinterest.com/ss0135b/예술/
초성 인식 :
-https://www.pinterest.com/a01022112821/%E1%84%86%E1%84%85/
-https://www.pinterest.com/a01022112821/ㅁㄹ/

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

https://www.pinterest.com/pgh74705002/lego/bionicle/ 은 https://www.pinterest.co.kr/pgh74705002/lego/ 로 리다이렉트되네요.

한글 주소 입력은 해결했어요.
https://www.pinterest.co.kr/a01022112821/ㅁㄹ/ 은 잘못된 주소이고, https://www.pinterest.co.kr/a01022112821/ᄆᄅ/ 가 맞는 주소예요.

**Comment by GH6** [comment]
리다이렉트 되는 문제는 해결이 안된거죠?

**Comment by KurtBestor** [comment]
로그인 안 하면 리다이렉트되네요.

테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by GH6** [comment]
로그인이라는 건 프로그램에서의 로그인이죠?
설정에 pinterest 설정칸이 없는데 어떻게 하나요?

**Comment by KurtBestor** [comment]
그냥 인터넷 브라우저에서 볼 때 그래요.

프로그램에서 따로 로그인 필요 없어요.

**Comment by GH6** [comment]
우와 잘됩니다!
리다이렉트 문제도 없어요!

**Comment by GH6** [comment]
이제 마지막 질문만 하고 코멘트를 닫으렵니다.
지금까지의 테스트링크들은 차후의 패치에 적용이 되나요?

**Comment by KurtBestor** [comment]
넵
