### ISSUE TITLE
이 사이트도 추가해주시면 안될까요

### ISSUE THREAD

**Issue by painterer** [KurtBestor/Hitomi-Downloader-issues#1088]
http://www.11toon.com/
부탁드립니다

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/302

**Comment by painterer** [comment]
폐쇄돼었다는건가요?

**Comment by painterer** [comment]
도데체 뭘 어떻게하라는지 모르겠습니다일일툰 스크립트도 없고

**Comment by KurtBestor** [comment]
이미 예전에 다른 분이 요청한 적이 있으니 중복이라는 거예요.

**Comment by painterer** [comment]
그러면 추가는된건가요?

**Comment by KurtBestor** [comment]
아직이요
