### ISSUE TITLE
중복 이미지 찾기 기능 관련 문의

### ISSUE THREAD

**Issue by wlehd44** [KurtBestor/Hitomi-Downloader-issues#1090]
안녕하십니까. 평소에 이 프로그램으로 많은 혜택을 누리고 있는 1인입니다
다름이 아니라 중복된 이미지가 많다보니 엑셀 같은 곳에 옮긴 후 정리하면 서 진행하려합니다
중복된 이미지를 단일 선택 후 Ctrl C / Ctrl V 가능한 데, 복수 선택 후 Ctrl C / Ctrl V가 안되서 진행하는 데 있어 애로사항이 생깁니다. 위가 같이 복수 선택 후 Ctrl C / Ctrl V 가능하게 해주실 수 있을 까요?

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by wlehd44** [comment]
일단 제가 생각하던 기능은 안됩니다

![1](https://user-images.githubusercontent.com/48654593/63212091-972bba00-c13a-11e9-8c27-acad474c7272.PNG)

위 사진 처럼 두개를 선택 후 복사 하면 붙혀넣기를 하면

![2](https://user-images.githubusercontent.com/48654593/63212103-a7dc3000-c13a-11e9-8a3f-f15f3b2733c9.PNG)

위사진같이 나옵니다


제가 원하는 결과값은  아래의 사진처럼 나오는 것입니다
![3](https://user-images.githubusercontent.com/48654593/63212114-b75b7900-c13a-11e9-9dc9-8251b372fe91.PNG)


아니면 위 같은 방법이 안되거나 힘드시면
 중복 이미지에 대한 결과 항목들을 TXT 파일이나 엑셀 파일 등으로 따로 뺄 수 있겠끔 해주실 수 있으신가요?

**Comment by KurtBestor** [comment]
다음과 같이 선택하고 복사해서:
![image](https://user-images.githubusercontent.com/14768120/63212727-b8dd6f00-c143-11e9-8719-6d75b7d51547.png)

엑셀에 붙여넣으면 돼요:
![image](https://user-images.githubusercontent.com/14768120/63212731-c692f480-c143-11e9-8ccb-59bec12cad73.png)

테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by wlehd44** [comment]
잘 됩니다 정말 감사합니다 ^^
