### ISSUE TITLE
중복 이미지 찾기 관련 건의사항.

### ISSUE THREAD

**Issue by kenasis428** [KurtBestor/Hitomi-Downloader-issues#1091]
프로그램 사용한지 2달쯤 된 사용자입니다 .

특히 중복 이미지 파일 찾기를 많이 사용하는데요.

이게 중복 이미지를 찾다가 보면 분명 다른 이미지인데 
중복 이미지라면서 검색되는 경우가 있습니다.

혹시 그렇게 검색된 이미지를 제외 시켜주는 목록에 추가하여
다음에 검색할 시 검색이 안되게 해주는 목록을 추가 가능 한지 건의 합니다.

**Comment by KurtBestor** [comment]
다른 이미지인데 오류로 같은 이미지라고 인식되는 이미지 알려주시면 분석해볼게요.

**Comment by kenasis428** [comment]
일단 ..사진크기 똑같고 비트같고 용량이 바이트까지 똑같아요 ..
![2564556](https://user-images.githubusercontent.com/53850082/62716498-3961e880-ba3d-11e9-8a5c-6c618ccf9ac4.png)
![2564558](https://user-images.githubusercontent.com/53850082/62716499-3961e880-ba3d-11e9-8e1a-fe98011f4395.png)
![2564559](https://user-images.githubusercontent.com/53850082/62716500-3961e880-ba3d-11e9-827d-1279572be3b3.png)
![2564560](https://user-images.githubusercontent.com/53850082/62716502-3961e880-ba3d-11e9-9702-9964c6102954.png)

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by kenasis428** [comment]
확인 결과. 다른이미지인데 중복이미지 라고 안뜨네요 .. 나중에 시간날떄 한 이미지 70만장 되거든요 ? 그거 하는데 약 2시간 걸리는데 그거 해보고 다시 알려드릴께요

**Comment by kenasis428** [comment]
이미지 83만장으로 확인결과 .. CG,수집형 모바일 게임 이미지 같은거 미묘하게 다른 이미지 들이 검색되어 뜨네요 .

**Comment by KurtBestor** [comment]
조금 더 자세히 검사하느라 시간이 더 걸릴 거예요. 중복이라고 잘못 검색되는 파일 주시면 분석해볼게요.

**Comment by kenasis428** [comment]
일단 이미지 70개 185MB인데 ... 이미지 어떻게 보내드리면 될까요 ?

**Comment by KurtBestor** [comment]
분할압축해서 여기에 올려주세요.

**Comment by kenasis428** [comment]
19금 CG 있는데 올려도 되나요 ?

**Comment by kenasis428** [comment]
[새 폴더 (4).zip](https://github.com/KurtBestor/Hitomi-Downloader-issues/files/3536853/4.zip)
[새 폴더 (5).zip](https://github.com/KurtBestor/Hitomi-Downloader-issues/files/3536854/5.zip)
[새 폴더 (6).zip](https://github.com/KurtBestor/Hitomi-Downloader-issues/files/3536855/6.zip)
[새 폴더 (7).zip](https://github.com/KurtBestor/Hitomi-Downloader-issues/files/3536856/7.zip)
[새 폴더 (8).zip](https://github.com/KurtBestor/Hitomi-Downloader-issues/files/3536857/8.zip)
[새 폴더 (9).zip](https://github.com/KurtBestor/Hitomi-Downloader-issues/files/3536858/9.zip)
[새 폴더 (10).zip](https://github.com/KurtBestor/Hitomi-Downloader-issues/files/3536859/10.zip)
[새 폴더.zip](https://github.com/KurtBestor/Hitomi-Downloader-issues/files/3536860/default.zip)
[새 폴더 (2).zip](https://github.com/KurtBestor/Hitomi-Downloader-issues/files/3536861/2.zip)
[새 폴더 (3).zip](https://github.com/KurtBestor/Hitomi-Downloader-issues/files/3536862/3.zip)

분할 압축으로 안올라가서 그냥 폴더 여러개만들어서 수동으로 분할 햇습니다.. 
올린 파일 문제될시 지워주세요 ...

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by kenasis428** [comment]
테스트 완 .. 이미지 양 103만장 .. 시간 14시간 . 중복 없습니다.
