### ISSUE TITLE
유저간 중복신고는 어떨런지

### ISSUE THREAD

**Issue by Kuluin** [KurtBestor/Hitomi-Downloader-issues#1092]
히토미등에 올라오는 이름은 다르지만 이미지가 같은 중복데이터를 일일히 거르기 번거로우니 

프로그램내에서 사용유저가 중복신고 요청을 하면 

다음 업데이트등에 확인하여 중복자료는 중복마크등을 띄우는것도 괜찮을것 같습니다.

한사람일일히 작업하는것보다 효율도 좋고 

이후에 다운 받는 사람들도 관리하기 쉬워질것 같습니다.

추가로 태그도 같이 붙일수 있으면 더 좋을것 같구요

**Comment by KurtBestor** [comment]
익헨에 직접 중복 자료라고 신고하는 게 낫지 않을까요?
