### ISSUE TITLE
프로그램 실행시 잠깐동안 멈춥니다

### ISSUE THREAD

**Issue by kiu2475** [KurtBestor/Hitomi-Downloader-issues#1097]
버전은 2.6d 입니다
예전 버전에서는 프로그램 실행한 직후에 아무 이상없이 동작 했었는데
지금은 실행시 몇초동안 멈춤 상태로 있다가 이후에 정상동작 됩니다.

그리고 GUI제작 하실때 어떤 프레임워크 썼는지 알수 있을까요?
파이썬 공부하는중에 궁금해서 여쭙니다.

**Comment by KurtBestor** [comment]
언제 멈추나요?
1. 로딩 화면
2. 목록 불러오기 전
3. 목록 불러오는 중
4. 목록 불러온 후

GUI는 [Qt](https://www.qt.io/) 썼어요.

**Comment by kiu2475** [comment]
목록 불러온 후 입니다

**Comment by KurtBestor** [comment]
[v2.6c](https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/v2.6c) 에선 안 그런가요?

**Comment by kiu2475** [comment]
v2.6c 에서도 그러네요

**Comment by KurtBestor** [comment]
멈추지 않는 가장 최신 버전이 뭔가요?
