### ISSUE TITLE
유튜브 60fps 영상 다운 불가

### ISSUE THREAD

**Issue by listandtag** [KurtBestor/Hitomi-Downloader-issues#1098]
https://www.youtube.com/watch?v=0823bhhAIc8

30프레임으로만 다운이 되네요....또르륵....ㅠ

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by listandtag** [comment]
乃乃 ^~^

혹시 기프티콘 같은 거 드리고 사이트 추가 가능할까요?

**Comment by KurtBestor** [comment]
어떤 사이트인가요?

**Comment by listandtag** [comment]
예-전에도 한 번 건의한 적 있는데 후순위로 밀렸는지 감감 무소식이라...
iwara.tv
ecchi.iwara.tv
MMD영상만 올라오는 사이트입니다.
히토미 다운로더가 지원하는 사이트들은 파밍이 정말 편리해져서요.

**Comment by KurtBestor** [comment]
대부분 유튜브 영상 걸어놓은 것 같은데 필요한가요?

**Comment by listandtag** [comment]
R-18 미만 영상들은 유튜브 겸업해서 유튜브 링크로 대체하는 게 꽤 많지만,
성인 영상들은 이와라 자체 업로드입니다. 이게 중요ㅠ

예)
https://ecchi.iwara.tv/users/strawberryai

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview
후원은 패트론에서 해주세요: https://www.patreon.com/join/KurtBestor

**Comment by listandtag** [comment]
이와라 잘 되네용~
세상에 그림까지 그리셨다니....구독했읍니다.

**Comment by dcie** [comment]
오래전에 건의드린건데 추가해 주셔서 감사합니다.

다만 아쉬운점이 2가지 있습니다. 

1. 로그인 기능의 부재 

픽시브처럼 로그인 기능을 추가해주셔서 프렌드 자료도 받을수 있으면

좋을것 같습니다.  

2. 동영상 올린 게시자 비디오를 한꺼번에 받을수 있는 기능 추가 

유튜브 다운받을때랑 비슷하게 게시자가 올린 비디오를 

한꺼번에 받을수 있는 기능도 추가해 주시면 좋을것 같습니다.
