### ISSUE TITLE
이거 왜 랜섬웨어 된다고하나요 ㅠㅡㅠ

### ISSUE THREAD

**Issue by rabirabin** [KurtBestor/Hitomi-Downloader-issues#11]
![1514384088](https://user-images.githubusercontent.com/34975196/34458872-51e88f7a-ee25-11e7-8dfd-1b04c47f366f.png)

**Comment by rabirabin** [comment]
기존 1.7쓰고있었는데 1.9 올리니까 켤때마다 저러네요

**Comment by rabirabin** [comment]
1.7은 안그런데 1.9만그래서...

**Comment by KurtBestor** [comment]
v1.9e 맞나요?

**Comment by rabirabin** [comment]
네 1.7b 에서 귀찮아서 업데이트안하다가 가끔씩 완전히 안받아지길래 업데이트하면 나아질것같아서 1.9e다운받고 실행하니까 실행할때마다 뜨내욤...

**Comment by KurtBestor** [comment]
![ransom](https://user-images.githubusercontent.com/14768120/34460327-400f0dc8-ee4e-11e7-9607-a7ed70c8949a.png)
방금 검사 해봤는데 이렇게 뜨는데요.

여기에 파일 넣고 나오는 결과값 알려주실 수 있나요?:
https://emn178.github.io/online-tools/sha256_checksum.html

**Comment by rabirabin** [comment]
c92b2dd2c259dd28cc41fff8dfa302134b1bd473b1b6e938b2227d83df67149f 
요ㅛ렇게 떠욤!!

**Comment by KurtBestor** [comment]
프로그램이 켜지긴 하나요?

**Comment by rabirabin** [comment]
네 켜지긴켜져욤
