### ISSUE TITLE
히토미 태그 필터링 기능

### ISSUE THREAD

**Issue by ddt5244** [KurtBestor/Hitomi-Downloader-issues#110]
히토미 작품 검색할 때 자료중 내가 원치않는 태그가 있으면 그 작품를 안보이도록 필터링 하는 기능을 추가해주셨으면 합니다. 
예로 cheating 이라는 태그가 붙어있는 작품을 보고싶지 않다면 필터링을 통해 검색된 작품중 cheating이라는 태그가 붙은 작품은 안보이도록 해주셨으면 좋겠습니다

**Comment by KurtBestor** [comment]
도움말 - 사용법을 참고해주세요.
Duplicate of #99

**Comment by ddt5244** [comment]
저 제가 멍청해서 그런지 사용법 봐도 잘 모르겠는데 혹시 태그에 - 붙이라는 건가요?

**Comment by KurtBestor** [comment]
태그 A를 검색하는데 B, C를 제외하고 싶으면 다음과 같이 검색하시면 됩니다:
```
A, -B, -C
```

**Comment by ddt5244** [comment]
자꾸 질문해서 죄송한데 그냥 전체에서 B와 C를 제외하려면 어떻게 하나요? 방금 -붙여서 해봤는데 아무런 효과가 없었습니다.

**Comment by KurtBestor** [comment]
```
-B, -C
```

**Comment by ddt5244** [comment]
아 이제 알았습니다 답변 정말 감사합니다.

**Comment by KurtBestor** [comment]
@RaceDriverMIKU 

https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

전역 필터링 기능 추가했습니다.
테스트 부탁드려요. 옵션 - 설정 - 히토미에서 설정하실 수 있어요.
근데 좀 지저분해진 것 같기도 해서 다른 좋은 방법 있으면 알려주세요.
