### ISSUE TITLE
[REQUEST] Pause button for downloads

### ISSUE THREAD

**Issue by dhimanAdhikari** [KurtBestor/Hitomi-Downloader-issues#1101]
I don't know if this has been opened since I can't read your language, a pause button for individual downloads beside the "Open Folder" icon would be nice.

Also, translations required on some parts of the app, especially the "How to use" and "Select chapters/pages & Download" sections.

Thanks!

**Comment by KurtBestor** [comment]
Try the test version: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview
