### ISSUE TITLE
스크립트로 사이트지원이 가능하다면 요청드려봅니다.

### ISSUE THREAD

**Issue by tdi2020** [KurtBestor/Hitomi-Downloader-issues#1102]
안녕하세요 선생님.  항상 업데이트 해주실때마다 잘 사용하고 있습니다.
혹시 http://dru.pl 사이트도 추가가 가능할까요? 
스크립트로 추가해주시는 걸 보고 혹시나 가능할까하고 건의드려봅니다.
항상 감사드립니다.

**Comment by tdi2020** [comment]
안녕하세요 선생님. 혹시 업데이트 되었으려나 들려보곤 하는데 워낙 바쁘실 줄로 압니다! 
그래서 혹시 향후에 스크립트로 추가 될 수 있을지 가능성이나..여부를 알수 있을까요? 
염치없지만 나름 고대하고 있는지라 궁금해 남겨봅니다. 환절기 건강 유의하시기 바랍니다.

**Comment by KurtBestor** [comment]
[여기](https://github.com/KurtBestor/Hitomi-Downloader-issues/wiki/Scripts)에서 받으세요.

**Comment by tdi2020** [comment]
헉 맙소사..감사합니다!ㅠㅠ 역시 갓갓 선생님... 우선 테스트 해보았는데 잘 작동되네요.

다만 현재는 작은 사이즈로만 다운로드가 되는 것 같습니다.

아래의 한 페이지를 예로들면,

▶A모델 페이지 예시
http://dru.pl/blog/alyssa-bennett-zmyslowe-czarne-body/285580/

접속후 최초 세로로 뜨는 이미지들은 
아래처럼 중화질 정도 사이즈의 미리보기입니다.

▶A사진 클릭 전 예시(중화질 - 800 x 1200)
http://dru.pl/blog/stuff/alyssa-bennett-zmyslowe-czarne-body/alyssa-bennett-black-bodysuit-naked-brunette-playboy-02-800x1200.jpg

그리고 중화질 사진을 클릭하면, 
아래처럼 큰 사이즈의 본래 이미지로 연결되는 형식입니다.

▶A사진 클릭 후 예시(고화질 - 1280 x 1920) 
http://dru.pl/blog/stuff/alyssa-bennett-zmyslowe-czarne-body/alyssa-bennett-black-bodysuit-naked-brunette-playboy-02.jpg

중화질이 아닌 클릭 후 큰 사이즈의 본래 이미지를 다운받을 수 있는 방법은 없을까요?
항상 감사드립니다.

**Comment by KurtBestor** [comment]
수정했어요: https://github.com/KurtBestor/Hitomi-Downloader-issues/wiki/Scripts

**Comment by tdi2020** [comment]
선생님 계좌로 도네이션은 안받으시나요? 
계좌로도 받으신다면 남겨주세요 미약하게나마 성의 보인 후 댓글 남기겠습니다.
정말 감사드립니다.

**Comment by KurtBestor** [comment]
후원은 [여기](https://patreon.com/KurtBestor)에서 받고있어요.

감사합니다.

**Comment by tdi2020** [comment]
안녕하세요 선생님! 작동하다가 갑자기 작동이 안되는데, 해결 가능할까요?

로그는 아래와 같습니다.

--------------------------------------------------------------------

Invalid: [dru] http://dru.pl / blog / heather-rene-smith / 1405 / 

version: 2.7b
platform: Windows-7-6.1.7601-SP1
gal_num: http://dru.pl/blog/heather-rene-smith/1405/
dir: 
zip: 
type: dru
artist: None
url: http://dru.pl/blog/heather-rene-smith/1405/
valid: False
done: True
range: None
range_p: None
single: False
time: 1570832540.51 (Oct 12)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False


[Gallery]
None


[File Names]



[URLs]



[Messages]
'NoneType' object has no attribute 'findAll'
stop
Traceback (most recent call last):
File "utils", line 708, in start
File "utils", line 754, in start_
File "dynamic_module_0", line 53, in read
AttributeError: 'NoneType' object has no attribute 'findAll'

Invalid: fail=True
EOT: http://dru.pl/blog/heather-rene-smith/1405/

**Comment by KurtBestor** [comment]
[스크립트](https://github.com/KurtBestor/Hitomi-Downloader-issues/wiki/Scripts) 다시 다운로드하고 [테스트 버전](https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview)에 넣어서 해보세요.
