### ISSUE TITLE
설정이 잘못되었습니다

### ISSUE THREAD

**Issue by lhj5426** [KurtBestor/Hitomi-Downloader-issues#1103]
![image](https://user-images.githubusercontent.com/30548000/62819684-f9a91700-bb8a-11e9-923a-39609534664e.png)
안녕하세요 개발자
최근 업데이트 된 새 버전
발견

사진에

이 위치에 텍스트가 잘못 배치되고 번역되지 않은 텍스트가 있습니다. 버그입니까, 아니면 새로운 설정입니까?

**Comment by KurtBestor** [comment]
번역 덜 된 부분 번역해주세요: [tr_dic.txt](https://github.com/KurtBestor/Hitomi-Downloader-issues/files/3488951/tr_dic.txt)

**Comment by lhj5426** [comment]
[tr_dic.txt](https://github.com/KurtBestor/Hitomi-Downloader-issues/files/3498492/tr_dic.txt)
 
안녕하세요

이미 번역

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by lhj5426** [comment]
아직 문제가 없습니다
 감사합니다
