### ISSUE TITLE
크흠...그...유튜브 크흠 성인 영상에서...

### ISSUE THREAD

**Issue by listandtag** [KurtBestor/Hitomi-Downloader-issues#1104]
https://www.youtube.com/watch?v=QM1EvGIFhPg

한국 지역에서 성인 인증을 거쳐야만 시청 가능한 영상을 받을 시,
영상, 음원은 다운로드가 되는데 타이틀을 못 따와서 _.mp4 로 다운되네요...

일반 영상은 타이틀 이상 없습니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by listandtag** [comment]
잘 됩니다! 60프레임까지 잘 되네요!
