### ISSUE TITLE
네트워크 레이턴시가 낮으면 아예 작동하지 않는 듯?

### ISSUE THREAD

**Issue by Laser-Cho** [KurtBestor/Hitomi-Downloader-issues#1105]
Traceback (most recent call last):
  File "hitomi_downloader_GUI.py", line 3532, in timer_event
NameError: global name 'ui_workInfo' is not defined

NAS에 올려놓고 사용하려 하니까, 
만화 파일 정보들 읽어 오는 것은 성공적으로 작동하나, 
다운로드가 일어나지 않습니다.

로그파일 열어보니 저런데, 네트워크 속도는 1기가급이지만, 이 안에서 레이턴시가 낮아서 타임아웃에 걸리는 모양입니다.

조금만 시간을 관대하게 주시면 어떨까요

**Comment by KurtBestor** [comment]
`Ctrl + Alt + C` 눌러서 콘솔 열고 다음 입력하고 `Enter` 누르세요:
```
downloader.TIMEOUT=1234;downloader.socket.setdefaulttimeout(downloader.TIMEOUT)
```
1234 부분에 원하는 타임아웃 시간 초단위로 넣어주세요.

**Comment by Laser-Cho** [comment]
> `Ctrl + Alt + C` 눌러서 콘솔 열고 다음 입력하고 `Enter` 누르세요:
> 
> ```
> downloader.TIMEOUT=1234;downloader.socket.setdefaulttimeout(downloader.TIMEOUT)
> ```
> 
> 1234 부분에 원하는 타임아웃 시간 초단위로 넣어주세요.

디폴트 값이 얼마인지 알려주실 수 있습니까?

**Comment by KurtBestor** [comment]
36 이에요.

**Comment by Laser-Cho** [comment]
123 넣고 실행중인데, 안되는거 같은 느낌이 솔솔.... 1234 넣고 실행해 보겠습니다.

**Comment by Laser-Cho** [comment]
네 안되네요.......

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/539
