### ISSUE TITLE
관리자님 유튜브 다운로드시 일부 문제가 있습니다. 

### ISSUE THREAD

**Issue by dcie** [KurtBestor/Hitomi-Downloader-issues#1107]
https://www.youtube.com/watch?v=xXstDmw0FnA

링크에 걸어둔 1080P 유튜브 동영상을 다운로더로 다운 받을시

화질이 360P로 고정되어 받아지는 문제가 있습니다. 

다운로더에서는 최대해상도 4K로 설정되어 있는걸 확인했습니다. 

https://www.youtube.com/watch?v=Fh1S3ivRGK8

해당 영상은 다운로더로 다운 받을시 음성이 출력되지 않습니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview
