### ISSUE TITLE
2.3버전에선 트위터 동영상을 제외하고 다운로드 하던데.. 

### ISSUE THREAD

**Issue by cocoman1111** [KurtBestor/Hitomi-Downloader-issues#111]
2.2a 버전에선 트위터의 사진과 동영상 둘다 다운로드 되었는데.

2,3버전에선 동영상만 다운되던데 일부러 바꾸신건가요???

**Comment by KurtBestor** [comment]
동영상 다운이 된다는 건가요 안 된다는 건가요?

**Comment by cocoman1111** [comment]
헉.. 제가 잘못적었군요.. 죄송합니다.
트위터 동영상만 다운이 안됩니다. 이미지는 잘 다운이 됩니다.

**Comment by KurtBestor** [comment]
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

테스트 부탁드려요.

**Comment by cocoman1111** [comment]
새로 글 올렸어요~
