### ISSUE TITLE
호두코믹스 주소가 바꿔서 다운이 안됩니다

### ISSUE THREAD

**Issue by geniussjt** [KurtBestor/Hitomi-Downloader-issues#1111]
주소가https://hodu01.net/ 여기에 바꿨습니다
hodu 파일이 제발 추가 해주세요

**Comment by geniussjt** [comment]
Can not determine type: https://hodu01.net / webtoon / list / 1921

version: 2.6d
platform: Windows-10-10.0.17763
gal_num: https://hodu01.net/webtoon/list/1921
dir: 
zip: 
type: 
artist: None
url: https://hodu01.net/webtoon/list/1921
valid: False
done: False
range: None
range_p: None
single: True
time: 1565666740.87 (Aug 13)
tags: []
goodbyedpi: True
lock: False


[Gallery]
None


[File Names]



[URLs]



[Messages]
Traceback (most recent call last):
File "hitomi_downloader_GUI", line 1267, in run
File "utils", line 236, in pop
IndexError

Fail: 

done : https://hodu01.net/webtoon/list/1921

**Comment by wiedor** [comment]
https://hodu202.net/%EC%9B%B9%ED%88%B0

툰코꺼보고 호두코믹스용으로 복사해서 고쳐서 써보려 했는데 내공이 딸려서 잘안되네요
혹시 호두코믹스 스크립트도 있나요 ?
