### ISSUE TITLE
다운로드 창에 직접 코멘트를 적어넣을 수 있게 해주실 수 있나요?

### ISSUE THREAD

**Issue by MoongSong** [KurtBestor/Hitomi-Downloader-issues#1113]
![빈공간](https://user-images.githubusercontent.com/40514407/62959925-8c201380-be34-11e9-910d-4a2683b6661c.png)

트위터나 픽시브 그림 줍는 용도로 사용 중인데
옆의 빈 공간에 해당 다운로드 파일(첨부파일에선 작가)에 대한 제 개인적인 코멘트를 적어넣을 수 있으면 좋을 것 같아요. 
다운목록이 800개를 넘어가다보니 7색 태그 설정만으론 많이 부족한 감이 있어서요..
나중에 찾기 쉽게 코멘트 검색 기능도 있으면 되게 편할 것 같은데 부탁드려도 될까요?

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by MoongSong** [comment]
> ![image](https://user-images.githubusercontent.com/14768120/63211717-26829e80-c136-11e9-8bb1-d0127ace06c0.png)
> 
> 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

감사합니다 적용 잘 돼요 덕분에 그림 정리가 너무너무 편해졌어요ㅜㅜㅜㅜ
죄송한데 혹시 필터(F3) 기능 통해서 코멘트도 검색 가능하게 해주실 수 있나요??

![예시1](https://user-images.githubusercontent.com/40514407/63652177-4ea67900-c798-11e9-9a1a-0eb2b9305eba.png)
![예시2](https://user-images.githubusercontent.com/40514407/63652178-50703c80-c798-11e9-91b9-261b66523d6b.png)


이런 식으로 제가 입력해둔 코멘트를 따로 검색할 수 있게 하면 진짜 엄청엄청 유용해질 것 같아서요.. 부탁드릴게요..

**Comment by KurtBestor** [comment]
코멘트는 `comment:xxx` 로 검색하시면 돼요.

`도움말` - `사용법... (F1)` - `다운로더 목록 필터링` 참고해주세요.

**Comment by MoongSong** [comment]
> 코멘트는 `comment:xxx` 로 검색하시면 돼요.
> 
> `도움말` - `사용법... (F1)` - `다운로더 목록 필터링` 참고해주세요.

확인했어요 감사합니다.. 감사합니다..
매일 상상만 하던 기능이 이렇게 구현되니까 진짜 너무 기뻐서 눈물까지 나올 것 같아요..
앞으로 좋은 일만 가득하길 바랄게요

**Comment by MoongSong** [comment]
> 코멘트는 `comment:xxx` 로 검색하시면 돼요.
> 
> `도움말` - `사용법... (F1)` - `다운로더 목록 필터링` 참고해주세요.

확인했어요 감사합니다
이건 약간 다른 문젠데 이 패치파일 이후론 완료됨으로 표시(D) 버튼을 눌러도 다운로드가 계속 진행되더라구요
![박제](https://user-images.githubusercontent.com/40514407/63680046-b35fe300-c82d-11e9-91f1-17ef28c66d70.png)

원래 트위터 잠금 걸거나 삭제하신 분들은 재다운로드 누르고 완료됨으로 표시 버튼 누르면 그 상태에서 다운로드가 완전히 정지돼서 사진저럼 사이트 링크와 폴더 열기 버튼이 계속 살아있었는데

![박제2](https://user-images.githubusercontent.com/40514407/63680093-d094b180-c82d-11e9-8768-4c6293a728fa.png)

코멘트 패치 이후론 완료됨 버튼을 눌러도 다운로드가 계속 진행돼서 사이트 링크 폴더 링크가 전부 죽어버리네요.. 
다운로더 목록 순서 정리할 때 비공개 트위터도 이렇게 멈춰두면 폴더 편하게 열 수 있어서 좋았었는데.. 혹시 이 부분도 수정해주실 수 있나요?

혹시나 해서 전에 쓰던 다운로더 파일 남길게요
[hitomi_downloader_GUI 2.zip](https://github.com/KurtBestor/Hitomi-Downloader-issues/files/3540460/hitomi_downloader_GUI.2.zip)

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by MoongSong** [comment]
> 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

확인했어요 이상 없이 잘 작동됩니다 정말 감사합니다
매일 상상만 하던 기능이 이렇게 구현되니까 진짜 너무 기뻐서 눈물까지 나올 것 같아요..
앞으로 좋은 일만 가득하길 바랄게요
