### ISSUE TITLE
소설가가 되자(ncode.syosetu.com) 건의 드립니다.

### ISSUE THREAD

**Issue by erebuseyny** [KurtBestor/Hitomi-Downloader-issues#1114]
소설가가 되자에서 다운로드할 때, 
merged파일에 코드번호도 표함되도록 할 수 있을까요?
예를 들면, ncode.syosetu.com/n7637dj/
[merged] 魔王様の街づくり！～最強のダンジョンは近代都市～ (n7637dj)
그럼, 좋은 하루 되시길...

P.S- 예로들은 ncode.syosetu.com/n7637dj/ 이상하게 다운로드 시 invalid 가 되던데.. 
시간되지면, 확인 부탁드립니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/759
