### ISSUE TITLE
지금 데이터 다운로드가 문제가 있습니다.

### ISSUE THREAD

**Issue by whgmlqja12** [KurtBestor/Hitomi-Downloader-issues#1116]
저만 그런건지 모르겠는데 데이터 다운로드가 [0/20]에서 계속 멈추고 껏다 켜도 똑같네요. 히토미 서버측 문제인가요?

**Comment by whgmlqja12** [comment]
Traceback (most recent call last):
  File "hitomi_searcher", line 224, in download_json
WindowsError: [Error 32] : u'C:\\Users\\whgml\\Desktop\\hitomi_downloader_GUI\\hitomi_data\\galleries0.json_new'

**Comment by KurtBestor** [comment]
테스트 해봤는데 제 쪽에선 잘 되네요.
재부팅하고 다시 시도해보세요.

**Comment by whgmlqja12** [comment]
단순히 그냥 히토미 서버 문제였던거 같네요. 시간 지나고 나서 해보니 잘 됩니다
