### ISSUE TITLE
익헨 관련 기능 추가 건

### ISSUE THREAD

**Issue by wlehd44** [KurtBestor/Hitomi-Downloader-issues#1117]
안녕하세요
hitomi download 사용 중에 이런 기능이 있으면 좋을 거 같아서 문의 드립니다
익헨에서 다운받을 때 익헨 서버로 받을 경우에 많은 자료를 받을 경우 IP 벤을 받습니다
그래서 저 같은 경우, 수동 서버 선택으로 해서 익헨 서버를 피해서 다운을 받습니다

이때 수동 서버를 선택할 때 중복으로 선택할 수 있겠끔해주실 수 있나요?

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/900
