### ISSUE TITLE
중복 이미지 찾기 기능 관련 건의 사항

### ISSUE THREAD

**Issue by wlehd44** [KurtBestor/Hitomi-Downloader-issues#1118]
저번에 건의 드렸던 부분입니다만 설명이 부족한거 같아 다시 건의 드립니다

![1](https://user-images.githubusercontent.com/48654593/63072482-01880300-bf5f-11e9-8be9-145c9ef5fa27.PNG)

위 사진처럼 중복된 이미지 중 하나를 선택하고 Ctrl + C(이하 복사), Ctrl + V(이하 붙여넣기)를 하면 

C:/Users/my/Desktop/새 폴더/77d7ab92618de5e778d88eae96a0f9a819234f48_GIruKonR_0be016ad1141d776cf6df243fb40060922c362fa - 복사본 - 복사본 (2).png

위처럼 잘 복사가 됩니다. 하지만,

![2](https://user-images.githubusercontent.com/48654593/63072551-5fb4e600-bf5f-11e9-964d-ea74eb2534e3.PNG)

위 사진처럼 중복된 이미지를 여러개 선택하고 '복사','붙여넣기'를 하게 되면

C:/Users/my/Desktop/새 폴더/77d7ab92618de5e778d88eae96a0f9a819234f48_GIruKonR_0be016ad1141d776cf6df243fb40060922c362fa - 복사본.png

위처럼 하나만 붙여지는 걸 볼 수 있습니다

2번째 사진처럼 선택하고 '복사'한 경우 선택한 것들 전부를 '붙여넣기'가 가능하겠끔 해주실 수 있나요?

**Comment by wlehd44** [comment]
많이 수정해서 죄송합니다 잘 다루지 못해서, 자꾸 실수하네요 죄송합니다

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/1090
