### ISSUE TITLE
설정의 히토미 탭에 서버를 자동으로 선택시 다운로드 서버 순서를 바꿔주시거나 바꿀 수 있게 해주실수 있나요?

### ISSUE THREAD

**Issue by ExNaGNe** [KurtBestor/Hitomi-Downloader-issues#1119]
지금 속도면에서는 히요비가 월등히 빠른데
히요비가 없는자료가 많은지 가끔 다운로드가 안됩니다.
그럴땐 익헨이나 히토미 서버로 바꿔서 다운로드 받는데

자동 서버 설정을 히요비를 먼저 시도한뒤 히요비에서 받을 수 없을때
다른 서버에서 받도록 바꾸거나 바꿀 수 있게 해두면 더 편할것 같습니다.

**Comment by KurtBestor** [comment]
![image](https://user-images.githubusercontent.com/14768120/63633938-254bf700-c68b-11e9-8ae1-b9e969484ae8.png)

테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by ExNaGNe** [comment]
잠시 써본 결과 제대로 작동 합니다.
계속 사용하다가 문제가 발생시 다시 메일 드리겠습니다.

**Comment by ExNaGNe** [comment]
익헨에는 있고 히토미나 히요미에는 아직 안 올라간 작품의 경우에
익헨에서 읽어와야하는데 익헨의 우선도가 가장 낮은 경우에 
다운 위치가 익헨인 상태에서 해당 작품을 읽어오지 못하고 계속 로딩 상태로 돌아갑니다.
이 상태에서 익헨의 우선으로를 가장 위로 올려주니까 바로 다운받네요.

**Comment by KurtBestor** [comment]
해당 작업 정보 보여주세요.

그리고 이것도 알려주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/112

**Comment by ExNaGNe** [comment]
저 글 올릴 당시가 2.3버전이었는데 당시 비슷한 문제가 있었던 분들 말 듣고 다른 버전 쓰다가
버전이 올라가면서 해당 문제는 없어졌습니다.
그리고 로딩이 길어지는 문제 정확히는 모르겠지만
아마 히요미->히토미 순으로 확인후에 해당 사이트에 자료가 없어서
익헨으로 넘어갈 경우에 로딩이 길어지는거 같습니다.

**Comment by KurtBestor** [comment]
해당 작업 정보 보여주세요.
