### ISSUE TITLE
익헨에서 다운로드가 문제가 있습니다.

### ISSUE THREAD

**Issue by ExNaGNe** [KurtBestor/Hitomi-Downloader-issues#112]
2.3 최신버전으로는 익헨에서 다운시 다운은 잘 되는데
중간에 다운이 멈추고 제목이 노랗게 변하면서 일시정지 되는 버그가 있습니다.
다시시작 해도 그 지점에서 다시 멈추고 파일 자체는 다 받아 집니다.

또 특정 파일은 무한 로딩이 걸립니다.
정보를 가져오지 못하고 계속 로딩만 합니다.

구 버전 몇개에선 로딩이 좀 길긴 하지만 그래도 작동은 합니다.

**Comment by KurtBestor** [comment]
무한로딩 걸리는 갤러리가 어떤 건지 알 수 있을까요?
