### ISSUE TITLE
개발자님 Rule34 사이트들도 추가해주시면 정말 감사하겠습니다.

### ISSUE THREAD

**Issue by saxking892** [KurtBestor/Hitomi-Downloader-issues#1120]
https://rule34.paheal.net/

https://rule34.paheal.net

위 두 사이트들은 Danbooru처럼럼 Shimmie 2 은 기반 사이트이고

https://rule34.xxx/

나머지 위의 하나는 Gelbooru처럼 Imageboard Search 기반 사이트라고합니다.

다름이 아니라. 개발자님께서 갤부루 단부루도 추가해주셔서 다운되게 해주셔서

나머지 저 Rule 34기반 사이트들도 혹시 추가해주실수 있지 않을까 싶어 여쭈어봅니다.

단부루, 갤부루에 없는 희귀한 자료들이 Rule34에 꽤나 많이 보이더라구요 ㅠㅠ

위의 Rule34 3종류 사이트들은 또 비슷하지만 서로 가지고 있는 자료수가 다른경우도 있더라구요 

그래서 3가지 사이트트를 다 지원해야 완전히 Rule34를 쓸 수 있다고 생각합니다.

개발자님 바쁘신 와중에 다운로더 정말 잘쓰고 감사드리는 마음입니다. 

여여기에 Rule34 사이트들이 추가된다면 더욱 기쁠것 같습니다. 한번만 꼭 부탁드립니다. 

긴 글 읽어주셔서 감사합니다.  항상 하시는일 잘되시길 바랍니다.

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/868, https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/1020

**Comment by KurtBestor** [comment]
투표 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/issues/868#issuecomment-723650147
