### ISSUE TITLE
무결성 검사 기능이 필요할듯 합니다.

### ISSUE THREAD

**Issue by Dumbisted** [KurtBestor/Hitomi-Downloader-issues#1121]
간혹 히토미 서버 문제든 프로그램의 비정상적인 종료든 어떤 이유로 인해 원래 받아야 할 파일 대신 깨진 파일들이 생성되곤 합니다. 저같은 경우는 각각 158바이트와 560바이트의 깨진 파일이 원래 파일 대신 생성되어 있더군요.

그런 탓에 받아놓은 파일을 일일이 검사해서 깨진 파일이 있나 없나를 찾아내야 하는데 그게 거의 중노동이라 골치가 아픕니다. 검사 기능이 있는 프로그램이나 스크립트를 써야 하는데 대체 어떻게 "압축 파일 내의 일정 크기를 가진 파일을 찾아내는 기능"을 가진 물건을 찾아야 할 지 모르겠군요.

여하튼 그런 기능을 가진 프로그램이나 스크립트를 알고 계시거나 무결성 검사 기능을 구현 가능하시다면 부탁드리는 바 입니다.

그리고 제작자님, 결과물이 반드시 최고로 인정받길 빕니다.

**Comment by sz1ah2** [comment]
깨진 파일들 보니까 죄다 4키로바이트 더라고요
정확히는 3.9였나 그랬습니다.
그래서 깨진 파일 찾을 때 4키로바이트 이미지들 찾아서 삭제하고
그에 해당하는 자료들 다시 받고 있는 걸로 해결하고 있는데
중노동이더라고요...

**Comment by KurtBestor** [comment]
깨진 파일들 보내주시면 분석해볼게요.

**Comment by Dumbisted** [comment]
@KurtBestor [SamplePages.zip](https://github.com/KurtBestor/Hitomi-Downloader-issues/files/3511980/SamplePages.zip) 여기 있습니다. 만약 만화 자체의 샘플이 필요하시다면 여기 [mediafire 링크](https://www.mediafire.com/file/2rpm4q2vz4tq7hv/Samples.zip/file)에서 받으시면 됩니다.

**Comment by KurtBestor** [comment]
v2.6d 이전 버전에서만 7월 26일부터 생긴 일인데, 해당 날짜의 파일만 삭제하고 다시 다운로드하면 될 거예요.
