### ISSUE TITLE
트위터의 사진 다운로드에 트윗이나 모멘트의 사진들도 다운로드 가능했으면 좋겠습니다

### ISSUE THREAD

**Issue by StrontYoon** [KurtBestor/Hitomi-Downloader-issues#1122]
https://twitter.com/i/moments/1012659133969924096
같이 만화 글들도 다운로드 받고 싶은데 이런것들 기능도 가능했으면 좋겠습니다!
오늘 다운로드 받아 아직 제가 쓰기에 이게 맞는 건지 틀린 건지 모르는 기능이 익숙하지 않은 상태라서 혹여 이런 기능이 이미 마련되어 있다면 알려주시면 감사하겠습니다.

**Comment by KurtBestor** [comment]
아직 그런 기능은 없어요.
