### ISSUE TITLE
검색기 목록 필터링 문제

### ISSUE THREAD

**Issue by hyunwe** [KurtBestor/Hitomi-Downloader-issues#1123]
히토미 검색기에서 필터링 기능중에 페이지수로 필터링하는 기능을 자주 사용했었는데
근래에 업데이트 이후부터 해당 필터링 기능이 작동되지 않습니다. 
p<100, p>100 

항상 감사합니다.

**Comment by KurtBestor** [comment]
참고해주세요: #1047

**Comment by hyunwe** [comment]
중복이었네요
감사합니다
