### ISSUE TITLE
마나모아 최신업데이트만 모아서 다운로드 가능한가요?

### ISSUE THREAD

**Issue by PrivateI** [KurtBestor/Hitomi-Downloader-issues#1124]
찾아보니 날짜별 다운로드는 사이트내에서 검색을 지원하지 않아서 안된다고 하던데,
https://manamoa.net/bbs/board.php?bo_table=manga&page=2
이런식으로 최신화가 업데이트되는 주소를 이용해서
몇페이지 전체 또는 몇페이지에서 몇페이지까지 업로드된 전체
이런식으로는 가능한지 문의드립니다

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/351#issuecomment-447619182

**Comment by PrivateI** [comment]
전부다 보려는건 아니지만 보려는게 절반이상 되게되면 새로올라오는거 전체받기 한다음에 안보는거 지우는게 더 나아보여서 그런거였는데 저방법이 더 나으려나요
북마크해둔거만 3자리수라...
그러면 보는작품을 북마크하듯이 리스트에 추가해서 그 리스트 전체 '다시시작'이나, 따로 리스트가 없더라도 추가해둔 링크 '전체 다시시작'같은건 가능한가요?
