### ISSUE TITLE
갤러리 넘버 복사 개선건의 입니다.

### ISSUE THREAD

**Issue by cdreadme** [KurtBestor/Hitomi-Downloader-issues#1125]
폴더내 갤러리 넘버를 확인해서 간소화 확인(용량, 페이지같은 조건)후 작업완료로 추가하는 기능이 있었으면 좋겠습니다.
기존 기능으로 갤러리 넘버 복사 후 입력하면 기존 리스트가 있을경우에 중복이 되는 경우가 있습니다. 또한 사이트로 가서 확인을 할 필요도 있고 가끔 폴더뒤에 (2)가 붙는 경우가 있더라구요

또한 현재 갤러리 넘버 복사를 선택하면 실패목록에 파일명으로 떠서 갯수가 엄청 많아보이는데 폴더로만 보이거나 파일 폴더를 분리해서 볼수 있으면 좋겠습니다.

늘 잘 사용하고 있고 고생해주셔서 감사합니다.

**Comment by KurtBestor** [comment]
중복된 작업 관리는 `도움말` - `사용법... (F1)` - `다운로더 목록 필터링` 을 참고해주세요.

폴더만 검사하게 바꿨어요. 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by cdreadme** [comment]
중복작업쪽은 해결법이 따로 있었네요.

알아보기 훨씬 쉬워졌습니다. 감사합니다!!

혹시 제가 작가별 폴더정리를 해서 [작가명 / 작품폴더] 이런식으로 하위폴더 저장을 하는데
하위폴더에 확인된 작품이 있다면 상위폴더 확인을 무시하게 해 주실수 있나요???
