### ISSUE TITLE
호두코믹스 스크립트 문의입니다.

### ISSUE THREAD

**Issue by jinjins7** [KurtBestor/Hitomi-Downloader-issues#1126]
호두코믹스 스크립트가 이제 작동을 하지 않습니다.
hodu01.net으로 주소가 바뀐것 때문인것도 같습니다만..
스크립트에서 
URLS = ['regex:hodu[0-9]+.com']
DOMAIN = re.findall('hodu[0-9]+.com', self.url)[0]
이 두부분을 .com을 .net으로 바꿔봐도 작동을 하지 않습니다.
제가 코드를 다루는것을 잘 몰라서 이 이상은 어떻게 해 볼수가 없네요ㅠㅠ
제발 스크립트를 작동이 되도록 조취해주시면 진심으로 감사드리겠습니다...

**Comment by Raycity** [comment]
저도 기다리고 있습니다.
밑에 다른 분이 글을 쓰셨는데, 준비하고 계신 거 같아요.

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/1111

**Comment by karnies** [comment]
URLS = ['regex:hodu0[0-9]+.com']
DOMAIN = re.findall('hodu0[0-9]+.com', self.url)[0]

일단 응급처치로 이렇게 바꿔보세요

**Comment by yooyoous** [comment]
기존 툰코 스크립트에서 toonkor 부분을 전부 현재 호두주소인 https://hodu208.net/toon 로 바꿔봣는데 되질않네요

툰코 스크립트켜고 replace 스크립트로 toonkor ㅡ> hodu 로 변경해도 안되구;; 기존에 올려주신 hodu 스크립트 구글드라이브는 url이 터졋네여;;

목록 주소를 입력해주세요: https://hodu208.net/episode?ind=%EC%9B%94/%EB%88%84%EB%82%98%EC%9D%98%20%EC%84%B1%EA%B5%90%EC%9C%A1

version: 3.5 (21-07-11 04:31:06 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 0 / False / 36397e793af14cacae6bf5243456fadb
input: https://hodu208.net/episode?ind=%EC%9B%94/%EB%88%84%EB%82%98%EC%9D%98%20%EC%84%B1%EA%B5%90%EC%9C%A1
type: hodu
single: False
url: https://hodu208.net/episode?ind=%EC%9B%94/%EB%88%84%EB%82%98%EC%9D%98%20%EC%84%B1%EA%B5%90%EC%9C%A1
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: -350 ~ / None
time: 1627259101.0799115 (Jul 26)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
goodbyedpi: False
ytdl: 2021.06.06
pinned: False
extras: {}
changed: True


[Gallery]
None


[File Names]



[URLs]



[Messages]
stop
Invalid: fail=False
EOT: https://hodu208.net/episode?ind=%EC%9B%94/%EB%88%84%EB%82%98%EC%9D%98%20%EC%84%B1%EA%B5%90%EC%9C%A1 (1.8s)
