### ISSUE TITLE
텀블러 받을 때 대시보드에서는 받지 못하나요? +건의

### ISSUE THREAD

**Issue by GH6** [KurtBestor/Hitomi-Downloader-issues#1128]
https://www.tumblr.com/dashboard/blog/블로그이름/
이런 형식으로 된 걸요.

미러사이트에서도 받을 수 있도록 추가해주실 수 있나요
예를 들어 tumbex 같은 데서요. 여기서는 대시보드형식이라도 표시가 되더라고요.
+제가 오늘 밤부터 꽤 오랫동안 인터넷을 하지 못할 거 같아요.
답변만 해주세요.
나중에 확인하게요.

**Comment by KurtBestor** [comment]
해당 링크들 알려주시면 살펴볼게요.
