### ISSUE TITLE
호두 코믹스 스크립트 수정..

### ISSUE THREAD

**Issue by realfeel87** [KurtBestor/Hitomi-Downloader-issues#1129]
호두코믹스 도메인이 변경(com→net)되어 스크립트가 먹히질 않습니다.

스크립트 com부분을 net으로 변경해도 되질않네요 ㅎㅎ;

스크립트 어딜 만져야 다시 작동하나요??

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/1111
