### ISSUE TITLE
머신러닝 추천 잘 안되고 기능 건의합니다. 항상 잘 쓰고 있습니다 감사해요

### ISSUE THREAD

**Issue by hodol333** [KurtBestor/Hitomi-Downloader-issues#113]
머신러닝 기반 작가추천에서 지금까지 받은 작품 리스트를 안받고 하나만 가져오네요. 다음으로 안넘어가지고 더 불러와지지도 않았던 거 같아요.

그리고 검색어 구독 기능 가능할까요? 검색기에서 즐겨찾기한 작가나 태그 뭐 그런것들의 가장 최신 자료가 무엇인지 기록해놓고 검색기를 다시 켜면 모든 즐겨찾기 항목의 가장 최신 항목만 검색해서 달라졌으면 알려주는 기능이 있으면 굉장히 편리할 것 같네요.

**Comment by KurtBestor** [comment]
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

이건 어떤가요?
폴더명 형식이 어떻게 되나요?

구독 기능은 힘들 것 같네요.
개인적으로 작가 A, B, C의 가장 최신 작품을 보려고할 땐 다음과 같이 북마크해놓고 필요할 때 꺼내서 검색합니다:
```
A + B + C
```

**Comment by hodol333** [comment]
잘 됩니다. 감사합니다!

그럼 혹시 북마크된 모든 항목들을 A + B + C + ... + Z 하는 식으로 써 주는 기능 같은 건 없을까요? 저만 해도 북마크가 모니터 한 열을 다 채우고 2열까지 넘어가서 그거 한번에 다... 다 쳐서 북마크 해놓으면 되겠네요...
그래도 그럴 경우 새로운 북마크는 포함되지 않아서... ㅎㅎ 가능할까요?

**Comment by KurtBestor** [comment]
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

북마크 작가명 합쳐서 불러오는 기능 넣었어요.
테스트 부탁드려요.
[검색기 - ★ - 모든 작가 불러오기] 로 불러올 수 있어요.

**Comment by hodol333** [comment]
잘 됩니다. 감사합니다!
산카쿠 추가된건 따로 산카쿠에 들어가서 링크찾아서 하나하나 붙여넣어야 하나요?

**Comment by KurtBestor** [comment]
목록 주소를 입력하면 돼요.

예시:
```
https://chan.sankakucomplex.com/?tags=loli
```
