### ISSUE TITLE
I can't download Deviantart galleries

### ISSUE THREAD

**Issue by Rocneriano** [KurtBestor/Hitomi-Downloader-issues#1130]
help please, I get the following errors:

Invalid : [deviant] https://www.deviantart.com / tirnanogindustries / gallery / 

version: 2.6d
platform: Windows-10-10.0.18362
gal_num: https://www.deviantart.com/tirnanogindustries/gallery/
dir: 
zip: 
type: deviant
artist: None
url: https://tirnanogindustries.deviantart.com/
valid: False
done: False
range: None
range_p: None
single: False
time: 1566206837.55 (Aug 18)
tags: []
goodbyedpi: False
lock: False

[Gallery]
None

[File Names]

[URLs]

[Messages]
'NoneType' object has no attribute 'children'
stop
Traceback (most recent call last):
File "utils", line 535, in start
File "utils", line 579, in start_
File "deviant_downloader2", line 103, in read
File "deviant_downloader2", line 134, in get_imgs
File "deviant_downloader2", line 122, in get_name
AttributeError: 'NoneType' object has no attribute 'children'

Fail: deviant

-
-

Invalid : [deviant] https://www.deviantart.com / dzourl

version: 2.6d
platform: Windows-10-10.0.18362
gal_num: https://www.deviantart.com/dzourl
dir: 
zip: 
type: deviant
artist: Projectcomment
url: https://dzourl.deviantart.com/
valid: False
done: False
range: None
range_p: None
single: False
time: 1566206822.89 (Aug 18)
tags: []
goodbyedpi: False
lock: False

[Gallery]
None

[File Names]

[URLs]

[Messages]
'NoneType' object has no attribute 'group'
stop
Traceback (most recent call last):
File "utils", line 535, in start
File "utils", line 579, in start_
File "deviant_downloader2", line 103, in read
File "deviant_downloader2", line 137, in get_imgs
AttributeError: 'NoneType' object has no attribute 'group'

Fail: deviant

**Comment by KurtBestor** [comment]
Try the test version: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by Rocneriano** [comment]
Thank you! yes it worked
