### ISSUE TITLE
VPN을 적용할 수 있는 방법이 있나요?

### ISSUE THREAD

**Issue by lililillilililililil** [KurtBestor/Hitomi-Downloader-issues#1131]
Manga Rock 의 경우 VPN없이는 접속이 불가능해서 VPN으로 접속해서 다운하고 싶은데 VPN 프로그램을 이용해도 웹 브라우저로는 접속이 되는데 다운로더로는 다운이 안 되네요.
VPN을 적용해서 다운할 수 있는 방법이 있나요?

**Comment by jinjins7** [comment]
VPN프로그램을 쓰면 싹다 우회되서 작동 잘되던데 어떠한것을 쓰시길래...

**Comment by lililillilililililil** [comment]
아 다른 VPN프로그램 깔아서 해봤더니 되네요. 감사합니다!
