### ISSUE TITLE
마나모아 사이트

### ISSUE THREAD

**Issue by aksghkqhrl** [KurtBestor/Hitomi-Downloader-issues#1133]
만화 사이트가

https://manamoa10.net/

에서 https://manamoa12.net/ 로 바뀌었는데

만화 링크를

https://manamoa10.net/bbs/board.php?bo_table=manga&wr_id=1769657

에서

https://manamoa12.net/bbs/board.php?bo_table=manga&wr_id=1769657

으로 다운로드 목록을 저 manamoa(숫자) 부분만 일괄변경은 불가능할까요?

이후 점점 사이트 넘버가 바뀔경우 예전의 manamoa4 에서 다운이 안되고 크롬이 켜지면서 다운이 되는 번거로운 상황이 생길까봐 ..

**Comment by lililillilililililil** [comment]
스크립트에 Replace URLs 이거 쓰시면 될 꺼에요.
아니면 목록 Ctrl + A 눌러서 전부 선택하신 뒤 Ctrl + C 눌러서 목록 림크 전부 복사하신 뒤 메모장이나 워드, 한글에 붙여넣은 뒤 "manamoa10.net" 을 "manamoa12.net" 로 일괄바꾸기 하시고, 기존 다운로더 목록을 지우신 뒤 바꾼 링크를 붙여넣으시면 됩니다.
