### ISSUE TITLE
xhamster.com 사이트 추가가 가능할까요?

### ISSUE THREAD

**Issue by mrdonghyun12** [KurtBestor/Hitomi-Downloader-issues#1135]
폰헙, 엑스비디오같이 단순 포르노보단 다른자료들을 구할 수 있어서 꼭 하고싶습니다..! 고전

자료라던가 폰헙 엑비디에선 볼 수없는게 많아요

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by mrdonghyun12** [comment]
확인해봤는데 영상다운은 정상적으로 되는데

갤러리라는 기능이있는데 이 사진들은 긁을 수 없는건가요..?

https://xhamster.one/photos/gallery/leah-gotti-10217575

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

갤러리 다운로드 기능은 나중에 넣을게요.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview
