### ISSUE TITLE
Xvideos problem

### ISSUE THREAD

**Issue by jessicachon** [KurtBestor/Hitomi-Downloader-issues#1137]
hi I can download a video from xvideos but it is bad quality is there a way too up the quality like I can do with youtube videos? Thank you for making such a great program!

**Comment by KurtBestor** [comment]
Let me know the link which is downloaded in bad quality.

**Comment by jessicachon** [comment]
is it ok if it is porn?

**Comment by KurtBestor** [comment]
OK

**Comment by jessicachon** [comment]
https://www.xvideos.com/video41778083/chaturbate_girl_dawn_willow

**Comment by KurtBestor** [comment]
Try the test version: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by jessicachon** [comment]
ok I will try! thank you kurtbestor, I love your program!
