### ISSUE TITLE
p<100 필터링이 작동하지 않습니다

### ISSUE THREAD

**Issue by siwkd2** [KurtBestor/Hitomi-Downloader-issues#1139]
https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/1047

여기 나와있는 버젼과 현재까지 나와있는 최신버젼 둘다 필터링기능이 작동하지 않습니다

혹시나 시간이 나시면 업데이트 부탁드립니다

감사합니다

**Comment by KurtBestor** [comment]
어떻게 안 되는지 스크린샷 찍어서 보여주세요.

**Comment by siwkd2** [comment]
> 어떻게 안 되는지 스크린샷 찍어서 보여주세요.

![758](https://user-images.githubusercontent.com/44530054/63639075-8f37c100-c6ca-11e9-98df-c759fff74fc7.png)

이렇게 p<100를 입력하여도 아무런 반응이 뜨지않습니다

**Comment by KurtBestor** [comment]
검색기에서만 되는 기능이에요

**Comment by siwkd2** [comment]
> 검색기에서만 되는 기능이에요

아 그렇군요 답변감사합니다
