### ISSUE TITLE
크기조절 옵션에서의 높이 맞춤 옵션 방식 건의

### ISSUE THREAD

**Issue by crescee** [KurtBestor/Hitomi-Downloader-issues#1140]
현재 크기 조절 옵션에서 폭 맞춤 설정만을 지원하고 있어
가로 길이 맞춤만이 가능한데 세로 길이 조절을 지원하지 못하는 
어떤 기술적인 문제가 있는지요?
만화는 2장의 이미지를 같이 표시하는 경우가 많기때문에
가로길이를 맞추는것보다는 세로를 맞추는게 더 중요하다고 생각하는데
세로 길이 맞춤 옵션을 지원하지 않아 매우 안타깝습니다.
혹여 추후라도 지원하실 의향이 있으신지 알고싶습니다.

**Comment by KurtBestor** [comment]
세로 길이가 매우 긴 이미지들이 있어요. (특히 웹툰)
세로 기준으로 크기조절하게 되면 그런 이미지들이 너무 작게 되는 문제가 있어서 넣지 않은 기능이에요.
