### ISSUE TITLE
관리자님 문의요 텔레그렘

### ISSUE THREAD

**Issue by kikinet88** [KurtBestor/Hitomi-Downloader-issues#1141]
텔레그렘 PC 판에서
그룹방에 동영상 일괄로 받는 방법 없을까요
도무지 검색을 해도 모르겠네.. 허허허

그리고 서버는 항상 잘돌아가고 있습니다..

**Comment by KurtBestor** [comment]
쉬운 방법은 없을 것 같아요..

서버 제공 감사드립니다!
