### ISSUE TITLE
폴더 밖 미리보기가 안보입니다

### ISSUE THREAD

**Issue by sik20852** [KurtBestor/Hitomi-Downloader-issues#1143]
파일 밖 다 받은 상태인데도 이리뜹니다
![KakaoTalk_20190827_022413767](https://user-images.githubusercontent.com/50183365/63709555-1c694a00-c872-11e9-8d28-8b4c046ee7d9.png)

**Comment by KurtBestor** [comment]
해당 파일들 보내주시면 분석해볼게요.
