### ISSUE TITLE
다운로드가 진행이 되지않습니다

### ISSUE THREAD

**Issue by smithkun** [KurtBestor/Hitomi-Downloader-issues#1144]
3일정도 재부팅해가면서 확인하고있는데 모든파일이 

[0/25] 이런 상태에서 다운로드가 되지않다가 노란색으로 바뀌면서 진행이 정지됩니다.

사이트의 서버의 문제인건가요?

**Comment by KurtBestor** [comment]
해당 작업들 `마우스 우 클릭` - `정보... (I)` 눌러서 나온 내용 보여주세요.
