### ISSUE TITLE
호두코믹스는 업데이트 지원중단하신건가요?

### ISSUE THREAD

**Issue by siwkd2** [KurtBestor/Hitomi-Downloader-issues#1146]
밑에 호두코믹스 관련 문의글을 보았는데 참고하시라는 글에 답변이 없으신걸보고 

혹시 더이상 스크립트 업데이트 지원을 안하시나해서 여쭤봅니다

**Comment by KurtBestor** [comment]
우선순위가 좀 밀려서 다른 것들 먼저 해결하고 하지 않을까 싶어요.

혹시 기여하고 싶으신 프로그래머 분들 있으시면 스크립트 고쳐서 보내주시면 감사하겠습니다.

**Comment by siwkd2** [comment]
> 우선순위가 좀 밀려서 다른 것들 먼저 해결하고 하지 않을까 싶어요.
> 
> 혹시 기여하고 싶으신 프로그래머 분들 있으시면 스크립트 고쳐서 보내주시면 감사하겠습니다.

답변 감사합니다

**Comment by realfeel87** [comment]
> 우선순위가 좀 밀려서 다른 것들 먼저 해결하고 하지 않을까 싶어요.
> 혹시 기여하고 싶으신 프로그래머 분들 있으시면 스크립트 고쳐서 보내주시면 감사하겠습니다.

호두코믹스 주소가 완전 바꼈네요.. 혹시나 추후 작업하실때 참고 되시라고 글 하나 적습니다,

https://hoduco.net/
