### ISSUE TITLE
다운로드 기능 추가 문의를 드립니다.

### ISSUE THREAD

**Issue by UzinSG** [KurtBestor/Hitomi-Downloader-issues#1148]
다운로드 기능 추가 문의를 드립니다.

이미 파싱된 텍스트 파일을 로드 하는 기능도있으면 합니다.

예) test.txt 가 있다고 가정할때

https://hi~~.la/g~/~
https://hi~~.la/g~/~
https://hi~~.la/g~/~
https://hi~~.la/g~/~
....
...
..
.

이런 링크로 하여 있는것을 갤러리 링크가 있는것들 [ 히토미, 히요비, 이헨, 익헨 등 ]
텍스트 파일로 삽입하여 자동으로 다운로드 하는 기능이 있었으면 합니다.

텍스트파일 스캔 후 하나씩 다운로드를 걸어 다운받고 다음링크도 다운받는식으로
 - 자동으로 링크 하나씩 추가하여 다운받고 완료되면 다음 링크 검색, 다운 반복 으로 했으면합니다.

이렇게해서 텍스트 안에 1000개의 링크가있다면 줄 순서 대로 링크 추가 -> 다운 -> 완료 -> 다음링크 추가 -> 다운 -> 완료 -> 이하 반복 [ 텍스트안에 모든 링크 다운시까지 ]

만약 어떠한 링크가 다운 오류가 날 시 바로 그 다음 링크로 다운로드를 진행합니다.

링크 에러가 난 링크는 따로 모아뒀다가 모든 링크 다운이 끝날시 재시도.
 - 다운받다가 에러난 경우 해당 링크 동인지 폴더를 지웁니다.

원하는 추가 기능 [ 로그 기능, 상태 확인 ]
 - 텍스트 파일을 읽어서 작업중인 링크 상태를 알려줍니다.
 - 아래를 참고해주세요.

예)

LOG [ 실시간 동기화 ]
 - 양식 : 링크 [ 상태 ] [ 갤러리 갯수 ]

https://hi~~.la/g~/~ [ 완료 ] [ 53 / 53 ]
https://hi~~.la/g~/~ [ 에러 ] [ 10 / 21 ] [ 재시도 예정! ]
https://hi~~.la/g~/~ [ 완료 ] [ 22 / 22 ]
https://hi~~.la/g~/~ [ 다운중... ] [ 24 / 100 ]
https://hi~~.la/g~/~ [ 대기중... ]
https://hi~~.la/g~/~ [ 대기중... ]
https://hi~~.la/g~/~ [ 대기중... ]
https://hi~~.la/g~/~ [ 대기중... ]
.....
...
...

**Comment by KurtBestor** [comment]
복사해서 주소창에 입력하고 다운로드하면 돼요.
