### ISSUE TITLE
검색기의 북마크 기능

### ISSUE THREAD

**Issue by Revena** [KurtBestor/Hitomi-Downloader-issues#115]
너무 많이 북마크 해서 그런지 목록화면 가득히 추가되서 짤려서 안보이네요.
이 부분 스크롤 같은 기능 넣어주실수 없을까요.
추가로 a-z 정렬 같은 기능도요.
항상 감사히 잘 쓰고 있습니다.

**Comment by KurtBestor** [comment]
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

좀 더 많이 보이게 했습니다. 제 해상도에선 700개 이상 보이네요.
이름순 정렬도 넣었습니다.
테스트 부탁드려요.

**Comment by Revena** [comment]
우선, 개선해주신점 감사드립니다.
이름 정렬, 재 전환 기능이 깔끔하게 되는것을 확인했습니다.
하지만 목록표시는 제 해상도로는 화면에 약470 개 정도가 한계라 이렇다할 변화는 못 느꼈습니다.
해상도에 상관없는 다른 방법이 필요할것 같습니다.
노고에 다시한번 감사드립니다.

**Comment by KurtBestor** [comment]
처음 설계할 때 북마크를 몇백개 하는 분이 있을 줄은 몰랐네요.
스크롤은 말씀하신대로의 문제가 있기도 해서 아마 바꾸진 않을 것 같고요.
꼭 필요하다면 가져오기 / 내보내기 기능을 이용해서 관리를 하는 게 좋을 것 같네요.
북마크 파일 (*.bmk)은 JSON 파일입니다. [JSON 에디터](https://jsoneditoronline.org/)로 수정할 수 있으니 참고해주세요.

**Comment by Revena** [comment]
네 알겠습니다. 수고하셨습니다. :D
