### ISSUE TITLE
Manamoa 다운로드 시 폴더명 관련 기능 문의

### ISSUE THREAD

**Issue by orangespoons** [KurtBestor/Hitomi-Downloader-issues#1154]
마나모아에서 다운로드를 하는데,
폴더명 형식 지정 기능이 있는걸 봤습니다.

근데 '[히토리] 쾌락 히스토리에' 같은 작품들을 보면
각 에피소드가 단편 단편으로 구성되어 있기때문에
1권, 2권 내지 1화, 2화로 구성되어 있는 다른 책들에 비해
순서대로 보기가 불편합니다. 가나다 순서기 때문에 이상하게 정렬되더라구요

혹시 다운로드 시 마나모아에 정렬되어 있는 순서대로 앞에 번호를 붙이는 등의 기능이 있을까요?
만약 없다면 기능 추가 건의 드려봅니다.

**Comment by orangespoons** [comment]
ex) 쾌락 히스토리에 -고대그리스시대편
쾌락 히스토리에 -고대로마시대편....

->
1. 쾌락 히스토리에 -고대그리스시대편
2. 쾌락 히스토리에 -고대로마시대편
같은 형식을 말하는 것 입니다..

**Comment by KurtBestor** [comment]
중복된 제목으로 똑같은 화가 올라오는 경우도 있고, 중간 화 하나 사라지면 폴더명이 엉키는 문제도 있고, 옛날 자료는 순서가 거꾸로 되어있거나 섞여있는 경우가 있어서 현재는 보류하려고 해요.
