### ISSUE TITLE
Site support: twitpic.com

### ISSUE THREAD

**Issue by nisehime** [KurtBestor/Hitomi-Downloader-issues#1155]
This is the part of twitter. Examples: https://twitter.com/saishow/status/338316793921806336

https://twitter.com/search?q=from:saishow%20since:2012-12-01%20until:2013-06-01%20filter:media&src=typd

This appears on old tweets. Most of those links are just direct links to images, so I guess shouldn't be big problem. Many of them also are dead, but still.

**Comment by KurtBestor** [comment]
Try the test version: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

It may fixes most of the problems.

**Comment by nisehime** [comment]
Thanks so much! And sorry, I forgot to add that not all twitpic urls are searched with `filter:~` operator. So it needs a separate search with query like that `from:user twitpic.com`. (https://twitter.com/search?f=tweets&vertical=default&q=from:saishow%20twitpic.com&src=typd)

I tested the same artists as the last time and everything is ok, some of them have even more because of twitpic. No errors occured.

**Comment by nisehime** [comment]
So, could you do it? Just add this search query to the end of the grabbing process, so it would work like that: 1. media 2. `from:x filter:media` 3. `from:x twitpic.com`

**Comment by KurtBestor** [comment]
No, it doesn't work. What i'm currently doing is:
1. Search in `/media` with `&max_position=xxxx`
2. Search by `from:xxxx max_id:xxxx exclude:retweets filter:media -filter:periscope`
3. Search by `from:xxxx max_id:xxxx exclude:retweets filter:media -filter:periscope` with `&max_position=xxxx`

There is no result in the search by `from:xxxx twitpic.com` from the beginning.
I could try search in every single periods, but it takes too many requests and time.

**Comment by nisehime** [comment]
> There is no result in the search by from:xxxx twitpic.com from the beginning.
What do you mean? I try this https://twitter.com/search?f=tweets&vertical=default&q=from:saishow%20twitpic.com&src=typd and there are results present.

**Comment by KurtBestor** [comment]
![image](https://user-images.githubusercontent.com/14768120/64490027-11f87880-d294-11e9-9c58-e8319de52f47.png)

Twitter behaves very strangely.
It returns different results vary depending on whether it has referer or not, vary from user agent to user agent, and even vary from IP to IP.
It's really hard to understand how it works.

**Comment by nisehime** [comment]
@KurtBestor 
That's true. I had this bug(?) too. It worked for me after I reload the page a few times.
