### ISSUE TITLE
에이전트는 항상 자동으로 종료됩니다

### ISSUE THREAD

**Issue by lhj5426** [KurtBestor/Hitomi-Downloader-issues#1156]
안녕하세요

이 에이전트의 일부
로 설정할 수 있습니까
지속적으로 개방

이제 프록시 설정이 사용됩니다.

그러나

소프트웨어를 끄고 프록시를 다시 열면 켜지지 않은 상태로 돌아갑니다.

에이전트가 고정되어 있지 않습니다. 고정하도록 설정할 수 있습니까?

중국에 있기 때문에 매번 에이전트를 열어 두어야하지만 소프트웨어를 닫을 때마다 소프트웨어를 열고 소프트웨어에서 프록시 기능을 다시 시작해야합니다.

반복하는 것이 불편합니다. 소프트웨어를 종료하고 상담원이 열린 후 종료 상태를 복원합니까?

프록시 켜기와 프록시 끄기 간 수동 전환

소프트웨어 프로세스가 종료 되더라도 소프트웨어 에이전트를 다시 열거 나 마지막으로 다시여십시오.
![image](https://user-images.githubusercontent.com/30548000/64072364-b80a1880-ccbf-11e9-8409-9c2fd91be2fe.png)

![image](https://user-images.githubusercontent.com/30548000/64072365-bb9d9f80-ccbf-11e9-945d-74fa35134072.png)

명확하지 않은 것 같습니다

동적 설명 사진 첨부
https://i.imgur.com/w4Pza9v.gifv

**Comment by KurtBestor** [comment]
Try the test version: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by lhj5426** [comment]
감사합니다

문제 해결
