### ISSUE TITLE
유튜브 2k, 4k 다운로드시 영상 깨짐

### ISSUE THREAD

**Issue by Aideln** [KurtBestor/Hitomi-Downloader-issues#1159]
190511 로즈퀸(Rose Queen) 지니 - Hot In Here @금촌통일시장 문화난장어울림공연행사 4K 60P 직캠 Fancam by LIKEY

version: 2.6d
platform: Windows-10-10.0.18362
gal_num: https://www.youtube.com/watch?v=I10qCqKxW2M
dir: hitomi_downloaded_youtube
zip: 
type: youtube
artist: LIKEY
url: https://www.youtube.com/watch?v=I10qCqKxW2M
valid: True
done: True
range: None
range_p: None
single: True
time: 1567417553.24 (Sep 2)
tags: []
goodbyedpi: True
lock: False
color: done

[Gallery]
None

[File Names]
[0001] hitomi_downloaded_youtube\190511 로즈퀸(Rose Queen) 지니 - Hot In Here @금촌통일시장 문화난장어울림공연행사 4K 60P 직캠 Fancam by LIKEY (I10qCqKxW2M).mp4

[URLs]
[0001] https://r8---sn-3u-bh2ek.googlevideo.com/videoplayback?expire=1567439157&ei=1eRsXe_GBZDI4wLCz72ACQ&ip=211.194.137.245&id=o-AOU-XeVQ_7NwoTZYeYdJeuSJ_ateY27ot1RQALA3DbTJ&itag=315&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C271%2C278%2C298%2C299%2C302%2C303%2C308%2C313%2C315&source=youtube&requiressl=yes&mm=31%2C26&mn=sn-3u-bh2ek%2Csn-i3b7kn7s&ms=au%2Conr&mv=m&mvi=7&pl=19&initcwndbps=1175000&mime=video%2Fwebm&gir=yes&clen=788025166&dur=275.191&lmt=1558130738627341&mt=1567417476&fvip=5&keepalive=yes&c=WEB&txp=2206222&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHylml4wRQIhAIC3sgsUqpGm3iCflW0V4ilrA553BGrDQ8B6bEvoj6jOAiAo8ADOP7YsHRwn4bOC3s2fF8Zio2UbdozNUSGofWj4Rg%3D%3D&sig=ALgxI2wwRAIgN50MCL8xjcxZDMq3wvqLN_tKLC8WT-kwYGwYNhOllTECIGyyR6N_FVzLhwyLrTsv3uB49N0VhhLWJ55mqKQ9xNbP&ratebypass=yes

[Messages]
[144p][0fps][None] mp4 None ─ 160 - 256x144 (144p)
[144p][0fps][None] webm None ─ 278 - 256x144 (144p)
[240p][0fps][None] mp4 None ─ 133 - 426x240 (240p)
[240p][0fps][None] webm None ─ 242 - 426x240 (240p)
[360p][0fps][None] webm None ─ 243 - 640x360 (360p)
[360p][0fps][None] mp4 None ─ 134 - 640x360 (360p)
[480p][0fps][None] webm None ─ 244 - 854x480 (480p)
[480p][0fps][None] mp4 None ─ 135 - 854x480 (480p)
[720p][0fps][None] webm None ─ 247 - 1280x720 (720p)
[720p][0fps][None] mp4 None ─ 136 - 1280x720 (720p)
[1080p][0fps][None] webm None ─ 248 - 1920x1080 (1080p)
[720p][60fps][None] webm None ─ 302 - 1280x720 (720p60)
[720p][60fps][None] mp4 None ─ 298 - 1280x720 (720p60)
[1080p][0fps][None] mp4 None ─ 137 - 1920x1080 (1080p)
[1080p][60fps][None] webm None ─ 303 - 1920x1080 (1080p60)
[1080p][60fps][None] mp4 None ─ 299 - 1920x1080 (1080p60)
[1440p][0fps][None] webm None ─ 271 - 2560x1440 (1440p)
[1440p][60fps][None] webm None ─ 308 - 2560x1440 (1440p60)
[2160p][0fps][None] webm None ─ 313 - 3840x2160 (2160p)
[2160p][60fps][None] webm None ─ 315 - 3840x2160 (2160p60)
[360p][0fps][96kbps] mp4 mp4a.40.2 ─ 18 - 640x360 (medium)

# stream_final <youtube_dl_test.Video object at 0x1FE765D0> 313 - 3840x2160 (2160p) 2160p webm None 0fps
# stream_final <youtube_dl_test.Video object at 0x1FE76C10> 315 - 3840x2160 (2160p60) 2160p webm None 60fps
[360p][0fps][96kbps] mp4 mp4a.40.2 ─ 18 - 640x360 (medium)

[360p][0fps][96kbps] mp4 mp4a.40.2 ─ 18 - 640x360 (medium)

# stream_audio 96kbps mp4 mp4a.40.2
https://r8---sn-3u-bh2ek.googlevideo.com/videoplayback?expire=1567439157&ei=1eRsXe_GBZDI4wLCz72ACQ&ip=211.194.137.245&id=o-AOU-XeVQ_7NwoTZYeYdJeuSJ_ateY27ot1RQALA3DbTJ&itag=18&source=youtube&requiressl=yes&mm=31%2C26&mn=sn-3u-bh2ek%2Csn-i3b7kn7s&ms=au%2Conr&mv=m&mvi=7&pl=19&initcwndbps=1175000&mime=video%2Fmp4&gir=yes&clen=24434360&ratebypass=yes&dur=275.249&lmt=1558128600186742&mt=1567417476&fvip=5&c=WEB&txp=2211222&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cmime%2Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt&lsparams=mm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHylml4wRQIhAIC3sgsUqpGm3iCflW0V4ilrA553BGrDQ8B6bEvoj6jOAiAo8ADOP7YsHRwn4bOC3s2fF8Zio2UbdozNUSGofWj4Rg%3D%3D&sig=ALgxI2wwRgIhAIAlTF-F0RBjIKoOwS3aZNS3rJKEurhjIiGIw42BTCHTAiEAoMjxP2LuifBDnhuuVxIcOZfSFV7oocPsRkdRwoYexW8=
Resolution: 2160p
Codec: vp9 / None
Abr: None
Subtype: webm
FPS: 60

Download audio: https://r8---sn-3u-bh2ek.googlevideo.com/videoplayback?expire=1567439157&ei=1eRsXe_GBZDI4wLCz72ACQ&ip=211.194.137.245&id=o-AOU-XeVQ_7NwoTZYeYdJeuSJ_ateY27ot1RQALA3DbTJ&itag=18&source=youtube&requiressl=yes&mm=31%2C26&mn=sn-3u-bh2ek%2Csn-i3b7kn7s&ms=au%2Conr&mv=m&mvi=7&pl=19&initcwndbps=1175000&mime=video%2Fmp4&gir=yes&clen=24434360&ratebypass=yes&dur=275.249&lmt=1558128600186742&mt=1567417476&fvip=5&c=WEB&txp=2211222&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cmime%2Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt&lsparams=mm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHylml4wRQIhAIC3sgsUqpGm3iCflW0V4ilrA553BGrDQ8B6bEvoj6jOAiAo8ADOP7YsHRwn4bOC3s2fF8Zio2UbdozNUSGofWj4Rg%3D%3D&sig=ALgxI2wwRgIhAIAlTF-F0RBjIKoOwS3aZNS3rJKEurhjIiGIw42BTCHTAiEAoMjxP2LuifBDnhuuVxIcOZfSFV7oocPsRkdRwoYexW8=
Convert: C:\Users\kyc45\Desktop\downloader_GUI_t\hitomi_downloaded_youtube\190511 로즈퀸(Rose Queen) 지니 - Hot In Here @금촌통일시장 문화난장어울림공연행사 4K 60P 직캠 Fancam by LIKEY (I10qCqKxW2M).webm
rename (1): hitomi_downloaded_youtube\E65B732E_a.tmp -> C:\Users\kyc45\Desktop\downloader_GUI_t\hitomi_downloaded_youtube\tmpC6731D2C_a.weba
rename (1): C:\Users\kyc45\Desktop\downloader_GUI_t\hitomi_downloaded_youtube\190511 로즈퀸(Rose Queen) 지니 - Hot In Here @금촌통일시장 문화난장어울림공연행사 4K 60P 직캠 Fancam by LIKEY (I10qCqKxW2M).webm -> C:\Users\kyc45\Desktop\downloader_GUI_t\hitomi_downloaded_youtube\tmpC6731D2C_v.webm
-i tmpC6731D2C_v.webm -i tmpC6731D2C_a.weba -c copy -strict experimental -preset ultrafast -shortest tmpC6731D2C_o.mp4
[code]
0
[out]
ffmpeg version 4.1 Copyright (c) 2000-2018 the FFmpeg developers
built with gcc 8.2.1 (GCC) 20181017
configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth
libavutil 56. 22.100 / 56. 22.100
libavcodec 58. 35.100 / 58. 35.100
libavformat 58. 20.100 / 58. 20.100
libavdevice 58. 5.100 / 58. 5.100
libavfilter 7. 40.101 / 7. 40.101
libswscale 5. 3.100 / 5. 3.100
libswresample 3. 3.100 / 3. 3.100
libpostproc 55. 3.100 / 55. 3.100
Input #0, matroska,webm, from 'tmpC6731D2C_v.webm':
Metadata:
encoder : google/video-file
Duration: 00:04:35.19, start: 0.000000, bitrate: 22908 kb/s
Stream #0:0(eng): Video: vp9 (Profile 0), yuv420p(tv, bt709), 3840x2160, SAR 1:1 DAR 16:9, 59.94 fps, 59.94 tbr, 1k tbn, 1k tbc (default)
Input #1, mov,mp4,m4a,3gp,3g2,mj2, from 'tmpC6731D2C_a.weba':
Metadata:
major_brand : mp42
minor_version : 0
compatible_brands: isommp42
creation_time : 2019-05-17T21:29:19.000000Z
Duration: 00:04:35.25, start: 0.000000, bitrate: 710 kb/s
Stream #1:0(und): Video: h264 (Constrained Baseline) (avc1 / 0x31637661), yuv420p(tv, bt709), 640x360 [SAR 1:1 DAR 16:9], 611 kb/s, 29.97 fps, 29.97 tbr, 30k tbn, 59.94 tbc (default)
Metadata:
creation_time : 2019-05-17T21:29:19.000000Z
handler_name : ISO Media file produced by Google Inc. Created on: 05/17/2019.
Stream #1:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 96 kb/s (default)
Metadata:
creation_time : 2019-05-17T21:29:19.000000Z
handler_name : ISO Media file produced by Google Inc. Created on: 05/17/2019.
Output #0, mp4, to 'tmpC6731D2C_o.mp4':
Metadata:
encoder : Lavf58.20.100
Stream #0:0(eng): Video: vp9 (Profile 0) (vp09 / 0x39307076), yuv420p(tv, bt709), 3840x2160 [SAR 1:1 DAR 16:9], q=2-31, 59.94 fps, 59.94 tbr, 16k tbn, 1k tbc (default)
Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 96 kb/s (default)
Metadata:
creation_time : 2019-05-17T21:29:19.000000Z
handler_name : ISO Media file produced by Google Inc. Created on: 05/17/2019.
Stream mapping:
Stream #0:0 -> #0:0 (copy)
Stream #1:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
frame=15505 fps=0.0 q=-1.0 size= 730112kB time=00:04:18.67 bitrate=23122.4kbits/s speed= 517x 
frame=16495 fps=0.0 q=-1.0 Lsize= 773047kB time=00:04:35.17 bitrate=23013.3kbits/s speed= 518x 
video:769427kB audio:3225kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.051162%

Convert success: True
rename (1): C:\Users\kyc45\Desktop\downloader_GUI_t\hitomi_downloaded_youtube\tmpC6731D2C_o.mp4 -> C:\Users\kyc45\Desktop\downloader_GUI_t\hitomi_downloaded_youtube\190511 로즈퀸(Rose Queen) 지니 - Hot In Here @금촌통일시장 문화난장어울림공연행사 4K 60P 직캠 Fancam by LIKEY (I10qCqKxW2M).webm
rename ext .webm --> .mp4
done : https://www.youtube.com/watch?v=I10qCqKxW2M

**Comment by KurtBestor** [comment]
어떤 동영상 플레이어 쓰시나요?

**Comment by Aideln** [comment]
곰플레이어 썼었습니다

**Comment by Aideln** [comment]
> 어떤 동영상 플레이어 쓰시나요?

곰플레이어 썼었습니다
