### ISSUE TITLE
'완전하지 않은 작업' 강제 완료 기능 건의

### ISSUE THREAD

**Issue by Gilmon96** [KurtBestor/Hitomi-Downloader-issues#116]
익헨이나 텀블러에서 다운을 받을때 간혹 "불완전한 작업 다시 시작"을 아무리 다시 눌러도

작업이 완료 되지 않는 경우가 있습니다 예를들어 파일이 10개라면 10개의 파일이 모두

받아졌음에도 불구하고 해당 작업이 9/10으로 계속 주황색 글씨인 '완전하지 않는 상태'로 남아있습니다.

이 작업 상황을 강제적?으로 초록색 글씨인 완료된 작업으로 바꿀수 있는 기능이 있었으면 합니다.

항상 유용하게 잘 사용하고 있습니다 감사합니다!

**Comment by KurtBestor** [comment]
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

테스트 부탁드려요

**Comment by Gilmon96** [comment]
잘 됩니다! 감사합니다!
