### ISSUE TITLE
히토미 다운로더 픽시브 ip 차단

### ISSUE THREAD

**Issue by momokoro1** [KurtBestor/Hitomi-Downloader-issues#1160]
수고 많으십니다. 급 ip 차단을 먹게 되어 좀 당황했는데, pc로는 차단 된 것 같지 않은데, 다운로더로는 차단이 이루어져 있어 로그인 테스트 통과를 못하네요
이 상태에서는 따로 프록시를 지정해주는 것 말고는 방법이 없는가요?

**Comment by lililillilililililil** [comment]
방금 저도 테스트 해 봤는데 안 되네요. 아마 픽시브 측에서 다운로더가 로그인 하던 방식을 막아버린듯 합니다.
히토미다운로더 외의 픽시브 다운로더도 시도해 봤는데 로그인이 안 되는 거로 봐서는 픽시브측이 막은게 확실한 거 같아요.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by momokoro1** [comment]
무사히 이륙했습니다!
감사합니다!

**Comment by kenasis428** [comment]
같은 상황이여서 해봣으나 .. 여전히 IP 일시적 차단 상태입니다.
