### ISSUE TITLE
웹툰 사이트는 지원이 안 되나요?

### ISSUE THREAD

**Issue by haahaha532** [KurtBestor/Hitomi-Downloader-issues#1161]
https://wfwf39.com/list?toon=1503

이런 사이트 혹시 될까 해서 안되던데
이후 지원해주실 계획이 있으신가요?
항상 감사히 잘 쓰고 있습니다.

**Comment by lililillilililililil** [comment]
뉴x끼가 스크립트로 지원하기 떄문에 뉴x끼 보다 더 좋은 점이 없다면 안 해주실 것 같아요.

**Comment by haahaha532** [comment]
> 뉴x끼가 스크립트로 지원하기 떄문에 뉴x끼 보다 더 좋은 점이 없다면 안 해주실 것 같아요.

아 감사합니다! 근데 스크립트로 지원한다는 게 제가 어떻게 하면 받을 수 있는 건가요? 링크 넣어 봐도 안 되네요. 감사합니다

**Comment by haahaha532** [comment]
> 뉴x끼가 스크립트로 지원하기 떄문에 뉴x끼 보다 더 좋은 점이 없다면 안 해주실 것 같아요.

스크립트 받은 다음 newtoki[24] 로 바꾸고 다운로더 프로그램에 밀어넣어서 시작하고 뉴토끼 링크를 넣어도 안되네요... 어떻게 사용하면 되나요?

**Comment by lililillilililililil** [comment]
메뉴 - 스크립트가서 뉴토끼 스크립트 가져오신 뒤에 링크 넣으시면 됩니다.
