### ISSUE TITLE
https://www.pixiv.net is not working anymore

### ISSUE THREAD

**Issue by xZabuzax** [KurtBestor/Hitomi-Downloader-issues#1162]
As the title suggest, https://www.pixiv.net stopped working because the login test is failing.

Hopefully this can be resolved, thanks.

**Comment by KurtBestor** [comment]
Please note: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/1160

**Comment by xZabuzax** [comment]
> Please note: #1160

The new version of Hitomi-Downloader worked perfectly, thanks!

**Comment by xZabuzax** [comment]
Since this issue was fixed a couple of months ago I will close it. If the issue persist then I'll open a new thread about it.
