### ISSUE TITLE
특정 유튜브 영상 다운로드 불가능문제

### ISSUE THREAD

**Issue by STRESSSSS** [KurtBestor/Hitomi-Downloader-issues#1163]
항상 감사하게 잘 사용하고있습니다. (_ _)

https://www.youtube.com/watch?v=bnb8-jpkQnc&has_verified=1
위 링크의 영상을 다운로더로 받으려고하니 계속 다운도 안되고 읽어오는것도 안됩니다.

여러번 시도를 해봤으나 계속 불가능하네요. 
히토미다운로더로 불가능한 유튜브 영상은 없을줄 알았는데 처음으로 막혔습니다.
혹시 해결방법이 있는지 문의드립니다.

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/ytdl-org/youtube-dl/issues/16445
