### ISSUE TITLE
이미 실행되어있다고 나와도 무시하고 강제로 실행할수 있게 해주세요.

### ISSUE THREAD

**Issue by miraclehoshi** [KurtBestor/Hitomi-Downloader-issues#1164]
매번 잘 사용하고 있습니다. 개발자님의 노고에 감사드립니다.

가끔 알 수 없는 이유로 히토미 다운로더가 다운되어 버리는데,

이럴때 다시 실행시키면 어떠한 이유에서인지 이미 실행되고 있다며 실행되지 않습니다.

재부팅(로그아웃)이 답인데, 컴퓨터를 24시간 켜두고 작업하는 사람은 이게 큰 스트레스 입니다..

만약 실행되어 있는데 다시 실행된다면, 이미 실행중이라는 메시지에 추가적으로

[강제 실행하기] 버튼을 만들어 기존 창을 종료하고 강제 실행시키겠다는 메시지를 띄우면 어떨까 하는 생각이 듭니다.

**Comment by KurtBestor** [comment]
한번 더 실행하면 대부분은 될 거예요.
그래도 안 되면 작업관리자에서 다운로더 프로세스, `ffmpeg.exe` 또는 `ffmpeg_xp.exe` 를 모두 종료해주세요.

**Comment by miraclehoshi** [comment]
아 ffmpeg.exe를 사용하는군요 어째 프로세스가 없는데 실행이 안되더라구요. 감사합니다.
