### ISSUE TITLE
xhamster사이트 테스트결과 오류가있네요

### ISSUE THREAD

**Issue by mrdonghyun12** [KurtBestor/Hitomi-Downloader-issues#1165]
2주전 테스트할때는 사이트 도메인?이 xhamster.com < 이런식으로 되어있었는데 

지금은 xhamster.desi 라고 링크가 바뀌어있네요 

이것때문인지 테스트 부탁해주신 걸로 다운이 안됩니다..!

직접 .desi를 .com으로 바꾸면 다운이 되긴하지만 너무 비효율적인거같습니다 ㅠㅠ

맨처음 문의글 https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/1135

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview
