### ISSUE TITLE
계속 이상한 알림이 뜹니다..

### ISSUE THREAD

**Issue by mrdonghyun12** [KurtBestor/Hitomi-Downloader-issues#1166]
현재 PC에서는 이 앱을 실행할 수 없습니다. 

PC버전을 찾으려면 소프트웨어 게시자에게 문의하세요.

---

라는 알림이 화면을 가리면서 자꾸뜨네요.. 

처음 킬때 로드하거나 매 영상, 자료 다운받을때마다 연속으로 뜹니다. 고쳐주실 수 있을까요??

**Comment by KurtBestor** [comment]
해당 작업 <kbd>마우스 우 클릭</kbd> - <kbd>정보... (I)</kbd> 눌러서 나온 내용 보여주세요.
