### ISSUE TITLE
히토미 검색기 질문

### ISSUE THREAD

**Issue by ddt5244** [KurtBestor/Hitomi-Downloader-issues#117]
히토미 검색기창을 2개이상 띄울 수 없나요? 이게 작품들 보면서 작품의 작가를 또 검색하고 하는데 창이 1개밖에 안되면 목록보고 작가검색하고 또 목록 검색해야해서 좀 불편합니다. 쉽게말해 새 창으로 여는 기능은 없나요? 폴더명 지정때문에 테스트버전 쓰고 있습니다.

**Comment by KurtBestor** [comment]
아직은 없습니다.
기술적으로 여러가지 문제가 있어서 좀 더 생각을 해봐야할 것 같네요:
1. 검색기가 여러개 있을 때 무엇을 기준으로 상태를 저장 해야하나
1. 검색기 여러개를 껐다가 새 창을 하나 만들면 어떤 창 상태로 가야하나
1. 검색 중 검색기를 껐다 키면 검색이 계속되어야하나
등등

미래에 해당 기능이 추가될 수도 있어요. 그때까진 북마크 기능을 이용해주세요.
