### ISSUE TITLE
다운받다가 이상한 거뜨다가 꺼져요

### ISSUE THREAD

**Issue by qwesry** [KurtBestor/Hitomi-Downloader-issues#1170]
https://blog.naver.com/qwesry/221639984363
제블러그인데 이미지 올리는 방법을 몰라서 이렇게 올립니다

**Comment by KurtBestor** [comment]
이건 어떤가요?: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview
