### ISSUE TITLE
웹툰 제외처럼 특정 태그도 제외되게 하는건 어려울까요?

### ISSUE THREAD

**Issue by gta9112** [KurtBestor/Hitomi-Downloader-issues#1171]
좋아하는 태그도 있고 기피하는 태그도 있는게
기억은 안나고 태그 하나만 검색할때는
자료가 너무 많다보니 찾는데 길어지기도 해서
태그도 제외할수 있었으면 좋겠어요.

**Comment by KurtBestor** [comment]
`도움말` - `사용법... (F1)` - `고급 검색 - 태그들 (Tags)` 을 보세요.
또는 `옵션` - `설정` - `히토미 / E(x)Hentai / 히요비 설정` - `제외 태그` 에 추가해주세요.
