### ISSUE TITLE
어제부터 마나모아만 다운이 안됩니다.

### ISSUE THREAD

**Issue by Mariecle** [KurtBestor/Hitomi-Downloader-issues#1172]
늘 감사하게 사용중입니다.

어제부터 마나모아만 다운이 안됩니다.
테스트로 다른 곳을 다운해봤는데 정상적으로 작동했습니다.
무엇이 잘못되었는지 짐작이 안가서 도움 부탁 드리려 글을 씁니다.

늘 최신버전을 유지하는 중이라 현재 9/6 오전2시자 베타를 쓰고 있습니다.
dpi 우회는 내장도 써보고 외장도 써보고 했습니다.

아래는 작업 정보를 첨부하겠습니다.
길이가 길어 중복된 정보는 삭제했습니다.
감사합니다.

======
모처럼 치트를 받아서 이세계에 전이했으니까, 맘대로 살고 싶어

version: 2.6d
platform: Windows-10-10.0.18362
gal_num: https://manamoa13.net/bbs/board.php?bo_table=manga&wr_id=1871575
dir: d:\down\comics\Downloads_manamoa\모처럼 치트를 받아서 이세계에 전이했으니까, 맘대로 살고 싶어
zip: d:\down\comics
type: manamoa
artist: 풋챠U
url: https://manamoa13.net/bbs/page.php?hid=manga_detail&manga_id=689
valid: True
done: False
range: None
range_p: None
single: False
time: 1567742743.47 (Sep 6)
tags: []
goodbyedpi: False
lock: False
color: downloading
paused: False

[Gallery]
None

[File Names]
[0001] d:\down\comics\Downloads_manamoa\모처럼 치트를 받아서 이세계에 전이했으니까, 맘대로 살고 싶어\모처럼 치트를 받아서 이세계에 전이했으니까, 맘대로 살고 싶어 14화\0000.jpg
[0002] d:\down\comics\Downloads_manamoa\모처럼 치트를 받아서 이세계에 전이했으니까, 맘대로 살고 싶어\모처럼 치트를 받아서 이세계에 전이했으니까, 맘대로 살고 싶어 14화\0001.jpg
[0003] d:\down\comics\Downloads_manamoa\모처럼 치트를 받아서 이세계에 전이했으니까, 맘대로 살고 싶어\모처럼 치트를 받아서 이세계에 전이했으니까, 맘대로 살고 싶어 14화\0002.jpg
[0004] d:\down\comics\Downloads_manamoa\모처럼 치트를 받아서 이세계에 전이했으니까, 맘대로 살고 싶어\모처럼 치트를 받아서 이세계에 전이했으니까, 맘대로 살고 싶어 14화\0003.jpg

[URLs]
[0001] LazyUrl(https://manamoa13.net/bbs/board.php?bo_table=manga&wr_id=1871575) ---> https://ironmancdn.xyz/upload/1269289452b70bc91cb663998a95a349.jpg
[0002] LazyUrl(https://manamoa13.net/bbs/board.php?bo_table=manga&wr_id=1871575) ---> https://ironmancdn.xyz/upload/4ec63b42b0c2aa30f854f4aea5b28475.jpg
[0003] LazyUrl(https://manamoa13.net/bbs/board.php?bo_table=manga&wr_id=1871575) ---> https://ironmancdn.xyz/upload/088674e49b6c7746dccd46684399bfa0.jpg

[Messages]
redirect: https://manamoa13.net/bbs/page.php?hid=manga_detail&manga_id=689
dirFormat: title
[seed] 모처럼 치트를 받아서 이세계에 전이했으니까, 맘대로 살고 싶어 14화 0

Fail : \\?\d:\down\comics\Downloads_manamoa\모처럼 치트를 받아서 이세계에 전이했으니까, 맘대로 살고 싶어\모처럼 치트를 받아서 이세계에 전이했으니까, 맘대로 살고 싶어 14화/0001.jpg
Traceback (most recent call last):
File "downloader", line 755, in download
IOError: [Errno 22] invalid mode ('wb') or filename: u'\\\\?\\d:\\down\\comics\\Downloads_manamoa\\\ubaa8\ucc98\ub7fc \uce58\ud2b8\ub97c \ubc1b\uc544\uc11c \uc774\uc138\uacc4\uc5d0 \uc804\uc774\ud588\uc73c\ub2c8\uae4c, \ub9d8\ub300\ub85c \uc0b4\uace0 \uc2f6\uc5b4\\\ubaa8\ucc98\ub7fc \uce58\ud2b8\ub97c \ubc1b\uc544\uc11c \uc774\uc138\uacc4\uc5d0 \uc804\uc774\ud588\uc73c\ub2c8\uae4c, \ub9d8\ub300\ub85c \uc0b4\uace0 \uc2f6\uc5b4 14\ud654/0001.jpg'

Fail : \\?\d:\down\comics\Downloads_manamoa\모처럼 치트를 받아서 이세계에 전이했으니까, 맘대로 살고 싶어\모처럼 치트를 받아서 이세계에 전이했으니까, 맘대로 살고 싶어 14화/0003.jpg
Traceback (most recent call last):
File "downloader", line 755, in download
IOError: [Errno 22] invalid mode ('wb') or filename: u'\\\\?\\d:\\down\\comics\\Downloads_manamoa\\\ubaa8\ucc98\ub7fc \uce58\ud2b8\ub97c \ubc1b\uc544\uc11c \uc774\uc138\uacc4\uc5d0 \uc804\uc774\ud588\uc73c\ub2c8\uae4c, \ub9d8\ub300\ub85c \uc0b4\uace0 \uc2f6\uc5b4\\\ubaa8\ucc98\ub7fc \uce58\ud2b8\ub97c \ubc1b\uc544\uc11c \uc774\uc138\uacc4\uc5d0 \uc804\uc774\ud588\uc73c\ub2c8\uae4c, \ub9d8\ub300\ub85c \uc0b4\uace0 \uc2f6\uc5b4 14\ud654/0003.jpg'

Fail : \\?\d:\down\comics\Downloads_manamoa\모처럼 치트를 받아서 이세계에 전이했으니까, 맘대로 살고 싶어\모처럼 치트를 받아서 이세계에 전이했으니까, 맘대로 살고 싶어 14화/0017.jpg
Traceback (most recent call last):
File "downloader", line 755, in download
IOError: [Errno 22] invalid mode ('wb') or filename: u'\\\\?\\d:\\down\\comics\\Downloads_manamoa\\\ubaa8\ucc98\ub7fc \uce58\ud2b8\ub97c \ubc1b\uc544\uc11c \uc774\uc138\uacc4\uc5d0 \uc804\uc774\ud588\uc73c\ub2c8\uae4c, \ub9d8\ub300\ub85c \uc0b4\uace0 \uc2f6\uc5b4\\\ubaa8\ucc98\ub7fc \uce58\ud2b8\ub97c \ubc1b\uc544\uc11c \uc774\uc138\uacc4\uc5d0 \uc804\uc774\ud588\uc73c\ub2c8\uae4c, \ub9d8\ub300\ub85c \uc0b4\uace0 \uc2f6\uc5b4 14\ud654/0017.jpg'

use alternative url: https://ironmancdn.xyz/upload/358b8e151d0db45aba3b7dfe59edf4b7.jpg --> https://ironmancdn.xyz/upload/358b8e151d0db45aba3b7dfe59edf4b7.jpg

Fail : \\?\d:\down\comics\Downloads_manamoa\모처럼 치트를 받아서 이세계에 전이했으니까, 맘대로 살고 싶어\모처럼 치트를 받아서 이세계에 전이했으니까, 맘대로 살고 싶어 14화/0012.jpg
Traceback (most recent call last):
File "downloader", line 755, in download
IOError: [Errno 22] invalid mode ('wb') or filename: u'\\\\?\\d:\\down\\comics\\Downloads_manamoa\\\ubaa8\ucc98\ub7fc \uce58\ud2b8\ub97c \ubc1b\uc544\uc11c \uc774\uc138\uacc4\uc5d0 \uc804\uc774\ud588\uc73c\ub2c8\uae4c, \ub9d8\ub300\ub85c \uc0b4\uace0 \uc2f6\uc5b4\\\ubaa8\ucc98\ub7fc \uce58\ud2b8\ub97c \ubc1b\uc544\uc11c \uc774\uc138\uacc4\uc5d0 \uc804\uc774\ud588\uc73c\ub2c8\uae4c, \ub9d8\ub300\ub85c \uc0b4\uace0 \uc2f6\uc5b4 14\ud654/0012.jpg'

use alternative url: https://ironmancdn.xyz/upload/c61c4448008cee8b72ae36310453fc93.jpg --> https://ironmancdn.xyz/upload/c61c4448008cee8b72ae36310453fc93.jpg
use alternative url: https://ironmancdn.xyz/upload/08f9a380d5e32207a34ac4f09bd48fb6.jpg --> https://ironmancdn.xyz/upload/08f9a380d5e32207a34ac4f09bd48fb6.jpg
use alternative url: https://ironmancdn.xyz/upload/34bdb05635e3c4ef4e7131d1f50afca3.jpg --> https://ironmancdn.xyz/upload/34bdb05635e3c4ef4e7131d1f50afca3.jpg
use alternative url: https://ironmancdn.xyz/upload/a75ec763d96ca650930960c2323d8dd2.jpg --> https://ironmancdn.xyz/upload/a75ec763d96ca650930960c2323d8dd2.jpg

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by Mariecle** [comment]
잘 됩니다. 빠른 수정 정말 감사드립니다.
