### ISSUE TITLE
하단에 메모리에러가 나면서 CPU를 과도하게 사용합니다

### ISSUE THREAD

**Issue by istake** [KurtBestor/Hitomi-Downloader-issues#118]
![image](https://user-images.githubusercontent.com/25282782/40999155-04558466-6945-11e8-86eb-9a2107b1c443.png)

윈7입니다

**Comment by KurtBestor** [comment]
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

이건 어떤가요?

**Comment by KurtBestor** [comment]
오랫동안 답이 없으셔서 닫습니다
