### ISSUE TITLE
옵션에서 갤러리 정보 파일 생성을 꺼도 파일이 생성됩니다

### ISSUE THREAD

**Issue by tlzmflt** [KurtBestor/Hitomi-Downloader-issues#1180]
옵션에서 갤러리 정보 파일 생성을 꺼도 파일이 생성됩니다

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by tlzmflt** [comment]
해결되었습니다.
