### ISSUE TITLE
갤러리 정보 클릭시 무반응

### ISSUE THREAD

**Issue by wpfhfpr** [KurtBestor/Hitomi-Downloader-issues#1181]
버그 발견한 것 같습니다. 검색기에서 오른쪽클릭- 갤리리 정보나 썸네일 클릭시 뜨던 갤러리 정보가 반응하지 않네요

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by wpfhfpr** [comment]
테스트 완료. 다만 avast에서 자꾸 검사를 해서 애먹었네요.이전에는 딱히 문제없었는데...
갤러리 정보 확인 가능합니다.
