### ISSUE TITLE
v2.7 업데이트 진행 오류

### ISSUE THREAD

**Issue by bhkim0115** [KurtBestor/Hitomi-Downloader-issues#1182]
v2.6에서 자동 업데이트를 실행하면 업데이트 파일을 자동으로 받은뒤 설치중
에러창과 Dos창이 나오면서 hitomi_downloader_GUI.exe 파일이 제거된상태로 
진행이 멈추면서 Readme 텍스트 파일만 실행됩니다.
![1](https://user-images.githubusercontent.com/49972127/64471465-f5254d80-d18c-11e9-80e5-85f933bfc265.PNG)
![2](https://user-images.githubusercontent.com/49972127/64471467-f9ea0180-d18c-11e9-9dea-545899f32557.PNG)

exe파일만 다시 설치해서 실행하면 업데이트는 안된상태로 나옵니다...

**Comment by KurtBestor** [comment]
자동 업데이트가 안 되면 수동으로 다운로드해서 업데이트 해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/latest
