### ISSUE TITLE
Sankaku 페이지지정했지만 2000장 에서 다운 완료되는 이슈

### ISSUE THREAD

**Issue by moonhole0512** [KurtBestor/Hitomi-Downloader-issues#1185]
테스트한 페이지는 총7052장이 있었습니다.
테스트결과 2000에서 정지되었습니다.
페이지 지정 ~7052로 테스트하였으며 1~7052도 동일한 결과 였습니다.

*로그인 에러가 발생해서 Sankaku 사이트 로그인후 테스트하였습니다.
pixiv처럼 로그인 처리가 필요할것 같습니다.

------------------------
[chan] mogudan

version: 2.7
platform: Windows-10-10.0.18362
gal_num: https://chan.sankakucomplex.com/?tags=mogudan
dir: G:\Image_Adult\hitomi_sankaku\[chan] mogudan
zip: 
type: sankaku
artist: None
url: https://chan.sankakucomplex.com/?tags=mogudan
valid: True
done: True
range: ~ 7052
range_p: None
single: False
time: 1567934195.55 (Sep 8)
tags: []
goodbyedpi: False
lock: False
color: done
paused: False

[Gallery]
None

[File Names]
[0001] G:\Image_Adult\hitomi_sankaku\[chan] mogudan\17100466.png
[0002] G:\Image_Adult\hitomi_sankaku\[chan] mogudan\17051477.jpg
[0003] G:\Image_Adult\hitomi_sankaku\[chan] mogudan\14102595.jpg
[0004] G:\Image_Adult\hitomi_sankaku\[chan] mogudan\14102605.jpg
[0005] G:\Image_Adult\hitomi_sankaku\[chan] mogudan\17149365.jpg
//
//--------------------------------------------------------------
문자수 제한에 따라 큰 의미없는 내용 제거
//--------------------------------------------------------------
//
[1995] G:\Image_Adult\hitomi_sankaku\[chan] mogudan\12290756.jpg
[1996] G:\Image_Adult\hitomi_sankaku\[chan] mogudan\12290729.jpg
[1997] G:\Image_Adult\hitomi_sankaku\[chan] mogudan\12290707.jpg
[1998] G:\Image_Adult\hitomi_sankaku\[chan] mogudan\12290684.jpg
[1999] G:\Image_Adult\hitomi_sankaku\[chan] mogudan\12290665.jpg
[2000] G:\Image_Adult\hitomi_sankaku\[chan] mogudan\12290631.jpg

[URLs]
[0001] G:\Image_Adult\hitomi_sankaku\[chan] mogudan\17100466.png
[0002] G:\Image_Adult\hitomi_sankaku\[chan] mogudan\17051477.jpg
[0003] G:\Image_Adult\hitomi_sankaku\[chan] mogudan\14102595.jpg
[0004] G:\Image_Adult\hitomi_sankaku\[chan] mogudan\14102605.jpg
[0005] G:\Image_Adult\hitomi_sankaku\[chan] mogudan\17149365.jpg
//
//--------------------------------------------------------------
문자수 제한에 따라 큰 의미없는 내용 제거
//--------------------------------------------------------------
//
[2000] G:\Image_Adult\hitomi_sankaku\[chan] mogudan\12290631.jpg

[Messages]
login... 3
https://chan.sankakucomplex.com/?tags=mogudan
https://chan.sankakucomplex.com/?next=17093902&tags=mogudan&page=2
https://chan.sankakucomplex.com/?next=17025527&tags=mogudan&page=3
https://chan.sankakucomplex.com/?next=17025506&tags=mogudan&page=4
https://chan.sankakucomplex.com/?next=16976928&tags=mogudan&page=5
https://chan.sankakucomplex.com/?next=16774406&tags=mogudan&page=6
https://chan.sankakucomplex.com/?next=16773168&tags=mogudan&page=7
https://chan.sankakucomplex.com/?next=16771999&tags=mogudan&page=8
https://chan.sankakucomplex.com/?next=16719035&tags=mogudan&page=9
https://chan.sankakucomplex.com/?next=16718396&tags=mogudan&page=10
https://chan.sankakucomplex.com/?next=16717825&tags=mogudan&page=11
https://chan.sankakucomplex.com/?next=16688236&tags=mogudan&page=12
https://chan.sankakucomplex.com/?next=16687193&tags=mogudan&page=13
https://chan.sankakucomplex.com/?next=16686611&tags=mogudan&page=14
https://chan.sankakucomplex.com/?next=16642808&tags=mogudan&page=15
https://chan.sankakucomplex.com/?next=16642218&tags=mogudan&page=16
https://chan.sankakucomplex.com/?next=16590334&tags=mogudan&page=17
https://chan.sankakucomplex.com/?next=16590170&tags=mogudan&page=18
https://chan.sankakucomplex.com/?next=16590045&tags=mogudan&page=19
https://chan.sankakucomplex.com/?next=16589909&tags=mogudan&page=20
https://chan.sankakucomplex.com/?next=16589795&tags=mogudan&page=21
https://chan.sankakucomplex.com/?next=16589682&tags=mogudan&page=22
https://chan.sankakucomplex.com/?next=16447048&tags=mogudan&page=23
https://chan.sankakucomplex.com/?next=16387060&tags=mogudan&page=24
https://chan.sankakucomplex.com/?next=16383594&tags=mogudan&page=25
https://chan.sankakucomplex.com/?next=16356667&tags=mogudan&page=26
https://chan.sankakucomplex.com/?next=16298579&tags=mogudan&page=27
https://chan.sankakucomplex.com/?next=16280240&tags=mogudan&page=28
https://chan.sankakucomplex.com/?next=16268945&tags=mogudan&page=29
https://chan.sankakucomplex.com/?next=16258041&tags=mogudan&page=30
https://chan.sankakucomplex.com/?next=16108745&tags=mogudan&page=31
https://chan.sankakucomplex.com/?next=16089385&tags=mogudan&page=32
https://chan.sankakucomplex.com/?next=15587719&tags=mogudan&page=33
https://chan.sankakucomplex.com/?next=15587486&tags=mogudan&page=34
https://chan.sankakucomplex.com/?next=15510713&tags=mogudan&page=35
https://chan.sankakucomplex.com/?next=15140806&tags=mogudan&page=36
https://chan.sankakucomplex.com/?next=15140513&tags=mogudan&page=37
https://chan.sankakucomplex.com/?next=15032423&tags=mogudan&page=38
https://chan.sankakucomplex.com/?next=14955105&tags=mogudan&page=39
https://chan.sankakucomplex.com/?next=14916656&tags=mogudan&page=40
https://chan.sankakucomplex.com/?next=14916306&tags=mogudan&page=41
https://chan.sankakucomplex.com/?next=14840253&tags=mogudan&page=42
https://chan.sankakucomplex.com/?next=14839535&tags=mogudan&page=43
https://chan.sankakucomplex.com/?next=14838575&tags=mogudan&page=44
https://chan.sankakucomplex.com/?next=14786600&tags=mogudan&page=45
https://chan.sankakucomplex.com/?next=14786416&tags=mogudan&page=46
https://chan.sankakucomplex.com/?next=14773329&tags=mogudan&page=47
https://chan.sankakucomplex.com/?next=14772960&tags=mogudan&page=48
https://chan.sankakucomplex.com/?next=14772499&tags=mogudan&page=49
https://chan.sankakucomplex.com/?next=14772098&tags=mogudan&page=50
https://chan.sankakucomplex.com/?next=14771563&tags=mogudan&page=51
https://chan.sankakucomplex.com/?next=14764502&tags=mogudan&page=52
https://chan.sankakucomplex.com/?next=14673773&tags=mogudan&page=53
https://chan.sankakucomplex.com/?next=14625170&tags=mogudan&page=54
https://chan.sankakucomplex.com/?next=14589285&tags=mogudan&page=55
https://chan.sankakucomplex.com/?next=14558070&tags=mogudan&page=56
https://chan.sankakucomplex.com/?next=14549813&tags=mogudan&page=57
https://chan.sankakucomplex.com/?next=14545941&tags=mogudan&page=58
https://chan.sankakucomplex.com/?next=14545691&tags=mogudan&page=59
429 Too many requests... wait 120 secs
https://chan.sankakucomplex.com/?next=14545691&tags=mogudan&page=59
https://chan.sankakucomplex.com/?next=14419578&tags=mogudan&page=60
https://chan.sankakucomplex.com/?next=14400516&tags=mogudan&page=61
https://chan.sankakucomplex.com/?next=14364667&tags=mogudan&page=62
https://chan.sankakucomplex.com/?next=14266031&tags=mogudan&page=63
https://chan.sankakucomplex.com/?next=14265884&tags=mogudan&page=64
https://chan.sankakucomplex.com/?next=14224344&tags=mogudan&page=65
https://chan.sankakucomplex.com/?next=14176287&tags=mogudan&page=66
https://chan.sankakucomplex.com/?next=14102595&tags=mogudan&page=67
https://chan.sankakucomplex.com/?next=13979977&tags=mogudan&page=68
https://chan.sankakucomplex.com/?next=13979951&tags=mogudan&page=69
https://chan.sankakucomplex.com/?next=13979926&tags=mogudan&page=70
https://chan.sankakucomplex.com/?next=13839781&tags=mogudan&page=71
https://chan.sankakucomplex.com/?next=13839011&tags=mogudan&page=72
https://chan.sankakucomplex.com/?next=13838292&tags=mogudan&page=73
https://chan.sankakucomplex.com/?next=13817831&tags=mogudan&page=74
https://chan.sankakucomplex.com/?next=13807341&tags=mogudan&page=75
https://chan.sankakucomplex.com/?next=13716497&tags=mogudan&page=76
https://chan.sankakucomplex.com/?next=13716220&tags=mogudan&page=77
https://chan.sankakucomplex.com/?next=13715914&tags=mogudan&page=78
https://chan.sankakucomplex.com/?next=13701998&tags=mogudan&page=79
https://chan.sankakucomplex.com/?next=13677355&tags=mogudan&page=80
https://chan.sankakucomplex.com/?next=13672592&tags=mogudan&page=81
https://chan.sankakucomplex.com/?next=13640840&tags=mogudan&page=82
https://chan.sankakucomplex.com/?next=13640461&tags=mogudan&page=83
https://chan.sankakucomplex.com/?next=13573155&tags=mogudan&page=84
https://chan.sankakucomplex.com/?next=13533484&tags=mogudan&page=85
https://chan.sankakucomplex.com/?next=13428961&tags=mogudan&page=86
https://chan.sankakucomplex.com/?next=13369408&tags=mogudan&page=87
https://chan.sankakucomplex.com/?next=13296038&tags=mogudan&page=88
https://chan.sankakucomplex.com/?next=12981890&tags=mogudan&page=89
https://chan.sankakucomplex.com/?next=12948936&tags=mogudan&page=90
https://chan.sankakucomplex.com/?next=12947971&tags=mogudan&page=91
https://chan.sankakucomplex.com/?next=12947006&tags=mogudan&page=92
https://chan.sankakucomplex.com/?next=12926011&tags=mogudan&page=93
https://chan.sankakucomplex.com/?next=12925262&tags=mogudan&page=94
https://chan.sankakucomplex.com/?next=12925020&tags=mogudan&page=95
https://chan.sankakucomplex.com/?next=12661640&tags=mogudan&page=96
https://chan.sankakucomplex.com/?next=12292667&tags=mogudan&page=97
https://chan.sankakucomplex.com/?next=12292277&tags=mogudan&page=98
https://chan.sankakucomplex.com/?next=12291711&tags=mogudan&page=99
https://chan.sankakucomplex.com/?next=12291159&tags=mogudan&page=100
https://chan.sankakucomplex.com/?next=12290599&tags=mogudan&page=101
EOT: https://chan.sankakucomplex.com/?tags=mogudan

**Comment by KurtBestor** [comment]
브라우저에서 로그인하고 다음 링크 들어가면 어떻게 뜨나요?:
https://chan.sankakucomplex.com/?next=12290599&tags=mogudan&page=101

브러우저에서 로그인 한 건 프로그램에서 영향이 없어요. 어쩌다 에러 뜰 때 있는데 그 땐 다시 시도하시면 돼요.

**Comment by rlacks1237** [comment]
로그아웃 상태에선 저 링크는 못들어가네요 25페이지 이상이라고하면서

**Comment by rlacks1237** [comment]
+로그인 후는 Error: You can only view up to 1000 pages of results
라고뜨네요

**Comment by KurtBestor** [comment]
사이트 자체에서 2000 장 이상은 보지 못하는 것 같네요.

**Comment by moonhole0512** [comment]
https://chan.sankakucomplex.com/?tags=mogudan

페이지 없는 링크에서 오토페이징으로 로드하면 2000장이상 확인가능하네요.
오토스크롤로 97페이지까지 가다가 리퀘스트 너무 많다고 걸렸네요 ㅎ;
소스보려고 html저장해서 같이 저된 섬네일 파일 3502개 저장되었습니다.(광고 이미지도 같이저장된;)
이부분 이용해서 101페이지 에러 우회하거나.
수동으로 전체 페이지 로딩하고 링크 수집해서 다운할수도 있을것 같습니다.
