### ISSUE TITLE
hitomi 다운받고 작가별로 자동으로 분류되었으면 합니다.

### ISSUE THREAD

**Issue by wldn3394** [KurtBestor/Hitomi-Downloader-issues#1187]
100개정도 넘어가면 한페이지에서 보기 힘들어집니다
히토미 다운받으면 자동으로 작가이름별 새문서가 만들어져서 분류되었으면 합니다

**Comment by lililillilililililil** [comment]
새 폴더 말하시는거면 폴더명 형식을 [artist]/title (id) 이런식으로 하면 작가별로 분류되긴 해요
