### ISSUE TITLE
v2.7 업데이트 후 문제

### ISSUE THREAD

**Issue by Stillehavet** [KurtBestor/Hitomi-Downloader-issues#1188]
실행할 때마다 다운로드 받은 목록, 검색 옵션(작가, 태그 등)이 초기화됩니다.
종료할 때에는 정상 종료됩니다.
v2.6d에서는 정상 작동합니다.

**Comment by KurtBestor** [comment]
저장 후에 `[실행파일명].ini` 파일이 실행파일과 같은 폴더에 생기나요? 만약 생겼다면 해당 파일 보내주시면 분석해볼게요.
