### ISSUE TITLE
로컬 변경 문제

### ISSUE THREAD

**Issue by aksghkqhrl** [KurtBestor/Hitomi-Downloader-issues#1191]
컴퓨터의 로컬을 변경해버리면 히토미 다운로더 실행이 안되네요.

해외의 온라인 게임을 즐겨하다보니 번거로움이 있어서 이런 부분은 따로 계획이 없으신가요?

**Comment by KurtBestor** [comment]
로컬을 변경한다는 게 어떤 의미인가요?

**Comment by aksghkqhrl** [comment]
> 로컬을 변경한다는 게 어떤 의미인가요?

![0001](https://user-images.githubusercontent.com/47558641/64708299-5cc1fc80-d4ef-11e9-924b-925da7181d07.png)

해외에 게임을 할려면 저렇게 변경을 해야하는데 저렇게 변경을 하게되면 다운로더 실행이 안됩니다.

일부 외국서버를 접속할려면 VPN 을 사용하거나 해야하는데 다운로더를 키면 자동으로 우회가 되다보니 ...

**Comment by KurtBestor** [comment]
제 쪽에선 시스템 로캘을 한국이나 미국으로 바꿔도 잘 실행되네요.
실행 됐을 때 <kbd>Ctrl</kbd> + <kbd>Alt</kbd> + <kbd>C</kbd> 눌러서 콘솔 창 띄우고 다음 내용 입력하고 <kbd>Enter</kbd> 눌러서 나온 내용 보여주세요:
```
fucking_encoding.encodings 
```
