### ISSUE TITLE
업데이트 후로 몇가지 오류가 있습니다

### ISSUE THREAD

**Issue by maybe74** [KurtBestor/Hitomi-Downloader-issues#1192]
다운로드 하면 거의 절반이 중간에 에러나서 주황색으로 변하네요

그리고 다운로드 성공이던 실패던 상관없이 해당 폴더 안에 info.txt 파일이 생깁니다

내용은 별다른 건 없고 해당 작품 번호, 작가, 태그 등등 이정도만 들어있네요

**Comment by KurtBestor** [comment]
해당 작업 `마우스 우 클릭` - `정보...` 눌러서 나온 내용 보여주세요.
