### ISSUE TITLE
도와주세요..

### ISSUE THREAD

**Issue by wjdeofla1358** [KurtBestor/Hitomi-Downloader-issues#1193]
옵션에서 dpi 우회를 설정해도 계속 오류가 나네요...... 그리고 밝은 회색 상태에서 다운로드가 진행되지 않습니다....
![캡처](https://user-images.githubusercontent.com/55176289/64671165-7f79f400-d4a2-11e9-8d9b-68e93d4b42a9.PNG)

**Comment by wjdeofla1358** [comment]
재부팅을 계속 시도해도 그대로고 따로 켜져있는 vpn 우회를 꺼도 그대로 입니다...

**Comment by wjdeofla1358** [comment]
가만히 내버려 두니 밝은 회색에서 주황색으로 바뀌었네요

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/546#issuecomment-464473160

**Comment by wjdeofla1358** [comment]
빠른 답변 감사합니다.... 제가 컴맹이라... 일단 열심히 시도해 보겠습니다....

**Comment by wjdeofla1358** [comment]
마이크로소프트 홈페이지에서 KB3033929를 다운받았는데,, 이런창이 뜨네요,,,,, 이런경우에는 어떻게 해야하나요?.....
![캡처](https://user-images.githubusercontent.com/55176289/64679670-26688b00-d4b7-11e9-94f5-a9a4f0b96aa0.PNG)

**Comment by wjdeofla1358** [comment]
마이크로소프트 홈페이지에서 KB3033929를 다운받았는데... 이런창이 뜨네요... 이런경우에는 어떻게 해야하나요?...
![캡처](https://user-images.githubusercontent.com/55176289/64679778-5e6fce00-d4b7-11e9-89ee-a030680e3458.PNG)

**Comment by wjdeofla1358** [comment]
괜찮아진것 같습니다. 감사합니다.
