### ISSUE TITLE
info.txt 버그 및 추가건의

### ISSUE THREAD

**Issue by rakukracha** [KurtBestor/Hitomi-Downloader-issues#1197]
1. info.txt 무조건 작성하는 버그
2.7버전부터인지 모르겠는데
히토미에서 info.txt라는거 작성하는게 새로 생겼더군요.
그런데 이게 설정에 켜기 끄기 버튼은 있는데,
이거 설정에 관계없이 무조건 info.txt를 작성합니다.
프로그램 껐다켰다 해보고 버튼도 껐다켰다해보고
아예 재부팅도 해보고 다 해봤습니다만 도저히 info.txt작성기능이 진짜로 꺼지진 않네요.
버그로 보이는데 확인해주시면 감사하겠습니다.

2. 멀티주소 한번에 추가
밀려있는거 한번에 받으려 할때 하나씩 주소 추가줄에 드래그앤드롭하거나
혹은 주소하나씩 복붙하게 되면 이미 시작된 다운로드에 밀려서 렉으로 작성이 어렵습니다. ㅠㅠ
그래서 건의드리는데 일단 기존 기능은 그대로 두고,
새창 열어서 textbox(뉴스기사 댓글창처럼 여러줄 되는거) 여러줄의 링크주소를 새줄로 하나씩 입력하고
다운목록 추가는 밑에 추가버튼 누르면 한꺼번에 추가 해주는 기능이 있으면 좋겠습니다.
(위의 뉴스댓글 예시와 마찬가지로 댓글 입력하고 댓글 등록하는 개념과 유사하겠네요.)
그렇게하면 필요한만큼 끊어서 한번에 처리하기가 좋겠더군요.
물론 현행처럼 브라우저에서 끌어와 멀티입력박스에 드래그앤드롭하면 맨뒤에 추가해주는 기능도 있으면 좋겠구요.

3. Artist 묶어서 받기
2번 방식으로 할때의 문제는 다른 아티스트들이 중구난방으로 섞이는 수가 생깁니다.
그리고 순차적으로 맞췄더라도 용량에 따라 늦게 다운이 완료되는 것들이 생기구요.
이걸 수정날짜순으로 정렬하면 아티스트가 뒤섞여 보기에 복잡해집니다.
그러므로 한명의 아티스트끼리 묶어 다운로드(압축완료까지) 후 그 다음 아티스트 다운으로 넘어가는 기능이 있으면 좋겠습니다.
그리고 2번처럼 멀티추가시 아티스트 정보를 앞에 있는것에 맞춰서 그룹으로 순서를 맞춰주면 좋을듯하구요.
(정 복잡해서 안되면 그냥 알파벳순으로 추가해주셔도 됨.)
이건 실제구현하면 조금(...아니... 많이..) 헷갈릴수 있으니 그냥 한번 생각이라도 해주세요. ㅠㅠ

4. 번역/미번(역) 파일명 작성규칙
설정에 보면 폴더/파일명을 작성하는 규칙에
[lang] 이라는 부분이 있더군요.
저같은 경우는 그냥 [번역] [미번] 이런식으로 구분하는데 가능하시면 이런 분류의 규칙도 추가해주시면 감사하겠습니다. ㅠㅠ

5. 윈도우 종료시 자동종료
컴퓨터를 아무생각없이 껐는데 안꺼져서 당황하는 경우가 종종 있는데
알고보니 히토미 다운로더가 가로 막더군요.
현재까지의 작업을 저장하고 종료할것인지 그냥 종료할것인지 묻는 확인창이 막은것이더군요.
프로그래밍 조금 배운 바로는
종료할때 중간에 가로채는 이벤트 함수에서 확인창을 띄울때
기본 들어가는 Cancel이라는 변수에서 "사용자 종료"인지 "윈도우 종료"인지 확인해주는
Enum상수가 날아오는 것으로 알고 있습니다.
(저거 2가지 외에도 여러가지 있더군요)
(소스가 공개되었다면 어느부분인지 정확하게 찍어드릴텐데, 간단한 파트니 설명만 대강 보셔도 어느 부분인지 아실듯...)
사용자 종료일때만 확인창 띄우고,
윈도우 종료일때는 원하시는대로 저장을 기본값으로 하시거나 저장안함을 기본값으로 해서
윈도우 종료를 방해하지 않고 히토미 다운로더도 같이 종료되도록 수정해주시면 감사하겠습니다.

첫 문의와 건의인데 너무 한꺼번에 많은걸 적었네요.
되는 부분이나마 처리해주시면 정말 감사하겠습니다.
다 그렇게 심각한건 아니니 여유되실때 하나씩 생각해주시면 감사하겠습니다.

현재버전은 v2.7입니다.
읽어주셔서 감사합니다. ^^

**Comment by rakukracha** [comment]
오오~
1~5번 전부 다 잘되는군요.
이미 있는 기능인것도 몰랐던것도 있고 번거롭게 해드려서 죄송스럽네요. ㅠㅠ
특히 멀티입력과 폴더분류 기능 같은건 전혀 몰랐었군요. ㅠㅠ

4번에서 더 좋은 방법이 있나 싶긴 한데
일단
[artist][lang==korean?번역:미번;] title (id)
이런 프리셋만 하나 있으면 좋을거 같습니다.

아니면 아예 lang 쓸 사람들은 언어 그대로 표시할테고
나머지는 번역/미번 이정도로 구분할 사람들이 다일테니
무조건 korean과 나머지로 구분한다고 치고
[artist][(lang:번역|미번)] title (id)
이런식의 문법이 생기면 어떨까요?
(단순화하긴 했지만 오류 여지가 커서 이건 좀 그렇군요. ㅠㅠ)


저는 천천히 보실줄 알았는데 정말 빠르게 적용해주셨군요.
빠른 피드백과 적용 정말 감사합니다. ^^

**Comment by rakukracha** [comment]
앗....
이거 말씀드리기 죄송스러운 버그가 생겼네요. ㅠㅠ
제가 히토미, 마나모아에서 히토미 다운로더를 이용하는데요

마나모아 다운 받아봤는데
마나모아에서 lang==A?B:C; 태그를 가져와서 이상하게 생성해버립니다.

제가 위에 언급한 프리셋
[artist][lang==korean?번역:미번;] title (id)
이걸 적용해뒀는데
히토미는 당연히 잘되나
마나모아 작품을 받으면

기존에는
"[작가명] 작품명"의 폴더가 생기고 그 밑에 저장하는데

lang문법을 적용하면
"[작가명][Korean==korean？번역：미번;] 작품명"
이렇게 처리되지 않은 상태로 폴더가 생겨버리네요.

(물론 기본 프리셋에서도 마찬가지 현상이 발생합니다)



저로서는 마나모아는 다운받고 따로 압축하기에
이건 그닥 상관없는 부분입니다만
다른분들이 불편하지 않을까 싶네요. ㅠㅠ

제가 굳이 건의 안했으면 이런일 없었을텐데. ㅠㅠ

**Comment by KurtBestor** [comment]
깜빡하고 말 안했는데 v2.7a 에선 해결됐어요.
