### ISSUE TITLE
webui 계획은 없으실까요...

### ISSUE THREAD

**Issue by proplcy** [KurtBestor/Hitomi-Downloader-issues#1199]
docker 에 올라간다든가... nas 에서 쓰고 싶어요. ㅠ 매번 컴퓨터 켜놓기가 번거롭습니다.

언젠가 계획이 있어서 나오면 좋을거 같네요.

**Comment by KurtBestor** [comment]
데스크톱 외 플랫폼은 계획이 없어요. 컴으로 다운로드하고 다운로드 한 파일만 공유하세요.

**Comment by proplcy** [comment]
> 데스크톱 외 플랫폼은 계획이 없어요. 컴으로 다운로드하고 다운로드 한 파일만 공유하세요.

답변 감사합니다. nas를 쓰고 있어서...점점 데스크톱을 쓸 일이 별로 없더라구요. 모바일로 처리하다보니.. 항상 감사합니다~
