### ISSUE TITLE
폰허브 동영상 다운로드시 불완전한 작업으로 완료됩니다

### ISSUE THREAD

**Issue by techromancer789** [KurtBestor/Hitomi-Downloader-issues#12]
히토미나 유튜브 등은 정상적으로 다운로드가 완료되지만 폰허브에 한해서만 불완전한것같습니다
100%까지 다운로드는 되지만 다운로더 작업색이 초록색이 아닌 주황색으로만 완료됩니다

**Comment by KurtBestor** [comment]
고쳤습니다. 고친 버전은 다음 링크에서 확인하실 수 있습니다:
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

테스트 부탁드려요.

**Comment by techromancer789** [comment]
정상적으로 다운로드 완료됩니다
빠른 피드백 감사합니다

**Comment by KurtBestor** [comment]
v2.0에서 해결됨
