### ISSUE TITLE
산카쿠 다운로드할때 로고만 무수히 다운로드 되네요

### ISSUE THREAD

**Issue by dullahan00** [KurtBestor/Hitomi-Downloader-issues#120]
저번에 제 요청 받아주신 거 같아서 매우 기뻤는데 오류가 있는 거 같습니다. 
겔부루마냥 원하는 태그에서 주소로 다운받는데 갯수는 얼추 맞는 거 같은데 다운은 산카쿠 기본 로고만 다운로드 됩니당.

**Comment by KurtBestor** [comment]
아, 네. 만들다 만건데 실수로 활성화해서 보냈네요.
아직 산카쿠는 지원하지 않습니다.
