### ISSUE TITLE
건의드립니다.

### ISSUE THREAD

**Issue by godhen** [KurtBestor/Hitomi-Downloader-issues#1200]
마나모아에서 다운로드시
미리보기? 겉페이지? 썸네일 페이지는 저장이 안되는데
썸네일 이미지도 같은화수에 저장되도록 가능할까요?

**Comment by KurtBestor** [comment]
화 썸네일은 없는 것 같은데 있다면 알려주세요.

**Comment by godhen** [comment]
> 화 썸네일은없는 것 같습니다.

예를들어
https://manamoa13.net/bbs/board.php?bo_table=manga&wr_id=1911465
이화를 보시면 제목옆에 이미지가 하나있는데
이런식으로 미리보기?썸네일?식으로 올린 이미지는 본문에 안올려놔서
놓치는경우가있어서요 이것도 같이 저장됬으면해서요
