### ISSUE TITLE
웹사이트 추가 건의

### ISSUE THREAD

**Issue by godhen** [KurtBestor/Hitomi-Downloader-issues#1201]
네이버 웹툰은 지원하는데
다음웹툰은 지원안하시는것 같아서요
몇번 건의 올라온거봤는데
답변이 없거나 참고올려주시는데 눌러보면
해결이 안된것같아서요
다음웹툰도 추가해주실수있나요?

그리고 호두코믹스도 지원하다 사이트 주소가바뀌면서
안되는상태인데 스크립트올려주신걸 나름대로 최대한 바꿔봤는데
안되더군요 수정해주시면 간단하겠지만 이런일있을때마다
손빌리는것보다 배워서 좀 써보고싶은데 어떻게 배울방법없나요?

개인적인 생각인데
사이트 스크립트 작성 방법글을 올려주시면
도움이 많이 될것같아요 사이트 건의글도 줄어들것같고

**Comment by KurtBestor** [comment]
다음웹툰이나 호두코믹스는 나중에 볼게요.

스크립트는 다른 프로그래머 분들이 기여 해주셨으면 하는 마음에서 넣은 기능이에요. 파이썬을 전혀 모르는 분들은 작성하기 힘들 거예요.
프로그래머 분들은 예제 스크립트들을 보면 이해하실 것 같아서 딱히 작성 방법은 쓰지 않았어요.
실제로 만들어주신 분도 있고요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/892

**Comment by godhen** [comment]
답변감사합니다

**Comment by KurtBestor** [comment]
https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/912#issuecomment-537749598
