### ISSUE TITLE
사이트 (tumbex.com) 추가 해주실 수 있으신가요?

### ISSUE THREAD

**Issue by mrdonghyun12** [KurtBestor/Hitomi-Downloader-issues#1203]
약 9개월전에 텀블러에서 성인물 제재할 때 당시에 있던 있던 모든 텀블러 성인 OR 일반게시물을 옮겨놓은 사이트입니다.

단 지금 자료도 있지만 당시 성인물을 모아놓은게 의의가 큰 사이트입니다.

  추가해주시면 정말 감사할거같습니다!

https://www.tumbex.com/  -> 사이트 메인페이지

자료가 있는 페이지 ↓-↓-↓-↓-↓-↓-↓  

( 두번째 링크처럼 현재게시물을 미러링하기도하지만 성인물 제재 전 게시물 모아놓은게 큽니다)

ex)
https://www.tumbex.com/photoman1004.tumblr/posts?page=1&tag=%EB%8F%8C%ED%95%80%ED%8C%AC%EC%B8%A0

https://www.tumbex.com/blackpinkofficial.tumblr/photo?page=1

----------------------------------------------------------

+ 텀벡스 메인페이지에서 원하는 자료 or 프로필을 찾기힘들다면 키워드 하나를 선택해 게시물을 찾아볼 수있는 사이트  (Tumbex와는 별개의 사이트입니다 이 사이트는 추가할가치x ) 

https://www.flaru.com/ko/tumbex.com/

**Comment by KurtBestor** [comment]
Tumbex 에서 자체 서버에 백업한 게 아니라 실시간으로 Tumblr API로 가져오는 건데 이미 다운로더에서도 똑같은 방식으로 가져오니까 Tumblr 에서 잘렸지만 Tumbex 에서 보이는 게시물도 다운로더로 다운로드 돼요.
