### ISSUE TITLE
유튜브 2k,4k 영상 다운시 파일에 썸네일 표시

### ISSUE THREAD

**Issue by ewqkje2s** [KurtBestor/Hitomi-Downloader-issues#1204]
안녕하세요 항상감사하게 사용하고있습니다

다름이 아니라 유튜브에서 동영상을 다운받는데 2k,4k 영상은

다운받고나면 파일에 썸네일표시가 안뜨는데 

오류인가요 아니면 원래안뜨게 설정하신건가요?

**Comment by KurtBestor** [comment]
해당 작업 <kbd>마우스 우 클릭</kbd> - <kbd>정보... (I)</kbd> 눌러서 나온 내용 보여주세요.

**Comment by ewqkje2s** [comment]
181104 레드벨벳 (Red Velvet) 빨간 맛 (Red Flavor) [조이] JOY 직캠 Fancam (2018 제주 한류 페스티벌) by Mera

version: 2.7
platform: Windows-10-10.0.18362
gal_num: https://www.youtube.com/watch?v=-tpYN3-oVo8
dir: hitomi_downloaded_youtube
zip: 
type: youtube
artist: Mera
url: https://www.youtube.com/watch?v=-tpYN3-oVo8
valid: True
done: True
range: None
range_p: None
single: True
time: 1568547262.9 (Sep 15)
tags: []
goodbyedpi: True
lock: False
color: done
paused: False


[Gallery]
None


[File Names]
[0001] hitomi_downloaded_youtube\181104 레드벨벳 (Red Velvet) 빨간 맛 (Red Flavor) [조이] JOY 직캠 Fancam (2018 제주 한류 페스티벌) by Mera.mp4


[URLs]
[0001] https://r7---sn-3u-bh2l7.googlevideo.com/videoplayback?expire=1568568863&ei=vyF-Xb76H4O5gAOyop3ICw&ip=222.118.155.210&id=o-ALT6ov4ZfdpFwJ5LkceyL6qdrouNUimNY3mZmCJBt82o&itag=315&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C271%2C278%2C298%2C299%2C302%2C303%2C308%2C313%2C315&source=youtube&requiressl=yes&mm=31%2C26&mn=sn-3u-bh2l7%2Csn-i3b7knsl&ms=au%2Conr&mv=m&mvi=6&pl=16&initcwndbps=1075000&mime=video%2Fwebm&gir=yes&clen=163435401&dur=197.830&lmt=1550484728418347&mt=1568547172&fvip=3&keepalive=yes&c=WEB&txp=5532432&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHylml4wRQIhAOlt4L_NmXENKlAsAiUwvmBkObujMDg9tQJtX2tVrYKaAiBQpRd0lDJRjk1iAk1pDl71kqeNsiTFlK5NAg8EcLFWow%3D%3D&sig=ALgxI2wwRAIgYWx7fMd0hPw0LR4JYpsTf9PKa2JZaOS0-7CIGEGR5U4CIGnv00Wc287l-_prn1uTBRxeUhWxrrJJtUJeyL6I1i2j&ratebypass=yes


[Messages]
[144p][0fps][None] webm None ─ 278 - 82x144 (144p)
[144p][0fps][None] mp4 None ─ 160 - 82x144 (144p)
[240p][0fps][None] webm None ─ 242 - 136x240 (144p)
[240p][0fps][None] mp4 None ─ 133 - 136x240 (144p)
[360p][0fps][None] webm None ─ 243 - 202x360 (240p)
[360p][0fps][None] mp4 None ─ 134 - 202x360 (240p)
[480p][0fps][None] webm None ─ 244 - 270x480 (240p)
[480p][0fps][None] mp4 None ─ 135 - 270x480 (240p)
[720p][0fps][None] webm None ─ 247 - 406x720 (360p)
[720p][0fps][None] mp4 None ─ 136 - 406x720 (360p)
[720p][60fps][None] webm None ─ 302 - 406x720 (360p60)
[1080p][0fps][None] webm None ─ 248 - 608x1080 (480p)
[720p][60fps][None] mp4 None ─ 298 - 406x720 (360p60)
[1080p][0fps][None] mp4 None ─ 137 - 608x1080 (480p)
[1080p][60fps][None] webm None ─ 303 - 608x1080 (480p60)
[1080p][60fps][None] mp4 None ─ 299 - 608x1080 (480p60)
[1440p][0fps][None] webm None ─ 271 - 810x1440 (720p)
[1440p][60fps][None] webm None ─ 308 - 810x1440 (720p60)
[1920p][0fps][None] webm None ─ 313 - 1080x1920 (1080p)
[1920p][60fps][None] webm None ─ 315 - 1080x1920 (1080p60)
[360p][0fps][96kbps] mp4 mp4a.40.2 ─ 18 - 202x360 (small)


# stream_final <youtube_dl_test.Video object at 0x1ED12030> 313 - 1080x1920 (1080p) 1920p webm None 0fps
# stream_final <youtube_dl_test.Video object at 0x1ED12790> 315 - 1080x1920 (1080p60) 1920p webm None 60fps
[360p][0fps][96kbps] mp4 mp4a.40.2 ─ 18 - 202x360 (small)

[360p][0fps][96kbps] mp4 mp4a.40.2 ─ 18 - 202x360 (small)

# stream_audio 96kbps mp4 mp4a.40.2
https://r7---sn-3u-bh2l7.googlevideo.com/videoplayback?expire=1568568863&ei=vyF-Xb76H4O5gAOyop3ICw&ip=222.118.155.210&id=o-ALT6ov4ZfdpFwJ5LkceyL6qdrouNUimNY3mZmCJBt82o&itag=18&source=youtube&requiressl=yes&mm=31%2C26&mn=sn-3u-bh2l7%2Csn-i3b7knsl&ms=au%2Conr&mv=m&mvi=6&pl=16&initcwndbps=1075000&mime=video%2Fmp4&gir=yes&clen=13645197&ratebypass=yes&dur=197.903&lmt=1550483417661865&mt=1568547172&fvip=3&c=WEB&txp=5531432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cmime%2Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt&lsparams=mm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHylml4wRQIhAOlt4L_NmXENKlAsAiUwvmBkObujMDg9tQJtX2tVrYKaAiBQpRd0lDJRjk1iAk1pDl71kqeNsiTFlK5NAg8EcLFWow%3D%3D&sig=ALgxI2wwRAIgK8GIHYbyPSJNh9ln0ttQJNBCXQCJjfbiCOmX0kScMBwCIHA44fS_l6NDT4DcnP9FUvOj_f8nCj2n67Nf2gQf2Bey
Resolution: 1920p
Codec: vp9 / None
Abr: None
Subtype: webm
FPS: 60

Download audio: https://r7---sn-3u-bh2l7.googlevideo.com/videoplayback?expire=1568568863&ei=vyF-Xb76H4O5gAOyop3ICw&ip=222.118.155.210&id=o-ALT6ov4ZfdpFwJ5LkceyL6qdrouNUimNY3mZmCJBt82o&itag=18&source=youtube&requiressl=yes&mm=31%2C26&mn=sn-3u-bh2l7%2Csn-i3b7knsl&ms=au%2Conr&mv=m&mvi=6&pl=16&initcwndbps=1075000&mime=video%2Fmp4&gir=yes&clen=13645197&ratebypass=yes&dur=197.903&lmt=1550483417661865&mt=1568547172&fvip=3&c=WEB&txp=5531432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cmime%2Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt&lsparams=mm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHylml4wRQIhAOlt4L_NmXENKlAsAiUwvmBkObujMDg9tQJtX2tVrYKaAiBQpRd0lDJRjk1iAk1pDl71kqeNsiTFlK5NAg8EcLFWow%3D%3D&sig=ALgxI2wwRAIgK8GIHYbyPSJNh9ln0ttQJNBCXQCJjfbiCOmX0kScMBwCIHA44fS_l6NDT4DcnP9FUvOj_f8nCj2n67Nf2gQf2Bey
Convert: C:\Users\cig\Desktop\hitomi_downloaded_youtube\181104 레드벨벳 (Red Velvet) 빨간 맛 (Red Flavor) [조이] JOY 직캠 Fancam (2018 제주 한류 페스티벌) by Mera.webm
rename (1): hitomi_downloaded_youtube\8C4A3F29_a.tmp -> C:\Users\cig\Desktop\hitomi_downloaded_youtube\tmpA36B492C_a.weba
rename (1): C:\Users\cig\Desktop\hitomi_downloaded_youtube\181104 레드벨벳 (Red Velvet) 빨간 맛 (Red Flavor) [조이] JOY 직캠 Fancam (2018 제주 한류 페스티벌) by Mera.webm -> C:\Users\cig\Desktop\hitomi_downloaded_youtube\tmpA36B492C_v.webm
-i tmpA36B492C_v.webm -i tmpA36B492C_a.weba -c copy -strict experimental -preset ultrafast -shortest tmpA36B492C_o.mp4
[code]
0
[out]
ffmpeg version 4.1 Copyright (c) 2000-2018 the FFmpeg developers
built with gcc 8.2.1 (GCC) 20181017
configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth
libavutil 56. 22.100 / 56. 22.100
libavcodec 58. 35.100 / 58. 35.100
libavformat 58. 20.100 / 58. 20.100
libavdevice 58. 5.100 / 58. 5.100
libavfilter 7. 40.101 / 7. 40.101
libswscale 5. 3.100 / 5. 3.100
libswresample 3. 3.100 / 3. 3.100
libpostproc 55. 3.100 / 55. 3.100
Input #0, matroska,webm, from 'tmpA36B492C_v.webm':
Metadata:
encoder : google/video-file
Duration: 00:03:17.83, start: 0.000000, bitrate: 6609 kb/s
Stream #0:0(eng): Video: vp9 (Profile 0), yuv420p(tv, bt709), 1080x1920, SAR 1:1 DAR 9:16, 59.94 fps, 59.94 tbr, 1k tbn, 1k tbc (default)
Input #1, mov,mp4,m4a,3gp,3g2,mj2, from 'tmpA36B492C_a.weba':
Metadata:
major_brand : mp42
minor_version : 0
compatible_brands: isommp42
creation_time : 2019-02-18T09:50:14.000000Z
Duration: 00:03:17.90, start: 0.000000, bitrate: 551 kb/s
Stream #1:0(und): Video: h264 (Constrained Baseline) (avc1 / 0x31637661), yuv420p(tv, bt709), 202x360 [SAR 1:1 DAR 101:180], 453 kb/s, 29.97 fps, 29.97 tbr, 11988 tbn, 59.94 tbc (default)
Metadata:
creation_time : 2019-02-18T09:50:14.000000Z
handler_name : ISO Media file produced by Google Inc. Created on: 02/18/2019.
Stream #1:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 96 kb/s (default)
Metadata:
creation_time : 2019-02-18T09:50:14.000000Z
handler_name : ISO Media file produced by Google Inc. Created on: 02/18/2019.
Output #0, mp4, to 'tmpA36B492C_o.mp4':
Metadata:
encoder : Lavf58.20.100
Stream #0:0(eng): Video: vp9 (Profile 0) (vp09 / 0x39307076), yuv420p(tv, bt709), 1080x1920 [SAR 1:1 DAR 9:16], q=2-31, 59.94 fps, 59.94 tbr, 16k tbn, 1k tbc (default)
Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 96 kb/s (default)
Metadata:
creation_time : 2019-02-18T09:50:14.000000Z
handler_name : ISO Media file produced by Google Inc. Created on: 02/18/2019.
Stream mapping:
Stream #0:0 -> #0:0 (copy)
Stream #1:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
frame= 9711 fps=0.0 q=-1.0 size= 132608kB time=00:02:41.99 bitrate=6705.9kbits/s speed= 257x 
frame=10519 fps=8930 q=-1.0 size= 143616kB time=00:02:55.47 bitrate=6704.7kbits/s speed= 149x 
frame=11385 fps=6762 q=-1.0 size= 155648kB time=00:03:09.92 bitrate=6713.6kbits/s speed= 113x 
frame=11858 fps=6151 q=-1.0 Lsize= 162126kB time=00:03:17.83 bitrate=6713.4kbits/s speed= 103x 
video:159522kB audio:2319kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.175828%

Convert success: True
rename (1): C:\Users\cig\Desktop\hitomi_downloaded_youtube\tmpA36B492C_o.mp4 -> C:\Users\cig\Desktop\hitomi_downloaded_youtube\181104 레드벨벳 (Red Velvet) 빨간 맛 (Red Flavor) [조이] JOY 직캠 Fancam (2018 제주 한류 페스티벌) by Mera.webm
rename ext .webm --> .mp4
EOT: https://www.youtube.com/watch?v=-tpYN3-oVo8

**Comment by KurtBestor** [comment]
![image](https://user-images.githubusercontent.com/14768120/64921162-a580fa80-d7fa-11e9-9d3f-810d71e8456e.png)
저는 보이네요. 어떤 동영상 플레이어 쓰시나요?

**Comment by ewqkje2s** [comment]
팟플레이어 사용합니다 
해상도를 1080p로 설정하면 잘나오는데 
2k,4k로 해놓으면 안뜨네요;
