### ISSUE TITLE
질문드립니다.

### ISSUE THREAD

**Issue by godhen** [KurtBestor/Hitomi-Downloader-issues#1205]
스크립트 수정해서 나름 해결해볼려고
(mana모아 만화들어가서 만화제목 왼쪽 이미지도 다운로드와
사이트추가)
올려주신 스크립트를 이리저리 비교도해보고
오늘 하루종일 알아봤으나 말씀하신대로
파이썬을 모르면 전혀 못하겠더군요.
히토미 다운로더도 전부 파이썬으로 만드신건가요?
파이썬을 배워볼려고하는데
조언을 받을수있을까 해서요.
스크립트를  보고 이해, 작성할정도가 될려면
많은 배움의 시간이 필요한가요?
어떻게해서 배우셨는지도 궁금합니다.

**Comment by KurtBestor** [comment]
제가 짠 부분은 98% 정도 파이썬이에요.
파이썬 기본 문법이랑 HTML, HTTP, Requests, Beautiful Soup 정도만 배우면 될 거예요.
1달 정도면 할 수 있지 않을까요?
컴퓨터 비전 쪽으로 배우려고 파이썬 시작했어요.
