### ISSUE TITLE
hitomi_data 폴더의 galleriesX_pack.json 이 어떻게 저장되있는지 알고 싶습니다.

### ISSUE THREAD

**Issue by affinityDrops** [KurtBestor/Hitomi-Downloader-issues#1208]
개인적으로 조악한 분류기를 만들어서 쓰고 있는데 거기에 갤러리 정보를 피드할 목적입니다.

이전까진 `galleriesX_pack.json` 끼리 disjoint 했었고 그걸 이용해서 빠르게 검색했었는데 좀 오래 손을 놓고 있다가 지금 작동시켜보니 더이상 그렇지 않더라구요.

어떻게 저장돼있는지 알 수 있을까요?

또 갤러리정보를 어떻게 수집하는지도 혹시 알 수 있을까요?

**Comment by affinityDrops** [comment]
<img width="338" alt="notgood" src="https://user-images.githubusercontent.com/39024071/64971726-11d72900-d8e3-11e9-9caa-2d94867a2bfa.PNG">

전체적인 경향은 감소같은데 왜 중간에 이상한 값들이 튀는지요 ㅠㅠ...

**Comment by KurtBestor** [comment]
지금도 각 파일들끼리 disjoint 해요.
인코딩이 [JSON](https://www.json.org) 에서 [MessagePack](https://msgpack.org) 으로 바뀐 것 이외에는 예전과 같아요.
ID 순으로 정렬 되어있지 않은 건 히토미에 올라온 순서대로 정렬해서 그래요.

**Comment by affinityDrops** [comment]
아 그러면 예전부터 저렇게 돼있었고 옛날에 정렬된 것처럼 가정했어도 우연히 동작한 것이었군요...

혹시 프로그램에서 검색할 때는 전탐색하는건가요?

**Comment by KurtBestor** [comment]
전탐색이 뭔가요? 프로그램에선 선형 검색해요.

**Comment by affinityDrops** [comment]
선형검색을 의미한 것이었습니다.

궁금증이 해결됐습니다. 감사합니다.
