### ISSUE TITLE
2.7버전에서 실행 후 한참 뒤에 창이 뜹니다.

### ISSUE THREAD

**Issue by pyropecat** [KurtBestor/Hitomi-Downloader-issues#1209]
제 컴퓨터만 그러는 건지 모르겠는데... 2.5버전에선 실행하면 바로 다운로더 창이 떴었는데 2.7버전 이후부터는 클릭한 뒤에 5분? 정도 있다가 다운로더창이 뜹니다. 

혹시나 해서 백신(ESET, 앱체크)를 다 끈 상태에서 실행을 해봤는데도 한참 뒤에 창이 뜹니다.

실행 이후로 바로 창이 안뜨고 작업 관리자 프로세스에서는 백그라운드로 돌아가고 있던데 원래 이렇게 실행이 되는게 맞는건지 궁금 합니다.

윈도우7 64비트 입니다.

![캡처](https://user-images.githubusercontent.com/55406897/64980482-e1988600-d8f4-11e9-8f1a-85756190b30b.PNG)

**Comment by KurtBestor** [comment]
[v2.6d](https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/v2.6d) 는 어떤가요?

**Comment by pyropecat** [comment]
> [v2.6d](https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/v2.6d) 는 어떤가요?

오 바로 실행 되네요. 감사합니다. 혹시 이후 버전에서 고쳐지는 문제인가요?

**Comment by KurtBestor** [comment]
일반적인 건 아닌 것 같아요. 그런데 재현을 할 수 없어서 고치기 어려울 것 같아요.

이건 어떤가요?: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by pyropecat** [comment]
> 일반적인 건 아닌 것 같아요. 그런데 재현을 할 수 없어서 고치기 어려울 것 같아요.
> 
> 이건 어떤가요?: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

이것도 바로 실행 됩니다. 고생 많으십니다. 어려운가 보군요 ㅜㅜ

**Comment by KurtBestor** [comment]
지금 개발중인 테스트 버전은 바로 실행되는 걸로 봐서 왠진 모르겠지만 고쳐진 것 같네요.. 담 버전엔 아마 고쳐진 채로 나올거예요.
