### ISSUE TITLE
웹사이트 추가 건의!

### ISSUE THREAD

**Issue by Raycity** [KurtBestor/Hitomi-Downloader-issues#1210]
https://wfwf41.com

 늑대닷컴이라는 곳인데, 호두코믹스를 이은 또 하나의 대세가 될 거 같습니다.

 이 사이트 추가를 부탁드립니다.

**Comment by rybshgsd** [comment]
근데 이사이트는 계속 경찰수사 할때마다 계속 주소 바꾸면서 피해다녀서
주소 한번 또바뀌면 다운로드 다 막히고 일일히 주소 업뎃해야되는데
현실적으로 힘들듯..
