### ISSUE TITLE
질문드립니다.

### ISSUE THREAD

**Issue by hsh209** [KurtBestor/Hitomi-Downloader-issues#1215]
오늘 마나모아나 제이마나 등을 다운로드받으려고 하는데

"크롬이 자동화된 테스트 소프트웨어에 의해 제어되고 있습니다"

하면서 창이 떴다가 사라지는데 무슨 문제가 있는 건가요?

**Comment by lducjswo** [comment]
저도 같은증상입니다
어제(9/18) 23시가량까지만 해도 정상적으로 사용이 가능했는데 방금 해보니 전혀 계속 윗분과 같은 창만 새창으로 뜨고 다운이 안되네요

**Comment by lducjswo** [comment]
해결됐습니다
혹시나해서 manamoa13.net로 바꾸고 해보니 잘 되네요
hsh님도 한번 해보세요

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/853
