### ISSUE TITLE
Tumbex 추가문의 드립니다

### ISSUE THREAD

**Issue by mrdonghyun12** [KurtBestor/Hitomi-Downloader-issues#1217]
참고 - https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/1203

텀블러 성인물 제재전에 안짤린걸 Tumbex에서 가져오고 싶은데

Tumbex자체를 따로 파주실 수는 없는건가요? ㅠㅠ 

수고하십니다.

**Comment by KurtBestor** [comment]
Tumblr 주소 입력하면 되는데 문제 있나요?

**Comment by mrdonghyun12** [comment]
다시해보니 텀블에선 블라처리돼도 링크로 받으면 받을 수 있군요.. 

착각했네요 ㅠㅠ 수고하세요
