### ISSUE TITLE
다운로드가 안됩니다.

### ISSUE THREAD

**Issue by alsrms8899** [KurtBestor/Hitomi-Downloader-issues#122]
구글 드라이브에 있는 파일을 다운할려고하니 크롬 / 익스에서 바이러스로 판단하여 계속 삭제합니다.
해결 부탁드립니다 ㅠㅠ

**Comment by KurtBestor** [comment]
https://www.virustotal.com/#/file/011c30383c601234a1c79ca675f43469eac890eef1dd258cb9d52c9733f8ec2d/detection

바이러스토탈 모두 통과인데 왜 그런지 알 수 없네요. 제 환경에선 재현해볼수가 없어서 답변을 못 드리겠어요.

https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/v2.3a
이 링크로 다운로드 해보시거나 파이어폭스 / 오페라 등 다른 브라우저로 다운해보세요.
혹시 해결하시면 알려주세요!

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/128
