### ISSUE TITLE
파일명 형식을 숫자로 해두면 뒤에 파일 형식이 안붙을 때가 있습니다.

### ISSUE THREAD

**Issue by A2Ring** [KurtBestor/Hitomi-Downloader-issues#1220]
대체로 제목이 긴 작품명일 경우와 [,(,),]들이 자주 사용되는 제목들이 그러고 있습니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by A2Ring** [comment]
잘 되네요!
