### ISSUE TITLE
[마나모아] 에피소드 폴더 뒤에 날짜를 추가하여 구분을 하였으면 합니다.

### ISSUE THREAD

**Issue by mita5549** [KurtBestor/Hitomi-Downloader-issues#1223]
안녕하세요. 개선 사항 건의를 드리려고 합니다.
 업로드 측이 제목을 잘못 기입하는 경우, 다운로드가 원하는 대로 작동하지 않는 경우가 있습니다.

 문제를 겪고 있는 현상은 "중복 된 제목이 있는 경우"에 발생하는데,
 예를 들어서 "6화"로 제목이 두개 올라와 있는 경우 마지막에 업로드 된 게시글의 내용이 "6-2화" 이거나, 다음 에피소드인 "7화"임에도 동일하게 6화로 기재되어 있는 경우입니다.
 해당 만화들을 다운로드 하려고 하면, 한 폴더 내에 두 만화를 모두 저장하는 일이 발생하곤 합니다.

 따라서 "만화 제목"의 폴더가 아니라, "에피소드"폴더의  "n화" 뒤에 날짜를 기입하는 옵션을 추가하여 해당 현상을 개선하였으면 어떨까 합니다. 
ex )  경로 **Hitomi Downloader>hitomi_downloaded_manamoa>원피스**
**원피스 56화 (20190919)** <<< 동일 이름이더라도 앞서 다운로드 된 파일이 먼저 정렬 됨
**원피스 56화 (20190924)** 

참고로 해당 현상에 대한 예시 작품은 "나는 100만 명의 목숨 위에 서 있다" 이며,
20, 24, 27 에피소드가 각각 하나씩, 중복 된 이름으로 나열되어 있습니다.
https://manamoa14.net/bbs/page.php?hid=manga_detail&manga_id=10658

**Comment by KurtBestor** [comment]
현재는 제목이 같다면 먼저 나온 하나만 저장해요. 만약 두 화를 모두 저장하는 경우가 있다면 해당 작업 정보 보여주세요.
