### ISSUE TITLE
[2.7 그리고 test 버전] 종료시 잦은 오류 메시지

### ISSUE THREAD

**Issue by godknowswho** [KurtBestor/Hitomi-Downloader-issues#1224]
[hitomi_downloader_GUI.exe.log](https://github.com/KurtBestor/Hitomi-Downloader-issues/files/3649017/hitomi_downloader_GUI.exe.log)

로그를 확인해보라는 error메시지가 뜨는데 이게 조금 켜놓고 있다보면 뜨는것 같습니다. 정확한 원인은 모르겠네요.

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/1181
