### ISSUE TITLE
Folder name formatting not working for nhentai

### ISSUE THREAD

**Issue by seafang** [KurtBestor/Hitomi-Downloader-issues#1225]
Download folder formatting is not working for nhentai, even after saving the preference or restarting the Downloader. The folder would be named in the form of "[artist] title (id)" regardless of the setting.

But downloads from Hitomi.la & ehentai are still ok, and the folder names reflect the format setting. Hence the issue is just with nhentai.

Latest version (v2.7) is in use, OS Windows 10 64bit.

Thank you in advanced!

**Comment by KurtBestor** [comment]
Try the test version: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by seafang** [comment]
The test version is working fine! Thank you!
