### ISSUE TITLE
세이브한거 로드하니까 터집니다 히토미가

### ISSUE THREAD

**Issue by qwesry** [KurtBestor/Hitomi-Downloader-issues#1227]
세이브갯수가 천개조금 넘어가는데 ㄱ- 세이브하고나서 로드하니까 95%지점에서
자꾸터져서 

다운목록이랑 태그 합성한거좀 살리고싶은데 방법이 없을까요?

**Comment by KurtBestor** [comment]
이건 어떤가요?: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview
