### ISSUE TITLE
마루마루 다운로드가 안 됩니다.

### ISSUE THREAD

**Issue by ktsse** [KurtBestor/Hitomi-Downloader-issues#123]
![2018-06-13 12 05 06](https://user-images.githubusercontent.com/40209085/41299410-56aadfdc-6e9e-11e8-9096-f99ee21d28c6.png)
![2018-06-13 12 06 14](https://user-images.githubusercontent.com/40209085/41299411-57073cd2-6e9e-11e8-9513-02831d086199.png)
이렇게 나오면서 다운로드한 만화들이 하나도 안 들어옵니다.

**Comment by KurtBestor** [comment]
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

고쳤습니다. 테스트 부탁드려요.

**Comment by marumar** [comment]
와 미쳤다 ㄷㄷ 다운 안되길래 구버전받을려고 들어왔더니 해결판 ㅋㅋㅋㅋㅋ 감사여 아재

**Comment by ktsse** [comment]
감사합니다. 해결되었습니다

**Comment by ktsse** [comment]
감사합니다.해결되었습니다.
