### ISSUE TITLE
pixiv 관련 문의드립니다.

### ISSUE THREAD

**Issue by HuRoe** [KurtBestor/Hitomi-Downloader-issues#1230]
pixiv 태그 검색 url 로 다운로드 시 인기순 url 로 페이지 지정 다운로드가 안되는거 같습니다.

페이지 지정 다운로드 시 인기순이 아닌 최신순 기준으로 페이지를 지정하여 다운이 됩니다.

인기순 페이지 지정으로 다운로드 가능할까요?

언제나 다운로더 잘 사용하고 있습니다. 감사합니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by HuRoe** [comment]
잘 작동 됩니다 감사합니다
