### ISSUE TITLE
pixiv 다운로드 불가능한 상태입니다.

### ISSUE THREAD

**Issue by abstergo0124** [KurtBestor/Hitomi-Downloader-issues#1231]
2.7, 2.6d, 테스트 버전 모두 사용했으나 
can not determine type:https:// ~~
이렇게 나옵니다. ㅠㅠ

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by abstergo0124** [comment]
감사합니다 해결했습니다.
