### ISSUE TITLE
픽시브 주소 바뀜

### ISSUE THREAD

**Issue by gksduf11** [KurtBestor/Hitomi-Downloader-issues#1233]
픽시브 다운받을때 단일작품 다운로드를 하려면 주소가
https://www.pixiv.net/artworks/숫자
이렇게 바뀌어서 인식을 못 합니다.

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/1231
