### ISSUE TITLE
Issues downloading folders ending with "..." in https://mangarock.com

### ISSUE THREAD

**Issue by xZabuzax** [KurtBestor/Hitomi-Downloader-issues#1236]
I'm trying to download the manga "Kimetsu no Yaiba" from https://mangarock.com but the download always stops on 3 chapters that are ending in "...", they are:

"Vol.2 Chapter 13: You are.."
"Vol.7 Chapter 53: You are..."
"Vol.15 Chapter 133: Welcome..."

Not only does the download stops but I'm not able to delete those folders afterwards because the system says that it can't find those folders so I'm forced to do some trickery to delete those folders using 7-Zip. If anyone has issues deleting those folders try this:

Right-click on the folder with the issue, select "Add to Archive" and then click the option that says "Delete files after compression". Once the file is compressed the folder with the issue will be deleted.

**Comment by KurtBestor** [comment]
Try the test version: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by xZabuzax** [comment]
> Try the test version: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

That version fixed the issue, thank you!
