### ISSUE TITLE
기능 건의드립니다!

### ISSUE THREAD

**Issue by Pseudo-Ray** [KurtBestor/Hitomi-Downloader-issues#1237]
동인지를 냐토렌트같은 곳에서 다운받으면 원 제목으로 다운받아지는데, 익헨에서 받으면 영어 제목으로 받아지네요.

정리하려 하니까 뒤죽박죽이라 그냥 임시방편으로 익헨에 있는 일어 제목 복붙해서 쓰고 있습니다 ㅠㅜ

익헨 페이지 소스 보니까 영어제목 다음에 일본어 제목 바로 붙어 있는데 일어 제목으로 다운받을 수 있는 옵션 추가하면 좋을 것 같아요!!

P.S 폴더 안에 자동으로 작가 폴더로 들어가게(?) 하는 건 욕심이겠죠?

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/855
