### ISSUE TITLE
익헨 사이트 다운로드 문의

### ISSUE THREAD

**Issue by wail0422** [KurtBestor/Hitomi-Downloader-issues#1238]
언제부터 이렇게 되었는지 감은 오지 않습니다.
Download original 2080 x 3000 3.42 MB source
원래 사용했을 때 위 파일 원본이 다운로드되었습니다. 지금 그렇지 못하더군요.
005.jpg :: 1280 x 1846 :: 666.2 KB
이상하게 위 파일 화질로 받아집니다.

개발자 분께서 의도하고 그러신 건지, 아니면 어떠한 막힘? 같은 건지 제가 판단할 수가 없네요. 확인 부탁드립니다.

**Comment by KurtBestor** [comment]
해당 작업 <kbd>마우스 우 클릭</kbd> - <kbd>정보... (I)</kbd> 눌러서 나온 내용 보여주세요.
