### ISSUE TITLE
검색도중 자동으로 종료되는 문제

### ISSUE THREAD

**Issue by Madistaken** [KurtBestor/Hitomi-Downloader-issues#1239]
검색기로 550~600개 정도의 파일들을 찾으면 프로그램이 멈추고 응답없음이 뜨더니 그대로 종료됩니다. 기본, 삭제된 데이터는 잘 받아지고 URL 입력하는식으로 다운하는것도 잘 되는데 검색기만 이러네요. 아주 옛날버전때는 검색이 잘됫던걸로 기억합니다.

**Comment by KurtBestor** [comment]
`검색기` - `옵션` - `50개씩 끊어서 검색` 체크해서 검색하면 어떻게 되나요?

**Comment by Madistaken** [comment]
안튕기고 잘 작동하네요. 감사합니다!
