### ISSUE TITLE
마루마루 관련

### ISSUE THREAD

**Issue by roseark** [KurtBestor/Hitomi-Downloader-issues#124]
밑의 건의 글에서 답변 해주신 테스트판을 사용하면
일단 다운은 제대로 됩니다.
다만 폴더가 제대로 생성되지 않는 듯 하네요.
['만화 타이틀' 폴더/'~화' 폴더/이미지 파일]
이런 식이여야 하는데
[만화폴더/이미지파일]
로 중간에 몇화 인지 구분하는 폴더가 생성되지 않네요.

**Comment by KurtBestor** [comment]
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

테스트 부탁드려요.

**Comment by roseark** [comment]
제대로 다운도 되고 폴더도 만들어지네요.
감사합니다~

**Comment by marumar** [comment]
이거 모르고 이전?? 테스트 버전으로 4기가 어치 받았다가 피똥쌈
몇개는 파일명이 00xx.jpg라 살렸는데 열에 아홉은 버림 ㅅㅂ

**Comment by bbangsdf** [comment]
받으면 다운은 잘 됩니다. 하지만 바이러스가 검출된다고 나오네요

**Comment by KurtBestor** [comment]
https://www.virustotal.com/#/file/13c20ac5a244b2e4242f31672328655a6cb7a6eb945c9d2917f33d70ca656dad/detection

@bbangsdf 
바이러스토탈에선 모두 검출 안되는데 어떤 백신 쓰시나요?

**Comment by bbangsdf** [comment]
기본 윈도우 10 디펜스 쓰고 있습니다.

**Comment by KurtBestor** [comment]
@bbangsdf 
어떻게 검출되는지 진단명이나 스크린샷 찍어서 보여주실 수 있나요?

**Comment by bbangsdf** [comment]
<img width="503" alt="default" src="https://user-images.githubusercontent.com/40308848/41504237-ec8b897e-7223-11e8-850d-7072d7fe7ba2.PNG">

백신끄고 다운 받고나서 압출풀고 다시 백신을 키면 트로이잔으로 나옵니다

**Comment by bbangsdf** [comment]
<img width="382" alt="default" src="https://user-images.githubusercontent.com/40308848/41504263-81154efe-7224-11e8-8cc8-a63e06bd3f5d.PNG">
진단명입니다.

**Comment by KurtBestor** [comment]
@bbangsdf 
크롬에서 바이러스 검출되는 건 윈도디펜스 끄면 사라지나요?
[자세한 정보] 눌러서 다시 보여주실 수 있나요?

https://drive.google.com/open?id=1TImpcZ0IjmKH0neR2rmmwr93MF7_4Kn_
이건 어떤가요?

**Comment by bbangsdf** [comment]
Not Found
Error 404  라고 뜹니다
크롬 바이러스 검출은 윈도우 디펜스 끄면은 안나옵니다

**Comment by bbangsdf** [comment]
<img width="408" alt="down" src="https://user-images.githubusercontent.com/40308848/41504723-36f37922-7233-11e8-8cdb-741ff180b984.PNG">

**Comment by KurtBestor** [comment]
@bbangsdf
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/128
