### ISSUE TITLE
설정에서 폴더명 형식을 수정시 이전 형식도 필터 가능했으면 좋겠습니다.

### ISSUE THREAD

**Issue by usadapekora** [KurtBestor/Hitomi-Downloader-issues#1240]
현재 설정에서 폴더명 형식을 수정시 이전에 쓰던 폴더명 형식과 달라서 
검색기 이용시 다운로드 받았던 것이 체크가 안되고
다운로드 시도시 새로운 폴더명 형식으로 새로 다운로드 받게 됩니다.

따라서 체크기능에 이전 형식을 추가할 수 있으면 좋겠습니다. 
아니면 폴더명 형식에 추가되어있는 형식은 전부 체크후 필터해서 기존 다운로드와 연동하면 좋겠습니다. 
형식 목록중에서 어떤 형식을 체크할지 여부를 사용자가 선택하게 하는것도 좋을것 같습니다. 
혹은 특정 형식만(예 : 뒤의 아이디값만 체크)으로 필터를 할 수 있게 하는것도 좋을것 같습니다.

혹은 이전 폴더명 형식을 새 폴더명 형식으로 일괄 수정하는 기능이 있는것도 좋을것 같습니다.
(아이디값이 있다는 전제로 기존 폴더명에 적혀있지 않은 부분은 새로 검색해서 붙여놓는다거나 하는것도 좋을것 같습니다.
<예 : [아티스트] 타이틀 (아이디) 를 
[아티스트][그룹][시리즈] 타이틀 (아이디) 로 
일괄 수정시 뒤의 아이디값으로 재검색해서 채워넣기>)

=====================================================

또한 폴더명 형식 필터에 걸려서 중복 다운로드시 파일명만 체크후 파일명이 같으면 무조건 다운로드를 안 하게 되는데 이것에 대한 선택 여부가 있었으면 좋겠습니다. 
가령 정전으로 컴퓨터가 종료되어 파일이 잘 안 받아진 상태인데 다시 받는걸 시도하면 다 안받아진 파일도 파일명만 남아있으면 그걸 스킵하게 됩니다. 
결국 기존에 있는 걸 지워야 받아지게 되는데 이것을 개선할 수 있으면 좋겠습니다.

덮어쓰기, 일괄 덮어쓰기, 좀더 큰 파일로만 일괄 덮어쓰기 같은 기존 윈도우 파일의 중복 파일명 덮어쓰기 기능같은게 있으면 좋을것 같습니다.

**Comment by KurtBestor** [comment]
다음 문제에 대한 깔끔한 해결 방법이 없어서 구현을 못 하고 있어요:
1. ID가 폴더명 형식에 들어가있지 않은 경우
1. 이미 다운로드 된 폴더명과의 호환
1. 서버 설정을 E(x)Hentai 해서 받으면 제목이 다름
1. 히토미에서 작품 ID가 바뀐 경우
1. 히토미에서 애니메이션인 ID가 E(x)Hentai 에서 그렇지 않은 경우
1. 히요비에만 남아있는 경우
1. 작품이 완전히 사라진 경우

파일명만 체크하진 않아요. 2KB 이하인 파일은 다시 다운로드해요.
파일 크기를 얻으려면 해당 서버에 요청(request)을 보내서 얻어야하는데, 이게 필수로 제공되는 건 아니라서, 서버에서 파일 크기를 제공하지 않도록 바꿔버리면 소용이 없어요.
파일이 있어도 무조건 다시 다운로드하는 옵션을 나중에 넣어볼게요.

**Comment by usadapekora** [comment]
0. 처음에 말한 필터방식의 추가를 사용자가 임의로 할 수 있게 하는건 어떤가요. 
가령 <<[아티스트] 타이틀 (아이디)>> 를 
<<[아티스트][그룹][시리즈] 타이틀 (아이디)>> 로 
바꿨지만 다운로드 받았다는 체크 필터는 기존에 다운받은 형식도 포함시키기 위해 
<<[아티스트] 타이틀 (아이디)>> 와 
<<[아티스트][그룹][시리즈] 타이틀 (아이디)>> 
둘다 포함시키는걸 사용자가 선택하게 하는건 어떤가요.

1. ID의 경우에는 어쩔 수 없다고 봅니다. 
현재 필터할 수 있는 PK요소가 ID값밖에 없는것 같으니 이게 없으면 폴더명 일괄수정 기능이나 아이디값 단독 필터를 쓸 수 없다는걸 설정란에 설명을 붙이고 뒤에 (아이디값) 있는 사람만 기능을 쓸 수 있게 하는것도 좋을것 같습니다

2. 0번 형식을 쓰던가 폴더명에 아이디값이 있거나 INFO파일을 받은경우 일괄수정 기능을 쓸 수 있게 하면 좋을것 같습니다.

3. 이것은 지금도 이미 일어나는 문제라 같은 번호여도 익헨으로 다운이 되버릴시 새로 받아서 폴더가 따로 생겨버립니다. 
제목이 완전히 같으면 상관없지만 다르면 같은 폴더명 형식이어도 타이틀값이 다르므로 다른걸로 받아들이고 새로 받아버립니다. 
아이디값이 있다면 익헨에 대한 아이디 필터가 필요할것 같습니다. 
게다가 사실 제목이 같아도 파일명이 다르면(가령 히토미에선 1.JPG지만 익헨에선 001.JPG일시) 새로 받아버립니다.
일괄수정시 익헨쪽의 바뀐 제목을 받으면 그쪽 정보로 갱신하거나 폴더명 형식 수정시 증가하는 요소와 소멸하는 요소를 체크해서 증가하는 요소만 새로 받아오는것도 좋을것 같습니다.

4. 3과 똑같은 문제입니다. 
기존에 있던 문제로 번호만 다르다고 필터에는 안 받았다고 뜨고 새로 받아버립니다. 
하지만 이것은 어쩔 수 없는 문제로 이건 새로 받은 후 사용자가 중복체크를 해서 기존걸 지우던가 하는 수동 관리를 해야할것 같습니다. 
폴더명 형식 수정시에는 바뀐 아이디값으로 추적이 가능하면 그걸로 하면 되지만 그게 되지 안되서 
다운로더 입장에서 '7.작품이 완전히 사라진 경우'와 다를바 없는 결과를 리턴 받을시 밑의 7번과 동일한 대응을 하면 될것 같습니다.
현재 PK 요소가 아이디값 밖에 없는것 같으므로 이것은 아이디값 외에 다른 PK 요소가 있지 않는한 어쩔 수 없는것 같습니다.

5. 4와 동일한 대응이 될것 같습니다. 
기존에도 다운로드를 할시 아이디가 같아도 익헨과 달라서 다른 정보라면 어차피 새로 받게 되버리니 
일괄수정시에는 전혀 다른 정보로 원치않는 수정이 있을 수 있다는걸 알람창을 띄어 숙지시키면 될것 같습니다.
일괄수정의 부작용은 어떤 곳에서나 있던 일이고 그런것이 싫다면 일괄수정을 하지말고 하나하나 지정수정을 하던가는 사용자의 몫이라고 생각합니다.
만일 익헨에선 아예 없는것으로 뜨면 마찬가지로 밑의 7번과 동일한 대응을 하면 될것 같습니다.

6. 히요비에 적혀있는것을 끌어쓰면 되지 않을까 합니다. 거기도 태그하고 시리즈 다 적혀있는데 끌어오면 좋을것 같습니다. 불가능일시 마찬가지로 밑의 7번과 동일한 대응을 하면 될것 같습니다.

7. INFO파일마저 없다면 모르는 추가 요소에는 Unknown이나 N/A로 채우면 될것 같습니다.

=========================================

1은 정말 어쩔 수 없는 문제로 PK요소인 아이디가 없으면 해당 기능을 쓸 수 없다고 할수밖에 없을것 같습니다. 혹은 그 필터에 걸맞는 제일 최신의 요소를 집어넣으면 좋을것 같습니다.

3~6은 결국 아이디가 달라져서 정보가 없을때, 혹은 같은 아이디어도 정보가 다를때인 경우이니 그럼 폴더명 일괄수정 시도때마다 해당 최신 정보로 업데이트하고 만약 완전히 모를시에는 Unknown이나 N/A로 표시하면 될것 같습니다.

즉,

1의 경우에는
가령
[아티스트] 타이틀 을
[아티스트][그룹][시리즈] 타이틀 (아이디) 로
일괄 수정 시도시 아이디값이 없으므로 인포파일이 없는한 불가능하다고 하거나
해당 [아티스트] 타이틀로 검색시 (아이디:1111)하고 (아이디:2222)라는 2개가 검색되면 제일 최신인 (아이디:2222)의 정보를 받아서 그룹과 시리즈와 아이디를 채워넣으면 될것 같습니다.
이미 작품이 소멸되어 검색이 안될시에는 Unknown이나 N/A로 채우거나 하면 될것 같습니다.

그렇다면 1의 경우를 제외해서
가령
[아티스트] 타이틀 (아이디) 를
[아티스트][그룹][시리즈] 타이틀 (아이디) 로
일괄 수정시 뒤의 아이디값으로 재검색해서 채워넣기를 할 시

3의 경우에는 만약 히토미쪽이나 히요비쪽에서 안되고 익헨으로만 된다는 전제하에 익헨쪽으로 아예 제목을 바꿔서 거기서 [아티스트][그룹][시리즈] 타이틀을 새로 업데이트 하면 될것 같습니다. 
혹은 A방식 -> B방식으로 폴더명 일괄수정시 추가되는 요소와 소멸되는 요소를 체크해서 추가되는 요소만 가져오면 좋을것 같습니다.
위의 예시를 잇자면 익헨쪽의 [그룹][시리즈]만 가져와서 붙이고 타이틀처럼 수정되는 요소는 바꿀거냐고 물으면 좋을것 같습니다.

4의 경우에는 어쩔수 없으니 바뀐 아이디로 추적이 되면 정보를 가져오고 안되면 일괄수정시 그렇게 해서 채워지지 않는 모르는 부분은 Unknown을 붙이던가 N/A를 붙이던가 공백으로 []만 두던가 그 부분만 아무것도 안하고 냅두게 하던가 하면 될것 같습니다. 
그 경우 어떻게 할지 사용자가 선택하게 하는것도 좋을것 같고요. 
사실 삭제된 데이터에서 그런것들이 날아가서 그런 요소가 모두 N/A로 되는건 종종 있는 일이므로 아이디가 달라지거나 이제는 없는 작품이라면 지금은 그때의 데이터를 알 수 없으므로 인포가 없는한 새로운 추가 요소를 모를시 N/A로 채워넣으면 무난할것 같습니다.
(결과예시 : [아티스트][N/A][N/A] 타이틀 (아이디) )

5의 경우 정말 어쩔 수 없습니다. 
기존에도 이미 문제입니다. 
바로 위에 적은 3의 방식을 일단 따를 수 밖에 없을것 같습니다. 
아니면
일괄수정말고 원하는 폴더만(아이디값이 있는) 선택하는 지정수정 
혹은 특정 폴더 잠금기능 
혹은 일괄수정시 제외할 폴더나 형식 지정 
같은 기능을 추가해서 일괄수정을 하기전에 경고알람창을 띄어서 원치않는 변환이 있을 수 있다를 숙지 시키고 
사용자가 직접 지정수정을 하던가 원하지 않는 폴더는 잠금을 하던가 제외할 폴더로 추가하거나 아니면 따로 빼놓거나 폴더명을 일괄수정에 적용되지 않게 아예 바꾸라고 하는 수 밖에 없는것 같습니다.

6의 경우 히요비의 정보를 가져올 순 없는지요? 그쪽도 태그하고 시리즈 다 적혀있는데 끌어오면 좋을것 같습니다. 불가능시 4의 경우와 대응은 같을것 같습니다.

7의 경우도 4의 경우와 대응은 같을것 같습니다. 억지로 요소 수정을 하는만큼 만약에 추가해야될 요소가 현재 남아있지 않다면 모르는게 당연한거고 위의 예시대로 아이디로 검색해도 작품이 완전히 사라져서 [그룹][시리즈] 정보를 모르겠다면 그 경우 정보가 없으므로 Unknown이나 N/A로 채워넣으면 무난하지 않을까 합니다. 
(결과예시 : [아티스트][N/A][N/A] 타이틀 (아이디) )

=========================================

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview
