### ISSUE TITLE
기존에 있던 다운로더를 다시 리스트에 못올리나요?

### ISSUE THREAD

**Issue by neetmeow** [KurtBestor/Hitomi-Downloader-issues#1241]
히토미 다운로더를 자동업데이트하는도중 에러가 생겨서, 
exe파일이 사라져서 , 다시 사이트에서 받았는데 , 다른 히토미다운로더가 생겼네요..

그래서 기존에 있던 "hitomi_downloaded" 이나 "hitomi_data"파일 등 그대로 복사해서 붙혀넣었는데, 다운로더 리스트에는 자동으로 연동(?)이 되지않아서 리스트에 뜨지않네요.

파일을 다시 다운로더 리스트에 올리는 방법 없나요 ?

**Comment by KurtBestor** [comment]
기존 폴더에 있는 `<실행파일명>.ini` 파일에 작업 리스트와 설정들이 저장되어 있어요. 이걸 옮겨주시면 될거예요.

**Comment by neetmeow** [comment]
그것들도 같이 옮겼는데 리스트에 안뜨는건 에러인가요??

**Comment by KurtBestor** [comment]
프로그램 끄고 INI 파일 옮긴 다음에 실행해야해요.

**Comment by neetmeow** [comment]
아 확인했습니다. 메뉴 - 저장폴더에 있는 모든갤러리넘버복사 해서 다시 다운로드 받으면 그대로 보존된 상태로 중복되지않게 다운이 되는군요..

그럼 혹시 다운로더를 통하지 않은, 히토미에서 직접받은 제목만 있거나 대충 있는 폴더명도 "hitomi_downloaded" 폴더에 넣으면 갤러리넘버복사할때 그것도 인식을 하나요??

**Comment by KurtBestor** [comment]
`id` 가 있는 폴더명만 인식해요.

**Comment by neetmeow** [comment]
그  id라는것은 품번을 의미하나요?? 제가 "hitomi_downloaded" 안에 있는 파일이 아닌, 다른 폴더에 있는 파일을 제목뒤에 "~제목~(품번)" 이런식으로 해놓고, "hitomi_downloaded" 안에 넣어도 인식을 하나요?

**Comment by KurtBestor** [comment]
네, 인식해요.
