### ISSUE TITLE
기능 건의

### ISSUE THREAD

**Issue by rlacks1237** [KurtBestor/Hitomi-Downloader-issues#1242]
항상 잘 사용하고있습니다
히토미 대부분을 다운받는데 가끔 아래쪽에 다 다운받은곳에 안 다운받은 것들이 가끔 생기더라구요
혹시 이미 다운로드 된 것들 그러니깐
![제목 없음](https://user-images.githubusercontent.com/40794812/65937978-8b7f2300-e45c-11e9-9182-a3b52f3bc0b0.png)
이런 마크가 붙은걸 검색할때 제외시키고 안붙은것들만 남게 할수 없을려나요

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/400#issuecomment-453401831

**Comment by rlacks1237** [comment]
감사합니다
이미 있는기능이였네요!

**Comment by rlacks1237** [comment]
아 혹시 작가 제외 기능은 있을까요?
태그 제외 기능은 있는거같은데

**Comment by rlacks1237** [comment]
메뉴얼 읽다가 혹시나해서
-작가이름하니깐 되네요
수고하세요!
