### ISSUE TITLE
특정 작가 다운받을때 이름이 비정상적으로 저장됩니다.

### ISSUE THREAD

**Issue by altergoogle1** [KurtBestor/Hitomi-Downloader-issues#1243]
type.90 작가 작품을 다운받을 시, 정보 등에 정상적으로 type.90으로 작가명이 표기되나
저장시에는 manga.90이라는 이름으로 저장됩니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by altergoogle1** [comment]
확인했습니다. 정상적으로 저장됩니다. 감사합니다.
