### ISSUE TITLE
몇가지 기능 추가 건의드립니다.

### ISSUE THREAD

**Issue by Dumbisted** [KurtBestor/Hitomi-Downloader-issues#1244]
1. 태그 감지 기능
특정 태그를 설정해 놓으면 다운받으려는 작품의 태그에서 그 특정 태그를 감지하여 1~2개만 제목에 표시해주는 기능이 있었으면 좋겠습니다.

예시)"Tankoubon" 태그를 설정해 놓았고 폴더명 형식에 tag가 있을시 tag에 Tankoubon을 입력함.

2. 픽시브에 제외 태그 기능 추가
혹시나 해서 태그 뒤에 -를 붙여보았지만 작동하지 않더군요. 개인적으로 사용하면서 느꼈던 것이, 포함 태그 기능도 유용하지만 제외 태그 기능도 필요하다고 생각했습니다. 포함 태그를 유지하면서 제외 태그 기능도 추가하는 것이 괜찮을듯 싶습니다.

+추가
버그인듯한 문제로 히토미 다운로더를 켜놓고 일정 시간이 지나면 픽시브 페이지를 다운로드 받을때 Invaild가 되면서 받아지질 않습니다. 다운로더를 재시작하면 해결되긴 하더군요. 

항상 소중히 사용하고 있습니다. 수고에 감사드립니다!

**Comment by KurtBestor** [comment]
픽시브 다운로드 안 될 때 해당 작업 <kbd>마우스 우 클릭</kbd> - <kbd>정보... (I)</kbd> 눌러서 나온 내용 보여주세요.

**Comment by Dumbisted** [comment]
@KurtBestor 
-
Invalid: [pixiv] https://www.pixiv.net / member_illust.php?id=3916286

version: 2.7b
platform: Windows-10-10.0.18362
gal_num: https://www.pixiv.net/member_illust.php?id=3916286
dir: hitomi_downloaded_pixiv\T.김수진 (pixiv_3916286)
zip: 
type: pixiv
artist: None
url: https://www.pixiv.net/member_illust.php?id=3916286
valid: False
done: True
range: None
range_p: None
single: False
time: 1570188856.14 (Oct 4)
tags: []
goodbyedpi: True
lock: True
color: invalid
paused: False


[Gallery]
None


[File Names]



[URLs]



[Messages]
PIXIV_TYPE: user
Type: all
info: None
No Name
stop
Traceback (most recent call last):
File "utils", line 708, in start
File "utils", line 754, in start_
File "pixiv_downloader", line 193, in read
Exception: No Name

Invalid: fail=True
EOT: https://www.pixiv.net/member_illust.php?id=3916286

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by Dumbisted** [comment]
제외 태그 기능 정상작동 확인했습니다. 감사합니다! 

Invaild가 되는 버그는 다시 발생한다면 바로 알려드리겠습니다.
