### ISSUE TITLE
이헨/익헨 doggie bag 방식 다운로드 기능 추가 문의드립니다

### ISSUE THREAD

**Issue by nikin78** [KurtBestor/Hitomi-Downloader-issues#1247]
히토미 외에도 GP로 이헨, 익헨에서 아카이브 다운로드를 종종 하는데, 다운로드 되는 파일을 hitomi downloader GUI처럼 이름 형식을 자유롭게 지정할 수가 없더군요.

https://forums.e-hentai.org/index.php?showtopic=229481&st=0
https://github.com/Mayriad/Mayriads-EH-Download-Shortcuts

위 링크는 이헨 내에서 유저가 개발한 스크립트인데, 외부 스크립트임에도 불구하고 로그인된 계정에서 GP (또는 Credits)를 소모하여 원버튼 클릭으로 파일 다운로드가 가능한 스크립트입니다.

다만 위 스크립트도 파일 이름 형식을 변경해 다운로드되는 파일 이름을 원본 갤러리의 제목과 달리하는 것은 불가능합니다.
그렇다면, 혹시 hitomi downloader GUI 프로그램 내에서 익헨, 이헨 계정 정보를 입력해 로그인 한 후, 이미지 크롭핑이 아니라 사이트 내 재화인 GP나 Credit를 소모해 원본 아카이브를 다운로드 하는 doggie bag 방식의 다운로드 기능을 추가할 수 있을지요?

그리고 Hitomi searcher로 검색 시 나타나는 작품들의 다운 소스를 Hitomi 서버가 아니라 Ehentai 나 Exhentai 서버로 하되, 위 doggie bad 다운로드 방식으로 다운로드 되게 기능을 추가하실 수 있으신 지도 궁금합니다.

**Comment by KurtBestor** [comment]
아카이브 다운로드는 사이트에서 직접 하면 되지 않나요?
`Click Here To Start Downloading` 우클릭하고 `Save link as...` 눌러서 다른 이름으로 저장하세요.

**Comment by nikin78** [comment]
> 아카이브 다운로드는 사이트에서 직접 하면 되지 않나요?
> `Click Here To Start Downloading` 우클릭하고 `Save link as...` 눌러서 다른 이름으로 저장하세요.

다른 유저가 만든 숏컷으로 원버튼 다운로드가 되는 것 까진 좋았는데, 다수의 작품을 다운로드 하려는 경우 이름을 일일히 하나씩 지정하기가 힘들어서 건의드렸었습니다. 몇 십개까지는 번거롭긴 해도 상관이 없으나, 몇 백개 단위부터는 아무래도 그리 하기엔 시간이 너무 소요되더군요...

**Comment by gembleman** [comment]
파일을 다 받으신 후에 DarkNamer나 다른 프로그램을 이용해서 이름만 일관 변경하는 방법이 편하겠습니다.
