### ISSUE TITLE
검색기 기능 추가 건의드립니다.

### ISSUE THREAD

**Issue by Rounlet** [KurtBestor/Hitomi-Downloader-issues#1248]
보통 작가 이름을 검색하면 작가 이름이 포함된 모든 작품이 나타나게 되는데

유명한 작가일 경우, 다른 작가들 같이 연제하는 COMICS 같은 작품들도 모두 검색이 됩니다.

드리고 싶은 제안은 어떤 작가를 검색할 경우에 atrist에 오직 해당 작가만 있을 경우만 작품을 보여주는 기능이 있었으면 좋겠습니다.

모음집이 아닌 오리지널 작품만을 추려내는 것이죠.

**Comment by KurtBestor** [comment]
![image](https://user-images.githubusercontent.com/14768120/66252426-7e34a200-e796-11e9-84f0-ccfa38767c2f.png)
이런 식으로 검색하면 돼요.

**Comment by Rounlet** [comment]
아! 이미 있었군요~ 유용하게 사용하도록 하겠습니다~
