### ISSUE TITLE
픽시브 다운 이용시 인터넷 문제 발생 

### ISSUE THREAD

**Issue by kenasis428** [KurtBestor/Hitomi-Downloader-issues#1249]
다운중에 인터넷 창을  열면 DNS_PROBE_FINISHED_NO_INTERNET 이란 오류가 발생하며 

증상은 다운 속도 저하 현상 7M/s 로 설정하며 받는데 
이 수차보다 낮은 1.5m/s 이하로 다운이 진행 

2번뿐이지만 컴퓨터 내의 인터넷 사용속도 저하 

이상하게 픽시브쪽 받으면 이런 현상이 2일전부터 발생하네요

겔부루.트위터,픽시브 3곳에서 이미지 받긴하는데 .. 
이건 좀 너무하다 싶을정도로 매우 느려지고 
사용중이던 인터넷의 모든 화면들이 먹통이 되버립니다.

확인 부탁드리겟습니다.

아 참고로 다운로더 종료 하면 인터넷 정상적으로 돌아옵니다.

**Comment by KurtBestor** [comment]
해당 작업 <kbd>마우스 우 클릭</kbd> - <kbd>정보... (I)</kbd> 눌러서 나온 내용 보여주세요.

**Comment by kenasis428** [comment]
인터넷 설정하고 인터넷 모뎀 건들여보니 정상 작동중이긴합니다.. 
만약 이와같은 현상 발상하면 정보 저장해두겟습니다.
