### ISSUE TITLE
제이마나 다운이 안되네요? 저만 그런가요?

### ISSUE THREAD

**Issue by niaong** [KurtBestor/Hitomi-Downloader-issues#1250]
Failed to read pages : AttributeError : 'NonoType' object has no attribute 'attrs'
Traceback (most recent call last):
file "page_selecter" line 90, in f
File "constants", line 640, in wrapper
Exception: fuckkk....
Traceback (most recent call last):
File "constants", line 615, in wrapper
File "jmana_downloder", line 210, in f
File "jmana_downloder", line 22, in fix_url
AttributeError : 'NonoType' object has no attribute 'attrs'

이렇게 떠요,

**Comment by niaong** [comment]
Invalid: [jmana] https://jmana14.com / book / 최강%20아재%20헌터%20이세계로%20~지금이야말로%20느긋하고%20조용하게%20살고%20싶어~

version: 2.7b
platform: Windows-7-6.1.7601-SP1
gal_num: https://jmana14.com/book/최강%20아재%20헌터%20이세계로%20~지금이야말로%20느긋하고%20조용하게%20살고%20싶어~
dir: 
zip: 
type: jmana
artist: None
url: https://jmana14.com/book/%EC%B5%9C%EA%B0%95%20%EC%95%84%EC%9E%AC%20%ED%97%8C%ED%84%B0%20%EC%9D%B4%EC%84%B8%EA%B3%84%EB%A1%9C%20~%EC%A7%80%EA%B8%88%EC%9D%B4%EC%95%BC%EB%A7%90%EB%A1%9C%20%EB%8A%90%EA%B8%8B%ED%95%98%EA%B3%A0%20%EC%A1%B0%EC%9A%A9%ED%95%98%EA%B2%8C%20%EC%82%B4%EA%B3%A0%20%EC%8B%B6%EC%96%B4~
valid: False
done: True
range: None
range_p: None
single: True
time: 1570272525.3 (Oct 5)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False


[Gallery]
None


[File Names]



[URLs]



[Messages]
stop
Traceback (most recent call last):
File "utils", line 595, in __init__
File "jmana_downloader", line 52, in init
File "jmana_downloader", line 22, in fix_url
AttributeError: 'NoneType' object has no attribute 'attrs'

Invalid: fail=True
stop
EOT: https://jmana14.com/book/최강%20아재%20헌터%20이세계로%20~지금이야말로%20느긋하고%20조용하게%20살고%20싶어~

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by niaong** [comment]
테스트 버전 잘 됩니다.  수리 감사합니다.
