### ISSUE TITLE
여기에 몇 가지 변화 새 버전입니다

### ISSUE THREAD

**Issue by lhj5426** [KurtBestor/Hitomi-Downloader-issues#1251]
![image](https://user-images.githubusercontent.com/30548000/66254000-c659c180-e7a2-11e9-8d0a-f18d1b2710a2.png)

여기에 몇 가지 변화 새 버전입니다

무엇에 번역 될 수

감사

**Comment by KurtBestor** [comment]
이거 번역 부탁드려요: [tr_dic.txt](https://github.com/KurtBestor/Hitomi-Downloader-issues/files/3693454/tr_dic.txt)

**Comment by lhj5426** [comment]
[tr_dic.txt](https://github.com/KurtBestor/Hitomi-Downloader-issues/files/3694080/tr_dic.txt)

감사

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

감사합니다!

**Comment by lhj5426** [comment]
Thank you for all normal
