### ISSUE TITLE
혹시 이런기능도 하나 추가될수있을까요?

### ISSUE THREAD

**Issue by ak156** [KurtBestor/Hitomi-Downloader-issues#1252]
안녕하세요 선생님 항상 프로그램 잘쓰고있습니다
히토미에서 새탭여러개로 다운로드 눌러가며 다운받다가 용량큰건취소되거나멈춰있어서좌절하던 시절을 돌이켜보면 사용하면서 이런프로그램을 만들어주신것에 항상 감사합니다
다름이아니라 혹시 이런기능도 추가될수있을지 싶어서 여쭤봅니다
다운받을때 폴더명과같이 표지도그림파일하나 같이 다운받는기능을 추가해주실수있을까?해서요
그러니까 예를들면 
[Menea The Dog][N／A][N／A] Akaruku Tanoshiku Kimochiyoku (1352336) 폴더와함께
표지파일도 같이하나 더 다운되면서
[Menea The Dog][N／A][N／A] Akaruku Tanoshiku Kimochiyoku (1352336)이름은 같게말이죠
혹시나 가능하시다면 잘부탁드립니다

**Comment by KurtBestor** [comment]
필요한 이유가 있나요?

**Comment by ak156** [comment]
폴더하나하나 들어가서 작품찾기보단 표지보고 찾고싶어서요

**Comment by KurtBestor** [comment]
폴더 미리보기에 보이지 않나요?

**Comment by Dumbisted** [comment]
제작자분 말대로 보통은 폴더 미리보기에 처음 1~2개의 이미지가 보일텐데요? 그걸로도 만족하지 못하신다면 ZIP이나 CBZ 형식으로 압축하신 뒤 CBXShell을 쓰시면 됩니다.

**Comment by ak156** [comment]
우와 CBXShell 정말 감사드려요 압축파일도 이렇게 볼수있게되는군요 
폴더 미리보기는 뭔가 작고 잘안보여서 아쉬웠거든요 
CBXShell 알려주신것 정말 감사드려요

이런식으로 파일들 표지보면서 파일찾고싶었거든요 표지이미지들로만 이미지프로그램으로 넘기면서 파일그림보면서 찾거나 좀 크게 잘 보고싶었는데 미리보기로는 조금 힘들었는데
이런 기능이있는 프로그램 처음알았네요 다시한번 감사드립니다

**Comment by Dumbisted** [comment]
추가적으로, 좀 더 세부적인 것(7z 지원, 미리보기 해상도 설정)을 원하신다면 [CDisplayEX](https://www.cdisplayex.com/)를 추천드립니다. 코믹 뷰어지만 CBXShell 기능도 갖추고 있거든요.

**Comment by ak156** [comment]
꿀팁 감사드려요~ 미리보기해상도설정은어딨는지 잘몰라서 찾아보고있지만
CBXShell정보와 추가정보 정말 감사드려요 ㅎㅎ
