### ISSUE TITLE
익헨뷰어 아이피 벤 당한거같은데

### ISSUE THREAD

**Issue by bcy0906** [KurtBestor/Hitomi-Downloader-issues#1253]
![Screenshot_20191006-121138_EhViewer](https://user-images.githubusercontent.com/56204245/66263723-06db2e80-e7e7-11e9-9f28-9be63c0b583f.jpg) 이런 경우에는 어떻게 해야죠?ㅠㅠ 

> ![Screenshot_20191006-034852_Puffin](https://user-images.githubusercontent.com/56204245/66263729-296d4780-e7e7-11e9-9c6c-4997705762c0.jpg)

**Comment by KurtBestor** [comment]
잘못 찾아오셨어요.
