### ISSUE TITLE
deviant art 다운로드 오류

### ISSUE THREAD

**Issue by Rounlet** [KurtBestor/Hitomi-Downloader-issues#1254]
예를 들어 설명해보겠습니다.
다운로드를 원하는 사이트 https://www.deviantart.com/streetmodders 가 있는데
가보면 아시겠지만 빈 사이트가 아닙니다. 하지만 다운로드 갯수가 '0'이라고 뜨고 되지 않습니다.
반복 시도에도 같은 증상을 보였구요,

아래는 정보입니다.

StreetModders (deviant_streetmodders)

version: 2.7b
platform: Windows-10-10.0.18362
gal_num: https://www.deviantart.com/streetmodders
dir: hitomi_downloaded_deviant\StreetModders (deviant_streetmodders)
zip: 
type: deviant
artist: None
url: https://streetmodders.deviantart.com/
valid: True
done: True
range: None
range_p: None
single: False
time: 1570352126.53 (Oct 6)
tags: []
goodbyedpi: True
lock: False
color: done
paused: False

[Gallery]
None

[File Names]

[URLs]

[Messages]
EOT: https://www.deviantart.com/streetmodders

최근 로그인을 해야만 mature contents들이 풀리던데 이와 관련된 문제인지 궁금합니다.

**Comment by KurtBestor** [comment]
아직 [Group](https://www.deviantartsupport.com/en/article/what-are-groups)은 지원하지 않아요.

**Comment by Rounlet** [comment]
아.. 이제 보니 개별 사이트와 그룹 사이트가 따로 있었네요. 알려주셔서 감사합니다~
