### ISSUE TITLE
이번 패치이후 그림사이즈 때문인건지... 위아래가 겹치는 현상이 생겼네요.

### ISSUE THREAD

**Issue by Honeyneo** [KurtBestor/Hitomi-Downloader-issues#1256]
![hitome](https://user-images.githubusercontent.com/56247450/66290395-2161f480-e91a-11e9-8fad-98223e9c4418.jpg)

이번 패치이후 그림사이즈 때문인건지... 위아래가 겹치는 현상이 생겼네요.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by Honeyneo** [comment]
잘되네요 너무 감사합니다.^^
