### ISSUE TITLE
마나모아 일부링크 다운로드불가

### ISSUE THREAD

**Issue by sdm8524** [KurtBestor/Hitomi-Downloader-issues#1258]
https://manamoa.net/bbs/board.php?bo_table=manga&wr_id=639096
https://manamoa.net/bbs/board.php?bo_table=manga&wr_id=750719

고생하십니다
다른건 다운로드 잘되는데 간혹 한두개씩 다운로드가 되질않고
읽는중으로만 표시되는 링크가 있네요 확인 부탁드립니다

**Comment by KurtBestor** [comment]
해당 작업 <kbd>마우스 우 클릭</kbd> - <kbd>정보... (I)</kbd> 눌러서 나온 내용 보여주세요.

**Comment by sdm8524** [comment]
읽는 중... [이토마치 아키네] Lv2부터 치트였던 전 용사 후보의 느긋한 이세계 라이프 / Lv2부터 치트였던 전 용사 후보의 느긋한 이세계 라이프 3화 (1 / 1)

version: 2.7b
platform: Windows-10-10.0.14393
gal_num: https://manamoa.net/bbs/board.php?bo_table=manga&wr_id=750719
dir: 
zip: 
type: manamoa
artist: 이토마치 아키네
url: https://manamoa.net/bbs/page.php?hid=manga_detail&manga_id=9937
valid: True
done: False
range: None
range_p: None
single: False
time: 1570540576.04 (Oct 8)
tags: []
goodbyedpi: False
lock: False
color: wait
paused: False


[Gallery]
None


[File Names]



[URLs]



[Messages]
redirect: https://manamoa.net/bbs/page.php?hid=manga_detail&manga_id=9937
dirFormat: [artist] title
[seed] Lv2부터 치트였던 전 용사 후보의 느긋한 이세계 라이프 3화 303510

Fail : \\?\c:\users\sin\appdata\local\temp\phantomjs.exe
Traceback (most recent call last):
File "downloader", line 851, in download
IOError: [Errno 28] No space left on device


Fail : \\?\c:\users\sin\appdata\local\temp\phantomjs.exe
Traceback (most recent call last):
File "downloader", line 851, in download
IOError: [Errno 28] No space left on device


Fail : \\?\c:\users\sin\appdata\local\temp\phantomjs.exe
Traceback (most recent call last):
File "downloader", line 851, in download
IOError: [Errno 28] No space left on device


Fail : \\?\c:\users\sin\appdata\local\temp\phantomjs.exe
Traceback (most recent call last):
File "downloader", line 851, in download
IOError: [Errno 28] No space left on device


Fail : \\?\c:\users\sin\appdata\local\temp\phantomjs.exe
Traceback (most recent call last):
File "downloader", line 851, in download
IOError: [Errno 28] No space left on device


Fail : \\?\c:\users\sin\appdata\local\temp\phantomjs.exe
Traceback (most recent call last):
File "downloader", line 851, in download
IOError: [Errno 28] No space left on device


Fail : \\?\c:\users\sin\appdata\local\temp\phantomjs.exe
Traceback (most recent call last):
File "downloader", line 851, in download
IOError: [Errno 28] No space left on device


Fail : \\?\c:\users\sin\appdata\local\temp\phantomjs.exe
Traceback (most recent call last):
File "downloader", line 851, in download
IOError: [Errno 28] No space left on device


Fail : \\?\c:\users\sin\appdata\local\temp\phantomjs.exe
Traceback (most recent call last):
File "downloader", line 851, in download
IOError: [Errno 28] No space left on device


Fail : \\?\c:\users\sin\appdata\local\temp\phantomjs.exe
Traceback (most recent call last):
File "downloader", line 851, in download
IOError: [Errno 28] No space left on device


Fail : \\?\c:\users\sin\appdata\local\temp\phantomjs.exe
Traceback (most recent call last):
File "downloader", line 851, in download
IOError: [Errno 28] No space left on device


Fail : \\?\c:\users\sin\appdata\local\temp\phantomjs.exe
Traceback (most recent call last):
File "downloader", line 851, in download
IOError: [Errno 28] No space left on device


Fail : \\?\c:\users\sin\appdata\local\temp\phantomjs.exe
Traceback (most recent call last):
File "downloader", line 851, in download
IOError: [Errno 28] No space left on device


Fail : \\?\c:\users\sin\appdata\local\temp\phantomjs.exe
Traceback (most recent call last):
File "downloader", line 851, in download
IOError: [Errno 28] No space left on device


Fail : \\?\c:\users\sin\appdata\local\temp\phantomjs.exe
Traceback (most recent call last):
File "downloader", line 851, in download
IOError: [Errno 28] No space left on device


Fail : \\?\c:\users\sin\appdata\local\temp\phantomjs.exe
Traceback (most recent call last):
File "downloader", line 851, in download
IOError: [Errno 28] No space left on device


Fail : \\?\c:\users\sin\appdata\local\temp\phantomjs.exe
Traceback (most recent call last):
File "downloader", line 851, in download
IOError: [Errno 28] No space left on device

**Comment by sdm8524** [comment]
읽는 중... [이토마치 아키네] Lv2부터 치트였던 전 용사 후보의 느긋한 이세계 라이프 / Lv2부터 치트였던 전 용사 후보의 느긋한 이세계 라이프 2화 (1 / 1)

version: 2.7b
platform: Windows-10-10.0.14393
gal_num: https://manamoa.net/bbs/board.php?bo_table=manga&wr_id=639096
dir: 
zip: 
type: manamoa
artist: 이토마치 아키네
url: https://manamoa.net/bbs/page.php?hid=manga_detail&manga_id=9937
valid: True
done: False
range: None
range_p: None
single: False
time: 1570540578.62 (Oct 8)
tags: []
goodbyedpi: False
lock: False
color: wait
paused: False


[Gallery]
None


[File Names]



[URLs]



[Messages]
redirect: https://manamoa.net/bbs/page.php?hid=manga_detail&manga_id=9937
dirFormat: [artist] title
[seed] Lv2부터 치트였던 전 용사 후보의 느긋한 이세계 라이프 2화 5040

**Comment by KurtBestor** [comment]
C 드라이브에 용량이 부족하네요.

**Comment by sdm8524** [comment]
허.. 신기하네요 다운로드폴더는 D드라이브에 따로 용량을 두고 사용하고있는데 C에도 여유용량이 필요한가보군요;; 도움 감사합니다 (_ _)
