### ISSUE TITLE
인스타 다운이 안됩니다

### ISSUE THREAD

**Issue by wc892** [KurtBestor/Hitomi-Downloader-issues#1259]
두명 테스트를 해봤는데 한명은 다운이 됩니다
그런데 다른 한명은 다운이 안됩니다

정보입니다

Traceback (most recent call last):
File "insta_downloader3", line 99, in read
File "insta_downloader3", line 319, in get_imgs
File "insta_downloader4", line 122, in get_urls
Exception: Too short: 0 / 20
- xx_fqqqq

version: 2.7b
platform: Windows-10-10.0.18362
gal_num: https://www.instagram.com/xx_fqqqq/
dir: 
zip: 
type: insta
artist: None
url: https://www.instagram.com/xx_fqqqq
valid: False
done: True
range: None
range_p: None
single: False
time: 1570309544.68 (Oct 6)
tags: []
goodbyedpi: False
lock: False
color: invalid
paused: False

[Gallery]
None

[File Names]

[URLs]

[Messages]
stop
Invalid: fail=False
stop
EOT: https://www.instagram.com/xx_fqqqq/

**Comment by KurtBestor** [comment]
비공개 계정은 지원하지 않아요. 참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/284
