### ISSUE TITLE
선생님 프로그램 잘 쓰고 있는데 오류 제보 드립니다.

### ISSUE THREAD

**Issue by eldkdl2002** [KurtBestor/Hitomi-Downloader-issues#126]
선생님이 만드신 프로그램 매우 잘 쓰고 있습니다. 좋은 프로그램 만들어주셔서 감사합니다.
다름이 아니라 이헨(익헨)의 자료들을 다운로드 받을 때, 일부 파일들이 제대로 다운되지 않는 오류를 발견해서 제보드리게 되었습니다. 아래 링크에는 19금 요소가 포함되어있으므로 열람하실 때 주의해주셨으면 합니다.

https://exhentai.org/g/520803/cf41a9663b
위 링크의 파일은 404 Not Found : 520803 문구가 뜨면서 다운로드되지 않습니다.
링크를 https://e-hentai.org/g/520803/cf41a9663b 로 바꿔서 인터넷 브라우저로 접속하면
파일이 짤렸다고 표시됩니다. 바꾼 주소로 다운로드하려고 해도 같은 오류가 발생합니다.
즉 이헨에서는 짤렸는데 익헨에서는 그대로 남아있는 자료들은 다운로드할 수 없습니다.

https://e-hentai.org/g/1240172/dedfbd42e9
위 링크의 파일은 568장 중에서 563장까지만 다운로드됩니다.
https://e-hentai.org/g/1240186/cc50778e11
위 링크의 파일은 75장 중에서 74장까지만 다운로드됩니다.
아래 두 경우는 추정컨대 99%까지만 다운로드되고 남은 1%가 다운로드되지 않는 오류인 것 같습니다.
선생님께서 시간이 나실 때 해당 오류들을 수정해주시면 매우 감사하겠습니다.

**Comment by KurtBestor** [comment]
1. 익헨 다운로드 안 되는 문제
익헨 계정 5개를 연결시켜 놓았는데 모두 죽었네요. 다시 계정 만드는 데 시간이 걸릴 것 같습니다..

2. 일부 다운로드 안 되는 문제
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview
한번에 안되면 몇번 더 시도하시면 될거예요.

혹시 몰라 제 익헨 계정으로 테스트 해보니 잘 되네요:
![issue126](https://user-images.githubusercontent.com/14768120/41709162-816f3426-757d-11e8-9cbd-45d691872d45.png)

**Comment by eldkdl2002** [comment]
선생님 답변해주셔서 감사합니다. 많은 도움이 되었습니다.
