### ISSUE TITLE
마나모아에서 선택화다운로드가 체크가 안됍니다 

### ISSUE THREAD

**Issue by jj2027** [KurtBestor/Hitomi-Downloader-issues#1261]
선택화목록이 체크가 안돼는데 버그인가요??

전체다운은 돼는데 선택항목은 체크가 안돼네요

**Comment by KurtBestor** [comment]
왼쪽 박스 눌러서 체크한 것 맞나요?

**Comment by jj2027** [comment]
> 박스 박스 체크 체크 한 것 맞나요?

네 버전까지 바꿔가면서 다 체크 해봤는데 클릭이 안돼더라구요 

다른 옵션은 다 잘돼구요

**Comment by KurtBestor** [comment]
어떻게 안 되는지 녹화해서 보여주실 수 있나요?

**Comment by jj2027** [comment]
다운로드 받으려는 사이트주소를 넣고 예를들어 100화까지 있으면 내가 97.98.99화를 받으려고 

클릭하면 그 선택창만 클릭이 안돼고 남어진 다 정상으로 작동해요 
![캡쳐](https://user-images.githubusercontent.com/56298223/66620959-5f625f80-ec1d-11e9-8f9d-94ee075bf81f.png)

여기서 몇화 몇화 클릭이 전혀 안먹힘

**Comment by jj2027** [comment]
> 어떻게 안 됐나요?

내 컴퓨터 문제일까요?

**Comment by KurtBestor** [comment]
![image](https://user-images.githubusercontent.com/14768120/66663770-404be800-ec86-11e9-822d-10ba4b473140.png)

**Comment by jj2027** [comment]
흠 그냥 저 옵션 안쓰는걸 택해야겠네요;;

아무래도 의미가 전달이 안돼는건지 아니면 제 컴터 문제인지 둘중하나인듯하니..
