### ISSUE TITLE
픽시브로 다운시 폴더명 형식이 제대로 작동하지 않는거 같습니다.

### ISSUE THREAD

**Issue by cdreadme** [KurtBestor/Hitomi-Downloader-issues#1267]
제가 저장하는 방식이 artist / [series] title [lang] (id)인데
이 형식이 무시되고 title (artist_id) 형식으로 저장되는거 같은데 
artist 부분에도 다른 작가를 받음에도 pixiv_illust로 고정됩니다.

확인 부탁드립니다.

**Comment by KurtBestor** [comment]
픽시브는 폴더명 형식에 관계 없이 동작해요.
