### ISSUE TITLE
햄스터 다운로드가 안됩니다

### ISSUE THREAD

**Issue by supermekadeathstalin** [KurtBestor/Hitomi-Downloader-issues#1268]
빨간글씨로 can not determine type:영상링크
이렇게 뜹니다.

**Comment by KurtBestor** [comment]
해당 작업 <kbd>마우스 우 클릭</kbd> - <kbd>정보... (I)</kbd> 눌러서 나온 내용 보여주세요.

**Comment by supermekadeathstalin** [comment]
Can not determine type: https://xhamster2.com / videos / painal-latina-not-ready-to-take-it-up-the-ass-6176900

version: 2.7b
platform: Windows-10-10.0.17763
gal_num: https://xhamster2.com/videos/painal-latina-not-ready-to-take-it-up-the-ass-6176900
dir: 
zip: 
type: 
artist: None
url: https://xhamster2.com/videos/painal-latina-not-ready-to-take-it-up-the-ass-6176900
valid: False
done: True
range: None
range_p: None
single: True
time: 1570674959.08 (Oct 10)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False


[Gallery]
None


[File Names]



[URLs]



[Messages]
Invalid: fail=False
EOT: https://xhamster2.com/videos/painal-latina-not-ready-to-take-it-up-the-ass-6176900

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by supermekadeathstalin** [comment]
잘됩니다
