### ISSUE TITLE
픽시브 다운로드 날짜순으로 다운되게 해주실수있나요?

### ISSUE THREAD

**Issue by usas12-dot** [KurtBestor/Hitomi-Downloader-issues#1269]
작가 픽시브 페이지에서 작가님 그림을 모두 다운받을때 그림을 그림 올라온 날짜순으로 다운로드 받고싶습니다  옛날그림->최근그림 순으로 보고싶은데 최근그림과 옛날그림이랑 섞여있으니까 순서대로 볼때 좀 불편하네요ㅠ! 수작업하기엔 그림이 너무 많고요..ㅠ

**Comment by Dumbisted** [comment]
픽시브에서의 이미지명은 숫자 7~8자리와 _p(페이지)의 조합(예: 12345678_p17)인데, 앞의 숫자가 크면 클수록 올라온 날짜가 최신에 근접해지니 참고하시면 됩니다.

**Comment by usas12-dot** [comment]
감사합니다!
