### ISSUE TITLE
nijie 다운로더의 기능을 탑재하실 생각은 없으신가요?

### ISSUE THREAD

**Issue by shopinclude** [KurtBestor/Hitomi-Downloader-issues#1270]
https://github.com/Nandaka/NijieDownloader/releases

에 nijie 다운로더가 존재하는데 여기서 다루면 한층 편하고 많은 사람들이 알 수 있을 것 같습니다.

**Comment by KurtBestor** [comment]
![image](https://user-images.githubusercontent.com/14768120/66582877-66598580-ebbd-11e9-89ca-d3d85deb8eb4.png)

저는 실행이 안 되네요. 혹시 실행 되나요?

**Comment by shopinclude** [comment]
저도 에러가 뜹니다. 해외 사이트나 블로그들 보면 추천하곤 하던 다운로더니 문제 없을거라 생각하는데 이상하군요. 해당 github 버그 제보에도 문제점들은 수정했다는 걸로 아는데 말입니다.
