### ISSUE TITLE
폰헙의 이미지다운

### ISSUE THREAD

**Issue by inki123** [KurtBestor/Hitomi-Downloader-issues#1273]
폰헙에서 영상은 다운이가능하지만 이미지는 다운이불가능하나요?

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by inki123** [comment]
잘되네요 감사합니다
