### ISSUE TITLE
마나모아 다운로드 건의 질문

### ISSUE THREAD

**Issue by pya357** [KurtBestor/Hitomi-Downloader-issues#1275]
안녕하세요 다운로더 정말 편리하고 감사하게 잘 사용하고 있다는 말씀부터 드립니다

처음으로 건의 질문 드립니다

마나모아에서 만화를 다운로드 받을 때

분할이 되어 있는 만화들이 있는데요

예) 친구게임 71화 친구게임 71-2화

이 경우 폴더에 정렬기준이 71-2화가 먼저 올라와서

꿀뷰로 한번에 볼 때 조금 불편하더라구요 ㅠㅠ

다운 받을 때 이름을 조금 바꾸는 형식으로 해결 할 수 있는 방법은 없을까요?

아니면 혹시 제가 모르는 정렬기준 방식이 있을까요...

또, 사이트가 이름을 같게 둔 경우

예) 친구게임 70화가 연속으로 두편 있슴 

https://manamoa15.net/bbs/page.php?hid=manga_detail&manga_id=1267

뒤의 한편만 다운 되는거 같습니다

해결 방법이 있을까요? ㅠㅠ

읽어주셔서 감사합니다

**Comment by KurtBestor** [comment]
PC에서 보는 경우라면 해당 작업 <kbd>마우스 우 클릭</kbd> - <kbd>브라우저로 보기 (B)</kbd> 로 순서대로 볼 수 있어요.

참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/1154#issuecomment-527783584
