### ISSUE TITLE
Hello! youtube video not downloading!

### ISSUE THREAD

**Issue by jessicachon** [KurtBestor/Hitomi-Downloader-issues#1276]
I am trying to download this video https://www.youtube.com/watch?v=ORCes7h8Nhs&t and it is not working. If you can help that would be great! :D

**Comment by KurtBestor** [comment]
Can you watch it in your webbrowser?
I got the following error:
![image](https://user-images.githubusercontent.com/14768120/66697599-117b5380-ed12-11e9-8e58-89a0828836d8.png)

**Comment by jessicachon** [comment]
odd, I can watch it in my browser.
