### ISSUE TITLE
마나모아 다운이 안 되네요

### ISSUE THREAD

**Issue by getsome23** [KurtBestor/Hitomi-Downloader-issues#1277]
항상 잘 쓰고 있습니다. 이번에 사이트 16으로 옮기면서 다운이 다 막혔네요.

**Comment by KurtBestor** [comment]
지금도 안 되나요?

**Comment by wkd284** [comment]
> 
> 
> 지금도 안 되나요?

잘됩니다 선생님.. 뭐가 달라진건없는데... 마나모아 서버 때문인가봐요.

**Comment by getsome23** [comment]
지금은 됩니다. 다행히  마나모아 자체적인 문제였나 보네요. 좋은 프로그램 항상 감사합니다
