### ISSUE TITLE
건의) 다음 블로그와 티스토리 다운로드도 추가해주세요!!

### ISSUE THREAD

**Issue by nptt7777** [KurtBestor/Hitomi-Downloader-issues#1280]
네이버 밖에 다운로드 기능이 없어서
티스토리와 다음 블로그 다운로드도 추가해주시면 감사하겠습니다!!

**Comment by KurtBestor** [comment]
다음 링크에서 `tistory.hds` 다운로드해서 스크립트 적용해주세요: https://github.com/KurtBestor/Hitomi-Downloader/wiki/Scripts
