### ISSUE TITLE
Download Stuck at Waiting or Reading

### ISSUE THREAD

**Issue by arjuna17jax** [KurtBestor/Hitomi-Downloader-issues#1281]
Hi, When i tried to download multiple task, some previous task are downloading and finished without problem. But some task that still reading or waiting stay that way. And then news task always stuck at waiting or reading.
![Untitled](https://user-images.githubusercontent.com/48570369/66711292-38d62d00-edb3-11e9-8e42-83ba0f45b55f.png)

**Comment by KurtBestor** [comment]
Right click on the task and press <kbd>Info... (I)</kbd>. Could you show me what appears?

**Comment by arjuna17jax** [comment]
Waiting... https://hitomi.la / galleries / 877318.html#

version: 2.7b
platform: Windows-7-6.1.7601-SP1
gal_num: https://hitomi.la/galleries/877318.html#
dir: 
zip: 
type: hitomi
artist: None
url: https://hitomi.la/galleries/877318.html#
valid: True
done: False
range: None
range_p: None
single: True
time: 1570950291.38 (Oct 13)
tags: []
goodbyedpi: True
lock: False
color: wait
paused: False


[Gallery]
None


[File Names]



[URLs]

**Comment by KurtBestor** [comment]
Show me what appears when you press <kbd>Shift</kbd> + <kbd>Esc</kbd> after stuck.

**Comment by arjuna17jax** [comment]
Thanks for your responses. But turn out the problem was this host modifier that i use to bypass my country internet cercorship.
https://github.com/gvoze32/bebasid
I already reported the bug to them and it fixed now. Sorry for the inconvenience.
