### ISSUE TITLE
인텔과 AMD CPU 사용 다른점이 있을까요?

### ISSUE THREAD

**Issue by Mariecle** [KurtBestor/Hitomi-Downloader-issues#1285]
일단 버그는 아닌거 같습니다. 
사용상 문제점이나 그런것도 아니고,
그냥 의문점이 있어 문의 드립니다.

제목이 좀 이상한데, 인텔과 AMD 환경에서 살짝 다른 차이가 있네요.
사전에 말씀드릴 비교 환경은 인텔은  i5 3550 이고, AMD는 라데온5 2600 입니다.
둘 다 노 오버로 사용중입니다.
히토미다운로더 버전은 늘 베타 최신 버전을 유지중이고, 모든 버전에서 같은 현상입니다.

둘의 차이점은 프로그램을 실행 후 아이들 상태일때 발생합니다.
인텔 환경에서는 진행중인 다운로드가 없이 프로그램만 실행 시켰을때에
시퓨는 아이들 환경에 맞게 모든 코어가 저클럭이 돼서 아이들 상태로 있습니다.
그런데 유독 AMD에서는 같은 상황에서 실행만 시켜놨을 뿐인데 코어 절반이상은 최고 클럭을 치닫고 있습니다.
트레이로 보내도 똑같고, CPU 로드율을 보면 0%로 작동 안하고 있는건 맞는데 클럭은 안떨어지네요.
프로그램을 완전 종료 시켜야 아이들로 최저 클럭으로 떨어집니다.

이게 은근 신경 쓰여서 인텔에선 그냥 실행시켜 놓는데, AMD에서는 사용안할땐 늘 꺼두다가 괜히 한번 여쭤봅니다.

늘 감사드립니다.

아 그리고 단축키 돌려주세요!!!!

**Comment by KurtBestor** [comment]
어떤 단축키요?

**Comment by Mariecle** [comment]
다운로드 목록에서 마우스 오른쪽 버튼 누르면 나오는 명령 중에 예를 들면,
'완료된 목록 모두 제거'가 마우스 오른쪽 버튼 누르고 R을 누르면 작동했는데
사라졌네요.

**Comment by KurtBestor** [comment]
<kbd>R</kbd> 은 `목록에서 제거` 로 바뀌었어요.
