### ISSUE TITLE
마나모아 다운로드가 다시 안되네요

### ISSUE THREAD

**Issue by 2gilla** [KurtBestor/Hitomi-Downloader-issues#1287]
사이트 접속할 때 cloudflare ddos 방어가 뜬 이후로 다시 안되네요.

**Comment by KurtBestor** [comment]
해당 작업 <kbd>마우스 우 클릭</kbd> - <kbd>정보... (I)</kbd> 눌러서 나온 내용 보여주세요.

**Comment by 2gilla** [comment]
이틀동안 안됐었는데 지금 해보니 되네요. 번거롭게 해드려서 죄송합니다ㅠ
혹시나 필요하실까봐 내용 첨부해드려요.

[오오타케 마사오] 히나마츠리

version: 2.7b
platform: Windows-10-10.0.18362
gal_num: https://manamoa16.net/bbs/board.php?bo_table=manga&wr_id=2103937
dir: D:\#Hitomi\[오오타케 마사오] 히나마츠리
zip:
type: manamoa
artist: 오오타케 마사오
url: https://manamoa16.net/bbs/page.php?hid=manga_detail&manga_id=1795
valid: True
done: True
range: None
range_p: None
single: False
time: 1571363846.16 (Oct 18)
tags: []
goodbyedpi: True
lock: False
color: done
paused: False


[Gallery]
None


[File Names]
[0001] D:\#Hitomi\[오오타케 마사오] 히나마츠리\히나마츠리 EXTRA 29화\0000.jpg
[0002] D:\#Hitomi\[오오타케 마사오] 히나마츠리\히나마츠리 EXTRA 29화\0001.jpg
[0003] D:\#Hitomi\[오오타케 마사오] 히나마츠리\히나마츠리 EXTRA 29화\0002.jpg
[0004] D:\#Hitomi\[오오타케 마사오] 히나마츠리\히나마츠리 EXTRA 29화\0003.jpg


[URLs]
[0001] LazyUrl(
https://manamoa16.net/bbs/board.php?bo_table=manga&wr_id=2103937) --->
https://ironmancdn.xyz/upload/d5bc6f7cc9071d22bed11cff57688492.jpg
[0002] LazyUrl(
https://manamoa16.net/bbs/board.php?bo_table=manga&wr_id=2103937) --->
https://ironmancdn.xyz/upload/79c1421094cce4f0eb69aa6c89d142d6.jpg
[0003] LazyUrl(
https://manamoa16.net/bbs/board.php?bo_table=manga&wr_id=2103937) --->
https://ironmancdn.xyz/upload/4ce35a2c20d9037cca1297edba9abf00.jpg
[0004] LazyUrl(
https://manamoa16.net/bbs/board.php?bo_table=manga&wr_id=2103937) --->
https://ironmancdn.xyz/upload/d0a77b6113a9220b1623d0b794141ebc.jpg


[Messages]
redirect: https://manamoa16.net/bbs/page.php?hid=manga_detail&manga_id=1795
dirFormat: [artist] title
[seed] 히나마츠리 EXTRA 29화 0
EOT: https://manamoa16.net/bbs/board.php?bo_table=manga&wr_id=2103937

2019년 10월 18일 (금) 오전 9:21, Kurt Bestor <notifications@github.com>님이 작성:
