### ISSUE TITLE
사이트 추가 건의 - 마나스페이스

### ISSUE THREAD

**Issue by Euthanatos1** [KurtBestor/Hitomi-Downloader-issues#129]
마루에는 없는 만화가 좀 있는데, 마나스페이스 추가해주시면 안될까요?

https://manaaspace.net/

**Comment by KurtBestor** [comment]
마루마루에 없는 만화가 어떤 게 있나요?

**Comment by Euthanatos1** [comment]
일단 기억나는 것은 MAPS 가 있네요.

**Comment by KurtBestor** [comment]
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

테스트 부탁드려요.
암호 안 걸린 것만 돼요.
