### ISSUE TITLE
프로그램이 계속 응답 없음이 뜹니다.

### ISSUE THREAD

**Issue by john8214** [KurtBestor/Hitomi-Downloader-issues#1292]
![캡처](https://user-images.githubusercontent.com/56732180/67105980-c925cf00-f204-11e9-9ba8-fac7b6437ebe.PNG)
다운로드 목록 쭉 업로드 되다가 자꾸 중단되고 응답없음이 뜹니다.

**Comment by KurtBestor** [comment]
이건 어떤가요?: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by john8214** [comment]
올려주신 링크에서 다운받을 걸로 하니 잘 되네요ㅎㅎ 감사합니다.
