### ISSUE TITLE
로그 조작은 불가능한가요?

### ISSUE THREAD

**Issue by ssjyham** [KurtBestor/Hitomi-Downloader-issues#1294]
개수가 너무 많아서 100개씩 쪼개서 다운받으려고 하는데 지워지네요..
해결 방법은 없을까요?

**Comment by KurtBestor** [comment]
로그 조작이 뭔가요?

**Comment by ssjyham** [comment]
아 앱이 오작동했었네요.. 다시 실행해보니 정상적으로 작동됩니다`
