### ISSUE TITLE
검색기 기본데이터 다운로드중 오류가 발생합니다

### ISSUE THREAD

**Issue by DayBreak000000** [KurtBestor/Hitomi-Downloader-issues#1295]
Traceback (most recent call last):
  File "hitomi_searcher", line 224, in download_json
WindowsError: [Error 32] : u'E:\\hitomi_downloader_GUI\\hitomi_data\\galleries0.json_new'

**Comment by KurtBestor** [comment]
다시 시도해도 그대로인가요?

**Comment by DayBreak000000** [comment]
어제는 여러회차 재시도 해도 그대로였었는데 지금은 정상작동 하네요 감사합니다
