### ISSUE TITLE
Pornhub 다운로드 오류

### ISSUE THREAD

**Issue by orangespoons** [KurtBestor/Hitomi-Downloader-issues#1296]
폰헙 접속은 두가지가 있습니다.
https://www.pornhubpremium.com/view_video.php?viewkey=ph5d951bedeb7fd
https://www.pornhub.com/view_video.php?viewkey=ph5d951bedeb7fd
위는 프리미엄 계정으로 접속했을때 뜨는 것이구요 (프리미엄영상, 일반영상 모두 저 주소로 뜸.)
아래는 일반계정으로 접속했을때 혹은 프리미엄계정으로 일반영상을 Share버튼을 눌러 공유링크를 띄웠을때 나오는 링크입니다.

이 중 프리미엄 계정으로 영상을 다운받으면
현재 모든 영상이 Invalid: [pornhub] https://www.pornhubpremium.com/view_video.php?viewkey=ph5d951bedeb7fd
이런식으로 뜹니다. 빨간글씨로요.

일반 폰업 주소로(https://www.pornhub.com/view_video.php?viewkey=ph5d951bedeb7fd) 복사하면 받아질 때도 있고, 받아지지 않을 때도 있습니다. 근데 대부분 받아지더라고요.

프리미엄계정 다운로드를 수정해주실 수 있을까요?
한 일주일 전쯤엔 잘 됐었는데, 갑자기 안되네요.

*참고로.. 테크니컬 프리뷰로 했는데도 안됐습니다. 동일증상이에요.

**Comment by KurtBestor** [comment]
폰헙 프리미엄 구독 취소해서 테스트해볼 수가 없네요. 계정 주시면 테스트해볼게요.

**Comment by orangespoons** [comment]
> 폰헙 프리미엄 구독 취소해서 테스트해볼 수가 없네요. 계정 주시면 테스트해볼게요.

어느 이메일 주소로 보내야 할까요? ebay에서 구매한 계정 보내드릴게요
