### ISSUE TITLE
인스타그램 다운로드 오류

### ISSUE THREAD

**Issue by saanaaghkd** [KurtBestor/Hitomi-Downloader-issues#1297]
Traceback (most recent call last):
File "insta_downloader3", line 99, in read
File "insta_downloader3", line 319, in get_imgs
File "insta_downloader4", line 31, in get_urls
Exception: Invalid page
- cathrynli

version: 2.7b
platform: Windows-10-10.0.18362
gal_num: https://www.instagram.com/cathrynli
dir: 
zip: 
type: insta
artist: None
url: https://www.instagram.com/cathrynli
valid: False
done: True
range: ~ 50
range_p: None
single: False
time: 1571562762.99 (Oct 20)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False

[Gallery]
None

[File Names]

[URLs]

[Messages]
stop
Invalid: fail=False
stop
EOT: https://www.instagram.com/cathrynli

혹시나 해서 다운로더 삭제 후 재설치 했음에도 오류가 발생합니다. 해당 인스타 뿐만 아니라 모든 인스타 다운로드가 불가합니다.

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/1262#issuecomment-539887994

**Comment by saanaaghkd** [comment]
[out.txt](https://github.com/KurtBestor/Hitomi-Downloader-issues/files/3755595/out.txt)
