### ISSUE TITLE
늑대닷컴 추가부탁드려요

### ISSUE THREAD

**Issue by ourload** [KurtBestor/Hitomi-Downloader-issues#1299]
요새 여기도 많더라고요 추가부탁드립니다
https://wfwf47.com/

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/1210

**Comment by ourload** [comment]
추가할 예정이라는 말씀이신거죠? 아니면 이미 추가되 있다는 건거요?

**Comment by KurtBestor** [comment]
이미 똑같은 내용 올라왔으니 중복이라는 거예요.
