### ISSUE TITLE
건의사항

### ISSUE THREAD

**Issue by rnsrnsrhrnak** [KurtBestor/Hitomi-Downloader-issues#13]
저장폴더: D:\hitomi_downloaded\[artist] 
폴더명 형식: title (id)
1234번 A작가의 B 작품이면 
 D:\hitomi_downloaded\A\B(1234) 이런식으로
저장폴더에도 폴더명 형식에 설정했던 키워드를 적용시킬 수는 없을까요?

**Comment by KurtBestor** [comment]
다음과 같이 폴더명 형식을 지정하면 됩니다:
artist / title (id)
