### ISSUE TITLE
제이마나다운로드가 안돼는데 제 문제일까요??

### ISSUE THREAD

**Issue by lama112** [KurtBestor/Hitomi-Downloader-issues#1305]
제이마나를 이번에 업데이트에서 보고 한번 다운로드 시도해봤는데 안돼네요. 업데이트에 #1250 수정 되어 있다고 되어있길래 제 문제일지도 모르겠지만 혹시나 해서요.

**Comment by KurtBestor** [comment]
해당 작업 <kbd>마우스 우 클릭</kbd> - <kbd>정보... (I)</kbd> 눌러서 나온 내용 보여주세요.

**Comment by lama112** [comment]
[https://jmana26.com/book/쟈히님은 굴하지 않아!#]

Invalid: [jmana] https://jmana26.com / book / 쟈히님은

version: 2.7c
platform: Windows-10-10.0.18362
gal_num: https://jmana26.com/book/쟈히님은
dir: 
zip: 
type: jmana
artist: None
url: https://jmana26.com/book/%EC%9F%88%ED%9E%88%EB%8B%98%EC%9D%80
valid: False
done: True
range: None
range_p: None
single: False
time: 1571794527.28 (Oct 23)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False


[Gallery]
None


[File Names]



[URLs]



[Messages]
No title
stop
Traceback (most recent call last):
File "utils", line 738, in start
File "utils", line 787, in start_
File "jmana_downloader", line 85, in read
File "jmana_downloader", line 78, in name
File "jmana_downloader", line 108, in get_title
Exception: No title

Invalid: fail=True
EOT: https://jmana26.com/book/쟈히님은






[https://jmana26.com/book/깨끗하게 해주시겠어요]


Invalid: [jmana] https://jmana26.com / book / 깨끗하게

version: 2.7c
platform: Windows-10-10.0.18362
gal_num: https://jmana26.com/book/깨끗하게
dir: 
zip: 
type: jmana
artist: None
url: https://jmana26.com/book/%EA%B9%A8%EB%81%97%ED%95%98%EA%B2%8C
valid: False
done: True
range: None
range_p: None
single: False
time: 1571794548.32 (Oct 23)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False


[Gallery]
None


[File Names]



[URLs]



[Messages]
No title
stop
Traceback (most recent call last):
File "utils", line 738, in start
File "utils", line 787, in start_
File "jmana_downloader", line 85, in read
File "jmana_downloader", line 78, in name
File "jmana_downloader", line 108, in get_title
Exception: No title

Invalid: fail=True
EOT: https://jmana26.com/book/깨끗하게

혹시나 해서 두개 다시 해봤는데 이런식이네요.
