### ISSUE TITLE
겔부루 이주소 받을라고하는데 안받아지네요

### ISSUE THREAD

**Issue by kenasis428** [KurtBestor/Hitomi-Downloader-issues#1306]
https://gelbooru.com/index.php?page=post&s=list&tags=ao%2bbeni 

이주소 받을려고하는데요 48장있다고하는데 다운로드는 0장으로서 마무리하네요 ...

ao+beni

version: 2.7c
platform: Windows-10-10.0.17763
gal_num: https://gelbooru.com/index.php?page=post&s=list&tags=ao%2bbeni
dir: hitomi_downloaded_gelbooru\ao+beni
zip: 
type: gelbooru
artist: None
url: https://gelbooru.com/index.php?page=post&s=list&tags=ao%2bbeni
valid: True
done: True
range: None
range_p: None
single: False
time: 1571745841.14 (Oct 22)
tags: []
goodbyedpi: True
lock: False
color: done
paused: False

[Gallery]
None

[File Names]

[URLs]

[Messages]
https://gelbooru.com/index.php?page=dapi&s=post&q=index&tags=ao+beni&pid=0&limit=100
EOT: https://gelbooru.com/index.php?page=post&s=list&tags=ao%2bbeni

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by kenasis428** [comment]
작동됩니다 확인
