### ISSUE TITLE
작가 추천 기능이 안됩니다.

### ISSUE THREAD

**Issue by fjekljtgljelkgjlksjl** [KurtBestor/Hitomi-Downloader-issues#1309]
![Hitomi Downloader 2019-10-23 오전 4_20_28](https://user-images.githubusercontent.com/56893170/67322837-98b79b00-f54c-11e9-988f-037f3509c5d9.png)
![Hitomi Downloader 2019-10-23 오전 4_20_46](https://user-images.githubusercontent.com/56893170/67322847-9bb28b80-f54c-11e9-9c22-761f3b3df26e.png)

분명이 다운받은게 있는데 데이터가 없다면서 작동하질 않습니다.
어떻게 해야할까요....

**Comment by KurtBestor** [comment]
검색기에서 데이터를 다운로드 해주세요.

**Comment by fjekljtgljelkgjlksjl** [comment]
> 검색기에서 데이터를 다운로드 해주세요.

100개 권장량엔 못미치지만 최소조건인 32개 이상 확실히 받고나서 해본거에요.

**Comment by KurtBestor** [comment]
`메뉴` - `검색기...` 에서 `메뉴` - `기본 데이터 다운로드...` 해주세요.

**Comment by fjekljtgljelkgjlksjl** [comment]
> `메뉴` - `검색기...` 에서 `메뉴` - `기본 데이터 다운로드...` 해주세요.

아... 그렇게 하는거였군요 이제 되네요 감사합니다
