### ISSUE TITLE
다운로드용 데이터 다운로드중 오류 발생

### ISSUE THREAD

**Issue by aria1th** [KurtBestor/Hitomi-Downloader-issues#131]
![1](https://user-images.githubusercontent.com/35677394/41698461-0b63a11e-750e-11e8-83dd-331abeb5027f.PNG)
![2](https://user-images.githubusercontent.com/35677394/41698473-198060ac-750e-11e8-81af-f7ea600ea7e1.PNG)

  File "hitomi_searcher", line 148, in download_json
  File "hitomi_searcher", line 343, in download_json_
Exception: WTF

히토미 측에서 목록 불러오는걸 막은건지 모르겠으나..

**Comment by KurtBestor** [comment]
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

테스트 부탁드려요.

**Comment by mxszzz** [comment]
잘 되요 감사함다
