### ISSUE TITLE
더 많은 웹 사이트 추가 요청

### ISSUE THREAD

**Issue by Rocneriano** [KurtBestor/Hitomi-Downloader-issues#1311]
건의할 추가싸이트는
https://vercomicsporno.com
https://www.pornpics.com/
https://www.pichunter.com/

당신이 그들을 추가 할 수 있다면 나는 매우 감사합니다

**Comment by KurtBestor** [comment]
Pornpics 는 추가했어요.

[여기](https://github.com/KurtBestor/Hitomi-Downloader-issues/wiki/Scripts)에서 `pornpic.hds` 다운로드해서 `메뉴` - `스크립트...` (`Menu` - `Script...`) 에서 불러오시면 돼요.
