### ISSUE TITLE
new토끼 문제

### ISSUE THREAD

**Issue by godhen** [KurtBestor/Hitomi-Downloader-issues#1312]
작품 다운로드가 안됩니다.

Can not determine type: https://newtoki30.com / webtoon / 124563?toon=%EC%9D%BC%EB%B0%98%EC%9B%B9%ED%88%B0

version: 2.7c
platform: Windows-10-10.0.18362
gal_num: https://newtoki30.com/webtoon/124563?toon=%EC%9D%BC%EB%B0%98%EC%9B%B9%ED%88%B0
dir: 
zip: 
type: 
artist: None
url: https://newtoki30.com/webtoon/124563?toon=%EC%9D%BC%EB%B0%98%EC%9B%B9%ED%88%B0
valid: False
done: True
range: None
range_p: None
single: True
time: 1571813622.18 (Oct 23)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False

[Gallery]
None

[File Names]

[URLs]

[Messages]
Invalid: fail=False
EOT: https://newtoki30.com/webtoon/124563?toon=%EC%9D%BC%EB%B0%98%EC%9B%B9%ED%88%B0

이렇게 하는게 맞나요??

**Comment by godhen** [comment]
어??? 지원하지 않았나요? 지원사이트에
newtoki.hds 이걸로 추가해서 받기 가능했었는데
더 이상 지원 안하기로 결정 하신건가요??

**Comment by KurtBestor** [comment]
스크립트를 추가하세요.

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/689
