### ISSUE TITLE
원하는 것들을 그룹으로 묶어서 받을 수 있게 하면 어떨까요?

### ISSUE THREAD

**Issue by shopinclude** [KurtBestor/Hitomi-Downloader-issues#1313]
그룹 기능이 있다면 원하는 태그나 픽시브나 트위터, 텀블러 같이 여러개 홈페이지를 가지고 있는 마음에 드는 아티스트 등을 꼭 포토샵 레이어 그룹으로 묶듯이 그룹으로 묶어어서 깔끔하게 정리할 수도 있고 주기적인 다운에도 용이할 것 같네요. 

특히나 그룹 접기 기능까지 있으면 더 깔끔해질 것 같습니다.

태그 및 코멘트 기능이 유용한 것 처럼요.

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/286#issuecomment-546244526

**Comment by KurtBestor** [comment]
![image](https://user-images.githubusercontent.com/14768120/67562853-7eeba300-f75a-11e9-909e-0e398d4465e4.png)

**Comment by shopinclude** [comment]
아.. 전에 분이 올려놓으신 글이 한참 전에 거라서 테스트 요청글도 그때 올리신 줄 알았습니다;;;

아무튼 그룹 기능 추가 및 제거 해봤는데 잘 됩니다. 감사합니다!
