### ISSUE TITLE
Downloader not displaying all downloaded items

### ISSUE THREAD

**Issue by brucealanwayne** [KurtBestor/Hitomi-Downloader-issues#1316]
Hello dev,

Thanks for the great program. After updating to version 2.7c, my list only shows 7 items. I would like for the program to show all the files I have downloaded thus far, kinda like hdoujin downloader. Before the update, it used to show everything I've downloaded so far. This is convenient for me since the thumbnail shows the preview of the mangas I've downloaded, so I would just have to navigate in the program instead of searching through windows explorer.

Is there a way to change this in the settings? I can't find any option pertaining to this.

Thanks for your great work and thanks for reading this. I wish you a pleasant day sir.

**Comment by KurtBestor** [comment]
Please send me your `<your executable filename>.ini` before overwriting it.

**Comment by brucealanwayne** [comment]
Hello Kurt,

Attached is the ini file. Thank you very much for your support.

**Comment by brucealanwayne** [comment]
[hitomi_downloader_GUI.zip](https://github.com/KurtBestor/Hitomi-Downloader-issues/files/3777682/hitomi_downloader_GUI.zip)

**Comment by KurtBestor** [comment]
There is actually 7 tasks.
You have to save tasks before exiting:
![image](https://user-images.githubusercontent.com/14768120/67743275-7c8e8f00-fa61-11e9-81ac-b3ae511b6f9f.png)

**Comment by brucealanwayne** [comment]
Sorry about that, I have save and quit the program. And here is the ini file:

[Uploading hitomi_downloader_GUI.zip…]()

Even after quitting and reopening, it still only shows the 7 items. Thanks for your support.
