### ISSUE TITLE
눈동자 일부가 제대로 다운로드가 되지 않습니다.

### ISSUE THREAD

**Issue by pcpp57** [KurtBestor/Hitomi-Downloader-issues#1318]
저는 꿀뷰를 이용하고 있는데요 
저번 업데이트 부터였던가 저저번이던가
100% 다운로드 완료 결과물 중에 일부 이미지가 안나오기 시작하더라구요 
전부 그러는게 아니라 정상적으로 잘 다운로드 받다가 가끔 하나둘씩 튀어 나옵니다. 

다운로드 받다가 꼬인거가 싶어 재 다운로드 해봐도 증상이 똑같구요 
그래서 해당 만화가 잘못 올라온건가 싶어 몇년된 놈들로가다 정상적으로 다운로드 되던
놈으로다가 테스트를 해보니 똑같이 가끔 다운로드가 제대로 안되는 놈이 하나씩 튀어 나오더군요 

혹시 몰라 파일속성 비교해보니 흥미로운 사실을 알수 있었는데
다운로드된 파일들이 24비트 이미지 파일과 8비트 이미지 파일들이 섞여있고 
제 이야기의 주제인 그 문제의 파일들은 어김없이 8비트 이미지들에게서만 
그 문제를 야기 하더군요...

근데 여기서 더 재미있는건.... 알씨에선 그 문제의 8비트 이미지 들도 잘 보여진다는거... 

그리고 혹시 몰라 문제의 다운로드 재대로 안되는것들의 일부를.....

1499885
1500052
1504290
1503847
1502930
1502259
1495293
1496310
1503805

**Comment by KurtBestor** [comment]
알씨에선 잘 보이는데 꿀뷰에선 안 보이는 거라면 꿀뷰 문제인 것 같네요.

참고로 제 쪽에선 꿀뷰로도 잘 보이네요.
