### ISSUE TITLE
픽시브 ip가 일시적으로 잠겼습니다.

### ISSUE THREAD

**Issue by fjscl4869** [KurtBestor/Hitomi-Downloader-issues#1322]
다운로드도 되질않구 픽시브 로그인테스트 누르면 ip가 일시적으로 잠겼다고 뜹니다.
문제가 무엇인가요..

**Comment by KurtBestor** [comment]
해당 작업 <kbd>마우스 우 클릭</kbd> - <kbd>정보... (I)</kbd> 눌러서 나온 내용 보여주세요.

**Comment by Airity27** [comment]
같은 증상이라 올립니다

로그인 실패: pixiv_https://www.pixiv.net / member.php?id=9016
[옵션 - 설정 - 픽시브 설정 - 로그인] 에서 설정해주세요.

version: 2.7c
platform: Windows-10-10.0.18362
gal_num: https://www.pixiv.net/member.php?id=9016
dir: 
zip: 
type: pixiv
artist: None
url: https://www.pixiv.net/member.php?id=9016
valid: False
done: True
range: None
range_p: None
single: False
time: 1571997783.93 (Oct 25)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False


[Gallery]
None


[File Names]



[URLs]



[Messages]
PIXIV_TYPE: user
stop
Invalid: fail=False
stop
EOT: https://www.pixiv.net/member.php?id=9016

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by cocoman1111** [comment]
저 다운로드가 안되는데요.. 꼐속 대기중이라고 뜹니다..

**Comment by arong7895** [comment]
픽시브 로그인이랑 다 다운로드랑 다 되네요

**Comment by kenasis428** [comment]
작동 확인 !.

**Comment by fjscl4869** [comment]
정상 작동됩니다! 언제나 감사드려요!

**Comment by ds5pin** [comment]
픽시브 로그인 테스트시 발생하는 에러
IP가 일시적으로 잠겼습니다. 잠시후에 다시 시도해주세요.
{"has_error":true,"errors":{"ststem":
{"message":"access_denied","code":1508}}}
