### ISSUE TITLE
Mac 가상윈도우 문의

### ISSUE THREAD

**Issue by Picstory** [KurtBestor/Hitomi-Downloader-issues#1325]
안녕하세요
Mac에서 Parallels Desktop으로 윈도우10을 사용입니다.
가상윈도우에서 히토미 다운로더를 실행하면 마나모아 다운로드가 안됩니다.
유투브는 정상적으로 다운로드 되네요
마나모아 링크를 넣으면 제목, 페이지 수 를 정상적으로 불러오는데 다운로드가 안되고 주황색 표시가 되버립니다.
어떠한 이미지 페이지 링크를 넣어도 주황색 표기가 나오고 다운로드가 안되네요.
제목과 권수, 이미지 수 는 정상적으로 불러오는데 IOError: [Errno 22] 를 뿜어내며 이미지를 전혀 다운로드 하지 못합니다.
어떠한 문제가 있는걸까요?

**Comment by KurtBestor** [comment]
해당 작업 <kbd>마우스 우 클릭</kbd> - <kbd>정보... (I)</kbd> 눌러서 나온 내용 보여주세요.
