### ISSUE TITLE
픽시브 로그인시 IP가 일시적으로 잠겼습니다.

### ISSUE THREAD

**Issue by ITS2318** [KurtBestor/Hitomi-Downloader-issues#1332]
![캡처](https://user-images.githubusercontent.com/35250779/67561025-0800db00-f757-11e9-83b3-a8b1eae6cdc3.PNG)

vpn때문인가 싶어서 꺼보기도 하고 재부팅도 해보고 했는데 안되네요

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/1322

**Comment by cocoman1111** [comment]
저 다운로드가 안되는데. 혹시 되시는분 계신가요??
