### ISSUE TITLE
픽시브 ip가 막혔다고 계속 뜹니다

### ISSUE THREAD

**Issue by dltkdgus03316** [KurtBestor/Hitomi-Downloader-issues#1334]
![스크린샷(110)](https://user-images.githubusercontent.com/57023551/67612309-92d7e900-f7dc-11e9-9c9a-0ae80e045753.png)

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/1322#issuecomment-546299905
