### ISSUE TITLE
네이버 웹툰 화질문제

### ISSUE THREAD

**Issue by biy00ss** [KurtBestor/Hitomi-Downloader-issues#1337]
안녕하세요.
경의로운 프로그램 만들어 주셔서 감사합니다.

저는 네이버 웹툰을 다운받아 소장하고 있습니다.
다만 제가 발견한점은
프로그램으로 다운받은 이미지 용량이랑 실제로 네이버 웹툰에서 받은 용량이 다르다는것입니다.
이게 무슨 말이냐면

개장수 1화에 2번째 컷
https://image-comic.pstatic.net/webtoon/729255/1/20190605144750_50fc12a2f0ebd17deed53ff653b35cf5_IMAG01_1.jpg

을 크롬에서 f12누른후 주소 알아내서 위 주소로 다운받으면
59.8kb 용량이 나오는데
다운로더로 받으면 43.5kb 용량이 나옵니다.
이게 왜 용량차이 나는가요? 화질저하는 있어보이지 않습니다만..
가능하면 원본이미지를 받고 싶은 욕심이 있습니다.
jpg 용량을 0% 혹은 100%로 설정해도 똑같은 결과가 나옵니다.

제가 방법을 잘못 알고 있는가요?

좋은 프로그램 만들어주셔서 다시 한번 감사드립니다.

**Comment by KurtBestor** [comment]
모바일 버전으로 다운로드하는데, 모바일 버전이 살짝 화질이 안 좋네요.

그런데 눈에 크게 띄는 차이는 아니니 그냥 두려구요.

**Comment by biy00ss** [comment]
> 모바일 버전으로 다운로드하는데, 모바일 버전이 살짝 화질이 안 좋네요.
> 
> 그런데 눈에 크게 띄는 차이는 아니니 그냥 두려구요.

네 답변 감사합니다.
혹시 탑툰 다운로드는 추가 계획에 있으신가요?
