### ISSUE TITLE
hitomi downloader 다운이 안됩니다.

### ISSUE THREAD

**Issue by khanms0011** [KurtBestor/Hitomi-Downloader-issues#1338]
기존 사용중이였으나 업데이트 오류로 삭제 후 다시 받으려 했지만
2.7c 다운 클릭 시 찾을수 없는 페이지로 넘어 갑니다.
혹시 저는 받을수 없는 건가요 아니면 다른 문제가 있는건가요?
죄송하지만 답변 부탁드립니다.

**Comment by khanms0011** [comment]
혹시 가능하시다면 rksdlqna@naver.com으로 보내주셔도 됩니다.

**Comment by KurtBestor** [comment]
어떤 통신사 쓰시나요?

**Comment by khanms0011** [comment]
안녕하세요
메일 주셔서 감사합니다.
인터넷은 티브로드 씁니다.
혹시 문제가 되나요?
그리고 혹시 문제가 된다면 이메일로 최신 업데이트 파일 받을 수 있을까요?
번거러우시겠지만 부탁드립니다.
수고하세요
 
-----Original Message-----

**Comment by KurtBestor** [comment]
여기에서 받아주세요: https://drive.google.com/open?id=1_CK-e7erBQL_VwhezdMNvQ-zFET17m-s

**Comment by koigokoro2** [comment]
저도 sk브로드밴드 씁니다. 
자동 업데이트를하면 매우 느린속도로 진행되다가 결국엔 응답없음이 되고
수동 업데이트를 하면 매우 느린속도로 되다가 절반을 채 못채우고 다운로드가 멈춥니다.

근데 저 주소로 받은 파일은 액세스 권한이 없다고 뜨네요

**Comment by khanms0011** [comment]
잘 받았습니다.
감사합니다. 
-----Original Message-----

**Comment by khanms0011** [comment]
인터넷 문제 인가요?
갑작스러워서 잘 모르겠습니다. 
-----Original Message-----

**Comment by khanms0011** [comment]
히토미 링크 형식이 달라져서 안되더군요 위에 다른분이 올려 주신거 글보고 혹시나 부탁드립니다.
새로 올리신 test 파일도 구글 드라이브로 부탁드려도 될까요?
