### ISSUE TITLE
사이트 추가 건의

### ISSUE THREAD

**Issue by kusunu** [KurtBestor/Hitomi-Downloader-issues#1339]
https://www.porncomixonline.net/
이 사이트도 추가해주심 안될까요?
또한 기부는 안 받으시나요?

**Comment by TAKE-401** [comment]
기부/후원은 위에 스폰서버튼을 눌러보세요

**Comment by kusunu** [comment]
오늘부터 스폰 시작했습니다.

**Comment by kusunu** [comment]
> 기부/후원은 위에 스폰서버튼을 눌러보세요

알려주셔서 감사합니다. 오늘부터 스폰 시작했네요

**Comment by KurtBestor** [comment]
추가했어요: https://github.com/KurtBestor/Hitomi-Downloader-issues/wiki/Scripts

후원 감사합니다!
