### ISSUE TITLE
기본데이터 다운이 불가합니다.

### ISSUE THREAD

**Issue by cpslqlf** [KurtBestor/Hitomi-Downloader-issues#1340]
이번 업데이트 이후에, 새로운 데이터를 받으려 기본데이터 다운을 시작해도 0/20에서 멈춰 움직이질 않습니다. 다른 사이트에서 다운은 가능한데, 유독 자체 프로그램으로 데이터를 받으려면 멈춰버리네요.

**Comment by KurtBestor** [comment]
어떤 ISP 쓰시나요?

**Comment by cpslqlf** [comment]
sk 쓰고 있습니다.
