### ISSUE TITLE
사이트 추가 건의

### ISSUE THREAD

**Issue by TAKE-401** [KurtBestor/Hitomi-Downloader-issues#1341]
늘 수고 많으십니다.

혹시 http://www.11toon.com/ 라는 사이트도 추가가 가능할까요?

지금 업로드 되어있는 전국요호 번역본들 중에서 거의 유일하다시피 누락된 화수가 체워진 상태로 되어있습니다.

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/302

**Comment by ntspaceowl** [comment]
> 늘 수고 많으십니다.
> 
> 혹시 http://www.11toon.com/ 라는 사이트도 추가가 가능할까요?
> 
> 지금 업로드 되어있는 전국요호 번역본들 중에서 거의 유일하다시피 누락된 화수가 체워진 상태로 되어있습니다.

혹시 무사히 구하셨나요 ㅠㅠ 저도 전국요호 너무 아끼는데 정발본 구매도 안되고 해메이고 있습니다
