### ISSUE TITLE
대량으로 받을 경우, 프리징이 일어나면서 다운 기록이 증발합니다.

### ISSUE THREAD

**Issue by yoysh** [KurtBestor/Hitomi-Downloader-issues#1342]
과거에도 몇 번 이런 에러 혹은 받는 도중 갑자기 프로그램이 뻗어 받던 히토미들의 정보가 싸그리 날아가는 경험을 했었습니다.

실시간 혹은 몇 분 간격으로 자동 리스트세이빙 기능이 있었으면 좋겠습니다.

**Comment by qwertgb99** [comment]
옵션에 자동저장 있어요

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/242
