### ISSUE TITLE
bilibili 안받아지는 파일 문의드려요

### ISSUE THREAD

**Issue by nopeher** [KurtBestor/Hitomi-Downloader-issues#1343]
https://www.bilibili.com/video/av73543384/?p=14
이 파일을 받으려고 하는데
다시시작를 눌러봐도 1.1kb만 받아지고 중지되어서 문의드립니다.
---------------------------------

NOGIBINGO!10蓝光特典全集(生肉)_p14

version: 2.7c
platform: Windows-10-10.0.18362
gal_num: https://www.bilibili.com/video/av73543384/?p=14
dir: hitomi_downloaded_bili\NOGIBINGO!10蓝光特典全集(生肉)_p14
zip: 
type: bili
artist: None
url: https://www.bilibili.com/video/av73543384/?p=14
valid: False
done: True
range: None
range_p: None
single: False
time: 1572299717.4 (Oct 29)
tags: []
goodbyedpi: False
lock: False
color: invalid_done
paused: False

[Gallery]
None

[File Names]
[0001] hitomi_downloaded_bili\NOGIBINGO!10蓝光特典全集(生肉)_p14\73543384_0.flv

[URLs]
[0001] LazyUrl(https://www.bilibili.com/video/av73543384/?p=14) ---> http://upos-hz-mirrorwcsu.acgvideo.com/upgcxcode/52/40/125884052/125884052-1-80.flv?e=ig8euxZM2rNcNbRVhWUVhwdlhWd17WdVhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEVEuxTEto8i8o859r1qXg8xNEVE5XREto8GuFGv2U7SuxI72X6fTr859r1qXg8gNEVE5XREto8z5JZC2X2gkX5L5F1eTX1jkXlsTXHeux_f2o859IB_&deadline=1572306918&gen=playurl&nbs=1&oi=237306440&os=wcsu&platform=pc&trid=3486dd572ff14d5abcbeff1950d4cb1f&uipk=5&upsig=bf83b35c387cf626974dee2b8f86c746&uparams=e,deadline,gen,nbs,oi,os,platform,trid,uipk&mid=0

[Messages]
resolution: 1080p
n_threads: 8
rename (1): E:\hitomi_downloader_GUI\hitomi_downloaded_bili\NOGIBINGO!10蓝光特典全集(生肉)_p14\73543384_0.flv -> E:\hitomi_downloader_GUI\hitomi_downloaded_bili\NOGIBINGO!10蓝光特典全集(生肉)_p14\tmp1BDB7A50_0.flv
[code]
1
[out]
ffmpeg version 4.1 Copyright (c) 2000-2018 the FFmpeg developers
built with gcc 8.2.1 (GCC) 20181017
configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth
libavutil 56. 22.100 / 56. 22.100
libavcodec 58. 35.100 / 58. 35.100
libavformat 58. 20.100 / 58. 20.100
libavdevice 58. 5.100 / 58. 5.100
libavfilter 7. 40.101 / 7. 40.101
libswscale 5. 3.100 / 5. 3.100
libswresample 3. 3.100 / 3. 3.100
libpostproc 55. 3.100 / 55. 3.100
[concat @ 06474300] Impossible to open 'tmp1BDB7A50_0.flv'
tmp1BDB7A50_list.txt: Invalid data found when processing input

Traceback (most recent call last):
File "utils", line 930, in finish
File "bili_downloader2", line 88, in post_processing
File "ffmpeg", line 462, in join
File "ffmpeg", line 122, in rename
Exception: No file

EOT: https://www.bilibili.com/video/av73543384/?p=14

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/1167#issuecomment-547274856
