### ISSUE TITLE
히토미 검색 화면에서 이미지 로드를 못합니다.

### ISSUE THREAD

**Issue by AKGGB** [KurtBestor/Hitomi-Downloader-issues#1345]
![제목 없음](https://user-images.githubusercontent.com/57125844/67740524-7399bf80-fa59-11e9-94c3-8af4972e639b.png)

검색을 마지막으로 사용한게 4일 정도 전이고 별 문제없이 사용했습니다.

오류 메시지 등은 안나오고 밝은 회색 화면 그대로 입니다. 재부팅도 해보고 exe파일도 다시 받아서 해봤으나 같은 현상이 나타납니다.

**Comment by DevSejin** [comment]
저도 그렇네요

**Comment by KurtBestor** [comment]
`옵션` - `설정` - `고급 설정` 에서 `DPI 우회` 가 켜져있나요?

**Comment by AKGGB** [comment]
네 켜져있습니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by AKGGB** [comment]
감사합니다 해결됬어요

**Comment by rlagns415** [comment]
![히토미 다운로더 문제](https://user-images.githubusercontent.com/57150258/67793381-09673600-fabe-11e9-8863-42e8961512fa.jpg)
새로 다운로드해도 안되고

위 파일은 아래 사진 처럼 뜨면서 실행이 안됨니다
![히토미 다운로더 문제 2](https://user-images.githubusercontent.com/57150258/67793565-69f67300-fabe-11e9-9da2-7b9d9c03c253.jpg)

**Comment by rlagns415** [comment]
해결 했습니다 위 파일 실행 안되는 원인은 백신 때문이라서 백신은 종료후 실행하니 잘됨니다
