### ISSUE TITLE
개발자님 부탁드립니다! 마나모아말고도 다음웹툰이랑 뉴토끼도 추가부탁드려요(스크립트)

### ISSUE THREAD

**Issue by jihochoi524** [KurtBestor/Hitomi-Downloader-issues#1346]
마나모아말고도 다음 웹툰 다운로드가 될수 있게 해주신것 정말감사드립니다. 저는  불법만화만 다운하지않고 만화를 돈주고 결제를 했습니다. 결제한편들까지혹시 결제이후에는 다운할수있는건가요?
그리고 혹시 뉴토끼도 스크립트에 추가해주실수있으실까요?

**Comment by jihochoi524** [comment]
Can not determine type: https://newtoki30.com / webtoon / 279999 / %EC%82%BC%EA%B5%AD%EC%A7%80%ED%86%A1?toon=%EC%9D%BC%EB%B0%98%EC%9B%B9%ED%88%B0

version: 2.7c
platform: Windows-10-10.0.17134
order: 0
group: False
gal_num: https://newtoki30.com/webtoon/279999/%EC%82%BC%EA%B5%AD%EC%A7%80%ED%86%A1?toon=%EC%9D%BC%EB%B0%98%EC%9B%B9%ED%88%B0
dir: 
zip: 
type: 
artist: None
url: https://newtoki30.com/webtoon/279999/%EC%82%BC%EA%B5%AD%EC%A7%80%ED%86%A1?toon=%EC%9D%BC%EB%B0%98%EC%9B%B9%ED%88%B0
valid: False
done: True
range: None
range_p: None
single: True
time: 1572333660.59 (Oct 29)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False


[Gallery]
None


[File Names]



[URLs]



[Messages]

**Comment by KurtBestor** [comment]
다음웹툰은 내장으로, 뉴토끼는 스크립트로 이미 추가되어있어요.
