### ISSUE TITLE
pornhubpremium 폰헙 프리미엄 다운로드 안되는 문제..

### ISSUE THREAD

**Issue by kaca2100** [KurtBestor/Hitomi-Downloader-issues#1347]
일반 URL은 다운이 되는데, 프리미엄 계정은 다운이 안되는 문제가 있습니다. 

직접 링크 따서 해보니 다운로드 받는데 문제는 없군요.. 태그가 바뀌거나 했나봅니다. 

URL : https://www.pornhubpremium.com/view_video.php?viewkey=ph5dae63b0a06b4

    scripts = parser.findAll('script', attrs={'type':'text/javascript'})

    for script in scripts:
        text = script.text
        if text.find('flashvars') != -1:
            js = text

    if 'js' in locals():
        js = js[:js.find('loadScriptUniqueId.push')]
        down_link = js2py.eval_js(js)

프리미엄 계정이 없다 하셨으니 

첨부한 소스로 링크따서 작동되게 해주시면 감사하겠습니다.

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/1335
