### ISSUE TITLE
작가명 복사가 안됩니다

### ISSUE THREAD

**Issue by lm8459** [KurtBestor/Hitomi-Downloader-issues#1348]
![제목 없음](https://user-images.githubusercontent.com/49753181/67779034-702d2500-faa7-11e9-8e7b-a45abd1972db.png)

받아져 있는 것들은 작가명 복사가 되지만

예전거를 받든 최근거를 받든 작가명 복사 활성화가 안됩니다

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/1308#issuecomment-545198894
