### ISSUE TITLE
히토미 링크 체계가 완전히 바뀌어서 다운이 안됩니다.

### ISSUE THREAD

**Issue by yoysh** [KurtBestor/Hitomi-Downloader-issues#1349]
기존에는 해당 갤러리 숫자만 나오던게 이제는 갤러리 이름과 언어 체계가 붙은 채로 링크가 나와서 다운로드가 막혀버렸습니다.

예시:https://hitomi.la/doujinshi/mizugi-helena-ga-shoukan-dekinai!-%ED%95%9C%EA%B5%AD%EC%96%B4-1508941.html

혹시나 갤러리 넘버만으로도 되는지 확인해봤지만 이것도 완전히 막혔네요.

**Comment by whgmlqja12** [comment]
주소체계가 달라져버려서 보통 히토미에서 연결안되면 이헨으로 넘어가거나 히요비로 넘어가는데 그러지도 않고 바로 빨간글짜 떠버리네요

**Comment by legnalegna** [comment]
검색기에서 기본 데이터를 다운로드 하여도 최신 업데이트는 못갖고 오는거 같네요

**Comment by exclude2000** [comment]
아 완전 망했는데...
익헨에서 목록 보고 숫자만 다운로더에 입력해서 히토미로 받아왔는데
주소가 이렇게 되면 숫자만 쳐서 받는게 불가능하게 될지도...아씹;

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by exclude2000** [comment]
> 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

우와 테스트해보니 숫자만으로도 잘 받아지네요.
너무 감사합니다!
