### ISSUE TITLE
다운로더 창에 태그 삽입해주실 수 있나요?

### ISSUE THREAD

**Issue by MoongSong** [KurtBestor/Hitomi-Downloader-issues#135]
![default](https://user-images.githubusercontent.com/40514407/41806962-072adad6-7702-11e8-8092-c89830b3c192.png)

개인적으로 다운받았던 것들을 폴더 들어가서 보는 것보단 다운로더 창에서 보는게 더 편해서 이렇게 쓰고 있는데요.
검색기에서 볼 때 처럼 다운로드 창에서도 관련 태그들을 볼 수 있게 설정할 수 있으면 좋을 것 같아요.
그리고 다운로드 창에도 태그검색이나 작가검색 기능을 넣어 받은 작품들을 분류해서 볼 수 있게 하면 좀 편할 것 같구요.

**Comment by KurtBestor** [comment]
![gengoroh](https://user-images.githubusercontent.com/14768120/41807719-02e8af00-770e-11e8-88fd-73ccaaec80da.png)

작가나 제목은 이렇게 검색할 수 있어요. 더 자세한 사용법은 [도움말 - 사용법 - 다운로더 목록 필터링] 을 참고해주세요.

태그는 안타깝게도 저장을 하도록 하지 않아서 어떻게 할 수가 없네요.
다만 새로 받아진 것에 한해서 tag:xxx 같은 식으로 검색할 수 있게 만들었어요:
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview
테스트 부탁드려요.

**Comment by MoongSong** [comment]
검색 잘 돼요 감사합니다
