### ISSUE TITLE
미리보기 사진이 안뜹니다

### ISSUE THREAD

**Issue by Febrie0** [KurtBestor/Hitomi-Downloader-issues#1353]
제곧내

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/1345

**Comment by dhtpdud** [comment]
허... 백신때문이라니...

**Comment by dhtpdud** [comment]
> https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview 이거 써 보십셔

감사합니다.

**Comment by lahuraa** [comment]
같은 문제입니다 이미지 미리보기가 안되네요 참고 대로 해봐도 ㅜㅠ
위의 테크니컬 프리뷰 링크에 있는 버전은 실행하니 권한이 없다고 나옵니다.

**Comment by Febrie0** [comment]
감사합니다
