### ISSUE TITLE
눈동자 기본데이터에 누락된 부분이 있습니다

### ISSUE THREAD

**Issue by yuchan39** [KurtBestor/Hitomi-Downloader-issues#1354]
눈동자 기본데이터에 누락된 부분이 있습니다. pennel같은 작가는 히토미에 들어가면 나오는 자료가  다운로더로 검색하면 일부가 나오지 않네요. 그리고 shirasagi rokuwa 같은 작가는 검색할 때 완성되게끔 뜨지 않고 자료도 조금만 검색됩니다. 그 외에도 쾌락천같은 경우는 삭제된 자료에서도 COMIC Kairakuten BEAST 2019-11이나 weekly kairakuten 13 같은 최신판은 검색이 안되네요. 혹시 저작권 때문에 완전히 삭제된건가요 아니면 데이터가 누락이 된건가요? 궁금해서 여쭤봅니다. 감사합니다.

**Comment by KurtBestor** [comment]
검색기에서 나오지 않는 작품 알려주세요. 저는 4개 전부 뜨네요.
`shirasagi rokuwa` 는 `rokuwa` 였다가 최근에 바뀌었는데 시간 좀 지나면 업데이트 될거예요.
삭제된 데이터 업데이트했어요. 이제 검색 될거예요.

**Comment by yuchan39** [comment]
제가 pennel과 nathaniel pennel을 삭제된 데이터랑 같이 보다 보니 자료를 검색할때 갯수를 헷갈렸나 봅니다. 정상적으로 전부 검색이 되네요. 그리고 업데이트한 삭제된 데이터로 쾌락천도 전부 검색됩니다. 정말 감사합니다!
