### ISSUE TITLE
이헨/익헨 그룹명 안 뜹니다

### ISSUE THREAD

**Issue by uniyui** [KurtBestor/Hitomi-Downloader-issues#1356]
![2](https://user-images.githubusercontent.com/57224328/67952594-df825080-fc30-11e9-9372-7d60d0a93ce2.png)

이번에 2.7d 업뎃하고 몇 개 다운받아봤는데 이렇게 그룹명이 안 떠서 파일명에도 N/A 처리가 됩니다. 
이전 버전에는 문제가 없었는데 이렇게 되네요.

**Comment by KurtBestor** [comment]
히토미에서 아직 업데이트가 안 돼서 그런건데, 지금은 업데이트 됐네요.
이전 버전도 똑같아요.
