### ISSUE TITLE
삭제된 데이터 섬네일 안보이는 문제(히요비)

### ISSUE THREAD

**Issue by ko003230** [KurtBestor/Hitomi-Downloader-issues#1358]
삭제된 데이터 중 미리보기 섬네일이 안나오는 경우는 종종 있었지만 근래 자료가 안나오기에 
찾아보니 히요비로 다운되는 파일들이 미리보기가 안되는거같습니다

검색 미리보기는 안나오고 다운 완료된  파일은 나옵니다

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by ko003230** [comment]
> 테스트 부탁 드려요 : https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

테스트 후 기본 데이터 검색, 삭제된 데이터 검색 모두 미리보기 잘 나옵니다!
