### ISSUE TITLE
검색후 미리보기 썸네일이 보이지 않습니다

### ISSUE THREAD

**Issue by kid9010** [KurtBestor/Hitomi-Downloader-issues#1359]
서치-검색기-검색후
얼마전부터 미리보기가 안되는것 같네요

DPI 우회도 켜져있는데 말이죠

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/1345, https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/1358
