### ISSUE TITLE
사이트 추가 건의.

### ISSUE THREAD

**Issue by seo1547** [KurtBestor/Hitomi-Downloader-issues#1360]
초창기 때 부터 편하게 잘 쓰고 있습니다. 정말 감사드립니다.

다름이 아닌 일본 굴지의 소설, 팬픽 사이트인 하멜른을 추가해주셨으면 하고 건의 해봅니다.

https://syosetu.org/

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/571

**Comment by KurtBestor** [comment]
https://github.com/KurtBestor/Hitomi-Downloader/issues/571#issuecomment-620495084
