### ISSUE TITLE
hitomi downloader 다운문제 관련

### ISSUE THREAD

**Issue by khanms0011** [KurtBestor/Hitomi-Downloader-issues#1363]
안녕하세요
앞 전에 다운 문제관련 문의드렸던 사람입니다.
다름이 아니라 이번 업데이트 파일 역시 다운이 안되더군요
죄송하지만 다시한번 구글드라이브로 부탁드려도 될까요?
그리고 추가 건의사항으로 앞으로 업데이트 된 파일을
링크형식이 아닌 구글드라이브도 병행 가능한지 여쭙니다.
수고하십시오.

**Comment by mondayholic** [comment]
혹시 DNS서버 설정 해보셨나요? 저는 DNS서버 자동에서 8.8.8.8로 바꿔보니까 다운되네요
