### ISSUE TITLE
오류가 디스플레이 인터페이스 발생한

### ISSUE THREAD

**Issue by lhj5426** [KurtBestor/Hitomi-Downloader-issues#1366]
![image](https://user-images.githubusercontent.com/30548000/68061818-9d94ff80-fd41-11e9-91ea-db1cf5fd87c7.png)
![image](https://user-images.githubusercontent.com/30548000/68061821-a5ed3a80-fd41-11e9-8226-e40d9fa8d16f.png)

사용에는 영향을 미치지 않지만

그러나 불편 찾고

하, 하, 하

개발자 바랍니다

다음 교정에서

**Comment by KurtBestor** [comment]
번역 부탁드려요: [tr_dic.txt](https://github.com/KurtBestor/Hitomi-Downloader-issues/files/3801348/tr_dic.txt)

**Comment by lhj5426** [comment]
[tr_dic.txt](https://github.com/KurtBestor/Hitomi-Downloader-issues/files/3801434/tr_dic.txt)
테스트 및 어디 번역을 볼 필요가없는 어떤 장소를 알게하려고

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by lhj5426** [comment]
[tr_dic.txt](https://github.com/KurtBestor/Hitomi-Downloader-issues/files/3801489/tr_dic.txt)
약간의 문제는 약간의 수정

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by lhj5426** [comment]
OK Thank you developer
