### ISSUE TITLE
핀터레스트 사용법이 어떻게 되는지 궁금합니다.

### ISSUE THREAD

**Issue by nerere** [KurtBestor/Hitomi-Downloader-issues#1367]
안녕하세요, 제작자님. 무료로 재능기부해주신 덕분에 손쉽게 잘 쓰고 있습니다. 노고에 언제나 감사드린다는 말씀을 먼저 전하고 싶습니다.
각설하고, 핀터레스트를 이용하려고 하는데 어떻게 이용하는지 몰라 이렇게 글을 남겨 봅니다.
검색창에서 pinter_라고 따로 카테고리가 설정되어 있는 건 확인했는데 
여기서 어떻게 진행해야 하는지 모르겠습니다. 
핀터레스트 이미지 주소는 https://www.pinterest.co.kr/pin/[18자리 숫자]
이런 식으로 되어 있는데 히토미 다운로더 검색창 pinter_ 뒤에 18자리 숫자를 입력하면 invaild라는 빨간색 문자와 함께 다운로드가 되지 않습니다.
그렇다고 pinter_ 카테고리를 설정하지 않고 https://www.pinterest.co.kr/pin/[18자리 숫자] 통째로 검색창에 넣고 다운로드를 해봐도 invaild라는 문자가 뜹니다.
게시판을 찾아보니 작성자님께서 https://www.pinterest.com/bsheppard0097 라는 형식으로 치면 다운이 된다고 하셨는데 그렇게 해도 먹통입니다..ㅠㅠ 어떻게 해야 다운받을 수 있는지 모르겠습니다.
부디 사용법을 알려주시면 감사드리겠습니다. 혹여 제 컴퓨터 상의 문제인건지, 아니면 제가 사용법을 제대로 숙지하지 못한 건지 궁금합니다.
주말 쉬는 시간에 이렇게 폐를 끼쳐드려 정말로 죄송합니다.

**Comment by KurtBestor** [comment]
다음과 같이 보드 주소를 입력해주세요: https://www.pinterest.co.kr/bsheppard0097/models/

**Comment by nerere** [comment]
KurtBestor님, 한창 휴식을 가질 일요일인데도 불구하고, 이렇게 일부로 짬을 내어 답변해주셔서 진심으로 감사드립니다. 저같은 문외한을 위해서 이렇게 기꺼이 시간 내주시고, 친절히 설명해주셔서 감사드립니다. 이 유틸리티를 처음 접했을 때부터 매양 감사한다는 마음을 가지고 있습니다. IT문외한인 저도 손쉽게 쓸 수 있도록 매번 업데이트해주시고 오류를 고쳐주셔서 감사드립니다.
다시 한 번 일요일인데 이렇게 폐를 끼쳐서 죄송하다는 말씀드립니다. 그리고 답변 감사드려요!
