### ISSUE TITLE
최신업데이트를 하고 실행하니 백신에서 바이러스로 보고 삭제합니다.

### ISSUE THREAD

**Issue by jave7** [KurtBestor/Hitomi-Downloader-issues#1370]
업데이트 될때마다 매번 해왔고, 이전 2.7c 버전까지는 잘 실행되다가

오늘 11/4일 2.7d버전을 업데이트하고 나니 실행창이 뜨지않길래 보니

백신프로그램에서 바이러스로 보고 삭제했네요. 프로그램 예외로 하면 뜨지않는거 같긴한데

혹여나 다른 사람도 이렇게 되는지 확인부탁드립니다.

실행한 백신프로그램은 카스퍼스키 프리 안티바이러스입니다.

**Comment by KurtBestor** [comment]
![image](https://user-images.githubusercontent.com/14768120/68101941-ae956a80-ff13-11e9-984b-e52bf5554511.png)

오진이라고 보고 받았어요. 좀 있으면 고쳐질거예요.

**Comment by jave7** [comment]
빠른 피드백 감사합니다
