### ISSUE TITLE
마나모아 다운로드가 되지않습니다

### ISSUE THREAD

**Issue by siwkd2** [KurtBestor/Hitomi-Downloader-issues#1371]
몇번 시도해봤는데 안되는걸로  봐선 패치를 한거같습니다

읽는중까지만 뜨고 그다음부턴 진행자체가 되지않아 오류코드는 올릴려고해도 없습니다

시간나시면 업데이트해주시면 감사하겠습니다

**Comment by rakukracha** [comment]
보아하니 클라우드 플레어로 DDOS 방어하는 상태 같던데
이건 좀 기다리면 풀릴거예요. 아마도...
물론 풀려면 풀수도 있겠지만, 툭하면 방식이 바뀔수 있어서 제작자님도 힘들듯?

**Comment by lducjswo** [comment]
주소를 manamoa16.net로 바꿔서 받으면 잘 됩니다
전부터 이런 증상생길때마다 이 방법으로 되더라구요

**Comment by rakukracha** [comment]
> 주소를 manamoa16.net로 바꿔서 받으면 잘 됩니다
> 일시적인 해결법이지만 전부터 이런 증상생길때마다 이 방법으로 되더라구요

우와~ 그런게 또 되는군요.
덕분에 받으려던거 무사히 받았습니다. ㅋ

**Comment by soulkcake** [comment]
16으로 가니까 다운받아지네요 너무 감사합니다!!

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview
