### ISSUE TITLE
사이트 추가 건의 입니다^^

### ISSUE THREAD

**Issue by geniussjt** [KurtBestor/Hitomi-Downloader-issues#1373]
진짜 호두코믹스 시즌2라고 나왔습니다
스크립트 지원되게 꼭 부탁드립니다^^
https://hoduco04.net/웹툰
그리고 굿밤되세요^^

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/1174
