### ISSUE TITLE
업데이트 문제입니다....

### ISSUE THREAD

**Issue by dydtjq1357** [KurtBestor/Hitomi-Downloader-issues#1374]
전에도 질문을 했었는데요 업데이트시 다하고 마지막에 파일을 못찾겠습니다 하면서 업데이트가 끝나면서 프로그램을 열경우 텍스트가 나와서 글이 뜹니다. 그래서 그냥 최신 파일을 다시 받았어요.. 혹시 그 전에 얻은걸 프로그램에 넣고싶은데요 이미있는 폴더를 인식하는 방법이 무엇인가요??!

**Comment by KurtBestor** [comment]
원래 프로그램이 있던 경로에 실행파일 (*.exe) 넣으시면 돼요.
