### ISSUE TITLE
3가지 건의사항 입니다

### ISSUE THREAD

**Issue by idroto** [KurtBestor/Hitomi-Downloader-issues#138]
1. 다른 작품이지만 제목과 언어가 같을 경우 중복제거로 처리되는데

작가나 페이지수까지 같아서 확실히 중복인 경우에만 제거 되게 할수는 없을까요?

2. 검색기에서 우클릭했을때 작가명,시리즈,캐릭터명 복사가 있는데 

작품 넘버 복사도 있었으면 좋겠습니다 

3. 마루마루 다운로드할때 매번 전체를 다운로드 할 필요 없이 최신화만 받을수 있도록

원화는 화수만 받는 기능이 추가되면 좋을것 같습니다

감사합니다.

**Comment by KurtBestor** [comment]
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview
1, 2번 고친 버전입니다. 테스트 부탁드려요!

3번은 이미 있는 기능이예요.
다운로드 버튼에서 화살표를 클릭하거나 우클릭하면 다음과 같은 메뉴가 나옵니다:
![marumaru](https://user-images.githubusercontent.com/14768120/42127350-cfe27054-7cd1-11e8-8ad8-3bfc1bb8beff.png)

**Comment by idroto** [comment]
갤러리 넘버 복사도 잘되고 제목 언어만 같은 다른 작품들도 이제 중복제거 켜도 정상적으로 잘 뜨네요
1,2번 모두 잘 됩니다 더 편리하게 사용할 수 있겠네요
감사합니다.
