### ISSUE TITLE
사소한 기능 건의

### ISSUE THREAD

**Issue by listandtag** [KurtBestor/Hitomi-Downloader-issues#1381]
다운로드 완료 시 파일의 '수정한 날짜'가 다운로더에 링크를 등록한 시점으로 변경이 되는데

'수정한 날짜'를 그냥 다운로드가 완료된 시점으로 그대로 두는 옵션도 추가해주세요.

**Comment by KurtBestor** [comment]
필요한 이유가 있나요?

**Comment by listandtag** [comment]
한 번에 수십 개씩 받으면 다운로드는 링크 등록한 순서대로 되는데,
나중에 날짜순으로 정렬할 때 수정한 날짜가 같은 시간(분 단위)인 파일이 여러개라 뒤죽박죽이 되네요...

**Comment by KurtBestor** [comment]
해당 작업들 작업정보 보여주세요.

**Comment by listandtag** [comment]
한 번에 100개 넘게도 받고 그러는데 완료 시 자동삭제를 켜놔서 남은 게 없네요;

**Comment by KurtBestor** [comment]
수십개씩 받아도 밀리초 단위로 시간이 달라서 정렬은 제대로 될텐데요.. 다시 같은 현상이 발생하면 해당 작업들 정보 보여주세요.

**Comment by listandtag** [comment]
넵 다음 기회에.....아마 제 생각엔 윈10 탐색기가 병신이 아닐까 합니다....
