### ISSUE TITLE
2.7d 버전이 다운로드 되지 않습니다.

### ISSUE THREAD

**Issue by NounKim** [KurtBestor/Hitomi-Downloader-issues#1382]
GUI 를 클릭하면 사이트에 연결할 수 없다고 뜹니다.

github-production-release-asset-2e65be.s3.amazonaws.com

코드는 downloader 라이브러리를 찾을 수 없다고 실행이 안됩니다.

현재 소지한 버전은 2.7b 버전이며 검색한 만화의 썸네일이 보이지 않습니다.

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/1324
