### ISSUE TITLE
네이버 웹툰 다운로드 지원 관련

### ISSUE THREAD

**Issue by tdi2020** [KurtBestor/Hitomi-Downloader-issues#1384]
안녕하세요 존경하는 선생님!
항상 감사히 잘 사용하고 있습니다.
네이버 웹툰에서 '도전만화' 와 '베스트도전만화' 란이 있습니다.
현재 이 두곳은 다운이 되지 않는데 이것도 받는 방법이 있을까요?

**Comment by KurtBestor** [comment]
`도전만화` 는 모바일 버전 웹 페이지가 없나요?

**Comment by tdi2020** [comment]
확인해보니 도전만화는 없네요! 도전만화의 윗단계인 베스트도전 부터 모바일버전이 있어요.
