### ISSUE TITLE
새로운 검열방식 우회를 대비해야 할 것 같습니다.

### ISSUE THREAD

**Issue by cshipa** [KurtBestor/Hitomi-Downloader-issues#1387]
https://youtu.be/Df8glloVdoo
10월에 dpi 우회를 막는 기술이 개발되었는데, 곧 정부 차원에서도 적용될 것 같습니다.
위 유튜브 링크의 내용을 보면 파편화된 사이트 주소 평문을 다시 합치는 방식의 검열로 추정되는데 히토미 다운로더도 이를 피하긴 어려울 것 같네요.
혹시 대안이나 대비책이 있나요?

**Comment by KurtBestor** [comment]
DPI 우회를 막는 기술 역시 많이 있는데, 대표적으로 중국의 [황금방패](https://en.wikipedia.org/wiki/Great_Firewall#Blocking_methods) 가 있어요.
[GoodbyeDPI](https://github.com/ValdikSS/GoodbyeDPI), [유니콘 HTTPS](http://unicorn-adblock.com/%EC%9C%A0%EB%8B%88%EC%BD%98-https-for-windows/), [Sniper](https://github.com/sniper-internet/Sniper-desktop-release) 모두 중국에선 동작하지 않아요.

한국이 이런 기술들을 적용한다면 일부 VPN 말고는 방법이 없을 수도 있어요.

**Comment by RaceDriverMIKU** [comment]
히토미 다운로더가 지원하는 프록시는 프로토콜이 뭔가요? Socks 인가요? HTTP 인가요?

**Comment by KurtBestor** [comment]
@RaceDriverMIKU 
모두 지원해요.
프로토콜을 명시하지 않으면 HTTP 로 적용돼요.
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/1031
