### ISSUE TITLE
ZIP 외에 CBZ 확장자도 지원 부탁드립니다.

### ISSUE THREAD

**Issue by dkraktksid** [KurtBestor/Hitomi-Downloader-issues#139]
ZIP 압축 후 확장자를 CBZ로 바꿔주는 기능을 넣어주셨으면 합니다.

파일 관리를 위해 개인용 문서 파일들은 ZIP, 7Z 등으로 압축하고, 만화책은 CBZ, CBR 등으로 압축해서 사용하고 있습니다. 프로그램 정말 잘 쓰고 있지만 다운로드 후 ZIP로 자동압축되는 것까진 좋은데 CBZ로 확장자를 바꿔야 하는게 여간 귀찮은 일이 아닙니다. ㅠㅠ

**Comment by KurtBestor** [comment]
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

테스트 부탁드려요.

**Comment by dkraktksid** [comment]
확인했습니다. 아주 잘됩니다. 감사합니다. 😄
