### ISSUE TITLE
픽시브 다운로드에 문제가 있는것 같습니다.

### ISSUE THREAD

**Issue by catarina38** [KurtBestor/Hitomi-Downloader-issues#1390]
안녕하세요. 배포해주신 프로그램 감사히 잘 쓰고 있습니다.

다름이 아니라 픽시브에서 자료를 받는데 문제가 생겨 문의드립니다.

https://www.pixiv.net/member.php?id=11937

이런식으로 작가페이지 주소를 입력해 자료를 받을때는 문제가 없었는데

https://www.pixiv.net/search.php?s_mode=s_tag&word=%E3%83%97%E3%83%AA%E3%83%B3%E3%82%BB%E3%82%B9%E3%82%B3%E3%83%8D%E3%82%AF%E3%83%88%21Re%3ADive

이런식으로 키워드 검색을 한 주소를 입력해 받을때는 자료파일 갯수만 읽어오고 다운로드가 되지 않습니다.

작업정보에는 

Fail : \\?\E:\hitomi_downloaded_pixiv\プリンセスコネクト!Re:Dive (pixiv_search_プリンセスコネクト!Re:Dive)\[デニオール・デニオン@リク停止] 77781132_p2 美しいボクの生暖かい風.png
Traceback (most recent call last):
File "downloader", line 768, in download
IOError: [Errno 22] invalid mode ('wb') or filename: u'\\\\?\\E:\\hitomi_downloaded_pixiv\\\u30d7\u30ea\u30f3\u30bb\u30b9\u30b3\u30cd\u30af\u30c8!Re:Dive (pixiv_search_\u30d7\u30ea\u30f3\u30bb\u30b9\u30b3\u30cd\u30af\u30c8!Re:Dive)\\[\u30c7\u30cb\u30aa\u30fc\u30eb\u30fb\u30c7\u30cb\u30aa\u30f3@\u30ea\u30af\u505c\u6b62] 77781132_p2 \u7f8e\u3057\u3044\u30dc\u30af\u306e\u751f\u6696\u304b\u3044\u98a8.png'

이 문구가 반복적으로 나타나고 있습니다.

확인 부탁드리며 혹시 질문방법이 틀렸다면 지적을 부탁드립니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by catarina38** [comment]
Invaild 오류가 발생합니다.

작가 페이지 주소로 받을때는 여전히 문제 없었습니다.

이하 작업정보 전문입니다.

Invalid: [pixiv] https://www.pixiv.net / search.php?s_mode=s_tag&word=%E3%83%97%E3%83%AA%E3%83%B3%E3%82%BB%E3%82%B9%E3%82%B3%E3%83%8D%E3%82%AF%E3%83%88%21Re%3ADive

version: 2.7d
platform: Windows-10-10.0.17763
order: 0
group: False
gal_num: https://www.pixiv.net/search.php?s_mode=s_tag&word=%E3%83%97%E3%83%AA%E3%83%B3%E3%82%BB%E3%82%B9%E3%82%B3%E3%83%8D%E3%82%AF%E3%83%88%21Re%3ADive
dir: 
zip: 
type: pixiv
artist: None
url: https://www.pixiv.net/search.php?s_mode=s_tag&word=%E3%83%97%E3%83%AA%E3%83%B3%E3%82%BB%E3%82%B9%E3%82%B3%E3%83%8D%E3%82%AF%E3%83%88%21Re%3ADive
valid: False
done: False
range: None
range_p: None
single: False
time: 1573647762.5 (Nov 13)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False


[Gallery]
None


[File Names]



[URLs]



[Messages]
PIXIV_TYPE: search
Type: all
info: {'ecd': None, 'scd': None, 'bgt': None, 'blt': None, 'type': None, 'order': 'date_d'}
プリンセスコネクト!Re：Dive (pixiv_search_プリンセスコネクト!Re：Dive)
tags: [r-18]
tags_ex: []
read ugoira... 77613364
read ugoira... 77464282
read ugoira... 77318935
requests GET https://app-api.pixiv.net/v1/search/illust error: ('Connection aborted.', BadStatusLine('No status line received - the server has closed the connection',))
stop
Traceback (most recent call last):
File "utils", line 790, in start
File "utils", line 837, in start_
File "pixiv_downloader", line 181, in read
File "pixiv_downloader", line 386, in get_imgs
File "FUCK(4)\aapi", line 42, in no_auth_requests_call
File "FUCK(4)\api", line 67, in requests_call
PixivError: requests GET https://app-api.pixiv.net/v1/search/illust error: ('Connection aborted.', BadStatusLine('No status line received - the server has closed the connection',))

Invalid: fail=True

**Comment by KurtBestor** [comment]
다시 시도해도 안 되나요?

**Comment by catarina38** [comment]
죄송합니다. 제 컴퓨터 쪽에 문제가 있었던거 같습니다.

제대로 작동하네요 감사합니다!
