### ISSUE TITLE
픽시브 페이지 지정 다운로드를 '웹사이트 페이지' 기준으로 추가해주실 수 있나요?

### ISSUE THREAD

**Issue by lgx2nicphy** [KurtBestor/Hitomi-Downloader-issues#1392]
히토미 다운로더 항상 감사하게 쓰고 있습니다.  히토미 다운로드에선 아무런 불편함이 없는데요.

 픽시브를 다운받을 때,  '페이지 지정 다운로드' 기능이 조금 불편해요.

페이지 5으로 하면,  픽시브에 올라온 이미지파일 5개만 받아지는데요. 

 제가 원했던 건 픽시브 웹페이지의 이미지 페이지 1 2 3 4  이 페이지였거든요. 웹사이트의.  

웹사이트의 페이지를 기준으로 바꿔주실 수 있나요?

 혹은,  이전에 다운받았던 로그가 남아서,  이전에 다운받았던 건 새로 받지 않게 되면 좋겠어요. 

다운받은 후에 태그별로 다른 폴더에 재분류하는 데,  이전에 받았던것까지 모두 다 받아져요. 

 히토미 다운로더 항상 유용하게 쓰고 있습니다.   감사합니다.

**Comment by lgx2nicphy** [comment]
4개월 전에 픽시브에서 좋아하는 일러스트레이터의 이미지 모두 받았는 데,  

현재 추가로 새로 올라온 이미지들만 받고 싶은 데,  이걸 지정할 수 있게 되면 좋겠어요. 

 
 웹사이트 픽시브 페이지에서 1페이지에 있는 이미지만 모두 받거나, 

픽시브 포스팅 기준으로 포스팅 몇개 받거나 하는 등으로요.  


 웹사이트 기준으로 해당 ID의 1페이지에 있는 이미지 모두 저장 이런 식으로 되면 정말 좋겠어요. 


 지금은 지정 페이지 다운로드가, 이미지 파일 숫자로 받아져서,  

픽시브 포스팅마다 올라온 이미지 갯수가 다르다보니  

이미지 파일 갯수 알려면 제가 일일이 숫자 센 후에 계산기로 덧셈해서 

새로 받아야할 이미지 숫자 계산하고 입력했어요 ㅠㅠ   


픽시브 이미지를 받고나서는 이미지 중에 마음에 안 드는 건 삭제하거나 

태그별로 다른 폴더에 분류하고 있어서  

왕차 처음부터 끝까지 새로 받는 기능만으로는 불편해서 요청 드립니다.

**Comment by KurtBestor** [comment]
다운로드하고 파일 옮긴 후에 `다시 시작` 하면 이미 다운로드한 파일은 제외하고 받아요.

**Comment by lgx2nicphy** [comment]
> 다운로드하고 파일 옮긴 후에 다시 시작 하면 이미 다운로드한 파일은 제외하고 받아요.

다운로드 완료 내역에 있는 것을 마우스 오른쪽 클릭하고 나오는 메뉴에서 '다시 시작' 말씀이신가요?

다운로드 완료 내역에서 지운 이후에는 무조건 다시 새로 다 받나요?

지금 제가 확인해보니까 그냥 처음부터 새로 다 받아지고 있어서요.
