### ISSUE TITLE
폴더 이름을 '일본어'로 저장하는 기능 추가해주실 수 있나요? 

### ISSUE THREAD

**Issue by lgx2nicphy** [KurtBestor/Hitomi-Downloader-issues#1393]
e-hentai 주소를 입력해도 

바로 hitomi로 빠른 속도로 다운받아지더군요.  정말  편하게 사용하고 있습니다.

 그런데 폴더명이 항상 알파벳 로마자로만 저장이 되는 데,  

e-hentai에서 일본어 제목으로 표기되어 있어도 폴더는 항상 로마자로 변형이 되어요. 

옵션에서 폴더 이름을 일본어로 저장되는 기능 추가해주실 수 있나요?

개발해주셔서 감사합니다.

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/855

**Comment by lgx2nicphy** [comment]
> 참고해주세요: #855

흠.. 올해 5월달에 이미 건의가 들어갔는 데 아직도 못 고친 걸 보면 그냥 실력이 없어서 못 하는거였군여..

**Comment by KurtBestor** [comment]
음.. 그렇게 생각하시면 어쩔 수 없네요. 원하시는 대로 영영 안해드릴게요.
