### ISSUE TITLE
최근 다운속도가 0kb가 됩니다

### ISSUE THREAD

**Issue by ritwork** [KurtBestor/Hitomi-Downloader-issues#1394]
한꺼번에 많은걸 다운받는게 문제가 되었는지 요 며칠간 0kb가 뜨네요 다운이 안되서..

익헨쪽에만 이상이 생깁니다

히토미는 무리가 없습니다

**Comment by KurtBestor** [comment]
해당 작업 <kbd>마우스 우 클릭</kbd> - <kbd>정보... (I)</kbd> 눌러서 나온 내용 보여주세요.

**Comment by ritwork** [comment]
확인해보니 아마 윗글에 있던 ip밴 비슷한거같습니다 윗글에 따라 해결방법찾아보겟습니다
