### ISSUE TITLE
호두 코믹스 스크립트 어찌써야하는지 하나도 모르겠습니다.

### ISSUE THREAD

**Issue by hejw1004** [KurtBestor/Hitomi-Downloader-issues#1397]
호두 코믹스 스크립트 어찌써야하는지 하나도 모르겠습니다.
참고 하라는 글을 들어가도 프로그래밍은 1도 모르는 사람이라서요.
어찌 써야하나요?

**Comment by KurtBestor** [comment]
호두코믹스 폐쇄돼서 이제 지원하지 않아요.
