### ISSUE TITLE
다운받은 url 정보를 수정할 방법은 없을까요

### ISSUE THREAD

**Issue by sameer-g** [KurtBestor/Hitomi-Downloader-issues#1398]
망가쇼미같은 경우는 끝에 숫자만 변경되는 것 같은데 다시 받는 대신 url을 수정해서 새로고침 하는 식으로 받게 할 수 없을까요?

**Comment by KurtBestor** [comment]
[여기](https://github.com/KurtBestor/Hitomi-Downloader-issues/wiki/Scripts) 에서 `Replace URLs` 스크립트 받아서 쓰세요.

스크립트 사용 방법은 `도움말` - `사용법... (F1)` - `스크립트` 참고해주세요.
