### ISSUE TITLE
혹시 1.9e 다운로더쓰시는분들중 랜섬뜨는분

### ISSUE THREAD

**Issue by rabirabin** [KurtBestor/Hitomi-Downloader-issues#14]
없나요 appcheck 가  랜섬웨어 확인되었다고 자꾸해서...........혹시 저랑같은거뜨시는분 ㅠㅠ

**Comment by KurtBestor** [comment]
다운로더 특성 상 동시에 여러개를 다운로드하는데, 그 과정에서 많은 파일을 동시에 수정합니다. 이걸 랜섬웨어로 오진하는 것 같습니다.
관련 링크를 첨부합니다:
http://motivation.tistory.com/964
https://checkmal.zendesk.com/hc/ko/articles/218824967
