### ISSUE TITLE
사이트 추가 건의 - 픽시브 코믹스

### ISSUE THREAD

**Issue by MoongSong** [KurtBestor/Hitomi-Downloader-issues#140]
https://comic.pixiv.net/
지금 보니까 픽시브 코믹스에 있는 작품들은 받아지질 않던데.. 혹시 이쪽도 다운로드 가능하게 해주실 수 있을까요?

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview
