### ISSUE TITLE
[사이트 추가 건의]

### ISSUE THREAD

**Issue by ch3rrybls** [KurtBestor/Hitomi-Downloader-issues#1401]
안녕하세요. 개발자님 덕분에 항상 잘 이용하고 있습니다.
스포위키라고 호두코믹스같은곳에서 웹툰을 주로 퍼오는 곳인데 가능하다면 새로운 사이트로 추가 부탁드립니다. 항상 감사합니다!

https://spowiki8.com/
https://spowiki8.com/bbs/board.php?bo_table=webtoon

+아래 두 사이트는 디지털본,스캔본을 취급하는 곳인데 이곳들도 가능하다면 추가 부탁드립니다!!
https://lhscan.net/
https://mangakakalot.com/

**Comment by KurtBestor** [comment]
LHScan 은 이미 지원해요.
