### ISSUE TITLE
vpn 사용중인대 질문이 있습니다

### ISSUE THREAD

**Issue by mimimomozomzom** [KurtBestor/Hitomi-Downloader-issues#1403]
expressvpn을 사용하면 특정앱만 vpn을 사용하게 할수있는 기능이 존재하는대 hitomi_downloader_GUI.exe 이 실행파일을 등록하고 하니 너무많이 받아서 차단된 사이트가 다운로드를 안하는대요 특정앱만 사용이 아닌 전체vpn 하면 너무받아서 안받아지는 사이트도 다운로드가 됩니다 저 실행파일말고도 추가적으로 등록해야할게 있는거같은대 어떤걸 등록하면 될까요 전체vpn 해버리면 다른거 할때 지장이 생겨서요

**Comment by lgx2nicphy** [comment]
너무 많이 받아서 차단되었다는 건, 그 사이트측에서 차단한거니까 안 받아지는거지.  해결 안됨.

**Comment by KurtBestor** [comment]
ExpressVPN 에 문의해주세요.
