### ISSUE TITLE
이헨 다운로드 제한 먹었네요

### ISSUE THREAD

**Issue by hyuneth03** [KurtBestor/Hitomi-Downloader-issues#1405]
이헨에서 다운로드로 이미지 긁고있었는데 너무 많이 다운했다고 일시적 ip밴 먹었습니다 
#900 에 있는 이슈는 이미 보고 스레드도 1로 바꾸고 크레딧으로 리셋도 하고 있습니다
이걸 피할 방법이 VPN외에도 있나요?
아니면 다운로드 속도를 어느정도까지 제한을 해야 다시 안걸릴까요
참고로 현재 2번 먹었습니다

**Comment by KurtBestor** [comment]
해당 작업 <kbd>마우스 우 클릭</kbd> - <kbd>정보... (I)</kbd> 눌러서 나온 내용 보여주세요.

**Comment by hyuneth03** [comment]
[image: image.png]

2019년 11월 17일 (일) 오전 10:39, Kurt Bestor <notifications@github.com>님이 작성:

**Comment by hyuneth03** [comment]
![unnamed](https://user-images.githubusercontent.com/57847774/69005110-8ad01c80-0936-11ea-9701-9469a4bfa2ca.png)

**Comment by KurtBestor** [comment]
`다시 시작` 해서 `작업 정보` 모두 복사해서 보여주세요.

**Comment by lgx2nicphy** [comment]
ip밴 먹은 건,  앱 문제가 아니라.  사이트측에서 차단한건데,  작업 정보를 보여달라는 KurtBestor는 멍청하다.   그리고 내가 hyuneth03한테 답변하자면, 그건 하루에 다운받는 용량을 기준으로 하는 거라서.  속도 문제가 아니다.   하루 용량 제한이 있고,  크레딧으로 리셋하면  하루어치 용량 다시 받을 수 있게 되지만 하루용량 어치를 또 다 쓰면 다시 차단되지.   하루 지나면 해결된다.   그러니까 속도가 빨라서 차단된 게 아니고,   ip마다 하루 용량 제한을 건다.

**Comment by whatohyou** [comment]
이헨/익헨의 경우에는 크레딧이나 gp로 다운가능 수를 리셋하거나 안하거나 일정 숫자 이상 이미지를 뷰 하면 무조건 ban을 먹게 되어 있습니다. 그래서 아카이브 다운로드를해서 zip파일을 받는 것입니다. ban의 경우 1시간->24시간->1주일->30일(?기억 안남) 등으로 진행됩니다. 1시간벤되면 24시간 내에 또 ban되면 24시간 벤으로 진행되고 24시간 벤되면 1주일 내에 벤당하면 1주벤으로 진행되는 방식입니다.
