### ISSUE TITLE
실행 자체가 안됩니다.

### ISSUE THREAD

**Issue by aorl1598** [KurtBestor/Hitomi-Downloader-issues#1406]
확장자가  downloader.py로 되고 실행 불가능 하네요

따로 설치해야하는게 있는건가요

**Comment by KurtBestor** [comment]
[여기](https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/latest) 에서 다운로드 해주세요.

**Comment by aorl1598** [comment]
똑같습니다.. py로 확장자가 나오네요

**Comment by KurtBestor** [comment]
`hitomi_downloader_GUI.zip` 다운로드해주세요.
