### ISSUE TITLE
데이터 다운로드가 적용이 안되는것 같습니다.

### ISSUE THREAD

**Issue by whgmlqja12** [KurtBestor/Hitomi-Downloader-issues#1409]
늦어도 뜬지 1시간 이내에 거의 업데이트 됬는데 지금 5~6페이지에서 갱신이 멈춰있네요

**Comment by KurtBestor** [comment]
어제 잠깐 크롤러 서버 점검하느라 멈췄었어요. 지금은 제대로 될 거예요.
