### ISSUE TITLE
invalid라고 뜨면서 다운이 되질 않습니다.

### ISSUE THREAD

**Issue by 12344353** [KurtBestor/Hitomi-Downloader-issues#141]
![image](https://user-images.githubusercontent.com/40817956/42259268-b05e1136-7f9a-11e8-8531-68c64f394e78.png)

사진처럼 뜨면서 다운이 되질 않습니다.
그냥 검색해서 받으면 아무 문제가 없는데,
403 forbidden검색으로 받은 파일들만 이렇네요.

**Comment by KurtBestor** [comment]
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

테스트 부탁드려요.

**Comment by 12344353** [comment]
제대로 작동하네요! 감사합니다.
