### ISSUE TITLE
마나모아 암살교실 다운이 안됩니다.

### ISSUE THREAD

**Issue by aceburnett** [KurtBestor/Hitomi-Downloader-issues#1411]
![주석 2019-11-19 100939](https://user-images.githubusercontent.com/57926067/69107742-c6ddbb80-0ab5-11ea-9797-4cbafaf00ecc.png)

이 상태로 다운이 안되고 있습니다.
버전은 2.7d구요, 다른 만화들은 다운이 잘 되는데 암살교실만 이렇습니다.

**Comment by KurtBestor** [comment]
참고해주세요: #1386

**Comment by aceburnett** [comment]
잘 됩니다. 감사합니다.
