### ISSUE TITLE
받아온 파일들 보는 형식 설정 어디있나요?

### ISSUE THREAD

**Issue by wlals67945** [KurtBestor/Hitomi-Downloader-issues#1413]
예전에 받아온 파일 형식을 

이미지 ㅡㅡ 제목
이미지 ㅡㅡ 제목
이미지 ㅡㅡ 제목 .... 형식말고

이미지 이미지 이미미
이미지 이미지 이미지
이미지 이미지 이미지....

형식이 있는걸로 기억하는데 찾아도 안보입니다..

사라진건지.. 있으면 어디있는지 알려주실수 있나요?
알려주시면 감사합니당.

**Comment by KurtBestor** [comment]
동봉된 `Readme.txt` 에 써진 대로 해당 기능은 사라졌어요. (그룹 기능과  충돌해서)

꼭 써야한다면 <kbd>Ctrl</kbd> + <kbd>Alt</kbd> + <kbd>C</kbd> 눌러서 콘솔창 열고 아래 내용 입력하고 <kbd>Enter</kbd> 눌러서 쓰실 수 있어요:
```
ui.viewIcon.setChecked(True);viewChanged() 
```

원래대로 되돌리려면 아래와 같이 입력해주세요:
```
ui.viewIcon.setChecked(False);viewChanged() 
```
