### ISSUE TITLE
파일 삭제 관련 문제

### ISSUE THREAD

**Issue by aperie** [KurtBestor/Hitomi-Downloader-issues#1415]
마나모아에서 A 만화의 1화, 2화, 3화..를 따로 다운로드 받았을 때 어떤 화라도 다운로드 목록 내에서 파일 삭제(Shift+Del)를 실행하면 상위 폴더(해당 만화의 전체 폴더)가 전부 다 삭제되는 문제가 있네요. 다른 화는 목록에는 그대로 남아있는데 실제 폴더가 없습니다.

과거에는 이렇게 작동하지 않았던 걸로 기억하는데 수정 가능할지 여쭤봅니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

과거에도 전체 폴더가 삭제됐어요.

**Comment by aperie** [comment]
제가 새 화수 다운받고 이전 화 목록에서 바로 삭제하는 식으로 관리했거든요. 그 때는 새로 받은 화수가 사라지거나 하는 경우는 없었던 걸로.. 최소 2.6 버전때까지도 그랬던 걸로 기억하는데 아니라고 말씀하시니 또 긴가민가 하네요..;;

여튼 잘 동작하네요. 감사합니다!
