### ISSUE TITLE
[픽시브/산카쿠 관련] 다운받는 작가의 이미지가 2000장까지 밖에 다운이 안됩니다.

### ISSUE THREAD

**Issue by Ru-dy** [KurtBestor/Hitomi-Downloader-issues#1418]
다운받는 작가의 이미지가 2000장 이상이면 2000장까지 밖에 다운이 되질 않습니다.
2000장 이상이라도 다운할 수 있게 해주시면 감사드리겠습니다.

**Comment by KurtBestor** [comment]
해당 작업 <kbd>마우스 우 클릭</kbd> - <kbd>정보... (I)</kbd> 눌러서 나온 내용 보여주세요.
