### ISSUE TITLE
스크립트 추가한 사이트는 클립보드에서 자동추가가 안되나요?

### ISSUE THREAD

**Issue by qwertgb99** [KurtBestor/Hitomi-Downloader-issues#1419]
스크립트도 어느 폴더같은곳에 두면 킬때마다 스크립트 추가 안해도 되는건 안되나요

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/689

스크립트 추가 후에 `클립보드에서 자동 추가` 껐다가 다시 적용하시면 돼요.
