### ISSUE TITLE
미리보기(섬네일) 관련

### ISSUE THREAD

**Issue by aperie** [KurtBestor/Hitomi-Downloader-issues#142]
다운로더, 검색기 공통으로 화면 아래쪽 목록의 섬네일이 화면 밑으로 내려가 잘려보여서 일일이 스크롤을 해서 봐야 하는 불편이 있습니다. 섬네일이 일괄적으로 '아래'로 표시되게 되어있는데 잘릴 경우 '위'로 표시되도록 수정 가능할까요?

![image](https://user-images.githubusercontent.com/40833764/42284838-ad542bbc-7fe8-11e8-8ef1-a5c2891aaa39.png)

**Comment by KurtBestor** [comment]
이미 그렇게 되게 만들어 놓았습니다. 화면 넘어가면 자동으로 보정됩니다. 적어도 제 환경에서는요.

혹시 더블모니터 쓰시나요?

**Comment by aperie** [comment]
맞습니다. 듀얼모니터 환경이에요. 말씀 보고서 단일 모니터 환경으로 전환하고 확인해보니 제대로 동작하네요.. 듀얼에서는 저렇게 작동하는 방법이 없는 건가요?

**Comment by aperie** [comment]
QtGui.QApplication.desktop().screen().rect() 

PyQt4.QtCore.QRect(0, 0, 3640, 1920)


number = QtGui.QApplication.desktop().screenNumber(QtGui.QCursor.pos()) 

number, QtGui.QApplication.desktop().screen(number).rect() 

(0, PyQt4.QtCore.QRect(0, 0, 3640, 1920))

**Comment by KurtBestor** [comment]
```
QtGui.QCursor.pos()
```
위 명령어를
1번 모니터에 마우스 포인터를 놓고 실행시키고, 2번 모니터에 마우스 포인터를 놓고 실행시켜서 나오는 내용 알려주세요.

모니터 해상도는 각각 3640 x 1920 맞나요?

**Comment by aperie** [comment]
1번 모니터

QtGui.QCursor.pos() 

PyQt4.QtCore.QPoint(1310, 1366)

2번 모니터

QtGui.QCursor.pos() 

PyQt4.QtCore.QPoint(2585, 1328)


해상도는 1번이 2560x1440, 2번이 1080x1920(세워서 씀) 입니다. 확장모드라 가로 해상도가 합쳐서 표기된 모양이네요.

**Comment by KurtBestor** [comment]
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

테스트 부탁드려요.

**Comment by aperie** [comment]
양쪽 모니터 다 잘 작동합니다. 감사해요!
