### ISSUE TITLE
소설가가되자 (id)에 소설코드 넣어주실수 있으신가요.

### ISSUE THREAD

**Issue by KANTDAIL** [KurtBestor/Hitomi-Downloader-issues#1420]
안녕하세요 히토미다운로더 잘 이용중인데요. 소설가가되자 사이트에서 소설을 다운로드하면 막상 소설코드가 안보여서 찾기가 어렵더군요.. 혹시 소설가가되자 (id)에 소설코드 넣어주실수 있으면 감사하겠습니다.

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/759
