### ISSUE TITLE
실행 후 3초 뒤 멈추면서 작동이 중지됩니다.

### ISSUE THREAD

**Issue by jkh2761** [KurtBestor/Hitomi-Downloader-issues#1421]
윈도우즈 10에서 버전 2.7c와 2.7d 모두에서 증상이 나타나며, 백신과 방화벽을 모두 끄고 파일을 다시 다운받아 실행하더라도 다음과 같은 메시지가 뜨며 종료됩니다.
![image](https://user-images.githubusercontent.com/58176838/69545094-6f1ee300-0fd4-11ea-921d-2b713cd48241.png)

**Comment by jkh2761** [comment]
관리자 권한으로 실행하여도 달라지는 것이 없습니다

**Comment by KurtBestor** [comment]
실행이 되는 가장 최신 버전이 뭔가요?: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases

**Comment by jkh2761** [comment]
더 이전 버전을 테스트해보지는 않았지만 오늘 확인한 바로는 재부팅하고 바로 프로그램을 실행시켰을 때는 정상 작동하나, 저장 및 종료를 눌러 종료하고 다시 실행을 시도할 경우에는 위처럼 실행이 중지되었습니다.

**Comment by KurtBestor** [comment]
실행파일 경로에 `실행파일명.ini` 파일이 있을텐데 그거 보내주시면 분석해볼게요.

**Comment by jkh2761** [comment]
감사합니다.

[hitomi_downloader_GUI.zip](https://github.com/KurtBestor/Hitomi-Downloader-issues/files/3893032/hitomi_downloader_GUI.zip)

**Comment by KurtBestor** [comment]
재현할 수가 없네요.

시작할 때 항상 타이틀바에 `offline` 뜨나요?

**Comment by jkh2761** [comment]
네 항상 offline 뜹니다.

**Comment by KurtBestor** [comment]
[여기](https://kurtbestor.github.io/res/version_check.txt) 들어가면 어떻게 뜨나요?

**Comment by jkh2761** [comment]
<!DOCTYPE html>
<html>
<h1>unicode, html</h1>
###hitomila###hitomi<br />
<br />
###version2.7d###version<br />
<br />
###linkhttps://github.com/KurtBestor/Hitomi-Downloader-issues/releases/latest###link<br />
###link_exporthttps://github.com/KurtBestor/Hitomi-Downloader-issues/releases/latest/download/hitomi_downloader_GUI.zip###link_export<br />
###feedbackhttps://github.com/KurtBestor/Hitomi-Downloader-issues/issues###feedback<br />
###donatehttp://bit.ly/2mRRKnF###donate<br />
###discordhttps://discord.gg/n64kr2g###discord<br />
###url_datahttps://kurtbestor.pythonanywhere.com/h_data###url_data<br />
<br />
###front_text<br />
<br />
<b><font color="red">※ v2.4 와 v2.5 에서 [자동 업데이트]가 동작하지 않습니다.<br />
[수동 업데이트] 해주세요.</font></b>###front_text<br />
<br />
###front_text_new###front_text_new<br />
<br />
###text<br />
<b>2.7d</b><br />
<br />
[버그 해결]<br />
<br />
- 작가명 복사 안 되는 문제 해결 （#1308, #1348）<br />
<br />
- 겔부루 "+" 들어간 태그 다운로드 안 되는 문제 해결<br />
<br />
- 픽시브 로그인 안 되는 문제 해결 （#1322, #1332）<br />
<br />
- 폰허브 프리미엄 다운로드 안 되는 문제 해결 （#1296, #1335）<br />
<br />
- Bilibili 일부 다운로드 안 되는 문제 해결 （#1167, #1343）<br />
<br />
- 검색기에서 미리보기 안 보이는 문제 해결 （#1345）<br />
<br />
- 히토미 애니 다운로드 안 되는 문제 해결<br />
<br />
- #1355<br />
<br />
- 기타 자잘한 것들<br />
<br />
<br />
[변경/추가된 기능]<br />
<br />
- "다시 시작" 하면 맨 위로 올리지 않고 제자리에 두도록 수정<br />
<br />
- 그룹 기능 （#286, #1313）<br />
&nbsp;&nbsp;&nbsp;&nbsp;작업 - 새 그룹 만들기<br />
<br />
- 그룹 안의 모든 작업 다시 시작 （#1336）<br />
<br />
- 작업 목록 아이콘 보기 모드 제거<br />
<br />
- 기타 자잘한 것들<br />
###text<br />
<br />
@ 2019.10.31</p>
</html>

이렇게 뜹니다

**Comment by KurtBestor** [comment]
[여기](http://bit.ly/HitomiDownloader2) 들어가면 어떻게 뜨나요?

VPN 같은 거 쓰시나요?

**Comment by jkh2761** [comment]
<!DOCTYPE html>
<html>
<h1>unicode, html</h1>
###hitomila###hitomi<br />
<br />
###version2.7d###version<br />
<br />
###linkhttps://github.com/KurtBestor/Hitomi-Downloader-issues/releases/latest###link<br />
###link_exporthttps://github.com/KurtBestor/Hitomi-Downloader-issues/releases/latest/download/hitomi_downloader_GUI.zip###link_export<br />
###feedbackhttps://github.com/KurtBestor/Hitomi-Downloader-issues/issues###feedback<br />
###donatehttp://bit.ly/2mRRKnF###donate<br />
###discordhttps://discord.gg/n64kr2g###discord<br />
###url_datahttps://kurtbestor.pythonanywhere.com/h_data###url_data<br />
<br />
###front_text<br />
<br />
<b><font color="red">※ v2.4 와 v2.5 에서 [자동 업데이트]가 동작하지 않습니다.<br />
[수동 업데이트] 해주세요.</font></b>###front_text<br />
<br />
###front_text_new###front_text_new<br />
<br />
###text<br />
<b>2.7d</b><br />
<br />
[버그 해결]<br />
<br />
- 작가명 복사 안 되는 문제 해결 （#1308, #1348）<br />
<br />
- 겔부루 "+" 들어간 태그 다운로드 안 되는 문제 해결<br />
<br />
- 픽시브 로그인 안 되는 문제 해결 （#1322, #1332）<br />
<br />
- 폰허브 프리미엄 다운로드 안 되는 문제 해결 （#1296, #1335）<br />
<br />
- Bilibili 일부 다운로드 안 되는 문제 해결 （#1167, #1343）<br />
<br />
- 검색기에서 미리보기 안 보이는 문제 해결 （#1345）<br />
<br />
- 히토미 애니 다운로드 안 되는 문제 해결<br />
<br />
- #1355<br />
<br />
- 기타 자잘한 것들<br />
<br />
<br />
[변경/추가된 기능]<br />
<br />
- "다시 시작" 하면 맨 위로 올리지 않고 제자리에 두도록 수정<br />
<br />
- 그룹 기능 （#286, #1313）<br />
&nbsp;&nbsp;&nbsp;&nbsp;작업 - 새 그룹 만들기<br />
<br />
- 그룹 안의 모든 작업 다시 시작 （#1336）<br />
<br />
- 작업 목록 아이콘 보기 모드 제거<br />
<br />
- 기타 자잘한 것들<br />
###text<br />
<br />
@ 2019.10.31</p>
</html>

이렇게 뜹니다
VPN은 추가로 쓰지 않고 있고, 컴퓨터를 재부팅하면 정상작동하고 있으니 혹 번거로우시거나 다른 오류 발생자가 없다면 그냥 두셔도 좋을 것 같...은...
