### ISSUE TITLE
중복 이미지 찾기 버그 

### ISSUE THREAD

**Issue by kenasis428** [KurtBestor/Hitomi-Downloader-issues#1422]
중복 이미지 찾기 중에 발견한 버그가 있어서 알려드립니다 .

중복 이미지 찾기 중에 폴더를 추가해서 이미지를 찾는데 

맨 위에 있는 폴더 3개 까지만 검색이 되고 그 4번쨰부터는 검색이 안뜨더군요.

A-폴더
B-폴더
C-폴더
D-폴더
E-폴더
F-폴더

이렇게 폴더를 정하고 검색을한다고 하면은 

맨위에 A,B,C 폴더속 중복 이미지만 검색이되고 

그 이후의 D,E,F 폴더는 검색이 안 뜹니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by kenasis428** [comment]
순서가 좀 뒤죽박죽 결과 나오지만 . 전부 나오네요 .
