### ISSUE TITLE
luscious의 자료들을 다운받으려는데 다운로드가 안되네요

### ISSUE THREAD

**Issue by okmark045** [KurtBestor/Hitomi-Downloader-issues#1423]
![캡처](https://user-images.githubusercontent.com/58194281/69586646-8f778d80-1026-11ea-9227-7944889d0a73.PNG)
이렇게 뜨면서 다운로드가 안되네요

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by okmark045** [comment]
잘 됩니다 감사합니다
