### ISSUE TITLE
마나모아 구글드라이브 이미지 일부 파싱버그

### ISSUE THREAD

**Issue by whatohyou** [KurtBestor/Hitomi-Downloader-issues#1427]
예) https://manamoa18.net/bbs/board.php?bo_table=manga&wr_id=26029
쟈히님은 굴하지 않아 22화.
웹페이지 소스코드를 보면,
var img_list1 = ["https:\/\/drive.google.com\/uc?export=view&id=1W2AjO28tFFnCoGts0DtaqdVxi0zgmCQl","https:\/\/drive.google.com\/uc?export=view&id=1UExuYqd_IqT7ofxaa5YnEAjIw3B4syFg","https:\/\/drive.google.com\/uc?export=view&id=18ptOfJXBKD6-XLF-9hVn_bwZv7gVG35n","https:\/\/drive.google.com\/uc?export=view&id=18cfK0vlyWUltoJkF_OomqZNIZrKx81g-","https:\/\/drive.google.com\/uc?export=view&id=1OqVhRKRf9K-Bde54ZG5fW5EUaKyhQlQv","https:\/\/drive.google.com\/uc?export=view&id=1IBOgdJDgHhVEhB-lMrYPgInd9VtILrMd","https:\/\/drive.google.com\/uc?export=view&id=1g-J0abcClTbXcYDYf4E6idPUG4ZTdmlr","https:\/\/drive.google.com\/uc?export=view&id=10eyREajXfbctVgwM1zC74Wpq31YFKcjR","https:\/\/drive.google.com\/uc?export=view&id=1xdiQjiJPWN-rJYeaJqu_I8p3G5RX4vew","https:\/\/drive.google.com\/uc?export=view&id=1boivodAn0dFCQ5LFi8X7fl3Q-PuQ4P6S","https:\/\/drive.google.com\/uc?export=view&id=1xdPox3MxPld1FdNZkdKQwnIC_w8Cg88O","https:\/\/drive.google.com\/uc?export=view&id=1mg-I__5-j9RJihC6o0KmjozkMg8yg64G","https:\/\/drive.google.com\/uc?export=view&id=1YE5OcDRTRt0bGmVqrjtDPemR6RKtjoX8","https:\/\/drive.google.com\/uc?export=view&id=1UZinaU9WnyIre1bHksaJ-sbbP8myJ-_u","https:\/\/drive.google.com\/uc?export=view&id=11eAsB4SQ-thbjVK2D5PfpgMjiOUkB5l7","https:\/\/drive.google.com\/uc?export=view&id=1bNxdsL54zbzHVgz60vvTUTtArGk7LoLD","https:\/\/drive.google.com\/uc?export=view&id=1wFgawvh_555npv1g2rnvMmY-hkdanYaX","https:\/\/drive.google.com\/uc?export=view&id=17jeBwa1UzJwxuJk0EwlgDE2mazjGjO0O"];

라고 링크가 잘 나와있는데, 히토미 다운로더는 이 링크를 제대로 파싱하지 못하는지, 18개의 이미지가 있다는 것은 아는데 다운로드에 실패합니다.

직접 파이썬 소스코드를 고치고 싶어도 소스가 공개되지 않아서 불가능한데 이런 식으로 파싱 문제가 발생했을 때에 스크립트로 해결하는 방법은 없나요?

**Comment by whatohyou** [comment]
아래 이슈에 언급된 테스트버전으로 해보니 잘 다운됩니다. regex파싱 문제라면 그걸 유저가 각자 수정할 수 있게 세팅파일을 만들어서 파싱옵션을 추가할 수 있게 해두는 방법은 없을까요? regex.txt->set1=[site:abc.com],[regex:""@"document.location='(https:\/\/.*?.org\/get\/.*.?.*?)';"] 뭐 이런식으로 세팅을 추가해서 기존 regex세팅을 대체할 수 있게요.

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/1386

파싱 문제는 아니예요.
