### ISSUE TITLE
픽시브 태그 다운로드가 안되네요.

### ISSUE THREAD

**Issue by 8519city** [KurtBestor/Hitomi-Downloader-issues#1429]
작가 다운로드는 되는데 태그 다운로드가 안됩니다.

**Comment by KurtBestor** [comment]
해당 작업 <kbd>마우스 우 클릭</kbd> - <kbd>정보... (I)</kbd> 눌러서 나온 내용 보여주세요.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview
