### ISSUE TITLE
업데이트후 폴더 지정문제

### ISSUE THREAD

**Issue by tipytipytipy** [KurtBestor/Hitomi-Downloader-issues#143]
아티스트/시리즈/타이틀 순으로 폴더로 지정해서 다운로드했는데,
업데이트 이후부터 그냥 위에 경로가 풀로 폴더로 지정됩니다
A라는 작가의 B작품 동인지 C라는 작품이 있다면
예전엔 A안에B안에 C라는 폴더로 저장이 되었는데
업데이트후 A/B/C라는 폴더로 저장이 됩니다
왜이럴까요....?

**Comment by KurtBestor** [comment]
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

테스트 부탁드려요.

**Comment by tipytipytipy** [comment]
이상하게 집피시로는 테스트버젼은 안받아져서 다른 피시로 해봤는데 잘 되는것같네요!
