### ISSUE TITLE
Pixiv 다운이 12~14개 진행되고 나서 멈춥니다

### ISSUE THREAD

**Issue by momokoro1** [KurtBestor/Hitomi-Downloader-issues#1434]
작가 등록을 2-300 이상 해놓고 한 번에 진행을 누르면 12-14정도 진행을 하다 invalid로 작업이 완료됩니다. 며칠 전부터 갑자기 이런 증상이 나타났는데 이유가 뭘까요? 
조금 뒤 시도하면 다시 12~14 작업 다운 진행이 이루어진 뒤 같은 현상이 반복됩니다

**Comment by KurtBestor** [comment]
`Invalid` 뜨는 작업 <kbd>마우스 우 클릭</kbd> - <kbd>정보... (I)</kbd> 눌러서 나온 내용 보여주세요.

**Comment by momokoro1** [comment]
Invalid: [pixiv] https://www.pixiv.net / member_illust.php?id=573302

version: 2.7d
platform: Windows-10-10.0.18362
order: 315
group: False
gal_num: https://www.pixiv.net/member_illust.php?id=573302
dir: 
zip: 
type: pixiv
artist: None
url: https://www.pixiv.net/member_illust.php?id=573302
valid: False
done: True
range: ~4
range_p: None
single: False
time: 1575236712.37 (Dec 2)
tags: []
goodbyedpi: False
lock: False
color: invalid
paused: False


[Gallery]
None


[File Names]



[URLs]



[Messages]
PIXIV_TYPE: user
Type: all
info: None
'JsonDict' object has no attribute 'user'
stop
Traceback (most recent call last):
File "utils", line 765, in start
File "utils", line 812, in start_
File "pixiv_downloader", line 174, in read
File "pixiv_downloader", line 273, in get_name
File "FUCK(4)\utils", line 24, in __getattr__
AttributeError: 'JsonDict' object has no attribute 'user'

Invalid: fail=True
EOT: https://www.pixiv.net/member_illust.php?id=573302

**Comment by momokoro1** [comment]
![캡처111111](https://user-images.githubusercontent.com/44127091/69921139-0901f680-14d3-11ea-9c51-928b048ec36e.PNG)

위처럼 진행되다 멈추더군요. 예전에는 100개 넘어가서 저런 식으로 잠시 멈췄었는데, 요 며칠 전부터는 딱 저정도 진행 이루어진 뒤부터 멈춰버리더라고요

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by momokoro1** [comment]
작업 진행 개수는 변하지 않았지만 Invalid로 작업이 변환되지 않고 진행이 되는 거 같습니다
14개 완료되고 멈췄다가 다시 14개 순으로 진행되네요
