### ISSUE TITLE
soundcloud 원본 파일로 받는 방법은 없나요?

### ISSUE THREAD

**Issue by dlehdrjs0606** [KurtBestor/Hitomi-Downloader-issues#1436]
soundcloud 받을 때 항상 mp3로 변환하는 거 같은데 flac이나 wav 원본 파일로 받는 기능이 있으면 좋겠습니다~!!!

**Comment by KurtBestor** [comment]
원본 파일이 MP3 파일이에요. 변환하는 것처럼 보이는 건 앨범아트 넣기 때문이에요. `옵션` - `설정` - `고급 설정` - `음악 파일에 앨범아트 삽입` 참고해주세요.

**Comment by dlehdrjs0606** [comment]
그렇군요 감사합니다!
