### ISSUE TITLE
e-hentai에서 다운이 안됩니다

### ISSUE THREAD

**Issue by pink0258** [KurtBestor/Hitomi-Downloader-issues#1437]
![안됩니다](https://user-images.githubusercontent.com/58359066/69899020-02289600-13a4-11ea-8d83-922eafc74b0b.PNG)

**Comment by pink0258** [comment]
저기서 더이상 진행이 안됩니다

**Comment by KurtBestor** [comment]
해당 작업 <kbd>마우스 우 클릭</kbd> - <kbd>정보... (I)</kbd> 눌러서 나온 내용 보여주세요.
