### ISSUE TITLE
픽시브 검색어 다운로드가 되지않습니다.

### ISSUE THREAD

**Issue by catarina38** [KurtBestor/Hitomi-Downloader-issues#1438]
작업정보 전문입니다.

[pixiv] Can not determine type: https://www.pixiv.net / tags / %E9%80%86%E3%83%AC%E3%82%A4%E3%83%97 / artworks

version: 2.7d
platform: Windows-10-10.0.17763
order: 0
group: False
gal_num: https://www.pixiv.net/tags/%E9%80%86%E3%83%AC%E3%82%A4%E3%83%97/artworks
dir: 
zip: 
type: pixiv
artist: None
url: https://www.pixiv.net/tags/%E9%80%86%E3%83%AC%E3%82%A4%E3%83%97/artworks
valid: False
done: True
range: None
range_p: None
single: False
time: 1575116159.96 (Nov 30)
tags: []
goodbyedpi: False
lock: False
color: invalid
paused: False

[Gallery]
None

[File Names]

[URLs]

[Messages]
stop
Invalid: fail=False
stop
EOT: https://www.pixiv.net/tags/%E9%80%86%E3%83%AC%E3%82%A4%E3%83%97/artworks

최근 픽시브 검색환경이 리뉴얼되며 검색시 주소도
tags/검색어/artworks 이런식으로 변경되었는데 그 영향이 아닐까 합니다.
예전 주소양식 
https://www.pixiv.net/search.php?s_mode=s_tag_full&word=(검색어)&order=date_d&mode=r18
에 검색어를 넣고 받아보니 정상 작동합니다.

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/1429
