### ISSUE TITLE
업데이트 후 기본데이터 다운로드 불가 증상

### ISSUE THREAD

**Issue by kikinet88** [KurtBestor/Hitomi-Downloader-issues#144]
현제 업데이트 후에
기본데이터를 받을수가 없습니다
아래와 같은 오류
![22222](https://user-images.githubusercontent.com/36730120/42353403-0d2c5a88-80fb-11e8-8b2f-d294f7b89253.jpg)

**Comment by KurtBestor** [comment]
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

테스트 부탁드려요.

**Comment by owowow23** [comment]
잘되네요.
