### ISSUE TITLE
주소가 S3로 된 이미지는 다운로드가 안되는 것 같습니다

### ISSUE THREAD

**Issue by BBQ-MAN** [KurtBestor/Hitomi-Downloader-issues#1440]
https://manamoa.net/bbs/page.php?hid=manga_detail&manga_id=9704

앞쪽의 10-2화부터는 잘 되는데 1~10화는 다운로드가 안됩니다

이미지 주소를 보니 1~10화는 S3가 붙어 있는데 AWS에 뭔가 차단 방법이 있는것 아닌가 싶습니다,

확인 부탁드려요~!

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/1386

**Comment by BBQ-MAN** [comment]
잘 됩니다! 감사합니다~
