### ISSUE TITLE
이제 밤토끼 안되는건가요?

### ISSUE THREAD

**Issue by kingcheee** [KurtBestor/Hitomi-Downloader-issues#1441]
전에 됐던걸로 알고 있는데 혹시 이제 밤토끼는 다운이 불가한지 묻습니다. 
그리고 가능하다면 어떻게 하고 
불가능 하면 사이트 건의? 같은걸로 하고 싶습니다.
언제나 잘 쓰고 있습니다. 감사합니다.

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/1228
