### ISSUE TITLE
사이트 추가 및 수정

### ISSUE THREAD

**Issue by superrogin** [KurtBestor/Hitomi-Downloader-issues#1445]
사이트 추가 제의  : http://nozomi.la/ 지원 부탁드립니다.

사이트 수정 제의 : weibo 주소 중 weibo.cn 으로 뜨는 경우 인식이 안됩니다.
cn 을 com으로 수동으로 수정해주면 다운이 되긴 합니다.
weibo.cn 주소를 자동으로 weibo.com으로 인식하면 좋을 것 같습니다.

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/331

테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by superrogin** [comment]
잘 됩니다, 감사합니다 :)
