### ISSUE TITLE
이제 아프리카는 안되는 건가요?

### ISSUE THREAD

**Issue by Mrfoolll** [KurtBestor/Hitomi-Downloader-issues#1446]
며칠 전부터 다운이 안되네요

**Comment by Mrfoolll** [comment]
Invalid: [afreeca] http://vod.afreecatv.com / PLAYER / STATION / 49396969

version: 2.7d
platform: Windows-8.1-6.3.9600
order: 0
group: False
gal_num: http://vod.afreecatv.com/PLAYER/STATION/49396969
dir: 
zip: 
type: afreeca
artist: None
url: http://vod.afreecatv.com/PLAYER/STATION/49396969
valid: False
done: False
range: None
range_p: None
single: False
time: 1575269402.94 (Dec 2)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False


[Gallery]
None


[File Names]



[URLs]



[Messages]
404
stop
Traceback (most recent call last):
File "utils", line 765, in start
File "utils", line 812, in start_
File "afreeca_downloader", line 43, in read
File "afreeca_downloader", line 94, in get_video
File "afreeca_downloader", line 102, in extract_m3u8
File "downloader", line 347, in read_html
Exception: 404

Invalid: fail=True

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by Mrfoolll** [comment]
다운로드 잘 되요. 감사합니다.
