### ISSUE TITLE
dc쪽 스크립트 / [artist] title (id) 에서 **(id)** 부분만 제거를 하고 싶습니다.

### ISSUE THREAD

**Issue by mita5549** [KurtBestor/Hitomi-Downloader-issues#1448]
dc 스크립트를 사용하면 다음과 같이 게시글이 저장 되는데, **(dc_comic_new2_890900)**  부분을 지우고 싶습니다. EX) **번역) 목요일의 플루트 - 코멧 편 (dc_comic_new2_890900)**
 
 폴더명 형식 / [artist] title (id)가 있기에 해당 칸에서 (id) 부분을 지워보았으나 결과물에는 변함이 없었고, 드롭다운 버튼을 눌러 아래 항목을 찾아봐도 (id) 부분은 모든 항목에 기재되어 있습니다.

**Comment by mita5549** [comment]
혹시 스크립트 수정을 통해서 간단히 해결할 수 있다면, 답변 부탁드립니다!
#coding: utf8
#title: DCInside 사이트 추가
#author: Kurt Bestor

import downloader
import re
from utils import urljoin, Downloader, Soup, LazyUrl
import json
from fucking_encoding import clean_title
from time import sleep
import os
from translator import tr_


class Image(object):
    def __init__(self, page, url, p):
        def f(page):
            return url
        self.url = LazyUrl(page, f, self)
        ext = os.path.splitext(url.split('?')[0])[1]
        if ext.lower()[1:] not in ['jpg', 'jpeg', 'bmp', 'png', 'gif', 'webm', 'webp']:
            ext = '.jpg'
        self.filename = u'{:04}{}'.format(p, ext)


def get_gal_id(url):
    if '/board/' in url:
        gal = re.findall('[?&]id=([0-9a-zA-Z_-]+)', url)[0]
        id = re.findall('[?&]no=([0-9]+)', url)[0]
    else:
        gal, id = url.split('dcinside.com/')[1].split('/')[:2]
        id = re.findall('[0-9]+', id)[0]
    return gal, id


@Downloader.register
class Downloader_dc(Downloader):
    type = 'dc'
    URLS = ['gall.dcinside.com']
    icon = 'https://kurtbestor.github.io/res/dc.png'
    _soup = None
    def init(self):
        self.url = self.url.replace('dc_', '').replace('&t=cv', '')
        if 'gall.dcinside.com' not in self.url:
            id = self.url.split('_')[-1]
            gal = self.url.replace('_'+id, '')
            self.url = 'http://gall.dcinside.com/board/view/?id={}&no={}'.format(gal, id)

    @property
    def id(self):
        gal, id = get_gal_id(self.url)
        return u'dc_{}_{}'.format(gal, id)

    @property
    def soup(self):
        if self._soup is None:
            self._soup = read_page(self.url, cw=self.customWidget)
        return self._soup

    @property
    def name(self):
        soup = self.soup
        title = soup.find('span', class_='title_subject').string
        return clean_title(u'{} ({})'.format(title, self.id))

    def read(self):
        self.title = u'읽는 중... {}'.format(self.name)

        imgs = get_imgs(self.url, self.soup)

        for img in imgs:
            self.urls.append(img.url)

        sleep(.5)
        self.title = self.name


def read_page(url, cw=None):
    print 'read_page', url
    url = url.replace('&t=cv', '')
    html = downloader.read_html(url)

    if len(html) < 2000 and 'location.replace(' in html:
        url_old = url
        url = re.findall('location.replace.+?["\'](.*?)["\']', html)[0]
        if url.startswith('/'):
            url = urljoin(url_old, url)
        if cw is not None:
            cw.print_(u'Redirect: {} --> {}'.format(url_old, url))
        html = downloader.read_html(url)

    soup = Soup(html)
    return soup


def get_imgs(url, soup=None):
    if soup is None:
        print 'soup is None'
        soup = read_page(url)

    imgs = []
    url_imgs = set()
    view = soup.find('div', {'class': 'writing_view_box'})
    p = 0
    for img in view.findAll('img'):
        url_img = img.attrs['src']
        if 'nstatic.dcinside' in url_img:
            continue
        if url_img in url_imgs:
            continue
        url_imgs.add(url_img)
        img = Image(url, url_img, p)
        imgs.append(img)
        p += 1

    return imgs


messageBox(u'{}: dc'.format(tr_(u'사이트를 추가했습니다')))

**Comment by KurtBestor** [comment]
스크립트에서 `clean_title(u'{} ({})'.format(title, self.id))` 부분을 `clean_title(title)` 로 수정하시면 돼요.

**Comment by mita5549** [comment]
@property
    def name(self):
        soup = self.soup
        title = soup.find('span', class_='title_subject').string
        return clean_title(title)

네임이라길래 혹시나 싶어서 구글 검색 하던 도중 알림이..!! 감사합니다!!!!
