### ISSUE TITLE
#1244 버그가 재발했습니다.

### ISSUE THREAD

**Issue by Dumbisted** [KurtBestor/Hitomi-Downloader-issues#1450]
#1244 

한동한 별 문제 없이 잠잠했는데 최근들어 다시 켜놓고 일정 시간이 지난 후 다운로드를 시도하면 몇몇 페이지가 Invalid로 전환되더군요. 아래는 로그입니다.

----

Invalid: [pixiv] https://www.pixiv.net / member_illust.php?id=169668

version: 2.7c
platform: Windows-10-10.0.18362
order: 342
group: False
gal_num: https://www.pixiv.net/member_illust.php?id=169668
dir: hitomi_downloaded_pixiv\今日ピン (pixiv_169668)
zip: 
type: pixiv
artist: 今日ピン
url: https://www.pixiv.net/member_illust.php?id=169668
valid: False
done: True
range: None
range_p: None
single: False
time: 1575301117.23 (Dec 3)
tags: []
goodbyedpi: True
lock: True
color: invalid
paused: False

[Gallery]
None

[File Names]

[URLs]

[Messages]
PIXIV_TYPE: user
Type: all
info: None
'JsonDict' object has no attribute 'user'
stop
Traceback (most recent call last):
File "utils", line 765, in start
File "utils", line 812, in start_
File "pixiv_downloader", line 174, in read
File "pixiv_downloader", line 273, in get_name
File "FUCK(4)\utils", line 24, in __getattr__
AttributeError: 'JsonDict' object has no attribute 'user'

Invalid: fail=True
EOT: https://www.pixiv.net/member_illust.php?id=169668

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by Dumbisted** [comment]
프로그램을 켜놓고 8시간이 지난 지금 정상작동 확인했습니다. 감사합니다!
