### ISSUE TITLE
baraag.net 을 추가해주실 수 있을까요?

### ISSUE THREAD

**Issue by bobinewg** [KurtBestor/Hitomi-Downloader-issues#1451]
필요할 때마다 잘 이용하고 있습니다. 유용한 프로그램을 만들어 주셔서 정말 감사합니다.
혹시 baraag.net 사이트를 추가해주실 수 있을지 검토해주신다면 정말 좋겠습니다.

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/1911
