### ISSUE TITLE
유튜브 목록으로 다운받을 경우 2000개 제한이 있나요?

### ISSUE THREAD

**Issue by unflac** [KurtBestor/Hitomi-Downloader-issues#1454]
재생 목록이나, 채널 전체로 다운로드 시도할 경우

몇 번 시도해도 계속 2000개에서 더 못 읽어 오는데, 원래 그런건가요?

제한 없애주실 수 있을까 싶어서 글 남겨 봅니다.

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/1178

<kbd>Ctrl</kbd> + <kbd>Alt</kbd> + <kbd>C</kbd> 눌러서 콘솔창 띄워서 다음 내용 입력하고 <kbd>Enter</kbd> 누르면 강제로 풀 수 있어요:
```
TOO_MANY = 9999
```

다만 메모리 부족으로 오류나서 강제 종료 될 수 있어서 권장하진 않아요. 가능하면 기존 작업 목록을 줄이거나 백업해놓고 지운 다음에 다운로드하세요.

**Comment by unflac** [comment]
잘되네요. 감사합니다^^
