### ISSUE TITLE
아이디어 제공 및 간단한 질문 드립니다.

### ISSUE THREAD

**Issue by chbk256** [KurtBestor/Hitomi-Downloader-issues#1458]
태그를 그림판이나 포토샵 같은데서 쓰는 팔레트 형식으로 커스텀 할 수 있게 하면 어떨까요?
일단 현재 존재하는 7개의 태그 외에도 더 만들어낼 수 있으니 색상과 태그 갯수의 제한이 사라져서 유용할 것 같습니다.

+ 질문이 있는데, Patreon, FANBOX, FANTIA 같은 후원 사이트들은 기술적으로 원본 이미지 다운로더를 만드는데는 무리가 있나요? 아무래도 유료 후원 사이트다 보니 관련해서 만들려면 좀 까다롭지 않을까 싶은 단순 호기심입니다.

**Comment by KurtBestor** [comment]
로그인이 필요한 경우는 대체로 까다로워요. 캡차를 띄우는 경우도 있고, 평소에 로그인하던 브라우저가 아니면 이메일/폰 인증을 요구하는 경우, 자바스크립트로 진짜 브라우저인지 체크하는 경우, 봇인 것 같은 행동을 하면 차단/로그아웃 시킨다던지 하는 경우 등 때문이에요.

**Comment by chbk256** [comment]
가만히 생각해보면 FANBOX 같은거야 그림을 열람할 수 있는 후원자 기준으로는 
픽시브랑 원리는 비슷할 것 같기는 하네요.

아무튼 로그인 필요한 사이트들도 지원하시는 거 보면 대단하십니다. ㅎㅎ

+

![1312](https://user-images.githubusercontent.com/42115261/70441575-fccff780-1ad7-11ea-9ea0-64ad6dfaf267.jpg)

대충 이런 팔레트 같은 걸 도입해서 태그의 색깔 종류를 늘리거나 커스텀 할 수 있게하면 위에 말씀드린 것 처럼 여러모로 유용할 것 같습니다. 이후 생각있으시면 부탁드립니다. ㅎㅎ
