### ISSUE TITLE
2.3c 업데이트 후 기본데이터 다운로드 불가 문제

### ISSUE THREAD

**Issue by fomafee** [KurtBestor/Hitomi-Downloader-issues#146]
2.3c 업데이트 직후, 기본데이터 다운로드 시, 
첨부한 하단 스크린샷 에러와 함께 다운로드 실패

https://cdn.discordapp.com/attachments/262439945145155589/464667108203036672/ScreenShot_20180706144055.png

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/144
