### ISSUE TITLE
제이마나에서는 개별 만화 다운로드가 지원되지 않습니까?

### ISSUE THREAD

**Issue by cancerogenic** [KurtBestor/Hitomi-Downloader-issues#1462]
전체 목록 다운로드는 됩니다만은, 개별 항목을 다운받으려고 하면 항상 목록 주소를 입력해주세요라고 메시지가 뜨면서 다운로드가 진행되지 않습니다. 원래 이런 건지요, 아니면 제가 잘못한 부분이 있는지요?

==========

목록 주소를 입력해주세요: https://jmana37.com / book / %ED%8C%A8%EB%9F%AC%EB%A0%90%20%ED%8C%8C%EB%9D%BC%EB%8B%A4%EC%9D%B4%EC%8A%A4 / 166522

version: 2.7d
platform: Windows-10-10.0.18362
order: 0
group: False
gal_num: https://jmana37.com/book/%ED%8C%A8%EB%9F%AC%EB%A0%90%20%ED%8C%8C%EB%9D%BC%EB%8B%A4%EC%9D%B4%EC%8A%A4/166522
dir: 
zip: 
type: jmana
artist: None
url: https://jmana37.com/book/%ED%8C%A8%EB%9F%AC%EB%A0%90%20%ED%8C%8C%EB%9D%BC%EB%8B%A4%EC%9D%B4%EC%8A%A4/166522
valid: False
done: True
range: None
range_p: None
single: False
time: 1575740169.72 (Dec 8)
tags: []
goodbyedpi: False
lock: False
color: invalid
paused: False

[Gallery]
None

[File Names]

[URLs]

[Messages]
stop
Invalid: fail=False
stop
EOT: https://jmana37.com/book/%ED%8C%A8%EB%9F%AC%EB%A0%90%20%ED%8C%8C%EB%9D%BC%EB%8B%A4%EC%9D%B4%EC%8A%A4/166522

**Comment by KurtBestor** [comment]
`도움말` - `사용법... (F1)` - `선택 화 다운로드` 참고해주세요.
