### ISSUE TITLE
https://www.deviantart.com/ 다운로드 갯수 0개 완료 

### ISSUE THREAD

**Issue by kenasis428** [KurtBestor/Hitomi-Downloader-issues#1463]
deviantart 이사이트에서 다운로드 할려고 하는데 

다운갯수 0개로 뜨네요 무슨 문제가 있나요 ?

https://www.deviantart.com/

1번.
-------------------------------
ShuraKRGT (deviant_shurakrgt)

version: 2.7d
platform: Windows-10-10.0.17763
order: 4
group: False
gal_num: https://www.deviantart.com/shurakrgt/gallery/all
dir: hitomi_downloaded_deviant\ShuraKRGT (deviant_shurakrgt)
zip: 
type: deviant
artist: None
url: https://shurakrgt.deviantart.com/
valid: True
done: True
range: None
range_p: None
single: False
time: 1575755143.68 (Dec 8)
tags: []
goodbyedpi: True
lock: False
color: done
paused: False

[Gallery]
None

[File Names]

[URLs]

[Messages]
Traceback (most recent call last):
File "utils", line 1202, in compress
File "zipfile", line 779, in __init__
IOError: [Errno 2] No such file or directory: u'D:\\hitomi_downloader_GUI_test\\hitomi_downloaded_deviant\\ShuraKRGT (deviant_shurakrgt).cbz'

Traceback (most recent call last):
File "utils", line 1231, in compress
WindowsError: [Error 3] : u'D:\\hitomi_downloader_GUI_test\\hitomi_downloaded_deviant\\ShuraKRGT (deviant_shurakrgt).cbz'

EOT: https://www.deviantart.com/shurakrgt/gallery/all

2번.
------------------------------------------------

miura-n315 (deviant_miura-n315)

version: 2.7d
platform: Windows-10-10.0.17763
order: 0
group: False
gal_num: https://www.deviantart.com/miura-n315/gallery/all
dir: hitomi_downloaded_deviant\miura-n315 (deviant_miura-n315)
zip: 
type: deviant
artist: None
url: https://miura-n315.deviantart.com/
valid: True
done: True
range: None
range_p: None
single: False
time: 1575755237.8 (Dec 8)
tags: []
goodbyedpi: True
lock: False
color: done
paused: False

[Gallery]
None

[File Names]

[URLs]

[Messages]
Traceback (most recent call last):
File "utils", line 1202, in compress
File "zipfile", line 779, in __init__
IOError: [Errno 2] No such file or directory: u'D:\\hitomi_downloader_GUI_test\\hitomi_downloaded_deviant\\miura-n315 (deviant_miura-n315).cbz'

Traceback (most recent call last):
File "utils", line 1231, in compress
WindowsError: [Error 3] : u'D:\\hitomi_downloader_GUI_test\\hitomi_downloaded_deviant\\miura-n315 (deviant_miura-n315).cbz'

EOT: https://www.deviantart.com/miura-n315/gallery/all

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by kenasis428** [comment]
잘 다운 됩니다.
