### ISSUE TITLE
히토미 다운로더 가끔가다 누락된 자료가 있는데

### ISSUE THREAD

**Issue by collagen12** [KurtBestor/Hitomi-Downloader-issues#1465]
기본데이터 다운로드 해봐도 그대로고 시간이 한참지나서 다시 검색해봐도 히토미 사이트에는 멀쩡하게 있는데 중간중간 누락되서 파싱하던데, 검색 타입에서 제외된건가 싶어서 전부 체크해봐도 안나오는것도 있고 이런건 왜 그런건지

예를들어 12/9일 8:17기준으로 한국어 목록 1페이지에 [Dowarukofu - Tenryuu-Chan O Kyankyan Iwasechau Hon | 텐류쨩을 꺄악꺄악 울게 만드는 책]가 3번째로 있는데 히토미 다운로더에선 이걸 빼고 넘어감. 이거말고도 1페이지에 누락된 자료 갯수만 4개가 더 있음

제목으로 검색해도 Dowarukofu 작가명으로 검색해도 안나옴

그리고 삭제된데이터도 완전하게 구할수없는것도 있음?

nakani - Mukashi wa Kakko Yokatta 2 같은건 히토미에 올라왔다가 삭제됬는데 삭제된데이터 최신으로 받아도 검색이 아예 안됨

**Comment by KurtBestor** [comment]
고쳤어요. 데이터 다시 다운로드 해주세요.
