### ISSUE TITLE
한글 폰트가 깨집니다

### ISSUE THREAD

**Issue by Quiple** [KurtBestor/Hitomi-Downloader-issues#147]
![-1](https://user-images.githubusercontent.com/11014257/42379462-ad4f0a46-8165-11e8-9f73-b768355934bd.jpg)
이처럼 프로그램 내 한글이 정상적으로 표시되지 않아 어쩔 수 없이 영어로 쓰고 있습니다ㅠㅠ
제가 윈도우 폰트 우선순위를 시고UI-메이료UI-맑은고딕 순으로 바꿔서 쓰고 있는 탓인 듯한데
다른 프로그램은 한글이 잘만 표시된다는 말이죠...

**Comment by KurtBestor** [comment]
일단 Options - Preferences - Language 를 English로 바꿔서 써주세요.

나중에 해결되면 알려드리겠습니다ㅠㅠ

**Comment by KurtBestor** [comment]
Ctrl + Alt + C 눌러서 콘솔 띄우시고, 다음과 같이 입력하고 Enter 눌러보세요:
```
app.setFont(QtGui.QFont())
```

어떻게 되나요?

**Comment by Quiple** [comment]
![image](https://user-images.githubusercontent.com/11014257/42407968-919e9bcc-8200-11e8-9016-80b394187c9f.png)
Ctrl + Alt + C가 안 돼서 그냥 Shift + 우클릭으로 해봤는데 이러네요.

**Comment by Quiple** [comment]
![image](https://user-images.githubusercontent.com/11014257/42408001-2bac4430-8201-11e8-9b09-5adb272e80e5.png)
이렇습니다.

**Comment by KurtBestor** [comment]
콘솔에 입력한 것 때문에 그럴 수도 있어요.
다시 껐다 켜보시고 한글 제대로 나오는지 확인 해보실래요?

**Comment by Quiple** [comment]
아 그런 거 같네요
다시 켜니 원래대로 돌아옴

**Comment by KurtBestor** [comment]
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

테스트 부탁드려요.

**Comment by Quiple** [comment]
넵 잘 나오네요 감사함닷!
