### ISSUE TITLE
동시 다운로드 갯수 설정이 있었으면 합니다

### ISSUE THREAD

**Issue by q2343454** [KurtBestor/Hitomi-Downloader-issues#1470]
1.히토미는 4개를 한번에 받고
폰허브는 동영상 16개를 한번에 받고 있습니다;;

2.컴퓨터 리소스를 많이 쓰거나 좀 구린 컴퓨터면
솔직히 한번에 받는 갯수 조절 기능이 유용한데
히토미 다운로더는 그런 기능이 없어서 많이 안타깝습니다

특히 폰허브는 한번에 동영상을 16개씩 읽고 다운받고 하다보니까
컴퓨터에 많이 무리가 가는 듯 합니다
16는 정말 너무 많습니다;;

3.제작자님께서 구린 컴퓨터나 리소스 많이 쓰는 작업 등등
여러가지 상황을 고려해 주셔서

부디 동시 다운로드 갯수 설정이 가능하게 해 주셨으면
정말 감사하겠습니다 ㅠㅠ

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

앞으로 나올 버전에선 한 사이트 당 동시 다운로드가 4개를 초과하지 않게 조절될 거예요.

**Comment by q2343454** [comment]
테스트를 했고
폰허브 사이트에서 기존 16개 동시 읽기+다운에서
4개 읽기+다운으로 확인 되었습니다

그런데 동시 다운로드 갯수 설정이란 말씀은
사용자가 원하는 대로 한번에 받는 파일 갯수를 
1개부터 다수까지 원하는대로 설정 가능한가 여쭤 본 것이었습니다

많은 용량의 파일을 받거나 
컴퓨터 리소스를 다른 곳에 많이 쓰는 중이거나
그러한 여러가지 경우에 

사용자가 임의로 파일을 1개만 받을 것인지 다수를 받을 것인지
결정 가능하다면 유용할거 같아서 그렇습니다

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

![image](https://user-images.githubusercontent.com/14768120/70770346-5f631500-1db0-11ea-905d-fbfa2d2f84bd.png)

**Comment by q2343454** [comment]
테스트 결과 최대 동시 작업 기능은 정상적으로 문제 없이 작동하는 듯 합니다
다운로드 받는 도중에 변경해도 바로바로 적용이 되는 듯 합니다

제작자님의 신속 정확한 움직임에 감사드립니다;;
