### ISSUE TITLE
중복 이미지 찾기 문제?

### ISSUE THREAD

**Issue by kenasis428** [KurtBestor/Hitomi-Downloader-issues#1471]
중복이미지 항상 하던대로 폴더 설정해서 찾고 있는데 

분명 160만장 이상 떠야하는데 

검색되는건 11만장 정도 뜨네요 ?

이건 무슨 문제인가요 ?

**Comment by KurtBestor** [comment]
글쎄요, 포함되지 않는 파일들의 경로나 내용에 공통점이 있나요?

**Comment by kenasis428** [comment]
최근에 받은 프로그램
![최근꺼](https://user-images.githubusercontent.com/53850082/70843116-520d5f80-1e70-11ea-9832-d9d14a529779.png)

예전에 받은 프로그램
![예전거](https://user-images.githubusercontent.com/53850082/70843119-605b7b80-1e70-11ea-9476-ab365cf9d076.png)

뭔 문제인지 저도잘 ;;; 항상 똑같은 위치 똑같은 경로 똑같은 폴더수 순서 똑같은데 이러네요 .

위의 사진은 방금 두개 돌리고 나온 결과입니다.

**Comment by KurtBestor** [comment]
서브폴더가 최대 몇 깊이 까지 있나요?

**Comment by kenasis428** [comment]
가장 깊은 폴더 D드라이브 기준 7폴더입니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

최대 8 깊이 까지만 탐색해요.

**Comment by kenasis428** [comment]
3만장 추가적으로 더 발견하네요 ㅋㅋㅋㅋ  188만장 ...
