### ISSUE TITLE
픽시브 움짤 변환이 이루어지지 않습니다.

### ISSUE THREAD

**Issue by azzxxa** [KurtBestor/Hitomi-Downloader-issues#1475]
갑자기 픽시브 움짤 변환이 몇 시간이 걸려도 이루어지지 않습니다.

GIF 로 설정해놓은 상태이며 압축파일은 만들어지지만 GIF는 만들어지지 않고 무한 변환중입니다.

**Comment by KurtBestor** [comment]
지금도 안 되나요?

**Comment by azzxxa** [comment]
네 원래는 바로 됐었는데 지금도 안 됩니다.

[Messages]
PIXIV_TYPE: user
Type: all
info: None
Enigi09 (pixiv_8829494)
tags: []
tags_ex: []
read ugoira... 65229405
read ugoira... 57209234
read ugoira... 57136404
read ugoira... 55328264
read ugoira... 55249142
convert ugoira: hitomi_downloaded_pixiv\Enigi09 (pixiv_8829494)\65229405_p0 動かしてみた.zip --> hitomi_downloaded_pixiv\Enigi09 (pixiv_8829494)\65229405_p0 動かしてみた.gif
Duration: [100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100]
Convert: hitomi_downloaded_pixiv\Enigi09 (pixiv_8829494)\65229405_p0 動かしてみた.zip

**Comment by KurtBestor** [comment]
어떤 ISP 쓰시나요?

**Comment by azzxxa** [comment]
SK 입니다. 정확히는 모르겟네요 ㅠㅠ 다른건 다 잘되는데 움짤 변환만 안 됩니다.

**Comment by azzxxa** [comment]
어제 인터넷 최적화하고 오늘 했더니 갑자기 잘 됩니다. 감사합니다.
