### ISSUE TITLE
포르노허브 동영상 파일 이름이 같으면 다운이 안 됩니다. 

### ISSUE THREAD

**Issue by goodhubuser** [KurtBestor/Hitomi-Downloader-issues#1478]
https://www.pornhub.com/view_video.php?viewkey=ph5d1a32505baab

https://www.pornhub.com/view_video.php?viewkey=ph5b08618a46d2d

 위 2개 동영상은 서로 다른 동영상입니다.

근데 파일 이름이 같다는 이유로 다운로드가 안 됩니다. 

 파일 이름 생성할 때, 포르노허브 주소를 추가한다던가 해야할 듯 합니다.

**Comment by KurtBestor** [comment]
참고해주세요: #233

**Comment by goodhubuser** [comment]
> 참고해주세요: #233

다운받아서 테스트해봤더니 여전히 다운로드 안 됩니다...   애초에 파일명 형식을 설정에서 바꿔도 단순히 타이틀만 나옵니다.

**Comment by KurtBestor** [comment]
해당 작업 <kbd>마우스 우 클릭</kbd> - <kbd>정보... (I)</kbd> 눌러서 나온 내용 보여주세요.

**Comment by goodhubuser** [comment]
> 해당 작업 마우스 우 클릭 - 정보... (I) 눌러서 나온 내용 보여주세요.

frogstyle

version: 2.7d
platform: Windows-10-10.0.18362
order: 0
group: False
gal_num: https://www.pornhub.com/view_video.php?viewkey=ph5a8e9207100bc
dir: hitomi_downloaded_pornhub
zip: 
type: pornhub
artist: None
url: https://www.pornhub.com/view_video.php?viewkey=ph5a8e9207100bc
valid: True
done: True
range: None
range_p: None
single: True
time: 1576727844.43 (Dec 19)
tags: []
goodbyedpi: True
lock: False
color: done
paused: False


[Gallery]
None


[File Names]
[0001] hitomi_downloaded_pornhub\frogstyle.mp4


[URLs]

**Comment by goodhubuser** [comment]
> 해당 작업 마우스 우 클릭 - 정보... (I) 눌러서 나온 내용 보여주세요.

지금보니, test 파일을 받아서 압축풀고 실행해도 2.7d 버전으로 실행되네요.

컴퓨터 재부팅하고 다시 받아서 새로운 폴더에서 다시 압축풀어도 여전히 2.7d 버전으로 실행됩니다.

**Comment by KurtBestor** [comment]
`파일명 형식` 어떻게 바꿨는지 스크린샷 찍어서 보여주세요.

**Comment by goodhubuser** [comment]
> 파일명 형식 어떻게 바꿨는지 스크린샷 찍어서 보여주세요.

https://imgur.com/a/JrbfmkH

**Comment by KurtBestor** [comment]
`폴더명 형식` 말고 `파일명 형식` 바꿔주세요.
