### ISSUE TITLE
히토미 저장시 아티스트명 관련

### ISSUE THREAD

**Issue by aperie** [KurtBestor/Hitomi-Downloader-issues#148]
해당 작품의 아티스트가 2인 이상일 경우 [누구, Etc]로 저장되는데, 딱 2인일 경우 아티스트명을 [누구, 누구누구] 처럼 둘 다 표기되도록 하는 옵션을 지정 가능할까요? 동인지 같은 경우 2인 합동지가 제법 많아서 저렇게 저장되면 관리하기 편할 것 같아요.

그룹명의 경우 둘 이상이더라도 맨 앞의 하나만 표기되도록 되어있는데(ex. 756604) 이것도 수정 가능한지 궁금하구요..

**Comment by KurtBestor** [comment]
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

테스트 부탁드려요.
이제 2명까지 표기해요.

**Comment by aperie** [comment]
아티스트, 그룹명까지 잘 작동하네요. 감사합니다!

**Comment by aperie** [comment]
그런데 아티스트가 셋 이상일 경우 [누구, 누구누구, Etc]로 표기되는데 개인적으로 이 경우엔 그냥 기존처럼 [누구, Etc]로 표기하는게 낫지 않을까 싶어요. 셋 이상일 때 둘까지 표기하는건 큰 의미가 없다고 생각해서요. 아니면 몇 명 까지 표시할지 옵션으로 지정 가능하게 한다거나.. 번거롭게 해 드려 죄송합니다.

**Comment by KurtBestor** [comment]
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

테스트 부탁드려요.

**Comment by aperie** [comment]
아주 잘 됩니다. 감사합니다!
