### ISSUE TITLE
현재 다운 잘되시나요??

### ISSUE THREAD

**Issue by wpfhfpr** [KurtBestor/Hitomi-Downloader-issues#1480]
다운이 안되서 상황 파악이 안되네요. 익헨이랑 링크는 들어가지는데말이죠..

**Comment by KurtBestor** [comment]
해당 작업 <kbd>마우스 우 클릭</kbd> - <kbd>정보... (I)</kbd> 눌러서 나온 내용 보여주세요.

**Comment by wpfhfpr** [comment]
왜 답글이 왔는지 아무것도 안떴을까요;; 죄송해요 이제 봤습니다. 제가볼때는 검색과 확인해본 결과 일정량 초과해서 그런거같네요.음..예전엔 안그랬는데 운이없었나..그런 경우도 있나요?

**Comment by KurtBestor** [comment]
다운로드 목록에 작업이 몇 개 있나요?

**Comment by wpfhfpr** [comment]
작업은 보통 100개~300개정도 추가하는데 동시 다운로드 수는 4개고 항시는 아니고 2~3일에 한번 받는 것 같습니다. 어느때는 많이 받아도 문제없다가 위처럼 멈춘 경우가 있는데 사이트문제인지는 모르겠네요
