### ISSUE TITLE
flickr 로그인 문의

### ISSUE THREAD

**Issue by karl5432** [KurtBestor/Hitomi-Downloader-issues#1483]
항상 수고가 많으십니다.
flickr도 다운로드 지원이 된다는 사실을 알고, 주소를 입력해 다운로드를 시도하였으나
로그인이 필요하다는 알림창이 뜨고 다운로드가 대기중인채로 멈추었습니다.

설정에 들어가 flickr항목을 찾아 정보를 입력하려 하였지만 별다른 항목을 찾지 못하였는데
어떻게 로그인을 하여야 다운로드를 받을 수 있을까요?

브라우저로 접속해 api인증을 받으려 했지만 API키를 인식할 수 없다는 메세지도 출력받았습니다.

![image](https://user-images.githubusercontent.com/57511621/70872657-10ee8a00-1fed-11ea-80df-4b18f3ed59cb.png)

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by wkd284** [comment]
> 
> 
> 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

잘됩니다 감사합니다.
