### ISSUE TITLE
임시폴더 설정 외

### ISSUE THREAD

**Issue by Laser-Cho** [KurtBestor/Hitomi-Downloader-issues#1486]
NAS 의 네트워크 드라이브에 올려놓고 쓰는데, 임시파일 다운로드 시 같은 주소를 사용합니다. 
임시파일은 램디스크 같은 곳으로 설정해 두고 나스에 엑세스 하는 횟수를 최대한 줄이면 좀 더 안정적으로 쓸 수 있을 것 같습니다.

다운로드 이후 폴더열기 버튼을 처음 누를 때는 정상적으로 폴더가 열리지만, 두번째 부터는 문서 폴더만 열리고 마는 문제가 있습니다.

**Comment by KurtBestor** [comment]
이해가 안 되는데 좀 더 자세히 설명해주실 수 있나요?
