### ISSUE TITLE
저번주까지 잘 다운 되던 jmana 다운이 안되네요.

### ISSUE THREAD

**Issue by niaong** [KurtBestor/Hitomi-Downloader-issues#1487]
저만 그런건지 모르겠습니다.

그냥 우연히 그러는지는 모르겠지만 익헨만 다운 받으면 Jmana 주소를 찾지 못해요.

https://jmana.net/book/영웅의%20딸로%20다시%20태어난%20영웅은%20다시%20영웅을%20목표로%20한다

https://jmana.net/book/%EC%98%81%EC%9B%85%EC%9D%98%20%EB%94%B8%EB%A1%9C%20%EB%8B%A4%EC%8B%9C%20%ED%83%9C%EC%96%B4%EB%82%9C%20%EC%98%81%EC%9B%85%EC%9D%80%20%EB%8B%A4%EC%8B%9C%20%EC%98%81%EC%9B%85%EC%9D%84%20%EB%AA%A9%ED%91%9C%EB%A1%9C%20%ED%95%9C%EB%8B%A4

이렇게 두 곳 검색해도 주소를 찾지 못 합니다고 뜨네요.

다른 곳은 다 다운이 잘되네요. Jmana만 그렇습니다.

------------------------------------------------------------------------------------------------
정보
------------------------------------------------------------------------------------------------
Can not determine type: https://jmana.net / book / 영웅의%20딸로%20다시%20태어난%20영웅은%20다시%20영웅을%20목표로%20한다

version: 2.7d
platform: Windows-7-6.1.7601-SP1
order: 0
group: False
gal_num: https://jmana.net/book/영웅의%20딸로%20다시%20태어난%20영웅은%20다시%20영웅을%20목표로%20한다
dir: 
zip: 
type: 
artist: None
url: https://jmana.net/book/영웅의%20딸로%20다시%20태어난%20영웅은%20다시%20영웅을%20목표로%20한다
valid: False
done: True
range: None
range_p: None
single: True
time: 1576495683.52 (Dec 16)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False

[Gallery]
None

[File Names]

[URLs]

[Messages]
Invalid: fail=False
EOT: https://jmana.net/book/영웅의%20딸로%20다시%20태어난%20영웅은%20다시%20영웅을%20목표로%20한다

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by niaong** [comment]
넵 잘 작동 됩니다. 감사합니다.
