### ISSUE TITLE
(기능추가 문의) 픽시브 팔로우 일괄 다운기능은 없나요?

### ISSUE THREAD

**Issue by hifatia** [KurtBestor/Hitomi-Downloader-issues#1488]
기능이 존재하는데 제가 못찾는건지는 잘 모르겟는데 만약 있다면

사용법좀 가르쳐주시고 없다면 추가는 어려울까요?

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/2286
