### ISSUE TITLE
Twitter error

### ISSUE THREAD

**Issue by panhartstuff** [KurtBestor/Hitomi-Downloader-issues#1493]
Getting an error in https://twitter.com/bongchoonsik/media
The download got stuck on 1975/1976
Error log is here:
https://pastebin.com/raw/BiUwN00F

I'm also getting a lot of youtube-dl errors in other downloads. Example:
https://twitter.com/hanabushi_/media >> https://pastebin.com/raw/S2trCTxa
But those downloads finishes just fine. Don't know of any reliable way of verifying the resulting file quantity, though.

This error message seems to appear frequently:

> Twitter video Error:
> Traceback (most recent call last):
> File "twitter_downloader", line 425, in get
> File "youtube_dl\YoutubeDL", line 819, in extract_info
> File "youtube_dl_test", line 13, in report_error
> DownloadError: ERROR: Unable to extract OpenGraph title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Any ideas why?

**Comment by KurtBestor** [comment]
Try the test version: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

If the error occurs again, please report it later.

**Comment by panhartstuff** [comment]
Test version no longer fail on bongchoonsik
But it still fails on:
https://twitter.com/kuroboshi/media >> https://pastebin.com/raw/9kw2vAPk
Stuck on 977/978

https://twitter.com/k3_spaceybear/media >> https://raw.githubusercontent.com/panhartstuff/dump/master/error (got hit bypastebin size limit)
Stuck on 2054/2066

**Comment by KurtBestor** [comment]
Try the test version: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

kuroboshi has 1 broken image:
- https://twitter.com/kuroboshi/status/231985916477075456

k3_spaceybear has 4 broken images:
- https://twitter.com/k3_spaceybear/status/772534025424474113
- https://twitter.com/k3_spaceybear/status/769978418125504517
- https://twitter.com/k3_spaceybear/status/700364845850296320
- https://twitter.com/k3_spaceybear/status/550680967212306432

All of them are not available neither in the downloader nor in web browser:
![image](https://user-images.githubusercontent.com/14768120/71206112-2ca4a980-22e7-11ea-9e5b-b6b5f4f3f721.png)

**Comment by KurtBestor** [comment]
Try the test version: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

kuroboshi has 1 broken image:
- https://twitter.com/kuroboshi/status/231985916477075456

k3_spaceybear has 4 broken images:
- https://twitter.com/k3_spaceybear/status/772534025424474113
- https://twitter.com/k3_spaceybear/status/769978418125504517
- https://twitter.com/k3_spaceybear/status/700364845850296320
- https://twitter.com/k3_spaceybear/status/550680967212306432

None of them are available even in web browser:
![image](https://user-images.githubusercontent.com/14768120/71206112-2ca4a980-22e7-11ea-9e5b-b6b5f4f3f721.png)

**Comment by anonieee** [comment]
Thank you, the number checks out now.
Another thing I want to ask: why is youtube-dl involved when downloading videos? I thought you can just grab direct links to the mp4? Strangely, some (not all) videos have different hash compared to the ones grabbed by the Twitter Media Downloader chrome extension (https://github.com/furyutei/twMediaDownloader)
Also is there an option for overwriting files? Or specifically just video files? I want to recheck for errors.

**Comment by panhartstuff** [comment]
Thank you, the number checks out now. 
I want to ask about another thing: why is youtube-dl involved when downloading videos? I thought you can just grab direct links to the mp4? Strangely, some videos have a different hash compared to the ones grabbed by the Twitter Media Downloader chrome extension. (https://github.com/furyutei/twMediaDownloader)

**Comment by KurtBestor** [comment]
youtube-dl is used to get high quality MP4 videos. Without the Twitter API, only low quality TS videos are available.
The Twitter Media Downloader uses Twitter API to get videos also.

FFmpeg is used to get thumbnails. It's used only when the latest tweet has a video.
