### ISSUE TITLE
네이버웹툰 성인툰 다운로드

### ISSUE THREAD

**Issue by unknown041** [KurtBestor/Hitomi-Downloader-issues#1497]
다운로더가 성인인증이 안돼서 다운이 안되는건지,
네이버 성인웹툰 다운로드가 안됩니다. 확인부탁드립니다.
프로그램 늘 잘쓰고 있습니다. 감사합니다

**Comment by KurtBestor** [comment]
성인웹툰은 로그인이 필요한데, 네이버 로그인은 아직 지원하지 않아요.
