### ISSUE TITLE
Exception: recaptcha

### ISSUE THREAD

**Issue by copper-W** [KurtBestor/Hitomi-Downloader-issues#15]
maru_266642: reCAPTCHA

gal_num: http://www.marumaru.in/b/manga/266642
dir: 
zip: 
type: maru
artist: 오지로 마코토
url: http://www.marumaru.in/b/manga/266642
valid: False
done: False

[File Names]

[URLs]

[Messages]
Traceback (most recent call last):
File "hitomi_downloader", line 999, in download_maru
File "maru_downloader", line 111, in get_imgs_all
Exception: recaptcha

Traceback (most recent call last):
File "hitomi_downloader", line 999, in download_maru
File "maru_downloader", line 111, in get_imgs_all
Exception: recaptcha

Fail: maru

done : http://www.marumaru.in/b/manga/266642

**Comment by KurtBestor** [comment]
현재 개발중인 기능입니다.

다음 링크에서 프리릴리즈 버전을 다운로드해서 reCAPTCHA 관련 설정을 할 수 있습니다:
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

![recaptcha](https://user-images.githubusercontent.com/14768120/34658713-854a5948-f474-11e7-9d1f-ec8a3cbce62e.png)

한번 테스트해보시고 어떻게 동작하는지 확인해주시면 도움이 될 것 같아요.

**Comment by KurtBestor** [comment]
v2.0에 해당 기능 추가됨
