### ISSUE TITLE
다운로드 목록에서 중복되는 것 삭제 기능에 대해

### ISSUE THREAD

**Issue by wpfhfpr** [KurtBestor/Hitomi-Downloader-issues#150]
필터 자체에 dup: 를 사용해도 중복되는 것은 다운 완료 후로 중복 확인이 가능하더라구요.

다운로드 목록에 옮겨졌을 때 중복되는 것을 일제히 삭제하는 버튼이나 기능이 있었으면 해서 건의 해봅니다.
예를 들면 제가 히토에서 IRIOMOTE 그룹을 검색해서 다운받고 작가 Saryuu를 검색해서 다운을 받게 되는 데 문제는 그룹에 Saryuu라는 작가만 있으면 좋겠지만 다른 작가도 있어서 다운받다보면 자연스레 중복되는게 생기게 됩니다.반대로 Saryuu라는 작가가 IRIOMOTE라는 그룹만 이용하지 않을 경우 다른 그룹에 소속되있는 게 안뜨는 경우가 있어서 다른 그룹걸 다운받다보면 중복이 생기는 데
저같은 경우는 파일이 두번받아지는 경우가 생겨서요 ㅠ

실현이 가능하다면 매우 고맙겠습니다. 프로그램 정말 잘 쓰고 있습니다. 감사합니다.

**Comment by KurtBestor** [comment]
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

테스트 부탁드려요.
다운로드 완료되지 않아도 dup: 으로 중복 체크 가능해요.

**Comment by KurtBestor** [comment]
어떤 버전 쓸 때 에러 뜨면서 꺼졌나요?

**Comment by wpfhfpr** [comment]
검색기 검색된 것 내부 리스트에서 검색되는 기능도 있으면 나쁘지 않을 거 같아요!!ㅎㅎ

**Comment by wpfhfpr** [comment]
아니요 이전 버전에는 아예 목록에 뜨지않더라구요

**Comment by KurtBestor** [comment]
어떤 버전 쓸 때 에러 뜨면서 꺼졌나요?

**Comment by wpfhfpr** [comment]
2.3d입니다!
