### ISSUE TITLE
사이트 추가 문의

### ISSUE THREAD

**Issue by totle91** [KurtBestor/Hitomi-Downloader-issues#1509]
안녕하세요. 프로그램 잘 쓰고 있습니다. 감사합니다. 

https://newtoki38.com/
https://toonkor.rent/

이 사이트들도 추가 시켜주시면 안될까요?? 부탁드립니다.

**Comment by KurtBestor** [comment]
참고해주세요:
- `도움말` - `사용법... (F1)` - `스크립트`
- https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/404

**Comment by totle91** [comment]
감사합니다!
