### ISSUE TITLE
다운로더, 검색기 창 관련

### ISSUE THREAD

**Issue by aperie** [KurtBestor/Hitomi-Downloader-issues#151]
다운로더를 껐다가 켤 경우 다운로더와 검색기 모두 창 위치, 크기가 초기화되어 나타나더군요. 다음 실행시 이전과 같은 위치, 크기로 나타나는 기능은 구현 가능할까요? (주로 win+←로 검색기를 화면의 좌측에, win+→로 다운로더를 화면의 우측에 정렬해서 사용하고 있습니다)

그리고 검색기를 최소화하면 작업 표시줄로 들어가지 않고 화면 좌하단에 플로팅 형태로 표시가 되던데(듀얼 모니터 환경인데 2번 모니터에서 최소화를 했는데 1번 모니터로 가더라구요.. 덕분에 처음 최소화 해놓고 어디 있는지 몰라서 한참 헤멨습니다. alt+tab 으로도 안 잡히고 다운로더 → 메뉴 → 검색기를 눌러봐도 아무 반응이 없기에) 작업 표시줄에 서로 다른 창으로 표시되어서 다운로더와 검색기를 alt+tab 등으로 오갈 수 있게 되었으면 좋을 것 같아요.

**Comment by KurtBestor** [comment]
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

테스트 부탁드려요.

**Comment by aperie** [comment]
작업 표시줄은 제대로 표시되네요. alt+tab 으로 창 전환도 잘 됩니다. 감사합니다!

창 위치, 크기 저장 관련은 적용이 되지 않은 건가요?

**Comment by KurtBestor** [comment]
네. 창 위치크기 저장은 넣지 않았어요.
