### ISSUE TITLE
실행이 안 됩니다.

### ISSUE THREAD

**Issue by Elrendar** [KurtBestor/Hitomi-Downloader-issues#1511]
exe 파일 실행 시 아주 잠깐 마우스 커서가 모래시계로 바뀌었다가 다시 돌아오고 이후 반응이 없습니다.
작업관리자에 뜨지도 않고, 관리자 권한을 묻지도 않네요.

얼마 전까지 잘 되고 있었는데 갑자기 안 되네요.

새로 다운로드 받아서 실행해도 같은 증상인 거 보면 제쪽에 문제가 있는 것 같은데, 아무런 반응이 없으니 뭘 어떻게 해야 할지 잘 모르겠습니다.

**Comment by KurtBestor** [comment]
어떤 백신 쓰시나요?

**Comment by Elrendar** [comment]
카스퍼스키 무료버전 사용중입니다.
보호 일시 정지 후 실행해봤으나 동일 증상 발생합니다.

**Comment by KurtBestor** [comment]
글쎄요.. 제 쪽에선 재현할 수 없어서 제가 묻고 싶네요. 뭔가 바꾼 게 있나요?

**Comment by Elrendar** [comment]
당장 생각나는 건 없네요;;
혹시 다른 보안 프로그램 때문일 수 있으니 추후에 문제 재발 시 다시 테스트 해보겠습니다.
