### ISSUE TITLE
마루마루 장르별 다운로드

### ISSUE THREAD

**Issue by ssh003** [KurtBestor/Hitomi-Downloader-issues#152]
혹시 장르별로 그냥 전부 다 다운로드 할 수가 있을까?? 그렇게 해서 중복 폴더명은 바로바로 스킵해서
항상 최신으로 유지될 수 있게..
https://puu.sh/ASSAS.jpg

이런식으로 원래 내가 관리하던게 있는데.. 폴더명은 전부 마루마루 제목 기준으로...
원래 내가 만들어 쓰던 프로그램이 있는데 Attention required 뜨면서 원천에서 막혀버리니까
오토핫키 스크립트 언어밖에 못쓰는 나는 도저히 살아갈 방법이 없다....
히토미도 내가 만들어서 쓰던게 있는데 사실상 버린게 되어버림 히토미 롤러라고

**Comment by KurtBestor** [comment]
필요한 만화 추가해놓고 필요할 때마다 [다시 시작] 하면 최신으로 유지돼요.

오토핫키는 안 써봐서 잘 모르겠는데, 그 전까지 됐는데 안됐다면 헤더만 조금 만져주면 될거예요.
최근에 헤더에 Referer가 없으면 다운로드 못하게 했더라구요.
다음과 같이 해주시면 될거예요:
```
SetRequestHeader("Referer", "http://wasabisyrup.com/archives/1234")
```

**Comment by ssh003** [comment]
세상에 마상에... 정말 고맙습니다... 당신은 저의 구세주이십니다
