### ISSUE TITLE
[Request] Saving the account password for "Pixiv" when closing the application

### ISSUE THREAD

**Issue by xZabuzax** [KurtBestor/Hitomi-Downloader-issues#1533]
Your account password for "Pixiv" doesn't get saved when you close the application so every time you open it you need to enter the password again. Some users would love if you provide the option to save the password.

Is there any reason why the password doesn't get saved?

Thanks.

**Comment by KurtBestor** [comment]
Press `Tasks` - `Save (Ctrl + S)` to save the preferences.

**Comment by xZabuzax** [comment]
> Press `Tasks` - `Save (Ctrl + S)` to save the preferences.

I already did and the Password doesn't get saved, it only saves the Username but not the Password.

**Comment by KurtBestor** [comment]
Please send your INI file to me, It's in the same folder as the executable. I'd like to analyze it.

**Comment by xZabuzax** [comment]
> Please send your INI file to me, It's in the same folder as the executable. I'd like to analyze it.

Thank you for taking your time to analyze it. Here's the .ini file:

https://mega.nz/#!BVQDEawI!8O0jupVV-bH9BkoYC_SlU7J_dtMS5dQfv3bMWSklynM

**Comment by KurtBestor** [comment]
Press <kbd>Ctrl</kbd> + <kbd>Alt</kbd> + <kbd>C</kbd> to open the console window, and type the following text and press <kbd>Enter</kbd>:
```
fucking_encoding.encodings
```
Can you show me the output from the console?

**Comment by xZabuzax** [comment]
> Press Ctrl + Alt + C to open the console window, and type the following text and press Enter:
> 
> ```
> fucking_encoding.encodings
> ```
> 
> Can you show me the output from the console?

Sure mate:

> ['cp1252', 'mbcs', 'ascii', 'utf-8', 'ascii']

**Comment by KurtBestor** [comment]
Try the test version: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by xZabuzax** [comment]
> Try the test version: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

Excellent!, that version fixed the issue, the password is getting saved now.

Thanks!
