### ISSUE TITLE
툰코 스크립트에서 urljoin 하는 부분입니다.

### ISSUE THREAD

**Issue by kdrkdrkdr** [KurtBestor/Hitomi-Downloader-issues#1535]
get_imgs_page() 함수에서 페이지URL 이랑 img['src'] 둘을 합치는 것으로 보이는데, 둘이 안합치고 그대로 이미지 주소 써도 되는 페이지도 존재합니다. 나눠서 처리하셔야할 것 같습니다.

https://github.com/kdrkdrkdr/ToonKorDownloader/blob/master/ToonkorDownloader.py#L184

GetIMGsURL() 함수 확인 부탁드립니다.

**Comment by KurtBestor** [comment]
안 되는 화 있으면 알려주세요.
