### ISSUE TITLE
마루마루 다운받을때 

### ISSUE THREAD

**Issue by tkffuwntpdy** [KurtBestor/Hitomi-Downloader-issues#154]
제가 컴에서 받고 폰에다 넣어서 보는데 압축 안한거로 넣으면 넣는데 시간이 오래걸려서 

올라온 글에 전체목록 보기 주소를 복사해서 압축으로 다운받았더니 

최신화까지 한번에 압축이 되더라구요 그래서 다음화가 추가되면 기존걸 지우고 

다시 받아 넣어야할거 같아서 말입니다 

각 화별로 개별 압축 되는 방법이 있는데 제가 못찾은 건가요?

만약 없다면 추가는 안될까요?

**Comment by KurtBestor** [comment]
네. 직접 하셔야 할 것 같아요.

**Comment by luku756** [comment]
https://github.com/luku756/ComicZip
위 작성자님 말대로 각자 다운받은 후 자동 압축 프로그램 돌려서 하시면 될 것 같네요.
제작자분은 따로 압축을 추가할 용의가 없으신 것 같아서 간단하게 만들었습니다.
