### ISSUE TITLE
페이지 지정다운문제

### ISSUE THREAD

**Issue by tlzmflt** [KurtBestor/Hitomi-Downloader-issues#1548]
히토미에서 페이지 지정 다운을 하면 페이지 관계없이 첫번째 페이지 이름으로 저장됩니다 해결바랍니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by tlzmflt** [comment]
잘됩니다 감사합니다.

**Comment by Sn0w0wl** [comment]
고쳐진게 있었네요;; (고쳐졌어요!)
읗. 최신버전 다운받았었는데 최신이 아니었나;
