### ISSUE TITLE
건의사항

### ISSUE THREAD

**Issue by jaejunghan** [KurtBestor/Hitomi-Downloader-issues#155]
겔보루는 다운받아지는데, 단보루하고 센카쿠 콤플렉스 다운받아지도록 요청드립니다

**Comment by jaejunghan** [comment]
단보루가 여전히 다운이 안되네요.. 단보루에잇는게 겔보루에 자동등록은 2013년 2월이후 되지않는걸로 알고잇습니다

**Comment by KurtBestor** [comment]
https://gelbooru.com/index.php?page=post&s=list&tags=user:danbooru

단부루는 넣지 않았다고 했습니다. 여전히 미러링 잘 되고 있네요.

**Comment by KurtBestor** [comment]
https://github.com/KurtBestor/Hitomi-Downloader/issues/2074#issuecomment-654589343
