### ISSUE TITLE
마나모아 특정 화의 특정페이지가 안받아집니다

### ISSUE THREAD

**Issue by lducjswo** [KurtBestor/Hitomi-Downloader-issues#1552]
https://manamoa23.net/bbs/board.php?bo_table=manga&wr_id=1377724
웹에서 보면 중간중간에 깨진그림파일 표시가 나오긴 해도 실제로 보이는 페이지수가 18페이지 정도 되는데 다운로드할때 보면 10페이지정도만 받아지고 나머지는 실패합니다
몇번 다시받아도 마찬가지인데 확인부탁드립니다

**Comment by KurtBestor** [comment]
테스트 해봤는데 보이는 페이지는 일단 다 받아지네요. 브라우저에선 보이는데 다운로드 안 되는 페이지 있으면 알려주세요.

**Comment by lducjswo** [comment]
다시 확인해보니 잘 되네요
감사합니다
