### ISSUE TITLE
Tumblr 다운로드 오류

### ISSUE THREAD

**Issue by khornek** [KurtBestor/Hitomi-Downloader-issues#156]
(버전 2.3d)
텀블러 등록한 것들 전부 다 약 98~99%정도만 받아집니다.
트위터는 드물게 몇개 안맞아지고 다운종료되네요.

그리고 다운로드를 시작/정지 기능이 있었으면 좋겠습니다.

**Comment by KurtBestor** [comment]
해당 작업 마우스 우클릭 후 정보... 눌러서 나오는 내용 알려주시면 분석해볼게요.
