### ISSUE TITLE
검색 시 이미지가 나오지 않습니다.

### ISSUE THREAD

**Issue by stvking72** [KurtBestor/Hitomi-Downloader-issues#1563]
1월 10일인가 이쯤 부터 검색하는 파일의 이미지가 나오질 않습니다.
근 전 파일들은 이미지가 나옵니다.
DPI 우회 실행 중 입니다.
![이미지오류](https://user-images.githubusercontent.com/59783254/72213314-1c6f9b00-3530-11ea-84a5-92110c995e79.png)

**Comment by KurtBestor** [comment]
Duplicate of #1562
