### ISSUE TITLE
NAS(네트워크 디스크)에서 작동이 되지 않습니다.

### ISSUE THREAD

**Issue by mirusu400** [KurtBestor/Hitomi-Downloader-issues#1568]
안녕하세요. 프로그램 항상 잘 쓰고 있습니다.
최근에 프로그램을 제 외장하드에서 NAS로 옮기고, 이를 네트워크 디스크나 RaiDrive를 이용한 WebDav를 이용해서 프로그램을 켜는데, 이렇게 프로그램을 켜면 아래 사진과 같이 작동하지 않습니다.

![예시](https://i.imgur.com/rjbqU0J.png)

첫번째 노란색으로 된건 네트워크 디스크, 즉  #1520 의 케이스같이 주소창에 직접 제 NAS 주소를 입력해 들어가 다운을 시도한것입니다. 이 경우 아예 폴더가 생성되지 않고 저렇게 다운로드 시도만 계속합니다.

두번째는 제가 강제로 확인 표시한 것인데, RaiDrive를 이용해 연결한 WebDav로 시도한 케이스입니다. 이 경우 폴더 생성 및 다운로드는 되지만, 썸네일 생성과 완료 확인이 되지 않습니다. 결론적으로 위 케이스와 마찬가지로 다운로드 시도만 계속합니다.

제 얄팍한 지식으로 생각해보자면 후자의 경우는 ini파일에 저장할때 썸네일 이미지와 기타 등등을 상대경로가아닌 절대경로로 저장해서 그런 듯 한데, 확인 후 수정 부탁드리겠습니다. 감사합니다.

[첫번째 케이스 로그](https://slexy.org/view/s20nByuIUp) [두번째 케이스 로그](https://pastebin.com/x2ncvGJF) 첫번째 케이스는 용량상 slexy를 이용했습니다

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/1520#issuecomment-574579430

**Comment by mirusu400** [comment]
1. 탐색기로 네트워크 드라이브에 마운트(드라이브 문자 할당)
2. WebDav + RaiDrive
유튜브는 2번 방식으로밖에 테스트해보지 못했지만, 트위터와 웨이보 링크로 테스트 결과 두 케이스 다 잘 작동하는거 같습니다. 감사합니다.

실례가 안된다면 혹시 언제 업데이트 될지 여쭤봐도 될까요?

**Comment by KurtBestor** [comment]
아마 이번 달 안에 업데이트 될거예요.

**Comment by mirusu400** [comment]
Readme파일에는 해결됬다고 나와있진 않지만 2.7h 버전에서 정상적으로 작동하는걸 확인했으므로 이슈 닫겠습니다 감사합니다 ㅎㅎ
