### ISSUE TITLE
코드 부분 질문입니다.

### ISSUE THREAD

**Issue by hyuk199** [KurtBestor/Hitomi-Downloader-issues#158]
저번에 코드관련 질문했는데 다른 부분 때문에 질문해요.
코드중 히토미에서 웹크롤링해서 이미지만 소스따서 다운 받는 부분 좀 자세히 알려줄수 있을까요?
코드를 참고해 작업을 하려해도 너무 많고 제가 파이썬 초보라 잘 모르겠어요.

**Comment by KurtBestor** [comment]
파이썬을 배우거나, 아니면 아는 다른 언어로 된 코드를 참고하는 게 좋을 것 같아요.

[다양한 다른 프로젝트](https://github.com/search?o=desc&q=hitomi&s=updated&type=Repositories)들이 있으니 참고해보세요.

**Comment by hyuk199** [comment]
현재 웹크롤링해서 이름이랑 작가명 번호 따오는건 했는데 이미지 소스를 못 찾아서 그래요.
이미지 소스를 어디 부분에서 따오신지 알수있을까요?

**Comment by KurtBestor** [comment]
hitomi_downloader 모듈에 pop_img 보시면 나와있습니다.
