### ISSUE TITLE
클립보드에서 자동 추가 설정 저장 안 됨, 채널 단위의 다운로드에 관해

### ISSUE THREAD

**Issue by c8ch** [KurtBestor/Hitomi-Downloader-issues#1580]
클립보드에서 자동 추가 기능을 끄고 저장해도 프로그램을 재시작할 경우 항상 활성화돼 있다

이처럼 프로그램을 켜둔 채 웹서핑을 하다가 유튜브나 네이버, 인스타그램 등

채널, 계정 단위의 주소를 복사할 경우, 다운로드 의사가 없음에도 불구하고

한 번에 수백 개 이상의 항목을 받으려다 프로그램이 뻗고, 재시작해도 마찬가지

분석 후 10개 이상의 항목을 다운로드 할 경우 정말 다운로드 할 건지 물어봐야 한다

1. '클립보드에서 자동 추가' 설정이 저장 안 됨

2. 채널, 계정 단위의 주소 분석 후 다운로드 시 확인 메시지 필요

3. 혹 다운하려고 해도 프로그램이 뻗는 건 프로그램의 안정성 미흡

**Comment by KurtBestor** [comment]
1. 참고해라: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/567, https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/1291
2. `클립보드에서 자동 추가` 를 끄고 해라.
3. 뻗는 주소 알려달라.

**Comment by c8ch** [comment]
1. 근 1년동안 해결 못한 일이니 더 기다리란 소리인가? 읽어도 도움이 되지 않는다
2. 자주 쓰는 사이트는 자동 추가 기능이 유용하다
문제는 프로그램을 시작하면 내 선택과 관계 없이 설정이 모두 켜져서 그렇지
프로그램을 켤 때마다 원하는 사이트만 받도록 체크하는 건 평범하지 않다
그 설정을 프로그램이 기억해서 사용자를 편하게 하지
3. 특정 주소가 문제가 아니다
https://www.youtube.com/user/MBCkpop/videos
https://www.youtube.com/user/ebsdocumentary/videos
이처럼 동영상이 많은 곳, 웹 서핑을 하다보면 이 주소, 저 주소 복사할 수도 있는데
그것들이 모두 다운로더에서 받고 있으면 안정성이 급격히 떨어진다

**Comment by KurtBestor** [comment]
1. 다른 우선순위 더 높은 것들을 먼저 하고있다. 내 개인 시간을 할애해서 만들고 유지보수하는 프로젝트다. 기다리기 싫으면 기다리지 마라.
2. 1번과 동일한 내용
3. `클립보드에서 자동 추가` 는 항상 켜놓고 쓰는 기능이 아니다. 여러 주소를 빠르게 추가할 때 잠깐 켜놓는 용도로 만들어졌다. 테스트 해보니 다운로드하는데 문제는 없었다.
