### ISSUE TITLE
마나모아 다운로드가 봉쇄되었습니다

### ISSUE THREAD

**Issue by cancerogenic** [KurtBestor/Hitomi-Downloader-issues#1582]
너무 슬픕니다..

Invalid: [manamoa] https://manamoa25.net / bbs / board.php?bo_table=manga&wr_id=2595534

version: 2.7e
platform: Windows-10-10.0.18362
order: 0
group: False
gal_num: https://manamoa25.net/bbs/board.php?bo_table=manga&wr_id=2595534
dir: 
zip: 
type: manamoa
artist: None
url: https://manamoa25.net/bbs/board.php?bo_table=manga&wr_id=2595534
valid: False
done: True
range: None
range_p: None
single: True
time: 1579286270.14 (Jan 18)
tags: []
goodbyedpi: False
lock: False
color: invalid
paused: False

[Gallery]
None

[File Names]

[URLs]

[Messages]
stop
Traceback (most recent call last):
File "utils", line 671, in __init__
File "manamoa_downloader", line 129, in init
File "manamoa_downloader", line 97, in get_title_page
AttributeError: 'NoneType' object has no attribute 'findAll'

Invalid: fail=True
stop
EOT: https://manamoa25.net/bbs/board.php?bo_table=manga&wr_id=2595534

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by cancerogenic** [comment]
너무 감사천만입니다..
