### ISSUE TITLE
익헨 원제목으로 저장할 수 있는 방법이 있나요?

### ISSUE THREAD

**Issue by fdsa1538** [KurtBestor/Hitomi-Downloader-issues#1583]
**다운로드는 히토미에서 하구,, 이름은 익헨 페이지에 명명된 제목 그대로 폴더 이름을 지어줄 수는 없을까요?** 
여기 들어와서 이름,제목,네이밍등으로 검색해서 찾아봤는데 #1074 여기를 보니 익헨서버에서 다운로드해야 되더라구요.. 

섭종 사태 때 위기를 느끼고 방주 만들다 이런 고마운 프로그램을 접하게 됐는데요,, 오래전부터 익헨식작명법으로 저장해와서 만들어주신 프로그램으로 다운로드 하려니 중복이 생기더라구요.. 
방주 만들면서 익헨에서만 다운로드 하다보면 익헨 IP밴당할까봐 걱정되기도 하구,, 
동인지에 붙는 (C99) (COMIC*22) 같이 행사를 지정해주는 머리말이나 상업단편 제목에 뒤에 붙는 (Angel club 몇월호) (comic koh 2020-01) 이런 정보를 이용해서 윈도우 탐색기 기능을 자주 사용해서요,, 
익헨 제목에 붙는 작가 이름과 히토미 작가이름 태그가 일치하지 않을 때두 있구요.. 
현재 다운로더의 폴더 작명 방식으로는 압축까지 완료되는 걸 기다린 다음 익헨 페이지를 다시 검색해서 복붙해야하다보니, 노가다성이 너무 심해서 혹시 제가 모르는 방법이 있는지 여쭤봅니다..

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/855

아직 추가되지 않은 기능이에요.

**Comment by fdsa1538** [comment]
답변감사드립니다~!!

**Comment by fdsa1538** [comment]
#855 
혹 이슈가 닫혀서 못보신 것 같아서 다시 여쭤봅니다..
제목 100자 제한 때문에 라노벨 원작 같이 제목이 긴 동인지 같은 것들은 이름이 짤려서 붙여져요..
이름이 계속 짤려서 나오길래 혹시나 싶어서 세어보니까 딱 100자였어요
기능 만들어주셔서 감사합니다
