### ISSUE TITLE
Unable to download the full image set from artists in "Pixiv"

### ISSUE THREAD

**Issue by xZabuzax** [KurtBestor/Hitomi-Downloader-issues#1587]
In Pixiv you are unable to download the full image set from an artist, it stopped working, you are only able to download the images separately by clicking on the link of that image, but if you wish to download all the images from the artist you get an error.

**Comment by KurtBestor** [comment]
Please see: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/1550

**Comment by xZabuzax** [comment]
> Please see: #1550

Thank you, the version you provided in that link fixed the issue. I guess this issue is fixed then, I will close this one.

Keep up the awesome work dude!
