### ISSUE TITLE
[bug] Pixiv link structure has changed

### ISSUE THREAD

**Issue by TheJvict** [KurtBestor/Hitomi-Downloader-issues#1595]
Recently, pixiv's link structure has changed from: https://www.pixiv.net/member.php?id=12345678 (for users) and https://www.pixiv.net/member_illust.php?mode=medium&illust_id=12345678 (for illustrations)
To: https://www.pixiv.net/en/users/12345678 (for users) and https://www.pixiv.net/en/artworks/12345678 (for illustrations)
Which makes the Hitomi Downloader not recognize the link as valid
The id numbers are still the same, so the issue can be worked around by copying the id from the new structure and pasting it in the old one

**Comment by KurtBestor** [comment]
Please see: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/1550

**Comment by TheJvict** [comment]
Thanks
