### ISSUE TITLE
다운로드 혹시 저만 안되나요?

### ISSUE THREAD

**Issue by ggoke123** [KurtBestor/Hitomi-Downloader-issues#16]
10.6MB 까지만 다운로드 되고 .. 막히네요

이 사이트? 에서는 첨 받아보고 항상 구글 링크로 연결됬던거같은데... 다른 링크가 있을까요 혹시?

**Comment by KurtBestor** [comment]
어떤 브라우저 쓰시나요? 다른 브라우저로 시도 해보셨나요?

실은 제 다른 컴에서 크롬 + 구글 드라이브는 다운로드가 안되더라구요.
테스트 삼아 다른 컴에서 실행 해보기도 하는데, 불편해서 이 링크를 쓰게 되었어요.

**Comment by KurtBestor** [comment]
문제가 많은 것 같아 일단 구글 드라이브로 다시 돌려놨습니다.
