### ISSUE TITLE
기능 건의입니다.

### ISSUE THREAD

**Issue by wpfhfpr** [KurtBestor/Hitomi-Downloader-issues#161]
1. 검색기 자체에 "결과 내 검색"을 실현하는 것이 가능할 지 궁금합니다.
     작가 검색이나 그룹 검색 결과 목록에서 어떠한 작품을 찾을 때 용이하다고 생각합니다.
     대신 문제가 되지 않는 선에서 검색된 작품에 대해 다운로드 후 "결과 내 검색"을 해제 했을 때 이전 검색 목록에는 변화가 없고 검색 후 다운받거나 제거한 목록이 '해제'했을 때 역시 표시되지 않게끔 하는 게 가능할지요.

2. 이건 제가 봐도 조금 어렵거나 컴퓨터 사양을 탈 것 같긴하지만 가능한 지 여쭤보고 싶습니다.
 
   이전 중복파일 제거 문의에서  PC에 이미 받아놓은 작품에 대해 중복 확인이 가능한가에 대해서 입니다. 아무래도 작가별 + 그룹별로 받다보니 중복파일을 받는 경우가 많아져서 3TB의 용량도 버티기 힘들 때가 있어서 조심스레 여쭤봅니다 ㅠㅠ

3. 검색 후 같은 이름의 작품인데도 불구하고 정렬을 이름 순서로 해도 떨어져있는 경우가 있는데 이것은 버그일까요..?ㅠ

4. 검색 후에 같은 작품이 있는 경우가 있습니다. 저는 언어를 ALL로 해놓아서 다양한 나라의 언어로 된 동일 작품이 있는 데요.  한국 작품이 있는 경우 그 작품만 한글로 된 작품만이 나오고 번역이 안된 작품들은 외국어로 된 작품이 검색될 수 있게끔 할 수 있는 필터를 만들어주실 수 있을까요?

## 작품 검색시 ##
A라는 작품은 (일 영 한 중국어) B라는 작품은 ( 일 타이 중국어)
~ 기존(언어: ALL)                =>      ~ 적용 시(언어: 주! 한국어 ~ 그외 모든 언어)
A(일 영 한 중국어)                          A(한국어)
B(일 타이 중국어)                           B(일 타이 중국어)
총 7개의 목록                                 총 4개의 목록
----------------------------------------------------------------------------------------------------------
실현이 될 지는 모르겠지만 한국어 번역판이 있는 것을 모르고 타국어로 된 것을 받을 가능성이 줄어들지 않을까하고 건의를 남겨봅니다.
PS. 혹시 테스트용으로 만들어주신다면 중복제거에 대해 적용시켰던 다운로더 테스트 버전에 추가해주시면 감사하겠습니다 ~

마지막으로.........
제가 이전에 중복 파일 문제로 건의했었는 데 역시 감사하게도 구현해주셨습니다.
이쪽 프로그래밍을 하지 않고 기계 내부 시스템에 관련된 프로그래밍을 하다보니 프로그래밍이 어렵고 복잡하다는 것도 충분히 알고 있다 생각합니다. 
이런 조그마한 글 밖에 못 쓰는 게 죄송하네요. 이런 갓 프로그램을 만들어주셔서 감사합니다!

**Comment by KurtBestor** [comment]
1. 무슨 말인지 모르겠습니다. 좀 더 쉽게 설명해주실 수 있나요?
2. 이것도 무슨 말인지 잘 모르겠습니다. 같은 작품을 다운로드하면 같은 폴더명을 가지니까 중복돼도 문제 없는 것 아닌가요?
3. 검색기 ★ 메뉴에서 정렬을 말씀하시는거면 북마크를 정렬하는 기능이예요. 검색은 항상 똑같은 순서입니다.
4. 같은 작품이라도 언어가 다르면 제목이 같은 경우는 드물기 때문에 어려울 것 같아요. 언어가 다를 때 같은 작품인지 판단하기 어렵네요. 언어가 다르면 표지 이미지도 다른 경우가 대부분이라서, 표지로 구분하는 것도 불가능해요. 표지 이미지를 피쳐매칭하면 어느정도 가능하긴 할텐데, 너무 연산량이 크네요.

**Comment by wpfhfpr** [comment]
답변 감사합니다.
1. Kojima saya라는 작가를 검색했을 경우 Bunny Gakuen e yokoso라는 작품이 여러개 나오게 됩니다.
    같은 작품인데도 후기 페이지나 기타페이지 차이로 2~3페이지 나는 경우가 있지만 거의 동일한 작품이라서 다운받기전에 미리 중복 작품을 없애고 받거든요.
 
저는 한번에 받기때문에 중복파일을 미리 목록에 나와있는 것들을 Del 해서 검색된 목록에서 삭제 후 Kojima 작가의 중복이 안된 (A라는 작품이 한국어가 있을 경우 일일이 다 클릭해서 Del로 목록에서 없앤 뒤) 것들을 다운받습니다.

여기서 제가 말씀드린 기능은 다나와 같은 사이트를 가보면 보이는 검색 후에 결과 내 검색이란 기능입니다.
Kojima saya의 작품 A(한 중 일),B(중 영),C(중 일),D(영 일)로 되있는 경우 고급 검색에서 작가(Artists)에 Kojima saya를 쓰고 검색하면 A,B,C,D에 관련된 작품 9개가 나오겠죠?
이 때 A에 관련된 작품을 모아서 보고 싶을 경우 결과 내 검색을 통해서 A의 한 중 일어 작품 3개만 목록에 뜨게 한 뒤에 다운을 받던지 Del키를 눌러 목록에서 삭제를 하던지 작업을 하는 거죠.
저 같은 경우엔 A의 작품에 한국어가 있으므로 중 일어는 Del을 눌러 목록에서 삭제를 하겠네요.
그 뒤 결과 내 검색 기능에 공백을 만들던지 기능을 off시키면 다시 목록창엔 Kojima Saya 작품들 A,B,C,D가 나오고 대신 A작품을 검색했을때 삭제한 중 일어는 나오지 않고
A(한국어) ,B(중 영),C(중 일),D(영 일) 이렇게 총 7개의 작품만 목록에 나오게 되는 .. 그러한 기능을 가능하시다면 보고싶습니다.

저 같이 작가를 검색하고 원하는 작품을 찾으려 하는 사람에게 유용한 기능이지 않을까 생각됩니다.
제작자님이 말씀하신대로 연산량이 크기에 피쳐매칭은 어려워 보이기에 이를 해결할 방도가 이걸로 어느정도 해소 되지 않을까해서 건의드립니다.

2.저는 설정을 다운받은 후 압축으로 해놓기도 했지만 혹여 압축안하고 폴더로 받는 다 했을 때도
 기존의 파일이 존재하면 그것을 다시 덮어쓰는 식으로 다운받는 걸로 알고 있는 데 아닌가요??

3, 검색 목록 자체를 정렬하는 기능은 힘들까요? 히토미 품번으로 검색되는 것 같아서 어려울것 같기도 하네요 ㅠ

4. 왠지 모르게 예상은 했지만 역시 연산에 무리가 가면 안되죠ㅠ 감사합니다!

**Comment by KurtBestor** [comment]
1. 네. 그러면 다운로더 목록처럼 필터링 기능이 구현될 것 같네요.

2. 폴더로 다운받으면 덮어씌우지 않고 그냥 넘어가요. 다만 지금은 원본 폴더가 삭제되고 압축파일만 있는 경우에 다시 다운로드하는 걸로 되어있습니다. 정리하면 원하시는 기능이 "압축 옵션이 체크되어있고, 컨텐츠 내용이 변하지 않는 작업(Hitomi.la, E(x)hentai)에 대해서, 같은 이름의 압축 파일이 있다면, 다운로드를 스킵한다" 라고 할 수 있겠네요. 틀렸다면 말해주세요.

3. 아직 구현하기가 까다롭네요.. 나중에 추가될 수도 있을 것 같아요.

4. 네.. 여러가지 아이디어는 있는데 속도나 메모리, 안정성 때문에 구현 못한 기능들이 많네요..

자세한 설명 감사합니다!

**Comment by wpfhfpr** [comment]
1. 넵! 작가별로 다운받다보면 Comic 시리즈(용량이 큼)이 많아서 100기가는 금방이더라구요. ㅠㅠ

2. 말씀하신 그대로 입니다~ 
   폴더로 받으면 덮어씌우지 않고 넘어가는 사실은 몰랐네요.알게 되서 다행입니다 ㅎㅎ
   제가 폴더를 사용하지 않는 이유가 파일을 대량으로 옮길때 개수가 많으면 하드 간의 파일이동 속도가 잘 나오지않아서 압축기능(갓갓기능)을 사용해서요. 이것도 구현된다면 매우 좋겠네요 

3,4 배보다 배꼽이 커지는 경우긴 하죠. 3번의 경우는 같은 제목이라도 왜 목록에서 똑같이 나열되지않을까 생각하다보니 데이터 상 히토미 품번 순으로 찾는데로 띄우는 거라 생각했습니다만 맞는거같네요.
이 기능이야 1번의 필터링 기능이 구현되면 필요없어지는 기능이지만요 ㅎㅎ

이런 갓 프로그램 매우 사랑합니다 ㅎㅎ 
혹시 테스트용으로 올려주신다면 중복제거 기능 살려서 해주세요 >_<

**Comment by KurtBestor** [comment]
다음 기능이 추가됐어요:
1. 검색기 목록 필터링
2. 압축과 원본 폴더 삭제를 체크하고 다운로드 할 때, 이미 다운로드된 것 스킵

테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by wpfhfpr** [comment]
1.확인 완료 했습니다.
2.스킵 기능 확인 완료했습니다.
둘다  정상 작동하네요. 검색하는 데 많은 도움이 되고 다운된 것 스킵이 갓갓 기능입니다!
