### ISSUE TITLE
익헨에만 있는거 원래 검색기에 안뜨던가요?

### ISSUE THREAD

**Issue by supermekadeathstalin** [KurtBestor/Hitomi-Downloader-issues#1628]
번호 입력해서 다운하면 다운로드 되는걸로 봐서 차단의 결과거나 한것은 아닌거같은데
검색으로는 목록에 안나옵니다

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/983
