### ISSUE TITLE
질문드립니다

### ISSUE THREAD

**Issue by codeshot2** [KurtBestor/Hitomi-Downloader-issues#163]
혹시 픽시브 유저가 아닌 검색창에 검색해서 나온 그림들을 직접 다운로드 하는 기능이 있나요..?

원하는 그림이 많은데 유저로 일일히 다운로드 받기가 번거로워서요 ㅠ

**Comment by KurtBestor** [comment]
내. 그 부분은 아직 없어요.
픽시브는 현재 다음 기능이 있습니다:
1. 작가 일러스트 일괄 다운로드
2. 작가 북마크 일괄 다운로드
3. 개별 일러스트 or 만화 다운로드
4. 우고이라 변환 (GIF, WEBP)
