### ISSUE TITLE
마리망이 안됩니다..

### ISSUE THREAD

**Issue by tlvkfka** [KurtBestor/Hitomi-Downloader-issues#1635]
마리망 모든 페이지 다 안돼요, 최신 업데이트버전입니다.

[Messages]
cf protection
stop
Traceback (most recent call last):
File "utils", line 653, in __init__
File "mrm_downloader", line 44, in init
File "mrm_downloader", line 193, in get_session
File "constants", line 616, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 589, in wrapper
File "clf", line 9, in wait
File "chrome", line 194, in start
File "chrome", line 120, in __init__
File "FUCK(5)\chrome\webdriver", line 28, in __init__
File "FUCK(5)\remote\webdriver", line 83, in __init__
File "FUCK(5)\remote\webdriver", line 138, in start_session
File "FUCK(5)\remote\webdriver", line 194, in execute
File "FUCK(5)\remote\errorhandler", line 183, in check_response
WebDriverException: Message: unknown error: cannot parse internal JSON template: Line: 1, column: 1, Unexpected token.

Invalid: fail=True
stop
EOT: https://myreadingmanga.info/ultimate-safaripark-horiuchi-mochiko-saraba-itoshi-no-goodbye-love-boku-no-hero-academia-dj-eng/

**Comment by KurtBestor** [comment]
지금도 안 되나요?

**Comment by tlvkfka** [comment]
> 지금도 안 되나요?

네 지금도 안돼요... 같은 증상입니다.

**Comment by KurtBestor** [comment]
<kbd>Ctrl</kbd> + <kbd>Alt</kbd> + <kbd>C</kbd> 눌러서 콘솔창 열고 아래 내용 입력하고 <kbd>Enter</kbd> 눌러서 나오는 내용 보여주세요:
```
__import__('chrome').get_local_version()
```

**Comment by tlvkfka** [comment]
> Ctrl + Alt + C 눌러서 콘솔창 열고 아래 내용 입력하고 Enter 눌러서 나오는 내용 보여주세요:
> 
> ```
> __import__('chrome').get_local_version()
> ```
콘솔창 열어서 해당 명령어 입력하면 창 안뜨고 멈추네요..
제가 위에 글을 헷갈리게 잘못 썻는데,  전에 올렸던 테스트글이 안돼서
→ 1년전 다른 사람이 질문한 마리망 테스트버전을 시도했는데 안됐다는 말이였습니다.
백신이나 다른 파일 충돌 일지도 몰라서 실시간 끄고 했는데도 같습니다.

**Comment by KurtBestor** [comment]
<kbd>Ctrl</kbd> + <kbd>Alt</kbd> + <kbd>I</kbd> 눌러서 인터프리터 열고 쓰여있는 내용 모두 지운 후 아래 내용 입력하고 <kbd>Exec</kbd> 눌러서 나오는 내용 보여주세요:
```
messageBox(u'{}'.format(__import__('chrome').get_local_version()))
```

**Comment by tlvkfka** [comment]
> messageBox(u'{}'.format(__import__('chrome').get_local_version()))

(79, 0, 3945, 130) 라고 창하나 나옵니다.

**Comment by KurtBestor** [comment]
프로그램 끄고 크롬 업데이트 한 다음 다시 시도해보세요.

**Comment by tlvkfka** [comment]
> 프로그램 끄고 크롬 업데이트 한 다음 다시 시도해보세요.

최신업데이트 하고 컴퓨터 재부팅도 했는데, 
읽는중 길게 나오길래 오오 되나 했는데
똑같은 증상 뜨네요... 흑흑

**Comment by KurtBestor** [comment]
`%temp%\chrome_data` 폴더 지우고 다시 시도해보세요.

**Comment by tlvkfka** [comment]
> `%temp%\chrome_data` 폴더 지우고 다시 시도해보세요.

잘 되네요. 정말 감사합니다 :D

**Comment by monchertonton** [comment]
> `%temp%\chrome_data` 폴더 지우고 다시 시도해보세요.

죄송하지만 이 폴더 어디에 있는지 알려주실 수 있나요? 검색해도 나오지가 않아서요

**Comment by KurtBestor** [comment]
@monchertonton 윈도 탐색기 주소창에 입력해주세요.

**Comment by monchertonton** [comment]
> @monchertonton 윈도 탐색기 주소창에 입력해주세요.

찾을 수 없습니다 라는 알림창만 뜹니다 AppData\Local\Temp 폴더에 들어가서 찾아봐도 크롬 데이터 폴더는 없네요

**Comment by KurtBestor** [comment]
https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/1691
