### ISSUE TITLE
다운로드 경로 설정 질문

### ISSUE THREAD

**Issue by kyk7523** [KurtBestor/Hitomi-Downloader-issues#164]
프로그램의 기본 다운로드 위치가 내 문서 안에 히토미 다운로드 폴더인데

이걸 임의의 경로로 설정을 하고 저장 한 뒤에 종료까지 했는데...

다시 프로그램 실행하면 경로가 처음으로 바뀌여있어요...

이게 계속 이러는데 뭐가 문제인가요..

**Comment by KurtBestor** [comment]
Ctrl + S 눌러서 저장하거나
종료할 때 [저장 & 종료] 눌러서 종료하세요.
