### ISSUE TITLE
유튜브 다운로드 문제

### ISSUE THREAD

**Issue by KFromage** [KurtBestor/Hitomi-Downloader-issues#1666]
유튜브에서 한 채널 주소를 입력해서 그 채널에 있는 총 9개의 영상을 받는 작업을 했습니다.
영상 다운로드가 100%가 된 후 변환 중... 이라는 글자가 떳고, 그 다음으로 진행이 되지 않습니다.

다운로드 폴더에 들어가 보면 tmp7B044173_a.weba , tmp7B044173_v.mp4 와 같이 임시 파일명으로 영상 자체는 저장되어 있었고, mp4 파일은 재생 문제는 없었으나 소리가 빠져 있습니다. (각 영상 길이는 30분 이하였습니다.)

어떻게 하면 문제를 해결할 수 있는지 알려주세요.

**Comment by KurtBestor** [comment]
10분 이상 기다렸나요?
