### ISSUE TITLE
저장 실패

### ISSUE THREAD

**Issue by Yoon0618** [KurtBestor/Hitomi-Downloader-issues#1674]
![image](https://user-images.githubusercontent.com/36811336/74583980-a966b200-5010-11ea-8251-3dbe88dfc90f.png)

추가로 작업 갯수는 1600개입니다,,

**Comment by KurtBestor** [comment]
메모리가 부족해서 그런데, 작업 일부를 삭제해서 목록을 줄여주세요.
`작업` - `선택된 작업들 내보내기...` 로 일부분을 `*.hdt` 파일로 백업할 수 있어요.
