### ISSUE TITLE
히토미 다운로더로 받은 자료들 제목을 바꿔도 작가추천 데이타로 가나요?

### ISSUE THREAD

**Issue by gensousuikoden** [KurtBestor/Hitomi-Downloader-issues#169]
전 다운 받은것들 압축파일로 바꾸고 제목도 제가 분류하기 편하게 바꿔놓는데
그렇게 해도 작가추천 눌렀을때 데이터로 읽히나요?

**Comment by KurtBestor** [comment]
[123] 이나 (123) 같이 괄호 안에 숫자가 들어있는 형태로 폴더명이나 압축파일명에 포함되어있어야해요. 그렇지 않으면 읽히지 않아요.

작품 목록을 저장하거나 불러오려면 다음 버튼들을 사용하면 돼요:
![rec](https://user-images.githubusercontent.com/14768120/42922547-fa727d3a-8b5b-11e8-9665-fa46d6788977.png)
