### ISSUE TITLE
클립보드에서 자동추가 기능 불안정성

### ISSUE THREAD

**Issue by siegfried2p** [KurtBestor/Hitomi-Downloader-issues#17]
위기능을 사용해서
갤러리들을 빠르게 여러개 추가할시 중간중간 인식을 못하고 무시되는 현상이 있습니다

**Comment by KurtBestor** [comment]
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

일단 추가할 때 부하를 줄이고 클립보드를 타이머로 일일히 체크하는 게 아닌, 이벤트방식으로 바꿨습니다.
이벤트 방식은 백신이 후킹으로 오진할까봐 꺼려했었는데, 해보니 별문제 없는 것 같네요.
테스트 부탁드려요.

**Comment by siegfried2p** [comment]
프리뷰 버전을 쓰면 하나라도 갤러리 추가시 잠깐 프리징후 작동 중지 알림창이 뜹니다
윈도우10 프로 x64 입니다

**Comment by siegfried2p** [comment]
테스트 샘플이 좀 부족하긴 하지만 지금은 잘 작동하는거 같습니다

**Comment by KurtBestor** [comment]
해결된걸로 보고 닫습니다
