### ISSUE TITLE
기능 건의  및 에러에 대한 질문

### ISSUE THREAD

**Issue by wpfhfpr** [KurtBestor/Hitomi-Downloader-issues#170]
![default](https://user-images.githubusercontent.com/40918484/42951212-ac78f1b8-8bb0-11e8-836d-e15909d3db15.PNG)

안녕하세요 제작자님 날 더우신데 몸 잘 관리하시고 계신가요

다름아니라 에러가 계속 뜨는 데 이에 대한 원인을 아시는지 해서 여쭤보고 싶은 것과 개인적으로 기능 개선에 대한 건의를 드릴까합니다.

캡처한 것과 같은 에러가 계속 뜨게 되는 데 이게 뜨는 상황이 제가 예상하기론
1. 보통 대용량 혹은 대량의 작품을 받을 경우 ..300개나 500개를 다운받게 켜놓고 자는 경우 아침에 일어나보면 오류가 발생하고 있네요.하지만 50개일 때도 뜨는 경우가 있어 애매하긴 하지만..보통 많이 받으면 뜨는 것 같습니다.
2. 하드용량과 관계가 있는 거 같기도 하네요. 하드가 꽉 차서 에러가 난 적이 있어서 그러려니 했지만
지금 20~30기가 이상 남았는데도 간헐적으로 꺼지는 경우가 발생하네요.

해결을 못하더라도 어쩔수 없지만 혹시 아시나 해서 여쭤봅니다.
버전은 가장 최근 테스트 했던 테스트버전입니다
기능 개선 건의에 대해서도..

1. 일시정지 기능
   다운로더의 경우 추가하면 무조건 다운을 받게 되있어서 정지를 시키기 위해서는 저장 및 종료로 밖에 안되더라구요. 하드에 다운받으면 그 드라이브에서 액세스가 느려지기도하고 인터넷도 느려져서 가끔 일시정지하고 싶은데 없어서 끄는 방법밖에 없던 게 조금 아쉬웠습니다.

2. 검색기 작품 목록 썸네일에 뜰 목록 설정
말이 좀 어렵긴한데 요는 검색기에서 작품을 검색하면 썸네일에 언어, 제목 , 작가 , 캐릭터명 ,태그 이런식으로 나열되어있는데 이를 보고 싶은 항목만 설정해서 보여지게 되면 좀더 검색에 용이하지 않을까 합니다.
현재는 검색하면 

--------------------------------------------------------------------- 
썸네일 |                                     제목                                                    |
            |    작가                                                                  언어            |
            |    캐릭터 시리즈                                                   페이지 수   |      다운        다운 후 제거   제거
            |           태그                                                                              |
---------------------------------------------------------------------

이런식인데 이 보여지는 항목을 설정할 수 있으면 어떨까합니다.
원하는 항목(그룹,작가,페이지수, 등등) 이런식으로요.

이 아래부터는 개인적인 소망입니다 안되도 괜찮아욧 ㅠㅠ!

3. 다운로더 필터에서 dup: 을 구현해주셔서 잘 사용하고 있습니다. 다만 중복된것이 리스트에 표시되는 건 좋은데 어떤 게 중복됬는 지 확인하기 어려울 때가 있습니다.
중복된 것을 리스트에서 제거하기 위해서 dup: 필터를 사용하는데요.
다행히 짝수로 딱 맞아떨어질경우 절반정도 위치에 보면 중복되는 것들이 보여서 한번에 제거하기 편합니다. 다만 홀수로 떨어질경우는 어떤게 중복됬는 지 확인하기 어려워지네요 ㅠ
그래서 이건 희망사항입니다만..어차피 중복리스트이므로 다운로드가 시작되도 중복이면 스킵이 되게끔 구현해주셨는데 (감사합니다 ) 필터링이든 기능이든 중복되는 파일이 존재할 경우 한개의 리스트를 제외하고 나머지 중복 작품을 제거하는 기능이 구현될 수 있을까요?
흔히 중복제거 프로그램 처럼 말이죠.

4. 폴더 뿐만아니라 압축된 것 중복되면 스킵되는 기능 매우 감사합니다.
이건 진짜로 가능한지 궁금한 ㅠ 내용이네요.
다운로드 받는 폴더에 원본파일을 바로가기로 설정해놓아도 똑같이 스킵되게끔 실현할 수 있을까요?
제가 해봤을땐 역시나....... .lnk로 인식하는지 새로 받더군요 ㅠㅠ

여차저차 엄청 말이 길어졌네요 ㅠ 좋은 하루되세요

**Comment by wpfhfpr** [comment]
제목
작가                                                                                   언어                      다운     다운 후 제거   제거
캐릭터                                                                              페이지 수

**Comment by KurtBestor** [comment]
목록 길이가 꽤 긴데, 작업 900개 이상은 메모리 부족으로 오류 뜰 수 있어요.

1. 구현했어요.
2. 굳이 넣을만한 기능은 아닌 것 같아서 일단 보류할게요.
3. 이제 중복된 것이 하나만 남게 되면 자동으로 목록에서 사라지게 했어요.
4. 가능하긴 하겠는데, 굳이 넣을만한 기능은 아닌 것 같아서 일단 보류할게요.

https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview
테스트 부탁드려요.

**Comment by wpfhfpr** [comment]
메모리 부족은 램 용량과 관계가 없나보네요 ㅠ 64기가인데 한도가 있나보군요.

테스트결과입니다!

1,3 번 기능 정상 작동합니다.
정말 감사합니다!

4번 기능에 대해 구현하려면 파이썬으로 수정을 하면 되는걸까요..?
그리고 필터에 대한 단축키를 설정할 수 있을까요?
한글문서나 탐색기에서 CTRL+F하면 찾기가 되듯이요 
현재는 작가 탐색기가 뜨는 것으로 알고 있지만요

**Comment by KurtBestor** [comment]
네, 32비트 프로그램이라 2기가 정도가 한계예요.

필터는 F3 키로 열고 닫을 수 있어요.

네, 바로가기 인식은 코드 직접 수정해서 쓰셔도 될 것 같아요.

그룹 검색도 되게 수정했어요.
자세한 사용방법은 도움말 - 사용법... (F1) - 검색기 목록 필터링을 참고해주세요.
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview
테스트 부탁드려요.

**Comment by wpfhfpr** [comment]
글을 올리고 보니 F3이 필터키였군요.
32비트로 설계된것은 어쩔 수 없군요 ㅠ 64비트랑은 다르니..
테스트 결과로는 변함없던 것 같습니다. 
이유는 전의 테스트 버전에서 group: 이런식으로는 명령어가 먹혔던 것으로 보이지만
작가의 이름을 검색할 경우는 artist: 이런식으로 하지 않아도 잘 작동됬으나 그룹의 경우는 group:이라는 명령어가 필요했다는 점이 였는데 두 버전 모두 그룹은 group:을 쳐야 작동을 하는 군요 ㅠ

바로가기 인식을 코드로 수정하려고 하는데..파이썬은 리눅스에서 안테나 모듈을 처리하는데 사용한 적밖에 없어서 지식이 많이 없네요 ㅠ 디컴파일을 해야 내부를 볼 수 있을 것 같은 데 간단히라도 설명해주실수 있을까요? 리눅스 환경에서 해야하는지 단순히 윈도우에서 가능한지..
디컴파일러도 아무거나 써도 상관없는지 궁금합니다

**Comment by KurtBestor** [comment]
group: 입력하지 않아도 되게 바꿨는데요, 다시 확인해보니 저는 잘되네요. 다시 확인해주실 수 있나요?

다음 참고해서 PYO파일 추출하고: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/46
PYO파일을 디컴파일하면 됩니다. 여러가지 파이썬 디컴파일 라이브러리가 있으니 아무거나 골라서 쓰세요. 참고로 Python2로 개발했으니 Python2를 지원하는 디컴파일러 쓰셔야합니다.

**Comment by wpfhfpr** [comment]
감사합니다!!

**Comment by KurtBestor** [comment]
> 다음 참고해서 PYO파일 추출하고: #46
> PYO파일을 디컴파일하면 됩니다. 여러가지 파이썬 디컴파일 라이브러리가 있으니 아무거나 골라서 쓰세요. 참고로 Python2로 개발했으니 Python2를 지원하는 디컴파일러 쓰셔야합니다.
