### ISSUE TITLE
데이터 갱신이 안되는 문제

### ISSUE THREAD

**Issue by csr5487** [KurtBestor/Hitomi-Downloader-issues#1702]
예상하기로는 검색 범위의 최대값이 1574800인데 현재 업데이트 되고 있는 자료들 품번이 그 이상으로 늘어나서 검색이 안되는것같습니다.

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/1693
