### ISSUE TITLE
픽시브는 다운이 되는데 트위터는 다운로드가 안되네요

### ISSUE THREAD

**Issue by jaejunghan** [KurtBestor/Hitomi-Downloader-issues#171]
![20180720_100718](https://user-images.githubusercontent.com/41049446/42977912-ef080f06-8c04-11e8-952e-eee81a35fd6a.png)
![20180720_100811](https://user-images.githubusercontent.com/41049446/42977917-f2de7548-8c04-11e8-8594-d2bdfef40bdb.png)
![20180720_100844](https://user-images.githubusercontent.com/41049446/42977918-f492fc88-8c04-11e8-8154-c45a261d3b09.png)

**Comment by KurtBestor** [comment]
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

테스트 부탁드려요.

**Comment by jaejunghan** [comment]
![20180720_125413](https://user-images.githubusercontent.com/41049446/42982396-23d7749e-8c1c-11e8-808f-8818af60295e.png)
3개중에 1개는 되고 나머지 2개는 안되네요
![20180720_125616](https://user-images.githubusercontent.com/41049446/42982453-597819fa-8c1c-11e8-95b3-e729d39e027a.png)
![20180720_125634](https://user-images.githubusercontent.com/41049446/42982458-5bb154c0-8c1c-11e8-8a80-07d6289a3800.png)
