### ISSUE TITLE
2.3버전 이후로 트위터 동영상이 다운로드 되지 않습니다. 

### ISSUE THREAD

**Issue by cocoman1111** [KurtBestor/Hitomi-Downloader-issues#172]
안녕하세요. 이래저래 바빠서 제대로 확인도 못하고 그랬는데..

여전히 2.3버전 이후로는 트위터 사진만 일괄다운이 되고 영상은 제외되는 현상이 발생합니다.

같은 주소를 2.2a 버전 다운 시와 2.3d버전 다운 시의 차이점입니다.

2.3버전에서는 항상 같은 현상이 발생했습니다.

2.2a 다운 시 사진
![2 2a](https://user-images.githubusercontent.com/35674951/42991456-89d7c81a-8c40-11e8-87a2-ef5251ec3738.PNG)

2.3d 다운 시 사진
![2 3d](https://user-images.githubusercontent.com/35674951/42991494-aee18cc2-8c40-11e8-9758-b16e92661e00.PNG)

**Comment by KurtBestor** [comment]
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

테스트 부탁드려요.

**Comment by cocoman1111** [comment]
엥? 위험하다면서 다운로드가 안되는데요;;; 다른 릴리즈를 다운받으면 잘 다운되는데...
링크있는걸 받으니 브라우저가 차단해버리는데.. 어떡하죠??

**Comment by KurtBestor** [comment]
https://drive.google.com/open?id=1SQsQWFK-Mdth5fFNHDQH-eEmAd6KSwou

이건 어때요

**Comment by cocoman1111** [comment]
똑같네요,, 갑자기 왜지... 브라우저가 차단을 해버려요 ㅜㅠ
쓰는 건 크롬입니다

**Comment by KurtBestor** [comment]
다른 브라우저로 다운로드해보세요.
