### ISSUE TITLE
consultation in the form of a request (?

### ISSUE THREAD

**Issue by Rocneriano** [KurtBestor/Hitomi-Downloader-issues#1729]
I wanted to ask if there's any way to download all the images from a private Instagram account.
Or if you could add that function in some Hitomi Downloader update, maybe by logging in with our Instagram account as with pixiv?

**Comment by KurtBestor** [comment]
Try the test version:
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

You can load cookies to access private accounts in here:
- `Options` - `Preferences...` - `Advanced setting` - `Cookies` - `Load`
