### ISSUE TITLE
익헨 제목으로 저장하는 기능 만들어주셔서 감사합니다

### ISSUE THREAD

**Issue by fdsa1538** [KurtBestor/Hitomi-Downloader-issues#1734]
그런데 익헨 제목으로 저장하는 글자 수에 한계가 있어서 제목이 짤려서 다운로드 됩니다.
세어보니까 딱 100자가 나오는데 제목 긴 라노벨 같은 원작이 있는 동인지가 아니더라도 조금만 긴 제목이 붙어있는 잡지망가 마저 짤리는 경우가 종종 생깁니다.
조금만 더 여유있게 수정해주셨으면 좋겠습니다 ㅠㅠ
감사합니다!

**Comment by KurtBestor** [comment]
늘려봤자 127자인데 이전 버전과 호환을 위해서 100자 그대로 두려구요.

**Comment by fdsa1538** [comment]
한계가 있나보네요 ㅠㅠ 감사합니다
