### ISSUE TITLE
검색기 썸네일 크기 조절하게 해주세요.

### ISSUE THREAD

**Issue by KKK-Man** [KurtBestor/Hitomi-Downloader-issues#174]
썸네일이 검색하는데 굉장히 큰 비중을 차지하는 가장 중요한 정보인데
썸네일 기본 표시 크기가 너무 작습니다.

썸네일 영역을 드래그해서 원하는 사이즈로 키우거나
배율식으로 확대 표시해서 설정을 저장할 수 있으면 좋을 것 같습니다.

**Comment by KurtBestor** [comment]
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

테스트 부탁드려요.
검색기 - 옵션 - 미리보기 크기 에서 바꿀 수 있어요.

**Comment by KKK-Man** [comment]
써봤는데 아주 좋네요!!

크기 조절 단계가 여러개 있어서
자신의 취향에 맞춰서 조절 가능해서 너무 좋습니다.

정식기능으로 들어가기를 기대합니다.
