### ISSUE TITLE
삭제를 해도 삭제가 되지 않는 버그가 있습니다

### ISSUE THREAD

**Issue by didzlwhehfdl** [KurtBestor/Hitomi-Downloader-issues#175]

**Comment by KurtBestor** [comment]
프로그램 목록에서 삭제가 안 된다는 건가요, 파일이 삭제가 안 된다는 건가요?

**Comment by didzlwhehfdl** [comment]
프로그램 목록에서 삭제가 된것처럼 보이는데 다운로드 폴더를 들어가면 남아있는것들이 있어요 삭제시 휴지통으로 보냄을 체크하거나 풀어도 봤는데 삭제가 완전히 안되는게 있더라고요

**Comment by KurtBestor** [comment]
수동으로 직접 폴더 삭제하면 삭제 되나요?

**Comment by didzlwhehfdl** [comment]
네 수동으로 삭제하면 삭제가 되요

**Comment by didzlwhehfdl** [comment]
사용 중인 폴더라 삭제 안된다고 하는건 뜨지 않네요

**Comment by KurtBestor** [comment]
![thread state](https://user-images.githubusercontent.com/14768120/43175902-50bbe308-8ffc-11e8-8ff2-04b1e1d5f541.png)
프로그램 실행 중에 Shift + Esc 누르면 맨 아래에 아직 삭제하지 못한 파일들이 보여요. 프로그램이 켜져있는 동안 계속 삭제를 시도해요. 
프로그램이 켜져있는 당시에 폴더가 사용중이었기 때문에 삭제가 안 되었던 것이고, 현재는 예전에 삭제가 안 된 폴더들이 삭제가 될거예요. 만약 사용하면서 삭제되지 않은 폴더들이 있다면 프로그램을 끄지 말고 바로 수동으로 삭제 해보세요.

**Comment by didzlwhehfdl** [comment]
네 예전버전에서 삭제가 안된거일지도 모르겠네요
