### ISSUE TITLE
유투브 최신버전으로 영상을 받으면 420p로 다운이 됩니다.

### ISSUE THREAD

**Issue by catheart123** [KurtBestor/Hitomi-Downloader-issues#176]
https://www.youtube.com/watch?v=CoSW-pBGsMw

이것도 그렇고 다른 몇 몇 영상은 다운로드를 하면 계속 420p로 받는데, 수정 안될까요?

**Comment by KurtBestor** [comment]
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

테스트 부탁드려요.

**Comment by catheart123** [comment]
720으로 잘 받아집니다. 감사합니다
