### ISSUE TITLE
Pixiv Videos

### ISSUE THREAD

**Issue by BatmanPerbert** [KurtBestor/Hitomi-Downloader-issues#1760]
Hello!! Me again, I want to know if exists a way to download the mp4 files (videos) from Pixiv because when I download it, it appears like a .rar file and when I extract it there are just the images...

**Comment by KurtBestor** [comment]
It automatically converts to WEBP or GIF format when the download is completed. You can change the option in here: `Options` - `Preferences..`. - `Pixiv Setting` - `Ugoira` - `Format`

**Comment by BatmanPerbert** [comment]
Thank You!
