### ISSUE TITLE
404 페이지 다운이안됩니다

### ISSUE THREAD

**Issue by Lnmi** [KurtBestor/Hitomi-Downloader-issues#177]
히토미는 아니고 익헨입니다

ip벤이 아닐때도 다운이안됩니다

**Comment by KurtBestor** [comment]
해당 링크 알려주실 수 있나요?

**Comment by Lnmi** [comment]
링크는 아니고 버그인듯합니다
다운받다가 도중에 끄거나 혹은 다운받다 ip벤먹고 아이피 바꿔서 다운받으려고해도 다운이 안되네요

**Comment by Lnmi** [comment]
해결되었습니다 늦게 이야기해서 죄송합니다 ㅎㅎ
