### ISSUE TITLE
유튜브 프리미엄 영상은 mp3파일등으로 받을수 없나요?

### ISSUE THREAD

**Issue by inchaos4315** [KurtBestor/Hitomi-Downloader-issues#1777]
유튜브 프리미엄 이용중인데

특정 음원을 한국에선 구하기 몹시 어려워서

다운받아서 들으려 했더니

프리미엄 동영상이라 받을수가 없네요

유튜브 계정 등을 로그인해서 받는 방법등은 없나요?

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/1680
