### ISSUE TITLE
장편을 검색할수 있도록 100p이상 따로 검색기능 추가 건의드립니다

### ISSUE THREAD

**Issue by cul9** [KurtBestor/Hitomi-Downloader-issues#178]
쁘니거니드립니다

**Comment by KurtBestor** [comment]
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

테스트 부탁드려요.
아래와 같이 필터링 하면 돼요:
![filter_p](https://user-images.githubusercontent.com/14768120/43378405-b150c036-9401-11e8-849e-f963c24b9c8a.png)
