### ISSUE TITLE
글자 깨짐 & 이미지 로딩 문제 

### ISSUE THREAD

**Issue by aria1th** [KurtBestor/Hitomi-Downloader-issues#179]
![image](https://user-images.githubusercontent.com/35677394/43356244-d1f43ba2-92a7-11e8-8bc4-1d9c632aaf0b.png)

![image](https://user-images.githubusercontent.com/35677394/43356256-eb66893c-92a7-11e8-875b-9cad1710b83a.png)

이렇게 됩니다

**Comment by KurtBestor** [comment]
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

테스트 부탁드려요.
