### ISSUE TITLE
기본 데이터 팩은 히토미 몇 페이지 까지 로드 하는건가요?

### ISSUE THREAD

**Issue by XeonEXP** [KurtBestor/Hitomi-Downloader-issues#182]
기본 데이터 팩은 히토미 몇 페이지 까지 로드 하는건가요?

단순 궁금증이며 끝까지 로드 하는건지 아니면 제한이 걸려있는건지 궁금 합니다.

**Comment by KurtBestor** [comment]
끝까지 로드해요

**Comment by XeonEXP** [comment]
@KurtBestor 흠...그렇군요...

그러면 1000개 이하로 로드 되거나 양이 적으면 렉이 안심해서 다운로드를 쉽게 걸긴 합미다만...

양이 많을경우 프로그램이 계속 렉을 먹고있더군요...
 - 이건 최적화를 더 하셔야 하는 문제인가요?

그리고 검색해서 나온 동인지에 대해서 수동으로 누르는게 아니라 전체로 다운 받고 삭제 하는 기능도 있었으면 좋겠습니다.

단일 다운도 누르면 된다지만 양이 많을 경우엔 불편한 감이 있어요.

**Comment by KurtBestor** [comment]
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

현재 테스트 버전은 1000개씩 끊어서 검색해요. 다음 버전에 적용될거예요.
마우스 우클릭 후 [모두 선택] 한 뒤에 Enter 누르면 모두 다운로드돼요.
최적화는 충분히 했다고 생각해요. 리스트가 길 때 추가하는 데 시간이 많이 걸리는 문제는 GUI 프레임워크인 Qt 자체 문제입니다.
