### ISSUE TITLE
사이트 추가 건의 드립니다 -디시인사이드

### ISSUE THREAD

**Issue by guuhar** [KurtBestor/Hitomi-Downloader-issues#1824]
https://gall.dcinside.com/
https://gall.dcinside.com/board/lists/?id=comic_new2
https://gall.dcinside.com/board/lists/?id=cartoon

은근히 만화 번역이나 창작 게재가 많이 되는 사이트인데 글삭제가 상당히 불규칙적으로 이루어지고 검색기능도 빈약해서 검색해서 다시보기가 힘들어 다운로드를 받아두고싶은 글이 많은데 원본을 일괄다운받을 방법이 없어서 히토미다운로더에 추가가 되었으면 좋겠습니다

**Comment by Yoon0618** [comment]
디시는 스크립트로 가능합니다

![image](https://user-images.githubusercontent.com/36811336/77830430-b62c0900-716b-11ea-9168-c8df91255494.png)

**Comment by guuhar** [comment]
스크립트가 있었군요 감사합니다!
