### ISSUE TITLE
다운로더 일정 이상 내려받기시 튕김 문제

### ISSUE THREAD

**Issue by Aleady-taken** [KurtBestor/Hitomi-Downloader-issues#183]
누적 1885개 정도쯤 받은 상태에서 켜서 모든 목록 불어오기가 끝나자 마자, 혹은 무사히 로딩되어 켜진 상태에서도 5~6개 받으면 오류 메시지도 없이 갑자기 꺼지거나 검색창에서 버튼 눌러도 검색이 안 되네요. 다시 기본 데이터 다운로드 받으면 No data라고 뜨기도 하고요.  램은 8기가를 사용하고 있고, 실시간 메모리 사용량을 봐도 문제는 없는데 무슨 문제일까요?

**Comment by KurtBestor** [comment]
프로그램이 32bit 프로그램이라 발생하는 문제예요.

900개 이상은 권장하지 않아요. 참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/170
