### ISSUE TITLE
인스타 다운로드 오류 뜨네요.

### ISSUE THREAD

**Issue by pkpkyuyu** [KurtBestor/Hitomi-Downloader-issues#184]
![2018-08-02](https://user-images.githubusercontent.com/42033068/43580453-7a73ad12-9690-11e8-912b-86a9edbc1d8a.png)

이렇게 뜨면서 다운로드가 계속 안되네요. 도움 부탁드립니다~

**Comment by KurtBestor** [comment]
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

테스트 부탁드려요.

**Comment by pkpkyuyu** [comment]
되네요! 감사합니다.
기존 프로그램은 삭제해도 되는건가요?

**Comment by KurtBestor** [comment]
@pkpkyuyu  네. 기존 프로그램에 덮어씌우시면 돼요.
