### ISSUE TITLE
폰헙 프리미엄 다운로드 이슈 문의.

### ISSUE THREAD

**Issue by bdpx-png** [KurtBestor/Hitomi-Downloader-issues#1845]
문제 -
[Pornhub] Login cookies required가 쿠키를 추가해도 뜨는 현상.

제가 해본것.

1. 테크니컬 프리뷰 다운로드. - 안됨
2. 사용하는 브라우저를 통하여 폰헙 프리미엄의 쿠키 불러오기. - 안됨
3. 사용하는 브라우저를 통하여 폰헙의 쿠키 불러오기. - 안됨
4. 사용하는 브라우저의 모든 쿠키 불러오기. - 안됨
5. 다운로더의 설정 저장 파일 삭제후 쿠키 불러오기. - 안됨

다른분들께서 발행하신 이슈를 찾아봐도 안되더라구요.

또한 기존의 폰헙에서 사용 가능했던 브라우저 확장 프로그램이 프리미엄 동영상에서는 먹히지 않는다는 것을 깨달았습니다.

[Pornhub] Login cookies required

version: 2.8 (20-04-01 09:09:14 GMT+0)
platform: Windows-10-10.0.18362
order: 4
group: False
gal_num: https://www.pornhubpremium.com/view_video.php?viewkey=ph5c8a9596441e0
dir: 
zip: 
type: pornhub
artist: None
url: https://www.pornhubpremium.com/view_video.php?viewkey=ph5c8a9596441e0
valid: False
done: True
range: None
range_p: None
single: True
time: 1585737231.1 (Apr 1)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
stop
Invalid: fail=False
stop
EOT: https://www.pornhubpremium.com/view_video.php?viewkey=ph5c8a9596441e0

stop
Invalid: fail=False
stop
EOT: https://www.pornhubpremium.com/view_video.php?viewkey=ph5c8a9596441e0

**Comment by KurtBestor** [comment]
폰허브 프리미엄 계정이 없어서 테스트 해볼수가 없는데 주시면 테스트 해볼게요.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by bdpx-png** [comment]
> 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

잘 됩니다. 감사합니다.
