### ISSUE TITLE
유튜브 영상을 mp3로 다운받을 시 Fail 에러가 발생합니다

### ISSUE THREAD

**Issue by techromancer789** [KurtBestor/Hitomi-Downloader-issues#186]
https://youtu.be/031RCfNvqDQ
https://youtu.be/Efhd9W9KovA
위 링크는 에러가 발생하는 예입니다
모든 영상에서 에러가 뜨는것은 아니고 몇몇 영상들에 한해서 Fail 에러가 뜨는것같네요
설정에서 mp4로 설정할 시 정상적으로 다운로드 되고 mp3로 설정할 시 에러가 발생합니다

**Comment by KurtBestor** [comment]
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

테스트 부탁드려요.

**Comment by techromancer789** [comment]
아주 잘되네요 늘 감사합니다
