### ISSUE TITLE
gelbooru 다운로드가 2000장을 초과해서 다운로드 되지 않습니다

### ISSUE THREAD

**Issue by yuchan39** [KurtBestor/Hitomi-Downloader-issues#1875]
#1185에서 Sankaku가 사이트 제한때문에 2000장 초과해서 다운이 안된다고 하셨는데

gelbooru도 사이트 자체에서 제한을 걸어서 

2000장을 넘어가는 tag가 2000장 밖에 다운이 안되는 건가요?

gelbooru에서 tag를 kochiya_sanae로 검색하면 페이지가 477장을 넘어갔을때

Unable to search this deep due to coding limitations. 라고 뜨면서 더이상 검색이 안되는데

2000장만 다운되는게 coding limitations이랑 관련이 있는 건가요?

https://gelbooru.com/index.php?page=post&s=list&tags=kochiya_sanae&pid=19992

kochiya_sanae

version: 2.8 (20-03-27 19:50:23 GMT+0)
platform: Windows-10-10.0.18362
order: 1
group: False
gal_num: https://gelbooru.com/index.php?page=post&s=list&tags=kochiya_sanae&pid=19992
dir: hitomi_downloaded_gelbooru\kochiya_sanae
zip: 
type: gelbooru
artist: None
url: https://gelbooru.com/index.php?page=post&s=list&tags=kochiya_sanae&pid=19992
valid: True
done: True
range: None
range_p: None
single: False
time: 1586310100.9 (Apr 8)
tags: []
goodbyedpi: False
lock: False
color: done
paused: False
format: None
p2f: None

[Messages]
https://gelbooru.com/index.php?page=dapi&s=post&q=index&tags=kochiya_sanae&pid=0&limit=100
https://gelbooru.com/index.php?page=dapi&s=post&q=index&tags=kochiya_sanae&pid=1&limit=100
https://gelbooru.com/index.php?page=dapi&s=post&q=index&tags=kochiya_sanae&pid=2&limit=100
https://gelbooru.com/index.php?page=dapi&s=post&q=index&tags=kochiya_sanae&pid=3&limit=100
https://gelbooru.com/index.php?page=dapi&s=post&q=index&tags=kochiya_sanae&pid=4&limit=100
https://gelbooru.com/index.php?page=dapi&s=post&q=index&tags=kochiya_sanae&pid=5&limit=100
https://gelbooru.com/index.php?page=dapi&s=post&q=index&tags=kochiya_sanae&pid=6&limit=100
https://gelbooru.com/index.php?page=dapi&s=post&q=index&tags=kochiya_sanae&pid=7&limit=100
https://gelbooru.com/index.php?page=dapi&s=post&q=index&tags=kochiya_sanae&pid=8&limit=100
https://gelbooru.com/index.php?page=dapi&s=post&q=index&tags=kochiya_sanae&pid=9&limit=100
https://gelbooru.com/index.php?page=dapi&s=post&q=index&tags=kochiya_sanae&pid=10&limit=100
https://gelbooru.com/index.php?page=dapi&s=post&q=index&tags=kochiya_sanae&pid=11&limit=100
https://gelbooru.com/index.php?page=dapi&s=post&q=index&tags=kochiya_sanae&pid=12&limit=100
https://gelbooru.com/index.php?page=dapi&s=post&q=index&tags=kochiya_sanae&pid=13&limit=100
https://gelbooru.com/index.php?page=dapi&s=post&q=index&tags=kochiya_sanae&pid=14&limit=100
https://gelbooru.com/index.php?page=dapi&s=post&q=index&tags=kochiya_sanae&pid=15&limit=100
https://gelbooru.com/index.php?page=dapi&s=post&q=index&tags=kochiya_sanae&pid=16&limit=100
https://gelbooru.com/index.php?page=dapi&s=post&q=index&tags=kochiya_sanae&pid=17&limit=100
https://gelbooru.com/index.php?page=dapi&s=post&q=index&tags=kochiya_sanae&pid=18&limit=100
https://gelbooru.com/index.php?page=dapi&s=post&q=index&tags=kochiya_sanae&pid=19&limit=100
stop
EOT: https://gelbooru.com/index.php?page=post&s=list&tags=kochiya_sanae&pid=19992

다운로더 잘 쓰고 있습니다. 감사합니다.

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/382#issuecomment-450846793

**Comment by yuchan39** [comment]
혹시 질문이 중복되었을까봐 issue들을 찾아 본 후에 질문드렸었는데 같은 내용의 issue가 있는 줄 몰랐습니다. 다음부터는 좀 더 찾아보고 질문드리겠습니다. 다운로더 잘 쓰고 있습니다. 감사합니다.

**Comment by yuchan39** [comment]
혹시 질문이 중복되었을까봐 issue들을 찾아 본 후에 질문드렸었는데 같은 내용의 issue가 있는 줄 몰랐습니다. 다음부터는 좀 더 찾아보고 질문드리겠습니다. 다운로더 잘 쓰고 있습니다. 감사합니다.
