### ISSUE TITLE
몆가지 건의드립니다.

### ISSUE THREAD

**Issue by buntail** [KurtBestor/Hitomi-Downloader-issues#188]
1. 특정히 지정한 태그or타잎은 받을시 파일뒤에 따라붙었으면좋겠습니다.

*태그

저같은경우 # artist / title 를 주로쓰는데 여기에 저 기능이 추가된다면

예를들어 yuri, yaoi, loli, mlif 태그를 지정해둔채로 어떤 작품을 받았는데 10여개의 태그중 yaoi를 제외한 

세 태그가 일치시 # artist / title(태그)  즉 결과는 작가명 폴더안에 타이틀(yuri, mlif, loli)  이런식으로 나오겠죠. 

(male, female 구분까지는 필요없을것같네요)

이 기능이 필요하다고 느낀이유는 저는 많은 동인/상업지를 받아두고 골라보는데 

재가 나름 필터링해서 모은다고쳐도 굉장히 많은자료이고 이걸 전부 기억은 못하며 가끔씩 찾아봅니다만

찾고싶은 작품이 생각이 안날시 정말 짜증납니다. 이럴경우 이기능이있다면 찾기가 굉장히 편하겠죠.

보통 오리지널작품or시리즈가 기억안나고 인기있는 태그가 끼어있고 그림체만 기억나는 작품들이 까다롭습니다. 검색

다운로더의 검색기를 워낙 잘만들어두셔서 검색기자체로도 찾을수있겠지만 위에 예시로든것처럼 

몆몆 작품들은 저런기능이 없다면 필터내 수백작품중에서 찾아봐야하며 심지어 몆몆작품은 필터가 

재대로 안적혀있어 더욱더 곤란한상황도 많이오더군요 이럴떄 저런기능이 있었다면 자신의 다운로드폴더 내에서 자체검색기를 돌려서 찾을수 있겠죠.(전 Everything 검색기를 주로 씁니다.)

*타잎

위에 연장선입니다. 단행본은 이미 태그로 있지만 아티스트CG는 태그가 아닌 타잎으로 분류되죠

개인적으로 특정 타잎도 태그처럼 추가해두면 제목뒤에 붙었으면 합니다. 

이경우는 # artist / title (태그) (타잎) 즉 결과는 작가명 폴더안에 타이틀(ArtistCG) 이런식이겠죠?

2. ETC 폴더의 간략화 기능 추가요청.

이기능은 필요하다싶은데 어떻게 수정해야할지 저도 감이안잡힙니다. 

주로 언어로 한국어만 넣고 돌리는경우에도 자주 생기는 녀석들이죠; 다중작가떄문인데....이경우는 제외하더라도

적어도 검색기에 넣은 작가or그룹명이 있다면 이걸로 통일되어 들어갔으면 좋겠습니다. 

작가 하나 검색기돌려서 쭈~욱 받는데 가끔 찾던게 없어서 이리저리 뒤져보면 ETC에 있는경우가 많아요

저같은경우 관리를 너무안했는지 ETC폴더만 147개네요...

3. 검색 결과값에서 오른클시 작품명 복사 요청

개인적으로 갤러리넘버복사가 왜 필요한지 잘 모르겠습니다. 오히려 이자리에 작품명 복사가 있어야하지않나요? 

같은 작품이여도 여러개가 있죠. 언어때문일수도있고 언어가 동일해도 사실상 같은 작품 같은 언어가 올라와있는경우도있고 리사이징일수도있고...등등

즉, 재가하고싶은말은 작품명이 갤러리넘버보다 훨씬더 정확하다는겁니다. 

주로 자신이 받았나 안받았나 긴가민가한작품을 검색해보곤하는데 이떄 항상 갤러리정보를 눌러서 마우스로 긁고 복사해서 찾아야했습니다....

다른분들이 이 기능을 어떻게사용하는지 모르곘네요..심지어 링크열기라는 아주좋은기능까지있는데말이죠

**Comment by KurtBestor** [comment]
1. [옵션 (Options) - 설정 - 히토미 - 갤러리 정보 텍스트 파일로 저장] 체크하면 폴더에 info.txt 파일이 만들어집니다. [FindInFiles](http://toolscode.com/findinfiles/) 같은 프로그램으로 태그 검색하면 돼요. 폴더명 형식은 # artist / title (type) 와 같이 하면 타입이 붙게됩니다.

2. 이것도 [갤러리 정보 텍스트 파일로 저장] 체크하고 다운로드 한 후에 검색하시면 될 것 같아요.

3. 갤러리 넘버 복사는 다음 요청으로 넣은 기능이예요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/138

제목 복사는 추가했어요. 테스트 부탁드려요:
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview
