### ISSUE TITLE
건의사항이 있습니다.

### ISSUE THREAD

**Issue by miraclehoshi** [KurtBestor/Hitomi-Downloader-issues#19]
![image](https://user-images.githubusercontent.com/35333519/34823772-3274a7f8-f70f-11e7-8160-8a966675d2f1.png)

검색 기능을 사용하는데 있어, 해당 동인지가 무슨 태그를 가지고 있는지 알 수 없습니다.
예를들어 위의 사진에서는 Miko, Mind Control 등이 히토미 사이트에는 표기되므로
쉽게 태그를 확인해 보고 넘어가거나 선택해 다운로드 받을 수 있지만
검색기에서는 내부 공간이 넓은데도 불구하고 태그나 정보등을 보려면 이미지를 클릭해야 하는 점이 불편합니다.

내부에 태그, 그룹, 타입을 선택 가능하게끔 옵션을 제공해 주었으면 합니다.
항상 사용하며 감사함을 느끼고 있습니다. 잘 부탁 드립니다.

**Comment by KurtBestor** [comment]
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

해당 기능 넣어봤습니다.
테스트 부탁드려요.

**Comment by KurtBestor** [comment]
v2.0에 해당 기능 추가됨
