### ISSUE TITLE
적용시킨 스크립트를 제거하는 방법은 없나요?

### ISSUE THREAD

**Issue by inchaos4315** [KurtBestor/Hitomi-Downloader-issues#1903]
이전에 지원하던 호두코믹스 관련 스크립트가

더 이상 지원되지 않는다고 들었는데

다운로더 내부에서 스크립트 적용 알림이 뜨는게 불편해서요

새로 다운 받기에는 일일히 세세한 설정을 다시하기 번거로워서 그런데

적용시킨 스크립트를 제거하거나

또는 설정파일을 따로 내보내서 저장할 수 없을까요?

**Comment by KurtBestor** [comment]
재시작하면 스크립트는 모두 초기화돼요.

`scripts` 폴더에 스크립트 넣은 거면 해당 스크립트 파일을 지우세요. `도움말` - `사용법 (F1)` - `스크립트` 참고해주세요.

**Comment by inchaos4315** [comment]
감사합니다
