### ISSUE TITLE
deviantart 일부 계정의 갤러리 다운로드가 안되는 문제

### ISSUE THREAD

**Issue by zephy8181** [KurtBestor/Hitomi-Downloader-issues#191]
현재 2.4 업데이트 후 사용중입니다.
(이슈가 따로 없어서 남기게 되었습니다.)
deviantart 사이트에서 다운로드 받을 시,

https://username.deviantart.com
deviant_username

사용법대로 위와같은 주소를 입력, 다운을 똑같이 시도하지만 
어떤 계정은 풀 갤러리가 다운받아지고,
어떤 계정은 풀 갤러리가 다운받아지지 않습니다.

예를 들어서, 현재 mostlyguystock 라는 계정을 다운로드 해보시면
실제 갤러리(https://www.deviantart.com/mostlyguystock/gallery/) 에는 상당한 양의 사진이 있으나,
단 2장만 다운받아지는 것을 볼 수 있습니다.

혹시 해결방법이 따로 있는데 제가 모르는 것일까요?

**Comment by KurtBestor** [comment]
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

고쳤어요. 테스트 부탁드려요.

**Comment by zephy8181** [comment]
해결되었습니다! 늘 잘 사용하고 있습니다. 감사합니다.
