### ISSUE TITLE
최신 업데이트(2,4) 하고 히토미 다운이 안되고 있어요

### ISSUE THREAD

**Issue by yjsung1206** [KurtBestor/Hitomi-Downloader-issues#192]
서버를 익헨으로 옮겨서 다운 받다가 안돼서 다시 자동으로 바꿔놓고 했는데도 안되네요 ㅜㅜ

**Comment by KurtBestor** [comment]
알려주세요:
1. [도움말 - 정보 - 버전 확인] 눌러서 나오는 내용
2. 다운로드 실패한 작업 [마우스 우클릭 - 정보... (I)] 눌러서 나오는 내용
3. [Ctrl + Alt + C] 눌러서 콘솔 띄우고 downloader.requests.utils.getproxies() 입력하고 Enter 누른 다음 나오는 내용
