### ISSUE TITLE
웹툰다운로드 후 각 화마다 개별 압축이 가능할까요

### ISSUE THREAD

**Issue by iluzde** [KurtBestor/Hitomi-Downloader-issues#193]
다운로더 잘 사용하고 있는 유저입니다.
웹툰 다운로드 후 압축 폴더전체로 진행되는 것 같은데, 혹시 각 화 개별 압축이 가능할지 여쭈어봅니다.

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/154
