### ISSUE TITLE
히토미 다운로드가 안됩니다

### ISSUE THREAD

**Issue by qqwwee112200** [KurtBestor/Hitomi-Downloader-issues#194]
Traceback (most recent call last):
  File "customWidget.pyo", line 622, in retries
  File "customWidget.pyo", line 603, in retry
TypeError: argument of type 'NoneType' is not iterable

피드백 봐도 모르겠어서 글 올립니다

**Comment by KurtBestor** [comment]
알려주세요:
1. [도움말 - 정보 - 버전 확인] 눌러서 나오는 내용
2. 다운로드 실패한 작업 [마우스 우클릭 - 정보... (I)] 눌러서 나오는 내용
3. [Ctrl + Alt + C] 눌러서 콘솔 띄우고 ```downloader.requests.utils.getproxies()``` 입력하고 Enter 누른 다음 나오는 내용
4. 콘솔에 ```downloader.hdr``` 입력해서 나오는 내용

**Comment by qqwwee112200** [comment]
1.버전은 최신버젼

2.
대기 중... [Suzunone Rena] 猫姦～成猫編～ (1267105)

gal_num: [Suzunone Rena] 猫姦～成猫編～ (1267105)
dir: 
zip: 
type: 
artist: None
url: None
valid: True
done: False
range: None
range_p: None
single: True

3. 
downloader.requests.utils.getproxies() 

{}

4.
downloader.hdr 

{'Accept-Language': 'en-US,en;q=0.8', 'Accept-Encoding': 'none', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (X12; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36', 'Accept-Charset': 'ISO-8859-1,utf-8;q=0.7,*;q=0.3', 'Connection': 'Keep-Alive', 'Upgrade-Insecure-Requests': '1'}

**Comment by KurtBestor** [comment]
프로그램 스크린샷 찍어서 보여주세요.

**Comment by qqwwee112200** [comment]
콘솔창 말슴하시는거죠?

**Comment by qqwwee112200** [comment]
![1](https://user-images.githubusercontent.com/42193329/43816544-3b47d120-9b10-11e8-889d-94e1f1d68eab.PNG)

**Comment by KurtBestor** [comment]
다운로더 메인창이요.

**Comment by qqwwee112200** [comment]
![default](https://user-images.githubusercontent.com/42193329/43817277-90b52c72-9b13-11e8-9d81-4cdf9bab27a0.PNG)

**Comment by qqwwee112200** [comment]
![1](https://user-images.githubusercontent.com/42193329/43817282-97ee2070-9b13-11e8-869a-9a546337840c.PNG)

**Comment by qqwwee112200** [comment]
![asdf](https://user-images.githubusercontent.com/42193329/43817314-bf2eab5a-9b13-11e8-8295-a3ca46eb955a.PNG)

**Comment by KurtBestor** [comment]
![play](https://user-images.githubusercontent.com/14768120/43817342-e058faf6-9b13-11e8-88bd-99ea16f6946f.png)

이 부분 눌러서 켜주세요.

**Comment by qqwwee112200** [comment]
아 부끄러워

도와주셔서 감사합니다
