### ISSUE TITLE
네트워크 드라이브에 프로그램 넣어놓고 쓸 수 없을까요?

### ISSUE THREAD

**Issue by alskdh** [KurtBestor/Hitomi-Downloader-issues#195]
다운로드 폴더를 네트워크 폴더에 선택은 안 되는 것 같아요 ㅠㅠ

**Comment by KurtBestor** [comment]
현재는 불가능해요. 참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/88

**Comment by hdgth** [comment]
네트워크 드라이브가 지원 안되는군요..

**Comment by hdgth** [comment]
네트워크 드라이브가 지원 안되는군요..
NAS를 좀더 알차게 쓸수있을거라 생각했는데..

**Comment by hdgth** [comment]
네트워크 드라이브가 지원 안되는군요..
NAS를 좀더 알차게 쓸수있을거라 생각했는데..
==============================
컴퓨터 - 네트워크 드라이브 연결(M) 이란 메뉴를 까먹고 있었네요.
마운트해서 실행시키면 잘되네요 ^오^
![image](https://user-images.githubusercontent.com/42745813/44697275-00439900-aab6-11e8-86d5-b5466549ee70.png)
