### ISSUE TITLE
검색기 목록상태에서 십자키→로 추가하는 단축키 없어진거 아쉽네요.

### ISSUE THREAD

**Issue by KKK-Man** [KurtBestor/Hitomi-Downloader-issues#196]
아이콘 모드가 생기면서
조작키가 중복되서 없어진거 같은데

아이콘 모드와 중복되지 않게
목록상태에서는 예전처럼 →키로 추가 가능하게 할 수 없을까요?

이게 굉장히 편하게 쓰던키라 없어지니 아쉽네요.

십자키로 탐색하다 맘에들면 →딱딱 눌러서
추가하는게 참 편했는데요.
지금은 엔터키에 손가락을 놔둬야하는데 영 불편하네요. ^^;;;

**Comment by KurtBestor** [comment]
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

테스트 부탁드려요.

**Comment by KKK-Man** [comment]
잘 동작하네요.
평소에 편리하게 자주 쓰던 기능이라 아쉬웠는데
다른 기능과 충돌되거나 키중복으로 꼭 없애야하는거 아니면
유지시켰으면 하는 기능입니다.

둘러보면서 가장 빠르게 추가할 수 있고
리스트에서 사라져서 깔끔하기도 하구요.
