### ISSUE TITLE
가끔 강종이 됩니다

### ISSUE THREAD

**Issue by heromn0409** [KurtBestor/Hitomi-Downloader-issues#198]
뷰어를 켜다가 갑자기 혼자 강종이 되기도하며 히토미에서 받다가도 가끔 파일은 받아지는데 목록에 저장이 안된상태로 혼자 강종이 됩니다. 자료양은 약 1900개 정도 됩니다

**Comment by KurtBestor** [comment]
프로그램이 32bit 프로그램이라 발생하는 문제예요.

900개 이상은 권장하지 않아요. 참고해주세요: #170
