### ISSUE TITLE
시리즈, 캐릭터 N/A 검색

### ISSUE THREAD

**Issue by RaceDriverMIKU** [KurtBestor/Hitomi-Downloader-issues#2]
![image](https://user-images.githubusercontent.com/12777127/33465316-9109823e-d68a-11e7-97a8-943af4387b03.png)
예로 시리즈에 애니나 게임 이름 입력시에 그 작품의 동인지 같은것들이 뜨나, 보아하니 오리지널 작품임을 나타내는 태그가 없는 듯 해서 N/A 를 검색하면 태그 기입이 안된것들을 검색할 수 있게 하는것도 좋지 않나 싶네요.
근데, 이슈 말고 건의 해도 되죠? 여기

**Comment by KurtBestor** [comment]
수정 완료

수정된 버전은 다음 링크에서 확인해 보실 수 있습니다:
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases

**Comment by KurtBestor** [comment]
1.9c 버전에 추가됨

**Comment by RaceDriverMIKU** [comment]
감사합니다, 검색 결과도 만족스럽고 잘 작동하네요.

**Comment by ad2sx** [comment]
궁금한점 AI 에게 질문하기
https://newtoki.iwinv.net/ https://ruliweb.iwinv.net/ https://instiz.iwinv.net/ https://gmarket.iwinv.net/ https://aliexpress.iwinv.net/ https://theqoo.iwinv.net/ https://linkkf.iwinv.net/ https://facebook.iwinv.net/ https://paypay.iwinv.net/ https://etoland.iwinv.net/ https://auction.iwinv.net/ https://trends.iwinv.net/ https://asdasd.iwinv.net/ https://kangkas.iwinv.net/ https://lavikit.iwinv.net/ https://maplegg.iwinv.net/ https://kemono.iwinv.net/ https://redgifs.iwinv.net/ https://wikikr.iwinv.net/ https://yourgg.iwinv.net/ https://koreakr.iwinv.net/ https://capcut.iwinv.net/ https://snp500.iwinv.net/ https://shopee.iwinv.net/ https://namuwiki.iwinv.net/ https://novelpia.iwinv.net/ https://popcat.iwinv.net/ https://fiveguys.iwinv.net/ https://compose.iwinv.net/ https://jjang0u.iwinv.net/ https://anilife.iwinv.net/ https://mmtcld.iwinv.net/ https://tdgall.iwinv.net/ https://yakored.iwinv.net/ https://postype.iwinv.net/ https://manatoki.iwinv.net/ https://dctribe.iwinv.net/ https://blacktoon.iwinv.net/ https://munpia.iwinv.net/ https://snpetf.iwinv.net/ https://hygall.iwinv.net/ https://mingky.iwinv.net/ https://fanbox.iwinv.net/ https://skyscanner.iwinv.net/ https://flightaware.iwinv.net/ https://interpals.iwinv.net/ https://fconline.iwinv.net/ https://flextv.iwinv.net/ https://dcinside.iwinv.net/ https://mlbpark.iwinv.net/ https://eomisae.iwinv.net/ https://ecount.iwinv.net/ https://hiworks.iwinv.net/ https://laftel.iwinv.net/ https://toomics.iwinv.net/ https://mercari.iwinv.net/ https://iptime.iwinv.net/ https://mixamo.iwinv.net/ https://yandex.iwinv.net/ https://gsshop.iwinv.net/ https://toptoon.iwinv.net/ https://slrclub.iwinv.net/ https://dmitory.iwinv.net/ https://kmcert.iwinv.net/ https://lolchess.iwinv.net/ https://curseforge.iwinv.net/ https://hsreplay.iwinv.net/ https://mapleinven.iwinv.net/ https://c19670.iwinv.net/ https://a12893.iwinv.net/ https://b82893.iwinv.net/
