### ISSUE TITLE
2가지 궁금사항이 있습니다.

### ISSUE THREAD

**Issue by HoGu00** [KurtBestor/Hitomi-Downloader-issues#20]
1.
 지금 1.9e 버전 사용중인데 켤때마다 업데이트 하시겠습니까? 라는 문구에 예 누르고
새로 받았는데도 계속 1.9e 버전상태..던데 어떻게 해야되나요..??

2.
CG나 동인지쪽은 다운로드가 잘되는데
익헨쪽에서 ImageSet 쪽 주소를 붙여와도 읽는중 이라고만 나오고 다운로드가 진행안되는게 많은데
이쪽은 아직 지원이 안되는건가요??
서버를 수동 익헨으로 해봤는데도 잘 안되네요..

**Comment by HoGu00** [comment]
십여분 기다리니까 다운로드 되는것도 있네요;;
단순히 서버때문에  이런건가..

**Comment by KurtBestor** [comment]
1. 실수로 1.9e 버전을 올려놨었네요. 다시 2.0버전으로 올려놓았습니다.

2. 안 되는 갤러리 샘플로 주시면 분석해보겠습니다.

**Comment by HoGu00** [comment]
https://exhentai.org/g/1169177/44b68a5c44/
https://exhentai.org/g/1169089/5900beffd0/

몇개더 있긴한데
일단 2개만 올리겠습니다..
어떤거는 10~20분 기다려야 받아지는것도 있더군요

**Comment by KurtBestor** [comment]
테스트 해보니 잘 되는 것 같습니다.
짧은 시간에 많은 이미지를 다운로드하면 서버 쪽에서 해당 아이피를 일정 시간 동안 막습니다. 아마 이것 때문엔 것 같은데요, 프록시 등을 써서 다운로드 하시거나 나중에 다시 시도해보시기 바랍니다.
