### ISSUE TITLE
기본 데이터 다운로드가 안됩니다.

### ISSUE THREAD

**Issue by gvg23** [KurtBestor/Hitomi-Downloader-issues#201]
안녕하십니까. 항상 감사히 프로그램 잘 사용하고있습니다.

다름이 아니고 현재 기본 데이터 다운로드가 다운이 안되고있습니다.

![k-001](https://user-images.githubusercontent.com/42315425/44001161-73cf78fe-9e67-11e8-9685-f0784fdcc976.png)

![k-002](https://user-images.githubusercontent.com/42315425/44001162-77060dee-9e67-11e8-8eab-5952be9a4280.png)

![k-005](https://user-images.githubusercontent.com/42315425/44001163-810976a0-9e67-11e8-8f86-6fa9d60b970d.png)

![k-004](https://user-images.githubusercontent.com/42315425/44001185-1441f302-9e68-11e8-8c65-cc8b1c21939f.png)

이 화면에서 기본 데이터 다운로드를 누르면 다운로드 화면은 뜨지만 활성화가 안됩니다. 30분 넘게
기다려봐도 계속 무한로딩 상태구요,

![k-003](https://user-images.githubusercontent.com/42315425/44001170-98de6042-9e67-11e8-8117-02691f8f9e14.png)

그런데 여기서 취소를 누르면 다운로드는 되지만 완료된 후에도 업데이트가 안되있는걸로 나옵니다.

비슷한 증상으로 보이는 계시글을 보고 윈도우 디펜더나 V3 비활성화를 해도 해결되지않네요.

시간되시면 확인 부탁드립니다...ㅠ

**Comment by KurtBestor** [comment]
지금 테스트 해봤는데 저는 잘 되네요.
취소 눌렀을 때 진행바가 차긴 하지만 다운로드가 되진 않아요.

삭제된 데이터는 다운로드 되나요?

**Comment by gvg23** [comment]
아 삭제된 데이터로 체크하고 검색하니 나옵니다.

간단한거였네요... 정말 감사합니다!
