### ISSUE TITLE
핀터레스트 다운로드 방법을 알고 싶어요.

### ISSUE THREAD

**Issue by signCD** [KurtBestor/Hitomi-Downloader-issues#202]
도움말이나 메모장에도 딱히 사용법이 없네요 ㅠㅠ. 서치하고 주소 복사 후 넣는다거나 해도 

Traceback (most recent call last):
File *pinter_downloader*, line60, in read

라고 뜨면서 안되네요. 방법을 알고 싶어요

**Comment by KurtBestor** [comment]
다음과 같이 입력하면 돼요:
```
https://www.pinterest.com/bsheppard0097
```
