### ISSUE TITLE
deviantart 갤러리를 폴더로 분류한 계정의 다운로드가 안되는 문제

### ISSUE THREAD

**Issue by zephy8181** [KurtBestor/Hitomi-Downloader-issues#204]
현재 deviantart의 일반적인 갤러리는 정상적으로 다운로드가 됩니다.
하지만 폴더로 분류되어있는 계정의 경우는 아무것도 다운로드가 되지 않습니다.

https://www.deviantart.com/tjstock  
위 계정을 예로 들면

https://www.deviantart.com/tjstock/gallery/  
위에서 보는 것처럼 갤러리에 많은 사진이 있지만 다운로드를 시도하면 
아무것도 다운되지 않는 것을 확인할 수 있습니다.
(최근 deviantart 버그 제보에 대해서 수정해주신 버전으로 시도한 결과입니다.)

해결 가능한 문제인가요?

**Comment by KurtBestor** [comment]
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

테스트 부탁드려요.

**Comment by zephy8181** [comment]
너무 잘 됩니다.감사합니다.
