### ISSUE TITLE
웹툰다운에 대해 질문할게 있는데요

### ISSUE THREAD

**Issue by NANARANG** [KurtBestor/Hitomi-Downloader-issues#206]
안녕하세요 최근에 히토미다운로더 알게되서 감사하게 잘 쓰고있습니다.
웹툰을 다운받고싶은데, 밑에분 피드백에 달아주신 답변을 보고 네이버웹툰 다운할수있는 테스트버전 
써봤습니다. 만약에 정식버전에 업뎃된다면, 네이버스토어로 옮겨져서 따로 결제해야되는 웹툰은
다운받을수없는건가요?
그리고..웹툰올라오는 기타 복돌사이트는 추가업뎃해주시기 어려운가요?

히토미다운로더를 마루마루와 웹툰에 주로쓰고있어서,,웹툰에 대한 패치를 많이 기다리고있습니다.
꼭 부탁드립니다!!

**Comment by KurtBestor** [comment]
네, 제가 웹툰을 보는 것도 아니라 우선순위가 좀 밀리네요. 현재는 밤툰만 지원해요.

https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview
프로그래밍 할 줄 아시는 분이라면 스크립트 만들어서 사이트 추가할 수 있게 만들었어요.
[메뉴 - 스크립트...] 로 스크립트 실행할 수 있어요.

테스트용으로 nhentai 스크립트 하나 만들었어요. 테스트 부탁드려요:
https://drive.google.com/open?id=1FP0YZp7QyGDyOQ1nwILRIVT3kd58NYxo

**Comment by NANARANG** [comment]
n헨타이 잘돼요!
그리고 밤툰은 사이트가 막혔나보네요 
알려주신 스크립트추가 방법은 개인적으로 공부해볼께요! 
만들줄만 알면 원하는거 다운받을수있어서 더 좋을것같아요 ^^ 도움주셔서 감사합니다!

**Comment by KurtBestor** [comment]
밤툰이 HTTPS 지원을 안 해서 따로 우회 안하면 막히네요.

프록시 같은 걸로 우회하면 들어가지긴 해요.
