### ISSUE TITLE
유튜브 음원 및 영상 다운시 화질이나 음질 선택이 가능했으면 좋겠어요...

### ISSUE THREAD

**Issue by hp784951623** [KurtBestor/Hitomi-Downloader-issues#21]
외국 사이트의 힘을 빌려서 유튜브 영상 및 음원을 다운 받는데

어쩔땐 안되는것도 있고 너무느린것도 있어서

이걸로 다운 받아 봤는데 영상이랑 음질이 고정이라서 조금 아쉬워요

**Comment by KurtBestor** [comment]
유튜브 동영상은 해상도가 720p를 초과하면 영상이랑 소리가 따로 저장되어있더라구요.
이걸 각각 다운로드 한 후에 합치는 과정이 필요한데, 그러려면 FFmpeg같은 비디오 인코더가 필요하고, 더 들어가면 신경 쓸 게 많더라구요.
720p 미만 해상도는 필요가 없다고 생각해서 720p로 고정시켜 두었습니다.

음원은 딱히 필요성을 못 느껴서 MP3포맷, 음질 192Kb로 고정시켜 두었어요. 음질이 192Kb면 충분하다고 생각했고, 그 이하로 한다고 해서 파일 크기가 많이 달라지는 것도 아닌 것 같아서요.
