### ISSUE TITLE
몇가지 기능 건의드립니다.

### ISSUE THREAD

**Issue by miraclehoshi** [KurtBestor/Hitomi-Downloader-issues#211]
1. 창을 껐을때 트레이 아이콘으로 갔으면 좋겠습니다. 아래 있기엔 거슬리는데, 매번 켜는게 느리고 귀찮습니다.

2. DB 자동갱신이 있었으면 좋겠습니다. 1,3,6시간(선택)마다 갱신하면 편할 것 같습니다. 매번 수동 갱신이 조금 불편합니다.

3. 이게 제일 중요합니다. 이미 다운받은 작품을 검색에서 제외되도록 해주세요. 다운로드 & 제거를 눌러도 다시 검색하면 다시 나오게 되니 계속 본것들을 중복으로 받게 됩니다. 

4. 창이 작을때 전체 제목을 볼 수 있도록 어떤 조치를 취해 주셨으면 좋겠습니다. 
검색기를 켰을때 기본 창 사이즈에서 제목이 긴 작품들의 끝부분이 잘립니다.
현재 는 이 제목을 보려면 창 크기를 늘려서 보고 있는데, 
창 크기에서 이름이 잘리는 작품들의 경우 제목 위에 마우스를 올리면 전체 이름을 볼수 있다던지 하는 기능이 있었으면 좋겠습니다.

늘 잘 사용하고 있습니다. 수고가 많으십니다.

**Comment by RaceDriverMIKU** [comment]
3번은 갤러리 넘버 블랙리스트 기능 어때요?

**Comment by miraclehoshi** [comment]
아 그리고 이미 받은 작품 외에도 검색기에서 임의로 삭제한 작품들도 안나왔으면 좋겠습니다. 예로 번역이 마완된 작품들이 완성되는 중간중간 여러 파트로 올라오는데 완성본이 있으면 미완본을 검색 리스트에서 제외하고 싶습니다

**Comment by KurtBestor** [comment]
1. [메뉴 - 트레이로 최소화] 기능을 쓰세요.

2. 백그라운드에서 갱신하게되면 다운로드를 실패하거나 도중에 프로그램을 종료하는 등 예외상황이 생겼을 때 처리를 하기 애매해요. 일단은 그대로 둘게요.

3. 구현을 어떻게 할지 고민이에요. @RaceDriverMIKU 님 말대로 블랙리스트를 만들지, 한번이라도 다운로드 받은 적이 있는 갤러리를 모두 제외할지, 현재 다운로더 목록에 있는 갤러리를 모두 제외할지, 다운로드 폴더에 있는 삭제되지 않는 갤러리를 모두 제외할지, ... 좋은 구현 방법 있으면 말씀해주세요.
아예 목록에서 없애버리는 건 좀 별로라서 따로 표시를 하던지 할 것 같아요.

4. 마우스 올리면 전체 이름 뜨게 수정했어요.

https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview
테스트 부탁드려요.

**Comment by KurtBestor** [comment]
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview
이미 다운로드한 작품 검색기 검색 결과에서 표시되게 수정했어요.
아예 목록에 표시 안되게 하려면 `도움말 - 사용법... (F1) - 검색기 목록 필터링`을 참고해주세요.
테스트 부탁드려요.
