### ISSUE TITLE
마루마루 다운시 범위 조절을 할수 있게 해주세요

### ISSUE THREAD

**Issue by underexe** [KurtBestor/Hitomi-Downloader-issues#214]
몇화부터 몇화까지 선택해서 다운로드 가능하게 해주시면 좋을꺼같아요

이미 다운로드 받은 화도 있고
그리고 범위를 선택하면
다운로드 받았던 파일을 다시 다운로드안해도 되니까 괜찮을꺼같아요

모두 다운로드 / 내가 선택한 범위 
로만 나뉘어도 괜찮을것 같아요

**Comment by KurtBestor** [comment]
이미 있는 기능이예요.

작업 추가할 때 우클릭해서 다음과 같이 해주시면 돼요:
![image](https://user-images.githubusercontent.com/14768120/44558948-e5a1b500-a781-11e8-8195-acb4ac267566.png)
