### ISSUE TITLE
선택화 다운로드를 하면 프로그램이 응답없음이 됩니다.

### ISSUE THREAD

**Issue by minasis** [KurtBestor/Hitomi-Downloader-issues#216]
64비트 윈10 에서 사용하고 있는데
선택화 다운로드만 하면 프로그램이 응답없음이 되어버리는데
다른 사람은 된다는 사람이 있어서
어떤 문제인지 알수가 없습니다.

관리자모드로 구동시켜도 마찬가지네요

**Comment by KurtBestor** [comment]
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

테스트 부탁드려요.

**Comment by KurtBestor** [comment]
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

테스트 부탁드려요.
