### ISSUE TITLE
히토미다운받는데 4개이상안받아져요.

### ISSUE THREAD

**Issue by shansiro1234** [KurtBestor/Hitomi-Downloader-issues#218]
버전2.4 쓰고있구요
자동으로목록받오아는게아니라 제가원하는작품만 직접 주소입력해서 다운받는데
4개까지만 동시다운로드 하고 나머지는 대기만 뜨네요.
설정에 스레드올려도 적용이안되나.. 
i7-7700대 컴터쓰고있습니다. 윈10이구요

**Comment by KurtBestor** [comment]
설정의 스레드 갯수는 한 작업 당 동시 다운로드 수예요.
작업 스레드는 4개로 고정이고, 하나 당 최대 64개의 다운로드 스레드를 가져요.
[Shift + Esc] 눌러보시면 스레드 상태 창이 뜨는데 띄우고 다운로드 해보시면 감이 올거예요.
