### ISSUE TITLE
건의 사항....

### ISSUE THREAD

**Issue by megatron1423412** [KurtBestor/Hitomi-Downloader-issues#22]
1.
파일 다운 받았을 때 파일들이 가끔
1,2,3,4,5,6,7,8,9,10,11,....

이렇게 말고

01,02,03,04,05,...

이런식으로 padding 기능이 있었으면 좋겠는데요.... 가능한가요?

2. 만약 padding 기능이 안되면

파일 이름 싹 다 지우고 001,002,003, 이런식으로 그냥 순서대로 이름 다시 붙일 수 있는 기능이라도 가능한가요??

**Comment by KurtBestor** [comment]
어떤 사이트를 원하나요?
현재 파일 이름 작성 규칙은 이렇습니다:
- 원본 파일 이름: Hitomi.la, E-Hentai, ExHentai
- 게시물 제목: YouTube, Vimeo, Tvple, Pornhub, Bilibili
- 패딩 붙은 숫자: Marumaru
- 게시글 ID + 페이지: Pixiv, Twitter, Instagram, DeviantArt, Tumblr

**Comment by megatron1423412** [comment]
히토미 주로 다운 받을때 padding이 안되더라구요.

근데 마루 다운받으려고 하는데 어떻게 다운받는지 모르겠더라구요?

링크 복붙넣어도 계속 에러 뜨던데...

**Comment by KurtBestor** [comment]
히토미 계열 파일 이름 수정은 설정에 해당 기능 ON/OFF할 수 있게 하겠습니다.
마루마루는 다음과 같이 입력하면 됩니다:
    http://marumaru.in/b/manga/316
reCAPTCHA 걸려있는 건 지금 해보니 패턴을 바꿨는지 안되네요.. 나중에 이것도 다시 봐야겠습니다..

**Comment by megatron1423412** [comment]
실례가 안된다면 혹시 padding 기능 어떤식으로 넣으실지 물어봐도 될까요

아예 전부 3자리수로 넣기? 혹은 본인이 원하는대로 임의로 padding숫자 조정?

항상 감사합니다.

**Comment by KurtBestor** [comment]
패딩은 네자릿수로 고정하려고 합니다.

**Comment by megatron1423412** [comment]
혹시 파일명 싹다 지우고 4자리수로 padding도 옵션으로 부탁드릴수있나요? 
가끔 파일명이 이상하게 길어서 거슬릴때도 있더라구요. 
이런 파일 aa_35_01_c은 padding 4자리로 하면 aa_0035_01_c으로 padding 될때가 있더라구요.

**Comment by KurtBestor** [comment]
네, 그냥 마루마루와 같이 0000.jpg, 0001.jpg, ... 이런 식으로 하려고 합니다.

**Comment by megatron1423412** [comment]
감사합니다.

**Comment by KurtBestor** [comment]
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

해당 기능 구현해봤습니다. 테스트 부탁드려요.
옵션 - 설정 - 히토미 설정 - 파일 이름 형식을 숫자로 바꾸면 됩니다.

**Comment by megatron1423412** [comment]
감사합니다. 완벽하네요.

**Comment by KurtBestor** [comment]
v2.0에 해당 기능 추가됨
