### ISSUE TITLE
호두코믹스

### ISSUE THREAD

**Issue by ldh7680** [KurtBestor/Hitomi-Downloader-issues#220]
호두코믹스 사이트 주소 변경 되고 다운이 안돼네요..ㅜㅜ

**Comment by NANARANG** [comment]
지나가다 댓글남깁니다
원래주소 https://hodu8.com/에서 https://hodu12.com/로 바뀌었는데
스크립트변경프로그램으로 바뀐부분만 수정하면 정상적으로 적용될까요?
이런 복돌사이트는 주소가 매번 바뀌어서.. 바뀔때마다 요청드리는게 죄송스럽습니다 ㅠㅠ

**Comment by KurtBestor** [comment]
https://drive.google.com/drive/folders/1FP0YZp7QyGDyOQ1nwILRIVT3kd58NYxo

수정했습니다

**Comment by KurtBestor** [comment]
참고로 스크립트(*.hsc)는 메모장이나 기타 텍스트 에디터로 열어서 간단하게 수정할 수 있으니 관심 있으신 분은 해보세요.

**Comment by NANARANG** [comment]
감사합니다!!!!

**Comment by ldh7680** [comment]
감사합니다!!!!!ㅜㅜ
