### ISSUE TITLE
기존 파일을 불러올 수 있는 기능 추가 요청

### ISSUE THREAD

**Issue by GoopyAspirin** [KurtBestor/Hitomi-Downloader-issues#221]
안녕하세요.

불필요한 다운로드파일을 다운로드 경로에 있는 폴더에서 삭제하면, 프로그램 실행시 프로그램에서는 자동으로 삭제된 파일이 손상된 것으로 판단하고 다시 다운로드합니다.

그렇다고 프로그램 내에서 삭제를 일일히 하기에는 다소 무리가 있고..

아래 기능이 추가되면 좋겠습니다.

1. 다운로드 경로에 있는 목록을 전부 불러와서, 현재 목록을 대체(전부 지우고 대치) 일종의 불러오기 기능

2. 프로그램 경로에 로그 파일을 남기고, 정상종료시 삭제하거나 유지하는 방식으로 예기치못한 종료시 작업 이어하기

3. 프로그램 리스트 초기화(전부 삭제)

4. 유투브 화질설정

5. 후원을 하고싶은데 후원을 할 수없음, 후원방법에 대한 설명이나 좀더 쉬운 방법으로 대체부탁드립니다.

좋은 프로그램 잘 쓰고 있습니다.
항상 감사합니다.

**Comment by GoopyAspirin** [comment]
추가로, 작업 쓰레드를 4개 이상으로 늘릴 수 있으면 좋겠습니다.

**Comment by KurtBestor** [comment]
불필요한 파일은 다운로드가 완료된 후에 삭제해주세요.
삭제된 파일은 손상된 것으로 인식하지 않아요. 다운로드가 완료될 때만 체크합니다.

1. 목록 저장 기능을 써주세요.

2. 자동 저장 같은 기능으로 구현될 것 같네요.

3. Ctrl + A 눌러서 모두 선택한 후 Delete 누르시면 돼요. 윈도 탐색기랑 비슷하게 동작해요.

4. 참고해주세요: #21

5. 프로그램 오른쪽 아래에 하트모양 버튼 누르시면 돼요. 익명으로 주고 받으려고 하는데, 비트코인보단 이게 더 쉬운 것 같아서 하게됐어요. 다른 좋은 방법 있으면 알려주세요.

작업 스레드는 4개, 다운로드 스레드는 각각 64개 씩 해서, 최대 256개를 동시에 다운로드하게 되는데요, 이 이상은 속도에 의미가 없기도 하고, 더 늘리기도 힘들어요. 32비트 프로그램이라 프로세스 하나에 2048개의 스레드가 이론상 최대예요.

현재 스레드는 이만큼 쓰고있어요:
- 작업 스레드 4개
- 다운로드 스레드 256개
- 데이터 다운로드 스레드 0~20개
- 섬네일 다운로드 스레드 32개
- 기타 10개 정도

**Comment by KurtBestor** [comment]
자동 저장 기능 넣었어요. 
[옵션 - 설정 - 고급 - 자동 저장] 에서 설정할 수 있어요.

https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview
테스트 부탁드려요.
