### ISSUE TITLE
사이트 오류로 인한 다운로드 불가

### ISSUE THREAD

**Issue by ldh7680** [KurtBestor/Hitomi-Downloader-issues#222]
호두코믹스에서 웹툰 다운로드하려는데 중간에 사이트 자체 오류난 화가 있으니 다운이 안되네요
방법이 없나요??
예를 들어 브릿지라는 웹툰 13화가 사이트 자체에서 웹툰이 없습니다 라는 오류로 들어가지지
않는데 그로 인해 프로그램에서 12화까지 읽고 진행디 되질 않네요
선택화 다운로드를 하려고 해도 일단 전체를 다 읽어야 가능한 것같고
해당화를 건너뛰고 다운가능한 방법은 없나요??

**Comment by KurtBestor** [comment]
https://drive.google.com/drive/folders/1FP0YZp7QyGDyOQ1nwILRIVT3kd58NYxo

수정했어요.
