### ISSUE TITLE
e헨에서 404가 뜨면서 다운되지않습니다

### ISSUE THREAD

**Issue by cv44444** [KurtBestor/Hitomi-Downloader-issues#223]
평소에 잘쓰고있습니다
근데 E헨주소를 복사해서 다운을 했는데 다운된 링크를보니 hitomi로 되어있고
그중 몇몇개는 이름이 주황색이 되면서 다운이되지않거나
404 not faund 가 뜨면서 다운이 되지않습니다
벤 안먹었을떄도, IP바꿔도다운이되지않습니다
혹시몰라 이헨 검색필터에 Show Expunged Galleries 이거 체크하고 X뜬표시 다운받은거라 안되나 싶어서 X안뜬것도 해봣지만 안뜬것도 다운이 안됩니다
https://exhentai.org/g/1280473/666a5b40ba/ 이링크 파일등 대다수가 404가 뜨면서 다운이 되지않습니다
해결법을 알려주시면 매우감사하겠습니다

**Comment by KurtBestor** [comment]
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview
의심가는 부분 조금 고쳤어요.
테스트 부탁드려요.

![image](https://user-images.githubusercontent.com/14768120/44955029-8103fa00-aee7-11e8-855b-dcf580a8dc0f.png)

**Comment by cv44444** [comment]
감사합니다!! 
근데 소스코드말고 GUI만 다운받아서 실행하면되는건가요?
소스코드는 어떻게쓰는지 몰라서여....
그리고 GUI만 다운받아서 실행해봣는데 안되요....ㅠㅜ

**Comment by KurtBestor** [comment]
네 실행파일만 받으시면 돼요.
이게 됐다가 안 됐다가 하는데 나중에 시간나면 고쳐볼게요.

**Comment by cv44444** [comment]
감사합니다!!

**Comment by KurtBestor** [comment]
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview
테스트 부탁드려요
