### ISSUE TITLE
hitomi_data폴더에 기본 데이터가 있음에도 검색기에서 검색이 되지 않습니다.

### ISSUE THREAD

**Issue by inchaos4315** [KurtBestor/Hitomi-Downloader-issues#224]
hitomi_downloader_GUI폴더를 첫 압축 해제후 다른 폴더에 실수로 옮긴 이후

hitomi_data폴더에 기본 데이터가 있음에도 검색기에서 검색이 되지 않습니다.

검색기 우측 상단에는 No data라고 표시되어 있고

기본 데이터 다운로드를 시도하면 hitomi_data폴더에 무언가 채워지다가 삭제되고

기본 데이터 다운로드는 완료되지 않고 data downloader 대화상자가 사라집니다.

검색기 우층 상단의 No data는 계속 유지된 상태입니다.

hitomi_downloader_GUI를 전혀 다른 하드디스크에 다시 새로 압축 해제해도 해결되지 않고있습니다.

**Comment by KurtBestor** [comment]
[Ctrl + Alt + C] 눌러서 콘솔 열고 ```print constants.HITOMI_DATA```를 입력한 다음 [Enter] 누르고 나오는 내용 알려주세요.

**Comment by inchaos4315** [comment]
![default](https://user-images.githubusercontent.com/42910198/44970725-0346f980-af8e-11e8-8231-d7d757ca064c.PNG)

**Comment by inchaos4315** [comment]
혹시몰라 같은 오류를 보이는 다른 하드에 설치한 것도 가져왔습니다.
![default](https://user-images.githubusercontent.com/42910198/44970875-7a7c8d80-af8e-11e8-8122-c914997e4a71.PNG)

**Comment by KurtBestor** [comment]
hitomi_data 폴더에 어떤 파일들이 있나요?

**Comment by inchaos4315** [comment]
![image](https://user-images.githubusercontent.com/42910198/45029294-299a9100-b083-11e8-985b-3db613cd0164.png)

이런 파일들이 있습니다.

저런 파일들이 전혀 없는 새로운 압축 해제 후에도 같은 증상이 발견됩니당.

**Comment by inchaos4315** [comment]
다른 컴퓨터에서 잘 구동됩니다. 제 pc문제인것 같네요 도움 주셔 감사합니다.
