### ISSUE TITLE
몇몇 제안 및 문제점.

### ISSUE THREAD

**Issue by hoindinwgj** [KurtBestor/Hitomi-Downloader-issues#225]
일단 컴퓨터 사양은 i7-6700k 32GB 에 윈도우즈7을 씁니다.

1. 고전버전에서는 안그랬는데 한 6-8개월 전쯤 업데이트부터 프로그램이 다운로드 중 에러메세지와 함께 강제 종료됩니다. 4-8개 마다 받고 다운로드된 리스트 클리어 해주면 괜찮긴한데 이런 문제없이 다운로드했던 고전버전들이 그립습니다. 제가 생각할 수 있는 범위로는 컴퓨터 리소스(메모리) 충돌이나 다운로드속도를 하드디스크 수명이 못 따라가서 강제종료됐을 수도 있을 것 같습니다.
2. 예전 프로그램에서 파일명 언어부분에 [한국어]가 들어갔을 때 받아뒀던 자료들이 영어인 [Korean]으로 바뀌고나서부터 [한국어]를 인식을 못하고 [Korean]으로 다시 중복다운로드됩니다.
3. 타입(Type)에 NON-H도 추가해주세요!

Hitomi-Downloader 감사하게 잘 쓰고 있습니다. 고맙습니다!

**Comment by KurtBestor** [comment]
1. 정확히 문제가 생기는 가장 오래된 버전이 뭔지 알 수 있을까요? 예전 버전은 다음 링크에서 확인할 수 있어요:
https://drive.google.com/drive/folders/0B8iYCPDKWc_NYU5KLS0tbzRWenM

2. 폴더명 변경 프로그램으로 [한국어] 를 [Korean] 으로 바꿔주세요.

3. NON-H 는 히토미엔 없어요.

**Comment by hoindinwgj** [comment]
1. 너무 옛날버전인지 DB다운로드중에 에러가 나네요..
2. Darknamer 라는 유틸로 해결했습니다.
3. 그랬군요...
