### ISSUE TITLE
검색기 문의사항있습니다!!!! 확인해주시면 감사!

### ISSUE THREAD

**Issue by rabirabin** [KurtBestor/Hitomi-Downloader-issues#226]
가끔씩 다운로더가 강종될때가있는데요 검색기를 켜놓고 계속검색 뜨기전것만 다운로드하고 (약 995개정도) 그뒤에 남은거 다운받으려하는데  여기서 문제가 히토미다운로더가 강종되면 검색기도 강종되서 어디까지 검색해서 다운했는지 알수가없더라구요 혹시 예를들면 작가이름 즐겨찾기로 저장해놓고 그대로 다시검색하면 강종되기 이전 검색결과 순서랑 새로켜서 검색한 결과순서가 같나요?

**Comment by KurtBestor** [comment]
검색 데이터를 다시 다운로드 하지 않는 이상 검색되는 내용은 같아요.
