### ISSUE TITLE
프로그램 시작 후 자동 이어받기 관련 문제

### ISSUE THREAD

**Issue by RaceDriverMIKU** [KurtBestor/Hitomi-Downloader-issues#23]
옵션에서 저장 폴더를 기본값이 아닌 다른 곳으로 지정후, 히토미에서 무언가를 받다가 도중에 프로그램 종료 후(리스트 저장) 재실행 하면 지정된 경로로 이어받기를 실행 하는것이 아닌 기본값에다가 처음부터 저장을 실행 합니다, 다만 기본값 링크에 있던것이 있다면 그것을 이어받기를 실행 합니다.
다만 자동으로 이어받는걸 수동으로 다시시작 해주면 지정된 저장 폴더에 다운로드 하더라고요.

**Comment by KurtBestor** [comment]
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

고친 버전입니다. 테스트 부탁드려요.

**Comment by RaceDriverMIKU** [comment]
다른 저장 경로 설정 후, 리스트 저장 후 프로그램 재시작 해서 자동 이어받기 여러번 해본 결과, 의도대로 작동 합니다.

**Comment by KurtBestor** [comment]
v2.1에서 해결됨
