### ISSUE TITLE
소스코드는 어떻게사용하는건지 궁금합니다

### ISSUE THREAD

**Issue by cv44444** [KurtBestor/Hitomi-Downloader-issues#230]
이떄까지 소스코드말고 다운로더만 다운햇는데 소스코드는 안쓰는건가요?
어떻게 쓰는지 궁금합니다 알려주시면 감사하겠습니다

**Comment by KurtBestor** [comment]
duplicate of https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/223
