### ISSUE TITLE
기본 데이터를 다운로드할 수 없습니다.

### ISSUE THREAD

**Issue by undisclosed213** [KurtBestor/Hitomi-Downloader-issues#231]
프로그램 잘 쓰고 있습니다.

https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/201

이 이슈랑 동일한 증상이 일어납니다.
기본 데이터 다운로드를 누르면 0/20에서 진행되지 않습니다.
hitomi_data 폴더에는 galleries(숫자).json_new 파일들이 19번까지 생성되지만 파일 용량이 0KB네요.

삭제된 데이터 다운로드는 가능합니다.

혹시나 해서 다른 곳에 다시 압축을 풀어도 똑같은 증상이 발생하네요...

**Comment by KurtBestor** [comment]
인터넷 주소창에 `https://ltn.hitomi.la/galleries0.json` 입력해서 접속해보세요. 어떻게 뜨나요?

**Comment by undisclosed213** [comment]
{"id":1284681,"t":["female:milf","female:sole female"],"n":"Mama-san Volley Tokubetsu Lesson","l":"japanese","type":"doujinshi"},{"id":1284680,"n":"There Goes The Neighborhood","l":"japanese","type":"doujinshi"}

이런 식으로 수많은 json 파일이 나오네요. 근데 지금 다시 데이터 다운로드를 하니까 제대로 다운로드가 됩니다. 일시적인 현상이었나 봐요.
