### ISSUE TITLE
기능 건의 관련

### ISSUE THREAD

**Issue by wpfhfpr** [KurtBestor/Hitomi-Downloader-issues#232]
안녕하세요 오랫만에 건의 사항 올릴까해서 들어오게 됬습니다.
원하는 기능이나 피드백을 금방 해주시다보니 제작자님을 많이 귀찮게 해버렸네요.

1.  이건 건의보단 문의네요. 32비트의 프로그램환경으로 인해 오류가 잦은 것 같은 데 이게 목록의 개수에 상관없이 발생했다 안했다 하는 기분이 많이 듭니다.
이유로는 십여개의 목록을 사용할 때도 오류가 발생하기도 하고 그와 반대로 1200여개가 문제없이 다운되어있는 경우가 있더군요. 오류의 원인이 메모리인지 ..아니면 해결되면 매우 좋을 거같아서요~문의남깁니다.
또다른 의심 사항으론 CPU,메모리보단.. 오히려 하드 속도에 의한 것인가 싶기도 합니다.왜냐하면 히토미다운로더를 사용하면 다운 여부와 상관없이 그 드라이브에 대한 엑세스가 매우 느려집니다.

2. 이 기능은 위의 오류로 인해 불편한 걸 해소하는 방안으로 생각해본 기능입니다.
목록에 자료가 많이 있을 시 32비트의 환경으로 인해 에러가 발생한다고 하면..
다운받은 즉시 목록에서 삭제되는 기능을 On/Off 식으로 만들면 어떨가 합니다.
말그대로 목록의 자료로 인해 메모리를 차지한다고 하면 이를 해소할 수 있으며,
자료를 많이 받다가 에러가 나면 이전에 저장된 형태로 다시 다운을 시작하는 데 가끔 이 과정에 파일이 깨지는 경우가 생기더군요.

3. 중복 파일 처리에 대해서 입니다. 위의 1번 마지막 추측이 맞았다고 (하드 과사용) ,,다운받는 것을 생각하면 하드가 언젠가 나갈 것이라는 각오는 하고 있지만 조금이라도 더 효율적으로 쓰면 좋겠다고 생각해서 건의드립니다.

   이전의 글을 보면서 저와 비슷한 생각을 했던 분이 계시더군요.#221 
   다운받은 저장 위치에 있는 파일을 대치해서 목록에 있는 것을 대치하는 기능이였었나요?
목록 저장기능이 Ctrl+S를 말씀하는 건지 모르겠지만 그게 아니라면 잘 이해가 안되서요.

각설이 길었습니다.ㅜㅠ

중복이 되는 경우 폴더이든 Zip(압축파일)이든 다운로드 스킵을 하는 기능을 감사하게도 구현해주셨습니다.번호로 비교해서 중복을 판별하는 줄 알았지만 파일이름을 비교해서 하는 것이더군요.
번호를 이용하여 파일 다운로드 스킵을 하는 기능이 구현이 된다면 매우 효율적일 것이라 생각합니다.
#225 분의 [한국어]와 [Korean]의 폴더 이름이 변하여 중복 다운되는 경우도 피할 수 있지 않을 까 생각합니다. 
굳이 목록에 추가하는 건 상관없다고 생각합니다.왜냐하면 다운 받을 때 저장위치에 번호로 비교를 할 수 있다면 추가를 하더라도 스킵이 되서 중복 다운이 되지 않기때문이죠.

또다른 방법으로
다운로더를 보면 저장 폴더의 번호 저장이 있더군요. 이게 어떤 목적으로 있는 기능인지는 제가 사용법을 몰라서 안쓰고 있지만 이 기능을 이용해서 히토미 다운로더 검색기 자체에 쓸수 없을까요?
예를 들면 제외 태그 기능에 번호가 적힌 .txt나 .ini을 이용하여 검색기를 쳤을 때 다운받은 목록은 검색기에 뜨지 않는 다던가, 
히토미 데이터에서 그 번호만 삭제할 수 있게끔 하면 어떨까 합니다.
정확히는 모르지만 검색기의 원리가 검색을 했을 시 검색 범위가 번호로 되어있는 것을 감안하면 가능성이 일말이라도 있지 않을까 희망을 갖기에..

매우 감사하게 사용하고 있습니다. 실현이 되지 않더라도 이 프로그램은 이미 갓갓이지만
실현되면 갓갓갓갓?ㅎㅎ 여튼 매우 감사합니다.

**Comment by KurtBestor** [comment]
1. 제 쪽에서 재현해볼 수가 없네요. 하드에 부담이 많이 된다면 스레드 갯수를 낮춰주세요.

2. 즉시 삭제하지 않아요. 삭제할 목록에 추가해놓고 차례대로 삭제를 시도합니다.

3. 중복된 목록은 [F3] 눌러서 필터 키고 `dup:` 입력해서 확인할 수 있어요.

번호를 이용해서 스킵하는 기능은 효율적이지 않아요. 다운로드 폴더에 있는 폴더명을 모두 읽어야하는데, `하드에 부담`이 되고 속도가 느려져요. 또한 폴더명 형식에 `id`가 들어있지 않는 경우에는 인식할 수 없구요.

이미 다운로드 받은 작품은 따로 표시되게 구현할 생각이예요. 참고해주세요: #211

**Comment by KurtBestor** [comment]
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview
이미 다운로드한 작품 검색기 검색 결과에서 표시되게 수정했어요.
아예 목록에 표시 안되게 하려면 `도움말 - 사용법... (F1) - 검색기 목록 필터링`을 참고해주세요.
테스트 부탁드려요.

**Comment by wpfhfpr** [comment]
테스트버전 즉 , 정식으로 받은 2.4D버전 이후에는 다량의 검색결과물이 발생시 검색기 결과 목록이 스크롤 자체는 되지만 내용이 내려가지 않게 됩니다.즉, 오른쪽의 스크롤바는 내려가는데 내용이 변하지 않고 유지된다는 거죠. 렉이걸렸달까요..?
게다가 F3버튼(필터링)이 작동을 하지 않습니다. 정식버전은 잘 작동됩니다.

그와중에 잠시 테스트 해본것은 이미 다운로드 받은 작품에 대한 표시입니다만
제가 생각한 것과 일맥상통하는 부분이 있습니다. 이미 다운받은 작품이 표시된다면 다운받지 않아도 되고 필터링으로 그것들만 삭제하면 되기에 편리합니다. 다만 검색기에 다운받았던 것을 표시하는 원리가 무엇인지는 모르겠으나 폴더로 다운받았을 때만 인식되는 것을 확인했습니다. 이것 역시 압축파일역시 인식되게 해주실수 있을까요?

그리고 2번에 대해 이해가 가지 않는 점이 있습니다.
즉시 삭제를 하지않는다는 게 어떠한 건지요? 
제가 말씀드린 건 다운완료되면 바로 목록에서 제거하게끔 하는 기능을 ON/OFF식으로 할 수 있지 않을까란 내용이여서요 ㅠ아니면 이미 구현되있는 기능인데 제가 모르는 건가 싶어서 여쭤봅니다~

**Comment by KurtBestor** [comment]
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview
테스트 부탁드려요.

2번은 제가 잘못이해했어요. 파일을 삭제했을 때 디스크에 부담주지 않게 한꺼번에 삭제하지 않는 걸로 이해했어요. 만약 구현된다면 일정 갯수 초과됐을 때 제일 오래된 순으로 삭제하는 방식으로 될 것 같아요.

**Comment by wpfhfpr** [comment]
2번 구현은 다음기회에~인가요?ㅠ
아! 그리고 위의 링크 테스트버전은 오류가 뜨면서 실행이 안되네요?
Traceback (most recent call last):
  File "hitomi_downloader_GUI.py", line 2640, in <module>
  File "hitomi_downloader_GUI.py", line 2607, in setColor
TypeError: 'int' object is not iterable
Traceback (most recent call last):
  File "hitomi_downloader_GUI.py", line 2640, in <module>
  File "hitomi_downloader_GUI.py", line 2607, in setColor
TypeError: 'int' object is not iterable
 인수가 잘못되었낭..?

**Comment by KurtBestor** [comment]
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview
테스트 부탁드려요.

**Comment by wpfhfpr** [comment]
테스트 완료했습니다.
이전에 받았던 목록들 다운받은걸로 적용이 되있네요.이것은 저장  위치에 있는 것만 적용되겠죠? 파일을 이미 전 작가별로 분류하고 있는 터라 개인적으론 번호추출해서 받은것도 따로 입력을 하던가해서 목록에 표시되게하고싶지만 이건 욕심인듯하네요 ㅎㅎㅠ
F3버튼도 작동 잘됩니다.
테스트 완료입니다~

삭제기능이 구현되면 좋을거같긴합니다.바로제거는 프로그램이 무거워지려나?

**Comment by KurtBestor** [comment]
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

삭제 기능 만들었어요. `옵션 - 설정 - 고급 설정 - 다운로드 완료 후 자동 제거` 에서 설정할 수 있어요.
테스트 부탁드려요.
