### ISSUE TITLE
동영상 다운로드 문의

### ISSUE THREAD

**Issue by ShizuKR** [KurtBestor/Hitomi-Downloader-issues#233]
익스플로러를 쓰던 시절 동영상 다운로드 프로그램으로 알툴바...를 쓰다가

도저히 익스플로러를 못 쓰겠어서 크롬으로 넘어왔고.

그 후, 유투브 등의 동영상 다운로드는 en.savefrom.net 등의 사이트를 이용했었는데요...

히토미 다운로더에 주소 드래그 후 엔터 한번 치면 다운로드 되는 신세계에 빠져 잘 이용하고 있습니다.

감사감사. 압도적 감사.

그런데 쓰다보니 좀 불편한 부분이 있어 맞게 사용하고 있는건가 문의드립니다.

유투브 등 동영상 다운로드 시, 게시글 주소 기준으로 제목이 저장되는거 같은데...

https://www.youtube.com/watch?v=761ae_KDg_Q

예를 들면...

--> 상어 가족 ｜ 아기 상어 ｜ 동물동요 ｜ 핑크퐁! 인기동요.mp4 로 저장됩니다.

유튜브는 대부분 게시글 제목이 너무 길어서 파일 이름을 편집해야 하는 경우도 있고.

제목이 같을 경우, url이 달라도, 파일 명이 같으면 그냥 완료 처리가 되더군요.

파일명 저장 형식을 지정할수 있었으면 가장 좋겠고...

(2) 이런식으로 뒤에 이름 추가를 하던가. 파일 뒤에 url을 붙이는 등의 변경이 가능한지요?

두줄 요약하면,

동영상 다운로드 시 파일명 규칙을 커스텀할수 있는지

url이 달라도 제목 중복시 후속 파일이 자동 완료됨 처리되는데, (2) 등의 파일명 처리 후 다운로드가 가능한지 문의드립니다.

감사합니다.

**Comment by KurtBestor** [comment]
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview
테스트 부탁드려요.

[옵션 - 설정 - 유튜브 - 파일명 형식]에서 바꿀 수 있어요.

**Comment by ShizuKR** [comment]
유투브에서 파일명 (id) 작동 잘됩니다.
(id) title 로 변경해서 저장해도 잘 작동되네요.

호옥시 pornhub 에서도 (id) 명령어가 작동되게 할 수 있나요?? =////=

**Comment by KurtBestor** [comment]
Pornhub도 파일명 겹치는 게 있나요?

**Comment by ShizuKR** [comment]
제목 (파일명) 이 짧을 경우 겹치는게 많이 나옵니다... 예를 들어보자면..

https://www.pornhub.com/view_video.php?viewkey=ph5a8e9207100bc

https://www.pornhub.com/view_video.php?viewkey=ph5a8cdad3417ea

이런식이네요. 아이디 명령어로 해결이 가능할 것으로 보이는데, 동영상 다운로드 파일명 규칙을 잡으면 되려나요.

유투브 수정사항은 잘 쓰고 있습니다. 감사합니다.

**Comment by KurtBestor** [comment]
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview
테스트 부탁드려요.

**Comment by ShizuKR** [comment]
완벽합니다. 감사합니다.
즐거운 추석 보내세요
