### ISSUE TITLE
머신러닝 관련 기능 건의합니다

### ISSUE THREAD

**Issue by Ggirub** [KurtBestor/Hitomi-Downloader-issues#234]
다운로드 후 외장하드에 정리하는터라 머신러닝 기능에 목록이 추가되지 않습니다.
현재 텍스트 파일로 작품 목록을 저장/불러오기하는 기능은 있는데 좀 더 간편하게 개선됐으면 좋겠습니다.

https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/95
위 건의 이후 현재 다운로더 폴더 안에 "(갤러리번호)"인 폴더가 있으면 머신러닝 목록에 인식되고 있는데, 검색기 상에 오른쪽 클릭으로 "이 갤러리 번호로 빈 폴더 만들기" 같은 기능이 있었으면 좋겠습니다.

**Comment by KurtBestor** [comment]
텍스트 파일로 저장하고 불러오는 걸로는 충분하지 않나요?
텍스트 파일 내용을 수정하고 싶으시면 그냥 메모장으로 열어서 수정하시면 돼요.

**Comment by Ggirub** [comment]
말씀하신대로 텍스트 수정해서 사용 중인데 영 불편하다 싶어서요...
지금까진 다운로드한 작품이나 검색기에서 일일이 갤러리 번호를 복사하고 있는데, 숫제 검색기에서 바로 추가할 수는 없을까하여 건의드립니다.

아니면 다른 방법으로, 다운로드한 파일들을 옮겨도 프로그램상에는 작품들 목록이 남아있는데, 그것들이 머신러닝에서 인식될 수 있도록 수정해주실 수 있을까요?
