### ISSUE TITLE
마루마루 일부 다운할때 폴더 제목에 횟수 표시기능이 있었으면 하는 소망이...

### ISSUE THREAD

**Issue by dullahan00** [KurtBestor/Hitomi-Downloader-issues#237]
너무 신경쓰지 않으셔도 되지만 자그마한 부탁좀 드려볼까 합니다. 

전체 다운하는 것도 있지만 특별 화수 다운을 합니다. 

예를 들어 원피스 200~250화
이런 식으로 다운을 할때 압축 설정을 한 상태로 다운을하는데 제목에 선택 화수가 나오게도 가능하게 될 수 있는지요...?

**Comment by KurtBestor** [comment]
폴더 이름에 이미 몇화인지 나오지 않나요?
