### ISSUE TITLE
네이버 블로그에서도 받아지긴하는데 이런건 안긁어지네요

### ISSUE THREAD

**Issue by TopGuunN** [KurtBestor/Hitomi-Downloader-issues#238]
안녕하십니까
항상 감사드리고 잘 이용하고있습니다.  

다름이아니라 
https://blog.naver.com/sp39871/221272622801

이런식으로 되어있는데 
주소를 치고 다운로더로 받으면 
맨위에 나와있는 표지로 올려놓은 이미지 하나만 받아지고
밑에 더보기를 눌러야 보이는 이미지들은 
받아지지를 않더라구요

더보기를 눌러서 이미지파일들을 다로딩시키고 다시 주소를 긁어서 한다해도
결과는 마찬가지구요. 
이런류는 어떻게 해야할까요?

**Comment by KurtBestor** [comment]
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

테스트 부탁드려요.

**Comment by TopGuunN** [comment]
오 잘되네요 펼치기 누르고 

주소붙여넣었더니 19장 다 잘받았네요 감사드립니다
