### ISSUE TITLE
다운로드 목록이 전부 지워졌습니다

### ISSUE THREAD

**Issue by marumar** [KurtBestor/Hitomi-Downloader-issues#239]
저장 후 종료는 항상 하는데

D:\hitomi downloader\hitomi_downloaded 여기에 파일과 폴더들은 전부 살아있음에도

다운로더에서 미리보기 등이 전부 지워졌습니다.

작가추천에 들어가면 400 여개의 작품번호가 남아있고

저장폴더에 있는 갤러리 넘버 복사하기를 하면

모든갤러리 넘버를 복사했습니다
성공414
실패254

라고 뜨는데 하나도 복사가 되지 않습니다.

**Comment by KurtBestor** [comment]
실행파일 경로 안에 `*.ini` 파일이 있을거예요. 거기에 목록이 저장돼요. 메일로 보내주시면 분석해볼게요.
