### ISSUE TITLE
깨진이미지 다운받아서 압축해버린당...

### ISSUE THREAD

**Issue by dlrauddlek** [KurtBestor/Hitomi-Downloader-issues#24]
![image](https://user-images.githubusercontent.com/35634939/35186036-0cfe35e0-fe51-11e7-88a7-40a2c90e1c2e.png)

1.9e버전인데 다운받으면 29개중 7 ~ 8개정도가 꺠진이미지다운받아짐
한 2~3번 다시다운받으면 잘받아지는경우도있고 이전버전은안그랬는데 최신버전업뎃하고 몇일지나니까 이런일이생겨브러쓰 그냥 그런일이있었다고 개발자찡에게 말해보고싶었음

**Comment by KurtBestor** [comment]
다음 두 가지를 mangrovn@gmail.com으로 보내주시면 분석해보겠습니다:
1. 해당 작업 마우스 우클릭 후 [정보... (I)]를 눌러서 나오는 내용
2. 다운로드 된 파일

**Comment by KurtBestor** [comment]
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

고친 버전입니다. 테스트 부탁드려요.

**Comment by KurtBestor** [comment]
v2.1b에서 해결됨
