### ISSUE TITLE
히토미 뷰어 문의 및 건의 사항

### ISSUE THREAD

**Issue by QNamelessQ** [KurtBestor/Hitomi-Downloader-issues#241]
안녕하세요. 우선 히토미 다운로더 제작해주셔서 감사합니다! 매우 잘 사용하고 있습니다.

 바로 본론으로 들어가자면, 히토미 다운로더에 '작가 추천' 기능을 사용해 보니 '뷰어'라는 기능이 내장 되어 있더군요. 그런데 분명 작가 추천에서는 1000명을 추천해줬는데 뷰어로 볼 때는 약 500명까지밖에 나오지 않더라고요.

 원래 이런 것인가요? 아니면 다른 오류에서 나타나는 현상인가요?
혹시 이것이 정상이라면 작가 추천에 나온 결과 1000개를 모두 뷰어에서 볼 수 있도록 개선해주셨으면 하는 바람입니다.

 긴 글 읽어주셔서 감사합니다.

**Comment by KurtBestor** [comment]
네, 일부러 500개까지만 했어요. 설마 그정도까지 볼 분이 있을 줄은 몰랐네요. 1000개로 고친 버전이예요. 테스트 부탁드려요.

https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by QNamelessQ** [comment]
정식버전에도 추가해주셨군요! 정말 감사드립니다!
