### ISSUE TITLE
Hitomi Searcher 에서 갤러리 번호 내림차순 나열

### ISSUE THREAD

**Issue by RaceDriverMIKU** [KurtBestor/Hitomi-Downloader-issues#245]
보통 검색창에서 가장 최신의 갤러리를 맨 위에, 높은 번호에서 낮은 번호로 내림차순으로 보여주잖아요, 옛날 자료를 찾기를 원한다거나 하는 이유등으로 내림차순 나열, 가장 오래된것부터 먼저 보여주는 기능이 있었으면 좋겠습니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요.
[검색기 - 옵션 - 검색 순서] 에서 설정할 수 있어요.

https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by RaceDriverMIKU** [comment]
역순 설정으로 여러 태그들 필터에 넣고, 안넣고 돌려보니까 정상적으로 작동합니다.
