### ISSUE TITLE
유튜브 다운로드 관련해서 질문드립니다

### ISSUE THREAD

**Issue by rlacks1237** [KurtBestor/Hitomi-Downloader-issues#247]
항상 수고가 많으십니다

다름이 아니라 유튜브 채널을 긁어서 다운로드하면 동영상쪽의 영상들을 다운을 받는데

한번에 최대 30개 정도가 한계인거 같은데 맞습니까?

혹시 늘릴수있다면 방법이 있나요

한번에 쭉 다운받을려 하는데

**Comment by rlacks1237** [comment]
+한가지 더 궁금한게 생겨서 질문드립니다
컨f로 나오는 탐색기는 히토미만 검색해주는건가요? 익헨은 안나오는거 맞는건가요?

**Comment by KurtBestor** [comment]
1. 네, 현재는 30개가 최대입니다.

2. 히토미만 검색합니다.

3. 검색 범위 안의 것들만 중복 제거합니다.
