### ISSUE TITLE
v.2.5 폴더 분류 문제

### ISSUE THREAD

**Issue by newtype0222** [KurtBestor/Hitomi-Downloader-issues#248]
늘 감사히 쓰고 있습니다.

현재 설정에서 폴더명 형식을
# type / artist] title (id)

으로 사용하여 다운로드 시 자동으로 분류가 되도록 했는데요
저번 업데이트 때도 그랬지만 이번 업데이트 때도 자동으로 폴더 분류가 되지 않고
파일 이름이 
# type / artist] title (id) 
식으로 저장되는 문제가 있습니다.

유사한 글이 있나 찾아봤지만 지난 업데이트 기준으로 되어있는지
Test 파일을 다운받아서 덮어봐도 수정이 안 되더라구요...

**Comment by KurtBestor** [comment]
v2.4 는 그렇지 않은 걸로 알고 있는데, 제가 잘못 알고있나요?

**Comment by newtype0222** [comment]
5개월 전 버젼이었는데... 중간에 제가 자동 업뎃을 해서 착각했던 것 같습니다.
2.3 버젼인가 보네요. 2.4는 별 문제 없었던 게 맞습니다. 혼동을 드려서 죄송합니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요.

https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by newtype0222** [comment]
방금 집에 와서 확인했습니다.
잘 되네요.
빠른 피드백 감사합니다.

2018년 9월 29일 (토) 오후 3:44, Kurt Bestor <notifications@github.com>님이 작성:

**Comment by ereshkigal25** [comment]
이것과 관련해서 
값이 없는 경우 (N/A)
N/A의 슬래쉬를 폴더 구분자로 인식하는 것인지 하위폴더를 하나 더 만드는 문제가 생겼습니다
예를들어 작가명이 N/A 라면 N 폴더가 만들어지고 그 아래에 나머지 이름이 들어가버립니다
확인 부탁드리겠습니다

**Comment by KurtBestor** [comment]
테스트 부탁드려요.

https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by ereshkigal25** [comment]
네 확인했습니다. 문제없이 잘 되네요
감사합니다
