### ISSUE TITLE
기본 데이터 다운로드가 되지 않습니다.

### ISSUE THREAD

**Issue by isss33** [KurtBestor/Hitomi-Downloader-issues#249]
![image](https://user-images.githubusercontent.com/43691018/46240224-0e4f4700-c3df-11e8-8634-24b97b293b43.png)

새 버전으로 업데이트 후 기본 데이터 다운로드를 하려고 했더니 해당 창이 뜨고 다운로드가 되지 않습니다.
삭제된 데이터 관련은 모두 문제없이 실행됩니다.
재설치도, 예전버전으로도 돌려도 안되네요. 해결방법을 알고싶습니다.

**Comment by isss33** [comment]
![image](https://user-images.githubusercontent.com/43691018/46250899-971dbf80-c47f-11e8-8d59-c1ac5dc89ff0.png)
이렇게 뜹니다

**Comment by isss33** [comment]
아직도 해결이 안되서 그러는데 답변 해주실수있나요 ㅠㅠ

**Comment by KurtBestor** [comment]
https://hitomi.la/search.html?female:loli%20male:shota

여기 접속 되나요?

**Comment by KurtCobane** [comment]
> https://hitomi.la/search.html?female:loli%20male:shota
> 
> 여기 접속 되나요?
접속이 됩니다.
