### ISSUE TITLE
다운로드시 지나친 저용량으로 저장되는 경우. (버그)

### ISSUE THREAD

**Issue by 68958274** [KurtBestor/Hitomi-Downloader-issues#25]
![01](https://user-images.githubusercontent.com/35635961/35186356-38f9a44a-fe56-11e7-835f-47a62998f18e.PNG)
![02](https://user-images.githubusercontent.com/35635961/35186357-3bdaf466-fe56-11e7-8041-0a8609652f30.PNG)
![03](https://user-images.githubusercontent.com/35635961/35186365-482626b4-fe56-11e7-8073-39e6a3f8c23a.PNG)

보통 망가하나당 mb단위인데
 kb 단위로 다운되는경우
이미지가 아예 안뜨는 문제점이 있음
삭제하고 다시하거나, 다시시작의 경우에도 해결되지않음

**Comment by KurtBestor** [comment]
다음 두 가지를 mangrovn@gmail.com으로 보내주시면 분석해보겠습니다:
1. 해당 작업 마우스 우클릭 후 [정보... (I)]를 눌러서 나오는 내용
2. 다운로드 된 파일

**Comment by KurtBestor** [comment]
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

고친 버전입니다. 테스트 부탁드려요.
혹시 설정에서 서버가 수동으로 되어있나요?

**Comment by 68958274** [comment]
오, 완전히 해결되었습니다. 설정에서 서버는 항상 자동이었습니다.

하지만 원래 kb단위로 다운된걸 프로그램에서 다시시작하는 경우에는 해결되지 않고
그 다운된 파일삭제를 한뒤에 웹페이지에서 다시 링크를 가져와서 받으니 문제가 해결되었네요
본래는 아예 kb단위로 사진조차 안떴거든요. 완벽한 해결입니다.


2018-01-21 18:06 GMT+09:00 Kurt Bestor <notifications@github.com>:

**Comment by KurtBestor** [comment]
해당 파일 지우고 다시 시도해보셨나요?

**Comment by Aleady-taken** [comment]
네, 다시 시도해봤는데도 그러더군요. 그래서 이전 1.9 버전들도 받아보고 했는데도, 처음 킬 때만 2개 정도 받아지고, 나머지는 KB단위 저장행이 됩니다.

**Comment by KurtBestor** [comment]
@Aleady-taken 
해당 작업 다운로드 완료된 후에 마우스 우클릭해서 [정보... (I)]를 누른 다음 나오는 내용을 보내주시면 분석해보겠습니다.

**Comment by KurtBestor** [comment]
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

일단 이걸로 테스트 부탁드려요.

**Comment by Aleady-taken** [comment]
정보 보내려고 했는데, 방금 올려주신 시험판 이용해 보니 잘 되네요. 여러 더 시도해 보고 추후에 문제 생기면 말씀드리겠습니다.

**Comment by KurtBestor** [comment]
v2.1b에서 해결됨
