### ISSUE TITLE
페이지 지정 다운로드

### ISSUE THREAD

**Issue by ldh7680** [KurtBestor/Hitomi-Downloader-issues#250]
호두코믹스에서 페이지 지정 다운로드를 하면
선택화가 다운이 아니라 총 이미지 중 해당 순번 이미지 받아지네요
예를 들면 1 ~ 3 지정하면 1,2,3화가 아니라
1화의 1,2,3,번째 이미지
23~25쯤하면 대략 2화쯤에 해당하는 그이미지가 받아지는 식이네요
마루마루 처럼 원하는 화를 받을 수는 없는건가요??

**Comment by KurtBestor** [comment]
네, 안돼요.
