### ISSUE TITLE
다운 받을때 작가 이름 별로 정리되게 하고 싶은데요

### ISSUE THREAD

**Issue by FRT222** [KurtBestor/Hitomi-Downloader-issues#252]
2.4 버전까진 됐었는데 2.5버전으로 업그레이드 하면서 저장경로가 초기화 되버려서요

저장경로 어떻게 셋팅했는지 까먹어서..

예를 들어서 A라는 작가의 작품을 하나 받았으면 hitomi_downloaded 폴더에 A라는 폴더가  새로 생성되고(이전에 A라는 작가 작품을 받은 적이 있어서 폴더가 생성 되있으면 그 폴더 안으로 저장) 

다운 받은 작품은 그 새로 생성된 폴더 안에 저장되는 식으로 설정하고 싶은데 저장경로 어떻게 설정해야하나요?

**Comment by KurtBestor** [comment]
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

이거 다운받아서 기존 실행파일에 덮어씌우신 다음 [옵션 - 설정 - 일반 설정 - 폴더명 형식]을 바꿔주세요.

**Comment by FRT222** [comment]
경로를 어떻게 설정해야하나요?

**Comment by FRT222** [comment]
감사합니다
