### ISSUE TITLE
재설치어떻게하나요?

### ISSUE THREAD

**Issue by buntail** [KurtBestor/Hitomi-Downloader-issues#254]
업데이트후 뭔가 많이 이상해졌더라구요...

파일 폴더별분류설정도 했는데 안되고.... 뭔가 오류가났는지 검색기 창부터 다릅니다;

재설치를하고싶어서 관련파일 다 삭제해도 그대로이고 2.4 버전을 받아서 실행해봐도 2.5버전으로실행되고...ㅠㅠ

![image](https://user-images.githubusercontent.com/42077863/46270379-3034ff00-c582-11e8-826b-31950e601802.png)

**Comment by KurtBestor** [comment]
오른쪽 위 파란색 스위치를 누르시면 고급 검색으로 변경돼요.

이전 버전은 다음 링크에서 받으실 수 있어요:
https://drive.google.com/drive/folders/0B8iYCPDKWc_NYU5KLS0tbzRWenM

폴더 분류 문제는 다음을 참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/248
