### ISSUE TITLE
히토미 기능 건의

### ISSUE THREAD

**Issue by ddt5244** [KurtBestor/Hitomi-Downloader-issues#255]
만일 히토미 작품을 10개 받았다고 했을때 다운받은 작품에 대해 우클릭하면 작가명 복사 기능이 있잖아요?

그 10개에 대한 작가가 여러명이 있을텐데 10개를 다 드래그 해서 작가명 복사를 누르면

작가가 A B C D 이렇게 있으면

A, B, C, D   <<<<<이렇게 복사가 되었으면 좋겠습니다. 왜냐하면 작가에 대해 다른 작품을 검색하고 싶은데 

일일이 한명의 작가씩 복사해서 붙여넣어서 찾고 또 다른작가 복사해서 붙여넣기 번거로워서요.

아 그리고 확인해보니까 검색창 작가부분에  and기능만 있는거 같은데 스위치처럼 해서 and 랑 or 2가지 기능을 넣는것부터 해야할거 같습니다. ㅠㅠ

**Comment by KurtBestor** [comment]
사용법 (F1) 보시면 나와있어요.
동봉된 Readme.txt 맨 아래에 더 자세히 적혀있어요.

작가 A, B 둘중 하나 이상 포함하는 작품을 검색하려면 다음과 같이 입력하면 됩니다:
```
A + B
```

복사하면 `A + B + C + D` 이렇게 되도록 나중에 기능 구현해볼게요.
