### ISSUE TITLE
마루마루에 있는 만화 전부 한번에 다운받을 수있나요

### ISSUE THREAD

**Issue by ghost** [KurtBestor/Hitomi-Downloader-issues#257]
일일히 만화 시리즈 하나씩 다운 받기가 힘들어서 마루마루에 있는 완결만화 다 다운받고 싶네요. 혹시 가능한가요. 불가능하면 마루마루 만화 검색기능 추가해주세요

**Comment by KurtBestor** [comment]
불가능해요. 검색은 직접 사이트에서 하세요.
