### ISSUE TITLE
검색기 다운로드가 8월 3일로 게속 생깁니다.

### ISSUE THREAD

**Issue by BaekwooLife** [KurtBestor/Hitomi-Downloader-issues#259]
데이터를 삭제하고 오늘걸로 했다가 잠시후에 다시 끄고 켜보면 8월 3일로 되어 있습니다.

도와주세요 ㅠ

**Comment by KurtBestor** [comment]
데이터를 어떻게 삭제했나요?

**Comment by BaekwooLife** [comment]
> 데이터를 어떻게 삭제했나요?

hitomi_data 폴더를 삭제했는데여

**Comment by KurtBestor** [comment]
삭제하지 않고 그냥 다운받으셔도 돼요.

**Comment by BaekwooLife** [comment]
다운이 안되던데요

**Comment by KurtBestor** [comment]
어떻게 안되나요?

**Comment by BaekwooLife** [comment]
이렇게 안되네요.

Traceback (most recent call last):
  File "hitomi_downloader_GUI", line 1974, in dataDownload
  File "hitomi_searcher", line 220, in download_json
IOError: [Errno 13] Permission denied: u'C:\\WINDOWS\\system32\\hitomi_data\\completed_v2.3c'

**Comment by KurtBestor** [comment]
[Ctrl + Alt + C] 눌러서 콘솔 연 다음 `sys.argv, sys.path` 입력하고 Enter 누른 다음 나오는 내용 알려주세요.

**Comment by BaekwooLife** [comment]
그냥 관리자권한으로 실행하니까 되네여 감사합니다
