### ISSUE TITLE
히토미 특정 항목 다운로드 불가 오류(아마도 폴더명 길이로 인한 오류 같습니다.)

### ISSUE THREAD

**Issue by hny2798** [KurtBestor/Hitomi-Downloader-issues#260]
https://hitomi.la/galleries/1261548.html
[Gujira][Otokonoko Soft][1261548] Netorare Otoko no Ko \~Ore no Osananajimi no Mujaki na Otoko no Ko ga Masaka Sobou na Taiiku Kyoushi ni Yowami o Nigirarete Choukyou Sarete Itsu no Ma ni ka Kairaku ni Oborete Aheahe Double Peace de Video Satsuei Sarete Yorokondeita Da Nante!!~
상기 링크 다운로드 진행시 사이트 상에서는 잘 보였는데 다운로더에서는 다운로드 진행을 하지 않고 회색상태입니다(수정 다시보니 작품명이 회색에서 주황색 상태로 바뀌고 페이지수는 안뜨고 계속 재시도만 합니다) 캐시 및 프로그램을 삭제후 최신버전 다시 압축 풀어서 진행시에도 진행되지않고있습니다. 다운로드 폴더에는 폴더가 생성되지 않으며 파일명은 원본 파일말고 숫자파일명이며 폴더명 형식은 상기에도 적어놓았지만 [artist][group][id] title 입니다 별도 에러문구는 못본것같은데 확인 부탁드립니다.
혹시 상세 자료가 필요하시면 답신 부탁드립니다.

**Comment by KurtBestor** [comment]
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

폴더명 길이가 255를 넘으면 생성이 안되네요. 255를 넘어가면 적당히 자르도록 했습니다.
테스트 부탁드려요.

**Comment by hny2798** [comment]
해당 링크 건에 대하여 테스트 시 문제없이 잘 받아졌으나 검색시 이미 다운완료 상태인데도 녹색 v 체크 표시가 되지않았습니다
아마 폴더명에 글자 제한을 두는과정 때문에 검색에서 동일성 체크시 실제 제목과 차이가 발생하여 다운받은적없다라고 판단하는것 같습니다. 
실제 재 다운로드시에는 처음받는것처럼 중복으로 다운로드 없이 파일들을 훑어나가면서 이미 다운받은것이라고 인식되었습니다. 사용에는 문제가 없으므로 이대로 처리문을 삽입하셔도 될것이고 혹시 완성도를 조금더 올리고자하신다면 검색시 기 다운로드항목체크(녹색 v 체크 표시)에도 유사 처리가 필요할것같습니다.
그런데 설마라고 생각하지만 저런  긴 제목으로 추가로 2편을 내놓지는 않겠죠?
그런 것까지 감안하면 예외 처리에 너무 변수가 많아질것 같습니다.
적당히 걸러들어주세요

**Comment by KurtBestor** [comment]
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

테스트 부탁드려요.
