### ISSUE TITLE
2.5버전 패치이후 검색기 gui

### ISSUE THREAD

**Issue by usdid** [KurtBestor/Hitomi-Downloader-issues#261]
오늘 2.5 버전으로 업데이트 이후 검색기 gui의 매뉴가 바뀐거 같은데 검색어 부분이외는 다 삭제가 되었나요?

**Comment by KurtBestor** [comment]
검색기 오른쪽 위 스위치 눌러서 고급 검색으로 바꾸실 수 있어요.

**Comment by usdid** [comment]
이렇게 간단한것을 감사합니다.
