### ISSUE TITLE
검색범위 이동 기능

### ISSUE THREAD

**Issue by totle91** [KurtBestor/Hitomi-Downloader-issues#262]
안녕하세요! 좋은 프로그램 만들어주셔서 감사합니다!

예전 버전엔 검색 범위 숫자에 클릭한 상태로 위아래로 100개, 좌우로1개씩 이동이 가능했는데

그 기능을 다시 만들어주실 수 있나요?

**Comment by KurtBestor** [comment]
직접 숫자 입력해서 바꾸는 걸로 바뀌었어요.

다음 요청으로 바뀐 기능이에요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/103

**Comment by totle91** [comment]
그렇군요, 감사합니다!
