### ISSUE TITLE
핀터레스트 저장이 최대 2000장밖에 되지 않습니다.

### ISSUE THREAD

**Issue by bwcat2** [KurtBestor/Hitomi-Downloader-issues#263]
2000장이 최대로 저장되서 어디까지 받았는지 확인도 불가하고 2000장씩 끊어서 받을 방도도 없습니다.. 제한이 되있는건지 확인 부탁드립니다

**Comment by KurtBestor** [comment]
네, 현재는 2000개로 제한되어있어요.
