### ISSUE TITLE
히토미 다운로드 시  # 타입 /  형식의 폴더가 생성되지 않아요

### ISSUE THREAD

**Issue by kikinet88** [KurtBestor/Hitomi-Downloader-issues#264]
오래전에도 이러한 문제로 문의를... 드렸던거 같은대..
이번에도 그렇습니다

폴더로 설정되지 않고  파일명에  타잎이 붙어서 출력되고 있습니다

**Comment by KurtBestor** [comment]
Duplicate of #248
