### ISSUE TITLE
다운 받은 날짜 표시 기능 건의 드립니다.

### ISSUE THREAD

**Issue by Gilmon96** [KurtBestor/Hitomi-Downloader-issues#265]
지금은 다운로더 목록에 보면 제목, 아이콘, 페이지 수, 용량 정도만 표시되는데

여기에 받은 날짜도 조그마나게 18-10-08 이런 식으로 표시할 수 있었으면 좋겠네요

항상 유용하게 사용하고 있습니다. 늘 감사드려요.

**Comment by KurtBestor** [comment]
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

테스트 부탁드려요. [옵션 (Options) - 설정 - 고급 설정 - 다운로드 날짜 표시] 체크하시면 돼요.
