### ISSUE TITLE
겔부루 다운로드시 여러 테그 적용하면 이미지를 인식을 하지 못합니다.

### ISSUE THREAD

**Issue by rkfmwof13** [KurtBestor/Hitomi-Downloader-issues#266]
겔부루 다운로드시 태그를 2개 이상 설정하면 아예 다운로드가 되지 않습니다.

단일 테그로 검색하여 시도하였을때는 문제가 없으나 2개 이상의 테그를 사용하면 이런 현상이 일어납니다.

혹시 저만 그런건가요?

이전 이슈들 중 겔부루 이미지 다운로드 문제에 관한 이슈에서 작업정보 내역 올려달라고 하신걸 보아 작업작업정보 첨부하갰습니다.

rating：explicit kashiwazaki_sena

gal_num: https://www.gelbooru.com/index.php?page=post&s=list&tags=rating%3aexplicit+kashiwazaki_sena
dir: hitomi_downloaded_gelbooru\rating：explicit kashiwazaki_sena
zip: 
type: gelbooru
artist: None
url: https://www.gelbooru.com/index.php?page=post&s=list&tags=rating%3aexplicit+kashiwazaki_sena
valid: True
done: True
range: None
range_p: None
single: False

[Gallery]
None

[File Names]

[URLs]

[Messages]
https://gelbooru.com/index.php?page=dapi&s=post&q=index&tags=rating%3Aexplicit%2Bkashiwazaki_sena&pid=0&limit=100
done : https://www.gelbooru.com/index.php?page=post&s=list&tags=rating%3aexplicit+kashiwazaki_sena

**Comment by KurtBestor** [comment]
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

테스트 부탁드려요

**Comment by rkfmwof13** [comment]
> https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview
> 
> 테스트 부탁드려요

테그 5개까지 넣어봣는대 잘 작동합니다.

감사합니다.
