### ISSUE TITLE
작가 추천 기능은 어떻게 사용하는건가요?

### ISSUE THREAD

**Issue by nitrobenjen** [KurtBestor/Hitomi-Downloader-issues#269]
다운로드를 할 때 상위 태그 - 작가 - 각 하위폴더에 다운로드를 받거든요.
그런데 작가추천을 눌러도 작품목록이 안나오길래 설정에서
다운받은 폴더로 바꿔보니 목록이 뜨긴 하는데요.
다음 눌러도 데이터가 없습니다. 검색기에서 데이터를 다운로드 하라고 나오거든요.

그래서 검색기 누르고 삭제된 데이터 다운로드를 해보니
목록에서 지웠던 작품들이 주루룩 뜨긴 하는데
이 다음에 어떻게 진행해야하는지 알 수가 없네요.
도움말 사용법을 살펴봐도 이 기능에 대한 내용은 없고, 도움말같은게 존재하지 않나요?

**Comment by KurtBestor** [comment]
[검색기 - 메뉴 - 기본 데이터 다운로드...] 를 눌러서 데이터를 다운로드한 후에 사용 가능해요.
