### ISSUE TITLE
바이러스로 인식되요

### ISSUE THREAD

**Issue by 654453** [KurtBestor/Hitomi-Downloader-issues#27]
https://imgur.com/a/qXFuO

비트디펜더 사용 중입니다.

위 링크에 있는 이미지와 같이 인식하면서 계속 검역소로 이동하네요.

2.1 최신 버전에서 이럽니다 이전엔 안그랬어요

**Comment by KurtBestor** [comment]
패키징 툴을 바꿨더니 그걸 오진하네요.

![bd](https://user-images.githubusercontent.com/14768120/35197234-eb908fb4-ff1f-11e7-915c-cc081aa85e32.png)
카스퍼스키를 지워보기도 하고 재부팅도 했는데 설치가 계속 안돼서 확인은 못해봤습니다.

예외 목록에 추가하거나, 비트디펜더 측에 False Positive 제보를 하셔야 할 것 같습니다:
https://www.bitdefender.com/submit/

**Comment by KurtBestor** [comment]
v2.1b에서 해결됨
https://www.virustotal.com/#/file/f909e612cc6d60ecf39fe5101177c7a0294b9d0fb6e24c6fbdcbdfee5df314ff/detection
