### ISSUE TITLE
몇몇 히토미 작품들 404

### ISSUE THREAD

**Issue by rlacks1237** [KurtBestor/Hitomi-Downloader-issues#270]
한꺼번에 우르르 다운을 받아서 검색기 기본 데이터 인지 삭제된 데이터인지 잘 모르겠는데
아마 삭제된 데이터인거같습니다
번호만 적겠습니다
1266219
1269065
1266219
1055990
1269065

**Comment by KurtBestor** [comment]
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

테스트 부탁드려요. 이제 다운로드 될 거예요.

**Comment by rlacks1237** [comment]
위 번호들은 다 됩네요~ 감사합니다

**Comment by rlacks1237** [comment]
> 한꺼번에 우르르 다운을 받아서 검색기 기본 데이터 인지 삭제된 데이터인지 잘 모르겠는데
> 아마 삭제된 데이터인거같습니다
> 번호만 적겠습니다
> 1266219
> 1269065
> 1266219
> 1055990
> 1269065
