### ISSUE TITLE
올려주신 스크립트 변경 문의사항

### ISSUE THREAD

**Issue by rabirabin** [KurtBestor/Hitomi-Downloader-issues#271]
밑에 게시글중 호두코mix 스크립트 다운받아서 hodu 뒤에 숫자붙어있는것들 다 최근걸로바꿨는데 안되네요....프로그래밍 잘할줄몰라서....혹시 뭐바꿔야하는지알수있을까요 ㅠㅡㅠ

**Comment by KurtBestor** [comment]
지금 해보니 스크립트 수정 없이도 잘 되는데요. 스크립트랑 프로그램 최신버전인지 확인해주세요.

그래도 안 되면 해당 작업 마우스 우클릭 후 [정보... (I)] 눌러서 나오는 내용 알려주세요.

**Comment by rabirabin** [comment]
#coding: utf8
#title: 호두코믹스 사이트 추가
#author: Kurt Bestor

import downloader
from utils import Downloader, Soup, LazyUrl, try_n
import phantomjs
from time import sleep
import re
import os
from fucking_encoding import clean_title
from translator import tr_
DOMAIN = 'hodu14.com'


class Page(object):
    def __init__(self, onclick, title):
        self.onclick = onclick
        self.title = title
        self.id = re.findall('view/([0-9]+)', onclick)[0]
        self.url = 'https://{}/webtoon/view/{}'.format(DOMAIN, self.id)


class Image(object):
    def __init__(self, page, i, url):
        ext = os.path.splitext(url)[1]
        filename = u'{:04}{}'.format(i, ext)
        self.filename = u'{}/{}'.format(clean_title(page.title), filename)
        def f(page_url):
            return url
        self.url = LazyUrl(page.url, f, self)


class Downloader_hodu(Downloader):
    type = 'hodu'
    URLS = ['hodu14.com', 'regex:hodu[0-9]+.com']
    icon = 'https://kurtbestor.github.io/res/hodu.png'
    def init(self):
        global DOMAIN
        self.url = self.url.replace('hodu_', '')
        domain = re.findall('hodu[0-9]+.com', self.url)
        if domain:
            domain = domain[0]
        else:
            domain = 'hodu14.com'
        DOMAIN = domain
        self.url = 'https://{}/webtoon/list/{}'.format(domain, self.id)

    @property
    def id(self):
        try:
            return int(self.url)
        except:
            return re.findall('/list/([0-9]+)', self.url)[0]

    def read(self):
        cw = self.customWidget

        for try_ in range(8):
            try:
                html = downloader.read_html(self.url)
                break
            except Exception as e:
                print e
        else:
            raise e

        soup = Soup(html)
        title = soup.find('title').string
        if u'호두코믹스' in title:
            title = title.replace(u'- 호두코믹스', '').strip()
        else:
            raise Exception('No hodu')
        title = clean_title(title)

        pages = []
        for tr in soup.findAll('tr', class_='episode_tr'):
            onclick = tr.attrs['onclick']
            title_ = tr.find('div', class_='episode_subtitle').string
            page = Page(onclick, title_)
            pages.insert(0, page)

        driver = phantomjs.start()

        try:
            imgs = []
            for p, page in enumerate(pages):
                try:
                    page = read_page(driver, self.url, page, cw)
                except Exception as e:
                    cw.print_(u'Failed to read page: {}\n{}'.format(page.title, e))
                    continue

                for i, img in enumerate(page.imgs):
                    img = Image(page, i, img)
                    imgs.append(img)
                    self.title = u'{} - {}    [{}/{}]    ({})'.format(title, page.title, p+1, len(pages), len(imgs))
                if cw is not None and not cw.alive:
                    break
        finally:
            driver.close()

        for img in imgs:
            self.urls.append(img.url)

        self.title = title
Downloader.register(Downloader_hodu)


@try_n(2)
def read_page(driver, url_list, page, cw=None):
    print 'read list...'
    driver.get(url_list)
    print 'read page...'
    driver.execute_script(page.onclick)

    for t in range(120):
        if cw is not None and not cw.alive:
            imgs = []
            break

        print 'waiting...'
        sleep(1)
        html = driver.page_source

        if 'accounts.google.com' in html:
            raise Exception('Google')
        if u'웹툰이 없습니다' in html:
            raise Exception('No webtoon')
        soup = Soup(html)
        viewer = soup.find('div', id='app_img')
        if viewer is None:
            continue
        imgs = viewer.findAll('img')
        if not imgs:
            print 'no imgs'
            continue
        if 'checking your browser before accessing' not in html.lower():
            break
    else:
        raise Exception('hodu timeout')

    page.imgs = []
    for img in imgs:
        page.imgs.append(img.attrs['data-original'])

    return page


messageBox(u'{}: hodu'.format(tr_(u'사이트를 추가했습니다')))

그 제가 이런거 건드릴줄몰라서 호두8 >>호두14 이런식으로 일일이 ctrl+f 로 호두 찾아서 뒤에 숫자만 바꿨거든요!! 이렇게하는게 맞나요?

**Comment by KurtBestor** [comment]
해당 작업 마우스 우클릭 후 [정보... (I)] 눌러서 나오는 내용 알려주세요.

**Comment by rabirabin** [comment]
악 지금 외부나와있어서 잠시만요! 들어가서 올리겠습니다!! ㅠㅠ

**Comment by rabirabin** [comment]
아 제가 최신아닌걸받았나봐요 근데 다른거 ㅎㅎ...

**Comment by rabirabin** [comment]
몇개는잘됩니다! 근데 invalid 뜨는파일이 좀많아서 이거 확인부탁드려도될까요?

**Comment by rabirabin** [comment]
아 제가 최신아닌걸받았나봐요 잘됩니다!!!감사합니다!!!싸랑합니다!!!!!!!!!
