### ISSUE TITLE
중복 파일 한번에 삭제하는 기능 추가 요청

### ISSUE THREAD

**Issue by GoopyAspirin** [KurtBestor/Hitomi-Downloader-issues#274]
안녕하세요.

늘 좋은 프로그램, 꾸준히 업데이트해주셔서 감사합니다.

중복 파일에 대해 제거하는 기능을 추가해주셨는데..

중복 파일이 많을 경우 일일히 Del 키를 눌러 삭제해야한다는것에 충격입니다.. 너무 많아서요..

한번에 일괄로 중복 파일을 삭제하는기능 추가 부탁드리겠습니다.

감사합니다.

**Comment by KurtBestor** [comment]
`Shift + 클릭`으로 여러 개 선택해서 지우실 수 있습니다.
