### ISSUE TITLE
겔부루 태그 다운로드시 다운되는 이미지 수가 검색된 이미지 수보다 작은 이유가 무엇인가요

### ISSUE THREAD

**Issue by dullahan00** [KurtBestor/Hitomi-Downloader-issues#275]
제목 그대로입니다. 항상 다운로드하는데 이미지 수가 많은 작가들 것을 보면 다운로드 된 이미지가 적게는 10여개, 많으면 몇백개 차이도 나더라고요. 그 이유가 뭔지 알려주실 수 있으신가영

**Comment by KurtBestor** [comment]
실제 갯수와 표시되는 갯수가 달라요.
참고해주세요: #217
