### ISSUE TITLE
기능 추가와 성능 개선 문의드려요 181023

### ISSUE THREAD

**Issue by sa4ga** [KurtBestor/Hitomi-Downloader-issues#276]
기능 추가와 성능 개선 문의드려요

안녕하세요. 프로그램을 가끔씩 써보면서 만들고 공개해주시는 것에 대해서 정말 멋지다고 생각하고 있습니다.

글을 드릴까 말까 고민하다가 나름 몇가지만 적었다고 생각하는데도 많이 기네요. 길게 많이 부탁드려 죄송합니다.

 　

성능 개선에 대해서도 문의드리고 싶지만, 
제가 쓰는 컴퓨터가 구형 보급형이기도 하고, 지금의 방식으로는 어차피 누적하여 이용하게 되면 ini 파일을 초기화하지 않는 이상 다시 많은 자원을 이용하느라 느려지게 될 것이니 후순위로 두고, 기능 추가에 대해서 우선적으로 먼저 건의드려요.

이런저런 자료들을 시험삼아 내려받아 보았습니다.

예를 들어, 인스타그램의 한 계정을 전체 내려받기 할 때 처음에 100장을 잘 받았습니다. 그 뒤에 그 계정의 사진 20장이 비공개가 되거나 삭제되고 30장이 추가된 다음, 다시 전체 내려받기를 작동하면, 새롭게 110장의 목록을 모두 읽은 다음 내려받아서 덮어씌우는 것 같더군요. 즉 최근 내려받은 일시의 파일 110장과 비공개가 된 사진 20장까지 더해서 총 130개요.

문의1
6월 2일에 인스타그램 전체 내려받기를 한 다음 6월 29일에 똑같은 작업을 하면, 겹치는 파일의 수정 날짜도 모두 29일로 바뀌던데요. 이건 덮어씌워서 그러는 것 같더라고요.
1-1
예전에 전체를 받은 적이 있는 인스타그램 계정에서 이후에 또다시 전체 내려받기를 할 때, 계정의 자료 목록을 전체를 다시 읽어야 하는 것은, 지금으로서는 꼭 해야 하는 것인가요?
다운로더의 ini 파일의 정보나, 다운로드 폴더에 남아있는 파일의 최근 마지막 날짜가 [18-06-02] 일 경우, 마지막 다운로드가 02일 아침이며 그 뒤로 저녁에 이 계정에 새로운 사진이 올라왔을 가능성을 감안하여 다시 받을 때에는 자료 읽기를 [18-06-01] 또는 [18-06-02] 부터 하는 것은 어려울까요?
1-2
이것이 어렵다면, 목록은 전체를 읽어와야 하더라도, 다운로드 내려받기 만이라도 [18-06-01] 또는 [18-06-02] 부터 하는 것은 가능할까요?
1-3
어렵다면, 메모리까지는 내려받고 읽어오더라도, 디스크에 만들려고 하던 파일과 같은 이름의 파일이 이미 있다면, 내려받지 않게 해주셨으면 해요. 정 어렵다면 덮어쓰지 않거나, 물어보거나, 어차피 다 받은 것 지우기 아깝다고 하시면 (2)이나 [3] 을 뒤에 붙여주는 기능은요?
파일의 CRC 값을 비교하여 결정하는 기능은 얻는 것보다 잃는 것이 더 클 것 같네요.

문의2
몇몇 기존 범용 다운로더를 보면, 파일이 위치한 서버에서 파일의 (생성) 일시를 읽어와서 처음부터 그렇게 받거나 받고 나서 일시를 서버의 자료 기준으로 바꿔주는 기능이 있더라고요.
많은 성능과 추가 작업이 필요할 것 같고, 반드시 필요한 기능은 아니지만, 혹시 구현이 크게 어렵지 않고 가능하시다면 선택사항으로 넣어주시는 것도 고려해봐주시길 부탁드려요.

문의3
ini 데이터베이스 파일은 지금으로서는 오래 쓰고 기록을 유지 증가시킬수록 비례해서 커지고 작업이 오래 걸리는 것 같더라고요. 이것은 꼭 필요하다면 감당할 수 있는 것입니다만 혹시나 해서 문의드려요.

상황
지금의 ini파일을 보면, 첫 부분은 다운로더와 검색기의 기본 설정, 이후 자료 목록의 정보와 썸네일 이미지 자료의 데이터 또는 인터넷 주소, 서브 폴더가 아닌 절대 경로 디렉토리 주소를 포함한 검색어 입력값, (인스타그램) 받은 자료들의 인터넷 파일 이름과 목록 등등이 함께 있는 것 같더라고요.
최근에 2.4를 이용하면서 목록을 저장하는데, 중간에는 평소대로 잘 되었습니다.
그 뒤에 조금 더 이용할 때와 종료할 때, 
'저장 실패' 그리고 '저장에 실패했습니다. 무시하고 종료하시겠습니까?'
Traceback (most recent call last):
 File "hitomi_downloader_GUI", line 268, in write_config_safe
 File "hitomi_downloader_GUI", line 423, in write_config
 File "ConfigParser", line 277, in write MemoryError
이렇게 뜨는 것은 이때 처음 봤습니다.
더군요. 일단 중간에 저장 잘 된 ini 파일을 백업하고, 자료 손실을 각오하고 종료를 시도하고 이것저것 해보니 어쩌다보니 일단 종료는 된 것 같고 백업도 잘 된 것 같은데, 용량이 줄어들어서 70% 정도의 크기가 되었더군요. ini파일의 최적화 혹은 누락 자료 삭제는 아닌 것 같고 자료 손실 같아서 두 파일을 비교해보았는데도 잘 모르겠더라고요.
ini 파일을 치워두고 경고문을 보면서 2.5로 자동 업데이트를 한 상태입니다.

 　

일단 저는 이번 일을 겪으며 생각한 것이, 이 다운로더의 목록 자료 보존은 포기하는 것이 나은가 하는 고민이었습니다.
자료 누적으로 통계를 낼 수 있는것은 히토미 사이트 자료 뿐이고, 그마저도 파일이 남아있고 ini에 목록 자료가 있어야 하는 것 같더라고요.
그리고 인스타그램은 표시 이름이 달라지면 새로운 폴더를 만들어 새롭게 받는데, 같은 계정 같은 이름이어도 주소 입력창에서 추가를 하면 기존 목록이 갱신되는 것도, 지워지는 것도 아니고 똑같은 것이 새롭게 추가가 되더군요. 제가 이용해본 상황에서는 갱신을 하려면 ctrl F 로 목록 이름이나 일자 검색 혹은 이동을 하지 못하고 직접 스크롤하여 찾아야 하는데, 다른 사이트 서비스들도 섞여서 많으면 그것도 어려울 것 같고, 그걸 잘 찾는다고 해도 ini파일 중복 방지 외의 이득은 없어보이더라고요.
일단 여러 폴더를 새로 만들어서, 정션 대신 그 폴더들에 hitomi_downloader_GUI.exe, phantomjs.exe, 그리고 최소한의 설정값만 저장된 hitomi_downloader_GUI.ini 파일을 모두 각각 복사해준 뒤, 한 폴더는 인스타그램만, 한 폴더는 특정 사이트 웹툰만 받는 식으로 해볼까 생각중입니다.

3-1
혹시 ini파일의 분리 저장 혹은 통합 저장을 하더라도 프로그램 처리 차원에서의 분리 관리가 가능하실까요?
hitomi_downloader_GUI_insta.ini, hitomi_downloader_GUI_youtube.ini, hitomi_downloader_GUI_launcher.ini 라는 식으로요.

3-2
어차피 서버에서 파일 시간을 읽어오거나, 서버에서 증분된 자료만 골라서 읽거나 받는 것이 어렵다고 하시면, 히토미처럼 작가 추천 등의 부가기능이 없는 이상 ini 저장 항목을 조금 줄이면 처리가 더 빨라질 것 같아서 드리는 문의입니다.
ini파일의 자료 저장 수준을 이용자가 선택 가능하게 해주실 수 있을까요?
저사양 체계 이용자 또는 빠른 처리 속도를 바라는 이용자들을 위해서, ini 파일에 썸네일과 파일 이름과 인터넷 주소 등을 저장하지 않고, 단순히 받은 폴더 이름과 일시 정도만 저장할수도 있게 선택기능을 주신다면 어떨까요.

이번에 2.4에서 저장 문제를 겪으면서 일부 손실된 자료, 직전의 큰 ini파일은 있는데요. 이것을 서비스별로 나눈 각각의 폴더에 복사해서 전체를 불러온 다음, 그 서비스에 해당하는 것만 남기고 나머지를 지우는 편집을 한 다음 이용해볼까 하면서 든 생각들입니다.
3-3
다운로더의 목록을 편집할 수 있을까요?
끌어 옮기기로 목록의 순서 바꾸기
서비스별로 목록 나누어보기, 접어두기
인스타그램 계정주인의 표시 이름이나 주소가 바뀌었을 경우 자동 혹은 수작업으로 이름 바꾸어주어서 중복 또는 또 받기 방지하기
꼬리표 라벨링 태그 또는 임의의, 혹은 표시된 작가 등으로 그루핑하여 묶어두기 또는 검색 가능하게 하기
목록의 백업하여 CVS 등으로 내보내기와 불러 읽어오기, 부분 복구하기
이런 기능들요.

　

 

많은 내용을 많이 요약하지 못하고 길게 남겼네요.
줄바꿈이 한줄씩만 되는줄은 몰랐습니다 처음이라서요.
읽어봐주셔서 고맙습니다.
항상 건강하게, 기능 개선하시면서 행복하실 때가 더 많으시길 바라겠습니다.

**Comment by sa4ga** [comment]
( _ _)
고맙습니다~~!!

**Comment by KurtBestor** [comment]
1. 한번 다운로드 한 파일은 파일 크기가 일정 이상 되면 다시 다운로드하지 않아요. 종종 이미지 순서가 뒤죽박죽이다라고 하는 분들이 있는데, 대부분 이미지 뷰어 정렬을 수정된 날짜 순으로 해서 그래요. 동시에 다운로드를 하기 때문에 수정된 날짜 순서가 일정하지 않거든요. 그래서 수정된 날짜를 모두 동일하게 바꾸게 했어요.

2. Windows야 생성 날짜가 표준이지만, 리눅스 같은 경우 그렇지 않아요. 서버에서 생성 날짜를 지원하지 않는 경우도 있고, 있더라도 이상하게 되어있는 경우도 있어서, 생성 날짜는 그대로 두는 게 좋을 것 같아요.

3. [메뉴 - 파일 - 선택된 작업들 내보내기... / 작업들 가져오기...] 로 작업 목록을 내보내고 가져올 수 있어요. 작업들을 내보내고 목록을 모두 지우시면 INI 파일 크기가 작아질거에요.
알려주신 에러메시지는 메모리가 부족해서 나오는 메시지에요. 작업 목록이 너무 많아서 저장하지 못하는 건데, 작업 목록을 정리하시거나, 작업 일부를 내보낸 다음 목록에서 삭제하시면 메모리를 확보할 수 있을거에요.
INI 파일에 남아있지 않아도 파일만 남아있다면 통계엔 들어가요.

- 썸네일이나 주소를 저장하지 않는다고 처리 속도는 그다지 달라지지 않아요. 메모리를 차지하는 가장 큰 원인은 프로그램상에서 보이는 작업 UI 그 자체입니다. 썸네일을 저장하지 않는다면 INI 파일 크기는 작아지겠지만요.

- 끌어 옮기기로 목록의 순서 바꾸기
[메뉴 - 도움말 - 사용법 - 다운로더 목록 순서 변경] 을 참고해주세요.
- 서비스별로 목록 나누어보기, 접어두기
[메뉴 - 도움말 - 사용법 - 다운로더 목록 필터링] 을 참고해주세요.
- 인스타그램 계정주인의 표시 이름이나 주소가 바뀌었을 경우 자동 혹은 수작업으로 이름 바꾸어주어서 중복 또는 또 받기 방지하기
현재는 트위터, 픽시브만 자동으로 폴더명 바꾸게 되어있는데, 테스트 버전에 인스타그램도 추가했어요.
- 목록의 백업하여 CVS 등으로 내보내기와 불러 읽어오기, 부분 복구하기
3번 참고해주세요.

테스트 버전 링크예요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview
테스트 부탁드려요.

빠뜨린 것 있으면 알려주세요.

**Comment by KurtBestor** [comment]
1. 전체 게시물을 읽는 게 꼭 필요한 것은 아니지만, 최근 것만 읽는다면 오래된 비공개 게시물을 공개한다거나 하는 경우에 사진을 빠뜨릴 수 있기 때문에 그다지 좋은 방법은 아닌 것 같아요.

2. 네, 이미지 정보를 읽긴 하지만 이미 다운로드 된 파일이 있다면 다운로드하지 않아요.

3. 네, 저장할 때 필요한 메모리 이용량이 있어요. 프로그램 오른쪽 하단 보시면 다량의 작업 목록을 저장할 때 메모리 사용량이 증가하는 걸 볼 수 있어요.

4. 예전엔 완료된 URL을 저장했었는데, 지금은 완전히 완료된 작업에 한해서 저장하지 않아요. 또한 시스템 DPI가 표준보다 높을 때 저장하는 썸네일의 크기가 달라서 DPI가 높을 때 파일 크기가 비례해서 커지는 문제가 있었는데, 이것도 나중에 고쳤어요. 이런 것들 때문에 용량이 작아졌을 수도 있어요.

5. `목록 - 파일 - 작업들 가져오기...` 를 하면 작업들이 대체되는게 아니라 추가돼요. A.INI 파일을 읽고 작업 목록을 저장하고, B.INI 파일을 읽어서 저장했던 작업 목록을 불러오는 식으로 하면 합칠 수 있어요.
