### ISSUE TITLE
원본 자료와 다운받은 자료의 용량이 상이한 문제

### ISSUE THREAD

**Issue by bloodza** [KurtBestor/Hitomi-Downloader-issues#277]
안녕하세요. 
다름이 아니라 제목에도 말했듯이 예를 들자면 원본 자료는 218.1 MB 인데 
다운받은 자료는 112 MB 인 경우 처럼
대부분의 자료들이 이런식으로 압축(?) 된 형태로 다운 받아지는데요.
단순 서버 문제인가 해서 hitomi -> exhentai 로 바꿔 보기도 하고 했지만 그대로네요.
의도하신 부분인지 궁금해서 질문 드립니다.

**Comment by KurtBestor** [comment]
네. 현재는 웹에서 보이는 이미지를 다운로드해요. 이 이미지는 히토미 / 이헨 / 익헨 모두 동일해요.

**Comment by bloodza** [comment]
아 그렇군요... 답변 감사합니다.
