### ISSUE TITLE
갤부루나 산카쿠 등 다운로드시 태그에 특정 문자열이 포함되면 인식이 불가합니다

### ISSUE THREAD

**Issue by ereshkigal25** [KurtBestor/Hitomi-Downloader-issues#278]
fujimaru_ritsuka 라는 태그로 다운로드를 시도하니 마루마루로 인식하여 invaild 됩니다

![image](https://user-images.githubusercontent.com/42225667/47524948-0a77ed00-d8d7-11e8-9a44-1b3c1ef96ed2.png)

**Comment by KurtBestor** [comment]
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

테스트 부탁드려요.

**Comment by ereshkigal25** [comment]
잘 작동합니다
감사합니다.
