### ISSUE TITLE
삭제된 데이터에서 검색이 안되는 작품이 몇개있습니다

### ISSUE THREAD

**Issue by siwkd2** [KurtBestor/Hitomi-Downloader-issues#279]
삭제된 데이터에서 일부 검색이 되지않는것으로 확인되었는데요

(즉 익헨싸이트에서도 데이터가 지워지고

프로그램에 있는'삭제된 데이터'에서도 지워져서 작품검색이 아예 불가능함)

이경우 버그발생이 일어난건가요? 아니면 정상인가요?

현재 확인된것으론 groups : tiramisu 가있습니다

삭제데이터 중 일부가 아예 검색이 안되는것으로 확인되었습니다

제가  이 그룹 작품을 30여개 가지고있는데 그중 7개만이 기본데이터에서 검색이 되었으며

나머진 아예 검색이 안되는 상황입니다

**Comment by KurtBestor** [comment]
현재 삭제된 데이터에서 그룹은 검색되지 않습니다.

**Comment by siwkd2** [comment]
> 현재 삭제된 데이터에서 그룹은 검색되지 않습니다.

답변감사합니다
