### ISSUE TITLE
건의사항

### ISSUE THREAD

**Issue by vibap** [KurtBestor/Hitomi-Downloader-issues#28]
![image](https://user-images.githubusercontent.com/35663889/35196749-869e2a36-ff19-11e7-9934-e4ff39e36715.png)

폴더명 형식 지정할 시에
types(manga, doujinshi, artistcg etc...) 도 형식에 들어갈수 있도록 해주시면 감사하겠습니다

아 그리고 혹시 zip 압축기능은 추가될 예정이 없나요?

**Comment by KurtBestor** [comment]
고급탭에서 압축 관련 설정을 할 수 있습니다.

**Comment by KurtBestor** [comment]
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

Type도 가능하게 수정한 버전입니다

**Comment by vibap** [comment]
피드백 감사드립니다
잘 작동합니다
