### ISSUE TITLE
2.5버전에 이전버전에서 다운로드하던 방식을 사용할수는 없나요?

### ISSUE THREAD

**Issue by koouoo** [KurtBestor/Hitomi-Downloader-issues#280]
![default](https://user-images.githubusercontent.com/44537450/47611022-36de6580-da9f-11e8-8247-1f5ef8c41260.png)

이전버전에서는 위 그림처럼 파일명 폴더 형식을 # artist / title (id) 로 지정해놓고 다운로드를 받으면 
작가명 폴더가 하나 생긴뒤에 그 작가명 폴더 안에 다운로드한 자료들이 하나씩 다운되는 구조였는데

이번 2.5버전부터는 작가명 폴더가 생기지 않고 바로[ #작가명/제목(id)] 폴더가 따로따로 생성이 되는 방식이 되었더라고요 

이전버전에서 사용했던것처럼 바꿀수 있는건지 아니면 그냥 2.4버전을 써야하는건지 좀 문의드립니다

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/248

Duplicate of #248
