### ISSUE TITLE
안녕하세요 프로그램 관련되서 질문이 있습니다.

### ISSUE THREAD

**Issue by ahn270364** [KurtBestor/Hitomi-Downloader-issues#281]
안녕하세요
제가 요즘 파이썬 GUI 제작 관련 공부하고 있는데 확인해보니깐 파이썬으로 제작하셨다고 되어있고, 또 도움말에 powered by Qt로 되어있어서, 혹시 괜찮으시다면 몇가지 여쭤보고자 합니다. 
(참고로 저는 PyQt5로 제작을 하고 있는데, 어떤 모듈을 쓰시는지 알 수 있을까 합니다.)

1. 이미지 파일이 있는 폴더가 따로 없던데 프로그램에 사용되는 이미지는 어디서 가져오시는지 궁금합니다. 저는 항상 프로그램 옆에 폴더를 둬서 사용하는 이미지 파일들은 그 안에 두고 거기서 가져오는데, 어떻게 하신 것인지 해서 여쭤보려합니다.

2. 그리고 메뉴 부분에서 옵션 > 항상위를 클릭하면 가운데 검정테두리 박스가 뜨면서 사라지는게 있던데 해당 부분도 어떻게 하는지 궁금해서 여쭤보려합니다.

개인적으로 방법을 찾아봤는데 잘 찾아지지가 않아 부득이하게 방명록 남깁니다.
방명록창에 쓰시는게 어려우시다면 ahn2703644@gmail.com  으로 힌트라도 알려주시면 감사하겠습니다. 좋은 하루 되시면 좋겠습니다. 감사합니다.

**Comment by KurtBestor** [comment]
PyQt4 써요.

1. [pyrcc4](http://pyqt.sourceforge.net/Docs/PyQt4/resources.html) 써요.

2. 직접 만들었어요.
