### ISSUE TITLE
이미 받았던 파일을 프로그램 실행 시 마다 다시 받는 경우

### ISSUE THREAD

**Issue by boogi505** [KurtBestor/Hitomi-Downloader-issues#282]
ini를 열어보니 이미 다운로드가 완료되었음에도 "Done":false로 저장되어 있더라구요
해당 문제가 발생한 라인은 대충 전체의 10% 정도고 오래전에 받았던 일부 라인 몇줄도 false로 바뀐것으로 보아 순서 문제는 아닌 것 같습니다

강제로 전부 true로 바꿨더니 다시 받는 경우는 없어졌지만 썸네일을 제대로 읽어오지 못합니다

파일열기를 클릭하면 제대로 열리는 것으로 보아 경로 문제는 아닌 듯 한데 저는 직접 개발한 사람이 아니라서 잘 모르겠네요

이럴때는 어떻게 해야 될까요? 무결성 검사 같은게 있나요?

**Comment by KurtBestor** [comment]
해당 작업 마우스 우클릭 후 `정보... (I)` 눌러서 나오는 내용 보여주세요.

**Comment by boogi505** [comment]
> 
> 
> 해당 작업 마우스 우클릭 후 `정보... (I)` 눌러서 나오는 내용 보여주세요.

zip: 
type: 
valid: True
done: True
range: None
range_p: None
single: False

[File Names]
[URLs]

쓸모 없는 부분 지우고 위처럼 나옵니다
zip, type, fileNames, urls는 비어있었구 done은 본문처럼 false여서 직접 true로 바꿨습니다

**Comment by KurtBestor** [comment]
아뇨아뇨 전체 다 보여주세요.

**Comment by boogi505** [comment]
> 
> 
> 아뇨아뇨 전체 다 보여주세요.

![dddd02](https://user-images.githubusercontent.com/44722307/47960693-1768af00-e042-11e8-9977-8f39eacccd50.png)
![dddd01](https://user-images.githubusercontent.com/44722307/47960694-18014580-e042-11e8-9a93-4dd26e742b5f.png)
