### ISSUE TITLE
안녕하세요 개발자님 혹시 갤러리정보만 받을수있는 방법이 있을까요?

### ISSUE THREAD

**Issue by mmj3676** [KurtBestor/Hitomi-Downloader-issues#283]
고급란에서 파일유형 제거 이미지를 선택하면 info만 생성될줄알았는데 아예 폴더자체가 안만들어지네요..
info.txt만 긁어올 방법이 있을까요?

섬네일만 받는 기능이 혹시 있나요? 섬네일과,info파일만 넣어놓고 관리하고싶어서요,,

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

섬네일만 받는 기능은 없어요.

**Comment by mmj3676** [comment]
잘 작동합니다! 감사합니다
