### ISSUE TITLE
히토미 다운받을때 일부 404가 뜹니다

### ISSUE THREAD

**Issue by jaejunghan** [KurtBestor/Hitomi-Downloader-issues#285]
히토미 번호는  998990
  996402
1288965
1289383
1288963
1000859
인데 1000859는 메뉴에서 검색을 삭제된 파일데이터까지 법위늘려서 상세검색해도 뜨지도 않고 다운로드해도 404가 뜹니다 이처럼 검색이 안되는 항목들이 있습니다

공짜로 쓰는 놈이 염치불구하고 문의드립니다

https://hiyobi.me/reader/1289383#1-도 다운 받아지지 않습니다

또한 https://twitter.com/OrangeMaru_ 해당 링크를 트위터 다운받으려고 하는데 안되네요 마루마루로 인식을 합니다

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

![image](https://user-images.githubusercontent.com/14768120/48478763-8f0bba80-e848-11e8-9275-f6a2bff996a0.png)

**Comment by jaejunghan** [comment]
1000859 은 여전히 검색하고 다운이 받아 지지않습니다 맨처음에 20p를 다운받고 완료했길레 다시 했더니 404 not found 입니다

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by KurtBestor** [comment]
히토미 서버에 있는 것만 검색돼요.
