### ISSUE TITLE
폴더기능 문의 합니다

### ISSUE THREAD

**Issue by alsdn45611** [KurtBestor/Hitomi-Downloader-issues#286]
따로 안에 폴더분류할수있게 만들어 주시면
히토미 다운로더안에  따로
  
   A 작품 (ㄱ형식)
   B 작품 (ㄴ형식)
   C 작품 (ㄱ형식)
   D 작품 (ㄴ형식)
 만약 이렇게 작품들이 있으면 
 사용자가 따로 분류 정리할수있게

 ### ㄱ형식 폴더 
    A 작품
    C 작품
 ### ㄴ형식 폴더 
    B 작품
    D 작품

따로 폴더를 만들어 열수있거나 닫을수있게 하면 사용자가 분류하기 쉬워질것 같아요
끌어당겨 옮기거나 작품 우클릭해서 폴더목록에서 설정가능한
폴더기능 구현해주시면 좋겠습니다

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

`작업` - `새 그룹 만들기 (Ctrl + G)` 눌러서 만들 수 있어요.
