### ISSUE TITLE
일부 트위터가 다운되지 않습니다

### ISSUE THREAD

**Issue by jaejunghan** [KurtBestor/Hitomi-Downloader-issues#288]
![default](https://user-images.githubusercontent.com/41049446/48559369-dcfaee00-e92e-11e8-9fe9-84ea9e42a9ad.PNG)
![2](https://user-images.githubusercontent.com/41049446/48559372-df5d4800-e92e-11e8-95c7-0950d0a8fd68.PNG)

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/285
