### ISSUE TITLE
저장을 하면 다운목록이 지워집니다

### ISSUE THREAD

**Issue by agegaori** [KurtBestor/Hitomi-Downloader-issues#290]
![1](https://user-images.githubusercontent.com/45113488/48655687-948e1e00-ea5d-11e8-8ce2-3643e212d78b.png)

저장을 하면 위 사진처럼 줄어들고 다시 키면 다운안된 500개 분량을 다시 다운하기 시작합니다

**Comment by KurtBestor** [comment]
저장할 때 오류 메시지 없이 저장 됐나요?

다운로드 목록 900개 이상은 권장하지 않아요. 참고해주세요: #170

**Comment by agegaori** [comment]
네 저장할때 오류는 없어요
