### ISSUE TITLE
마루마루 recaptcha 뚫기가 안됩니다

### ISSUE THREAD

**Issue by qwer191** [KurtBestor/Hitomi-Downloader-issues#292]
비밀번호를 입력하는 중간에도 계속 새로고침되면서 튕기고 간신히 빠르게 비밀번호를 입력해도 다음단계인 맞는사진 클릭하는 단계에서도 계속 새로고침되면서 튕겨내서 다운을 할 수가 없습니다ㅠㅠ
나중엔 죄송합니다. 컴퓨터 또는 네트워크에서 자동화된 쿼리를 보낼 수 있습니다. 사용자를 보호하기 위해 요청을 처리 할 수 ​​없습니다 어쩌구 이런 게 뜨면서 넘어가지도 않고요. 자세한 건 아래 링크를 참조하라고 뜨더군요... 뭐가 문제인걸까요ㅠㅠ

https://developers.google.com/recaptcha/docs/faq#my-computer-or-network-may-be-sending-automated-queries

**Comment by qwer191** [comment]
> 비밀번호를 입력하는 중간에도 계속 새로고침되면서 튕기고 간신히 빠르게 비밀번호를 입력해도 다음단계인 맞는사진 클릭하는 단계에서도 계속 새로고침되면서 튕겨내서 다운을 할 수가 없습니다ㅠㅠ
> 나중엔 죄송합니다. 컴퓨터 또는 네트워크에서 자동화된 쿼리를 보낼 수 있습니다. 사용자를 보호하기 위해 요청을 처리 할 수 ​​없습니다 어쩌구 이런 게 뜨면서 넘어가지도 않고요. 자세한 건 아래 링크를 참조하라고 뜨더군요... 뭐가 문제인걸까요ㅠㅠ
> 
> https://developers.google.com/recaptcha/docs/faq#my-computer-or-network-may-be-sending-automated-queries

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/289

**Comment by qwer191** [comment]
> 참고해주세요: #289

이제 되네요!!! 정말 감사드립니다ㅠㅠ 이런 좋은 프로그램 만들어주셔서 너무 감사해요ㅎㅎ 좋은 하루 되세요~ :)
