### ISSUE TITLE
스크립트 제작문의드려도 될까요?

### ISSUE THREAD

**Issue by siwkd2** [KurtBestor/Hitomi-Downloader-issues#294]
마루마루가 오늘자로 폐쇄되어서

http://manazero008h.blogspot.com

여기서 백업본이라도 다운받을려고하는데 혹시 다운로드 스크립트 만들어주실수있는지요

부탁드립니다

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/293

사실 스크립트는 다른 개발자 분들이 필요한 사이트 있으면 만들어서 추가하라고 만든건데요, 쓰는 분들이 없는 것 같네요.

**Comment by ourload** [comment]
브금전선껀은 잘 되네요 근데 브금전선(bgmfl) 하고 http://manastaynight008h.blogspot.com/2018/11/88_18.html#link 이 사이트는 다른 사이트라 적용이 안되네요 브금전선에 없는데 여기엔 있는 만화가 있어서요 추가 가능할까요??
그리고 가능하시면  https://bonotoon.com/?adtbrdg=e#_adtReady  여기도 좀 추가해 주세요 ㅎㅎ

**Comment by siwkd2** [comment]
> 참고해주세요: #293
> 
> 사실 스크립트는 다른 개발자 분들이 필요한 사이트 있으면 만들어서 추가하라고 만든건데요, 쓰는 분들이 없는 것 같네요.

브금전선 서버가 많이 느려서 다운도중 invalid가 뜨면서 다운중지되는게 부지기수입니다

 마나제로에서 다운을 받고싶은데

혹시 마나제로 스크립트는 못만들어주시는지.....

실례가 됐다면 죄송합니다

**Comment by KurtBestor** [comment]
@qwertyage @kimmubong @aegis000 @ourload @TopGuunN @juddem002

테스트 부탁드려요: https://drive.google.com/drive/folders/1FP0YZp7QyGDyOQ1nwILRIVT3kd58NYxo

manazero.hds 파일이에요.

**Comment by aegis000** [comment]
읽는데 시간이 좀 걸리지만 제대로 다운됩니다!
정말로 감사해요ㅠㅠ 바쁘실텐데 이렇게나 빨리 해주시다니 감사합니다

**Comment by KurtBestor** [comment]
수정했어요

**Comment by aegis000** [comment]
감사합니다

**Comment by aegis000** [comment]
죄송하지만 동시에 링크를 2개이상 넣으면 invalid가 뜨네요. 몇몇은 2-3개도 괜찮은데 몇몇은 금방 invalid 뜨네요.
그래도 스크립트 만드느라 고생하셨습니다

**Comment by aegis000** [comment]
지금 확인해보니 두개이상 넣으면 대기에 들어가야 하는데 그냥 invalid로 되네요. 부탁드립니다

**Comment by aegis000** [comment]
Invalid : [manazero] http://manazero008h.blogspot.com / 2015 / 08 /
blog-post_237.html

gal_num: http://manazero008h.blogspot.com/2015/08/blog-post_237.html
dir:
zip:
type: manazero
artist: None
url: http://manazero008h.blogspot.com/2015/08/blog-post_237.html
valid: False
done: False
range: None
range_p: None
single: False


[Gallery]
None


[File Names]



[URLs]



[Messages]
stop
Traceback (most recent call last):
File "utils", line 398, in start
File "utils", line 409, in start_
File "dynamic_module_0", line 59, in read
File "dynamic_module_0", line 54, in name
File "dynamic_module_0", line 49, in soup
File "dynamic_module_0", line 75, in get_soup
File "selenium\webdriver\remote\webdriver", line 323, in get
File "selenium\webdriver\remote\webdriver", line 309, in execute
File "selenium\webdriver\remote\remote_connection", line 460, in execute
File "selenium\webdriver\remote\remote_connection", line 522, in _request
File "urllib2", line 429, in open
File "urllib2", line 447, in _open
File "urllib2", line 407, in _call_chain
File "urllib2", line 1228, in http_open
File "urllib2", line 1201, in do_open
File "httplib", line 719, in getresponse
File "httplib", line 271, in begin
File "httplib", line 234, in _read_status
File "socket", line 373, in readline
timeout: timed out

Fail: manazero


이렇게 뜨네요

**Comment by KurtBestor** [comment]
이거 써보세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by aegis000** [comment]
소스 코드들은 어떻게 사용하는건가요?

**Comment by KurtBestor** [comment]
`hitomi_downloader_GUI_test.zip` 만 다운로드해서 `hitomi_downloader_GUI.exe` 파일만 교체하면 돼요.

**Comment by momokoro1** [comment]
감사합니다!

**Comment by kimmubong** [comment]
테스트 해보겠습니다 만들어 주셔서 감사해요

**Comment by kimmubong** [comment]
저도 다음과 같은 오류가 나는데. 
왜 이런가요?


Invalid : [manazero] http://manazero008h.blogspot.com / 2018 / 09 / blog-post_64.html#link

gal_num: http://manazero008h.blogspot.com/2018/09/blog-post_64.html#link
dir: 
zip: 
type: manazero
artist: None
url: http://manazero008h.blogspot.com/2018/09/blog-post_64.html#link
valid: False
done: False
range: None
range_p: None
single: False


[Gallery]
None


[File Names]



[URLs]



[Messages]
stop
Traceback (most recent call last):
File "utils", line 398, in start
File "utils", line 409, in start_
File "dynamic_module_0", line 59, in read
File "dynamic_module_0", line 54, in name
File "dynamic_module_0", line 49, in soup
File "dynamic_module_0", line 72, in get_soup
File "phantomjs", line 46, in start
File "selenium\webdriver\phantomjs\webdriver", line 60, in __init__
File "selenium\webdriver\phantomjs\webdriver", line 76, in quit
File "selenium\webdriver\common\service", line 182, in stop
File "selenium\webdriver\common\service", line 38, in kill
File "psutil\__init__", line 251, in __init__
File "psutil\__init__", line 280, in _init
NoSuchProcess: psutil.NoSuchProcess no process found with pid 104688

Fail: manazero

done : http://manazero008h.blogspot.com/2018/09/blog-post_64.html#link

**Comment by siwkd2** [comment]
> `hitomi_downloader_GUI_test.zip` 만 다운로드해서 `hitomi_downloader_GUI.exe` 파일만 교체하면 돼요.

바쁘신 와중에 시간내어서 만들어주셔서 감사합니다 덕분에 편리하게 잘쓰고있습니다

**Comment by kimmubong** [comment]
> > `hitomi_downloader_GUI_test.zip` 만 다운로드해서 `hitomi_downloader_GUI.exe` 파일만 교체하면 돼요.
> 
> 바쁘신 와중에 시간내어서 만들어주셔서 감사합니다 덕분에 편리하게 잘쓰고있습니다

오 잘됩니다. ^^  확인 했습니다. 감사합니다.

**Comment by tanuki777** [comment]
2.5a 버전에 TEST 파일 교체해도 다운이 안되는데 어떻게 해야되나요...ㅠㅠㅠㅠㅠㅠ
고생많으십니다..

**Comment by KurtBestor** [comment]
@tanuki777 

다운로드 실패한 작업 마우스 우클릭 후 `정보... (I)` 눌러서 나오는 내용 보내주세요.

**Comment by TopGuunN** [comment]
항상 수고많으십니다

네 저도 tanuki님과 마찬가지의 이유입니다. 

테스트 exe파일 교체해줬고 

저 HDS파일? 도 연결프로그램 히토미다운로더로 해서 실행해줬구요 

http://manazero008h.blogspot.com/2018/05/blog-post_99.html#link 

위의링크로 복붙했는데 

------------------------------------------------------------------------------------------------------------------
Invalid: http://manazero008h.blogspot.com / 2018 / 05 / blog-post_99.html#link

gal_num: http://manazero008h.blogspot.com/2018/05/blog-post_99.html#link
dir: 
zip: 
type: None
artist: None
url: http://manazero008h.blogspot.com/2018/05/blog-post_99.html#link
valid: False
done: False
range: None
range_p: None
single: True
time: 1543078449.86 (Nov 25)


[Gallery]
None


[File Names]



[URLs]



[Messages]
Traceback (most recent call last):
File "hitomi_downloader_GUI", line 1157, in run
File "utils", line 129, in pop
IndexError

Fail: ??

done : http://manazero008h.blogspot.com/2018/05/blog-post_99.html#link
-----------------------------------------------------------------------------------------------------------------

이렇게 나옵니다

**Comment by KurtBestor** [comment]
`[도움말] - [사용법...  (F1)] - 스크립트`  를 참고해주세요

**Comment by TopGuunN** [comment]
네 말씀하신대로 f1눌러서 스크립트 란에 가보니 드래그&드롭으로 스크립트파일을 실행할수있다고

써있어서 manazero.hds를 받아서 히토미다운로더exe파일에 드래그드랍으로 했는데도 

결과는 마찬가지입니다... 


Invalid: http://manazero008h.blogspot.com / 2017 / 04 / blog-post_66.html#link

gal_num: http://manazero008h.blogspot.com/2017/04/blog-post_66.html#link
dir: 
zip: 
type: None
artist: None
url: http://manazero008h.blogspot.com/2017/04/blog-post_66.html#link
valid: False
done: False
range: None
range_p: None
single: True
time: 1543126783.65 (Nov 25)


[Gallery]
None


[File Names]



[URLs]



[Messages]
Traceback (most recent call last):
File "hitomi_downloader_GUI", line 1157, in run
File "utils", line 129, in pop
IndexError

Fail: ??

done : http://manazero008h.blogspot.com/2017/04/blog-post_66.html#link



이렇게 뜨네요

**Comment by KurtBestor** [comment]
@TopGuunN 

![image](https://user-images.githubusercontent.com/14768120/48976298-5382b300-f0c8-11e8-9023-3cf0b46216f2.png)

이런식으로 창 뜨고 `예(Y)` 를 눌러야 추가돼요.

**Comment by FKDLTBSK1020** [comment]
위에 방식 전부해도 안되서 그러는데요ㅠ
Invalid : [manazero] http://manazero008h.blogspot.com / 2018 / 05 / blog-post_99.html

gal_num: http://manazero008h.blogspot.com/2018/05/blog-post_99.html
dir: 
zip: 
type: manazero
artist: None
url: http://manazero008h.blogspot.com/2018/05/blog-post_99.html
valid: False
done: False
range: None
range_p: None
single: False
time: 1543139942.73 (Nov 25)


[Gallery]
None


[File Names]



[URLs]



[Messages]
stop
Traceback (most recent call last):
File "utils", line 403, in start
File "utils", line 414, in start_
File "dynamic_module_0", line 59, in read
File "dynamic_module_0", line 54, in name
File "dynamic_module_0", line 49, in soup
File "dynamic_module_0", line 86, in get_soup
Exception: can not load :(

Fail: manazero

done : http://manazero008h.blogspot.com/2018/05/blog-post_99.html
뭐가문제인지 가르쳐주세요 아무리해도 안되요 ㅠ

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/314

**Comment by FKDLTBSK1020** [comment]
감사합니다

**Comment by lducjswo** [comment]
감사합니다
스크립트까지 적용해서 잘 사용하고 있습니다
한가지 여쭤보고 싶은게 있는데
마나제로에서 해당 만화의 모든 화를 받는게 아니라 한 화씩 선택해서 받는 방법은 현재 올려주신 스크립트에선 안되나요?
