### ISSUE TITLE
잘 쓰고있습니다 감사합니다

### ISSUE THREAD

**Issue by leejunebae** [KurtBestor/Hitomi-Downloader-issues#295]
^^ 감사히 잘 쓰고있습니다.
지금까지 써본 다운로더 중에 가히 최강인것 같습니다.

다른 좋은 기능에 비해서 이건 뭐 소소한 거긴 한데요.
유툽 다운로드 해보면 저화질로 다운로드가 되더라구요.
혹시 고화질을 기준으로 다운로드 될 수는 없을까요? 나~~~중에 시간나실때 한번 

암튼 잘 쓰고있고 앞으로도 잘 쓰도록 하겠습니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

다음과 같이 설정할 수 있어요:
![image](https://user-images.githubusercontent.com/14768120/48749913-4c226a80-ecc0-11e8-9b3e-fc4673696b8f.png)

**Comment by leejunebae** [comment]
네 재생되는것 확인했습니다. 음성도 들리네요. 
[중요하지 않음] 다음 팟 플레이어 ( 옛날버전 )는 4K를 지원을 안해서 Window Media Player 에서 확인했습니다. 
감사합니다.
