### ISSUE TITLE
마나제로랑 보노툰도 스크립트 제작 부탁드려요

### ISSUE THREAD

**Issue by ourload** [KurtBestor/Hitomi-Downloader-issues#297]
브금전선껀은 잘 되네요 근데 브금전선(bgmfl) 하고 http://manastaynight008h.blogspot.com/2018/11/88_18.html#link (마나제로)이 사이트는 다른 사이트라 
적용이 안되네요 브금전선에 없는데 여기엔 있는 만화가 있어서요 추가 가능할까요??
그리고 가능하시면 https://bonotoon.com/?adtbrdg=e#_adtReady 여기도 좀 추가해 주세요 ㅎㅎ

**Comment by momokoro1** [comment]
제작자님. 이번 브금 전선 스크립트 빠른 추가 감사합니다.
다름이 아니라, 윗분이 언급하신 마나스테이나이트 사이트의 스크립트 추가를 건의하고 싶어서 입니다.
프로그래밍을 배운 건 아니지만 스크립트를 보고 나름대로 수정을 해 보았지만, 작동하지 않아서 눈물이 나오려 합니다...
이미지가 업로드 된 주소가 
1bp.blogspot.com 2bp.blogspot.com 3bp.blogspot.com 4bp.blogspot.com
이고 각 업로드 주소마다 일관성이 없어 난처했습니다. ㅠ.
