### ISSUE TITLE
다운로더로 JMANA는 받을수 없나요? 

### ISSUE THREAD

**Issue by Impress2** [KurtBestor/Hitomi-Downloader-issues#298]
https://www.jmana2.com/

스크립트를 조금씩 바꿔보면서 해봤는데 아예 읽지를 못하는데
히토미 다운로더는 JMANA는 받질 못하는 건가요?

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/315
