### ISSUE TITLE
버그랑 건의사항

### ISSUE THREAD

**Issue by vpvp100** [KurtBestor/Hitomi-Downloader-issues#3]
제 컴퓨터가 구려서 그런지 모르겠는데

이전에는 한번에 대량으로 클립보드로 바로 추가시킬때 문제가 없었는데

이앞에 버전이랑 지금 버전에서 한번에 여러개를 추가하면

일정시간동안 추가가 안되는 버그가 있는거 같습니다.

물론 수동으로 추가하기 버튼을 눌려서 추가하면 문제없이 추가는 됩니다.

그리고 건의사항이 하나 있는데

다운로드한것에 폴더 삭제를 하면 압축파일은 삭제가 안되도록은 불가능한가요?

폴더만 삭제하고 압축파일은 남기고 싶습니다.

옵션에서 압축후 원본 폴더 삭제를 체크하면 되긴한데. 그럼 따로 따로 찾아보기가 불편해져서...

**Comment by KurtBestor** [comment]
설명해주신 것만으로는  어떤 상황인지 잘 모르겠습니다. 한번에 대량으로 추가한다는 것이, A, B, C, D 개별의 URL을 빠르게 차례대로 복사해서 추가했을 때 D가 씹히는 경우가 생긴다는 건가요?
폴더 삭제시에 압축파일 삭제 안되게 하는 건 좋은 아이디어 있나요? 옵션에 '폴더 삭제시 압축파일 그대로 두기' 이렇게 추가하기는 지저분해질 것 같아서요.

**Comment by vpvp100** [comment]
버그 같은경우에는 이해하신것처럼 개별 url을 한번에 복사해서 추가할때 많으면 많을수록 씹히는 빈도가 늘어나는게 맞구요.

압축파일 삭제는 뮤토렌트 처럼 이렇게 삭제버튼이나 우클릭시에 표시하는 방법은 어떠신가요?
![dsaasd](https://user-images.githubusercontent.com/34399531/33804249-4b2b55ba-dde4-11e7-9649-9160c951acb5.PNG)
사실 저도 어떻게 하면 좋을까 라는 생각은 안하고 얘기했던거라ㅠㅋ

**Comment by KurtBestor** [comment]
@vpvp100 

[hitomi_downloader_GUI_test.zip](https://github.com/KurtBestor/Hitomi-Downloader-issues/files/1546535/hitomi_downloader_GUI_test.zip)

패치판입니다. 수정된 부분은 다음과 같습니다:
1. 추가할 때 부하 줄임
2. 압축파일과 폴더가 동시에 존재하면 어떤 걸 삭제할지 고르게 함

버그는 잘 해결됐는지 모르겠어요. 제 환경에선 재현이 안되네요..

삭제 부분은 옵션 - "경고 없이 삭제" 부분을 체크 해제하면 삭제할 때 고를 수 있게 했습니다:
![img](https://user-images.githubusercontent.com/14768120/33815683-971d0ea4-de76-11e7-9544-d4acd3d04ccb.png)
말씀하신대로 하는 것보다 이게 더 편할 것 같아서 이렇게 하게 되었습니다.

테스트 부탁드려요.

**Comment by vpvp100** [comment]
사용해봤습니다 건의사항 들어주셔서 감사합니다.

버그 같은 경우에는 이게 발생 할때가 있을때도 있고 없을때도 있어서 잘 모르겠네요.

일단 확실한건 바뀐 상태에서 좀 여러개를 한번에 추가해봤는데 아직까지 발생하지는 않네요.

**Comment by KurtBestor** [comment]
아직까지 버그가 다시 발생했다는 보고가 없어서 해결되었다고 판단, 닫습니다

**Comment by sili078** [comment]
궁금한점 AI 에게 질문하기
https://newtoki.iwinv.net/ https://ruliweb.iwinv.net/ https://instiz.iwinv.net/ https://gmarket.iwinv.net/ https://aliexpress.iwinv.net/ https://theqoo.iwinv.net/ https://linkkf.iwinv.net/ https://facebook.iwinv.net/ https://paypay.iwinv.net/ https://etoland.iwinv.net/ https://auction.iwinv.net/ https://trends.iwinv.net/ https://asdasd.iwinv.net/ https://kangkas.iwinv.net/ https://lavikit.iwinv.net/ https://maplegg.iwinv.net/ https://kemono.iwinv.net/ https://redgifs.iwinv.net/ https://wikikr.iwinv.net/ https://yourgg.iwinv.net/ https://koreakr.iwinv.net/ https://capcut.iwinv.net/ https://snp500.iwinv.net/ https://shopee.iwinv.net/ https://namuwiki.iwinv.net/ https://novelpia.iwinv.net/ https://popcat.iwinv.net/ https://fiveguys.iwinv.net/ https://compose.iwinv.net/ https://jjang0u.iwinv.net/ https://anilife.iwinv.net/ https://mmtcld.iwinv.net/ https://tdgall.iwinv.net/ https://yakored.iwinv.net/ https://postype.iwinv.net/ https://manatoki.iwinv.net/ https://dctribe.iwinv.net/ https://blacktoon.iwinv.net/ https://munpia.iwinv.net/ https://snpetf.iwinv.net/ https://hygall.iwinv.net/ https://mingky.iwinv.net/ https://fanbox.iwinv.net/ https://skyscanner.iwinv.net/ https://flightaware.iwinv.net/ https://interpals.iwinv.net/ https://fconline.iwinv.net/ https://flextv.iwinv.net/ https://dcinside.iwinv.net/ https://mlbpark.iwinv.net/ https://eomisae.iwinv.net/ https://ecount.iwinv.net/ https://hiworks.iwinv.net/ https://laftel.iwinv.net/ https://toomics.iwinv.net/ https://mercari.iwinv.net/ https://iptime.iwinv.net/ https://mixamo.iwinv.net/ https://yandex.iwinv.net/ https://gsshop.iwinv.net/ https://toptoon.iwinv.net/ https://slrclub.iwinv.net/ https://dmitory.iwinv.net/ https://kmcert.iwinv.net/ https://lolchess.iwinv.net/ https://curseforge.iwinv.net/ https://hsreplay.iwinv.net/ https://mapleinven.iwinv.net/ https://c19670.iwinv.net/ https://a12893.iwinv.net/ https://b82893.iwinv.net/
