### ISSUE TITLE
건의사항

### ISSUE THREAD

**Issue by ghost** [KurtBestor/Hitomi-Downloader-issues#30]
2.0 버전은 https://hiyobi.me/ 이 싸이트가 다운로드 가능하였지만
2.1 버전 넘어오면서 다운로드가 안됩니다.

**Comment by KurtBestor** [comment]
hiyobi.me에서 번호만 읽어서 hitomi.la에서 다운로드 하는 방식입니다.
지금 해보니 되는 것 같은데 어떻게 다운로드가 안되는지 좀 더 자세히 알려주실 수 있나요?

**Comment by KurtBestor** [comment]
대답이 없어서 일단 닫습니다
