### ISSUE TITLE
마루마루가 터지면서 디시 만갤쪽에 번역본들이 올라오고 있는데 이 사이트도 부탁드립니다

### ISSUE THREAD

**Issue by dullahan00** [KurtBestor/Hitomi-Downloader-issues#300]
http://gall.dcinside.com/board/view/?id=comic_new1&no=6998214

이런 게시글처럼 이 사이트에 번역본이 올라오고 있는 상태인데 이게 이미지 불러오는 방식이 달라서인지 다른 프로그램으로 긁히지가 않는 것 같더라고요. 

개인적으로 해보려고 했지만 제 능력으로는 어려운 크롤링이 난해해서 이렇게 부탁드립니다 ㅜ

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://drive.google.com/drive/folders/1FP0YZp7QyGDyOQ1nwILRIVT3kd58NYxo

dc.hds 파일이에요.
