### ISSUE TITLE
안녕하세요 마루마루 미러 사이트 하나만 스크립트 작성 부탁드려요

### ISSUE THREAD

**Issue by kimmubong** [KurtBestor/Hitomi-Downloader-issues#301]
http://manazero008h.blogspot.com/search/label/9%EA%B7%B8%EB%A6%BC%E3%84%B1
여기인데요./. 
자료를 받고 싶은데 브금전선이 죽었네요./. 대체 사이트로 스크립트 작성 부탁드립니다.
제 능력이 되질 않아서 부탁 드립니다.

**Comment by KurtBestor** [comment]
Duplicate of #294
