### ISSUE TITLE
개인적인 요구사항인데요...

### ISSUE THREAD

**Issue by locien10** [KurtBestor/Hitomi-Downloader-issues#303]
솔직히 프로그램을 너무 잘 만드셔서 그러는데 소스코드를 얻을 수는 없을까요?
개인적으로 변경해서 쓰고싶은 욕구도 있는데
전에 알려주신 압축해제로는 코드를 읽을 방도가 없어서요....
개인적인 공부용도로도 좋고 수정해서 크롤러로 활용하고 싶습니다....

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/170#issuecomment-406796246
