### ISSUE TITLE
부탁드립니다

### ISSUE THREAD

**Issue by aegis000** [KurtBestor/Hitomi-Downloader-issues#304]
지금 마루마루 터지고 나서 http://manazero008h.blogspot.com/2015/08/150_9.html 다운로드 스크립트를 부탁드립니다. 상당히 많은 사람들이 다운로더를 필요하고 있어서 부탁드립니다.

**Comment by KurtBestor** [comment]
Duplicate of #294

**Comment by ourload** [comment]
> Duplicate of #294

그 bgmfl.hds 를 쓰면  http://manazero008h.blogspot.com/2015/08/150_9.html 이 사이트에서 다운이 된다는 말씀인가요???  계속 답변으로 293번 글을 복사하시네요?? bgmfl.hbs로 되던 브금전선이란 사이트는 이미 터졌거든요 답변 부탁드려요

**Comment by KurtBestor** [comment]
@ourload

아뇨. 다운 안돼요.
똑같은 사이트 요청 글을 계속 올리니 같은 글은 중복으로 묶어놓는 거예요. 관리하기 쉽게요.
저도 할 일이 있어서 시간 나면 만들어볼게요.

**Comment by TopGuunN** [comment]
확실히 마루마루터지니까 전전긍긍하시는분들이 많이보이는군요
저 또한 마찬가지지만, 이렇게까지 마루마루에 의존도가 높을지는 꿈에도몰랐네요

**Comment by juddem002** [comment]
@KurtBestor 바쁘시겠지만 제이마나 사이트도 부탁드립니다. 위엣분 말대로 하루하루 시한폭탄마냥 여기저기가 뻥뻥 터져나가서 전전긍긍하네요...
