### ISSUE TITLE
마루 미러사이트 스크립트 부탁드립니다

### ISSUE THREAD

**Issue by zizizi1132** [KurtBestor/Hitomi-Downloader-issues#307]
다운로더 항상 애용하고있습니다

이번에 마루마루가 터지고 미러사이트 다운로더를 찾고있는데

혹시 이 사이트도 hds 스크립트 추가해주실수 있나 해서 문의드립니다

http://mangashow.me/

**Comment by locien10** [comment]
#coding: utf8
#title: mangashow.me 사이트 추가
#author: locien10

import downloader
import re
from utils import urljoin, Downloader, Soup, LazyUrl, try_n
import json
from fucking_encoding import clean_title
from time import sleep
import os
import phantomjs
import requests
from translator import tr_


class Image(object):
    def __init__(self, url, page, p):
        ext = os.path.splitext(url)[1]
        name = u'{:04}{}'.format(p, ext)
        self.filename = u'{}/{}'.format(clean_title(page.title), name)
        self.url = url


class Page(object):
    def __init__(self, title, url):
        self.title = title
        self.url = 'http://mangashow.me/viewer.php?chapter_id={}'.format(url)


class Downloader_mangashow(Downloader):
    type = 'mangashow'
    URLS = ['mangashow.me']
    icon = 'https://kurtbestor.github.io/res/mana.png'
    _soup = None
    def init(self):
        self.url = self.url.replace('mangashow_', '')
        self.url = 'http://mangashow.me{}'.format(self.id)

    @property
    def id(self):
        return self.url

    @property
    def soup(self):
        if self._soup is None:
            self._soup = get_soup(self.url)
        return self._soup

    @property
    def name(self):
        soup = self.soup
        title = soup.find(class_="manga-subject red").text.strip()
        return clean_title(title)

    def read(self):
        self.title = u'읽는 중... {}'.format(self.name)

        imgs = get_imgs(self.url, self.name, self.soup, customWidget=self.customWidget)

        for img in imgs:
            self.urls.append(img.url)

        sleep(.5)
        self.title = self.name
Downloader.register(Downloader_mangashow)


def get_soup(url):
    driver = phantomjs.start()
    driver.get('http://mangashow.me/')
    if driver.find_element_by_name('id') is not None:
        driver.find_element_by_name('id').send_keys('id')
        driver.find_element_by_name('password').send_keys('password')
        driver.find_element_by_tag_name('form').find_element_by_tag_name('button').click()

    try:
        driver.get(url)

        for i in range(30):
            html = driver.page_source
            soup = Soup(html)
            list = soup.find('div', class_='chapter-list')
            if list is not None:
                break
            print 'wait...'
            sleep(1)
        else:
            raise Exception('can not load :(')
    finally:
        driver.close()

    return soup


def get_imgs(url, title, soup=None, customWidget=None):
    if soup is None:
        soup = get_soup(url)

    lists = soup.findAll('div', class_='chapter-list')
    items = []
    for list in lists:
        items += list.findAll('div', class_='slot')

    pages = []
    for item in reversed(items):
        text = item.find('div', class_='title').text.strip()
        href = item.attrs['data-chapter']
        page = Page(text, href)
        pages.append(page)

    imgs = []
    for i, page in enumerate(pages):
        try:
            imgs += get_imgs_page(page, customWidget)
        except Exception as e:
            if customWidget is not None:
                customWidget.print_(u'Skip: {}'.format(page.url))

        if customWidget is not None:
            if not customWidget.alive:
                return
            customWidget.setTitle(u'{} {} / {}  ({} / {})'.format(tr_(u'읽는 중...'), title, page.title, i+1, len(pages)))

    return imgs


@try_n(4)
def get_imgs_page(page, customWidget=None):
    soup = get_soup(page.url)
    soupimg = soup.findAll('img')
    n = len(soupimg)
    imgs = []
    for i in range(n):
        img=soupimg[i].attrs['src']
        img = Image(img, page, i)
        imgs.append(img)
    return imgs


messageBox(u'{}: mangashow'.format(tr_(u'사이트를 추가했습니다')))







파일을 만들어서 돌려봤는데 


stop
Traceback (most recent call last):
File "utils", line 403, in start
File "utils", line 414, in start_
File "dynamic_module_1", line 58, in read
File "dynamic_module_1", line 53, in name
File "dynamic_module_1", line 48, in soup
File "dynamic_module_1", line 90, in get_soup
Exception: can not load :(

Fail: mangashow
에러가 나네요 어떤 문제인지는 잘 모르겠....습니다. ㅜㅜㅜ
로그인을 구현해야하는 부분때매 저게 맞는지부터도 잘 모르겠네요.. ㅜㅜ

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://drive.google.com/drive/folders/1FP0YZp7QyGDyOQ1nwILRIVT3kd58NYxo

**Comment by locien10** [comment]
1개의 만화를 다운받을때는 조금 느리더라도 큰 문제가 없으나 2개 이상이 되면 접속 과다로 읽어오지 못하는 현상이 있습니다.
접속이 몰린다는 텍스트만 뜨는 페이지로 넘어가는데 다운로드 숫자를 제어를 할 수가 없어 여러개를 넣으면 진행이 거의 안되는 수준이거나 에러가 발생하네요

**Comment by KurtBestor** [comment]
느린건 어쩔 수 없는 것 같네요..

테스트 부탁드려요: https://drive.google.com/drive/folders/1FP0YZp7QyGDyOQ1nwILRIVT3kd58NYxo
