### ISSUE TITLE
그룹명 복사

### ISSUE THREAD

**Issue by Revena** [KurtBestor/Hitomi-Downloader-issues#309]
항상 감사히 잘 쓰고 있습니다.
건의 드리고 싶은건 
검색창에서 우클릭 메뉴에 "작가명 복사" 처럼 "그룹명 복사" 기능도 넣주시면 좋겠습니다.
부탁 드리겠습니다. ( _ _)

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by Revena** [comment]
잘 되는것 같습니다. 감사합니다.
