### ISSUE TITLE
이게 버그인지 히토미측에서 막은 건지 모르겠으나..

### ISSUE THREAD

**Issue by cocoman1111** [KurtBestor/Hitomi-Downloader-issues#31]
새로 릴리즈 된 걸 받아도

다운로드시 실패도 뜨지 않고 목록상에 굉장히 느리게 받아지면서

0% 상태임에도 받아지지도 않았는데 파일은 깨져 있는 상태로 다운로드 되어 있음.

같은 주소임에도 불구하고 제대로 다운 될때도 있고 안될때도 있어서 뭐라 말을 못하겠음..

느리게 받아지는 파일경우 구버전 사용시 대부분 파일이 깨져서 다운로드 완료됨.. ㅠㅠ

나도 제대로 확인해서 알려주고 싶은데.. 진짜로 케바케니까 돌아버리겠음... 

근데 브라우저로 다운시는 그 문제적 파일이 잘 다운되는 게 더 문제,... ㅠㅠ

**Comment by KurtBestor** [comment]
해당 파일 지우고 다시 시도해보셨나요?

**Comment by KurtBestor** [comment]
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

일단 이걸로 테스트 부탁드려요

**Comment by cocoman1111** [comment]
테스트 자체가 안되네요.. 어베스트에서 바이러스 취급하는 거 같은.. 그전 다운로더 들은 이런 거 체크 안당했는데..
fatal error! 뜨면서 영어로 다운로더 스크립트를 실행할 수 없다고 나옵니다..

**Comment by KurtBestor** [comment]
흐.. 개인적으로 프로그램을 개발하면 이런 오진 문제 때문에 속상하네요. 현재 보고된 백신 오진으로는 V3, 비트디펜더, 앱체크, 어베스트가 있습니다. 제가 이걸 다 오진으로 보고하기는 힘들어서 해당 백신 사용자 분들이 보고해주시면 감사하겠습니다. 참고로 전 카스퍼스키 씁니다.

**Comment by cocoman1111** [comment]
v3나 같은 백신은 옛날부터 이런문제가 있었지만.. 어베스트의 경우 나름 괜찮다고 믿고 넘어왔는데 요즘 들어 오진, 설명없이 윈도우 설정변경 등 여러 가지로 실망스럽네요. KurtBestor님이 잘못한게 아니니까 너무 속상해 하시지 마세요ㅠㅠ

**Comment by KurtBestor** [comment]
#38 이거 테스트 좀 부탁드려요

**Comment by KurtBestor** [comment]
v2.1b에서 해결됨
