### ISSUE TITLE
새버전 오류

### ISSUE THREAD

**Issue by hdiw23** [KurtBestor/Hitomi-Downloader-issues#310]
![default](https://user-images.githubusercontent.com/45303021/48964028-04af1d80-efe3-11e8-80f8-50e09558972e.png)

구버전까지 같이 맛이 가버렸네요

**Comment by KurtBestor** [comment]
`hitomi_data` 폴더에 다음 두 파일이 있을거에요:
* `completed_v2.3c`
* `completed_forbidden_v2.3c`

메모장으로 열어서 내용 알려주세요.

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/311
