### ISSUE TITLE
갑자기 작동이 안되는 스크립트가 있어 문의 드려봅니다

### ISSUE THREAD

**Issue by siwkd2** [KurtBestor/Hitomi-Downloader-issues#314]
마나제로 스크립트입니다

어제까진 잘됐는데 오늘부터 갑자기 안되더라구요 

혹시나 해서 이미 다운받았던것도 다시 작동시켜보니 안되더군요

증상은 일단 링크추가해서 작동하면  마나제로 아이콘이랑 읽는중까지는 뜨는데

읽는중 1분정도뜨다가 invalid 뜨면서 중지됩니다(밑에 정보 복붙해놓았습니다)

아마 싸이트쪽에서 어떤 요소를 변경했을거라 생각합니다

아마 제 생각이 맞다면 다른 이용자들도 불편을 겪고 있을것이라 생각합니다

바쁜 와중에 실례되는 말이지만 마나제로 스크립트를 고쳐주실수 있으신가하고 문의 드려봅니다

읽어주셔서 감사합니다

Invalid : [manazero] http://manazero008h.blogspot.com / 2018 / 05 / blog-post_99.html#link

gal_num: http://manazero008h.blogspot.com/2018/05/blog-post_99.html#link
dir: 
zip: 
type: manazero
artist: None
url: http://manazero008h.blogspot.com/2018/05/blog-post_99.html#link
valid: False
done: False
range: None
range_p: None
single: False
time: 1543135870.38 (Nov 25)

[Gallery]
None

[File Names]

[URLs]

[Messages]
stop
Traceback (most recent call last):
File "utils", line 403, in start
File "utils", line 414, in start_
File "dynamic_module_0", line 59, in read
File "dynamic_module_0", line 54, in name
File "dynamic_module_0", line 49, in soup
File "dynamic_module_0", line 86, in get_soup
Exception: can not load :(

Fail: manazero

done : http://manazero008h.blogspot.com/2018/05/blog-post_99.html#link

**Comment by siwkd2** [comment]
그리고 제작자분께서 새로 올려주신 프로그램과 마나제로 스크립트를 한번더 다운받아서 적용후 작동해보았지만 똑같은 증상이 발생하였습니다 

스크립트 적용또한 문제없이 잘되었으니 작동이 안되는것은 

아마 싸이트에서 무언가 바꿨을것이라 생각됩니다

**Comment by siwkd2** [comment]
https://www.blogger.com/blogin.g?blogspotURL=http://manastaynight008h.blogspot.com/2018/11/1_25.html#link

(모든만화에 적용된 사안입니다)

만화를 들어가기전에 콘텐츠 경고가 뜨는데

아마 이것때문에 다운이 안되는거같습니다

콘텐츠경고때문에 이런오류가 발생하는거같으니 스크립트 수정하실때 참고해두셨으면 합니다

**Comment by siwkd2** [comment]
확인해보니 모든 만화에서 동일하게 콘텐츠 경고가 뜨는것이 확인되었습니다

**Comment by siwkd2** [comment]
> 스크립트 수정했어요: https://drive.google.com/drive/folders/1FP0YZp7QyGDyOQ1nwILRIVT3kd58NYxo

수정 감사합니다 덕분에 한시름놓았습니다

**Comment by TopGuunN** [comment]
정말감사합니다. 전에 계속 덧글 쓰던 게시물은 너무 길어져서 어차피 여기를 보고 해결했기때문에

여기다가 올립니다.

아까 커베님이 스크립트 추가하는법도 알려주신대로 했는데도 또 글을 쓰려던찰나에 

이글보고 해결이 되었네요.

항상 커베님 감사할따름입니다. 

조심스럽게 건의하는데요 후원계좌같은거 올려놓으시면 후원같은거 하고싶은사람만 자율적으로 할수있게끔 해놓으면 더 좋을것같기도합니다.
