### ISSUE TITLE
다운 받다가 멈추는건 왜 이런거죠~?

### ISSUE THREAD

**Issue by Kannaris** [KurtBestor/Hitomi-Downloader-issues#316]
지금까지 받은것들 중에 두 작품만 이런데 
보통 다운이 완료되면 다운로더에 초록색으로 작품 이름이 표시되는데
멈추는 두 작품은 작품 이름이 주황색으로 뜨고 1881/1889 요런 식으로 더이상 다운이 안 됩니다

**Comment by KurtBestor** [comment]
다운로드를 시도했지만 파일들 중 일부분을 받지 못하고 완료했을 경우 주황색으로 표시돼요. 대개 서버에 해당 파일이 없을 경우 생기는 오류예요.
문제 없다고 생각되면 해당 작업 마우스 우클릭하고 `[완료됨으로 표시 (D)]` 하시면 돼요.

**Comment by Kannaris** [comment]
컴 3대 돌려봤는데 전부 같은 부분에서 멈추는거 보니 서버 문제가 맞는 거 같네요 :D
