### ISSUE TITLE
질문 있습니다

### ISSUE THREAD

**Issue by momokoro1** [KurtBestor/Hitomi-Downloader-issues#317]
다운로더 잘 사용하고 있습니다.
한 가지 질문을 드리고 싶어서 이슈란에 글을 적게 되었는데요.

스크립트 사용 후 다운로드를 실행하면 "phantomjs.exe" 라는 프로그램이 하나 생성이 되네요.
혹시 무엇인지 아시면 답변 해주시면 감사하겠습니다!

**Comment by momokoro1** [comment]
# # # # # # #

**Comment by locien10** [comment]
javascript 결과 값을 받아보기 위해 실행되는 headless 브라우저에요

**Comment by KurtBestor** [comment]
참고해주세요: https://ko.wikipedia.org/wiki/PhantomJS

**Comment by momokoro1** [comment]
하나 배워갑니다
