### ISSUE TITLE
네이버 블로그에서 원본 이미지를 받을 수 있는 방법이 있나요?

### ISSUE THREAD

**Issue by MoongSong** [KurtBestor/Hitomi-Downloader-issues#318]
네이버 블로그는 해상도나 용량이 리사이징된 이미지만 받아지던데
혹시 원본 이미지를 받게 해주실 수 있나 해서요 ㅜ

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview
