### ISSUE TITLE
다운로더로 특정 dc 갤러리에 있는 짤을 다운받게 하실 계획이 있나요?

### ISSUE THREAD

**Issue by healust** [KurtBestor/Hitomi-Downloader-issues#319]
짤 다운로더라고 잘 쓰던게 있었는데, 개편되고 나서 먹통이 되어버렸습니다.
혹시 dc 사이트에서도 짤을 받을 수 있게 지원을 하실 계획이 있나요?

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/300
