### ISSUE TITLE
파일 다운로드시 내용을 잘 받지 못합니다

### ISSUE THREAD

**Issue by aria1th** [KurtBestor/Hitomi-Downloader-issues#32]
2.0에서부터 일어난 문제입니다.
![image](https://user-images.githubusercontent.com/35677394/35205236-fd09f9cc-ff76-11e7-85d5-7626a55ce871.png)

다만, 서버를 변경하면서 다운로드시 다운로드가 되는 경우가 있습니다.
아마 hitomi 측에서 수작을 걸면서 (몇몇 다운로드 링크를 ba에서 aa로 바꿈) 일어난 문제로 보입니다.
그러나 ba가 아니라 여러 종류가 보이는 걸로 봐서는, *a로 랜덤하게 보내는 거로 보입니다.
파일 크기 체크 검사를 한번 추가해 주시면 감사하겠습니다.

예시로 https://aa.hitomi.la/galleries/1173294/1.jpg 은 되지만 https://ba.hitomi.la/galleries/1173294/1.jpg 는 안됩니다. 

그리고 이하는 2.1a에서 일어난 문제입니다. 

또한 검색시 thumbnail 표시 설정을 했으나 표시가 되지 않고 있어요.

**Comment by aria1th** [comment]
1번 문제는 pre-release에서 파일 크기체크를 하면서 해결된것 같아요
2번에 썸네일이 표시되지 않는건 아직 미해결입니다

**Comment by KurtBestor** [comment]
검색 데이터를 403 Forbidden으로 하고 검색하면 어떤가요?

**Comment by aria1th** [comment]
두 경우 모두 썸네일이 나타나지 않아요
![image](https://user-images.githubusercontent.com/35677394/35206622-280446fa-ff81-11e7-90a1-3bb06a507da1.png)

**Comment by KurtBestor** [comment]
v2.1b에서 해결됨
