### ISSUE TITLE
네이버 블로그 다운이 안되네요

### ISSUE THREAD

**Issue by jaejunghan** [KurtBestor/Hitomi-Downloader-issues#321]
서로이웃만 볼수있는 글이 다운이 안됩니다

제가 로그인해서 서이상태인데 안되네요...

그전에 404검색 요청한사람인데 404검색 업데이트 가능한가요?

**Comment by KurtBestor** [comment]
이웃 공개나 서로이웃 공개 등 비로그인 상태에서 볼 수 없는 글은 지원하지 않아요.
