### ISSUE TITLE
검색기에서 hiyobi 나 익헨도 긁어오는게 가능한가요? (지금은 히토미만 되는거 같습니다)

### ISSUE THREAD

**Issue by jtrpc** [KurtBestor/Hitomi-Downloader-issues#323]
먼저 좋은 프로그램 만든것에 대해 감사합니다.

현재 옵션에서는 '서버' 설정을 수동으로 익헨이나 히요비를 선택가능한데
검색기는 무조건 히토미 에서만 긁는것 같습니다.
혹시 히요비쪽을 긁는게 가능할까요?

링크 쪽에 10000005 로 타이핑하면 제대로 히요비의 https://hiyobi.me/reader/10000005 를 받아오지만
검색기에서는 해당 데이터가 검색되지 않습니다.(숫자범위도 벗어난 점도 있고요)

이쪽도 긁는게 가능하면 정말 좋을것 같습니다.
(히토미에서 없는 데이터가 히요비에 대량으로 있는 케이스가 많더군요/ 실제 위 링크가 그렇습니다)

**Comment by KurtBestor** [comment]
현재는 히토미만 검색돼요.
