### ISSUE TITLE
2.5a 버전 프로그램 실행이 안돼네요

### ISSUE THREAD

**Issue by envysky85** [KurtBestor/Hitomi-Downloader-issues#324]
Traceback (most recent call last):
  File "hitomi_downloader_GUI.py", line 5187, in <module>
  File "hitomi_downloader_GUI.py", line 2157, in set_slider
  File "MySlider.pyo", line 152, in setMaximum
TypeError: QAbstractSlider.setMaximum(int): argument 2 has unexpected type 'unicode'

로그에는 요렇게 뜨네요
v2.3c 에는 각각
{"count":460452,"max":"965561","min":1,"time":1543028202.9140000343}
{"count":10859,"max":1318059,"min":873,"time":1543028398.6579999924}
요렇게 나와요

**Comment by KurtBestor** [comment]
[테스트 버전](https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview)도 실행 안되나요?

참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/311

**Comment by envysky85** [comment]
테스트 버전 다운받아해보니 잘되네요
고맙습니다
