### ISSUE TITLE
안녕하세요 여쭤보고자 하는게 있는데요

### ISSUE THREAD

**Issue by lducjswo** [KurtBestor/Hitomi-Downloader-issues#327]
우선 프로그램 제작해 주신것에 대해 감사드립니다
현재 마나제로 스크립트까지 적용해서 잘 사용하고 있습니다
한가지 궁금한게 있는데요
마나제로에서 해당 만화의 모든 화를 받는게 아니라 한 화씩 개별적으로 선택해서 받는 방법은 현재 올려주신 스크립트에선 안되나요?

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/312

**Comment by lducjswo** [comment]
감사합니다
