### ISSUE TITLE
목록에서 삭제한 만화를 다시 불러올순 없나요?

### ISSUE THREAD

**Issue by siwkd2** [KurtBestor/Hitomi-Downloader-issues#329]
미리 저장했다가 로드하는거 말고

혹시 목록에서 삭제했던 만화 다시 목록에 추가할수있는 기능추가해주실수 있나요?

웹브라우저로 보는기능을 애용중인데 

목록에서 삭제한 만화는 다시 불러오기가 안되서 웹브라우저로 볼수 없더라구요

**Comment by KurtBestor** [comment]
Duplicate of #313
