### ISSUE TITLE
1.9d 버전은 실행이 되는데...

### ISSUE THREAD

**Issue by kokonutboy** [KurtBestor/Hitomi-Downloader-issues#33]
이번 2.1a 버전이나 중간중간 다른 버전들은 작업 관리자에서 실행되고 있다는 표시만 있고 실제 창은 뜨지는 않네요 윈도우 10 쓰고 있는데 뭐가 문제인지.. 1.9d 버전은 아무 문제 없이 사용하고 있습니다.

**Comment by KurtBestor** [comment]
v2.1b에서도 그런가요?

**Comment by KurtBestor** [comment]
답이 없으셔서 일단 닫습니다
