### ISSUE TITLE
안녕하세요 프로그램 편하게 잘쓰고있습니다 항상감사합니다

### ISSUE THREAD

**Issue by ak156** [KurtBestor/Hitomi-Downloader-issues#330]
이사이트에서도 이런 편리한 기능 사용하고싶은데
혹시 https://newtoki.com/ 이 사이트에서도 사용가능할수있게 해주실수있으시나요??

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://drive.google.com/drive/folders/1FP0YZp7QyGDyOQ1nwILRIVT3kd58NYxo
`newtoki.hds` 파일이에요.

스크립트 사용법은 `사용법... (F1)`을 보시면 돼요.

**Comment by ak156** [comment]
잘되네요 감사합니다 ㅎㅎ

**Comment by ak156** [comment]
선생님 어제까진 잘되다가 오늘부텉 갑자기 안되네요 왜그런걸까요? ㅠㅠ 그리고 혹시 개별다운로드도 가능하게 가능하실까요?

**Comment by KurtBestor** [comment]
스크립트 수정했어요: https://drive.google.com/drive/folders/1FP0YZp7QyGDyOQ1nwILRIVT3kd58NYxo

선택 화 다운로드는 테스트 버전에서 쓰실 수 있어요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by ak156** [comment]
선생님 또다시 막힌거같아요 ㅠㅠ

**Comment by ak156** [comment]
선생님 다시 막힌거같아요 ㅠㅠ 어제부터 다시 안되더라구요

**Comment by KurtBestor** [comment]
테스트 해보니 전 잘 되네요. 실패한 작업 마우스 우클릭해서 `정보... (I)` 눌러서 나온 내용 보여주세요.

**Comment by ak156** [comment]
엇 그러네요 다시되네요 뭐지...ㅎ 2일간 계속안되서 안되는줄알앗는데 번거롭게해드려서 죄송해요

**Comment by ak156** [comment]
Invalid: https://newtoki.com / webtoon / 105391 / %EB%8D%98%EC%A0%84%EC%97%90%EC%84%9C-%EB%A7%8C%EB%82%A8%EC%9D%84-%EC%B6%94%EA%B5%AC%ED%95%98%EB%A9%B4-%EC%95%88-%EB%90%98%EB%8A%94-%EA%B1%B8%EA%B9%8C-%EC%97%90%ED%94%BC%EC%86%8C%EB%93%9C-%EB%A5%98?toon=%EB%8B%A8%ED%96%89%EB%B3%B8

gal_num: https://newtoki.com/webtoon/105391/%EB%8D%98%EC%A0%84%EC%97%90%EC%84%9C-%EB%A7%8C%EB%82%A8%EC%9D%84-%EC%B6%94%EA%B5%AC%ED%95%98%EB%A9%B4-%EC%95%88-%EB%90%98%EB%8A%94-%EA%B1%B8%EA%B9%8C-%EC%97%90%ED%94%BC%EC%86%8C%EB%93%9C-%EB%A5%98?toon=%EB%8B%A8%ED%96%89%EB%B3%B8
dir: 
zip: 
type: 
artist: None
url: https://newtoki.com/webtoon/105391/%EB%8D%98%EC%A0%84%EC%97%90%EC%84%9C-%EB%A7%8C%EB%82%A8%EC%9D%84-%EC%B6%94%EA%B5%AC%ED%95%98%EB%A9%B4-%EC%95%88-%EB%90%98%EB%8A%94-%EA%B1%B8%EA%B9%8C-%EC%97%90%ED%94%BC%EC%86%8C%EB%93%9C-%EB%A5%98?toon=%EB%8B%A8%ED%96%89%EB%B3%B8
valid: False
done: False
range: None
range_p: None
single: True
time: 1545289128.33 (Dec 20)


[Gallery]
None


[File Names]



[URLs]
이런식으로 뜨면서 안되더라구요

**Comment by ak156** [comment]
지금은 잘되고있씁니다 감사합니다
