### ISSUE TITLE
nozomi.la 추가 하실 생각 있으신지 궁금합니다.

### ISSUE THREAD

**Issue by shopinclude** [KurtBestor/Hitomi-Downloader-issues#331]
아시다 시피 히토미의 짤 모음 버전 사이트인데 아직 언급이 없는 것 같아서 혹시 추가하실 생각이 있으신지 궁금합니다.

**Comment by shopinclude** [comment]
흠.. 안타깝지만 안되시는 것 같네요.

혹시 괜찮으시다면 사이트 추가하시는데 어떤 기준 같은게 있는지 궁금합니다.

쭉 보니까 어떤 건 되고 어떤 건 안 되고 하시는 걸 보니 서버랑 관련이 있나 싶어서요.

**Comment by KurtBestor** [comment]
기준은 제 흥미에 따라 갈려요.
짤 사이트는 [Gelbooru](https://gelbooru.com/)나 [Sankakucomplex](https://www.sankakucomplex.com/)를 이미 지원하고 있어요.

나중에 흥미 생기면 할 수도 있고요. 다음처럼요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/109

**Comment by shopinclude** [comment]
빠른 답변 및 정보 감사합니다.

아무튼 잘 쓰고 있고, 앞으로도 잘 부탁드립니다.
