### ISSUE TITLE
다운로드 폴더명

### ISSUE THREAD

**Issue by locien10** [KurtBestor/Hitomi-Downloader-issues#332]
다운로드 폴더가 설정될 때 뒤에 _maru, _twitter, _manazero 와 같이 붙어서 저장되는데, 그게 아니라 딱 제가 지정한 폴더에 다운되도록 하고 싶은데 방법이 있나요..?

**Comment by KurtBestor** [comment]
현재는 없어요. 설정해야하는 이유가 특별히 있나요?

**Comment by locien10** [comment]
만화가 다운가능한 곳이 여러곳있는데 각자 다른 폴더에 저장되고 재 다운로드시에 다른 폴더에 있어서 합치기가 어렵다는 생각이 들어서 그렇습니다.
