### ISSUE TITLE
제이마나 다운로드오류

### ISSUE THREAD

**Issue by spillriver** [KurtBestor/Hitomi-Downloader-issues#334]
제이마나 다운로드가 제대로 되지않습니다.
주소를 읽는도중 invalid가 뜨는데
확인 부탁드려요..

**Comment by ldh7680** [comment]
쇼미도 그렇네요 쇼미는 로그인없이 만화볼 수 있게 바뀌어서 그런가 모르겠네요 확인해주세요

**Comment by momokoro1** [comment]
주소가 바뀌어서 그렇지 않을까요.
스크립트 주소만 좀 수정하니 정상 작동 하는 거 같네요

**Comment by KurtBestor** [comment]
@spillriver 테스트해보니 저는 잘 되네요. 실패한 작업 마우스 우클릭해서 `[정보... (I)]` 눌러서 나온 내용 보여주세요.

**Comment by KurtBestor** [comment]
@ldh7680 스크립트 수정했어요: https://drive.google.com/drive/folders/1FP0YZp7QyGDyOQ1nwILRIVT3kd58NYxo

**Comment by macmorningg** [comment]
감사합니다

**Comment by spillriver** [comment]
아무래도 서버오류때문에 작동하지 않았던듯합니다.
감사합니다 :)

**Comment by leez32** [comment]
Invalid : [mangashow] http://mangashow.me / detail.php?manga_id=4361

gal_num: http://mangashow.me/detail.php?manga_id=4361
dir: 
zip: 
type: mangashow
artist: None
url: https://mangashow.me/detail.php?manga_id=4361
valid: False
done: False
range: None
range_p: None
single: False
time: 1544042718.92 (Dec 6)


[Gallery]
None


[File Names]



[URLs]



[Messages]
stop
Traceback (most recent call last):
File "utils", line 403, in start
File "utils", line 414, in start_
File "dynamic_module_2", line 72, in read
File "dynamic_module_2", line 68, in name
AttributeError: 'NoneType' object has no attribute 'div'

Fail: mangashow

쇼미 스크립트 추가해도 다음과 같이 에러가 뜨는데 문제가 뭔지 알 수 있을까요?

**Comment by momokoro1** [comment]
쇼미 정상 작동 합니다
개발자님 감사합니다!

**Comment by leez32** [comment]
감사합니다. 혹시 마루마루01은 어느 스크립트를 받아야 하는건가요?

**Comment by KurtBestor** [comment]
@leez32 마루마루01은 지원하지 않아요.

**Comment by li4ac1212** [comment]
마루마루 (x화~xx화) 다운로드 시스템을 망가쇼미로 바꿔주실 수도 있나요?

**Comment by li4ac1212** [comment]
만화가 목록에 뜨는데 실제로 파일은 안받아 지는데 어떻게 하나요?

**Comment by KurtBestor** [comment]
@li4ac1212  참고해주세요: #369
