### ISSUE TITLE
마루마루01 (망가쇼미) 다운로드가 가능한가요?

### ISSUE THREAD

**Issue by macmorningg** [KurtBestor/Hitomi-Downloader-issues#335]
디시 만화갤러리에서 누가 제이마나랑 같이 가능하게 만들었다고 들은거같은데 혹시 안된다면 새로 만들엊 실수있으신가요? 마루마루 망하고 원래 운영자가 만든 사이트라고 얘기가 나오더라구요

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/334#issuecomment-443959261
