### ISSUE TITLE
질문있습니다 

### ISSUE THREAD

**Issue by ourload** [KurtBestor/Hitomi-Downloader-issues#336]
올라온 글들을 쭉 보니 스크립트 추가 외에도 히요비 나 네이버 블로그 원본 사진 다운 제이마나 오류 수정등
hitomi downloader_gui.exe  프로그램도 수정이 많이 된거 같은데요 가장 최근 버전만 다운 받으면 그전에 내용들은 다 들어가 있는건가요??

**Comment by KurtBestor** [comment]
아뇨, 수정된 내용은 [Technical Preview](https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview) 에서 확인할 수 있어요.

**Comment by ourload** [comment]
> 아뇨, 수정된 내용은 [Technical Preview](https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview) 에서 확인할 수 있어요.

아 제가 질문을 잘못한거 같네요 추가된 기능의 내용이 아니라 가장 최신 버전에 그전에 추가된 기능이 전부 들어가 있는지를 여쭤본 거에요 ㅎ
