### ISSUE TITLE
폴더 분류없이 한 폴더에 다운가능한가요?

### ISSUE THREAD

**Issue by ldh7680** [KurtBestor/Hitomi-Downloader-issues#337]
지금 다운 받으면
hitomi_downloaded_maru 이런식으로 분류되서 각 사이트마다 폴더가 따로 생성되어 다운되는데
그냥 모든사이트 다운경로를 한폴더로 설정이 가능한가요?

**Comment by ciotte** [comment]
프로그램 잘쓰고 있습니다. 저도 한 폴더에 모든 사이트 설정 가능했으면 좋겠어요. 감사합니다.
