### ISSUE TITLE
뉴토끼 다운이 안됩니다 ㅠ

### ISSUE THREAD

**Issue by ourload** [KurtBestor/Hitomi-Downloader-issues#338]
Invalid: https://newtoki.com / newtoki / 104

gal_num: https://newtoki.com/newtoki/104
dir: 
zip: 
type: None
artist: None
url: https://newtoki.com/newtoki/104
valid: False
done: False
range: None
range_p: None
single: True
time: 1544085430.88 (Dec 6)

[Gallery]
None

[File Names]

[URLs]

[Messages]
Traceback (most recent call last):
File "hitomi_downloader_GUI", line 1157, in run
File "utils", line 129, in pop
IndexError

Fail: ??

done : https://newtoki.com/newtoki/104

스크립트에 추가되어 있는 newtoki가 여기 맞죠??

**Comment by KurtBestor** [comment]
다음과 같이 목록 주소를 입력해주세요: https://newtoki.com/webtoon/145828
