### ISSUE TITLE
혹시 전체말고 한편씩 다운로드 할수있나요?

### ISSUE THREAD

**Issue by FKDLTBSK1020** [KurtBestor/Hitomi-Downloader-issues#339]
쇼미같은데 한편씩 할려고해도 전체다운로드로 되서 디씨처럼 한편씩 다운받고 싶어서 그런데 혹시 설정이있나요?

**Comment by KurtBestor** [comment]
단일화 다운로드 되게 수정했어요: https://drive.google.com/drive/folders/1FP0YZp7QyGDyOQ1nwILRIVT3kd58NYxo

**Comment by FKDLTBSK1020** [comment]
감사합니다
