### ISSUE TITLE
pawoo.net 추가 건의합니다.

### ISSUE THREAD

**Issue by chbk256** [KurtBestor/Hitomi-Downloader-issues#341]
히토미 다운로더 잘 쓰고 있습니다.

혹시 https://pawoo.net 가능하신가요?

이미지 서처로 검색시에 꽤나 자주 뜨는 곳입니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview
