### ISSUE TITLE
니코동 영상 다운 안됩니다

### ISSUE THREAD

**Issue by kryuger** [KurtBestor/Hitomi-Downloader-issues#343]
2017년 이전, 2016년부터의 예전 영상들은 다운이 안됩니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by kryuger** [comment]
정상적으로 다운되네요 감사합니다
