### ISSUE TITLE
늘감사합니다

### ISSUE THREAD

**Issue by david761276** [KurtBestor/Hitomi-Downloader-issues#345]
늘 감사드립니다 ^^  너무 잘 사용하고 있어요..ㅎㅎ

질문을 하나 드리려고 합니다.

제컴이 이상한건지...
호두코믹스에서 전편말고 회차로는 다운이 안되는 건가 궁금합니다.

질문이 먼가 부탁드리는 느낌이라 죄송스럽네요... 

날씨가 춥습니다  건강하세요 ^^

**Comment by KurtBestor** [comment]
현재 버전에선 지원하지 않지면 테스트 버전에선 지원해요. 스크립트를 새로 받아서 테스트버전에 넣으면 돼요.
스크립트: https://drive.google.com/drive/folders/1FP0YZp7QyGDyOQ1nwILRIVT3kd58NYxo
테스트 버전: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/330#issuecomment-446467345

**Comment by david761276** [comment]
아~~~ 테스트 버젼이 있었네요...   감사합니다 ^^

**Comment by david761276** [comment]
제가 잘 못하는 건지....  T T 

알려주신대로 test버젼으로 스크립트 넣어 사용했는데....
전체로는 다운로드 되는 그냥 한편씩은 안되네요..
스크립트 안에 도메인은 houd21 로 바꾸긴 했는데...

lnvalid : https://houd21.com / webtoon / view / 108793     빨간색 에러뜨네요...

뉴토끼도 스크립트 있어서 함께 해보았는데.. 
전치 화는 다운이 되는데..    역시나 한편씩은 안됩니다.

바쁘실텐데....   제가 어떻게든 해보려고 했는데..실력이 없어놔서..ㅠㅠ.

조언부탁드릴꼐요....     감사합니다 ^^

**Comment by david761276** [comment]
아~~  방법을 찾았습니다. ^^

다운로드 아이콘에 회차 다운로드가 있었네요.... 

잘받아집니다..  정말 잘 만드신 프로그램 같아요...

고맙습니다.
