### ISSUE TITLE
기본 데이터 다운로드가 안됩니다.

### ISSUE THREAD

**Issue by YTOAA** [KurtBestor/Hitomi-Downloader-issues#347]
기본 데이터 다운로드 할시 0%에서 움직이지 않습니다. 갑자기 어찌된 영문인지..
삭제된 데이터는 안해봐서 모르겠습니다.

**Comment by KurtBestor** [comment]
아래 링크 들어가면 어떻게 보이나요?
https://ltn.hitomi.la/galleries0.json
