### ISSUE TITLE
망가쇼미에서 어떻게 다운받나요..??

### ISSUE THREAD

**Issue by alskfl01** [KurtBestor/Hitomi-Downloader-issues#348]
얼마전에야 이 프로그램을 알아서 잘 쓰고 있습니다.

다름이 아니라 제가 사용법을 잘 몰라서 질문을 드리고자 합니다

주소창에 만화 주소를 붙여넣기 하면

Invalid: https://mangashow.me / bbs / board.php?bo_table=msm_manga&wr_id=93348

gal_num: https://mangashow.me/bbs/board.php?bo_table=msm_manga&wr_id=93348
dir: 
zip: 
type: None
artist: None
url: https://mangashow.me/bbs/board.php?bo_table=msm_manga&wr_id=93348
valid: False
done: False
range: None
range_p: None
single: True
time: 1544683880.31 (Dec 13)

[Gallery]
None

[File Names]

[URLs]

[Messages]
Traceback (most recent call last):
File "hitomi_downloader_GUI", line 1157, in run
File "utils", line 129, in pop
IndexError

Fail: ??

done : https://mangashow.me/bbs/board.php?bo_table=msm_manga&wr_id=93348

위와 같이 나오는데 해결 방법좀 알려주시면 감사하겠습니다

그리고 회차목록에서 여러편을 동시에 다운할수 있는 방법이 있다면 같이 부탁드리겠습니다

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by alskfl01** [comment]
빠른 답변 정말 감사드립니다(--)(__)

**Comment by jtrpc** [comment]
테스트 해보니 아래와 같이 에러가 나오고 다운되지 않습니다
<img width="241" alt="aaa" src="https://user-images.githubusercontent.com/45491907/49972596-81e00980-ff75-11e8-80cc-d4359ba44996.png">

**Comment by KurtBestor** [comment]
@jtrpc 어떤 주소를 입력했나요? 목록 주소 입력한 거 맞나요?

**Comment by jtrpc** [comment]
https://mangashow.me/bbs/board.php?bo_table=msm_manga&wr_id=1

이런식으로 한 화를 입력하였습니다...
혹시 이런식으로도 가능할까요?

이슈를 올리려다 이글과 중복인거 같아서 내렸습니다. ㅠ

**Comment by KurtBestor** [comment]
@jtrpc 목록 주소 입력해서 `선택화 다운로드` 하시면 돼요.

**Comment by jtrpc** [comment]
답변 감사합니다.

그렇게 쓰는거였군요...


혹시 폐가 안된다면 https://mangashow.me/bbs/board.php?bo_table=msm_manga&wr_id= 숫자
식으로도 가능할까요?

**Comment by KurtBestor** [comment]
@jtrpc 개발 도중에 넣었었는데, 하나만 다운로드 가능한 걸로 오해하는 분들이 있어서 뺐어요.
