### ISSUE TITLE
인스타에서 이미지 다운로드시 파일이 이상합니다

### ISSUE THREAD

**Issue by als75** [KurtBestor/Hitomi-Downloader-issues#349]
안녕하세요 만들어주신 프로그램 잘사용하고있습니다^^
얼마전까지 인스타에서 이미지를 받는데 멀쩡하였으나 최근에 갑자기 일부 이미지나 동영상이 .com이라는 확장자로 보이며 읽을수없는 상태로 나오고 있습니다.
확인 부탁드립니다^^

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by als75** [comment]
정상적으로 작동합니다.
감사합니다^^
혹시 정상적으로 받아지다가
Traceback (most recent call last):
File "insta_downloader3", line 51, in read
File "insta_downloader3", line 248, in get_imgs
Exception: Too short

이런 메세지를 나타내는경우 무엇이 원인일까요?

**Comment by KurtBestor** [comment]
해당 작업 마우스 우클릭해서 `정보... (I)` 눌러서 나온 내용 보여주세요.

**Comment by als75** [comment]
제가 다시제현될줄알고 일부만 남겨놔서 이렇게밖에 로그가 안남아있네요...
Traceback (most recent call last):
File "insta_downloader3", line 51, in read
File "insta_downloader3", line 248, in get_imgs
Exception: Too short

**Comment by KurtBestor** [comment]
비공개 계정이면 그렇게 나와요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/284

공개 계정인데도 오류가 나면 해당 주소 알려주세요.
