### ISSUE TITLE
제작 감사합니다. 건의 드릴게 있습니다.

### ISSUE THREAD

**Issue by mita5549** [KurtBestor/Hitomi-Downloader-issues#351]
만화 수집을 취미로 하고 있는 사용자입니다.
 기존의 프로그램은 물론, 지금은 쇼미 다운로더로도 잘 쓰고 있습니다. 굉장히 빠르네요. :)

 다만, 제가 프로그램의 사용법을 제대로 이해 하고 있는 건지는 잘 모르겠습니다만,
작품 하나만을 지정해서 읽어오는 지금의 방식에서 조금 아쉬움을 느끼는 부분이 있습니다.

 혹시 검색기의 기능에서처럼 **업데이트 목록**에서 내려받아 갱신하거나, 읽어오고, 다운로드 받을 수는 없을까요? https://mangashow.me/bbs/board.php?bo_table=msm_manga 업데이트 게시판은 이쪽입니다.

**Comment by jtrpc** [comment]
작품 이름이 들어간 링크로 넣어야하는 불편함때문에
https://mangashow.me/bbs/board.php?bo_table=msm_manga&wr_id= 숫자
와 같이라도 된다면 해당 숫자 범위로 전체 다운로드 하면 될거 같기도 합니다만

위 말대로 리스트 다운이 가능하면 더할나위 없이 좋겠네요.

**Comment by KurtBestor** [comment]
숫자 범위는 다음 두 개 처럼 의미가 없어요:
https://mangashow.me/bbs/board.php?bo_table=msm_manga&wr_id=1
https://mangashow.me/bbs/board.php?bo_table=msm_manga&wr_id=2

`선택 화 다운로드`가 있으니 그걸 쓰세요.

참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/348

**Comment by mita5549** [comment]
선택 화 다운로드가 업데이트 목록에서도 작동하나요?
작품 하나(ex원피스1~최신화의 목록)에서만 작동하던 거 같던데...

**Comment by KurtBestor** [comment]
@mita5549 업데이트 목록은 여러가지 작품이 섞여있어서 동작하지 않아요. 원하시는 작품 골라서 다운로드 하시면 돼요.

**Comment by jtrpc** [comment]
해당사이트에 있는걸 싹 받는 방법이 없어서 직접 한개씩 통링크를 눌러 받기가 너무 힘든데
검색기 같은 방식이나
https://mangashow.me/bbs/board.php?bo_table=msm_manga&wr_id=숫자 방식으로 동작되게 해주세요.

https://mangashow.me/bbs/board.php?bo_table=msm_manga&wr_id=1
https://mangashow.me/bbs/board.php?bo_table=msm_manga&wr_id=2 
가 서로 연관이 없는것은 알고 있습니다

각 페이지당 내부에 제목이 있으니 그걸 기준으로 분류했으면 합니다

나중에 새로 갱신된걸 확인도 안되고 전부 받아버리니
https://mangashow.me/bbs/board.php?bo_table=msm_manga&wr_id=100000 와 같이
시도라도 해서 숫자 증가된것만 업데이트식으로 받으려고 합니다

**Comment by KurtBestor** [comment]
@jtrpc 필요한 작품 추가해놓고 저장한 다음, 필요할 때마다 우클릭해서 `다시 시작` 하시면 업데이트 돼요.
사이트에 있는 작품 모두를 받는 건 이 프로그램을 만든 의도와는 많이 멀어요.
보는 작품 / 안 보는 작품이 있을테니 보는 작품만 추가하시면 돼요.

**Comment by mita5549** [comment]
@KurtBestor 그렇군요.ㅠㅠ답변 감사합니다!
