### ISSUE TITLE
망가쇼미 서버에 있는 만화 전체 다운로드되게 할수 있습니까?

### ISSUE THREAD

**Issue by rakamir** [KurtBestor/Hitomi-Downloader-issues#352]
망가쇼미 서버에 있는 만화를 다 오프라인으로 보고 싶습니다. 그래서 한 번에 다 다운 받으려고 하는게 가능한가요?

**Comment by KurtBestor** [comment]
그런 작업은 [HTTrack](https://www.httrack.com/) 같은 오프라인 브라우저를 이용해주세요.
