### ISSUE TITLE
선생님 망가쇼미가 오류뜹니다

### ISSUE THREAD

**Issue by ouchh** [KurtBestor/Hitomi-Downloader-issues#353]
https://mangashow.me/bbs/page.php?hid=manga_detail&manga_name=%ED%98%B8%EC%A6%88%ED%82%A4%EA%B0%80%EC%9D%98%20%EB%88%84%EB%8B%98%20%EC%8B%9C%EB%A6%AC%EC%A6%88
와 같이 목록주소를 붙여넣기 해서 다운로드를 하려고 해도
Invalid: https://mangashow.me/bbs/page.php?hid=manga_detail&manga_name=%ED%98%B8%EC%A6%88%ED%82%A4%EA%B0%80%EC%9D%98%20%EB%88%84%EB%8B%98%20%EC%8B%9C%EB%A6%AC%EC%A6%88
라고 뜹니다 버전은 2.5a입니다 제이마나는 잘됩니다

**Comment by KurtBestor** [comment]
테스트 버전 써주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

아직 정식 버전 (v2.5a) 에선 지원하지 않아요.

**Comment by ouchh** [comment]
> 테스트 버전 써주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview
> 
> 아직 정식 버전 (v2.5a) 에선 지원하지 않아요.

감사합니다 항상 고생많으십니다 수고하세요
