### ISSUE TITLE
싸이트 추가 건의드립니다

### ISSUE THREAD

**Issue by siwkd2** [KurtBestor/Hitomi-Downloader-issues#359]
안녕하세요 프로그래머님 만들어주신 프로그램 잘 사용하고있습니다

다름이 아니라 제가 옛날애니를 구하고자하는데 

옛날 애니메이션은 토렌트가 작동이 안되서 구하기힘들고 p2p싸이트에 없는경우도 있더라구요 

그래서 애니스트리밍싸이트에서 다운을 받을려고하는데 혹시  

http://ani24view.com

이 싸이트 추가해주실수 없는지 해서 건의드립니다

건의사항 읽어주셔서 감사합니다

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://drive.google.com/drive/folders/1FP0YZp7QyGDyOQ1nwILRIVT3kd58NYxo

`ani24.hds` 파일이에요.

그런데 만들고 보니 단일화 다운로드는 사이트에서 이미 지원하네요. 참고해주세요.

**Comment by siwkd2** [comment]
> 테스트 부탁드려요: https://drive.google.com/drive/folders/1FP0YZp7QyGDyOQ1nwILRIVT3kd58NYxo
> 
> `ani24.hds` 파일이에요.
> 
> 그런데 만들고 보니 단일화 다운로드는 사이트에서 이미 지원하네요. 참고해주세요.

이걸 이제서야 봤네요 

만들어주셔서 정말 감사드립니다 잘쓰도록하겠습니다
