### ISSUE TITLE
건의사항:가끔 마루마루 만화중 404 뜨는만화가 있습니다..

### ISSUE THREAD

**Issue by YTOAA** [KurtBestor/Hitomi-Downloader-issues#36]
예를들어 첫사랑좀비 58화만...
404 not 이 뜹니다
이런건 ..건너뛸수있는 방법이 있으면 좋겠습니다
한화때문에...나머지 전체를 다운로드 못받는...

**Comment by KurtBestor** [comment]
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

고친 버전입니다. 테스트 부탁드려요.

**Comment by KurtBestor** [comment]
v2.1b에서 해결됨
