### ISSUE TITLE
망가쇼미 테스트 서버 오류 도와주세요 ㅠㅠ

### ISSUE THREAD

**Issue by wdojkqjo** [KurtBestor/Hitomi-Downloader-issues#360]
버전은 제대로 v2.5b 입니다. 4개 정도 만화가 잘 다운됐었는데 선택 화 다운로드로 하려고 누르자 그 후부터 그냥 일반 다운로드를 하려고 해도 아래와 같이 나오며 오류가 납니다. 이 만화가 특이한 건가 하고 다른 망가쇼미 만화 주소를 넣어 봐도 전부 이런 식으로 뜹니다. 파일을 지웠다가 다시 깔아봐도 마찬가지로 해결이 되지 않고 있습니다...

Invalid : [mangashow] https://mangashow.me / bbs / page.php?hid=manga_detail&manga_name=아이돌

gal_num: https://mangashow.me/bbs/page.php?hid=manga_detail&manga_name=아이돌
dir: 
zip: 
type: mangashow
artist: None
url: https://mangashow.me/bbs/page.php?hid=manga_detail&manga_name=아이돌
valid: False
done: False
range: None
range_p: None
single: False
time: 1545375767.15 (Dec 21)

[Gallery]
None

[File Names]

[URLs]

[Messages]
stop
Traceback (most recent call last):
File "utils", line 413, in start
File "utils", line 424, in start_
File "mangashow_downloader", line 74, in read
File "mangashow_downloader", line 152, in get_imgs
File "mangashow_downloader", line 143, in get_pages
Exception: no pages

Fail: mangashow

done : https://mangashow.me/bbs/page.php?hid=manga_detail&manga_name=아이돌

**Comment by KurtBestor** [comment]
주소를 복사할 때 어떤 웹브라우저를 썼나요?

**Comment by wdojkqjo** [comment]
>           주소를 복사할 때 어떤 웹브라우저를 썼나요?

마이크로 엣지입니다 아 혹시 익스플로러로 해야 하나요?

**Comment by KurtBestor** [comment]
주소가 잘못되어서요. 다음 주소는 잘못된 주소예요:
https://mangashow.me/bbs/page.php?hid=manga_detail&manga_name=아이돌

아마 띄어쓰기가 포함돼서 뒷부분이 잘린게 아닌가 하는데, 제가 아는 웹브라우저는 모두 띄어쓰기를 %20 으로 표시해서 물어본 거예요.

제가 테스트 해보니 엣지 브라우저도 띄어쓰기를 %20으로 표시하는데, 주소에 띄어쓰기가 포함되어있나요?

**Comment by wdojkqjo** [comment]
>           주소가 잘못되어서요. 다음 주소는 잘못된 주소예요:
> [https://mangashow.me/bbs/page.php?hid=manga_detail&manga_name=아이돌](https://mangashow.me/bbs/page.php?hid=manga_detail&manga_name=%EC%95%84%EC%9D%B4%EB%8F%8C)
> 아마 띄어쓰기가 포함돼서 뒷부분이 잘린게 아닌가 하는데, 제가 아는 웹브라우저는 모두 띄어쓰기를 %20 으로 표시해서 물어본 거예요.
> 제가 테스트 해보니 엣지 브라우저도 띄어쓰기를 %20으로 표시하는데, 주소에 띄어쓰기가 포함되어있나요?

복사해서 바로 프로그램에 넣었을 땐 없었습니다. 띄어쓰기 부분에 알려주신 %20을 넣고 해보니 정상작동 합니다. 처음에 다운 됐다던 것들중에 데드 마운트 데스 플레이라고 띄어쓰기 부분이 있는 만화가 있는데 이건 정상작동 했었는데 지금 다시 주소창 붙여넣기 해보니 위와 똑같은 오류가 납니다. 선택화 다운로드 버튼을 누른 후 무언가 변경된 것인지 어떤 것인지는 몰라도 직접 쳐서 넣으니 해결됐습니다. 감사합니다.
