### ISSUE TITLE
궁금한게 있습니다.

### ISSUE THREAD

**Issue by koh1264** [KurtBestor/Hitomi-Downloader-issues#363]
항상 감사드리고 있습니다. 

그런데 궁금한게 있는데요.

윈도우용 프로그램만 있는게 맞는건가요?

혹시 맥용은 없나요?

**Comment by KurtBestor** [comment]
네, 맥이나 리눅스에선 [Wine](https://www.winehq.org/) 같은 호환성 레이어를 써서 실행해주세요.
