### ISSUE TITLE
파일 매니저 기능 건의드립니다

### ISSUE THREAD

**Issue by xesgnik** [KurtBestor/Hitomi-Downloader-issues#364]
우선 좋은 프로그램 잘쓰고 있습니다. 감사합니다.

다운로더를 통해서 다운받은 작품을 썸네일 클릭을 통해서 볼 수 있는게 굉장히 편하던데, 애석하게도 작품을 많이 받다보면 순서도 그렇고 원하는 작품을 보기에 힘들더라구요.

혹시 다운로드 폴더내에 있는 작품들을 이름순 등으로 정리하거나, info.txt에 있는 태그정보를 기반으로 원하는 태그별로 필터링할 수 있는 기능이 있었으면 정말 좋겠습니다. 감사합니다!

**Comment by KurtBestor** [comment]
다음과 같이 태그로 필터링할 수 있어요:
![image](https://user-images.githubusercontent.com/14768120/50369393-4c23cc00-05d8-11e9-9b93-081ede2c7c8e.png)

`도움말 - 사용법... (F1) - 다운로더 목록 필터링` 을 참고해주세요.

만약 목록에서 지운것도 검색하고싶다면 [FindInFiles](http://toolscode.com/findinfiles/) 같은 프로그램으로 info.txt 검색하면 돼요.

**Comment by xesgnik** [comment]
빠른 답변 정말 감사드립니다! 

방금 생각난건데 검색기에서 히토미 데이터가 아닌 다운로드폴더내 info.txt 기반으로 검색할 수 있는 기능은 혹시 구현하기 까다로울까요? 링크해주신 FindInFiles는 보았는데 아무래도 KurtBestor님 UI가 더 깔끔하고 취지에 부합하는거 같아서 질문드려봅니다!

우선은 알려주신 기능 잘 활용하도록 하겠습니다 감사합니다!

**Comment by xesgnik** [comment]
추가문의 같은 경우 다른 포스트로 하는게 나을까요?

다운로더에 있는 필터링 기능을 사용하고 싶어서 저장 폴더에 있는 모든 갤러리 넘버 복사로 가져와서 추가한 후에 그 목록을 내보냈는데 중간에 에러메세지가 뜨면서 강종된 후 다시 열어보니까 추가목록이 다 사라졌습니다 ㅠㅠ. 그 후 생성된 hdt파일로 가져오기를 시도했는데 아래와 같은 메세지가 뜨네요.

![1](https://user-images.githubusercontent.com/46060275/50369720-daac3500-0567-11e9-8359-6daba3f658fd.PNG)

혹시 생성하려는 목록이 너무 커서 이런 문제가 생긴걸까요? (약 2000작품정도됩니다) 그리고 저장을 한 후에 이미 완료된 작품들의 30%~40% 정도를 다시가져오던데 이는 왜그런것인지 궁금합니다. 감사합니다!

**Comment by KurtBestor** [comment]
저장한 HDT 파일 용량이 어떻게 되나요? 만약 0 KB 이면 저장을 하지 못한거예요. 만약 0 KB가 아닌데도 내용을 읽지 못했다면 해당 HDT 파일 보내주시면 분석해볼게요.

목록은 900개 내로 하는게 안전해요.

참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/170

**Comment by xesgnik** [comment]
방금 500개정도로 만들었는데 160MB정도네용. 근데 이거를 import하니까 메모리 에러가 뜨네요 ㅠㅠ 설치되어있는 램은 16gb인데 혹시 왜 이런 문제가 생기는지 아시는 부분 있으신가요??

**Comment by KurtBestor** [comment]
원래 목록에 있던 걸 모두 지우고 import 해보세요.

32비트 프로그램이라서 메모리를 2GB 정도 밖에 쓰지 못해요.

**Comment by xesgnik** [comment]
다시하니까 잘되네요. 감사합니다!
