### ISSUE TITLE
히토미 다운로드가 되지 않습니다

### ISSUE THREAD

**Issue by alkjfgh** [KurtBestor/Hitomi-Downloader-issues#365]
서버를 옮겨보아도 다운로드가 진행되지 않습니다...
[0920/010754.452:ERROR:crash_report_database_win.cc(427)] unexpected header 로그에는 이렇게 뜹니다

**Comment by KurtBestor** [comment]
실패한 작업 마우스 우클릭해서 `정보... (I)` 눌러서 나오는 내용 보여주세요.

**Comment by alkjfgh** [comment]
Fail : \\Lab\HDD2\\?\\\Lab\HDD2\hitomi_downloader_GUI\hitomi_downloaded\[Kenpi] Namaiki JK Sumireko-chan ga Ayatsura Rape!! ｜ 건방진 JK 스미레코쨩을 조종 레이프!! (1332466)\16.jpg
Traceback (most recent call last):
File "downloader", line 595, in download
IOError: [Errno 22] invalid mode ('wb') or filename: u'\\\\Lab\\HDD2\\\\?\\\\\\Lab\\HDD2\\hitomi_downloader_GUI\\hitomi_downloaded\\[Kenpi] Namaiki JK Sumireko-chan ga Ayatsura Rape!! \uff5c \uac74\ubc29\uc9c4 JK \uc2a4\ubbf8\ub808\ucf54\uca29\uc744 \uc870\uc885 \ub808\uc774\ud504!! (1332466)\\16.jpg'

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/195

**Comment by alkjfgh** [comment]
빠른 답변 감사합니다
