### ISSUE TITLE
망가쇼미 단일화 주소만으로도 다운로드 할수 없을까요?

### ISSUE THREAD

**Issue by ciotte** [KurtBestor/Hitomi-Downloader-issues#366]
안녕하세요 히토미 다운로더 잘 쓰고 있습니다. 지금 사용하는 버전은 2.5B입니다.

차후 업데이트에서 개별화 주소만 복불해도 다운로드 할 수 있도록 해주시면 감사하겠습니다.

지금도 전체주소를 받아 단일화 선택해서 다운로드 할수 있는 기능은 알고있습니다만 그 절차가 복잡해요. 

예를 들어 전체 다운로드는 전체 주소 복사한뒤 엔터 누르면 시작합니다.

반면에 새롭게 업데이트된 만화만 다운 받고 싶다면, 해당 주소가 아닌 전체주소를 복사하고, 바로 시작버튼이 아닌 오른쪽 화살표 메뉴를 누른 다음, 새로운 만화 회차를 드래그하면서 찾아서 선택하고 다운로드를 눌러야 합니다.

사실상 개별화 다운로드 기능은 손이 안가게 되지만, 새로운 업데이트가 나올때 마다 전체화 다운로드 받는것은 비효율적이에요.

예전 버전에 쇼미 스크립트 불러와서 사용할 때는 개별화 주소만 복불해도 잘 되었는데, 지금 그 기능이 안되는 이유는 쇼미 사이트 개편인가요? 아니면 히토미 다운로더 기능 변경인가요?

기존 기능은 그 나름대로 필요성은 있지만 개별화 주소만 복사후 받는 기능은 꼭!! 필요합니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by ciotte** [comment]
잘 되네요. 테스트 버전 감사합니다.
