### ISSUE TITLE
픽시브 북마크다운로드 관련 질문입니다

### ISSUE THREAD

**Issue by cmg504** [KurtBestor/Hitomi-Downloader-issues#367]
픽시브 유저 북마크링크를 넣어서 다운로드 하는데 북마크의 숫자가 16000개가 좀 넘는데요 전부 인식을 못하는것인지 Invalid가 뜨면서 다운이 안됩니다. 많아서 그런가 싶어서 페이지 지정을 통해 10000페이지까지만 다운로드 하도록 설정하고 해보니 10000페이지까지는 다운로드 됩니다. 10001 ~ 20000으로 지정하고 하면 안됩니다

**Comment by cmg504** [comment]
> 픽시브 유저 북마크링크를 넣어서 다운로드 하는데 북마크의 숫자가 16000개가 좀 넘는데요 전부 인식을 못하는것인지 Invalid가 뜨면서 다운이 안됩니다. 많아서 그런가 싶어서 페이지 지정을 통해 10000페이지까지만 다운로드 하도록 설정하고 해보니 10000페이지까지는 다운로드 됩니다. 10001 ~ 20000으로 지정하고 하면 안됩니다

**Comment by KurtBestor** [comment]
해당 작업 마우스 우클릭 - `정보... (I)` 눌러서 나온 내용 보여주세요.

**Comment by cmg504** [comment]
Invalid : [pixiv] https://www.pixiv.net / bookmark.php?id=4595251

gal_num: https://www.pixiv.net/bookmark.php?id=4595251
dir: 
zip: 
type: pixiv
artist: None
url: https://www.pixiv.net/bookmark.php?id=4595251
valid: False
done: False
range: None
range_p: None
single: False


[Gallery]
None


[File Names]



[URLs]



[Messages]
PIXIV_TYPE: bookmark
Type: all
stop
Traceback (most recent call last):
File "utils", line 398, in start
File "utils", line 409, in start_
File "pixiv_downloader", line 132, in read
File "pixiv_downloader", line 324, in get_imgs
File "pixiv_downloader", line 350, in get_imgs_from_illust
File "pixivpy3\utils", line 24, in __getattr__
AttributeError: 'JsonDict' object has no attribute 'ugoira_metadata'

Fail: pixiv

done : https://www.pixiv.net/bookmark.php?id=4595251

이렇게 나옵니당

**Comment by KurtBestor** [comment]
다음 실행파일로 다시 시도해서 실패하면 해당 작업 마우스 우클릭 - 정보... (I) 눌러서 나온 내용 보여주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by cmg504** [comment]
왜인지는 모르겠는데 2.5버전부터는 정보를 눌러도 정보가 안뜨네요

**Comment by KurtBestor** [comment]
다음 실행파일로 다시 시도해서 실패하면 해당 작업 마우스 우클릭 - 정보... (I) 눌러서 나온 내용 보여주세요:  https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by cmg504** [comment]
우왕 잘됩니당 감사합니당
