### ISSUE TITLE
이게 버그인지는 잘 모르겠는데 이런 현상이 있네요.

### ISSUE THREAD

**Issue by kueisa** [KurtBestor/Hitomi-Downloader-issues#369]
![asdasd](https://user-images.githubusercontent.com/46125967/50417151-f7968000-0867-11e9-906f-849ced1fe9d7.PNG)

오늘(12월 25일)부터 발생한 증상인데요.
망가쇼미에서 기존 작품 다시 받기 말고 새 작품을 다운로드하면 완료되었다면서 저렇게 파일 0개가 뜹니다.
소프트의 문제인지 제 쪽의 문제인지 모르겠는데, 혹시 원인을 아시면 답변 부탁드립니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by hhhssj** [comment]
테스트 해보니 다운 잘되네요

**Comment by galxyvioelt** [comment]
저 같은 문제가 발생해서 문의 드립니다
테스트 어떻게 하는 건가요? 링크를 따라 들어가니 소스코드 2개와 exe가 있는데 어떻게 적용하는지 알려주세요

gal_num: https://mangashow.me/bbs/page.php?hid=manga_detail&manga_name=%ED%88%AC%EB%9F%AC%EB%B8%8C%20%ED%8A%B8%EB%9F%AC%EB%B8%94
dir: hitomi_downloaded_mangashow\투러브 트러블
zip: 
type: mangashow
artist: None
url: https://mangashow.me/bbs/page.php?hid=manga_detail&manga_name=%ED%88%AC%EB%9F%AC%EB%B8%8C%20%ED%8A%B8%EB%9F%AC%EB%B8%94
valid: True
done: True
range: None
range_p: None
single: False
time: 1546196598.12 (Dec 31)


[Gallery]
None


[File Names]



[URLs]



[Messages]
done : https://mangashow.me/bbs/page.php?hid=manga_detail&manga_name=%ED%88%AC%EB%9F%AC%EB%B8%8C%20%ED%8A%B8%EB%9F%AC%EB%B8%94

정보입니다

**Comment by galxyvioelt** [comment]
지정한 장치 파일또는 경로에 엑세스 할수 없습니다  이 항목에 엑세스할 수 있는 권한이 없는것 같습니다
라고 뜹니다. 어떻게 해결해야되는지 알려주시길 바랍니다

**Comment by KurtBestor** [comment]
@xenohoya 원본 실행파일이 지워지긴 하나요?

**Comment by galxyvioelt** [comment]
네

**Comment by xenohoya** [comment]
원본 실행파일이 지워지긴 했습니다. 
그런데 따로 글을 적어둔건 보이지 않는데 해결해주신건가요?
퇴근하고 컴퓨터 키자마자 덮어씌우니 해결됐습니다.
실행하려니까 오류 나길래
V3가 경고창 띄우길래 경고창 띄우지 않음으로 바꾸고 다시 실행하니 잘 되며, 
망가쇼미 역시 다운로드 잘 됩니다. 감사드립니다.
