### ISSUE TITLE
recaptcha 뚫기가 안됩니다

### ISSUE THREAD

**Issue by YTOAA** [KurtBestor/Hitomi-Downloader-issues#37]
원래는 설정하고 하면 크롬창이 하나 뜨면서
거기다가 비번입력했으면 됬지만...
설정하고 나서 크롬창 자체가 뜨지를 않습니다
혹시몰라 2.0버전에서 테스트한결과 2.0에서는 됩니다

**Comment by KurtBestor** [comment]
지금 확인해보니 2.0에서도 안되게 막아놨네요.
자바스크립트로 지저분하게 막아놨어요.. 왜인지는 몰라도 진짜 열심히 막네요.

https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview
고친 버전입니다. 테스트 부탁드려요.

**Comment by YTOAA** [comment]
음...역시..크롬창 자체가 뜨지를 않네요...
그리고 밑에 제가쓴건 건의사항이에요 다른문제점이 있는게 아니라요

**Comment by KurtBestor** [comment]
네 밑에 쓰신 만화로 테스트 해봤는데
![jombi](https://user-images.githubusercontent.com/14768120/35270527-c23b6c52-0072-11e8-8470-4263d7219c24.png)
404 뜨는 건 넘기게 만들어서 제대로 되는 걸 확인했습니다.

와사비시럽 주소로 다운하는 건 어떤 걸 말하는 건가요?
해당 화만 다운로드하는 건가요?

**Comment by YTOAA** [comment]
내 와사비시럽..주소로 다운로드 되는것도 있으면..좋긴하겠습니다만 일단 404뜨는건 패스가 되네요
그리고 recaptcha 뚫리네요 새로운 크롬창 뜨면서 
감사합니다
