### ISSUE TITLE
Jmana 사이트 개선후 다운이 안됩니다.

### ISSUE THREAD

**Issue by hhhssj** [KurtBestor/Hitomi-Downloader-issues#371]
다운 안된지 몇일 되긴 했는데 Jmana 사이트 개선후 다운이 안됩니다. 인터페이스도 바꿔있고 그 이후에는 다운이 안되네요. 확인 부탁드립니다. 그리고 늘 수고해주셔서 감사 드립니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by hhhssj** [comment]
다운 잘 됩니다. 감사합니다.
