### ISSUE TITLE
폴더명 변경설정이 되지 않습니다.

### ISSUE THREAD

**Issue by yojiland** [KurtBestor/Hitomi-Downloader-issues#372]
다운로드는 망가쇼미에서 했으며
버전은 v2.5b(Last updated on Dec 18,2018)버전입니다.

제가 잘 못 하고 있는걸지도 모르겠는데,
[설정]-[일반설정]에 있는 폴더명 형식을 title 로만 해 놓앗는데도
다운로드시'[작가명] 작품명 '으로 폴더가 생성됩니다.
전 작가명 없이 다운로드 하고 싶은데, 되질 않네요.

**Comment by KurtBestor** [comment]
여러가지 이유로 망가쇼미는 폴더명 변경이 되지 않아요.

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/375
