### ISSUE TITLE
망가쇼미 다운로드시 폴더에 작가이름 빼는건 어떻게하나요?

### ISSUE THREAD

**Issue by siwkd2** [KurtBestor/Hitomi-Downloader-issues#375]
안녕하세요 제작자님 만들어주신 프로그램 잘 사용하고있습니다 언제나 감사드립니다

다름이 아니라 제가 망가쇼미에서 작품을 다운로드하고 다시 정렬하는 과정에서

작가이름이 작품이름 앞에 있어 이름순으로 정렬하기가 매우힘듭니다

일일히 작가이름을 제외시켜야하는데 애로사항이 있습니다

그래서 작가이름을 작품이름뒤에 위치시키거나 아니면 작가이름을 뺄수있는 옵션을 추가해주셨으면 하는바람입니다

**Comment by KurtBestor** [comment]
이름순으로 정렬해야할 이유가 있나요?

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

다음과 같이 폴더명 형식에서 `artist`를 지우시면 돼요:
![image](https://user-images.githubusercontent.com/14768120/50544317-9a6a4800-0c34-11e9-9b96-9006a7f6e72f.png)

**Comment by pitchlatte** [comment]
잘 됩니다. 이렇게 빨리 피드백 주셔서 감사합니다.


그리고 제가 도움말을 봐도 프로그래머가 아니라 무슨 말인 잘 모르겠는데 혹시 검색 중에 망가쇼미 최신 목록 1부터 몇까지 이런 식으로 검색해서 다운도 가능한가요?

이 질문은 다 볼 수 있게 게시판에 질문을 드릴까요?

아무튼 빠른 피드백 감사드리며, 연말 자보내십시오~

Windows 10용 메일에서 보냄

보낸 사람: Kurt Bestor
보낸 날짜: 2018년 12월 30일 일요일 오후 1:14
받는 사람: KurtBestor/Hitomi-Downloader-issues
참조: pitchlatte; Comment
제목: Re: [KurtBestor/Hitomi-Downloader-issues] 망가쇼미 다운로드시 폴더에 작가이름 빼는건 어떻게하나요? (#375)

테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview
다음과 같이 폴더명 형식에서 artist를 지우시면 돼요:
