### ISSUE TITLE
쇼미 다운이 안되네요

### ISSUE THREAD

**Issue by enemyshin** [KurtBestor/Hitomi-Downloader-issues#376]
히토미다운로더 정말 잘 쓰고있습니다^^
망가쇼미가 어제 서버점검을 하면서 막은거 같은데
다시 부탁드립니다 ^^ 감사합니다

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/369
