### ISSUE TITLE
Jmana 사이트가 또 개편되어 다운이 안됩니다.

### ISSUE THREAD

**Issue by hhhssj** [KurtBestor/Hitomi-Downloader-issues#378]
안녕하세요. 늘 감사한 마음으로 사용하고 있습니다. 오늘 Jmana가 새롭게 개편되어 혹시나 또 다운 되지 않을까 싶어 불안했는데 역시 다운이 안되네요. 송구스럽게 자꾸 부탁드려 죄송합니다. 추운 날씨에 건강하시고 늘 좋은 일만 생기셨으면 좋겠습니다.

**Comment by KurtBestor** [comment]
사이트 구조 보니까 만들다 만 것 같은데.. 일단 고치긴 했어요.

테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by hhhssj** [comment]
다운 잘 됩니다. 정말 감사합니다.
