### ISSUE TITLE
히토미 다운로드 및 기본데이터가 다운로드 되지 않습니다.

### ISSUE THREAD

**Issue by muyi0162** [KurtBestor/Hitomi-Downloader-issues#379]
몇몇 작품들만 다운이 되고

대부분의 작품들이 번호를 정확히 기입해도 다운로드 되지 않습니다.

그리고 검색기에서 삭제 된 데이터 다운로드는 문제가 없으나

기본 데이터 다운로드는 매번 실패가 뜹니다.

무엇이 문제인가요?

**Comment by KurtBestor** [comment]
해당 작업 마우스 우클릭해서 `정보... (I)` 눌러서 나온 내용 보여주세요.

**Comment by muyi0162** [comment]
Traceback (most recent call last):
  File "customWidget.pyo", line 1358, in showInfo
  File "constants.pyo", line 426, in compact
UnicodeDecodeError: 'ascii' codec can't decode byte 0xb3 in position 3: ordinal not in range(128)

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by muyi0162** [comment]
파일을 덮어 씌워서 실행해도 마찬가지 입니다.  다운로드가 계속 진행되지 않습니다. 검색기에서의 기본 데이터 다운로드도 되지 않고요

**Comment by muyi0162** [comment]
![xcv](https://user-images.githubusercontent.com/46285114/50665179-06f99400-0ff3-11e9-9ae0-577637b16139.PNG)

**Comment by muyi0162** [comment]
![zxc](https://user-images.githubusercontent.com/46285114/50665197-18db3700-0ff3-11e9-8ed8-c4c49081cfea.PNG)

**Comment by KurtBestor** [comment]
해당 작업 마우스 우클릭해서 정보... (I) 눌러서 나온 내용 보여주세요.
