### ISSUE TITLE
산카쿠 컴플 질문!입니다

### ISSUE THREAD

**Issue by rabirabin** [KurtBestor/Hitomi-Downloader-issues#382]
female priest (dungeon and fighter) (?) 121 

다운로더 로 https://chan.sankakucomplex.com/?tags=female_priest_%28dungeon_and_fighter%29
이런 항목은 다운이 받아지는데요
dungeon & fighter (?) 3193

다운롤더에는 https://chan.sankakucomplex.com/?tags=dungeon_%26_fighter
invalid 뜨면서 이렇게 치면 다운이 안되네요

산카쿠는 처음이용해봐서 ...

**Comment by KurtBestor** [comment]
테스트  부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by rabirabin** [comment]
오 다운됩니다!!!>...근데 개수제한이 있나봐요? 3천여개 이미지 검색됬는데 다운로더는 딱 2천개만 되네요

**Comment by rabirabin** [comment]
그럼 나머지 1천개는 어떻게 마크해서 다운받죠?

**Comment by KurtBestor** [comment]
기본값은 2000장이 최대예요. 3000장 다운로드하려면 다음과 같이 페이지 지정해서 다운로드하면 돼요:
```
~ 3000
```

 `도움말 - 사용법 - 페이지 지정 다운로드` 참고해주세요.

**Comment by rabirabin** [comment]
감사합니다!
