### ISSUE TITLE
안녕하세요. Jmana 운영자가 인사드려요

### ISSUE THREAD

**Issue by jcomicbook** [KurtBestor/Hitomi-Downloader-issues#384]
오호홍 이렇게 우리 사이트가 목록에 들어가다니 영광입니다.

사이트 땡겨보셔서 아시겟지만 구조는 단순하죠.

나중에 구조를 바꾸게 되면 알려드릴께 반영도 해주세요~~
안그래도 요새 파이썬 배울까 생각도 하는 중인데...이 사이트도 많은 도움이 될듯 합니다.

**Comment by david761276** [comment]
우와~~ jmana잘 보고 있습니다.. 이렇게 뵈니.. 신기..ㅎㅎㅎ
