### ISSUE TITLE
안녕하세요 제작자님 건의사항 올립니다

### ISSUE THREAD

**Issue by shc67890** [KurtBestor/Hitomi-Downloader-issues#385]
![2019-01-02](https://user-images.githubusercontent.com/46307341/50579204-69815180-0e86-11e9-938d-aa07bc0956a9.png)

히토미 다운로더에 있는 '제외 태그' 기능을 유용하게 쓰고 있습니다만,
제외 태그에 있는 목록들은 따로 bmk 파일로 저장 할 수 없어서 
(좋아하는 작가태그와 달리) 업데이트 할때마다 한번에 불러올 방법이 없습니다

혹시 괜찮으시다면 제외 태그에 있는 목록들을 따로 내보내고 가져오는 기능을 추가해주셨으면 좋겠습니다
고맙습니다

**Comment by KurtBestor** [comment]
`자동 업데이트` 하시거나, 실행파일을 덮어씌우시면 돼요.

설정은 같은 폴더의 `[실행 파일명].ini`에 저장되어있어요.

**Comment by shc67890** [comment]
답변 감사합니다 잘쓸게요
