### ISSUE TITLE
새해복많이 받으세요^^..  망가쇼미 질문도 드립니다

### ISSUE THREAD

**Issue by david761276** [KurtBestor/Hitomi-Downloader-issues#386]
@안녕하세요..새해 복 많이 받으시고 
2019년 희망하시는 모든 일들이 술술 잘 풀려나가기를 
바랍니다 ^^

히토미 다운로다 프로그램 항상 잘 사용하고 있습니다.
한가지 질문 드릴것이 있어서요...
 
망가쇼미 보면 업데이트 가 있는데...
하단에 페이지들이 있습니다.

히토미 다운로더에 보면 페이지 지정 다운로드가 있던데
업데이트 페이지 주소 복사해서 집어넣고 
페이지 지정 1 로 하면 1페이지가 다운로드 되어야 하는데
안되는듯 하여... 문의 드려요...

이 기능도 히토미 다운로드에 구현이 되었으면 
많은 분들이 업데이트 한번에 받아서 볼수 있을것 같네요..ㅎㅎ
물론 저만 필요 할수도 있구요... ㅠㅠ.

바쁘신데 이렇듯 훌륭한 프로그램 만들고 
지속적으로 업데이트까지
해주셔서 감사합니다.. ^^

**Comment by KurtBestor** [comment]
페이지 지정 다운로드는 해당 작업의 이미지 중 일부만 다운로드 하는 기능이에요.

참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/351
