### ISSUE TITLE
픽시브 이미지 질문입니다.

### ISSUE THREAD

**Issue by rabirabin** [KurtBestor/Hitomi-Downloader-issues#388]
히토미 삭제된거 다운되길래 혹시나 픽시브 게시자가 삭제한 이미지도 되나 여쭤보는겁니다.
겔부루 같은 사이트에서 이미지 찾는데 없어서 asscii2d 라는 사이트로 수정된이미지(ex 모자이크된이미지)를 통해서 원본 사진 줌된거하고(그대로 다른이름저장하니 사진이 엄청작더군요) 좌표가 픽시브로 뜨는데 링크누르니까 삭제된거라고 뜨네요
 
질문
1.픽시브 게시자가 삭제한 이미지는 다운받지못하나요?

2. 수정된 이미지로 원래 찾고자한 이미지를 찾았는데 원본파일이아니고 사진사이즈 및 이름하고 썸네일같이 작게 되어있는데 이건 추출못하나요

**Comment by rabirabin** [comment]
픽시브 마이픽은 못뚫죠?

**Comment by KurtBestor** [comment]
1. 네, 다운로드하지 못 해요.
2. 네, 추출 못 해요.
3. 네, 마이픽 그림 얻으려면 해당 계정에 로그인해야하는데 현재는 지원하지 않아요.
