### ISSUE TITLE
다운로더 버그? 문의드립니다

### ISSUE THREAD

**Issue by xesgnik** [KurtBestor/Hitomi-Downloader-issues#389]
우선 새해복많이받으세요 ㅎㅎ 좋은 프로그램 잘 쓰고 있습니다.
히토미 다운로더를 파일매니지 겸해서 써보려고 이미 받은 번호들을 첫번째 커버페이지만 받으려고 해봤는데, 번호가 3개이상가니까 첫번째 두개 이후로는 파일 전체가 받아지는거 같습니다. 특정 번호랑 연관되어있는건 아닌거 같은게 3번째 후의 파일번호 가지고 한개만 테스트할 때는 정상적으로 1페이지만 받아지더라구요.

아 그리고 이건 추가적인 질문인데 혹시 .hdt 파일에 들어가는 내용이 뭔지 알 수 있을까요? 작품을 전체를 받거나 한개만 받거나 hdt 파일 크기는 똑같아서요. Total Commander도 써봤고 FindInFiles도 써봤는데 진짜 이게 너무 편리한데 이미 받은 파일들에 대해선 지원이 안되서 조금 아쉽네요 ㅠㅜ.

감사합니다!

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

HDT 파일은 JSON 형식의 텍스트 파일이에요. 메모장 같은 텍스트 에디터로 내용을 볼 수 있어요. 썸네일, 파일 이름, 저장 경로 등이 저장되어있어요. 차지하는 용량의 대부분은 썸네일이 차지해요.

**Comment by xesgnik** [comment]
잘되네요 감사합니다! 

혹시 용량을 줄이면 메모리 사용량이 줄어들까요? 제가 테스트해본결과 500개 작품 내보낸 hdt가 100mb 전후인데 이걸 3개 불러오면 그 이상은 메모리 에러로 못 불러오더라구요. 혹시 다운로드 받는 해상도가 썸네일 해상도에 영향을 미치나 싶어서 해상도를 640p로 제한해봤는데 용량이 똑같은걸 보면 그건 아닌거같고...혹시 hdt파일의 크기가 사용되는 메모리랑 직접적인 상관관계가 있는거라면 hdt 파일 생성시 저화질 썸네일을 사용하는 대신 용량이 더 작은 hdt 파일을 생성할 수 있는 옵션 만들어주실 수 있으면 감사하겠습니다

감사합니다! 새해복많이받으세요 ㅎㅎ

**Comment by KurtBestor** [comment]
HDT 파일의 크기는 사용되는 메모리의 크기와 별 상관이 없어요.

다은로더 목록에서 900개 이상은 권장하지 않아요. 참고해주세요: #170

**Comment by xesgnik** [comment]
아 알겠습니다. 감사합니다! 혹시 다운로더를 두개 띄울수는 없죠?

**Comment by KurtBestor** [comment]
같은 실행파일을 동시에 띄울 순 없지만 실행파일을 복사해서 따로 만들면 동시에 실행이 가능해요.
