### ISSUE TITLE
2.1a버전 치명적인 오류가 있습니다.

### ISSUE THREAD

**Issue by srd11333** [KurtBestor/Hitomi-Downloader-issues#39]
우선 좋은 프로그램을 개발해 주신점에 대하여 진심으로 감사의 말씀 전해드립니다.

제가 말씀드리는 문제는 다음과 같습니다.
다운로드를 하기 위해 링크는 추가하고 다운로드를 시작하면 읽는중...에서 계속 멈춰있고 다운로드가 진행되지 않습니다.  2.0버전에서의 다운로드가 지나치게 작은 용량으로 받아지는 오류만큼이나 치명적인 오류가 발생한 것 같습니다.

아무쪼록 위의 문제점에 대한 해결을 부탁드리겠습니다.

다시 한번 좋은 프로그램을 개발해 주신 KurtBestor께 감사하다는 말씀 드리겠습니다.

**Comment by KurtBestor** [comment]
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview
이걸로 테스트 부탁드려요

**Comment by KurtBestor** [comment]
v2.1b에서 해결됨
