### ISSUE TITLE
중복 다운로드 관련 문의드립니다

### ISSUE THREAD

**Issue by snopidist** [KurtBestor/Hitomi-Downloader-issues#390]
작품을 받은 후에 간혹가다 작품명 포매팅 문제 때문에 수동으로 이름을 바꾸는 경우가 있는데요. 이런 경우 같은 작품번호를 다운로드하게 되면 새로 다운로드가 되던데, 혹시 다운로드 안하게 하는 기능 건의가능할까요?

왜그러냐면 다운로드 받은 작품들을 다시 재다운로드해서 db검색기처럼 활용하고 싶은데 저런 경우 중복다운로드되는거 때문에 좀 지저분해지더라구요. 혹시 쉽게 구현가능한 기능이라면 고려해주시면 정말 감사하겠습니당

**Comment by KurtBestor** [comment]
이름을 어떤 식으로 바꾸나요? 최하위 폴더 이름만 바꾸나요 아니면 완전히 다른 경로에 옮기기도 하나요?

**Comment by snopidist** [comment]
최하위 폴더 이름만 바꿉니다. [Author] Name (12345678) 이런식이면 [Author] NewName (12345678), 뒤에 있는 작품번호는 안바꾸고요.

이게 막 챕터가 여러개있는 작품일 경우에 어떤거는 Ch.1되어있고 어떤거는 그냥 2 이렇게 되어있으면 순서대로 안맞을때가 있어서 바꿉니다 ㅜㅜ
