### ISSUE TITLE
페이지 검색 질문

### ISSUE THREAD

**Issue by whrqkfqkf** [KurtBestor/Hitomi-Downloader-issues#391]
"p<100" 을 입력하면 100 페이지 미만인 갤러리만 보입니다.
 "p>100" 을 입력하면 100 페이지 초과인 갤러리만 보입니다.
 사용법에 이렇게 써져 있던데 태그창에 그대로 검색해 봤는데 안되네요? 혹시 제가 뭘 잘못한 건가요?

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/178

**Comment by whrqkfqkf** [comment]
오! 감사합니다! 그리고 몰랐는데 100 뿐만 아니라 다른 수치도 되네요.
이런 기능까지 넣어준 세심함에 놀라울 따름이네요 ㅎㅎ
