### ISSUE TITLE
트위터 다운받을떄 트윗의 이미지를 다운받으면 안될까요?

### ISSUE THREAD

**Issue by jaejunghan** [KurtBestor/Hitomi-Downloader-issues#392]
예로들면 https://twitter.com/moehime_union이주소를 입력하면

https://twitter.com/moehime_union/media의 주소의 이미지만 다운받는거 같습니다

 https://twitter.com/moehime_union은 해당트위터 계정의 트윗인데 트윗과 리트윗까지 다운받도록 설정 안되나요?

**Comment by KurtBestor** [comment]
네, `/media` 에 더 많은 내용이 있는 경우가 있기 때문에 `/media` 에서만 읽고있어요.

참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/333
