### ISSUE TITLE
이 사이트도 지원 사이트 목록에 추가해주시면 안될까요?

### ISSUE THREAD

**Issue by mujumpou359** [KurtBestor/Hitomi-Downloader-issues#393]
https://newtoki.com/
뉴토끼라는 사이트인데
망가쇼미랑 비슷합니다.
이 사이트도 지원 사이트에 추가해주시면 안될까요?

**Comment by KurtBestor** [comment]
스크립트 고쳤어요.

참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/330
