### ISSUE TITLE
anthology 태그 질문입니다

### ISSUE THREAD

**Issue by whrqkfqkf** [KurtBestor/Hitomi-Downloader-issues#394]
저번 질문에 대한 답변 매우 감사합니다.
그런데 태그 검색을 할때 자신이 원하지 않는 태그는 -를 붙여서 검색하잖아요.
그런데 유독 anthology 태그는 -를 붙여도 그대로 나오네요. 
혹시 버그인 건가요? 확인 부탁드립니다.

**Comment by KurtBestor** [comment]
테스트 해보니 저는 잘 되네요. 혹시 검색어를 어떻게 입력했는지 스크린샷 찍어서 보여주실 수 있나요?

**Comment by whrqkfqkf** [comment]
![default](https://user-images.githubusercontent.com/46374303/50769086-23811f00-12c6-11e9-8859-5fceb5d5ac05.PNG)

**Comment by whrqkfqkf** [comment]
보시다시피 -anthology를 입력했는데도 anthology가 달린 갤러리가 떠요.

**Comment by KurtBestor** [comment]
뒤에 `+female:harem`이 붙어서 `female:harem`이 들어간 작품들도 합쳐져서 나와요.
`ffm threesome+female:harem` 을 `(ffm threesome+female:harem)` 이렇게 묶어주시면 원하는대로 검색이 될거예요.
`+ (or)` 보다 `, (and)` 의 우선순위가 높아서 생기는 현상이에요.
