### ISSUE TITLE
검색에 대한 질문있습니다.

### ISSUE THREAD

**Issue by wpfhfpr** [KurtBestor/Hitomi-Downloader-issues#396]
안녕하세요 항상 잘쓰고 있습니다.
고급검색 시에 작가나 그룹을 검색하면 ()로 검색되는 개수가 뜨지않습니까?
예로 (21)개면 21개의 작품이 나오는 데 
Daijobi Kenkyuujo 이 그룹이 21개가 떠야하는 데 3개만 뜹니다. 삭제된 데이터에서도 안뜨고요.
이러한 경우는 검색의 에러인건가요?

**Comment by KurtBestor** [comment]
히토미 서버에 기록된 갯수를 기준으로 해요.
대부분 갯수가 미묘하게 차이나는데, 정확한 원인은 모르겠네요.
참고로 현재 삭제된 데이터에서 그룹 검색은 안돼요.
