### ISSUE TITLE
망가쇼미에서 만화를 다운로드하면 계속 fail 했다고 뜨네요..

### ISSUE THREAD

**Issue by Enonono** [KurtBestor/Hitomi-Downloader-issues#397]
제곧내입니다.
fail 이라는 메시지가 뜨면서 이미지가 하나도 받아지지 않네요.. 뭐가 문제일까요?

**Comment by KurtBestor** [comment]
@ch3rrybls 
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by ch3rrybls** [comment]
앗 이제 잘 작동하네요!! 정말 감사합니다:D
