### ISSUE TITLE
안녕하세요 사이트 추가 건의하려 글올립니다

### ISSUE THREAD

**Issue by completelee** [KurtBestor/Hitomi-Downloader-issues#398]
pornhub 사이트는 등록이 되어있는데
pornhubpremium 사이트 (유료) 는 등록이 안되있더라구요
4k 영상 다운 목적으로 프리미엄 사이트도 등록해주시면 안될까요?
주소는 pornhub 뒤에 premium 만 붙이면 나머지는 똑같습니다.
항상 잘쓰고 있습니다. 감사합니다.

**Comment by KurtBestor** [comment]
수정했어요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

다만 premium만 볼 수 있는 영상은 다운로드 안 돼요.

**Comment by completelee** [comment]
> 수정했어요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview
> 
> 다만 premium만 볼 수 있는 영상은 다운로드 안 돼요.

감사합니다 정말 잘쓸게요

**Comment by completelee** [comment]
> 수정했어요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview
> 
> 다만 premium만 볼 수 있는 영상은 다운로드 안 돼요.

그런데 4K랑 FHD 화질로는 다운이 안되고 720P 로만 다운이 가능하네요 전이랑 똑같이..
화질은 어쩔수 없는 건가요?

**Comment by KurtBestor** [comment]
네, premium만 볼 수 있는 4K 동영상은 받아지지 않아요.

**Comment by completelee** [comment]
네 감사합니다!
