### ISSUE TITLE
혹시, 뉴토끼에서 다운받은 파일을 PDF로 엮는 스크립트 추가하실 계획 있으세요?

### ISSUE THREAD

**Issue by karnies** [KurtBestor/Hitomi-Downloader-issues#399]
안녕하세요,

정말 감사하게 잘 쓰고 있습니다.

혹시, 뉴토끼에서 다운받은 파일을 PDF로 엮는 스크립트 추가하실 계획 있으세요?

이게 웹툰은 캡쳐한거라 일반 만화처럼 한장한장이 나오지 않네요.

PDF로 엮어서 아래로 쭈욱 스크롤 하는 방식으로 볼 수 있으면 좋을 것 같은데 혹시 스크립트 변경 계획 있으세요?

**Comment by KurtBestor** [comment]
모든 화를 한꺼번에 PDF로 만드는 게 좋나요, 아니면 화별로 만드는 게 좋나요?

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

다음과 같이 설정하시면 돼요:
![190127-1318_nafmosvvhu](https://user-images.githubusercontent.com/14768120/51796476-07263180-2237-11e9-81d6-c5cf3257a119.png)
