### ISSUE TITLE
다운이 안되네요

### ISSUE THREAD

**Issue by rcyca** [KurtBestor/Hitomi-Downloader-issues#4]
http://marumaru.in/b/manga/253851
다운이 안되네여 다른마루마루만화들은 되는데

**Comment by KurtBestor** [comment]
![maru](https://user-images.githubusercontent.com/14768120/33885676-633bbb14-df87-11e7-8e2a-ab909f888ad6.png)

캡차를 걸어 놓았네요.
캡차를 뚫는 건 ANN이 필요해서 이런 10메가 남짓의 프로그램으로는 못합니다.
그래서 캡차 부분만 수동으로 한다던지 생각하고 있습니다.

이 부분은 좀 시간이 걸릴 것 같습니다.

**Comment by KurtBestor** [comment]
v2.0에서 해결됨
