### ISSUE TITLE
히토미에서 대량 다운을 막은거같아요

### ISSUE THREAD

**Issue by kusari555** [KurtBestor/Hitomi-Downloader-issues#40]
웹페이지서 하나씩 다운받는건 되는거같은데
태그검색으로 한꺼번에 다운받으면 멈추거나 저용량으로 깨진파일들이 받아지네요
최신버전뿐 아니라 1.9버전이하 버전들도 동일합니다

**Comment by KurtBestor** [comment]
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview
이걸로 테스트 부탁드려요

**Comment by kusari555** [comment]
테스트해보고있는데 이전에 10개중에 4개이상은 오류였는데 지금 아직까는지 무리없이 잘되고있네요
감사합니다

**Comment by KurtBestor** [comment]
v2.1b에서 해결됨
