### ISSUE TITLE
히토미 검색에서 이미 받은 자료 일괄 목록 삭제 기능 추가 부탁드려요

### ISSUE THREAD

**Issue by ONDR** [KurtBestor/Hitomi-Downloader-issues#400]
너무 좋은 프로그램 잘 쓰고 있습니다.^^ 감사합니다.
글자체는 삭제가 안돼네요
중복 항목은 중복 다운 안되고 넘어가는군요..  잘 쓰겠습니다 굳굳

**Comment by KurtBestor** [comment]
검색기 필터에 `done:x` 입력하면 다운로드하지 않은 작품만 보여요.

`도움말 - 사용법 - 검색기 목록 필터링` 참고해주세요.
