### ISSUE TITLE
망가쇼미 만화 전체 다운로드가 되는게 있고 안되는게 있네요

### ISSUE THREAD

**Issue by Reusy** [KurtBestor/Hitomi-Downloader-issues#401]
제작자님 정말 좋은 프로그램을 만들어 주셔서 편하게 사용하고 있네요
정말 죄송하지만 망가쇼미에서  한 화당 다운로드는 잘 되는데 이상하게 전 화를 다운받을려고 하면 되는게 있고 안되는게 있네요 이 문제점 고쳐 주시면 정말 감사하겠습니다!

**Comment by KurtBestor** [comment]
해당 작업 `[마우스 우클릭] - [정보... (I)]` 눌러서 나온 내용 보여주세요.

**Comment by Reusy** [comment]
Invalid : [mangashow] https://mangashow.me / bbs / page.php?hid=manga_detail&manga_name=매지컬

version: 2.5c
gal_num: https://mangashow.me/bbs/page.php?hid=manga_detail&manga_name=매지컬
dir: 
zip: 
type: mangashow
artist: None
url: https://mangashow.me/bbs/page.php?hid=manga_detail&manga_name=매지컬
valid: False
done: False
range: None
range_p: None
single: False
time: 1547218331.67 (Jan 11)
tags: []


[Gallery]
None


[File Names]



[URLs]



[Messages]
stop
Traceback (most recent call last):
File "utils", line 437, in start
File "utils", line 481, in start_
File "mangashow_downloader", line 94, in read
File "mangashow_downloader", line 80, in name
Exception: No title

Fail: mangashow

done : https://mangashow.me/bbs/page.php?hid=manga_detail&manga_name=매지컬

**Comment by Reusy** [comment]
이것 말고도 안되는게 많이 있어요

**Comment by Reusy** [comment]
익스플로로 했는데 크롬으로 하니까 다운 받아지네요 왜 그런건진 모르겠지만 익스플로로 해도 됬으면 좋겠네요 크롬에서는 사이트를 재대로 이용하지 못해서요
