### ISSUE TITLE
기능 추가 건의드립니다.

### ISSUE THREAD

**Issue by whrqkfqkf** [KurtBestor/Hitomi-Downloader-issues#403]
안녕하세요, 제작자님. 매일 아주 잘 쓰고 있습니다.
혹시 페이지 검색 기능에서 단순히 p<a, p>a가 아니라 아예 그 페이지의 수 자체를 지정해서
검색하는 기능이 있으면 어떨까 하고 건의드립니다. 예를 들어 'p=30'이라고 필터창에 검색하면
30페이지인 갤러리만 뜨는 것처럼요. 혹시 트래픽 등의 문제 때문이라면 a<p<b 같은 복합 형태도
괜찮을 것 같다고 생각하는데 어떻게 생각하시나요?

**Comment by KurtBestor** [comment]
`p>29 p<31` 와 같이 입력하면 30 페이지인 것만 보여요. 필터는 여러 개 동시에 적용 가능해요.
