### ISSUE TITLE
유튜브 1080p로 받으면 소리가 나오지 않습니다.

### ISSUE THREAD

**Issue by maplepoison** [KurtBestor/Hitomi-Downloader-issues#405]
예전에 해상도 선택 옵션이 없을 때 올라온 글과 코멘트도 봤는데, 기술적 문제가 아직 해결 안 된 건가요?
고생 많으십니다. 아무튼 잘 해결해 주시면 감사하겠습니다.

**Comment by KurtBestor** [comment]
소리는 다운 받는 도중에는 들리지 않아요. 완전히 다운로드 / 변환 완료 된 후에 들려요.

완전히 다운로드 / 변환 완료 된 후에도 들리지 않으면 해당 작업 `[마우스 우클릭] - [정보... (I)]` 눌러서 나온 내용 보여주세요.
