### ISSUE TITLE
한글 폰트 깨짐 문제

### ISSUE THREAD

**Issue by ValhallaAwaits** [KurtBestor/Hitomi-Downloader-issues#406]
![default](https://user-images.githubusercontent.com/46617924/51069631-4882e280-1676-11e9-8196-2779fc173f2a.png)
![2](https://user-images.githubusercontent.com/46617924/51069635-681a0b00-1676-11e9-8cd8-b314bc795ba5.png)

 이처럼 한글이 안나와요. 영어는 잘 나오구요.
#147 글 보고 타이핑해도 none 뜨면서 반응이 없네요. 테스트 모델 써봐도 똑같네요..
혹시 해결 가능할까요?

**Comment by KurtBestor** [comment]
`Ctrl + Alt + C` 눌러서 콘솔 열고 다음과 같이 입력한 다음 나오는 내용 알려주세요:
```
QtGui.QFont().family()
```

**Comment by ValhallaAwaits** [comment]
PyQt4.QtCore.QString(u'MS Shell Dlg 2')
뜹니다.

**Comment by KurtBestor** [comment]
콘솔에 다음과 같이 입력해서 나오는 내용 알려주세요:
```
for font in QtGui.QFontDatabase().families(QtGui.QFontDatabase.Korean): print unicode(font.toUtf8(), 'utf8')
```

**Comment by ValhallaAwaits** [comment]
![3](https://user-images.githubusercontent.com/46617924/51081420-7cbbd900-1732-11e9-9d60-3c879e814b1d.png)
복사하면 콘솔 창 복붙하면
HyhwpEQ
경기천년바탕 Bold
경기천년바탕 Regular
경기천년제목 Bold
경기천년제목 Light
경기천년제목 Medium
경기천년제목V Bold
굴림
굴림체
궁서
궁서체
돋움
돋움체
맑은 고딕
맑은 고딕 Semilight
문체부 훈민정음체
바탕
바탕체
전주 완판본 각B
전주 완판본 각L
전주 완판본 각R
전주 완판본 순B
전주 완판본 순L
전주 완판본 순R
함초롬돋움
함초롬바탕

이렇게 뜨네요

**Comment by ValhallaAwaits** [comment]
![default](https://user-images.githubusercontent.com/46617924/51082438-32465680-174a-11e9-9643-f7f4a1330ed7.png)
잘 돼요. 피드백 감사합니다.
