### ISSUE TITLE
익헨,이헨 다운로드시 일부만 다운로드 됩니다

### ISSUE THREAD

**Issue by techromancer789** [KurtBestor/Hitomi-Downloader-issues#407]
https://exhentai.org/g/553668/61929ae2bf/
위 링크같은 경우 200개의 이미지가 있지만 다운로더로 다운로드 받을시 63개의 이미지만 다운로드 됩니다
이헨 링크로 다운로드시에도 동일합니다
테스트 버전 다운로더도 똑같은 증상입니다

**Comment by KurtBestor** [comment]
파일 이름이 중복되네요.

다음과 같이 해주시면 될거예요:
![image](https://user-images.githubusercontent.com/14768120/51076499-7c90ee80-16dc-11e9-8a6f-bda876dc2105.png)

참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/80
