### ISSUE TITLE
크기조절 및 압축 방식 변경 건의

### ISSUE THREAD

**Issue by winty56** [KurtBestor/Hitomi-Downloader-issues#409]
안녕하세요. 두가지 개선사항 건의드립니다.
1. 크기조절 방식 변경
 '비율 유지'로 크기 조절시 변경할 최대 크기로 가로x세로 값을 받고 있는데요. 
        
    지금은 원본이미지 가로와 세로 중 큰 값을 최대 크기의 가로 가로값만을 사용하여 리사이징 하는것처럼 보입니다.  

    >  ex) 변경할 최대 크기 4500 x 1920 설정시  
원본 이미지가 9000 x 3000일경우 -> 4500 x 1500  
원본 이미지가 3000 x 9000일경우 -> 1500 x 4500  
원본 이미지가 1280 x 3500일경우 -> pass  
원본 이미지가 3500 x 1280일경우 -> pass  

    이 방식을 변경해서 원본 이미지의 가로나 세로 값 중 큰 값을 기준으로 리사이즈가 되었으면 좋겠습니다.  제가 생각한 방법의 슈도코드는 아래와 같습니다.

```
double widthResizeRatio = maxWidth / (double)img.Width;
double heightResizeRatio = maxHeight / (double)img.Height;

double resizeRatio = Math.Min(Math.Min(widthResizeRatio, heightResizeRatio), 1.0);
img.Resize(Size.Zero, resizeRatio, resizeRatio, InterpolationFlags.Area);
```

2. 이미지 포맷 변경 기능 추가
용량상의 문제 원본 이미지가 png등의 파일일 경우 jpg로 변경해서 저장하는 기능이 있으면 좋겠습니다.

**Comment by KurtBestor** [comment]
코드에 오류가 있었네요.
`최대 폭 x 최대 폭` 으로만 리사이즈하고있었어요.
`원본 이미지가 3000 x 9000일경우 -> 640 x 1920` 으로 되게 고쳤어요.

테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by winty56** [comment]
```
[P000.jpg] 2470x3000 --> 1581x1920
[P000A.jpg] 6876x3000 --> 4401x1920
[P000B.jpg] 6876x696 --> 4500x455
[P000C.jpg] 4539x3000 --> 2905x1920
[P001.jpg] 2046x3000 --> 1310x1920
[P002.jpg] 2040x3000 --> 1306x1920
```

이상없이 잘 되는것 같습니다. 감사합니다.

**Comment by winty56** [comment]
PNG -> JPG도 부탁드려요

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by winty56** [comment]
잘 됩니다! 감사합니다!
