### ISSUE TITLE
불완전한 작업을 자동으로 다시 시작하는 옵션을 넣어주실 수 있나요?

### ISSUE THREAD

**Issue by Dremelist** [KurtBestor/Hitomi-Downloader-issues#41]
나와있는 다운로더들 중에 이게 제일 좋습니다. 정말 잘 쓰고 있어요.
며칠 전까지 히토미 서브도메인이 바뀌었을 때도 빠른 대응에 감동했습니다.

그런데 제가 사는 곳 인터넷 선이 너무 불안정해서 굉장히 자주 "불완전한 작업을 자동으로 다시 시작" 버튼을 눌러줘야 해요. 잠깐만 눈을 떼면 목록이 주황색으로 가득 차버리거든요. 문제는, 이 상태가 되면 제가 다시 시작을 누르기 전까지 아무 작업도 하지 않고 가만히 있게 된다는 거지요.

하지만 똑같은 문제를 더 자주 일으키는 Hdoujin Downloader라는 유료 프로그램을 사용하면서 불편한 점이 정말 많았는데 성능도 더 나은 데다 리소스도 덜 차지하는 이걸 쓰니 여러 모로 편해졌습니다.

무료로 배포해주시는 것 만으로도 정말 감사해서 염치가 없다고 느껴질 정도입니다.
건승하세요.

**Comment by KurtBestor** [comment]
감사합니다!
최근 바이러스 탐지가 되는데 바이러스 집어넣은 것 아니냐, 업데이트 너무 자주 한다, 쓸데 없는 기능 넣어서 지저분하다, 서브 도메인 바뀐 것 패치가 왜 이렇게 늦냐 등 모진 소리를 많이 들어서, 선의로 수익 없이 만들고있는데, 내가 정말 잘못한건가? 하는 생각이 들기도 했었어요.
그런데 이렇게 말씀해주시니 정말 감사해요.
다음 업데이트에 해당 기능 추가하도록 하겠습니다.
불완전하게 작업이 완료되면 5분 후에 자동으로 다시 시작하는 기능으로 하려고 하는데, 더 좋은 방법 있으면 말씀해주세요.

**Comment by Dremelist** [comment]
주황색 갤러리들이 5분 후에 다시 시작 된다면 완벽할 것 같습니다!
다음 업데이트 기대할게요. 감사합니다.

P.S. 바이러스 오진 관련해서, 이런 종류 프로그램들에 바이러스나 채굴 코드를 심어두는 경우가 워낙 흔해서 사람들이 의심이 심한 것 아닐까 해요. 에시당초 법하고는 거리가 먼 프로그램들이기도 하고요. 사실 저도 파일 받자마자 카스퍼스키로 한 번 돌려봤습니다.(문제는 없었지만)

원래 사람이 게을러서 만족스러우면 아무 생각이 안 듭니다. 무언가 마음에 안 들어야 움직이죠. 만족하고 계신 사용자들도 많을겁니다.

**Comment by KurtBestor** [comment]
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

해당 기능 만들어 봤습니다. 설정 - 고급 설정 - 불완전한 작업 자동으로 다시 시작에서 설정하실 수 있습니다.
테스트 부탁드려요.

**Comment by Dremelist** [comment]
링크 다운로드가 안되는데 구글드라이브로 올려주실 수 있을까요?

**Comment by KurtBestor** [comment]
https://drive.google.com/open?id=1G4b7Kjgv-rYivWu4geUKw8CIQtGK8Tlt

**Comment by Dremelist** [comment]
너무 좋습니다. 자리를 오래 비웠다 왔는데 전부 받아져 있네요! 감사합니다!
