### ISSUE TITLE
히토미 폴더명 형식 건의

### ISSUE THREAD

**Issue by ddt5244** [KurtBestor/Hitomi-Downloader-issues#410]
폴더명 형식에 작품의 캐릭터 기능은 없는거 같더군요

만들어주실수 있나요? ㅠㅠ

(artist) title (characters) (series)

이렇게 하고싶습니다.

아 그리고 작품에 작가가 2명 이상일때 맨 앞 1명만 제대로 써지고 나머지는 etc처리되던데 

다 써지게 하는 방법은 없나요?

**Comment by ddt5244** [comment]
> 폴더명 형식에 작품의 캐릭터 기능은 없는거 같더군요
> 
> 만들어주실수 있나요? ㅠㅠ
> 
> (artist) title (characters) (series)
> 
> 이렇게 하고싶습니다.

아 그리고 작품에 작가가 2명이상일 경우 맨앞 작가만 써지고 나머지는 etc처리되던데 전부 보이게 하는

방법은 없나요?

**Comment by KurtBestor** [comment]
캐릭터 기능은 현재 없어요.
만약 넣게된다면 폴더명 길이 때문에 artist와 같이 3 명 이상이면 etc로 처리될텐데 이걸 원하시는 게 아닌 것 같아요.
그래서 딱히 넣을 이유가 없어서 안 넣으려고해요.

**Comment by ddt5244** [comment]
아 네 알겠습니닷 감사합니다
