### ISSUE TITLE
사이트 추가 건의 (소설가가 되자)

### ISSUE THREAD

**Issue by wianmp3** [KurtBestor/Hitomi-Downloader-issues#411]
일본 웹소설 연재 사이트입니다. 메인주소: https://yomou.syosetu.com/

이전 http://w033.seesaa.net/  에 NovelDL 란 다운로더가 있엇지만 현제 사용불가입니다.(소스공유중)

혹시 추가 가능한지 여쭤봅니다. 그리고 프로그램 잘쓰고 있습니다. 감사합니다.

필요기능
소설을 TxT 로 저장 (화당.TxT or 전화 1개로TxT저장)

일반       형식: 주소/작품번호/페이지
https://ncode.syosetu.com/n7105co/1/

성인      형식: 주소/작품번호/페이지
https://novel18.syosetu.com/n6426w/1/

**Comment by KurtBestor** [comment]
테스트 부탁드려요:  https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by wianmp3** [comment]
감사합니다 아주잘됩니다.

웹소설인 관계로 1개파일로 통합되면 좋겟지만 5작품정도 저장해본결과

작품 모두 화당 파일로 제대로 작동하는걸 확인햇습니다. 감사합니다.

**Comment by wianmp3** [comment]
저장된 텍스트 파일을 형식을

파일이름(화 제목)

+ 내용

이 되면 완벽하다고 생각합니다만 가능한지 궁금합니다. 매번 감사드립니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by wianmp3** [comment]
감사합니다 더할나위없는 결과물인것 같습니다. !
