### ISSUE TITLE
망가쇼미 폴더 문의

### ISSUE THREAD

**Issue by cocoman1111** [KurtBestor/Hitomi-Downloader-issues#413]
안녕하세요. 
망가쇼미 다운로드 받을 때 없는 제목이면 폴더가 생성 될 때,
[코노기 요시루, N／A ], [월간]  이런식으로 붙어서 생성되는데 이걸 변경할 수 있는 방법이 있나요?
히토미에서 다운받을땐 설정이 되는거 같은데 망가쇼미는 없는 건가요?

**Comment by KurtBestor** [comment]
해당 작업 `[마우스 우클릭] - [정보... (I)]` 눌러서 나온 내용 보여주세요.

**Comment by KurtBestor** [comment]
`[옵션] - [설정] - [폴더명 형식]` 이 어떻게 되어있나요?

**Comment by cocoman1111** [comment]
감사합니다. 몇 일전일이지만 이렇게 햇을때 변경되지 않아서 여쭈어본건데, 업뎃되면서 고쳐진거였군요... 답변 감사합니다
