### ISSUE TITLE
모바일 버전에 대해 건의합니다.

### ISSUE THREAD

**Issue by whrqkfqkf** [KurtBestor/Hitomi-Downloader-issues#416]
안녕하세요. 덕분에 언제나 감사히 잘 쓰고 있습니다.
이제 슬슬 스마트폰이나 태블릿 같은 환경에서도 쓸 수 있게 모바일 버전이 나올 때라고 생각하는데
모바일 버전은 만들 의향이 있으신가요?  혹시 기술 상의 문제로 불가능 한 건가요?

**Comment by KurtBestor** [comment]
아직 계획은 없어요.

아마 만든다면 첨부터 다시 만들어야할거예요. Android / iOS 도 따로 만들어야하고요.
