### ISSUE TITLE
망가쇼미 다운로드 진행이 안됩니다

### ISSUE THREAD

**Issue by mujumpou359** [KurtBestor/Hitomi-Downloader-issues#417]
![default](https://user-images.githubusercontent.com/46411690/51187888-257b5b80-1920-11e9-8ca9-107d2389f884.PNG)
이 사진처럼
다운로드를 인식은 하는데, 이미지 다운은 진행이 안되는 것 같습니다?
혹시 개인의 문제인지, 아니면 사이트가 뭘 변경해서 다운이 안되는 건지 확인좀 부탁드리겠습니다
항상 프로그램을 유지시키기 위해 힘써주셔서 정말 감사합니다.

**Comment by mujumpou359** [comment]
좀더 확인해보니
목록 주소를 넣고 다운하려 할때 안되는 것 같습니다.
개별적으로 들어가서 다운하니 진행되네요

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by siwkd2** [comment]
저도 동일한 증상이 보이네요 아마 1월 15일

> 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

감사합니다 구동결과 정상작동됩니다 오류해결해주셔서 감사합니다
