### ISSUE TITLE
한 가지 기능 건의+질문

### ISSUE THREAD

**Issue by KFromage** [KurtBestor/Hitomi-Downloader-issues#419]
몇달 전부터 잘 쓰고있습니다. 만들어주셔서 정말 감사드려요

혹시 히토미 내 작가의 (언어별) 전체 작품을 다운로드 하는 스크립트를 추가하시는건 어떤가요?
그리고 작가 추천 깊은 신경망은 언제쯤 개발하실지 궁금해요!
(자료 876개로 제가 선호하는 작가가 다수 나와서 놀랐습니다)

**Comment by KurtBestor** [comment]
1. 검색기를 쓰세요.

2. 깊은 신경망은 현재 계획된 건 없어요.
