### ISSUE TITLE
건의사항

### ISSUE THREAD

**Issue by Ooooool** [KurtBestor/Hitomi-Downloader-issues#42]
안녕하세요. 작년까지 다른 다운로더 쓰고 있었는데 우연히 KurtBestor님 다운로더 썼다가 반해서 계속 애용중입니다 ㅎㅎ 항상 빠른 업데이트 감사해요.

다른 게 아니라 작품 검색할 때 30~40개씩 끊어서 찾고 싶은데 검색범위로는 그게 잘 안 되더라구요.
검색 중에는 버벅이는 점도 있어서 끝날 때까지 기다리려니 좀 오래 걸리기도 하고...

그래서 끊어서 검색하는 기능이 있었으면 하는데 추가해주실 수 있나요?

**Comment by KurtBestor** [comment]
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

검색 속도가 느리고 버벅이는 건 일종의 버그였는데요, 고친 버전입니다. 이제 속도가 빨라져서 끊어서 검색하는 기능은 필요 없다고 생각해서 해당 기능은 넣지 않을 예정입니다.
