### ISSUE TITLE
오류인지 버그인지 해결법 알려주세요

### ISSUE THREAD

**Issue by fdaga** [KurtBestor/Hitomi-Downloader-issues#420]
![3](https://user-images.githubusercontent.com/46779614/51312210-1aded480-1a8e-11e9-812b-e353aadcbc29.PNG)

저장을 하면 꽉차있던 파란줄이 점점 줄어들면서 저장이 되고 다시 키면 이미지가 없어져 있고 다운로드 하듯이 됩니다 여러번 계속그러네요 해결법좀 알려주세요

**Comment by KurtBestor** [comment]
다운로더 목록에서 900개 이상은 권장하지 않아요. 참고해주세요: #170
