### ISSUE TITLE
망가쇼미 다운할 때, 폴더명에 NEW 가 붙네요.

### ISSUE THREAD

**Issue by karnies** [KurtBestor/Hitomi-Downloader-issues#421]
안녕하세요, 항상 잘 쓰고 있습니다. 감사합니다.

다름이 아니라 망가쇼미에서 새로 업데이트 된 만화 다운 받을 때, 폴더 병에 NEW 가 붙는데,
이거 안붙게 변경해 주실 수 있나요?

![image](https://user-images.githubusercontent.com/46523031/51359754-689a2200-1b0c-11e9-8693-b2495cd7d482.png)

감사합니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by karnies** [comment]
정상 동작 합니다.
감사합니다.
