### ISSUE TITLE
사이트별로 다운로드 폴더를 별도로 지정할 순 없을까요

### ISSUE THREAD

**Issue by cyworm** [KurtBestor/Hitomi-Downloader-issues#423]
매번 바꿔줘야 해서 번거롭네요

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

![190118-2330_miqbbipswq](https://user-images.githubusercontent.com/14768120/51392763-60c49700-1b79-11e9-8b4e-626f49a30345.png)
