### ISSUE TITLE
히토미 다운로더 검색기에서 특정 아티스트들을 검색할 수 있게 해주실 수 있나요?

### ISSUE THREAD

**Issue by chbk256** [KurtBestor/Hitomi-Downloader-issues#426]
이름이 특이하거나 긴 아티스트들의 경우 비슷한 작가들이 없으니 같이 검색이 안 되지만

 예를 들어 Naz 같은 아티스트가 있다면  minazuki juuzou나 nikusoukyuu 같이

전혀 상관없는데도 해당 문자가 포함되는 아티스트가 뜨는 경우가 많습니다.

히토미 사이트 자체에는 artist:naz 식으로 딱 특정해서 검색할 수 있는데, 도입이 가능하신지 궁금합니다.

**Comment by KurtBestor** [comment]
검색기 옵션에서 고급 검색을 키세요.

참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/261

**Comment by chbk256** [comment]
이때까지 괜한 고생을 했군요 ㅠㅠㅠ

감사합니다.

생각보다 훨씬 많은 기능을 탑재하고 있네요 .

**Comment by KurtBestor** [comment]
다음과 같이 태그에 입력해주세요:

![image](https://user-images.githubusercontent.com/14768120/51438405-25e46f80-1cef-11e9-8901-80cf355f6a0b.png)

**Comment by chbk256** [comment]
음? 분명 이렇게 입력했었는데 전 저런 창이 안 나왔었거든요.

가만 보니 앞에 다른 키워드를 적고 뒤에 다른 키워드를 같이 조합하려고 하면 조합이 안 되는 것 같네요.

고급 키워드 키워드 조합에 대해서 건의를 드렸어야 했는데

괜히 귀찮게 해드린 거 아닌가 죄송해지는군요.




아무튼 직접 스샷까지 찍어서 답변주신 거 감사합니다.

**Comment by KurtBestor** [comment]
`도움말 - 사용법 - 고급 검색` 을 보세요.
