### ISSUE TITLE
뉴토끼 홈페이지 리뉴얼 됐나봐요

### ISSUE THREAD

**Issue by NANARANG** [KurtBestor/Hitomi-Downloader-issues#427]
웹툰은 다운로드 문제없이 잘 되는데

단행본이 따로 분류됐는지 다운이 안되용 

스크립트 최신껄로 부탁드립니다~!!

**Comment by KurtBestor** [comment]
수정했어요: https://drive.google.com/drive/folders/1FP0YZp7QyGDyOQ1nwILRIVT3kd58NYxo

**Comment by NANARANG** [comment]
아주아주 잘돼요!!
바쁘신데 불구하고 빠르게 수정해주셔서 대단히 감사합니다! 충성충성

**Comment by ldh7680** [comment]
웹툰은 다운이 되는데 단행본쪽은 다운이 안되는것 같아요~
