### ISSUE TITLE
유튜브 mp3 다운이 안됩니다

### ISSUE THREAD

**Issue by zksl** [KurtBestor/Hitomi-Downloader-issues#428]
mp4 720p,1080p 다운은 잘되는대 
mp3로 변환해서 다운은 안되네요~

Invalid : [youtube] https://www.youtube.com / watch?v=gszuEGmVWlQ

version: 2.5c
gal_num: https://www.youtube.com/watch?v=gszuEGmVWlQ
dir: 
zip: 
type: youtube
artist: None
url: https://www.youtube.com/watch?v=gszuEGmVWlQ
valid: False
done: False
range: None
range_p: None
single: True
time: 1547988830.42 (Jan 20)
tags: []

[Gallery]
None

[File Names]

[URLs]

[Messages]
stop
Traceback (most recent call last):
File "utils", line 453, in start
File "utils", line 497, in start_
File "youtube_downloader", line 82, in read
AttributeError: Stream instance has no attribute 'resolution'

Fail: youtube

done : https://www.youtube.com/watch?v=gszuEGmVWlQ

이런식으로 나옵니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview
