### ISSUE TITLE
pixiv 다운로드가 안됩니다.

### ISSUE THREAD

**Issue by ryongdol** [KurtBestor/Hitomi-Downloader-issues#43]
pixiv 주소 입력 시 

invalid 라고 뜨면서 다운로드 시작을 하지 않습니다.

**Comment by KurtBestor** [comment]
지금 테스트 해봤는데 제 쪽에선 그런 문제가 발생하지 않네요.

해당 작업 우클릭 후 [정보... (I)]를 눌러서 나오는 내용 보여주시면 분석해보겠습니다.

**Comment by KurtBestor** [comment]
지금 보니 https://www.pixiv.net/member.php?id=xxxxxx 형식의 주소를 입력하니 그렇게 되네요.

https://www.pixiv.net/member_illust.php?id=xxxxxx로 입력하면 다운로드 될거예요.

코드 다듬다가 이걸 빼먹었네요..

해당 버그 수정된 버전입니다:
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by ryongdol** [comment]
수정된 버전으로 테스트 해보니 괜찮습니다.
프로그램 잘 쓰고 있습니다.
감사합니다.
