### ISSUE TITLE
다운로드 폴더명 지정오류로 문의드립니다

### ISSUE THREAD

**Issue by siwkd2** [KurtBestor/Hitomi-Downloader-issues#430]
![57 7](https://user-images.githubusercontent.com/44530054/51515259-5266cb80-1e56-11e9-85e8-00ce14e71eca.png)

영어로 표기된 폴더를 지정할때는 문제가 없는데

한국어 폴더로 지정할경우 ?? 가 뜹니다

??가 뜰경우 다운로드 시도를 해도 다운로드가 안되는 버그가 발견되었습니다

문의사항 읽어주셔서 감사합니다

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by siwkd2** [comment]
> 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

확인결과 잘됩니다 수정해주셔서 감사합니다
