### ISSUE TITLE
jmana 사이트에서 작품설명이 긴 파일들은 다운로드가 안 되네요.

### ISSUE THREAD

**Issue by vnfmsvldksh** [KurtBestor/Hitomi-Downloader-issues#433]
jmana 사이트에서 다운이 되는 게 있고 안 되는 게 있네요.

제가 다운받는 방법이 잘못된 건지 모르겠지만 다운로드가 안 되는 자료들이 많습니다.

히토미 다운로더는 2.5c 버전 사용중입니다.

예를 들어 아래 링크는 아무리 기다려도 파일을 읽어들이지 못하고 다운로드가 진행되지 않습니다.

https://www.jmana2.com/book/%EB%AF%B9%EC%8A%A4(MIX)

하지만 권수가 훨씬 많은 아래 링크의 파일은 다운로드가 됩니다.

https://www.jmana2.com/book/%EC%98%81%EC%9B%85%EB%AC%B82%EB%B6%80_%EC%8B%A0%EC%A1%B0%ED%98%91%EB%A0%A4

여러 개의 파일을 다운로드 시도해보니 jmana 사이트 왼쪽에 기재된 작품설명?이 짧은지 긴지에 따라 다운로드 에러가 발생하는 것 같습니다.

작품설명이 지나치게 긴 것들은 히토미 다운로더 프로그램이 읽어들이지를 못하네요.

예를 들어 아래의 링크도 jmana 사이트에 작품설명이 지나치게 길게 설명된 만화인데 다운로드가 안 됩니다.

https://www.jmana2.com/book/%EB%A8%B9%EC%A7%B1

혹시나 싶어서 설정에서 다운로드 폴더명 형식을 바꿔봐도 마찬가지였습니다.

이게 히토미 다운로더의 이상인지 아니면 제가 다운로드 하는 방식에 문제가 있는 건지 조언 주시면 정말 고맙겠습니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by vnfmsvldksh** [comment]
올려주신 파일로 실행해 봤더니 정상적으로 다운로드가 가능하네요.^^
빠른 피드백 정말 감사합니다.
앞으로도 잘 쓰겠습니다~!
