### ISSUE TITLE
익헨에 다운받아지지 않는 링크가 다수 존제합니다.

### ISSUE THREAD

**Issue by meandy124** [KurtBestor/Hitomi-Downloader-issues#434]
![default](https://user-images.githubusercontent.com/46983919/51651443-3aff1e00-1fcf-11e9-8c13-a6a5035b5e2f.JPG)

https://exhentai.org/g/998990/28f54ca006/

이 링크를 다운받으려고 하는데 저렇게 뜨고 다운이 되지않습니다.

버전은 최신버전입니다

**Comment by KurtBestor** [comment]
해당 작업 마우스 우클릭해서 `정보... (I)` 눌러서 나오는 내용 보여주세요.

**Comment by meandy124** [comment]
Invalid : [hitomi] https://exhentai.org / g / 998990 / 28f54ca006 / 

version: 2.5c
gal_num: https://exhentai.org/g/998990/28f54ca006/
dir: 
zip: 
type: exhen
artist: None
url: https://exhentai.org/g/998990/28f54ca006/
valid: False
done: False
range: None
range_p: None
single: True
time: 1548298911.19 (Jan 24)
tags: []


[Gallery]
None


[File Names]



[URLs]


이렇게 뜨는데요 다른 비슷한 증상 가지고 계신분들 게시글들 참고하다가

테스트 버전 있길래 그걸로 해봤더니 정상작동 합니다. 귀찮게 해드려서 죄송합니다
