### ISSUE TITLE
히토미다운로더 오프라인이 뜹니다.

### ISSUE THREAD

**Issue by insky007** [KurtBestor/Hitomi-Downloader-issues#435]
![image](https://user-images.githubusercontent.com/46981730/51652620-a945df80-1fd3-11e9-81cb-fb81fa20eafd.png)

히토미 다운로더 시작시 checking for updating 화면에서 소요시간이 많이걸리며 위 사진과 같이 오프라인이 뜹니다.  오프라인이 떠있는데 파일다운로드는 잘됩니다. 

![image](https://user-images.githubusercontent.com/46981730/51652697-ead68a80-1fd3-11e9-963b-ab2462e1b266.png)

도움말에서 버전확인버튼을 누르면 위처럼 실패가뜹니다.

**Comment by KurtBestor** [comment]
복구했어요.
