### ISSUE TITLE
삭제된 데이터 다운로드가 안됩니다.

### ISSUE THREAD

**Issue by mayocarmen** [KurtBestor/Hitomi-Downloader-issues#436]
다운로더 항상 감사하게 잘 쓰고 있습니다. 
이번 2.5c 버전에서 기본데이터 다운로드는 되는데, 삭제된 데이터 다운로드가 실패하고 이런 에러메세지가 뜹니다.

조언 부탁드립니다.

삭제된 데이터를 다운로드하는 중에  실패했습니다.
Traceback (most recent call last):
 File "hitomi_searcher", line 103, in 
download_json_forbidden 
 File "zip_forbidden", line 50, in load 
IOError: [Errno 13] Permission denied: u 'D:
\\hitomi\\Hitomi down\\hitomi GUI\\hitomi 
GUI v2.5c\\hitomi_data\\tmp.zip"

**Comment by KurtBestor** [comment]
`D:\hitomi\Hitomi down\hitomi GUI\hitomi GUI v2.5c\hitomi_data` 에 `tmp.zip` 이 있나요?

**Comment by mayocarmen** [comment]
혹시나 했는데 역시 관리자권한도 안 먹히네요. 
똑같은 에러메세지 뜹니다.  음..

**Comment by mayocarmen** [comment]
> 관리자권한으로 실행해보세요. 어떤가요?



> 관리자권한으로 실행해보세요. 어떤가요?

혹시나 했는데 역시 관리자권한도 안 먹히네요.
똑같은 에러메세지 뜹니다. 음..

**Comment by KurtBestor** [comment]
`D:\hitomi\Hitomi down\hitomi GUI\hitomi GUI v2.5c\hitomi_data` 에 `tmp.zip` 이 있나요?

**Comment by mayocarmen** [comment]
> `D:\hitomi\Hitomi down\hitomi GUI\hitomi GUI v2.5c\hitomi_data` 에 `tmp.zip` 이 있나요?

아뇨. 없네요. 숨김파일은 다 보이게 설정했는데도 그 경로에 tmp.zip은 없습니다. 
기본데이터 파일 21개만 있습니다.

**Comment by mayocarmen** [comment]
방금 v2.5b에서도 삭제데이터 다운 안되고 v2.5c랑 똑같은 에러메세지가 떴습니다. (기본데이터는 다운O)
분명 오늘 새벽까지만 해도 v2.5b는 됐었는데... 
제가 그 사이에 한 건 폴더 경로 중 하나 없앤 거 밖에 없습니다. 
D:\hitomi\Hitomi down\hitomi GUI\hitomi GUI v2.5b\hitomi_data 여기서 Hitomi down만 빼고 
D:\hitomi\hitomi GUI\hitomi GUI v2.5b\hitomi_data 이렇게 바꿨습니다.

**Comment by mayocarmen** [comment]
이제보니까 삭제데이터뿐만 아니라 아예 망가 다운 자체가 안 되네요.(주황색으로 뜨고 결과폴더안에 파일이 없음)
최소한 15시간 전까지만해도(오늘 새벽) 망가 다운은 됐습니다. 
근데 어제 새벽에는 받아졌던 똑같은 망가를 검색기로 다운하는 것도 안되고 주소복사해서 다운로더로 다운하는 것도 안됩니다. 
물론 다른 망가도 마찬가지로 안됩니다.
혹시나 서버밴 당한건가싶어서 히토미뿐아니라 폰허브도 시도해봤는데 폰허브 다운도 안됩니다.
스레드 개수도 1개, 32개까지 줄여가면서 실험해봤는데 안되는 건 마찬가집니다. 
계속 귀찮게 해드려서 죄송합니다. 정말 뭐가 문제인지...

**Comment by mayocarmen** [comment]
지금은 또 잘 받아집니다. 삭제데이터도 잘 다운됩니다.(v2.5b, v2.5c 둘 다)

아까 전에 어베스트 업데이트 되고나서 히토미GUI 앱허용/차단 메세지가 뜨길래 허용눌렀더니 되는 거 같기도 하고 잘 모르겠네요. 

실험해볼겸 백신프로그램없는 다른 컴퓨터(노트북, 윈7)에서 켜봤는데 이번엔 v2.5c는 되는데 v2.5b가 다운이 안되네요. 
그래서 백신 문제인지 아닌지도 확실하지가 않습니다. 
일단은 메인 컴퓨터에서 다운이 되니까 다행이긴한데... 원인을 모르니 겁이 나네요

**Comment by KurtBestor** [comment]
어떤 OS 쓰시나요?

**Comment by mayocarmen** [comment]
> 어떤 OS 쓰시나요?

윈10 씁니다
