### ISSUE TITLE
산카쿠 다운로드 관련 문의드립니다

### ISSUE THREAD

**Issue by xesgnik** [KurtBestor/Hitomi-Downloader-issues#438]
혹시 popular order로 상위 n개 받는 기능이 있을까요? 예를 들어 오버워치 popular같은 경우,
https://chan.sankakucomplex.com/?tags=overwatch%20order%3Apopular
를 기입하면 끝도 없이 read해서 결국 안받아지는거 같은데, 혹시 상위 100개만 받을 수 있거나 하는 기능이 있으면 좋겠는데 아시는바 있으신가요?

사실 이건 프로그램 자체 기능보다는 산카쿠 홈페이지 url 포매팅 관련된 질문이긴 한데, 혹시 아신다면 알려주시면 정말 감사하겠습니다.

**Comment by xesgnik** [comment]
아 그리고 혹시 폴더 없이 파일만 온전히 받을 수 있는 방법이 있을까요? 산카쿠 같은 경우에는 폴더 없이 받을 수 있으면 더 좋을거같네요.

항상 감사합니다!

**Comment by KurtBestor** [comment]
기본값은 2000장이에요. 100장만 다운로드 받으려면 다음과 같이 입력하면 돼요:
```
~ 100
```

![image](https://user-images.githubusercontent.com/14768120/51735102-cc52bb00-20c9-11e9-9f3c-b1f6fcf5d223.png)

참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/382#issuecomment-450846793

폴더 없이 다운로드 하는 기능은 없어요.

**Comment by xesgnik** [comment]
오오 감사합니다!
