### ISSUE TITLE
사이트 추가 건의 - 가능할까요, 여기?

### ISSUE THREAD

**Issue by baejusik** [KurtBestor/Hitomi-Downloader-issues#439]
https://funbe.net 여기 웹툰 많은 곳인데요... 혹시 가능할까요?
보니까 오른쪽 클릭했을 때 링크 주소도 안나오고 엄청 막아놓은 것 같던데...

**Comment by AnonymousPomp** [comment]
@baejusik 
https://github.com/AnonymousPomp/Comic-Downloader
