### ISSUE TITLE
건의사항

### ISSUE THREAD

**Issue by Kurtc0b4n3** [KurtBestor/Hitomi-Downloader-issues#44]
안녕하세요 
프로그램 잘 쓰고 있습니다
있었으면 하면 하는 부분들이 초기때부터 있었는데 
개발자분께서 업데이트를 계속 하시는 것 같아 건의해봅니다

- 저장할 페이지 지정 기능 
(예:2000장짜리 cg집을 다운받을때 "1, 500-1000" 입력시 1페이지와 500페이지~1000페이지만 다운로드). 대량 파일 저장할때 시간이 단축될거라 생각합니다. 다운받을 주소명 뒤에 원하는 페이지를 기입하거나 다운로드중인 항목 더블 클릭 후 입력하는것으로 설정 가능했으면 합니다

- 다운로드시 이미지 크기 설정기능 
(넓이/높이 max 설정, 비율고정)
(경험상 다운로드 후 리사이저 쓰려면 변환할 항목 일일히 찾느라 시간이 걸립니다) 

- 다운로드 일시정지 기능

이상입니다
문외한이 쓴 글이니 대충 보고 거르시면 되겠습니다

**Comment by KurtBestor** [comment]
1. 주소를 입력하고 추가하면 이미 다운로드를 시작한 상태여서, 그 후에 페이지를 지정하는 건 무리일 것 같아요. 말씀하신 대로 주소 뒤에 페이지를 지정하면 123[1,500-1000] 이런 식으로 되겠죠..
좀 지저분한 것 같아 좀 더 나은 방법이 있는지 생각해볼게요.

2. 이건 가능할 것 같아요. (GIF, 동영상 파일 제외)
다만, 32비트 환경에서도 돌아가게 32비트 프로그램으로 개발했는데요, 그래서 메모리 제한이 2GB 정도 됩니다. 그래서 큰 이미지 파일들은 읽지 못해요. 가끔씩 표지 이미지가 안 보이는 현상이 이것 때문입니다.

3. 이건 비유를 통해서 설명드릴게요. 공장이 프로그램이고, 그 안에서 일하는 사람들을 스레드라고 해요. 팀은 4개가 있고, 64명이 한 팀을 맺고 한 작업을 하게 돼요. 한 작업을 일시정지하게 되면, 해당 작업을 하던 사람들은 작업을 어디까지 했는지 기록해두고 다른 작업을 해야 해요. (다른 팀을 더 고용하면 안 되나 하는 생각을 하실 수도 있는데, 한 공장에 너무 많은 사람이 들어가면 공장이 터져버려요.) 여기서 문제가 있는데, 이 작업을 기록하는 과정이 너무 복잡하고, 다른 팀이 와서 해당 작업을 이어서 하게 되었을 때, 작업의 상태가 의도치 않게 조금 바뀌어버리면 작업을 제대로 할 수가 없다는 거예요. 해결 방법이 있을지도 모르지만 일단 제 능력으로는 무리인 것 같습니다ㅠㅠ

쓰고 보니 하나 빼고 다 안된다는 글만 쓴 것 같은데 죄송합니다ㅠ 혹시 다른 대안 있으시면 말씀해주세요!

**Comment by KurtBestor** [comment]
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

패치판입니다

**Comment by KurtBestor** [comment]
![page](https://user-images.githubusercontent.com/14768120/35843908-223c9d8e-0b4e-11e8-9dbe-49bdbb94f366.png)

페이지 지정 기능은 이렇게 구현할 예정인데 더 좋은 방법 있으면 제안 바래요.

**Comment by Kurtc0b4n3** [comment]
시간 날 때 보시겠지 하고 건의 남겼는데 금방 답해주셨네요 
알기 쉽게 친절히 알려주셔서 감사합니다. 일시정지 부분 안되는거 이해했구요
리사이징 엄청 빨리 구현해주신 부분 감사드립니다. 사용이 한결 편할 듯. 
png/bmp=>jpg까지 가능하면 더 편할지도?
페이지 지정 다운로드는 올려주신 이미지대로여도 괜찮을 것 같네요. 며칠 전부터 사이트가 얼은 상태라 판다를 써야하니 저 말고도 이 기능 필요한 분들이 많이 생길 듯 (gp 딸림...)
