### ISSUE TITLE
뉴토끼 다운이 안되요

### ISSUE THREAD

**Issue by ldh7680** [KurtBestor/Hitomi-Downloader-issues#443]
홈페이지 리뉴얼 때문인지 웹툰은 다운이 되는데 단행본쪽이 다운이 안되네요
수정 부탁드립니다

**Comment by KurtBestor** [comment]
수정했어요: https://drive.google.com/drive/folders/1FP0YZp7QyGDyOQ1nwILRIVT3kd58NYxo

**Comment by ldh7680** [comment]
Invalid : [newtoki] https://newtoki.net / comic / 133997

version: 2.5c
gal_num: https://newtoki.net/comic/133997
dir: 
zip: 
type: newtoki
artist: None
url: https://newtoki.com/webtoon/133997
valid: False
done: False
range: None
range_p: None
single: False
time: 1548650383.03 (Jan 28)
tags: []


[Gallery]
None


[File Names]



[URLs]



[Messages]
stop
Traceback (most recent call last):
File "utils", line 437, in start
File "utils", line 481, in start_
File "dynamic_module_1", line 74, in read
File "dynamic_module_1", line 70, in name
File "dynamic_module_1", line 55, in soup
File "dynamic_module_1", line 112, in get_soup
Exception: Failed to get soup

Fail: newtoki

done : https://newtoki.net/comic/133997

여전히 다운이 안되네요.ㅜㅜ

**Comment by KurtBestor** [comment]
실수로 업데이트를 안했네요. 이제 될거예요: https://drive.google.com/drive/folders/1FP0YZp7QyGDyOQ1nwILRIVT3kd58NYxo

**Comment by ldh7680** [comment]
잘되네요~~~ 너무 감사합니다^^
