### ISSUE TITLE
weibo 다운이 안됩니다.

### ISSUE THREAD

**Issue by tizmvkdnj** [KurtBestor/Hitomi-Downloader-issues#445]
예전에 잘됬었는데 요즘엔 안되네요
https://www.weibo.com/p/1005052238259744/photos?from=page_100505&mod=TAB#place
이 링크를 다운 받으려 안되서 링크주소 복사 하니
https://weibo.com/p 
이렇게 나오네요

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by unknownmania** [comment]
웨이보 다운로드가 안돼서 찾다가 이 테스트 버전을 발견해서 테스트 해봤음
결론적으로 이 테스트 버전으로는 웨이보 다운로드가 잘 이루어짐
