### ISSUE TITLE
픽시브 다운로드가 갑자기 안되네요

### ISSUE THREAD

**Issue by Rounlet** [KurtBestor/Hitomi-Downloader-issues#446]
Error L: pixiv_https://www.pixiv.net / member_illust.php?id=31314

[u'Traceback (most recent call last):\n File "pixiv_downloader", line 64, in init\n File "pixiv_downloader", line 278, in get_api\n File "pixivpy3\\api", line 99, in login\n File "pixivpy3\\api", line 130, in auth\nPixivError: [ERROR] auth() failed! check username and password.\nHTTP 400: {"has_error":true,"errors":{"system":{"message":"access_denied","code":1508}}}\n']

version: 2.5c
gal_num: pixiv_31314
dir: 
zip: 
type: pixiv
artist: None
url: https://www.pixiv.net/member_illust.php?id=31314
valid: False
done: False
range: None
range_p: None
single: True
time: 1548655936.31 (Jan 28)
tags: []

[Gallery]
None

[File Names]

[URLs]

몇분 전까지만 해도 주루룩 받았는데 갑자기 다운로드 에러가 뜨네요.
제가 봤을 땐 픽시브 로그인이 제대로 안 되서 아이디 및 비밀번호와 관련된 메시지가 출력되는거 같아요.

분명 로그아웃 한적도 없고 몇분전까지만 해도 잘 돌아갔었고..
텀을 두고 한개가 끝나면 다른 한개로 넘어가는 식으로 다운로를 했는데
다운로드를 연속적으로 하면 뜨는 일시적 현상인가요, 아니면 IP밴이라도 당한걸까요?ㅜㅠ

너무 훌륭한 프로그램 잘 쓰고 있습니다! 파이팅이요ㅎㅎ
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
지금은 또 잘 되네요. 혹시 원인을 좀 알 수 있을까요?
다운 받던 당시 익헨에서 아카이브 다운로드가 진행되고 있긴 했는데 다운로더를 쓴게 아니라 브라우저를 통해서 다운 받던거라 별 상관없으리라 생각했거든요. 직접적인 연관성이 있나요?

**Comment by KurtBestor** [comment]
익헨과 연관은 없어요.
얼마나 자주 그러나요?

**Comment by Rounlet** [comment]
> 익헨과 연관은 없어요.
> 얼마나 자주 그러나요?

그때 이후론 발생하고 있지 않습니다.
그때는 한 20여분 정도 작동을 안 했어서 문제가 심각한건줄 알았는데
일시적인 문제였던거 같습니다.
