### ISSUE TITLE
텀블러 다운로드가 주황색으로 완료되고 진행이 안됩니다.

### ISSUE THREAD

**Issue by bwcat2** [KurtBestor/Hitomi-Downloader-issues#447]
늘 수고 많으십니다 개발자님
주황색은 불완전한 완료라고 되있는데 안멈추는 텀블러 블로그가 없네요 혹시 확인 가능할까요?

**Comment by KurtBestor** [comment]
해당 작업 `마우스 우클릭` - `정보... (I)` 눌러서 나온 내용 보여주세요.
