### ISSUE TITLE
히요비 이제 다운로드 안되나여?

### ISSUE THREAD

**Issue by showupmoney** [KurtBestor/Hitomi-Downloader-issues#449]
히요비꺼는 이제 다운로드 안되는건가여?

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by PrivateI** [comment]
되네요. 히토미에 없으면 알아서 히요비로 받기까지 하는군요.
거기에 쇼미도 되는거같고요

**Comment by PrivateI** [comment]
![image](https://user-images.githubusercontent.com/47856246/53170411-65221b00-3623-11e9-846f-05bb8eb7fc15.png)

![image](https://user-images.githubusercontent.com/47856246/53170366-4d4a9700-3623-11e9-97cb-29bbaa05002b.png)
저런게 뜨긴 하네요

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/128, https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/472

해당 파일 [VirusTotal](https://www.virustotal.com/#/home/upload) 에서 검사해서 확인해보세요.
제가 확인해보니 AhnLab-V3 도 Clean이라고 나오네요: [[링크]](https://www.virustotal.com/#/file/0cfaa8416a9fc10aa7f0fdbfb95831e63613deca94007770bf13793d2cbde3e5/detection)
