### ISSUE TITLE
작가추천 기능이 되질 않습니다.

### ISSUE THREAD

**Issue by forthefsm** [KurtBestor/Hitomi-Downloader-issues#450]
작가추천 기능을 사용해도 작품을 제대로 읽어오질 못해요. 

설정에서 다운로드 폴더를 바꿔봐도 어째선지 작품을 2개 밖에 못 읽고요.

검색기-저장폴더에서 모든작가 불러오기는 잘 되거든요. 

기본 데이터 다운로드를 해봐도 작가추천이 모든 작품을 못 읽어요.

읽기가 진행되면서 1/324, 45/324 이런식으로 수치가 오르기는 하는데 작업이 끝나면 딸랑 두 작품 뿐이에요.

대체 뭐가 문제일까요?

**Comment by KurtBestor** [comment]
`메뉴` - `저장 폴더에 있는 모든 갤러리 넘버 복사` 누르면 어떻게 되나요?

**Comment by forthefsm** [comment]
> `메뉴` - `저장 폴더에 있는 모든 갤러리 넘버 복사` 누르면 어떻게 되나요?

전부 실패로 나와요.

**Comment by KurtBestor** [comment]
`자세한 정보 보기...` 눌러서 나오는 내용 보여주세요.
