### ISSUE TITLE
망가쇼미 다운로드 또 안되고 있습니다.

### ISSUE THREAD

**Issue by ralf79** [KurtBestor/Hitomi-Downloader-issues#451]
궁금한게 지금 canvas를 통으로 다운로드 하는거 아닌가요?

아까까지 잘되다가 지금은 다시 안되네요.
다시 퍼즐처럼깨지고 있습니다.
파이썬 공부중인데 많은 도움되고 있습니다. 
감사합니다.

**Comment by KurtBestor** [comment]
자바스크립트 복호화랑 똑같이 프로그램에서 돌아가게 한건데 최신화들은 복호화 방식을 바꿨네요.
사실 자바스크립트 조금만 바꿔도 막히는거라서 좀 불안하긴 했는데 이렇게 빨리 바꿀줄은 몰랐어요.
좀 시간이 걸릴 것 같네요.

**Comment by david761276** [comment]
주로 다운 걸어 놓고 보는데.. 
아쉽네요.. ㅜㅜ 

아무튼  히토미 너무 잘사용하고 있어요 
감사합니다 ^^

고쳐지면 부탁드릴께요~~~

**Comment by ralf79** [comment]
@KurtBestor  그렇다면 셀레니윰으 할때 canvas를 그대로 캡춰해서 다운로드 할수 있지 않을까요?? 
요새 막 스크래핑 파이썬을 공부하고 있어서 문의드려봅니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview
깨진 이미지파일은 모두 지우고 다시 다운로드해야해요.

**Comment by david761276** [comment]
와 !! 피드백 정말 빠르세요... 

너무 감사드리고 경이롭습니다.... 

감사합니다

**Comment by hhhssj** [comment]
저 같은 경우는 목록만 계속 읽을 뿐 다운이 안되네요. 전 버전 다운로더로 다시 해보니 다운은 잘 됩니다. 망강쇼미가 오늘부터 아예 마우스 오른쪽 버튼 클릭도 못하게 막아놨습니다. 어제 같은 경우 마우스 오른쪽 버튼으로 한 장씩 저장하는 것은 됐었거든요. 다른 분들은 다운 잘 되는지 궁금합니다.

**Comment by KurtBestor** [comment]
@hhhssj 해당 작업 `마우스 우클릭` - `정보... (I)` 눌러서 나오는 내용 보여주세요.

**Comment by hhhssj** [comment]
읽는 중... [쵸모란] 저 사람의 위엔 내가 부족해

version: 2.5c
gal_num: https://mangashow.me/bbs/page.php?hid=manga_detail&manga_name=%EC%A0%80+%EC%82%AC%EB%9E%8C%EC%9D%98+%EC%9C%84%EC%97%94+%EB%82%B4%EA%B0%80+%EB%B6%80%EC%A1%B1%ED%95%B4
dir: 
zip: 
type: mangashow
artist: 쵸모란
url: https://mangashow.me/bbs/page.php?hid=manga_detail&manga_name=%EC%A0%80+%EC%82%AC%EB%9E%8C%EC%9D%98+%EC%9C%84%EC%97%94+%EB%82%B4%EA%B0%80+%EB%B6%80%EC%A1%B1%ED%95%B4
valid: True
done: False
range: None
range_p: [6]
single: False
time: 1549115199.85 (Feb 2)
tags: []


[Gallery]
None


[File Names]



[URLs]



[Messages]
dirFormat: [artist] title
dirFormat: [artist] title
dirFormat: [artist] title

**Comment by hhhssj** [comment]
"저 사람의 위엔 내가 부족해 7화"를 받으려고 했는데 한 시간이 지나도 목록만 떠있을 뿐 전혀 받아지지 않았습니다.

**Comment by hhhssj** [comment]
"저 사람의 위엔 내가 부족해 7화"를 받으려고 했는데 한 시간이 지나도 목록만 떠있을 뿐 전혀 받아지지 않았습니다. 다른 사람들이 되는데 저만 안된다면 제 환경에 문제가 있다고 판단하고 운영체제나 컴퓨터 등을 바꿔볼 생각입니다.

**Comment by KurtBestor** [comment]
@hhhssj 
다음 실행 파일로 테스트해서 나오는 작업 정보 알려주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by hhhssj** [comment]
읽는 중... [쵸모란] 저 사람의 위엔 내가 부족해 / 저 사람의 위엔 내가 부족해 7화 (0 / 1)

version: 2.5c
gal_num: https://mangashow.me/bbs/page.php?hid=manga_detail&manga_name=%EC%A0%80+%EC%82%AC%EB%9E%8C%EC%9D%98+%EC%9C%84%EC%97%94+%EB%82%B4%EA%B0%80+%EB%B6%80%EC%A1%B1%ED%95%B4
dir: 
zip: 
type: mangashow
artist: 쵸모란
url: https://mangashow.me/bbs/page.php?hid=manga_detail&manga_name=%EC%A0%80+%EC%82%AC%EB%9E%8C%EC%9D%98+%EC%9C%84%EC%97%94+%EB%82%B4%EA%B0%80+%EB%B6%80%EC%A1%B1%ED%95%B4
valid: True
done: False
range: None
range_p: [6]
single: False
time: 1549120872.36 (Feb 3)
tags: []


[Gallery]
None


[File Names]



[URLs]



[Messages]
dirFormat: [artist] title

**Comment by KurtBestor** [comment]
@hhhssj 페이지 지정하지 않고 전체 다운로드 해보실래요?

**Comment by hhhssj** [comment]
읽는 중... [쵸모란] 저 사람의 위엔 내가 부족해 / 저 사람의 위엔 내가 부족해 2화 (1 / 7)

version: 2.5c
gal_num: https://mangashow.me/bbs/page.php?hid=manga_detail&manga_name=%EC%A0%80+%EC%82%AC%EB%9E%8C%EC%9D%98+%EC%9C%84%EC%97%94+%EB%82%B4%EA%B0%80+%EB%B6%80%EC%A1%B1%ED%95%B4
dir: 
zip: 
type: mangashow
artist: 쵸모란
url: https://mangashow.me/bbs/page.php?hid=manga_detail&manga_name=%EC%A0%80+%EC%82%AC%EB%9E%8C%EC%9D%98+%EC%9C%84%EC%97%94+%EB%82%B4%EA%B0%80+%EB%B6%80%EC%A1%B1%ED%95%B4
valid: True
done: False
range: None
range_p: None
single: False
time: 1549122340.11 (Feb 3)
tags: []


[Gallery]
None


[File Names]



[URLs]



[Messages]
dirFormat: [artist] title
[seed] 저 사람의 위엔 내가 부족해 1화 0

**Comment by hhhssj** [comment]
읽는 중... [쵸모란] 저 사람의 위엔 내가 부족해 / 저 사람의 위엔 내가 부족해 7화 (6 / 7)

version: 2.5c
gal_num: https://mangashow.me/bbs/page.php?hid=manga_detail&manga_name=%EC%A0%80+%EC%82%AC%EB%9E%8C%EC%9D%98+%EC%9C%84%EC%97%94+%EB%82%B4%EA%B0%80+%EB%B6%80%EC%A1%B1%ED%95%B4
dir: 
zip: 
type: mangashow
artist: 쵸모란
url: https://mangashow.me/bbs/page.php?hid=manga_detail&manga_name=%EC%A0%80+%EC%82%AC%EB%9E%8C%EC%9D%98+%EC%9C%84%EC%97%94+%EB%82%B4%EA%B0%80+%EB%B6%80%EC%A1%B1%ED%95%B4
valid: True
done: False
range: None
range_p: None
single: False
time: 1549122340.11 (Feb 3)
tags: []


[Gallery]
None


[File Names]



[URLs]



[Messages]
dirFormat: [artist] title
[seed] 저 사람의 위엔 내가 부족해 1화 0
[seed] 저 사람의 위엔 내가 부족해 2화 0
[seed] 저 사람의 위엔 내가 부족해 3화 0
[seed] 저 사람의 위엔 내가 부족해 4화 0
[seed] 저 사람의 위엔 내가 부족해 5화 0
[seed] 저 사람의 위엔 내가 부족해 6화 0

**Comment by hhhssj** [comment]
최신화인 7화는 못 읽는 것 같네요

**Comment by hhhssj** [comment]
최신화인 7화는 못 읽는 것 같네요. 1화부터 6화짜지 지정해서 다운 시도해 봤는데 1~6화는 다운됩니다.

**Comment by KurtBestor** [comment]
XP 쓰시나요?

**Comment by hhhssj** [comment]
예 평소엔 XP 사용합니다. 혹시 넷프레임 영향인가요?

**Comment by hhhssj** [comment]
예 평소엔 XP 사용합니다. 혹시 넷프레임 영향인가요? 한번 윈7으로 테스트 해보겠습니다.

**Comment by hhhssj** [comment]
윈7으로 하니까 잘 되네요. 저 때문에 고생시켜드려서 정말 죄송하고 또한 일일이 답변 달아주셔서 정말 감사드립니다.

**Comment by KurtBestor** [comment]
@hhhssj 
XP 에서도 되게 수정했어요. 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by david761276** [comment]
저는 방화벽 허용 메시지 나와서 허용했더니 잘됩니다
윈 10 사용해요...

**Comment by ourload** [comment]
어 망가쇼미 스크립트가 구글드라이브에서 안 보이네요?? mangashow라는 이름이었던거 같은데요
좀 오랜만에 왔는데 그사이에 스크립트가 업데이트 됐는지 제가 가진 망가쇼미 스크립트로는 invalid가 뜨네요 프로그램 최신으로 받았는데도요

**Comment by KurtBestor** [comment]
@ourload 
최신버전부턴 망가쇼미 스크립트 넣으면 안돼요. 내부적으로 지원해요.
스크립트 넣었다면 프로그램 재시작해주세요.

**Comment by ourload** [comment]
어우 매우 잘되네요 감사합니다
