### ISSUE TITLE
기본 데이터 다운로드가 안됩니다.

### ISSUE THREAD

**Issue by mita5549** [KurtBestor/Hitomi-Downloader-issues#452]
-

**Comment by whgmlqja12** [comment]
윗분과 마찬가지인 증상뜹니다. 데이터가 노 데이터로 계속 뜨구 한 새벽2신가 3시사이에 오류 뜬거같은데요. 히토미사이트가 문제인건지 다운로더가 문제인건지 잘 모르겠네요.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by chbk256** [comment]
기본 데이터는 받아지나, 고급 검색에서 MANGA 제외 아티스트 CG나 게임 CG 같은 다른 분류가 검색되지 않는 현상이 생겼군요.

**Comment by KurtBestor** [comment]
@chbk256 

히토미에서 전체 갤러리 정보를 제공해주는데, 이젠 `타입 (Type)` 이 없어졌네요. 그래서 Manga 인지, GameCG인지 구분을 못하게돼서 일단 모두 Manga로 분류되게 했어요.

가장 오래된 갤러리 번호가 기본 데이터는 7, 삭제된 데이터는 873이어서 그래요.

**Comment by chbk256** [comment]
히토미에서 왜 굳이 그렇게 불편하게 바꿨나 모르겠군요.

어쨌든 답변 감사합니다.
