### ISSUE TITLE
히토미 타입별로 검색할 수 있게  되는가요?

### ISSUE THREAD

**Issue by chbk256** [KurtBestor/Hitomi-Downloader-issues#453]
https://hitomi.la/type/doujinshi-all-1.html

타입 분류가 사라졌다기에 확인해보니 갤러리 내에 Type : Artist CG형식 표시 및

그 타입 형식을 누르면 위와 같이 그 타입 별로만 나타나는 걸 보니 기능 자체는 살아있는 것 같네요.
(게다가 삭제 된 데이터에서 검색할 경우 타입 별로 표시가 되더군요)

아무래도 다른 의미로 말씀하신 것 같은데, 일단 사이트 내 기능 자체는 남아있는 것 같으니

나중에라도 가능하신지 한번 건의드려 봅니다.

**Comment by chbk256** [comment]
코드 자체를 건드렸단 뜻이군요. 

사실상 타입 분류 표시가 없으면 많이 불편하긴 한데, 

사이트 자체에서 없애버렸으면 특별한 아이디어가 없는 한 힘들겠네요. 

아무튼 답변 감사합니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview
