### ISSUE TITLE
홈화면?에서 검색할수 있게 해주실수 있나요?

### ISSUE THREAD

**Issue by knife9707** [KurtBestor/Hitomi-Downloader-issues#454]
홈화면? 다운링크 적는 창에 리스트 많이 추가해놓고 사용하고 있는데 원하는 다운로드를 찾아서 다운받으려면 엄청 내려보고 찾아봐야되더라구요 모두선택해서 다운해도 되기는 한데 하나 다운하려고 계속 전체다운로드 하는건 비효율적인거같고..홈화면에 검색창을 만들어서 타이틀? 입력하면 그 목록이 뜨게 해주실수있나요?

**Comment by KurtBestor** [comment]
`도움말` - `사용법` - `다운로더 목록 필터링` 을 보세요.

**Comment by knife9707** [comment]
앗..잘 만들어져 있었군요 편리하네요! 감사합니다!
