### ISSUE TITLE
DC인사이드와 티스토리 지원 부탁드립니다.

### ISSUE THREAD

**Issue by kin9834** [KurtBestor/Hitomi-Downloader-issues#455]
국내에서 제일 이미지 많이 올라오는 곳인데 제대로 된 다운로더가 없어서 답답하네요. 부탁드립니다.

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/300

**Comment by KurtBestor** [comment]
https://github.com/KurtBestor/Hitomi-Downloader/issues/1280#issuecomment-692370898
