### ISSUE TITLE
픽시브 이미지 파일 네이밍 관련 요청사항입니다.

### ISSUE THREAD

**Issue by hitoto77** [KurtBestor/Hitomi-Downloader-issues#458]
안녕하세요. 개발자님. 초창기 때부터 매우 유용하게 잘 사용하고 있는 유저입니다.
여러 다운로드 프로그램 및 스크립트를 써왔는데 가장 깔끔하고 유저친화적이여서 초창기 때부터 매우 잘 사용하고 있습니다. 픽시브 작품들을 다운받을 때 이런 기능이 추가 되면 더 좋을 것 같아 요청 드려봅니다. 저는 픽시브 다운을 할 때 다른 것도 겸용해서 사용하고 있습니다. 크롬 확장프로그램 [Pixiv Downloader](https://chrome.google.com/webstore/detail/pixiv-downloader/fnbkeopcpjainobjebddfcnnknmfipid)입니다. 네이밍 기능이 정말 좋았거든요. 저는 픽시브 파일을 저장할 때 
![1](https://user-images.githubusercontent.com/47321370/52207525-11909d00-28c1-11e9-9d03-565479f78ce3.jpg)
이런 식으로 저장하고 있습니다.
예를 들어 https://www.pixiv.net/member_illust.php?mode=medium&illust_id=72963429 이 작품을 저장할 때
Restoria.樓 - 【PFLS】残光の魔女：Veronica p0
Restoria.樓 - 【PFLS】残光の魔女：Veronica p1
이렇게 파일 이름이 생성됩니다.

이런 식으로 https://www.pixiv.net/member.php?id=작가id넘버 링크로 다운받을 때
작가명 폴더에 저장되는 이미지 파일의 네이밍 규칙을 유저가 원하는 대로 설정할 수 있으면 정말 좋을 것 같습니다.

그리고 기존에 작가의 작품들을 일괄 다운받았을 경우 마음에 안들어서 삭제한 작품 로그가 저장이 되어
다시 다운받았을 경우 다운받지 않은 새로운 작품만 추가로 다운받을 수 있으면 좋겠습니다.

항상 잘 사용하고 있습니다… 감사합니다 ^_^

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

`옵션 - 설정 - 픽시브 - 파일명 형식` 에서 설정할 수 있어요.
다만 artist 이름이 바뀔 경우 폴더 명은 고치지만 파일 명은 고치지 못하니 주의해주세요.

**Comment by hitoto77** [comment]
테스트 해봤습니다!
    -id_ppage = 0000000_p0 / 0000000_p1 / 0000000_p2
    -id_ppage title = 0000000_p0 제목 / 0000000_p1 제목 / 0000000_p2 제목
    -[artist] id_ppage title = [작가이름] 00000000_p0 제목 / [작가이름] 00000000_p1 제목
기존 옵션은 다 문제 없네요.

제가 사용하는 방식으로 설정하고 한 페이지에 여러장 있을 땐, 그 페이지의 맨 앞장 _p0 만 받아집니다.
    -사진 한 장만 있을 시 artist - title = 작가이름 - 제목
    -사진 여러장 있을 시 artist - title = 작가이름 - 제목
다만 이 방식은 제가 하나씩 마음에 드는 작품을 저장할 때 쓰는 방식이였고
개발자님의 다운로더를 사용 시엔 한 작가의 작품을 일괄 다운로드 할 것이기 때문에
[artist] id_ppage title 로 설정 하여 업데이트 순으로 정렬하는게 더 좋아서 큰 문제는 안된다고 봅니다.
이대로 추가하셔도 괜찮다고 생각해요.

그리고 하나 궁금한 점이 있어 여쭈어 볼게요.
  -작가의 작품들을 일괄 다운 받았습니다.
  -그리고 마음에 안들어서 삭제한 작품 몇개를 삭제하였습니다.
  -며칠 후 그 작가가 새 작품들을 여러개 올려서 다시 그 작가 작품들을 다운 받으려 합니다.
  -이 경우, 다운받지 않은(새로 업데이트 된) 신규 작품만 추가로 다운 받을 수는 없을까요?
이는 인스타그램 이미지 & 영상 다운로더 프로그램인 [4K Stotram](https://www.4kdownload.com/ko/products/product-stogram) 에서 쓰이고 있습니다.
이 기능까지 있으면 정말 완벽하지 않을까 생각해봅니다.

네이밍 옵션 추가해주셔서 덕분에 훨씬 수월하게 픽시브 이용이 가능해 질 것 같습니다 감사합니다. ^_^

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/519
