### ISSUE TITLE
망가쇼미에서 이번엔 위아래를 절단시켜놨네요 업데이트가 필요한거같습니다

### ISSUE THREAD

**Issue by siwkd2** [KurtBestor/Hitomi-Downloader-issues#460]
16시 19분부터 올라오는 모든 만화들을 이번엔 위아래 절단시켜놨네요

다운로드를 받으면 한장을 둘로쪼개서 위아래로 두장씩 받아집니다

이번에도 확인결과 다운로드과정은 문제가 없었으며 망가쇼미측에서 패치를 한모양입니다

업데이트 해주시면 감사하겠습니다

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by david761276** [comment]
어차피 퍼 오는거 다함께 보게 해주고 다운도 하게 해주고 해주지.  
마루마루 보다 독하네요...  쩝... ㅜㅜ
일반 독자들이 다운 받아서 무슨 부귀영화를 얻는다고..
광고잔뜩 달려 있음.. 좀 베플어야 인지도 상승하지 

KurtBestor님 감사합니다 ^^

**Comment by siwkd2** [comment]
> 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview


업데이트 해주셔서 감사합니다 덕분에 잘쓰고있습니다

**Comment by mita5549** [comment]
혹시 저만 문제있나 싶어서 와보니 역시나 쇼미가 번거롭게 하네요;;
업데이트 감사합니다.
