### ISSUE TITLE
망가쇼미 화 수 정하기

### ISSUE THREAD

**Issue by samfan0429** [KurtBestor/Hitomi-Downloader-issues#462]
![sdsdsdsdsdz](https://user-images.githubusercontent.com/31524410/52228056-b4aeda00-28f4-11e9-9de1-53eb61cd6d75.PNG)

지금 현재 이러한 에러가 뜨는데요. 새로운 스크립트도 보이지 않아서 지금 해결방법을 모르겠네요. 화 수를 정할 수가 없네요.

**Comment by samfan0429** [comment]
해결이 됐네요. 갑작스럽게 죄송합니다. 근데 망가쇼미 스크립트가 구글 드라이브에 없어서 좀 놀랐습니다. 따로 저장되어 있는 건가요?

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/451#issuecomment-459989236
