### ISSUE TITLE
기본 데이터 다운로드가 안됩니다.

### ISSUE THREAD

**Issue by hitomila** [KurtBestor/Hitomi-Downloader-issues#463]
삭제된 데이터 다운로드는 잘 되지만 기본 데이터 다운로드는 "다운로드중에 실패하였습니다." 와 같은 내용과 함께 다운로드가 되지 않습니다.

**Comment by whgmlqja12** [comment]
히토미 사이트 측에서뭔 짓을 했는지 계속 다운로더 데이터 오류 뜨네요. 윗분처럼 그리고 가끔씩 히토미에는 뜨는데 다운로더 검색하면 안나오는 작가분이 있더군요...

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by Khrist0ph3r** [comment]
테스트 버전으로 받아서 하니 데이터가 잘 받아지네요
