### ISSUE TITLE
소설가가되자 기능중에

### ISSUE THREAD

**Issue by zkzk1209** [KurtBestor/Hitomi-Downloader-issues#464]
소설가가되자 사이트는 자주사용하는사이트라 저한텐 굉장히 좋은기능인거같아요
근데 단편은 다운로드가안되네요 단편은 목차가없어서그런가요?
그리고 혹시 가능하다면 설명글도 같이다운받을수있는 기능추가해주실수있을까요?
마구받아놓다보니 무슨소설인지헷갈려서..

**Comment by KurtBestor** [comment]
링크 알려주시면 확인해볼게요.

**Comment by zkzk1209** [comment]
> 링크 알려주시면 확인해볼게요.

https://ncode.syosetu.com/n8273ds/ 
소설가가되자 단편은 이런식으로 목차없이 바로내용이시작됩니다

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by zkzk1209** [comment]
단편도 문제없이 잘받아집니다
빠른피드감사합니다
