### ISSUE TITLE
업데이트 후 기본 데이터 다운로드 이상 증상

### ISSUE THREAD

**Issue by kazami0208** [KurtBestor/Hitomi-Downloader-issues#466]
2.5d 버전 업데이트후 
문제 발생하였습니다 
![default](https://user-images.githubusercontent.com/47350180/52265205-e10b3a80-2976-11e9-91af-185895733d3e.png)

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/463

**Comment by negoist** [comment]
동일한 증상입니다

**Comment by KurtBestor** [comment]
@negoist 
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/493
