### ISSUE TITLE
lhscan 사이트에서 일부작품 다운이 안되는 현상..

### ISSUE THREAD

**Issue by mnightmoon** [KurtBestor/Hitomi-Downloader-issues#469]
안녕하세요
lhscan 사이트에서 다운하려고 하는데 
https://lhscan.net/manga-tenohira-kaitaku-mura-de-isekai-kenkokuki-fueteku-yome-tachi-to-nonbiri-mujintou-life-raw.html
다운받고 싶은 몇몇 작품들이 다운이 안되는 문제가 있습니다..

**Comment by KurtBestor** [comment]
경로가 길어서 발생하는 문제인데, 억지로 만들면 되긴 하는데 열리지가 않네요:
![image](https://user-images.githubusercontent.com/14768120/52326284-736d1600-2a2b-11e9-9409-e078f86c7819.png)
Windows 버그인 것 같아요.

참고해주세요: https://docs.microsoft.com/en-us/windows/desktop/FileIO/naming-a-file
