### ISSUE TITLE
건의사항.

### ISSUE THREAD

**Issue by xlxlzl123** [KurtBestor/Hitomi-Downloader-issues#47]
띄엄띄엄 이런 저런 태그로 다운 받다가 그냥 작가별로 훑어서 받으려는데요 

제가 다운받고 압축하면 원본 파일 삭제하는 식으로 쓰고 있는데 

몇 개로 실험해보니까 압축을 해서 그런지 이미 받은 것도 일단 받고 나서 압축하려는 과정에서 

삭제하는 것 같더라구요. 

다운 받은 상태 그대로 순정 파일 이름이라는 가정하에 이미 있는건 바로 넘기는 기능은 없나요?

고유 갤러리 넘버를 인식해서 넘어간다던지 해서 하면 좋을 것 같아요

**Comment by KurtBestor** [comment]
음 잘 이해가 안됩니다. 좀 더 쉽게 설명해주실 수 있나요?

**Comment by xlxlzl123** [comment]
쓸데 없는 사족을 뺴면 

다운로더가 이미 있는 파일을 건너띌 줄 알고 받았는데 

폴더에 받고 - 압축 단계를 거치면서 

이미 압추되있는 작품은 이미 있다고 인식을 못하고 자꾸 중복 다운로드를 한다는겁니다.

**Comment by KurtBestor** [comment]
문제가 있나요..?

**Comment by KurtBestor** [comment]
그렇군요. 친절한 설명 감사합니다.

대부분의 사이트는 내용이 변하지 않으니까 좋은 방법인 것 같은데, 트위터나 인스타그램 등은 내용이 변하니 이건 예외로 해서 한다던지 해야겠네요. 더 좋은 방법 있으면 제안 바래요.

**Comment by KurtBestor** [comment]
지금 확인해보니 압축하는 사이트 중에 내용이 변하지 않는 곳은 히토미, 이(ㄱ)헨 밖에 없네요. 이것만 따로 예외처리 할게요.

**Comment by xlxlzl123** [comment]
저도 뭐 덧붙이고 싶긴한데 히토미밖에 안받아서 죄송합니다.

히토미만 받는 놈 입장에서는 그렇다는걸로만 알아주세요

**Comment by KurtBestor** [comment]
넹

**Comment by arsia13** [comment]
해당 이슈에서 중복다운로드 스킵이 있길래 여기에 코멘트를 남겨봅니다.
마루마루 주소를 가지고 한번에 넣어서 다운로드하는데 해당 만화가 업데이트가 되었으면 새로운 화가 추가되어 해당 화만 다운받도록 하고 싶은데요 가능한가요?
