### ISSUE TITLE
info.txt 생성 안됨

### ISSUE THREAD

**Issue by BBulMushroom** [KurtBestor/Hitomi-Downloader-issues#471]
2.5c는 되는데 2.5d에서 히토미 다운로드시
압축설정>zip 체크하면
원본 폴더에는 info 생성되는데 압축폴더에는 안들어갑니다

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by BBulMushroom** [comment]
> 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview
잘되네용
