### ISSUE TITLE
프로그램 질문이요

### ISSUE THREAD

**Issue by MP1402** [KurtBestor/Hitomi-Downloader-issues#472]
저기 혹시 phantomjs가 뭐할때 쓰는건가요? 예전버전에는 없었는데 망가쇼미에서  최근에 나온 만화에 사용하면 어느순간 생기는거 같아서..... 다른 사이트에서 이용하면 안생기던거 같던데...

**Comment by KurtBestor** [comment]
망가쇼미에서 자바스크립트로 암호화해놓아서 자바스크립트 실행하는 용도로 써요.

참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/317

**Comment by MP1402** [comment]
감사합니당 하나 배워가요~
