### ISSUE TITLE
현재 다운로더 업뎃해주셨는데요 질문드립니다

### ISSUE THREAD

**Issue by lacoon12** [KurtBestor/Hitomi-Downloader-issues#474]
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

이파일 받았구요

본 다운로더와 첨부가 각1개씩 두개있던데

첨부파일을 어느 폴더로 압축해제를 해야하는것인가 잘 모르겠습니다 

감사합니다

**Comment by KurtBestor** [comment]
`hitomi_downloader_GUI_test.zip` 안의 실행파일만 이전 실행파일에 덮어씌우시면 돼요.

**Comment by lacoon12** [comment]
말씀하신대로했는데 기본데이터 다운이 실패하네요..

Traceback (most recent call last):
  File "hitomi_searcher", line 203, in download_json
  File "hitomi_searcher", line 370, in download_json_
IndexError: list index out of range

요렇게뜹니다 ㅠㅠ 수고많으세요

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/493
