### ISSUE TITLE
티스토리도 해주실 수 있을까요?

### ISSUE THREAD

**Issue by Yurriii** [KurtBestor/Hitomi-Downloader-issues#477]
뭔가 오자마자부탁만 드린것같아 죄송하지만 가능하다면 부탁드려봅니다

늦었지만 새해 복 많이 받으세요

덕분에 프로그램 잘 이용하고있습니다 ㅎ

**Comment by KurtBestor** [comment]
https://github.com/KurtBestor/Hitomi-Downloader/issues/1280#issuecomment-692370898
