### ISSUE TITLE
newtoki 에서 다운 받으면 회차 이름 앞 뒤에 숫자가 붙어요.

### ISSUE THREAD

**Issue by karnies** [KurtBestor/Hitomi-Downloader-issues#478]
![image](https://user-images.githubusercontent.com/46523031/52396016-864b1d80-2af3-11e9-9227-228124c5fe37.png)

안녕하세요, 감사히 잘 쓰고 있습니다.
다름이 아니라. newtoki 에서 다운 받으면 회차 이름 앞 뒤에 숫자가 붙어요.
수정 가능할까요?

**Comment by KurtBestor** [comment]
스크립트가 오래된 거 같네요. [**여기**](https://drive.google.com/drive/folders/1FP0YZp7QyGDyOQ1nwILRIVT3kd58NYxo)에서 다시 다운로드 해주세요.
