### ISSUE TITLE
마루마루 다운관련 질문이 있어요~

### ISSUE THREAD

**Issue by ghfkddl007** [KurtBestor/Hitomi-Downloader-issues#48]
안녕하세요. 정말 좋은 자료 감사하게 잘 이용하고 잇습니다.
현재 이 좋은 프로그램으로 히토미는 아주 잘 사용하고 있어요 ㅎㅎ
그런데 예전버전부터 현재 2.1 버전 이용중인데
마루마루가 다운이 안되네요..

예를들어 제가 받고 싶은 자료는 "어떻게든 되는 나날" 이 자료이구
주소는 http://wasabisyrup.com/archives/1714683 이 주소입니다.

이상태로하니 lnvalid:http://wasabisyrup.com/archives/1714683
라고 붉은색 글씨로 오류가 뜨면서 안되길래

설명서 다시 읽어보고
http://marumaru.in/b/manga/1714683
이라고 입력해보니
reading error:maru_1714683

라고 붉은 글씨로 오류가 뜨면서 안되네요 ㅠㅠ
혹시해서 다른 작품들도 해봣는데 되는게 없네요
뭐가 문제일까요..

항상 좋은 자료 잘쓰고 있습니다.
제가 놓친부분이 잇으면 알려주시면 더욱 잘 사용할꼐요 ㅠ

**Comment by KurtBestor** [comment]
다음과 같이 목록 주소를 입력해야합니다:
```
http://marumaru.in/b/manga/148089
```
