### ISSUE TITLE
유튜브 영상 다운 시 소리가 나오지 않습니다.

### ISSUE THREAD

**Issue by naninore** [KurtBestor/Hitomi-Downloader-issues#480]
고생이 많으십니다.
제곧내이지만 다시 설명 드리자면 유튜브에서 1080p로 다운을 했는데 그 다운된 영상에서 소리가 나오지 않는 현상이 발견됩니다. 이게 또 모든 영상이 그런 건 아니고 특정 영상은 잘 돌아갑니다. 저로서는 무슨 차이가 있는지는 잘 모르겠습니다. (업로드 날짜 차이가 나거나 조회수차이가 있는 건가 싶었지만 그것도 아닙니다.) 확인 부탁드립니다.
정보 1은 소리가 나오지 않는 영상의 정보고
정보 2는 소리가 나오는 영상의 정보입니다.
대조 부탁드립니다.

[정보1]
[한글화] 보컬로이드들이 2코드를 반복하며 텟테-테렛테-라든지 외칠 뿐

version: 2.5d
platform: Windows-10-10.0.17134
gal_num: https://www.youtube.com/watch?v=OR7AnecryEE&feature=youtu.be
dir: hitomi_downloaded_youtube
zip: 
type: youtube
artist: None
url: https://www.youtube.com/watch?v=OR7AnecryEE&feature=youtu.be
valid: True
done: True
range: None
range_p: None
single: True
time: 1549546624.44 (Feb 7)
tags: []

[Gallery]
None

[File Names]
[0001] hitomi_downloaded_youtube\[한글화] 보컬로이드들이 2코드를 반복하며 텟테-테렛테-라든지 외칠 뿐 (OR7AnecryEE).mp4

[URLs]
[0001] https://r1---sn-3u-bh2d.googlevideo.com/videoplayback?aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278&ip=222.121.101.234&clen=191634336&requiressl=yes&mv=m&source=youtube&fvip=5&ms=au%2Conr&ei=hDRcXJiSG5nPqAG1oI2IDg&itag=137&pl=19&mt=1549546500&sparams=aitags%2Cclen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpcm2cms%2Cpl%2Crequiressl%2Csource%2Cexpire&mn=sn-3u-bh2d%2Csn-i3b7kn7d&mm=31%2C26&expire=1549568228&id=o-ADQ1ZqsILydJyLu3_T2nzroizB98zFa5I8CCz-4wW5fP&keepalive=yes&c=WEB&mime=video%2Fmp4&pcm2cms=yes&gir=yes&txp=5432432&dur=1818.549&key=yt6&lmt=1541010332240164&ipbits=0&initcwndbps=1307500&signature=ABDC5D16711E21EE802472FC8D03043FC0428D1F.C8D876BE0D20161AAE5BFB8DADD21BFC67ED7F4A&ratebypass=yes

[Messages]
[None][50kbps] webm
[None][70kbps] webm
[None][128kbps] m4a
[None][128kbps] webm
[None][160kbps] webm
[144p][None] webm
[144p][None] mp4
[240p][None] webm
[240p][None] mp4
[360p][None] webm
[360p][None] mp4
[480p][None] webm
[480p][None] mp4
[720p][None] webm
[720p][None] mp4
[1080p][None] webm
[1080p][None] mp4
[144p][24kbps] 3gp
[180p][None] 3gp
[360p][128kbps] webm
[360p][96kbps] mp4
[720p][192kbps] mp4

# stream_final <youtube_dl_test.Video object at 0x29FD0F30> 1080p None
# stream_final <youtube_dl_test.Video object at 0x23A05430> 1080p None
Resolution: 1080p
Codec: avc1.640028 / None
Abr: None
Subtype: mp4

Download audio: https://r1---sn-3u-bh2d.googlevideo.com/videoplayback?ip=222.121.101.234&clen=15608176&requiressl=yes&mv=m&source=youtube&fvip=5&ms=au%2Conr&ei=hDRcXJiSG5nPqAG1oI2IDg&itag=250&pl=19&mt=1549546500&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpcm2cms%2Cpl%2Crequiressl%2Csource%2Cexpire&mn=sn-3u-bh2d%2Csn-i3b7kn7d&mm=31%2C26&expire=1549568228&id=o-ADQ1ZqsILydJyLu3_T2nzroizB98zFa5I8CCz-4wW5fP&keepalive=yes&c=WEB&mime=audio%2Fwebm&pcm2cms=yes&gir=yes&txp=5411222&dur=1818.601&key=yt6&lmt=1541016336102961&ipbits=0&initcwndbps=1307500&signature=7A795353ADF812627A29F7952E6D3ECFA593216E.4353510A1F35486DE4428FE90FE0D6392C02AB95&ratebypass=yes
Convert: D:\user\DH\Documents\spacesniffer_1_1_4_0\hitomi_downloader_GUI\hitomi_downloaded_youtube\[한글화] 보컬로이드들이 2코드를 반복하며 텟테-테렛테-라든지 외칠 뿐 (OR7AnecryEE).mp4
rename: D:\user\DH\Documents\spacesniffer_1_1_4_0\hitomi_downloader_GUI\hitomi_downloaded_youtube\[한글화] 보컬로이드들이 2코드를 반복하며 텟테-테렛테-라든지 외칠 뿐 (OR7AnecryEE).mp4 -> D:\user\DH\Documents\spacesniffer_1_1_4_0\hitomi_downloader_GUI\hitomi_downloaded_youtube\tmpA6728EE2_v.mp4
-y -i tmpA6728EE2_a.weba -i tmpA6728EE2_v.mp4 -vcodec copy -acodec copy -strict experimental -preset ultrafast -shortest tmpA6728EE2_o.mp4
[code]
0
[out]
ffmpeg version 4.1 Copyright (c) 2000-2018 the FFmpeg developers
built with gcc 8.2.1 (GCC) 20181017
configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth
libavutil 56. 22.100 / 56. 22.100
libavcodec 58. 35.100 / 58. 35.100
libavformat 58. 20.100 / 58. 20.100
libavdevice 58. 5.100 / 58. 5.100
libavfilter 7. 40.101 / 7. 40.101
libswscale 5. 3.100 / 5. 3.100
libswresample 3. 3.100 / 3. 3.100
libpostproc 55. 3.100 / 55. 3.100
Input #0, matroska,webm, from 'tmpA6728EE2_a.weba':
Metadata:
encoder : google/video-file
Duration: 00:30:18.60, start: -0.007000, bitrate: 68 kb/s
Stream #0:0(eng): Audio: opus, 48000 Hz, stereo, fltp (default)
Input #1, mov,mp4,m4a,3gp,3g2,mj2, from 'tmpA6728EE2_v.mp4':
Metadata:
major_brand : dash
minor_version : 0
compatible_brands: iso6avc1mp41
creation_time : 2018-10-31T18:22:56.000000Z
Duration: 00:30:18.55, start: 0.000000, bitrate: 843 kb/s
Stream #1:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709, progressive), 1920x1080 [SAR 1:1 DAR 16:9], 0 kb/s, 29.97 fps, 29.97 tbr, 90k tbn, 59.94 tbc (default)
Metadata:
creation_time : 2018-10-31T18:22:56.000000Z
handler_name : VideoHandler
[mp4 @ 067d1980] track 1: codec frame size is not set
Output #0, mp4, to 'tmpA6728EE2_o.mp4':
Metadata:
encoder : Lavf58.20.100
Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709, progressive), 1920x1080 [SAR 1:1 DAR 16:9], q=2-31, 0 kb/s, 29.97 fps, 29.97 tbr, 90k tbn, 90k tbc (default)
Metadata:
creation_time : 2018-10-31T18:22:56.000000Z
handler_name : VideoHandler
Stream #0:1(eng): Audio: opus (Opus / 0x7375704F), 48000 Hz, stereo, fltp (default)
Stream mapping:
Stream #1:0 -> #0:0 (copy)
Stream #0:0 -> #0:1 (copy)
Press [q] to stop, [?] for help
frame=35699 fps=0.0 q=-1.0 size= 104448kB time=00:19:51.08 bitrate= 718.4kbits/s speed=2.38e+03x 
frame=54502 fps=0.0 q=-1.0 Lsize= 202785kB time=00:30:18.50 bitrate= 913.5kbits/s speed=2.27e+03x 
video:186466kB audio:14616kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.846974%

Convert success: True
rename: D:\user\DH\Documents\spacesniffer_1_1_4_0\hitomi_downloader_GUI\hitomi_downloaded_youtube\tmpA6728EE2_o.mp4 -> D:\user\DH\Documents\spacesniffer_1_1_4_0\hitomi_downloader_GUI\hitomi_downloaded_youtube\[한글화] 보컬로이드들이 2코드를 반복하며 텟테-테렛테-라든지 외칠 뿐 (OR7AnecryEE).mp4
done : https://www.youtube.com/watch?v=OR7AnecryEE&feature=youtu.be

================================================================
[정보2]
[한글화]보컬로이드들이 그저 텟테 테렛테 할뿐

version: 2.5d
platform: Windows-10-10.0.17134
gal_num: https://www.youtube.com/watch?v=UDK5Lu4QfwE
dir: hitomi_downloaded_youtube
zip: 
type: youtube
artist: None
url: https://www.youtube.com/watch?v=UDK5Lu4QfwE
valid: True
done: True
range: None
range_p: None
single: True
time: 1549498757.39 (Feb 7)
tags: []

[Gallery]
None

[File Names]
[0001] hitomi_downloaded_youtube\[한글화]보컬로이드들이 그저 텟테 테렛테 할뿐 (UDK5Lu4QfwE).mp4

[URLs]
[0001] https://r8---sn-3u-bh2ek.googlevideo.com/videoplayback?source=youtube&mn=sn-3u-bh2ek%2Csn-i3b7knlk&ei=BnpbXJbmJZCUgAO-0ZvwDg&ms=au%2Conr&ipbits=0&mv=m&pl=19&id=o-AMtpPl7a8vLQIF5OhWOm-JPB-fey95LkqkrUuByjwK1i&mm=31%2C26&expire=1549520486&ip=222.121.101.234&pcm2cms=yes&dur=1219.326&lmt=1531973191066179&fvip=3&c=WEB&ratebypass=yes&mt=1549498789&requiressl=yes&initcwndbps=1632500&mime=video%2Fmp4&key=yt6&itag=22&sparams=dur%2Cei%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpcm2cms%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cexpire&signature=7FE0AC5E4BDAF485A56070943B58BD0C60047328.6286694FF691AC21EA1D20AD3B3B144919EC598D

**Comment by KurtBestor** [comment]
어떤 비디오 플레이어 쓰시나요?

**Comment by naninore** [comment]
다음팟플레이어 씁니다. 일부러 카카오버전 아닌거 쓰고 있긴 합니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by naninore** [comment]
잘 작동됩니다.
정말 위대합니다 선생!!
