### ISSUE TITLE
카스퍼스키에서 바이러스로 인식을 합니다

### ISSUE THREAD

**Issue by cancerogenic** [KurtBestor/Hitomi-Downloader-issues#481]
최근 망가쇼미 분할되서 저장되는 버그 업데이트 파일을 다운 결과 카스퍼스키 바이러스가 검출됩니다.

**Comment by KurtBestor** [comment]
저도 커스퍼스키 쓰는데요, 바이러스라고 인식해서 삭제하길래 어제 카스퍼스키에 문의해서 오진이라고 답변 받은 상태예요:
![image](https://user-images.githubusercontent.com/14768120/52417174-9cc29a80-2b2e-11e9-838d-2d8dbcab7d80.png)

DB 업데이트되는데 시간 걸리니 그 동안 다음 파일 써주세요:
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

바이러스토탈 검사 결과예요:
https://www.virustotal.com/#/file/6d513771c39f88942bd96b8d8f9f3fb05e90e5047ae7733c684b6e69491b467b/detection

**Comment by cancerogenic** [comment]
감사합니다
