### ISSUE TITLE
메인 창(홈화면?)에 다운로드 내역이 안나옵니다.

### ISSUE THREAD

**Issue by rosenkavalier00** [KurtBestor/Hitomi-Downloader-issues#482]
항상 감사하며 잘 쓰고 있습니다.

발생한 문제는 다음과 같습니다.

하단 필터 옆의 바는 로딩중이라는 듯이 무한정 파란 바가 지나가기만 합니다.

기본 데이터 다운로드도 안 됐었는데 이건 test버전 사용하는 거로 해결했습니다.

하지만 다운로드 내역은 목록을 지우는 등 이짓저짓 다 해봤는데 변하지 않네요.

어쩌다가 튕긴 이후로 계속 이러는데 해결책이 있을까요?

다운로드 및 검색 등의 기능은 정상적으로 작동합니다.

*저장 폴더에 있는 모든 갤러리 넘버 복사 기능을 수행하면 
"Traceback (most recent call last):
  File "diriter", line 56, in f
IndexError: list index out of range
라면서 일부 실패가 뜨는데 이것도 문제와 관련이 있을까요?

**Comment by KurtBestor** [comment]
실행파일과 같은 폴더에 있는 `*.ini` 파일 보내주시면 분석해볼게요.

**Comment by rosenkavalier00** [comment]
감사합니다. 이 파일이 맞을까요?

>

**Comment by rosenkavalier00** [comment]
어.... 방금 ini 파일을 지우고 재시도 해봤는데 목록이 완전히 날아가긴 했지만 일단 작동이 되네요.. ;;
