### ISSUE TITLE
망가쇼미 파일이 안받아지는 현상이 있네요

### ISSUE THREAD

**Issue by doaldi** [KurtBestor/Hitomi-Downloader-issues#484]
예를들어 1~6화까지 있으면 4,5,6화는 받아지는데 1,2,3화가 안받아지는 현상이 있습니다
전부 그런건 아니고 특정 몇몇 만화가 그러하네요

**Comment by nadesion** [comment]
예를 들자면 드리프터즈의 경우 초반에는 받아지지만 중간에 대략 60화쯤에서 멈춥니다.

**Comment by KurtBestor** [comment]
사이트로 직접 들어가면 보이나요? 안 보이면 망가쇼미 서버 문제예요.
참고해주세요: https://mangashow.me/bbs/board.php?bo_table=msm_free&wr_id=108592
