### ISSUE TITLE
다운로드 폴더를 네트워크 폴더로 지정할수 없을까요?

### ISSUE THREAD

**Issue by Frostpunk** [KurtBestor/Hitomi-Downloader-issues#486]
사정상 가상화에서 쓰고 있습니다.
다운로드 폴더를 \\\VBOXSVR\A 라는 네트웍 폴더로 지정하고 싶은데 설정은 되지만 실제론 저장이 안되네요.
프로그램 디렉토리에 VBOXSVR 폴더가 만들어지고 그 안에 받아지는데 방법이 없을까요?

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/195#issuecomment-416274783
