### ISSUE TITLE
핀터레스트 오류보고입니다

### ISSUE THREAD

**Issue by siwkd2** [KurtBestor/Hitomi-Downloader-issues#487]
핀터레스트를 구동하면 임시 크롬창이 뜨고나서 얼마 안지나 로그인창이뜨면서 

읽는것이 도중에 멈추고 일부만 다운로드하는 현상이 발견되었습니다

나중에 시간이 되시면 업데이트해주시면 감사하겠습니다

**Comment by KurtBestor** [comment]
해당 작업 `마우스 우클릭` - `정보... (I)` 눌러서 나온 내용 보여주세요.
