### ISSUE TITLE
zip 파일 연결프로그램 지정

### ISSUE THREAD

**Issue by CherryDrops** [KurtBestor/Hitomi-Downloader-issues#489]
원본파일을 삭제한 zip 파일은 바로 보기가 어렵습니다.
압축파일 오픈시 연결프로그램 지정이 가능하면 좋겠습니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

`옵션` - `설정` - `고급 설정` - `압축파일 연결 프로그램` 에서 설정하실 수 있어요.

**Comment by CherryDrops** [comment]
정상 동작 확인했습니다.
