### ISSUE TITLE
유튜브 다운로드 문제

### ISSUE THREAD

**Issue by LainM** [KurtBestor/Hitomi-Downloader-issues#49]
2.2버전 업데이트가 있길래 패치 한 후 유튜브 다운로드를 했는데 Failed 오류가 나면서 영상이

안받아지는 현상이 있더라고요.

그런데 보니까 다운로드가 되는 영상도 있고 다운로드 안되는 영상도 2.1b 버전으로 파일을 다시 받은 후

받으니까 다시 정상적으로 다운로드가 되네요

혹시 지금 저만 문제가 있는건가요?

**Comment by KurtBestor** [comment]
모든 영상이 그렇게 되나요?

해당 작업 우클릭 후에 [정보...(I)] 눌러서 나오는 내용 보내주시면 분석해보겠습니다.

**Comment by LainM** [comment]
모든 영상이 그렇게 되는건 아니고 몇개의 영상만 그렇더라고요 !

1시간 정도 혼자서 해결 해보다가 데이터를 다 지워서 해보니까 제대로 해결 됬네요

답변 정말 감사합니다
