### ISSUE TITLE
그리드 필터 추가

### ISSUE THREAD

**Issue by CherryDrops** [KurtBestor/Hitomi-Downloader-issues#491]
아티스트별이나 파일 사이즈 별로 정렬이 필요한 경우가 있습니다.
필터로는 불가능 한 기능인데 작업정보에 있는 컬럼으로 그리드 바 생성이 가능할까요?

![default](https://user-images.githubusercontent.com/47455438/52490012-1e85f700-2c07-11e9-8480-ea1d8e15a532.png)

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

좌측하단 `정렬 기준...` 에서 설정하실 수 있어요.

**Comment by CherryDrops** [comment]
정상 동작 확인했습니다. 피드백 굉장히 빠르시네요!

**Comment by CherryDrops** [comment]
#463 이슈 재발인데,  2.5d에서 #491, #489 기능만 추가 된 프리뷰라 그런가요?

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview
