### ISSUE TITLE
데이터 다운시 오류가 발생합니다

### ISSUE THREAD

**Issue by YTOAA** [KurtBestor/Hitomi-Downloader-issues#493]
Traceback (most recent call last):
  File "hitomi_searcher", line 203, in download_json
  File "hitomi_searcher", line 370, in download_json_
IndexError: list index out of range
그 테스트버전이 된다고 하시길레 다운해서 실행했지만 이런 오류가 뜹니다
삭제된 데이터는 잘 다운받아 집니다
혹시 ini파일 설정 문제일까 삭제하고 실행해봤지만 그래도 다운이 안됩니다

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by YTOAA** [comment]
테스트버전은 다운이 잘됩니다 감사합니다.
