### ISSUE TITLE
기본데이터 다운로드가 안됩니다;;

### ISSUE THREAD

**Issue by codm0720** [KurtBestor/Hitomi-Downloader-issues#494]

**Comment by codm0720** [comment]
![dhfy](https://user-images.githubusercontent.com/47461379/52502756-e42c5200-2c26-11e9-9c8c-bb4143dd74eb.PNG)

**Comment by codm0720** [comment]
왜그럴까요... 잘쓰고잇엇는데 갑자기 이럽니다

**Comment by lacoon12** [comment]
저도 개발자님 새로올려주신거 하려니까 안되네요 ㅠㅠ

**Comment by Khrist0ph3r** [comment]
새로 올려주신 버전으로 됬었는데 2월 9일 오늘자로 다시 안되네요
히토미에서 뭔짓을 한건지

**Comment by ghost242** [comment]
저도 오류가 납니다..

Traceback (most recent call last):
  File "hitomi_searcher", line 203, in download_json
  File "hitomi_searcher", line 370, in download_json_
IndexError: list index out of range

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/493

**Comment by young1756** [comment]
올려주신 최신 참고파일 다운받고 잘됩니다.

**Comment by young1756** [comment]
> 참고해주세요: #493

올려주신 최신 참고파일 다운받고 잘됩니다.
