### ISSUE TITLE
망가쇼미 다운 안됨

### ISSUE THREAD

**Issue by jaejunghan** [KurtBestor/Hitomi-Downloader-issues#495]
https://mangashow.me/bbs/page.php?hid=manga_detail&manga_name=Fate+%2F+stay+night+-Heaven%E2%80%99s+Feel- 다운했는데

총1055장중에 123장만다운되고 진전이 없습니다
[324.txt](https://github.com/KurtBestor/Hitomi-Downloader-issues/files/2847638/324.txt)

**Comment by siwkd2** [comment]
망가쇼미측에서 아예 삭제한거라 다운로드가 안되는겁니다 그외엔 전부 정상 다운로드되요

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/484
