### ISSUE TITLE
제이마나에서 만화 다운로드가 되지 않습니다.

### ISSUE THREAD

**Issue by starspeargirl** [KurtBestor/Hitomi-Downloader-issues#497]
2.5d 버전 사용 중이고요, 쇼미는 지금 이미지가 안 나와서 대체제로 제이마나 주소를 써봤는데 예를 들어

https://www.jmana2.com/book/나의%20히어로%20아카데미아/112497

이걸 복사해서 붙이고 다운로드 버튼을 누르면 주소의 한글이 바뀌면서

목록 주소를 입력해주세요: https://www.jmana2.com/book/%EB%82%98%EC%9D%98%2520%ED%9E%88%EC%96%B4%EB%A1%9C%2520%EC%95%84%EC%B9%B4%EB%8D%B0%EB%AF%B8%EC%95%84/112497

라는 문구와 함께 빨간색 표시가 뜨고 다운로드가 되지 않습니다. 저 변한 링크를 대신 붙여봐도 똑같이 다운로드가 되지 않고요.

또 https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/431 여기서 자체 해결하신 분 말씀대로 개별 회차로 들어가기 전에 목록이 나열되는 창에서 주소를 긁어서 붙여봤는데, 사이트 개편이 된 건지 목록 창에서의 주소도 https://www.jmana2.com/book/나의%20히어로%20아카데미아/112497 로 기존의 주소와 똑같아서 소용이 없습니다.

**Comment by KurtBestor** [comment]
다음과 같이 입력해주세요: https://www.jmana2.com/book/나의%20히어로%20아카데미아

**Comment by starspeargirl** [comment]
아 목록창 자체의 주소를 붙여서 전부 다운로드하는 거였네요.

답변 감사합니다.
