### ISSUE TITLE
히토미 다운로더 데이터 다운로드.

### ISSUE THREAD

**Issue by whgmlqja12** [KurtBestor/Hitomi-Downloader-issues#498]
아침에 새로 올려주신거 받아서 해봤는데 최신업로드된게 안되서 물어봅니다. 다운로드 493 가니까 히토미 파일말고 소스코드 있는데 그건 어떻게 해야하는건가요? 다른사람들은 최신버전 잘 다운받아진다고 하는데 다운받은 정보 시점이 오늘 새벽 기준이후로는 안받아져서 그럽니다.

**Comment by aria1th** [comment]
기본 데이터 다운로드 에러 / (Technical Preview 버전에서)
Traceback (most recent call last):
  File "hitomi_searcher", line 203, in download_json
  File "hitomi_searcher", line 428, in download_json_
Exception: https://ltn.hitomi.la/galleries0.json
WTF

서버 문제인가요?

**Comment by Riadl** [comment]
2월 10일 오전 01:36 기준으로 위와 같은현상이 발생되고 있습니다.

**Comment by blackcherrysd** [comment]
저도 확인해봤는데 같은 현상이네요

**Comment by KurtBestor** [comment]
히토미에서 그동안 전체 갤러리 정보를 제공해줘서 쉽게 받아올 수 있었는데, 이제 없어졌어요.
좀 시간이 걸릴 것 같아요.

**Comment by wakeup5** [comment]
.nozomi라는 데이터를 가져와서 파싱하는 걸로 변경된 것 같습니다.
데이터를 살펴보니 쿼리로 검색된 갤러리 넘버 목록을 쭉 가져옵니다.

해당 코드는 search.js파일의 527번 줄이고, 콘솔에 이렇게 테스트 해봤습니다
```
var area = '';
var tag = 'index';
var language = 'korean';
var nozomi1 = [];
var nozomi_address = '//'+[domain, [tag, language].join('-')].join('/')+nozomiextension;
if (area) {
        nozomi_address = '//'+[domain, area, [tag, language].join('-')].join('/')+nozomiextension;
}

var xhr = new XMLHttpRequest();
xhr.open('GET', nozomi_address, true);
xhr.responseType = "arraybuffer";
xhr.onreadystatechange = function(oEvent) {
        if (xhr.readyState === 4) {
                
                if (xhr.status === 200) {
                        var arrayBuffer = xhr.response; // Note: not oReq.responseText
                        if (arrayBuffer) {
                                var view = new DataView(arrayBuffer);
                                var total = view.byteLength/4;
                                for (var i = 0; i < total; i++) {
                                        nozomi1.push(view.getInt32(i*4, false /* big-endian */));
                                }

                                console.log(nozomi1.length);
                        }
                }
        }
};
xhr.send();
```

**Comment by wakeup5** [comment]
area에는 artist나 series등 검색 키워드가 들어가고 tag에는 검색 내용이 들어가네요. index를 넣으면 전부 가져오는 듯 합니다.

**Comment by KurtBestor** [comment]
@wakeup5 
네, 저도 살펴봤는데 태그 정보도 모두 가져와야 하는데 갤러리 넘버만 가지고는 어떻게 할 수가 없네요.

**Comment by wakeup5** [comment]
@KurtBestor 그렇군요... 태그 정보가 서버에서 html로 변환되어 오긴 하는데 html파싱까지 하기에는 좀 힘들겟죠?

**Comment by KurtBestor** [comment]
그걸 다 읽기엔 너무 오래걸려서 힘들 것 같아요.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by Riadl** [comment]
19-02-11 14:26 데이터 다운로드 기능 정상적으로 작동 됩니다.

**Comment by Riadl** [comment]
19-02-11 14:50 최신자료의 경우 태그 미리보기 기능이 작동되지 않습니다.

**Comment by KurtBestor** [comment]
@Riadl 데이터 다시 다운로드해서 테스트 부탁드려요.

**Comment by Riadl** [comment]
19-02-11 18:49 새로 데이터 다운로드 하고 나니 태그 정보 제대로 불러오네요.
- 14:50분 경에는 다운로드 4~5번 해봤는데 그때는 계속 불러오지 못했습니다.

**Comment by hikari99** [comment]
안녕하세요.
배포하신 프로그램은 아주 잘 쓰고 있습니다.
그런데 이번에 망가쇼미 서버를 이전한것 같아요.
그래서 받을려고 하는데 최신 히토미 다운로더로 해봐도 안되는데 새로운 망가쇼미 서버로 접속해서 다운로드 받을 수 있도록 변경해주시면 안될까요?

https://mangashow2.me/

바뀐 망가쇼미 주소입니다.

**Comment by warabit** [comment]
Traceback (most recent call last):
File "hitomi_downloader_GUI", line 2048, in dataDownload
File "hitomi_searcher", line 312, in download_json
ValueError: Unexpected character found when decoding array value (2)

위에 올려주신 버전으로
19-02-12 23:58 기본 데이터 다운로드 안됩니다.

**Comment by aramath** [comment]
통신사 SK 사용중입니다.
SNI 암호화 한 상태로 이 버전 사용하니 데이터 다운로드 성공했습니다.

**Comment by warabit** [comment]
@aramath kt사용자고 vpn쓰고 있는데 sni암호화랑 차이가 있을런지요.

**Comment by warabit** [comment]
데이터 다 삭제하고 ini 지웠더니 데이터 다운이 됩니다.

**Comment by warabit** [comment]
다시 안됩니다. valueError 계속 나네요
