### ISSUE TITLE
완료되거나 삭제된 목록이 계속 남네요.

### ISSUE THREAD

**Issue by idvel6732** [KurtBestor/Hitomi-Downloader-issues#5]
제목대로 이미 다운로드 완료되서 삭제한 리스트가
종료 후 다시 실행할 때마다 리스트에 남아서 다운로드합니다.

**Comment by KurtBestor** [comment]
@idvel6732 

종료할 때 다음과 같이 저장하고 종료했나요?:
![jeojang](https://user-images.githubusercontent.com/14768120/34149393-3dc8dc3e-e4e8-11e7-8071-79cdb970687e.png)

저장하지 않고 그냥 종료하면 마지막으로 저장한 상태로 남습니다.

**Comment by idvel6732** [comment]
아, 제가 저장&종료 기능을 오해하고 있었네요.
감사합니다 ㅎㅎㅎ
