### ISSUE TITLE
히토미 검색기가 작동하지 않습니다.

### ISSUE THREAD

**Issue by miraclehoshi** [KurtBestor/Hitomi-Downloader-issues#50]
제목란에 키워드를 넣고 검색을 누르면 검색이 되지 않습니다.
제목을 제외한 다른것들은 문제가 없는데, 제목에 뭔가 넣고 검색하면 작동이 안되네요.

다운로더 exe 하나만 남기고 다 지운 후에 다시 데이터 다운로드를 해도 동일합니다.
리포트가 없어 남겨봅니다.

**Comment by RaceDriverMIKU** [comment]
저도 동일 문제 있어요, 태그나 그런건 다 되는데 오직 제목만 안되는거 같네요.

**Comment by KurtBestor** [comment]
아차.. 그러네요.. 해당 버그 패치판입니다:
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/edit/Technical-Preview

**Comment by KurtBestor** [comment]
v2.2a에서 해결 됨
