### ISSUE TITLE
망가쇼미 다운시 invalid 에러가 발생합니다.

### ISSUE THREAD

**Issue by tkfkarkxdmsdhwlddj** [KurtBestor/Hitomi-Downloader-issues#501]
망가쇼미가 2장으로 나뉘어 다운된다는 걸 뒤늦게 알고 최신 테스트버전을 다운받아보았지만 invalid 에러가 뜨면서 다운이 되지 않고 있습니다.
혹시 테스트 버전 다운받을 때 .EXE 파일만 받으면 되는 게 아닌가요?

**Comment by KurtBestor** [comment]
`*.exe` 만 받으면 돼요.
해당 작업 `마우스 우클릭` - `정보... (I)` 눌러서 나온 내용 보여주세요.

**Comment by tkfkarkxdmsdhwlddj** [comment]
Invalid : [mangashow] https://mangashow.me / bbs / board.php?bo_table=msm_manga&wr_id=595704

version: 2.5d
platform: Windows-10-10.0.17134
gal_num: https://mangashow.me/bbs/board.php?bo_table=msm_manga&wr_id=595704
dir: 
zip: 
type: mangashow
artist: None
url: https://mangashow.me/bbs/board.php?bo_table=msm_manga&wr_id=595704
valid: False
done: False
range: None
range_p: None
single: True
time: 1549872669.59 (Feb 11)
tags: []


[Gallery]
None


[File Names]



[URLs]



[Messages]
stop
Traceback (most recent call last):
File "utils", line 371, in __init__
File "mangashow_downloader", line 69, in init
File "mangashow_downloader", line 354, in find_url
IndexError: list index out of range

Fail: mangashow

stop
done : https://mangashow.me/bbs/board.php?bo_table=msm_manga&wr_id=595704

**Comment by tkfkarkxdmsdhwlddj** [comment]
시크릿 DNS를 켜서 다운받아보니 정상작동이 됩니다. 그리고 사진이 반 갈리는 문제는 최신 테스트 버전으로 해본 결과 현재는 문제가 없습니다.
