### ISSUE TITLE
망가쇼미 오류가 이번엔 새로운 문제에 부딪쳤네요

### ISSUE THREAD

**Issue by siwkd2** [KurtBestor/Hitomi-Downloader-issues#502]
정부차원에서 https를 막을줄이야....

아마 프록시 관련 기능을 보완해야하지않을까 싶습니다

인터넷에 올라온 무료 프록시 ip랑 포트를 프록시 입력창에 입력해도 안됩니다

이부분을 업데이트 해주시면 감사하겠습니다

사용된 프록시 ip는 177.131.49.77 포트는3128입니다

다운로드정보입니다

Invalid : [mangashow] https://mangashow.me / bbs / board.php?bo_table=msm_manga&wr_id=595861

version: 2.5d
platform: Windows-7-6.1.7601-SP1
gal_num: https://mangashow.me/bbs/board.php?bo_table=msm_manga&wr_id=595861
dir: 
zip: 
type: mangashow
artist: None
url: https://mangashow.me/bbs/board.php?bo_table=msm_manga&wr_id=595861
valid: False
done: False
range: None
range_p: None
single: True
time: 1549873930.4 (Feb 11)
tags: []

[Gallery]
None

[File Names]

[URLs]

[Messages]
retry...
retry...
retry...
retry...
stop
Traceback (most recent call last):
File "utils", line 370, in __init__
File "mangashow_downloader", line 60, in init
File "downloader", line 292, in read_html
Exception: None

Fail: mangashow

**Comment by samfan0429** [comment]
저도 같은 문제를 대면 중입니다. 확실히 귀찮아졌네요.

**Comment by samfan0429** [comment]
아아 아마도 디도스 프로텍션 때문이 아닌지 한번 조심스럽게 써봅니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview
