### ISSUE TITLE
망가쇼미 다운시 invalid라고 뜨고 다운이 아예 안돼요

### ISSUE THREAD

**Issue by geniussjt** [KurtBestor/Hitomi-Downloader-issues#503]
invalid라고 뜨고 다운이 안되네요..
혹시 무슨 문제라도 있나요?

**Comment by cancerogenic** [comment]
정부가 모든 https 사이트 전면 차단 실시했습니다

**Comment by geniussjt** [comment]
그럼 이제 다운이 안되나요..ㅠ_ㅠ
암튼 답변 감사합니다^^

**Comment by geniussjt** [comment]
cancerogenic님 그럼 해결책은 정녕 없는 건가요?
유튜브 히X미는 다운이 잘 되는데요..
암튼 자꾸 덧글 써서 정말 죄송합니다ㅠㅠ

**Comment by momokoro1** [comment]
눈동자는 아직 안 막혔어요.

**Comment by cancerogenic** [comment]
확인결과 망가쇼미는 막혔고 히X미는 아직 안막혔네요

**Comment by momokoro1** [comment]
눈동자 막혔습니다.
애ㅡ도

**Comment by KurtBestor** [comment]
@geniussjt 해당 작업 `마우스 우클릭` - `정보... (I)` 눌러서 나오는 내용 보여주세요.

**Comment by geniussjt** [comment]
이렇게요...아! 새벽에 다운이 다시 잘되다가 지금 또 안됩니다
Invalid : [mangashow] https://mangashow.me / bbs / board.php?bo_table=msm_manga&wr_id=599149

version: 2.5d
platform: Windows-10-10.0.17134
gal_num: https://mangashow.me/bbs/board.php?bo_table=msm_manga&wr_id=599149
dir: 
zip: 
type: mangashow
artist: None
url: https://mangashow.me/bbs/board.php?bo_table=msm_manga&wr_id=599149
valid: False
done: False
range: None
range_p: None
single: True
time: 1549951662.0 (Feb 12)
tags: []


[Gallery]
None


[File Names]



[URLs]



[Messages]
retry...
retry...
retry...
retry...
stop
Traceback (most recent call last):
File "utils", line 370, in __init__
File "mangashow_downloader", line 60, in init
File "downloader", line 292, in read_html
Exception: None

Fail: mangashow

stop
done : https://mangashow.me/bbs/board.php?bo_table=msm_manga&wr_id=599149

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/515

**Comment by geniussjt** [comment]
답변 대단히 감사합니다^^
