### ISSUE TITLE
히토미 다운로더 현재 상황

### ISSUE THREAD

**Issue by kin9834** [KurtBestor/Hitomi-Downloader-issues#506]
- VPN쓰면 다운로드 잘 됩니다
- 안 막힌 사이트는 그대로 잘 됩니다
- 망가쇼미는 또 위아래 나뉘어서 받아지네요 개씨발 양심도 없는 놈들

**Comment by pitchlatte** [comment]
> * VPN쓰면 다운로드 잘 됩니다
> * 안 막힌 사이트는 그대로 잘 됩니다
> * 망가쇼미는 또 위아래 나뉘어서 받아지네요 개씨발 양심도 없는 놈들

VPN켜고 다운받으니깐 망가쇼미 잘 받아집니다.
참고로 전 크롬에서 BROWSEC 사용합니다.
