### ISSUE TITLE
죄송하지만 질문 하나 드려봅니다.

### ISSUE THREAD

**Issue by oOOSss11** [KurtBestor/Hitomi-Downloader-issues#508]
이 프로그램은 웹 크롤링을 이용하여 데이터를 긁어오는 프로그램인가요?

**Comment by KurtBestor** [comment]
크롤러라기보단 웹 자동화 & 다운로드 툴이에요.

**Comment by oOOSss11** [comment]
감사합니다

**Comment by oOOSss11** [comment]
> 크롤러라기보단 웹 자동화 & 다운로드 툴이에요.

감사합니다, 그렇다면 사진 하나하나 우클릭해서 다운받는 것을 자동으로 해주는 프로그램이라고 생각하면 될까요?

**Comment by KurtBestor** [comment]
넵

**Comment by oOOSss11** [comment]
> 넵

정말 감사합니다!!
