### ISSUE TITLE
다운로드 폴더가 날아갔어요

### ISSUE THREAD

**Issue by crabfoot** [KurtBestor/Hitomi-Downloader-issues#51]
사용하는 도중에 다운완료된 파일이 노란색으로 뜨길래 뭔가 잘못됐나하고 폴더를 열었는데
잘 들어왔더라구요 그래서 나머지도 다 받았습니다.
그 이후에 폴더를 다시 확인하려했는데 download 폴더 자체가 사라져있어요
그러면서 download 주소를 참조할수 없다면서 오류가 떴고요
휴지통 확인해봤지만 없었구요
everything 으로 컴터 뒤져봤는데 어디에도 없습니다.
폴더가 그냥 붕떠서 사라졌는데 왜 그랬는지 원인도 이유도 모르겠습니다.

**Comment by KurtBestor** [comment]
노란색은 설정해둔게 없는데 혹시 주황색 말씀하시는 건가요?
옵션에서 휴지통으로 보내기 체크는 해두셨나요?
혹시 아직 프로그램을 안 껐으면 Ctrl + L 눌러서 나오는 내용 보내주시면 확인해보겠습니다.

**Comment by crabfoot** [comment]
노란색이라고 본게 아마 주황색 맞는거같습니다
삭제시 휴지통으로 보냄은 체크 되어있구요
로그 확인 되는건 이제 알았습니다
이미 종료를해서 로그 날아간거 같네요
다음에 같은 현상이 있으면 저장해 놓겠습니다
그리고 다운로더 런처를 다시키니까 설정값이 전부 디폴트로 돌아가있네요


혹시 몰라서 지금 켰을때 나온 로그를 붙입니다

---------------------------------------------------------------------------------------

Checking for updates... https://goo.gl/WdREc7

뙅캻껏싸뿹렅댸뱶뙻퉠뷒푈긍묬벹립싽턿쒙죩쵳곔둛뉆퉯틔켜삵념틳픀뢦똆쯐뺉쵞튪쟀붻갬읻솸쭷힉뾨펤곱뙭펺줉묽헐선쌭꼍묷뿜툯펵욷웰뎽쮑깩톗흮급꺉뚎땭묏쑌춋꺷맦뛻폖윮삕몠쥣뻋돼갂

Failed to start SingletonApp
Traceback (most recent call last):
  File "hitomi_downloader_GUI", line 52, in <module>
NameError: name 'SingletonApp' is not defined

v2.2 (latest : v2.2)
Encodings: ['cp949', 'mbcs', 'ascii', 'utf-8', 'ascii']
Supported Image Formats: ['bmp', 'pbm', 'pgm', 'png', 'ppm', 'xbm', 'xpm']

**Comment by KurtBestor** [comment]
음.. 이런 상황이 있을수도 있을 것 같아서 삭제하는 코드에 실행파일 폴더나 그 하위 폴더를 삭제하려고하면 에러를 나게 하고 모든 삭제를 멈추게 해뒀었습니다.
혹시 다운로드 폴더를 다른 곳에 해뒀었나요?

**Comment by crabfoot** [comment]
아니요 폴더도 기본생성자리입니다.
따로 폴더 생성하지않고 첫다운로드시에 자동생성되는 자리요
저 그 부분이 이상한게
이미 사용하는도중, 다운로드중이었는데 사라진거에요
작업을 하는도중에 폴더를 지우려고하면, 사용하고 있다고 작업 완료한후에 다시 시도하라고 하잖아요
근데 그런 알림창없이 폴더를 먼저 없애고 다운완료되니까 오류를 띄우네요


상황을 좀더 상세히 말씀드리면
직접 히토미 열람번호를 쳐서 받는 중이었고 애니였습니다.
총3개 중 1개완료 했고 그 다음것 받는도중에 초록색이 아닌 주황색으로 뜨길래 그 때 확인했어요
그때까지는 폴더 열렸고 파일도 확인했습니다.
거기서 상위 폴더로 갔습니다.
2번째 파일 다 받은 후 폴더를 열었더니 폴더 여는 시간이 굉장히 오래걸리면서 3번째 파일 받을때까지 로딩이 걸렸습니다.
3번째 파일 다운완료하는 순간 폴더 사라지면서 위치를 참조할수없다고 오류가 떴습니다.

최대한 상세하게 썼는데 도움이될지 모르겠네요

**Comment by KurtBestor** [comment]
혹시 그 번호가 어떤 건지 알 수 있을까요?

**Comment by crabfoot** [comment]
1번 1115
2번 930
3번 1107
입니다.
[hitomi_downloader_GUI.exe.log](https://github.com/KurtBestor/Hitomi-Downloader-issues/files/1717534/hitomi_downloader_GUI.exe.log)

**Comment by KurtBestor** [comment]
똑같이 다운로드 해봤는데, 똑같은 현상을 재현해볼수가 없네요ㅠ

해당 폴더는 삭제가 안되게 만들어놓았고, 설령 삭제하더라도 휴지통으로 가야하는데 완전 삭제된 이유도 모르겠네요.

일단 시스템 레벨에도 잘못된 폴더를 삭제하려고하면 에러를 띄우는 코드를 넣어 놓겠습니다.

**Comment by crabfoot** [comment]
네 알겠습니다.
신경써주셔서 감사합니다
