### ISSUE TITLE
망가쇼미가 도메인을 변경하였습니다

### ISSUE THREAD

**Issue by siwkd2** [KurtBestor/Hitomi-Downloader-issues#513]
https://mangashow2.me/

오후 1시 38분 부로 망가쇼미2로 변경되었습니다

아마도 막힐때마다 도메인을 변경하는식으로 차단을 피하는거같습니다

앞으로도 자주 도메인이 바뀔거같으니(2->3 이런식으로) 나중에 업데이트하실때

망가쇼미뒤에 붙은 숫자는 변수로 지정하시고 업데이트하시는게 좋은거같습니다

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by siwkd2** [comment]
> 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

작동결과 정상작동됩니다 업데이트해주셔서 감사합니다
