### ISSUE TITLE
pronhub다운로드시

### ISSUE THREAD

**Issue by qwertyasdfq** [KurtBestor/Hitomi-Downloader-issues#514]
개별 영상이 아닌

업로더 비디오란에  있는 영상 전부를 받는것도 가능한가요?

**Comment by KurtBestor** [comment]
현재는 불가능해요.

**Comment by qwertyasdfq** [comment]
답변감사합니다. 프로그램 잘쓰고있어요 항상 감사하게 생각하고있습니디ㅏ.

**Comment by qwertyasdfq** [comment]
> 현재는 불가능해요.
답변감사합니다. 프로그램 잘쓰고있어요 항상 감사하게 생각하고있습니다
