### ISSUE TITLE
VPN, ESNI 안쓰고 간단하게 우회해서 다운받을 수 있는 방법 있어요

### ISSUE THREAD

**Issue by wooeorbs** [KurtBestor/Hitomi-Downloader-issues#515]
널리 알리기 위해 여기서도 씁니다

https://www.dogdrip.net/196003393
https://github.com/ValdikSS/GoodbyeDPI/releases
https://github.com/Include-sys/GUI-for-GoodbyeDPI/releases

특정 웹사이트를 차단하는 인터넷 제공업체에서 사용하는 딥 패킷 검사를 우회하도록 설계한 이 프로그램으로 http, dns, https(SNI)차단을 넘어갈 수 있다고 하네요.

인터넷 속도는 vpn, esni와 달리 영향이 없다고 하네요. 속도 저하가 없어요

자세한 내용은 첫번쨰 링크로 참고하세요.

이 프로그램이 있어야 히토미 다운로더도 다운이 잘 되겠죠?

**Comment by david761276** [comment]
고맙습니다^^

**Comment by KurtBestor** [comment]
GoodbyeDPI가 내장되었어요. 둘 중에 하나만 키셔도 돼요.
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by wooeorbs** [comment]
https://www.dogdrip.net/196505068
https://github.com/kairos0/GUI-for-GoodbyeDPI
https://github.com/kairos0/GUI-for-GoodbyeDPI/releases/download/v1.0.2k/GoodByeDPI_GUI_64Bit.zip
GoodbyeDPI 한글판 나왔어요

**Comment by KurtBestor** [comment]
![image](https://user-images.githubusercontent.com/14768120/52898799-9ff01180-3225-11e9-9b42-4b8b290fd88f.png)
설정에서 키고 끌 수 있어요. 테스트 부탁드려요.
