### ISSUE TITLE
고생 많으십니다.

### ISSUE THREAD

**Issue by mita5549** [KurtBestor/Hitomi-Downloader-issues#516]
갱신

**Comment by KurtBestor** [comment]
다음 링크에서 개발 중인 테스트 버전을 다운받을 수 있어요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by mita5549** [comment]
답변 감사합니다. 
한가지만 더 여쭤볼게요.ㅠㅠ 저 링크에서 계속 갱신 되는 건가요?

**Comment by KurtBestor** [comment]
네
