### ISSUE TITLE
히토미 다운로더 망가쇼미 다운시

### ISSUE THREAD

**Issue by aksghkqhrl** [KurtBestor/Hitomi-Downloader-issues#518]
이미지 순서는 멀쩡한데 부분부분이 절반으로 잘려있는건 무슨문제인가요?

**Comment by mita5549** [comment]
최근에 올라온 버전 써보셨나요?
반토막 나는건 해결 된 거 같은데 또 그러나.ㅠㅠ

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/460

**Comment by aksghkqhrl** [comment]
감사합니다
