### ISSUE TITLE
기존 파일들을 이동/삭제한 상태에서 새 파일들만 받을 수 있게 해주세요

### ISSUE THREAD

**Issue by esotericer1** [KurtBestor/Hitomi-Downloader-issues#519]
안녕하세요. 항상 감사히 잘 쓰고 있습니다. 중복 다운로드 문제와도 겹치는 문제인데, 다운받은 파일들의 일부나 전부를 삭제 혹은 이동 후 새로 다운을 받으면 이전에 다운받은 기록이 있는 것들은 제외하고 새롭게 업로드된 파일만을 다운받도록 할 수는 없을까요? 필요없는 파일들을 다 지워 놨는데 그게 전부 다시 받아지니까 좀 골치아픕니다. 즉, 지금처럼 '다시 시작' 외에도 '새 파일 다운로드' 기능을 추가시켜주셨으면 합니다. 감사합니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview
이제 `다시 시작` 하면 지워진 건 제외하고 받아요.

**Comment by esotericer1** [comment]
잘 됩니다. 빠른 답변 감사합니다! :)

**Comment by esotericer1** [comment]
다른 기존 질문에도 답을 남겼는데 이 이슈가 재발한 것 같네요ㅠㅠ

**Comment by esotericer1** [comment]
아, 추가로 pinterest 다운은 어떻게 하면 되는지도 여쭤봐도 될까요?

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/202
