### ISSUE TITLE
bilibili 다운로드 관련 건의

### ISSUE THREAD

**Issue by roseark** [KurtBestor/Hitomi-Downloader-issues#52]
비리비리에서 영상을 다운 받으려고 하는데

영상이 파트 별(1~4)로 나누어져 있는데, 다운로드를 하면 첫 번째 꺼 만 받아집니다.

https://www.bilibili.com/video/av18937442/?from=search&seid=6382683159951548324

받고자 하는 영상 주소 입니다.

드라마 시디 영상이라 유투브처럼 mp3로 받을 수 있는 기능도 있으면 어떨까 합니다.

**Comment by KurtBestor** [comment]
비리비리에 그런 것도 있는지 첨 알았어요

한번 살펴보도록 할게요.

**Comment by KurtBestor** [comment]
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

테스트 부탁드려요.
