### ISSUE TITLE
마리망에서 여러챕터 있는 작품을 한번에 다운로드 할 수 있을까요?

### ISSUE THREAD

**Issue by lekim56** [KurtBestor/Hitomi-Downloader-issues#520]
여러 챕터가 있는 작품이 같은 제목을 쓰는지라, 1챕터 받고 2챕터 받으면 폴더명이 중복되어서 다운이 되지 않습니다.
그래서 기존에 받은걸 폴더명 바꿔서 다음 챕터를 받아야 하더군요.
한번에 받을 수 있을까요?

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by lekim56** [comment]
> 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

잘 되네요. 감사합니다. ^^

**Comment by lekim56** [comment]
아앗. 안되는게 있어서 몇번 실험해보니, 페이지 상단부에 챕터표시가 있는 작품은 정상적으로 잘 다운 받는데, 페이지 하단부에 챕터가 있는 작품은 다운이 안되네요. ㅠㅠ

**Comment by KurtBestor** [comment]
해당 작품 주소 알려주시면 분석해볼게요.

**Comment by lekim56** [comment]
https://myreadingmanga.info/hachisu-shitsuji-kanzaki-no-yuuutsu-kr/
이런식으로 된 작품은 위쪽의 영어버전만 같이 받아집니다. 챕터페이지는 밑쪽에 있구요.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by lekim56** [comment]
아주 잘 됩니다! 정말 감사합니다. ^^
