### ISSUE TITLE
다운로드 사이트 도메인주소를 일괄변경하는 기능은 추가할 수 없을까요?

### ISSUE THREAD

**Issue by jinjins7** [KurtBestor/Hitomi-Downloader-issues#521]
망가쇼미가 도메인변경을 진행중인데(mangashow.me->mangashow2.me)아마 저 숫자를 빼면 만화 주소들은 전부 일치할 것 같습니다.
제가 만화를 여러개(수십종)를 보고 있어서, 목록에 추가해놓고 한번씩 전부 다시받기 눌러서 업데이트 된것들을 받아서 보고 있습니다.
근데 도메인을 새로 하나하나 일일히 새로 넣으려니 막막합니다....
이전에도 저장전에 날라가거나 저장중에 튕기거나해서 몇번 싹다 새로 입력한 적이 있었거든요...ㅠㅠ
지금은 내보내기도 다 해두고 목록 너무 많지 않도록 2개로 나눠서 따로따로 해서 이제는 튕기지 않고 있습니다만 저 도메인 변경을 다 일일히 해줘야 한다니 너무 막막합니다ㅠㅠ

이번에 변경하는거보니 앞으로도 막히거나 하면 계속 숫자 변경하는식으로 대처할 것 같은데, 혹시
이전주소:xxx
바꿀주소:xdxd
이런식으로 입력을 받아서 목록에 있는 만화 주소를 검사해서, 주소변경을 일괄적으로 진행 시키는 기능을 추가 하는게 가능할까요?

ex/
입력시
이전주소: https://mangashow.me
바꿀주소: https://mangashow2.me

실제 변경
변경전
https://mangashow.me/bbs/page.php?hid=manga_detail&manga_name=%EA%B4%B4%EB%A1%AD%ED%9E%88%EC%A7%80+%EB%A7%90%EC%95%84%EC%A4%98%2C+%EB%82%98%EA%B0%80%ED%86%A0%EB%A1%9C+%EC%96%91
변경후
https://mangashow2.me/bbs/page.php?hid=manga_detail&manga_name=%EA%B4%B4%EB%A1%AD%ED%9E%88%EC%A7%80+%EB%A7%90%EC%95%84%EC%A4%98%2C+%EB%82%98%EA%B0%80%ED%86%A0%EB%A1%9C+%EC%96%91

이렇게 말이죠.
저런식으로 변경되서 목록에 다운완료 되어있는 목록을 전부 새로 다시 입력할 필요없이 일괄변경하는 기능이 있었으면 좋겠습니다..
메모장이나 한글에서 문자열 찾아 바꾸는것이 떠올라서 혹시 목록에서 주소 바꾸기를 이런식으로 하는 기능을 추가하는게 가능하실지 싶어서 문의드립니다.ㅠㅠ

**Comment by jinjins7** [comment]
아 혹시 몰라서 hdt파일 메모장으로 읽어들여서 문자열 바꾸기로 변경한 후, 넣어봤는데 그렇게 해도 바뀌네요ㄷㄷ
일단 급한 불은 끈것같네요....후..

**Comment by KurtBestor** [comment]
https://drive.google.com/drive/folders/1FP0YZp7QyGDyOQ1nwILRIVT3kd58NYxo

위 링크에서 `Tools` / `replace_urls.hds` 스크립트 받아서 쓰시면 돼요.
스크립트 사용법은 `도움말` - `사용법... (F1)` - `스크립트` 를 참고해주세요.

**Comment by jinjins7** [comment]
아앗.. 이런기능이... 감사합니다.
