### ISSUE TITLE
valueerror 나네요. 

### ISSUE THREAD

**Issue by warabit** [KurtBestor/Hitomi-Downloader-issues#522]
Traceback (most recent call last):
  File "hitomi_downloader_GUI", line 2048, in dataDownload
  File "hitomi_searcher", line 312, in download_json
ValueError: Unexpected character found when decoding array value (2)

오류메세지 입니다. 늘 수고하십니다.

**Comment by warabit** [comment]
Traceback (most recent call last):
  File "hitomi_searcher", line 214, in download_json
  File "hitomi_searcher", line 376, in download_json_
Exception: No url_data
03:11에 뜬 오류 메세지입니다. 아예 다른 오류가 떠버리네요.

**Comment by KurtBestor** [comment]
`Ctrl + Alt + C` 눌러서 콘솔 띄우시고 다음 내용 입력해서 나오는 내용 알려주세요:
```
h=hitomi_downloader;print','.join((h.version,h.link,h.feedback,h.url_data))
```

**Comment by warabit** [comment]
2.5d,https://drive.google.com/open?id=0B8iYCPDKWc_NbmhEQkRNekhBNFU,https://github.com/KurtBestor/Hitomi-Downloader-issues/issues,https://kurtbestor.pythonanywhere.com/h_data

라고 나옵니다.
어제는 ini파일이랑 데이더 폴더 지웠을 때는 됐는데 오늘은 그 방법도 안되네요.

**Comment by warabit** [comment]
Traceback (most recent call last):
  File "hitomi_downloader_GUI", line 2046, in dataDownload
  File "hitomi_searcher", line 312, in download_json
ValueError: Unexpected character found when decoding array value (2)
오늘은 이 에러가 뜨네요.

No url_data에러도 한 번 났었는데 어떤 조건에서 그러는지는 잘 모르겠습니다.

**Comment by KurtBestor** [comment]
`hitomi_data` 폴더에 보면 `galleries0.json` ~`galleries19.json` 파일들 있을거예요. 보내주시면 분석해볼게요.

**Comment by warabit** [comment]
여깄습니다

**Comment by warabit** [comment]
[galleries0_pack.zip](https://github.com/KurtBestor/Hitomi-Downloader-issues/files/2858898/galleries0_pack.zip)
[galleries1_pack.zip](https://github.com/KurtBestor/Hitomi-Downloader-issues/files/2858899/galleries1_pack.zip)
[galleries2.zip](https://github.com/KurtBestor/Hitomi-Downloader-issues/files/2858900/galleries2.zip)
[galleries3.zip](https://github.com/KurtBestor/Hitomi-Downloader-issues/files/2858901/galleries3.zip)
[galleries4.zip](https://github.com/KurtBestor/Hitomi-Downloader-issues/files/2858902/galleries4.zip)
[galleries5.zip](https://github.com/KurtBestor/Hitomi-Downloader-issues/files/2858903/galleries5.zip)
[galleries6.zip](https://github.com/KurtBestor/Hitomi-Downloader-issues/files/2858904/galleries6.zip)
[galleries7.zip](https://github.com/KurtBestor/Hitomi-Downloader-issues/files/2858905/galleries7.zip)
[galleries8.zip](https://github.com/KurtBestor/Hitomi-Downloader-issues/files/2858906/galleries8.zip)
[galleries9.zip](https://github.com/KurtBestor/Hitomi-Downloader-issues/files/2858907/galleries9.zip)
[galleries10.zip](https://github.com/KurtBestor/Hitomi-Downloader-issues/files/2858908/galleries10.zip)
[galleries11.zip](https://github.com/KurtBestor/Hitomi-Downloader-issues/files/2858909/galleries11.zip)
[galleries12.zip](https://github.com/KurtBestor/Hitomi-Downloader-issues/files/2858910/galleries12.zip)
[galleries13.zip](https://github.com/KurtBestor/Hitomi-Downloader-issues/files/2858911/galleries13.zip)
[galleries14.zip](https://github.com/KurtBestor/Hitomi-Downloader-issues/files/2858912/galleries14.zip)
[galleries15.zip](https://github.com/KurtBestor/Hitomi-Downloader-issues/files/2858913/galleries15.zip)
[galleries16.zip](https://github.com/KurtBestor/Hitomi-Downloader-issues/files/2858914/galleries16.zip)
[galleries17.zip](https://github.com/KurtBestor/Hitomi-Downloader-issues/files/2858915/galleries17.zip)
[galleries18.zip](https://github.com/KurtBestor/Hitomi-Downloader-issues/files/2858916/galleries18.zip)
[galleries19.zip](https://github.com/KurtBestor/Hitomi-Downloader-issues/files/2858917/galleries19.zip)
수고 많으십니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by warabit** [comment]
정상작동합니다. 감사합니다.
