### ISSUE TITLE
한국어 같은경우 히토미로 링크 다운받으면, 히요비로 전환되서 다운받아 집니다

### ISSUE THREAD

**Issue by jaejunghan** [KurtBestor/Hitomi-Downloader-issues#523]
집에 통신사는 kt이고 dns 우회같은거 안한 방금 포멧한 컴퓨터입니다.

포멧 전에도 우회나 vpn안했는데, 그때는 히토미 링크하면 히토미로 다운받아지는데

지금은 일어나 중국어등은 히토미로 다운받아지나, 한국어는 히요비통해서 다운받아집니다.

혹시 설정이 가능한가요?

추가질문) 이번에 https 접속막는것으로 인해 , 앞으로 히토미나 차단된 사이트는 vpn키고 다운받아야하나요? 혹여나 다운이 되도 속도가 차단되기 전보다  느려지나요? 아그리고 vpn 키고 다운받아도 되나요?

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/515

VPN은 종류에 따라서 프로그램에 적용되지 않을 수 있어요.

**Comment by jaejunghan** [comment]
vpn하고 관련없이 전에는 히토미로 링크하면 히토미로 다운이 됫는데 히요비로 다운이 받아집니다

**Comment by KurtBestor** [comment]
참고해주세요: #515
