### ISSUE TITLE
기본 데이터 다운로드가 안됩니다.

### ISSUE THREAD

**Issue by hanpaboy** [KurtBestor/Hitomi-Downloader-issues#524]
데이터를 다운로드하는 중에 실패했습니다.

라는 메세지와 함께 기본 데이터 다운로드가 안됩니다.

https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/347

위 링크에 첨부된 분이랑 비슷한 케이스인거 같은데 링크에서 https://ltn.hitomi.la/galleries0.json < 이 링크를 들어가면 404ERROR 가 뜨네요.

집 인터넷은 KT입니다.

혹시 몰라서 오류 스크린샷도 첨부합니다.

![alsmdf83jmfasdf](https://user-images.githubusercontent.com/47574567/52661904-68901500-2f46-11e9-9f07-bc2a678f86d2.png)

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/498
