### ISSUE TITLE
replace_urls로 스크립트를 적용했지만 여전히 작동하지 않습니다

### ISSUE THREAD

**Issue by sna0101** [KurtBestor/Hitomi-Downloader-issues#525]
Can not determine type: https://mangashow2.me / bbs / board.php?bo_table=msm_manga&wr_id=604642

이와같은 오류와 함께 다운로드가 되지 않습니다.
뉴토끼의 경우, 스크립트 파일을 메모장으로 열어서 숫자만 2 넣으면 해결 되긴 했습니다만
망가쇼미는 올려주신 replace_urls로 망가쇼미 -> 망가쇼2.미로 바꾸었어도 효과가 없었습니다.

아, url 중 2를 제거하면 정상 다운로드(dns 우회) 되는 걸 보아 relace 스크립트가 작동되지 않은 것 같습니다.
이 경우 제가 직접 메모장으로 수정해도 될 것 같은데요. 어느 부분을 수정해야 하는지 궁금합니다.

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/513
