### ISSUE TITLE
실행 실패, 만화 다운 오류, 

### ISSUE THREAD

**Issue by aksghkqhrl** [KurtBestor/Hitomi-Downloader-issues#526]
지정한 장치, 경로 또는 파일에 액세스할 수 없습니다. 이 항목에 액세스할 수 있는 권한이 없는 것 같습니다. 라는 문구가 높은확률로 나옵니다. 계속 시도하다보면 다시 실행이 됩니다. 어떠한 문제인지가요? 윈도우10 이고 관리자의 권한 사용해도 동일합니다.

그리고 만화를 한번에 예를들어 "원피스" 라고 한다면 1 ~ 300화를 한번에 다운받을시에 간혹 중간에 화가 빠집니다. 만화 사이트 자체에서는 문제가 없는없는걸로 보아 다운로드할때 문제가 생기는거 같습니다. 다시 시도를 해도 항상 같은 화만 빠집니다.

**Comment by KurtBestor** [comment]
다음 테스트 버전으로 시도해보세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview
같은 오류 나오면 해당 작업 `마우스 우클릭` - `작업 정보... (I)` 눌러서 나온 내용 보여주세요.
