### ISSUE TITLE
기능 추가 요청

### ISSUE THREAD

**Issue by andrew3870** [KurtBestor/Hitomi-Downloader-issues#529]
설정에 PDF파일 만들기가 있는데,
사진이랑 PDF파일 둘다 같은 폴더에 따로따로 저장되니 불편하네욥

PDF파일을 만들고 저장을 따로 할수 있도록 해주세요
또한 PDF파일만 만들고 다운받은 사진을 지울 수 있게 하는 기능 추가 부탁드립니다

뭐... 그전에 기본 데이터 받는 문제부터 해결해야..겠죠?

**Comment by KurtBestor** [comment]
참고해주세요: #498, #522
