### ISSUE TITLE
클립보드에서 자동추가가 안되네요

### ISSUE THREAD

**Issue by TurnonHitomi** [KurtBestor/Hitomi-Downloader-issues#53]
주소복사는 되서 나오는데
자동으로 다운목록으로 올라가지않네요

**Comment by KurtBestor** [comment]
버그 패치판입니다:
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by KurtBestor** [comment]
v2.2a에서 해결 됨
