### ISSUE TITLE
실행 오류

### ISSUE THREAD

**Issue by aksghkqhrl** [KurtBestor/Hitomi-Downloader-issues#530]
![20190214_011917](https://user-images.githubusercontent.com/47558641/52726623-e4499a80-2ff6-11e9-8e97-04e36e8c5b25.png)

지정한 장치, 경로 또는 파일에 액세스할 수 없습니다. 문구는 계속 뜨네요.

왜인지는 모르겠으나 될때가있고 안될때가있어서 많이 당황스럽네요 .. 관리자의 권한은 문제가 아닌거같습니다

**Comment by KurtBestor** [comment]
참고해주세요: https://support.microsoft.com/help/2669244
