### ISSUE TITLE
기본다운로드 문제...

### ISSUE THREAD

**Issue by whgmlqja12** [KurtBestor/Hitomi-Downloader-issues#532]
거의 항상 아침 10~11시 사이 기준으로 이후엔 다운이 안되네요.  요즘 매일같이 이러다시피 하는데 요즘들어서. 히토미에서 뭔짓을 하는건지.... 참

**Comment by KurtBestor** [comment]
지금도 그러나요?

**Comment by whgmlqja12** [comment]
방금 확인해봤는데, 지금은 잘 되네요. 기본 데이터 다운로드 텀이 길어진건지 저도 정확히는 잘 모르겠어요. 원래 히토미에 바로 업로드 되고 다운로더로 기본데이터 바로 하면 올라오는 식이었는데 그 텀이 길어졌다고 해야하나요... 암튼 그런거같네요

**Comment by KurtBestor** [comment]
히토미에서 더이상 전체 갤러리 정보를 제공 안해줘서, 제 컴퓨터에서 크롤러 돌리고 서버에 업로드해서 다운로드를 제공해드리고있어요. (서버는 사양이 부족해서)
그래서 제가 컴퓨터를 끄거나 크롤러에서 에러가 생기면 업데이트가 안 돼요.
