### ISSUE TITLE
호두웹툰중에 다운이 안되는 웹툰이 있습니다

### ISSUE THREAD

**Issue by siwkd2** [KurtBestor/Hitomi-Downloader-issues#533]
다운로드되는 웹툰도 있지만

다운로드가 안되고 무한 읽는중이 뜨는경우가 많습니다

이만화 한개뿐만이 아니라 다른 만화에서도 종종 발생합니다

https://hodu34.com/webtoon/list/1971
https://hodu34.com/webtoon/list/1479

다운로드 정보는 다음과 같습니다

-------------------------------------------------------------

읽는 중... https://hodu34.com / webtoon / list / 1971

version: 2.5d
platform: Windows-7-6.1.7601-SP1
gal_num: https://hodu34.com/webtoon/list/1971
dir: 
zip: 
type: hodu
artist: None
url: https://hodu34.com/webtoon/list/1971
valid: True
done: False
range: None
range_p: None
single: False
time: 1550153146.38 (Feb 14)
tags: []

[Gallery]
None

[File Names]

[URLs]

----------------------------------------------------

시간나시면 업데이트 해주시면 감사하겠습니다

**Comment by hhhssj** [comment]
이글을 보고  https://hodu34.com / webtoon / list / 1971 다운해보니 다운 잘됩니다. 참고로 정식 2.5d에서 추가 업데이트 하지않은 정식 2.5d 버전과 최신 스크립트를 사용했습니다.

**Comment by KurtBestor** [comment]
스크립트가 오래된 것 같네요. 다시 받아주세요: https://drive.google.com/drive/folders/1FP0YZp7QyGDyOQ1nwILRIVT3kd58NYxo

**Comment by siwkd2** [comment]
> 스크립트가 오래된 것 같네요. 다시 받아주세요: https://drive.google.com/drive/folders/1FP0YZp7QyGDyOQ1nwILRIVT3kd58NYxo

친절한 답변감사합니다 작동결과 정상작동됩니다
