### ISSUE TITLE
망가쇼미 주소 변경 예정 

### ISSUE THREAD

**Issue by 00junn** [KurtBestor/Hitomi-Downloader-issues#534]
https://mangashow2.me/
이걸로 바뀌는것같습니다.
이 주소로 받아봤더니
can not determine 주소가 뜨네요

엌 누군가 링크한 버전으로 다운받으니 잘되네요..

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/513
