### ISSUE TITLE
앞으로 프로그램에 dpi가 내장되어 나오는건가요? 

### ISSUE THREAD

**Issue by 68958274** [KurtBestor/Hitomi-Downloader-issues#535]
정말 코리안 성자 아닙니까

**Comment by KurtBestor** [comment]
네, 별 문제 없으면 내장되어서 나올거예요.
테스트해보고 결과 알려주시면 개발에 도움될거예요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/515#issuecomment-463518959
