### ISSUE TITLE
bilibili동영상 다운이 안 됩니다....

### ISSUE THREAD

**Issue by vpfxms** [KurtBestor/Hitomi-Downloader-issues#536]
프로그램 다운 받아서 주소 넣어봤는데 다운이 안 되네요....ㅠㅠㅠ혹시 확인 한 번 해주실 수 있나요??

**Comment by KurtBestor** [comment]
비리비리에서 암호화 키를 바꿨네요.
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview
