### ISSUE TITLE
관리자님 서버 관련 문의입니다.

### ISSUE THREAD

**Issue by kikinet88** [KurtBestor/Hitomi-Downloader-issues#537]
일단 히토미 다운로더 를 가장... 많이 쓰는 중인대
리플달린걸 보니 데이터 를 따로 받아서 업로드 하신다 들었습니다.

현제 서버를 관리자님 컴으로 대체하신거 같은대
따로 외부 서버 하나 만들어드리면 거기다 올려서 항시 업데이트 가능하게 할수 있을까요
즉 현제 하는 작업을 전부 오토식으로 될런지 궁금 합니다.

아니면 해당 작업을 좀 알려주시거나

저같은경우 FTP 서버와 일반 윈7 형 서버 또는 노트북을 이용한 24시간 풀타임 서버등
총 3개를 가지고 있습니다.
KT 망을 사용하긴하나 외부 VPN 으로 잡아놔서 큰 문제도 없는듯 하고..

그래서 혹시나 서버 운영체제 또는 기본 사양정도 좀 알았으면 합니다.
그럼 제가 셋팅해서 관리자님에게 원격 아이디 드리면 
추후 관리하시기에도 편하실것이라..

하튼 답변 기다리겠습니다

**Comment by KurtBestor** [comment]
감사합니다!
업로드 & 다운로드용 서버는 따로 있고, 크롤러는 제 컴에서 돌리고 있어요.
크롤러 보내드리면 서버에서 실행시켜주실 수 있나요?
파이썬 스크립트라 운영체제는 상관 없을 것 같고, 메모리는 2GB 정도, 저장공간은 300MB 정도 필요해요.

**Comment by kikinet88** [comment]
관리자님 이메일 주시면 제가 원격 주소와 아이디 패스워드 보내드릴게요
지금 이서버는 메모리 16기가 3930k 쓰고있습니다
정 접속하기 그러시면 이메일로 설치 실행 방법 적어서 보내주시면 하겠습니다

kikinet88@gmail.com

**Comment by mita5549** [comment]
아아 빛 아아..
