### ISSUE TITLE
쇼미에서 만화를 받으면 이미지 맨 오른쪽에 계속 검은 줄이 생겨납니다.

### ISSUE THREAD

**Issue by starspeargirl** [KurtBestor/Hitomi-Downloader-issues#538]
https://mangashow2.me/bbs/board.php?bo_table=msm_manga&wr_id=550684
https://mangashow2.me/bbs/board.php?bo_table=msm_manga&wr_id=613203
https://mangashow2.me/bbs/board.php?bo_table=msm_manga&wr_id=613833
https://mangashow2.me/bbs/board.php?bo_table=msm_manga&wr_id=613007

예전 만화들은 안 그런데 최근에 몇몇 만화들은 다시 받아봐도 특정 페이지들에 검은 줄이 안 없어지네요. 쇼미 홈페이지에서 볼 땐 깨끗하던데 무슨 문제가 있는 건가요.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by starspeargirl** [comment]
이제 검은 줄이 안 보이네요. 감사합니다.

그런데 테스트 버전으로 파일을 바꿔보니 내장된 GoodbyeDPI가 실행되지 않고 이런 글자와 함께 오류가 뜹니다.



---------------------------
Hitomi Downloader
---------------------------
Failed to run GoodbyeDPI
---------------------------
Traceback (most recent call last):
  File "goodbye_dpi", line 56, in run
  File "goodbye_dpi", line 147, in run
  File "subprocess", line 200, in __init__
  File "subprocess", line 375, in _execute_child
UnicodeEncodeError: 'ascii' codec can't encode characters in position 9-11: ordinal not in range(128)

---------------------------
확인   
---------------------------

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by starspeargirl** [comment]
잘 실행되네요. 친절한 답변 감사합니다.

**Comment by starspeargirl** [comment]
제가 착각했네요. 시작될 때 오류가 안 떠서 잘 되는 줄 알았는데 잠시 기다리니까 이런 글자와 함께 오류가 뜹니다.

---------------------------
Hitomi Downloader
---------------------------
Failed to run GoodbyeDPI
---------------------------
Traceback (most recent call last):
  File "goodbye_dpi", line 58, in run
  File "goodbye_dpi", line 166, in run
Exception: Dead: 1

---------------------------
확인   
---------------------------

**Comment by KurtBestor** [comment]
어떤 OS 쓰시나요?

**Comment by starspeargirl** [comment]
네 윈도우 10 쓰고 있습니다.

**Comment by KurtBestor** [comment]
다음 링크에서 GoodbyeDPI 받아서 실행하고 어떤 메시지 나오는 지 알려주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/download/Utils/goodbyedpi.zip

**Comment by starspeargirl** [comment]
GoodbyeDPI v0.1.5: Passive DPI blocker and Active DPI circumvention utility
https://github.com/ValdikSS/GoodbyeDPI

Block passive: 1
Fragment HTTP: 2
Fragment persistent HTTP: 2
Fragment HTTPS: 2
hoSt: 1
Host no space: 1
Additional space: 0
Mix Host: 0
HTTP AllPorts: 0
HTTP Persistent Nowait: 1
DNS redirect: 0
DNSv6 redirect: 0

Opening filter
Error opening filter: The system cannot find the file specified.

**Comment by KurtBestor** [comment]
다음 링크에서 x86_64/goodbyedpi.exe 실행해서 어떤 메시지 나오는지 알려주세요: https://github.com/ValdikSS/GoodbyeDPI/releases/download/0.1.5/goodbyedpi-0.1.5.zip

**Comment by starspeargirl** [comment]
GoodbyeDPI v0.1.5: Passive DPI blocker and Active DPI circumvention utility
https://github.com/ValdikSS/GoodbyeDPI

Block passive: 1
Fragment HTTP: 2
Fragment persistent HTTP: 2
Fragment HTTPS: 2
hoSt: 1
Host no space: 1
Additional space: 0
Mix Host: 0
HTTP AllPorts: 0
HTTP Persistent Nowait: 1
DNS redirect: 0
DNSv6 redirect: 0

Opening filter
Filter activated!

윈도우는 64비트 운영 체제입니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by starspeargirl** [comment]
네 정상적으로 실행되네요. 감사합니다.
