### ISSUE TITLE
네트워크 드라이브에 경로 저장

### ISSUE THREAD

**Issue by nicky707** [KurtBestor/Hitomi-Downloader-issues#539]
안녕하세요. 프로그램 잘사용하고있습니다.

전부터 네트워크 폴더에 실행파일을 넣고 저장중이었는데 며칠전부터 갑자기 저장이 안되더라구요..

폴더 변경 버튼으로 찾아보면 일반 탐색기로는 드라이브가 표시되는데 다운로더 gui에서는 목록에도 보이질않습니다.

에러메세지는 다음과 같이 나오네요.

Fail : \\?\\\192.168.0.5\homes\nicky\Drive\Data\Comic\hitomi_downloaded_mangashow\[우사자키 시로] 액터쥬(act-age)\액터쥬(act-age) 53화\0002.jpg
Traceback (most recent call last):
File "downloader", line 608, in download
IOError: [Errno 22] invalid mode ('wb') or filename: u'\\\\?\\\\\\192.168.0.5\\homes\\nicky\\Drive\\Data\\Comic\\hitomi_downloaded_mangashow\\[\uc6b0\uc0ac\uc790\ud0a4 \uc2dc\ub85c] \uc561\ud130\uc96c(act-age)\\\uc561\ud130\uc96c(act-age) 53\ud654\\0002.jpg'

뭐가 문제일까요 ㅠ

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/195#issuecomment-416274783

**Comment by HukoOo** [comment]
네 링크에 있는것처럼 원래 써오던 중이었는데 갑자기 안되더라구요 ㅠ

**Comment by HukoOo** [comment]
확인해보니 2.5d 릴리즈버전에선 잘되지만 DPI외부프로그램을 따로써야하는군요..
테크니컬 프리뷰버전에선 네트워크 드라이브 폴더경로로 다운이안됩니다 ㅠ

**Comment by nicky707** [comment]
확인해보니 2.5d 릴리즈버전에선 잘되지만 DPI외부프로그램을 따로써야하는군요..
테크니컬 프리뷰버전에선 네트워크 드라이브 폴더경로로 다운이안됩니다 ㅠ

**Comment by KurtBestor** [comment]
v2.5d에선 폴더 변경 목록에서 보이는데 테스트 버전에선 안 보이나요?

**Comment by nicky707** [comment]
넵

**Comment by konceal** [comment]
저도 네트워크 폴더 잘되다가 테스트 버젼에서는 안되네요

**Comment by KurtBestor** [comment]
어떻게 뜨는지 되는 버전이랑 안 되는 버전 스샷 찍어서 보여주실 수 있나요?

**Comment by nicky707** [comment]
2.5d랑 프리뷰 폴더변경버튼 누르면 나오는 탐색기창 비교스샷입니다.

2.5d
![2 5d](https://user-images.githubusercontent.com/47635406/52915598-6c8eaf00-3319-11e9-96f1-f275f5c78681.png)

preview
![preview](https://user-images.githubusercontent.com/47635406/52915599-6d274580-3319-11e9-8370-c7be8b546602.png)

**Comment by KurtBestor** [comment]
관리자권한으로 실행하니 그러네요.
v2.5d 도 관리자권한으로 실행하면 안 보여요.
왜 이럴까요..

**Comment by KurtBestor** [comment]
참고해주세요:
- https://support.microsoft.com/en-us/help/3035277
- http://woshub.com/how-to-access-mapped-network-drives-from-the-elevated-apps

**Comment by nicky707** [comment]
링크 참고하니 프리뷰버전에서도 드라이브가 목록에 보이네요.
그런데 맨위의 에러메세지가 여전히 뜨면서 폴더생성이 안되고 다운로드가 안되네요 ㅠ...

**Comment by KurtBestor** [comment]
레지스트리 바꾸고 재부팅한 거 맞나요?

**Comment by nicky707** [comment]
안녕하세요.
실행파일을 하드드라이브에 넣은채로 저장경로만 네트워크 폴더로 잡아주면 다운이 잘되네요.
예전 처럼 네트워크 폴더에 실행파일을 넣으면 여전히 다운은 안됩니다.
감사합니다.
