### ISSUE TITLE
태그 서치 중 특정 데이터를 불러오지 못해서 크래시가 일어납니다

### ISSUE THREAD

**Issue by aria1th** [KurtBestor/Hitomi-Downloader-issues#54]
txt로 덤프가 안되어있네요

![tag searching](https://user-images.githubusercontent.com/35677394/36133099-9564fcfa-10be-11e8-9172-b14a0497f9d8.PNG)

사용 태그는 female:schoolgirl_uniform, tankoubon 목록을 가져오던 중 발생하며, galleries_7.json을 부르던 중 버그가 발생합니다.

-male:yaoi,-female:scat, -male:scat,-female:mother, -female:futanari, -incomplete, 
 female:schoolgirl_uniform, tankoubon 에서 발생하는데, big_breasts 태그는 포함하거나 포함하지 않거나 넣으면 오류가 발생하지 않네요. 

![7](https://user-images.githubusercontent.com/35677394/36133196-768c1e84-10bf-11e8-8c75-fa2a0ef39508.PNG)

**Comment by KurtBestor** [comment]
테스트 해보니 해당 태그 + 데이터에는 문제가 없습니다.
아마 메모리가 부족해서 꺼지는 것일거에요. 다운로더 오른쪽 아래에 보면 메모리 사용량이 보입니다. 이게 100% 근처로 가면 OS에서 프로그램을 종료시킬겁니다.
검색 속도가 느릴 때는 눈치를 못 챘는데, 메모리 누수가 있네요.
조만간 메모리 누수 고치도록 하겠습니다.

**Comment by KurtBestor** [comment]
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview
고친 버전입니다. 테스트 부탁드려요.

**Comment by KurtBestor** [comment]
v2.2a에서 해결 됨
