### ISSUE TITLE
고생많으십니다.. 니코니코동화 영상은 이제 다운로드 못받나요..?

### ISSUE THREAD

**Issue by zeldin001** [KurtBestor/Hitomi-Downloader-issues#544]
테스트버젼, goodbyedpi 다 시도해봐도 invalid : [nico] https://www.nicovideo.jp/watch/sm~~~~~  로 뜹니다 ㅜㅜ..

**Comment by KurtBestor** [comment]
해당 작업 `마우스 우클릭` - `정보... (I)` 눌러서 나온 내용 보여주세요.

**Comment by zeldin001** [comment]
Invalid : [nico] https://www.nicovideo.jp / watch / sm34635739

version: 2.5d
platform: Windows-10-10.0.17134
gal_num: https://www.nicovideo.jp/watch/sm34635739
dir: 
zip: 
type: nico
artist: None
url: https://www.nicovideo.jp/watch/sm34635739
valid: False
done: False
range: None
range_p: None
single: True
time: 1550440411.48 (Feb 18)
tags: []


[Gallery]
None


[File Names]



[URLs]



[Messages]
'http'
stop
Traceback (most recent call last):
File "utils", line 490, in start
File "utils", line 534, in start_
File "nico_downloader4", line 65, in read
File "nico_downloader4", line 83, in get_video
File "nndownload", line 164, in request_video
File "nndownload", line 397, in perform_api_request
KeyError: 'http'

Fail: nico

done : https://www.nicovideo.jp/watch/sm34635739

이렇게뜹니다.

**Comment by KurtBestor** [comment]
다음 테스트 버전으로 실행해서 실패하면 해당 작업 `마우스 우클릭` - `정보... (I)` 눌러서 나온 내용 보여주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by zeldin001** [comment]
되는것 확인했습니다. 정말 감사합니다 !
