### ISSUE TITLE
기능 건의사항

### ISSUE THREAD

**Issue by aksghkqhrl** [KurtBestor/Hitomi-Downloader-issues#545]
![20190217_002520](https://user-images.githubusercontent.com/47558641/52901768-f02d9a80-324a-11e9-96d2-34b33e11408b.png)

편집한 이지미와 비슷하게 받았던 화를 표시하는것과

같은 만화의 내용으로 이전에는 몇화를 받았는지가 나오면 좋을거같습니다.

그리고 화에서 이미지가 빠질경우 어떤화에서 이미지 오류가있어서 빠진건지도 나오면 좋을거같습니다. 홈페이지 자체에서 이미지 오류가있어서 안나오는경우 따로 찾기가 힘든경우가 있습니다.

**Comment by KurtBestor** [comment]
해당 작업 `마우스 우클릭` - `정보... (I)` 눌러서 `[File Names]` 섹션에 보면 다운로드 안 된 파일은 빨간색으로 나와요. 또 오류 메시지는 `[Messages]` 섹션을 보시면 돼요.
