### ISSUE TITLE
다운로더 dpi 우회 오류 질문드립니다

### ISSUE THREAD

**Issue by maplelime** [KurtBestor/Hitomi-Downloader-issues#546]
![default](https://user-images.githubusercontent.com/47696251/52902508-e4df6c80-3254-11e9-826c-d7e8f8f82dcf.PNG)

dpi 우회 업데이트 된 버전으로 해봤는데 저 오류창이 계속 뜨네요. 혹시 해결방법 알고계신가요?

**Comment by KurtBestor** [comment]
확인 눌러도 계속 뜨나요?

**Comment by maplelime** [comment]
> 확인 눌러도 계속 뜨나요?

네 다운로더를 지우고 재설치도 해봤는데 계속 뜹니다

**Comment by KurtBestor** [comment]
실행했을 때 한번만 뜨는 게 아니라 프로그램을 사용하지 못하게 계속 뜨나요?

**Comment by maplelime** [comment]
옵션에서 DPI 우회 클릭시 저 창이 뜨면서 다시 DPI 우회가 꺼집니다. 그 외의 다운로더 기능들은 정상적으로 작동합니다.

**Comment by KurtBestor** [comment]
[GoodbyeDPI](https://github.com/ValdikSS/GoodbyeDPI)가 Windows7 미만은 지원하지 않아서 그래요.

**Comment by maplelime** [comment]
> [GoodbyeDPI](https://github.com/ValdikSS/GoodbyeDPI)가 Windows7 미만은 지원하지 않아서 그래요.

윈도우 7인데 저 창이 뜨는건 윈도우 업데이트가 덜 되어있어서 그런걸까요?

**Comment by KurtBestor** [comment]
테마는 일부러 비스타로 하신건가요?
Windows7은 KB3033929 업데이트를 받으셔야해요.
참고해주세요: https://reqrypt.org/windivert.html

**Comment by maplelime** [comment]
> 테마는 일부러 비스타로 하신건가요?
> Windows7은 KB3033929 업데이트를 받으셔야해요.
> 참고해주세요: https://reqrypt.org/windivert.html

답변 감사합니다
