### ISSUE TITLE
뉴토끼가 더이상 다운이 안되네요 ㅠㅠ

### ISSUE THREAD

**Issue by ak156** [KurtBestor/Hitomi-Downloader-issues#547]
웹툰쪽은 .com으로 바껴있구

Can not determine type: https://newtoki2.com / webtoon / 136709 / %EC%BF%A0%EB%B2%A0%EB%9D%BC

version: 2.5d
platform: Windows-10-10.0.17134
gal_num: https://newtoki2.com/webtoon/136709/%EC%BF%A0%EB%B2%A0%EB%9D%BC
dir: 
zip: 
type: 
artist: None
url: https://newtoki2.com/webtoon/136709/%EC%BF%A0%EB%B2%A0%EB%9D%BC
valid: False
done: False
range: None
range_p: None
single: True
time: 1550392414.02 (Feb 17)
tags: []

[Gallery]
None

[File Names]

[URLs]

[Messages]
Traceback (most recent call last):
File "hitomi_downloader_GUI", line 1199, in run
File "utils", line 195, in pop
IndexError

Fail: 

done : https://newtoki2.com/webtoon/136709/%EC%BF%A0%EB%B2%A0%EB%9D%BC

요러면서 안되고

만화쪽은 .net로 바뀐뒤
Can not determine type: https://newtoki2.net / comic / 113325

version: 2.5d
platform: Windows-10-10.0.17134
gal_num: https://newtoki2.net/comic/113325
dir: 
zip: 
type: 
artist: None
url: https://newtoki2.net/comic/113325
valid: False
done: False
range: None
range_p: None
single: True
time: 1550392467.88 (Feb 17)
tags: []

[Gallery]
None

[File Names]

[URLs]

[Messages]
Traceback (most recent call last):
File "hitomi_downloader_GUI", line 1199, in run
File "utils", line 195, in pop
IndexError

Fail: 

done : https://newtoki2.net/comic/113325
라면서 안되네요 주소가 2로 바뀌어서 그런건가요?

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/505

**Comment by ak156** [comment]
항상 감사합니다~ 잘되네요^^
