### ISSUE TITLE
마루마루2 다운로드 추가 부탁드립니다.

### ISSUE THREAD

**Issue by kaze4639** [KurtBestor/Hitomi-Downloader-issues#549]
초기부터 추가되있던 마루마루 사이트가 없어졌다

다시 사이트를 오픈하였습니다. 밑에 주소입니다.

주소는 https://marumaru01.com/ 입니다.

다운로드 추가 부탁드립니다.

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/468
