### ISSUE TITLE
요근래 다운로드가 제대로 안되네요.

### ISSUE THREAD

**Issue by idvel6732** [KurtBestor/Hitomi-Downloader-issues#55]
![bandicam 2018-02-13 22-08-53-994](https://user-images.githubusercontent.com/34673734/36151457-98d46f0a-110a-11e8-9a39-b86ac1b70f99.jpg)

익헨에서 쓰고 있는대요.
적게는 한두페이지, 많게는 5~10페이지 정도 남기고 불완전 다운로드로 넘어가고
재다운로드해도 계속 반복입니다.

또한 다운로드 한 파일 중에서도 온전하게 다운로드가 안되네요.

**Comment by KurtBestor** [comment]
나중에 좀 더 안정적으로 받게 고치려고 합니다. 지금 좀 바빠서 시간 내기가 어렵네요..

해당 갤러리(1184377)는 이제 히토미에도 올라와서 삭제하신뒤에 다시 받으시면 되겠습니다.
