### ISSUE TITLE
사이트 추가 건의 드립니다

### ISSUE THREAD

**Issue by rainabc** [KurtBestor/Hitomi-Downloader-issues#550]
https://toonkor.blue 웹툰 사이트인데 현재 등록된 사이트에 없는것도 종종있고 여기저기서
많이 퍼오는 사이트라 개인적으로 잘쓰고 있어서 부탁드려봅니다

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/404
