### ISSUE TITLE
사이트 추가 건의드립니다 - 모에니

### ISSUE THREAD

**Issue by daenan** [KurtBestor/Hitomi-Downloader-issues#551]
moeni.org

ani24와 다르게 자막 인코딩이 안되있는 곳이라...
가능하시면 추가건의 드립니다

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://drive.google.com/drive/folders/1FP0YZp7QyGDyOQ1nwILRIVT3kd58NYxo

`moeni.hds` 파일이에요.

**Comment by daenan** [comment]
잘 됩니다! 감사합니다!

**Comment by dox987** [comment]
> 테스트 부탁드려요: https://drive.google.com/drive/folders/1FP0YZp7QyGDyOQ1nwILRIVT3kd58NYxo
> 
> `moeni.hds` 파일이에요.

저도 hds받을수 있나요
