### ISSUE TITLE
관리자님 문의

### ISSUE THREAD

**Issue by kikinet88** [KurtBestor/Hitomi-Downloader-issues#552]
현제 서버에서 크롤러 잘돌아가고 있습니다.

하지만 해당서버 작업이 필요하여 오프를 해야 하다보니

노트북형 나스 서버 에서 크롤러 365일 켜둘 생각을 가지고 있습니다.

i5 - 3337U
8G Ram x2
80GB SSD Sata 3.5

해당 노트북은 고장 제품 구해서 직접 고쳐서 24시간 365일 풀타임으로 돌리려고
제작 했습니다.
(바로 어제 -_-)

배터리 웨어율도 높고 해서 혹시나 정전 대비 UPS 겸으로 해서 저전력으로 굴러가게 해놨는대
네트워크 작업만 좀 하고 이메일로 어드민 보내드릴테니 여기다 작업 해주실수 있는지 ..

일시는 02월 20일 00시 부터 가능합니다.

그리고 해당 서버는 관리자님 마음대로 작업 용으로 쓰셔도 됩니다.

관리자님 전용 으로 만들거니까...

**Comment by KurtBestor** [comment]
넵 준비 다 되면 알려주세요!
감사합니다.
