### ISSUE TITLE
프로그램이 비정상종료 됩니당

### ISSUE THREAD

**Issue by natoom** [KurtBestor/Hitomi-Downloader-issues#554]
안녕하세요. 먼저 그동안 너무 잘 써와서 감사인사 드립니다. 꾸벅!!
다름이 아니오라.. 제가 2.5a 버전까지는 잘 써왔는데
b, c, d 버전은 쓰면 항상 비정상종료가 됩니다.

히토미를 주로 쓰는데 다른 사이트들도 다 마찬가지구요.
읽는 중... 은 정상적으로 진행하고요, 그 다음에 실제 이미지들을 다운로드 받다가
**Hitomi Downloader의 작동이 중지되었습니다.** 이렇게 뜹니다. 100% 항상요.
다운로드 받은 폴더 가보면 이미지들이 다운받다가 멈춰있스빈다.

그때 팝업에서 뜨는 문제 정보는 다음과 같습니다.  (아래 첨부)
다른 만화주소에 대해서 해보니 "예외 오프셋"만 다르고 다른 값은 모두 같네요.
제가 해볼수 있는 설정이 쓰레드 조절밖에 없어서 해봤는데 별 차이는 없습니당. ㅠ.ㅠ

버전이 올라가면 저절로 해결되겠지 했는데
이건 아무래도 제 컴퓨터의 문제 같은데 뭐가 문제인지 모르겠습니다.
도움을 주시면 감사하겠습니다. 부탁드립니다.
저도 히토미 다운로더 최신버전 쓰고시퍼요!!!!
아무튼 개발하시고 기여하시는 모든 분들께 다시한번 감사드립니다.
고맙습니다.. 만수무강 하셔야해요.. 좋은 밤 되시구요..

--------------------------------------------------------------------------------------
문제 서명:
  문제 이벤트 이름:	APPCRASH
  응용 프로그램 이름:	hitomi_downloader_GUI.exe
  응용 프로그램 버전:	2.5.4.0
  응용 프로그램 타임스탬프:	49180193
  오류 모듈 이름:	StackHash_0a9e
  오류 모듈 버전:	0.0.0.0
  오류 모듈 타임스탬프:	00000000
  예외 코드:	c000001d
  예외 오프셋:	050e062f
  OS 버전:	6.1.7600.2.0.0.256.49
  로캘 ID:	1042
  추가 정보 1:	0a9e
  추가 정보 2:	0a9e372d3b4ad19135b953a78882e789
  추가 정보 3:	0a9e
  추가 정보 4:	0a9e372d3b4ad19135b953a78882e789

--------------------------------------------------------------------------------------
문제 서명:
  문제 이벤트 이름:	APPCRASH
  응용 프로그램 이름:	hitomi_downloader_GUI.exe
  응용 프로그램 버전:	2.5.4.0
  응용 프로그램 타임스탬프:	49180193
  오류 모듈 이름:	StackHash_0a9e
  오류 모듈 버전:	0.0.0.0
  오류 모듈 타임스탬프:	00000000
  예외 코드:	c000001d
  예외 오프셋:	0467062f
  OS 버전:	6.1.7600.2.0.0.256.49
  로캘 ID:	1042
  추가 정보 1:	0a9e
  추가 정보 2:	0a9e372d3b4ad19135b953a78882e789
  추가 정보 3:	0a9e
  추가 정보 4:	0a9e372d3b4ad19135b953a78882e789

**Comment by KurtBestor** [comment]
해당 버전 코드 비교해봤는데 딱히 나오는 건 없네요.
검색기에서 데이터를 다운로드하거나 검색할 때는 오류 안 생기나요?

**Comment by natoom** [comment]
네. URL을 입력하세요 라고 쓰여있는 창에
히토미 등 만화 주소 넣어서 받기 버튼 클릭 하면
읽는 중.... 여기는 정상적으로 처리됩니다. 항상 거기는 넘어가구요.
그 담에 실제로 이미지 받는 과정에서 비정상종료됩니다.
그래서 다운폴더 (hitomi_downloaded/해당만화/) 거기 가보면
만화 받다가 만 이미지들이 있습니다. 잘 받아진 것들도 있고
받다 말아서 깨진 파일들도 많구요..

히토미도 그렇고, 오늘 뉴토끼도 해보니까 그렇구요.
얼마전에 망가쇼미도 URL 바뀌기 전에 해보니까 역시 똑같은 증상이었습니당.

**Comment by natoom** [comment]
아 혹시 
검색기... 라는게 제가 모르는 뭔가 다른건가요? 검색창으로 이해했는데

**Comment by KurtBestor** [comment]
`메뉴` - `검색기...` 눌러서 `삭제된 데이터` 체크하고 검색해보세요.

**Comment by KurtBestor** [comment]
v2.5는 다운로드 제대로 되나요?

**Comment by natoom** [comment]
앗 그사이 댓글 달아주셨군요.. 제가 계속 해보면서 제 댓글 내용 수정했습니당 ^^
페이지 리로드 부탁드립니당!

**Comment by natoom** [comment]
넵 v2.5a 에서는 만화 다운로드 정상적으로 잘 쓰고 있습니다.
검색기에서 기본데이터 다운로드는 안되지만 삭제된 데이터다운로드 해서
거기서 검색하는것도 별 문제없이 잘 되네요.

**Comment by KurtBestor** [comment]
v2.5a 말고 v2.5요.

**Comment by natoom** [comment]
전에 받아둔 v2.5 지금 압축풀고 실행해보니 만화다운로드 잘 되구여.
검색기에서는 기본데이터다운로드는 안되구요
삭제된데이터다운로드는 잘 되고, 삭제된데이터에서 검색도 잘 됩니다.
비정상종료 그런거 없이 다 잘 됩니다.

**Comment by KurtBestor** [comment]
어떤 OS 쓰시나요?

**Comment by natoom** [comment]
windows 7 professional KN 입니당. 64비트이고
업데이트는 못했어요. 즉 sp1이 아닙니당.  업데이트 오류가 자꾸나서...
Intel Core i5-4200U, 메모리 4GB 입니당.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by natoom** [comment]
만화 다운로드 실행하니 처음에 Failed to run GoodbyeDPI 라는 줄로 시작하는 커다란 팝업이 떴습니다.
확인 누르니 정상적으로 다운로드 되었고,
다른 만화를 또 다운로드 하니 이번에는 그 팝업이 뜨지 않고 만화 정상적으로 잘 받아졌습니다!!

그리고 검색기에서 기본데이터, 삭제된 데이터 다 잘 받아지고
기본데이터에서 검색 실행해보니 비정상종료되지않고 잘 검색됩니다.

이 팝업 내용이 필요하시면 올려드릴게요. 캡쳐는 했는데 댓글로 이미지 올리는게 안되는거 같아요

**Comment by KurtBestor** [comment]
댓글에 이미지 드래그 드랍 하시면 올려져요.

**Comment by natoom** [comment]
![1](https://user-images.githubusercontent.com/47781262/53031263-d9d44880-34af-11e9-9839-09f91c1066d5.jpg)

**Comment by KurtBestor** [comment]
적힌대로 KB3033929 업데이트를 해야 DPI 우회를 할 수 있는데, 업데이트 못 한다고 하시니 그냥 그대로 사용하셔도 될 것 같아요.

**Comment by natoom** [comment]
역시 제 문제였군요 ㅠ.ㅠ 늦은 밤에 번거롭거롭게 해드려 죄송하고
정말 감사드립니다.
