### ISSUE TITLE
다운로더 dpi 우회 설정 관련 질문입니다.

### ISSUE THREAD

**Issue by nerere** [KurtBestor/Hitomi-Downloader-issues#556]
![11](https://user-images.githubusercontent.com/47818120/53090666-7ac80f80-3553-11e9-8c91-6aa3a7a023a4.png)

안녕하세요, 먼저 항상 노고에 감사드린다는 말씀 전하고 싶습니다. 덕분에 편하게 이용할 수가 있어요.
작성자님께서 다운로더에 dpi를 추가해주셔서 실행해 봤는데 위와같은 창이 뜨고 dpi우회가 적용되지 않습니다. 어떠한 문제 때문에 이렇게 되었는지 궁금합니다. # # @

**Comment by KurtBestor** [comment]
재부팅 해보시고 그래도 안되면 `c:\users\user\appdata\local\temp\WinDivert64.sys` 있는지 확인해주실래요?

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by nerere** [comment]
답변이 늦어서 죄송합니다. 지금 확인해 봤는데 제대로 작동합니다! 언제나 노고에 감사드려요!
