### ISSUE TITLE
VPN 병합 문의

### ISSUE THREAD

**Issue by kikinet88** [KurtBestor/Hitomi-Downloader-issues#559]
관리자님도 아시다싶이 저는 외부 VPN 서버를 따로 가지고 있습니다.
VPN 서버 위치는 일본 , 미국(LA) 등 두곳에 배치되어 있고 항시 가동 서버로 굴러가고 있습니다.

현제 히토미 다운로더 에다가 VPN 을 병합할수 있는지 궁금 합니다.

해당 서버들은 저의 개인 소유 이고 각 국가별 설치 위치도 저의 자산이므로
전혀 문제가 없을걸로 생각됩니다.

VPN 서버 와 통신망 데이터 우회 까지 병합되어 있어서
아마도 접속 외부 주소만 병합하면 될듯 한대..

한국정부가 이따구로 할걸 2년전부터 준비 해왔는대.. 정작 닥쳐오니.. 제가 할 시간이 안나네요..

**Comment by KurtBestor** [comment]
감사합니다.

아직은 GoodbyeDPI으로 우회가 잘 되어서 괜찮을 것 같아요.
나중에 이것도 안 먹히는 신기술이 나와서 막힌다면 부탁드려요.
