### ISSUE TITLE
예전 1.9d 이외 버전 안됬다고 말씀드렸던 사용자입니다.

### ISSUE THREAD

**Issue by tifh2002** [KurtBestor/Hitomi-Downloader-issues#56]
한동안 못해서 답변을 못했었습니다.
1.9d 다음 버전부터 2.2까지 모두 실행이 안되네요.
작업관리자에는 실행이 되나 실제 화면에는 실행이 안됩니다.
화면 표시 문제인지 잘모르겠으나 2.2 이외 낮은 버전사용시 최신버전 업데이트 확인질문 나올때
나오는 사운드가 나오기는 합니다.

**Comment by tifh2002** [comment]
1.9d버전이나 옛날 버전은 이상없이 작동됩니다.

**Comment by KurtBestor** [comment]
이건 잘 되나요?:
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by tifh2002** [comment]
링크 설어주신것도 작업관리자에는 뜨나 실제 창은 뜨질 않습니다.

**Comment by KurtBestor** [comment]
이거 실행해보시면:
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

win_pos.txt 파일이 실행파일이 있는 폴더에 생길겁니다. 내용 보내주시면 감사하겠습니다.

**Comment by tifh2002** [comment]
win_pos.txt 파일이 생성되지가 않네요

**Comment by KurtBestor** [comment]
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/download/Utils/start.bat
이걸 같은 폴더에 넣고 "start.bat"을 실행시켜보실래요?

**Comment by tifh2002** [comment]
start.bat 넣고 실행 해 보아도 아되네요...
뭐가문제인지.. 1.9d랑 다른버전과 뭐가문제인지 모르겠으나 제 컴퓨터 문제인가 보네요 다른 사람들은 잘 실행되는걸보면.. 그냥 1.9d로 다운 받아야 겠네요..시간 빼앗아서 죄송합니다 ㅜㅜ
