### ISSUE TITLE
제이마나 갑자기 다운 안됩니다.

### ISSUE THREAD

**Issue by zeninter** [KurtBestor/Hitomi-Downloader-issues#560]
아까 몇개  다운 받았었는데,
갑자기 그 뒤부터
다운이 안됩니다.
오른쪽에 보면 계속 0p로 나오네요.
몇번을 해봐도 다른 것을 다운 받아도 다 0p로 나옵니다.
왜 그럴까요?
저만 다운 못받게 무슨 조치를 했을까요? ㅠ.ㅠ

ㅡㅡㅡㅡㅡ밑에 정보

[모리 타이시] 오늘의 아스카 쇼

version: 2.5d
platform: Windows-7-6.1.7601-SP1
gal_num: https://jmana4.com/book/%EC%98%A4%EB%8A%98%EC%9D%98%20%EC%95%84%EC%8A%A4%EC%B9%B4%20%EC%87%BC
dir: hitomi_downloaded_jmana\[모리 타이시] 오늘의 아스카 쇼
zip: 
type: jmana
artist: 모리 타이시
url: https://jmana4.com/book/%EC%98%A4%EB%8A%98%EC%9D%98%20%EC%95%84%EC%8A%A4%EC%B9%B4%20%EC%87%BC
valid: True
done: True
range: None
range_p: None
single: False
time: 1550797262.21 (Feb 22)
tags: []

[Gallery]
None

[File Names]

[URLs]

[Messages]
done : https://jmana4.com/book/%EC%98%A4%EB%8A%98%EC%9D%98%20%EC%95%84%EC%8A%A4%EC%B9%B4%20%EC%87%BC

ㅡㅡㅡㅡㅡ 이렇게 뜨네요.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by zeninter** [comment]
> 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

테스트 해봤더니
다운 잘 됩니다.
감사합니다. ^^
