### ISSUE TITLE
mask as seen 기능

### ISSUE THREAD

**Issue by nass6842** [KurtBestor/Hitomi-Downloader-issues#561]
안녕하세요. 좋은 프로그램 개발해주신 덕분에 히토미 잘 즐기고 있습니다.

전 검색기에서 특정 키워드로 나온 작품을 링크주소 복사해서 파이어폭스 웹브라우저로 보는데요.
히토미내에 작품이 계속 늘어나다보니까 본걸 기억하는데 한계가 생기더라고요.
표지만 봐서는 모르고 몇페이지 읽어봐야 아 이거 봤던거구나 하고... ㅎㅎ

검색기에서 나온 작품 썸네일 우클릭 메뉴에 이미 본것으로 처리되는 기능이 있었으면 좋겠습니다.
특정 작품번호를 본것으로 처리해서 설정파일에 저장되면 다음에 검색할때 썸네일 위에 작은 표식으로 이미 보았던 작품이라고 알려주거나 아니면 검색에서 이미 본것이라고 체크된 작품은 제외하고 검색기에 표시되는 방식으로요.

그리고 디씨 짤 다운로더가 다 죽었던데 이기능도 추가가 가능한지 여쭤봅니다.

좋은 프로그램 감사합니다.

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/211#issuecomment-419862047, https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/300#issuecomment-440511649

**Comment by nass6842** [comment]
답변 감사합니다. 다운로드 하면 검색에서 제외할수있는 기능이 있었네요. 외장하드 하나 사러갑니다.
디씨는 제가 기능을 잘 몰라서 그런지 페이지내에 있는 파일만 다운가능한데 갤러리 전체의 짤을 일괄 다운로드 할수는 없는지 궁금합니다.

**Comment by KurtBestor** [comment]
네, 전체 다운로드는 지원하지 않아요.
