### ISSUE TITLE
마리망 다운로드 안되네요.

### ISSUE THREAD

**Issue by lekim56** [KurtBestor/Hitomi-Downloader-issues#562]
모든 작품이 안되는거 같습니다. ㅠㅠ

**Comment by KurtBestor** [comment]
잠시 Cloudflare's anti-bot page가 생겼다가 지금은 없어졌네요.
일단 나중에 다시 생겨도 문제 없게 수정한 버전이에요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by lekim56** [comment]
아주 잘 됩니다. 정말 감사합니다. ^^
