### ISSUE TITLE
확인 부탁드립니다

### ISSUE THREAD

**Issue by aperie** [KurtBestor/Hitomi-Downloader-issues#563]
테크니컬 프리뷰 버전에 새로 추가해주신 부팅시 실행 기능으로 자동 실행된 다운로더에서, 그 전에 이미 목록에 저장되어 있던 망가쇼미 다운로드 항목을 다시 시작(S) 할 경우 프로그램 파일이 있는 기존 폴더가 아닌 C:\Windows\SysWOW64 폴더 내의 하위 경로로 새로 받아지는 현상이 있네요. 추가로 그 시점부터 프로그램 재실행 전까지는 다른 사이트(히토미, 픽시브, 유튜브 등)에서 받은 파일도 모두 SysWOW64 폴더 내에 받아집니다. 이 상태에서 파일 → 저장을 해도 목록이 제대로 저장되지 않구요.

프로그램을 껐다 켜면 정상으로 돌아오고, 그 이후에는 재부팅 전까지 증상 재현이 안 되는걸로 봐서 부팅시 실행 기능 관련해서 뭔가 문제가 있는 것 같습니다.

번거롭겠지만 확인 부탁드릴게요.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by aperie** [comment]
해결됐네요. 빠른 피드백 감사합니다!
