### ISSUE TITLE
마루마루 신규 reCAPTCHA패턴있는 만화는 다운로드가 안됩니다

### ISSUE THREAD

**Issue by YTOAA** [KurtBestor/Hitomi-Downloader-issues#57]
기존 비밀번호(붕...탁..)을 치는거는 뚫기는 하는데
신규 http://marumaru.in/b/mangaup/281298 들어갈려고 하면 (아니면 그냥 랜덤으로 모든만화에
뜨는거 일수도..)
이상한(?) 한글을 치는 reCAPTCHA 가 있는데
이건 뚫지 못하는거 같아요

**Comment by KurtBestor** [comment]
네, 이것도 수동으로 돌려놔야겠네요..

**Comment by KurtBestor** [comment]
고친 버전입니다:
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

테스트 부탁드려요.

**Comment by YTOAA** [comment]
정상작동 합니다!
혹 기존에 비밀번호를 치는것과 출동할까 비밀번호가 있는 만화를 다운로드 받아봤지만
그런건 없네요
새로운 reCAPTCHA패턴에서 정상작동합니다!
감사합니다!
