### ISSUE TITLE
사이트 추가 건의(하멜른)

### ISSUE THREAD

**Issue by YooJH** [KurtBestor/Hitomi-Downloader-issues#571]
https://syosetu.org/

주소에서 알 수 있다 싶이 소설가가 되자와 비슷한 사이트로

소설가가되자에서 연재가 불가능한 2차창작소설 사이트로

현재 일본 사이트 중 최대규모의 2차 창작 소설 사이트입니다

꼭 좀 추가 부탁드리고 싶습니다

https://github.com/whiteleaf7/narou/wiki

narou.rb라는 전자책용 소설사이트 다운로더가 있긴 하지만

전자책용이라 이런저런 전차책용 ［＃区切り線］이런 이상한 옵션이 들어가서

소설가가되자가 추가된 히토미 다운로더에 부탁드리고싶습니다

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview
