### ISSUE TITLE
데이터 다운로드 안되네요.

### ISSUE THREAD

**Issue by whgmlqja12** [KurtBestor/Hitomi-Downloader-issues#572]
혹시 크롤런가 그 뭐 켜서 정보 받아야한다고 그런식으로 히토미 바꼇다고 저번에 들었는데 지금 그게 꺼져서 이게 업데이트가 안되는건가요? 아니면 히토미측에서 또 이상한 짓 한건가요...? 원래는 일요일 새벽인가 토요일 밤까지는 잘 되다가 새벽녘부터 지금까지도 계속 안되서요...

**Comment by KurtBestor** [comment]
크롤러가 죽은 것 같은데, 크롤러 서버 관리자분에게 연락드렸으니 조만간 해결될 거예요.

**Comment by KurtBestor** [comment]
해결됐어요.
