### ISSUE TITLE
goodbyedpi 관련 오류

### ISSUE THREAD

**Issue by aria1th** [KurtBestor/Hitomi-Downloader-issues#574]
![image](https://user-images.githubusercontent.com/35677394/53326277-7ff8d600-3928-11e9-839c-a23800a3b2ae.png)

해당 파일이 위치에 있는건 확인했어요

그리고 DPI 우회도 된 거로 확인됩니다

다만 실행 시마다 저 오류가 뜹니다. 중복 엑세스를 시키는거 아닐까 싶은데 확인 부탁드려요

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/556
