### ISSUE TITLE
해외거주자인데 goobyedpi 등의 프로그램 옵션으로 off 할 수 없나요?

### ISSUE THREAD

**Issue by friands** [KurtBestor/Hitomi-Downloader-issues#575]
뭔가 패치하고 켜 놓으면 vpn 키고 인터넷 하는 것 처럼 느려지더라구요

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/515#issuecomment-464336708
