### ISSUE TITLE
네이버 웹툰은 선택 화 다운로드가 안되는지요?

### ISSUE THREAD

**Issue by natoom** [KurtBestor/Hitomi-Downloader-issues#576]
히토미 다운로더 너무 잘 쓰고 있고 늘 감사드립니다.

네이버 웹툰 전체 받기는 잘 받아지는데... 선택화 다운로드는 안된다고 팝업이 뜨네요.

웹툰 주소는 이런 식으로 넣었구요
https://comic.naver.com/webtoon/list.nhn?titleId=697656&weekday=sun

제가 잘못 알고 있는 것인지... 아니면 네이버 웹툰은 지원되지 않는 것인지 궁금합니다.

네이버 웹툰은 원래 쓰던 다운로더가 있어서 불편하진 않습니당. 기능 요청은 아니예요 ^^

그래도 이왕이면 히토미 다운로더로 다 통합해서 쓸까 해서 여쭤봅니다.

답변 부탁드릴게요. 좋은밤 되셔요!

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by natoom** [comment]
**테스트해보니 잘 됩니다! 감사합니다!**
여러 네이버 웹툰에서 테스트해봤는데 다 잘 됩니다.

다만 예외적으로 안되는 웹툰이 있네요.
https://comic.naver.com/webtoon/list.nhn?titleId=651673 유미의 세포들
이건 [선택화 다운로드]만이 아니라 그냥 전체 다운로드도 안됩니다.
근데 제가 쓰던 NaverWebToonDonwloader 에서도 이 만화는 받을때
최신화 2편은 다운이 안되는 등 다른 웹툰과는 뭔가 관리가 다른거 같았습니다.
(웹에서는 볼수 있는데 다운이 안되었어요. 유료 미리보기 인것도 아닌데 말이죠)
제 경험상 딱 이 만화만 그런거 같습니다.
그래서 굳이 예외처리까진 안해주셔도 될거 같아요. 바쁘실텐데... ^^

오늘도 빠른 피드백 감사드립니다. 좋은 하루 되셔요!!!

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by natoom** [comment]
https://comic.naver.com/webtoon/list.nhn?titleId=651673 유미의 세포들

이거 말씀하시는거죠? 선택화 다운로드 해봤는데 잘 받아지네요.
신기한게 컷툰 버전으로 받아집니다.

아마도 이 만화가 컷툰 버전이랑 웹툰 버전이랑 둘다 있어서
네이버서버에서의 관리방법이 뭔가 달랐던게 아닌가 싶습니당.

감사합니다!!
