### ISSUE TITLE
음 검색기쓰는데 오류인거같아요

### ISSUE THREAD

**Issue by rabirabin** [KurtBestor/Hitomi-Downloader-issues#577]
업데이트 하기전이랑 하고난후 제 컴문제인지는 모르겠는데 기본데이터 다운받기하고나서 도 똑같네요 482개 가 맥시멈으로 검색되고 혹시나 해서 작가 추가해서 검색해봐도(기존검색+ 작가 한 네명추가) 최대 482개 검색이되네욥

**Comment by KurtBestor** [comment]
제 쪽에선 재현이 안 되네요.
