### ISSUE TITLE
히토미 다운로더가 실행이 안 됩니다.

### ISSUE THREAD

**Issue by Suk42** [KurtBestor/Hitomi-Downloader-issues#578]
얼마전 히토미 다운로더로 웹툰을 다운받고 있었는데 한 번에 너무 무리하게 한 것인지 오류가 생겨버렸습니다. 그래서 파일 다운이 중지되고 다운로더가 중지되었는데 그 뒤에 다시 다운로더를 실행시키니 이미 다운로더가 실행되고 있다고만 나오고 작업 관리자에선 인식조차 되지 않습니다. 이 문제를 해결할 수 있는 방법을 제시해 주십시오. 부탁드립니다.

**Comment by kikinet88** [comment]
흠.. 저같은경우 따로 프로세서 검색툴로 찾아서 끄곤 합니다.
저같은경우 1000개씩 내려받다보니 오류가 자주 발생하곤 하는대
윈도우 자체 작업관리자 말고  다른 툴로 한번 찾아보시는걸 권장합니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview
