### ISSUE TITLE
2.6 버전에서 주소창 드래그 다운로드가 안됩니다.

### ISSUE THREAD

**Issue by ShizuKR** [KurtBestor/Hitomi-Downloader-issues#579]
OS는 윈10 최신...

브라우저는 크롬,

다운로더 버전은 2.6입니다.

이전에는 링크가 설정된 썸네일만 드래그해도 다운로더 주소창에 올릴수 있었고,

거기서 오른쪽 위 다운로드 버튼만 누르면 됐는데

2.6버전에서는 썸네일 드래그도 안되고, 크롬 주소창에서 드래그해도 안되네요...

크롬에서 주소를 다운로더 주소창에 드래그 하는게 안됩니다..

되던게 안되니까 좀 아쉽습니다...

이 부분만 다시 가능하게 만들어 주실수 있는지요?

**Comment by KurtBestor** [comment]
참고해주세요:
- https://blogs.msdn.microsoft.com/patricka/2010/01/28/q-why-doesnt-drag-and-drop-work-when-my-application-is-running-elevated-a-mandatory-integrity-control-and-uipi
- https://answers.microsoft.com/en-us/windows/forum/windows_10-start/how-to-fix-drag-and-drop-in-windows-10/0ea16377-dfcf-4a28-9e38-c35f4113202b
