### ISSUE TITLE
맥용으로 만들수 없나요?

### ISSUE THREAD

**Issue by hyuk199** [KurtBestor/Hitomi-Downloader-issues#580]
py2exe를 사용하신다 하셨는데
py2app으로 맥용을 부탁하고 싶습니다.
현재 크로스파이어로 사용중인데 너무 느리고 가끔 꺼지기도 합니다.
맥용으로 만들수 없나요?

**Comment by KurtBestor** [comment]
힘들 것 같아요.

윈도 API를 많이 썼어요.
네트워크, 파일 입출력, 인코딩, 관리자 권한, 창 항상위, 소리, 창 투명도, 프로세스, 레지스트리, 드래그 드롭, 긴 파일 명, 프록시, 글로벌 핫키, 휴지통, 프로세스 관리, 스레드 관리, 클립보드, 작업표시줄 표시, 멀티모니터, 해상도, 악센트 컬러, 싱글톤, 파일 잠금, 시스템 트레이 등..

외부 라이브러리도 40개 넘게 가져다 썼고, 실행파일 형식의 라이브러리 (FFmpeg, GoodbyeDPI, PhantomJS, ChromeDriver 등) 도 있구요.

비슷한 이유로 하지 못하는 다른 것들도 있어요:
- [ ] 64-bit 운영체제 지원
- [ ] 리눅스 지원
- [ ] 모바일 지원
- [ ] PyQt4 -> PyQt5
- [ ] Python2.x -> Python3.x

Wine으로 실행해보니 그럴싸하게 나오네요:
![screen shot 2019-02-26 at 10 55 19 pm](https://user-images.githubusercontent.com/14768120/53417943-ff1a0700-3a19-11e9-8c0f-8c0803b59021.png)

현재 가장 좋은 방법은 부트캠프나 가상머신에서 실행하는 거예요.

**Comment by hyuk199** [comment]
많이 아쉽네요.
크로스파이어는 wine과 같아요.
질문드리면서 api나 다른 문제로 안될거 같긴 했습니다.

답변 감사합니다.

**Comment by mamakuma** [comment]
Wine으로 실행해보려 합니다만, Winetricks중 어떤걸 선택해야 하나요??
