### ISSUE TITLE
망가쇼미에서 이미지가 교차 되듯이 잘려서 다운로드 됩니다.

### ISSUE THREAD

**Issue by wkd284** [KurtBestor/Hitomi-Downloader-issues#581]
http://tinypic.com/r/10pcy2u/9

상기한 주소의 이미지처럼 다운로드 되네요. 
해당만화는
"돼지 공작으로 전생했으니, 이번에는 너에게 좋아한다고 말하고 싶어 13화" 입니다.
https://mangashow.me/bbs/board.php?bo_table=msm_manga&wr_id=679613

항상 감사히 쓰고 있습니다.

**Comment by KurtBestor** [comment]
해당 작업 `마우스 우클릭` - `정보... (I)`  눌러서 나오는 내용 보여주세요.

**Comment by wkd284** [comment]
> 
> 
> 해당 작업 `마우스 우클릭` - `정보... (I)` 눌러서 나오는 내용 보여주세요.


이게 해결이 됐습니다... 건드린 건 아무것도 없는데... 다운이 가능해 졌네요.
죄송합니다. 혹여 이것이 간헐적으로 발생하는 현상이라면 다음 번엔 꼭 정보내용 첨부하여 문의 드리겠습니다.  먼저 번에 받은건 항목을 지워버려서 볼 수가 없습니다...

**Comment by KurtBestor** [comment]
망가쇼미에서 이미지 조각내고 섞어놓은 다음, 브라우저에서 볼 때 자바스크립트로 다시 맞춰서 보여줘요.
최근에 이 섞는 알고리즘을 바꿨는데 아마 이미지와 자바스크립트 둘 중 하나의 업데이트가 늦어서 그런 것 같아요.

**Comment by wkd284** [comment]
그럴 수도 있군요. 다음에 문의드릴 땐 시간을 두고 문의를 드리겠습니다. 감사합니다!
