### ISSUE TITLE
저장은 되는데 hdt파일이 생기지 않거나 어디있는지 모르겠습니다

### ISSUE THREAD

**Issue by esotericer1** [KurtBestor/Hitomi-Downloader-issues#586]
안녕하세요. 항상 잘 쓰고 있습니다. 지금까지 종료할 때 저장하면서 써 왔는데 며칠 전에 대량으로 다운로드하다 보니 문제가 생기면서, 이전에 다운로드했던 기록들이 전부 날아가 버렸습니다. 앞으로는 그런 문제를 예방하려고 다운로드 리스트 같은 걸 만들려고, 파일 불러오기를 하면 hdt파일을 불러올 수 있다고 했는데 막상 그렇게 하려고 보니 hdt 파일이 안 만들어 진건지, 아니면 컴퓨터 어딘가에 있는데 제가 못 찾은 건진 모르겠지만 찾을 수가 없었습니다. hdt 파일을 저장하고 불러오려면 어떻게 해야 하나요? 부탁드립니다ㅠㅠ

**Comment by KurtBestor** [comment]
`파일` - `선택된 작업들 내보내기...` 누르시면 `*.hdt` 파일을 만들 수 있어요.

**Comment by esotericer1** [comment]
아 감사합니다!

2019년 3월 1일 (금) 오전 1:46, Kurt Bestor <notifications@github.com>님이 작성:

**Comment by esotericer1** [comment]
좀 바보같지만... 예전에는 hdt 등으로 저장된 리스트는 저장이 완료된 뒤, hdt를 불러와서 작업을 다시 시작하면 다시 전부 받는 것이 아니라 그 작업이 마지막으로 다운로드된 날짜 이후 새로 그 아티스트가 올린 파일(deviantart나 twitter등)만 다운되었습니다. 그런데 지금 다시 해보니 작업을 재시작하면 그냥 그 아티스트의 모든 파일이 다시 전부 받아지네요... 기존에 받은 파일들을 기껏 다 정리하고 분류해 놨고, 새로운 파일만을 필요로 하는 상황에서 낭패가 이만저만이 아닙니다. 어떻게 하면 될까요? ㅠㅠ

**Comment by KurtBestor** [comment]
테스트해보니 잘 되네요. 마지막으로 다운로드된 날짜 이후를 다운 받는 게 아니라 이전에 다운로드한 똑같은 이름의 파일이 있다면 건너뛰는 거예요. 다운로드 폴더를 바꿨다면 다른 폴더로 인식돼요.
