### ISSUE TITLE
망가쇼미에서 몇몇 만화가 다운로드 되지 않습니다.

### ISSUE THREAD

**Issue by muju7** [KurtBestor/Hitomi-Downloader-issues#587]
왜인지는 모르겠지만
새로 올라오는 만화들이 아니라 옛날 만화들이 다운로드 되지않는것 같습니다.

**Comment by muju7** [comment]
알고보니 dpi가 제대로 작동하지 않아서 일어난 일인것 같습니다.

**Comment by KurtBestor** [comment]
해당 작업 `마우스 우클릭` - `정보... (I)` 눌러서 나오는 내용 보여주세요.
