### ISSUE TITLE
작가 추천 기능이 작동하지 않습니다

### ISSUE THREAD

**Issue by ioj02385** [KurtBestor/Hitomi-Downloader-issues#588]
안녕하세요. 작가 추천 기능이 작동을 안하는데요 ㅠㅠ

작가 추천 창에서 다음 버튼을 눌러서 넘어가면 에러 메세지를 뱉어내네요.

![image](https://user-images.githubusercontent.com/48097899/53579723-74720d00-3bbd-11e9-85ec-1a4e8854f731.png)

버전은 며칠 전에 올라온 2.6 자동업뎃 받았던걸로 기억하고요...

대체 뭐가 문제일까요?

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by ioj02385** [comment]
정상 작동되네요. 감사합니다.
