### ISSUE TITLE
마루마루 만화 다운 중 큰 에러가 발생했습니다..

### ISSUE THREAD

**Issue by ggoke123** [KurtBestor/Hitomi-Downloader-issues#59]
몇몇 만화를 다운 받는데 에러가 나서. .올립니다;
개인적으로는 지금 하드를 포멧하게 생겼네요

1. 헌터X헌터 - 왠지 모르겠지만 다운 불가 / invalid 라고 뜸

2. (중요) 선생님, 좋아해요 라는 만화를 다운받으려 시도시(전체 범위 다운로드)
[단편] 화가 폴더는 생성되었으나, 안에 파일이 생기지 않았고
오류 0x80004005 가 나면서 접근 불가 및 폴더 제거 불가 현상입니다.

인터넷에 알려진 방법(CMD 상에서 제거)를 시도해봤으나, 모든게 접근 불가
지금 포멧을 준비중입니다..

좀 스트레스인데.. 
테스트 할려고, 기존 망가진 폴더 상위 폴더명을 바꿧고
새로 한번도 시도 해봣을때 또 같은 증상입니다...

**Comment by YTOAA** [comment]
음 그 삭제 안되는 폴더나 파일말이죠
cmd에서도 삭제가 안되고 다른 폴더,파일 삭제프로그램으로도 삭제가 안된다면
7-zip이라는 프로그램으로 삭제해보심이...
저도 한때 이 다운로더 프로그램에서 발생한 문제는 아니지만
같은 문제를 격은적이 있습니다
저도 그래서 포멧을 할까...했지만
어떤분께서 그럴때는 7-zip로 폴더나 파일 찾은후에 삭제하면 된다고..
원래 이 프로그램은 알집,반디캠과 같은 압축풀기,압축 프로그램이지만
여기서 해당 폴더 경로를 찾은후 우클릭후 삭제를 누르면 삭제가 되더군요
도움이 되시기를...

**Comment by KurtBestor** [comment]
2.2버전에서 해결되었을텐데요, 해당문제는 폴더 이름이 "."으로 끝나서 생깁니다.
