### ISSUE TITLE
다운로더에서 완료되고 삭제된 파일 검색기에서 필터링 가능여부

### ISSUE THREAD

**Issue by sesism** [KurtBestor/Hitomi-Downloader-issues#590]
다운로드가 완료된 파일 중 중복된 파일이나 필요가 없는 파일을 삭제하였을 경우

다운로더에는 완료된 기록이 남아있지만

검색기에서 done:x 옵션을 사용했을 경우 필터링이 되지 않습니다.

혹시 다운로드는 완료되었지만 현재 자료가 남아있지 않는 파일도 필터링 할 수 있을까요?

정말 좋은 프로그램 잘 쓰고 있습니다.

**Comment by KurtBestor** [comment]
이해가 안 되네요. 좀 더 자세히 알려주실 수 있나요?

**Comment by sesism** [comment]
A라는 파일을 다운로드 받고 검색기(searcher)에서 done:x 옵션을 사용해서 필터링을 할 경우 A라는 파일은 보이지 않게 됩니다. 그리고 다운로더에서는 다운로드 완료된것으로 표시가 되구요.

그후에 A라는 파일을 삭제한 이후,

다시 히토미 다운로더를 실행시키면 A라는 파일이 다운로드가 완료된 기록이 남아있습니다.
하지만, 검색기에서 done:x 옵션을 사용해서 필터링을 하면 A라는 파일이 보입니다.
A를 삭제하지 않으면 보이지 않구요.

저는 여기서 A를 삭제 했더라도 다운로드 기록이 남아있다면 필터링 되게 하고 싶습니다.

**Comment by KurtBestor** [comment]
용량때문에 지우시는 건가요? 꼭 하고싶으시면 폴더는 나두고 내용물만 지우세요.
