### ISSUE TITLE
2.6 업데이트 이후 네트워크드라이브에 저장이 안됩니다

### ISSUE THREAD

**Issue by wiejdm** [KurtBestor/Hitomi-Downloader-issues#591]
2.5d버전까지는 되었는데 2.6버전 올리니 설정에 폴더 경로 선택에 네트워크드라이브가 뜨지않네요.

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/539
