### ISSUE TITLE
픽시브 관련 질문입니다.

### ISSUE THREAD

**Issue by roseark** [KurtBestor/Hitomi-Downloader-issues#592]
픽시브에서 움직이는 그림의 경우 다른 파일 형식에 비해
gif 형식의 용량이 크게 다운로드 되는 부분에 대해서는
개선방법이 없을까요?

webp파일은 6mb 정도 나오는 파일이, gif의 경우에는 20mb 정도 되네요.
이건 그나마 그림 크기가 작은 편인데,
큰 그림의 경우 100mb도 훌쩍 넘어갑니다...

**Comment by KurtBestor** [comment]
100MB 넘는 그림 주소 알려주세요.

**Comment by roseark** [comment]
옛날에 받아놓았던 100mb 넘는 그림 찾다가
혹시나 해서 최신버전으로 다시 받아보니 예전에 받았던거 보다 용량이 낮게 받아지네요.
대체적으로 그때보다 절반 ~ 4분의 1 정도 줄어들었네요.
당시에는 1.9 버전으로 받았었는데, 지금 정도의 용량이면 어느정도 괜찮은 것 같습니다.
감사합니다.
