### ISSUE TITLE
암호화? 된 이미지를 받는 방법

### ISSUE THREAD

**Issue by aksghkqhrl** [KurtBestor/Hitomi-Downloader-issues#594]
![20190302_015453](https://user-images.githubusercontent.com/47558641/53653357-78ba2b00-3c8e-11e9-8dfa-40e11ac1d5a6.png)
보고싶은 만화가 번역되어 올라오지않아서 일본 공식사이트에서 구입해서 보고있는데 직접 번역해서 소장할려고하니 이미지에 암호? 가 걸려있어서 다운 시도할때 이미지 픽셀이 깨져있습니다.

히토미 스크립트에서 저 사이트를 추가하고싶은데 어떻게 해야하는지 방법을 알고싶습니다.

**Comment by KurtBestor** [comment]
**[여기에](https://drive.google.com/drive/folders/1FP0YZp7QyGDyOQ1nwILRIVT3kd58NYxo)** 다른 스크립트들 있으니 참고해서 수정해서 만드세요.

`도움말` - `사용법... (F1)` - `스크립트` 참고해주세요.
