### ISSUE TITLE
cli 버전을 만들어 주실수 있나요?

### ISSUE THREAD

**Issue by hwano1010** [KurtBestor/Hitomi-Downloader-issues#596]
항상 잘 쓰고 있습니다. 픽시브나 트위터, 갤부루같은데서 다운로드 받는데는 제격이네요. 좋은 프로그램 만들어 주셔서 감사합니다.
헌데 홈 서버에다 집어넣고 주기적으로 다운로드 받게 하면 좋겠다 싶은데, cli 버전이 없으니 어덯게 할지 좀 난감합니다.
혹시 여유가 되신다면 cli 버전을 따로 내 주실수 있으신가요?

**Comment by KurtBestor** [comment]
CLI 버전은 이미 좋은 프로그램이 있어요: https://github.com/mikf/gallery-dl

말씀하신 픽시브, 트위터, 갤부루 모두 지원하네요.

**Comment by hwano1010** [comment]
호오오오옹이 좋은 프로그램 추천 감사합니다.
