### ISSUE TITLE
다운로더가 갑자기 꺼지고 다시 켰는데...

### ISSUE THREAD

**Issue by chbk256** [KurtBestor/Hitomi-Downloader-issues#598]
다시 키니 다운 받고 있던 목록들이 갑자기 사라져있고 저장된 설정이 없다고 뜨네요.

기존 데이터를 읽지 못하게 된거거나 관련 데이터가 사라졌거나 둘 중 하나가 아닌가 싶은데

일단 직접 폴더에 들어가서 보면 끊기기 전까지 받고 있었던 자료들은 남아있습니다.

제가 히토미 다운로더를 각각 다른 폴더 2곳에 깔아놨고, 다른 히토미 다운로더 같은 경우엔

목록이 남아있네요.

혹시 왜 그런지 알 수 있을까요?

**Comment by KurtBestor** [comment]
`[실행파일 이름].ini` 에 설정과 작업 목록이 저장되는데요, 만약 저장하다 꺼졌으면 `[실행파일 이름]_backup.ini` 파일이 남아있을거예요.
`[실행파일 이름].ini` 파일이 남아있는데 읽지 못하나요?

**Comment by chbk256** [comment]
뭐 때문인지는 모르지만 아예 원본이 사라져버렸군요. 그래도 다행히 말씀주신대로 백업 ini파일이 남아 있어서 원본으로 고쳐 실행해보니 작업 내용들이 불러와집니다. 세밀하게 다운로더 하나하나 잘 만드신 것 같네요. 답변 감사합니다.
