### ISSUE TITLE
쇼미 사이트에서 일부 만화가 다운로드 되지 않습니다.

### ISSUE THREAD

**Issue by mita5549** [KurtBestor/Hitomi-Downloader-issues#599]
-

**Comment by mita5549** [comment]
최근 발견한, 다운로드 되지 않는 목록은 다음과 같습니다.
사이트에서는 정상적으로 이미지가 출력되는데, 뭐가 문제일까요.ㅠㅠㅠ;

https://mangashow3.me/bbs/board.php?bo_table=msm_manga&wr_id=684245
https://mangashow3.me/bbs/board.php?bo_table=msm_manga&wr_id=684214
https://mangashow3.me/bbs/board.php?bo_table=msm_manga&wr_id=678672
https://mangashow3.me/bbs/board.php?bo_table=msm_manga&wr_id=678351
https://mangashow3.me/bbs/board.php?bo_table=msm_manga&wr_id=678344
https://mangashow3.me/bbs/board.php?bo_table=msm_manga&wr_id=677886

**Comment by luku756** [comment]
같은 만화인데 특정 화가 다운되지 않는 경우도 확인했습니다.
다운받은 파일들이 전부 311byte의 '깨진 파일' 이네요.

몇 가지 경우가 있었는데 예를 들어 아래 만화의 104.5~107 화를 받았는데 106화가 깨져있습니다.
https://mangashow.me/bbs/page.php?hid=manga_detail&manga_name=%EC%9B%94%EA%B0%84%EC%88%9C%EC%A0%95+%EB%85%B8%EC%9E%90%ED%82%A4+%EA%B5%B0

반드시 최신 화만 그런 것도 아니고 잘 모르겠네요.

**Comment by KurtBestor** [comment]
깨진 파일 보내주세요.

**Comment by mita5549** [comment]
저는 아예 빈 파일이라서, 보내드릴게 없네요.ㅠㅠ

**Comment by KurtBestor** [comment]
DPI 우회 켜고 해도 그런가요?

**Comment by mita5549** [comment]
예전에 태그 걸어주셨던 이슈를 보고 있습니다.
https://reqrypt.org/windivert.html 까지는 들어갔는데, 여기서 어떤 행동을 해야 할지 모르겠습니다.ㅠㅠㅠ
무엇을 어떻게 해야 하나요?

**Comment by KurtBestor** [comment]
Windows7은 KB3033929 업데이트를 받으셔야해요.
