### ISSUE TITLE
익헨 다운로드 3건 안되는 현상입니다.

### ISSUE THREAD

**Issue by sexbitch** [KurtBestor/Hitomi-Downloader-issues#6]
https://exhentai.org/g/911754/aeb3b16a9c/
https://exhentai.org/g/1153457/2ab5abe2af/
https://exhentai.org/g/1042795/78e12b1668/

이렇게 3건입니다. 확인부탁드립니다.

언제나 감사드립니다.

**Comment by KurtBestor** [comment]
익헨에만 있고 이헨엔 없는 갤러리네요.
아직 익헨은 테스트 중이라 비활성화해두었습니다.
다운로더 메인창에서 Ctrl + L을 눌러서 디버그 모드로 진입한 뒤, 고급설정에서 이헨/익헨을 강제로 변경할 수 있습니다:
![exhen](https://user-images.githubusercontent.com/14768120/34346167-53f3634e-ea38-11e7-89c8-50679b99630c.png)
추후에 자동으로 이헨/익헨을 판단하는 기능을 넣으려고합니다.

**Comment by sexbitch** [comment]
감사합니다!

**Comment by KurtBestor** [comment]
v1.9e에서 해결됨
