### ISSUE TITLE
태그 관련 기능 건의 합니다.

### ISSUE THREAD

**Issue by Gilmon96** [KurtBestor/Hitomi-Downloader-issues#600]
지금은 다운 목록에서 우 클릭으로 "red" 태그를 지정하고 하단에 "필터"를 눌러서
색깔별로 표시된 태그 중에 하나를 선택하면 해당 태그가 설정된 목록이 뜨게 하는데

이 색깔별 태그에 "red"가 아닌 다른 이름으로 변경하는 기능과
해당 태그를 선택해서 목록이 선택된 태그로만 필터링 될 때
변경한 태그 이름이 UI 하단이나 다른곳에 작게나마 표시되게 할 수 있었으면 좋겠습니다.
태그를 지정할 때 색깔만 있다 보니 뭐였는지 헷갈리는 경우가 있어서 건의드립니다.

늘 유용하게 사용하고 있습니다. 감사합니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by Gilmon96** [comment]
감사합니다. 그런데 추가로 태그 안된 것만 보여주는 버튼도 만들어 주실 수 있나요?

**Comment by KurtBestor** [comment]
![image](https://user-images.githubusercontent.com/14768120/62441863-cb919480-b790-11e9-81ae-c3e7b977d0df.png)
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview
