### ISSUE TITLE
망가쇼미에서 만화의 일부 화가 제대로 다운로드 되지 않습니다.(일부 주소가 http)

### ISSUE THREAD

**Issue by luku756** [KurtBestor/Hitomi-Downloader-issues#601]
같은 만화인데 특정 화가 제대로 다운되지 않는 경우를 확인했습니다.
다운받은 파일들이 전부 311byte의 '깨진 파일' 이네요.

몇 가지 경우가 있었는데 예를 들어 아래 만화의 104.5~107 화를 받았는데 106화가 깨져있습니다.
https://mangashow.me/bbs/page.php?hid=manga_detail&manga_name=%EC%9B%94%EA%B0%84%EC%88%9C%EC%A0%95+%EB%85%B8%EC%9E%90%ED%82%A4+%EA%B5%B0

반드시 최신 화만 그런 것도 아니고 잘 모르겠네요.

아래처럼 편중 일부가 이런 식으로 다운로드가 되지 않습니다.

![a1](https://user-images.githubusercontent.com/43954535/53686244-0b7ac880-3d68-11e9-844c-2868b0d026f1.PNG)

위에 예시로 든 104.5~106화의 작업 정보 중 일부입니다.
![a2](https://user-images.githubusercontent.com/43954535/53686325-dde24f00-3d68-11e9-9887-58238fed474f.png)

이거 외에도 로그를 뒤적거려 봤는데, 제대로 다운로드 되지 않은 파일들의 공통점은 변환된(추출된) url이  http:// 로 시작하더군요. 다른 건 전부  https:// 로 시작하는데요.
아마 http는 막혀있기 때문에 그럴 것으로 예상합니다만...  실제로 같은 주소에서 s만 넣으면 정상적으로 확인됩니다. 부디 수정 부탁드립니다.

항상 감사합니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by luku756** [comment]
테스트 버전으로 해보니 정상적으로 다운되네요. 수정 감사합니다.
