### ISSUE TITLE
픽시브 키워드 단위로 받을 수 있게 하면 좋을 것 같습니다.

### ISSUE THREAD

**Issue by chbk256** [KurtBestor/Hitomi-Downloader-issues#602]
전에 쓰던 PixivUtil2 이라는 픽시브 다운로더에서는   

(ex :    https://github.com/bebound/pixiv  ) 작가 이름 외에도 키워드를 입력하면 

그 키워드 검색 결과로 나오는 이미지들 1페이지 부터 끝 페이지 까지 다 받아지더군요. 

여기도 이 기능이 있으면 좋을 것 같아서 한번 건의드려봅니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

다음과 같이 입력하면 돼요:
- https://www.pixiv.net/search.php?s_mode=s_tag&word=tag
- pixiv_search_tagname

PixivUtil2 와 동일하게 모바일 버전 API를 사용하기 때문에 PC 버전의 검색 결과와는 조금 다를 수 있어요.

**Comment by chbk256** [comment]
오.. 일본어로 위의 두 방식 다 검색 해봤는데  잘 됩니다. 썸네일의 아트 하나 뿐만 아니라 거기에 엮인 그림들도 다 딸려오는 게 좋네요. 의견 수렴 감사합니다.
