### ISSUE TITLE
히요비 다운로드 안되네요.

### ISSUE THREAD

**Issue by noname8** [KurtBestor/Hitomi-Downloader-issues#603]
히요비 사이트가 막혀서그런지 다운로드도 안되네요.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by noname8** [comment]
올려주신 파일로는 가능하네요 감사합니다.
