### ISSUE TITLE
제이마나 만화 다운로드가 되지 않습니다

### ISSUE THREAD

**Issue by cancerogenic** [KurtBestor/Hitomi-Downloader-issues#605]
Invalid : [jmana] https://jmana4.com / book / 마술%20선배

version: 2.6
platform: Windows-10-10.0.17763
gal_num: https://jmana4.com/book/마술%20선배
dir: 
zip: 
type: jmana
artist: None
url: https://jmana4.com/book/%EB%A7%88%EC%88%A0%2520%EC%84%A0%EB%B0%B0
valid: False
done: False
range: None
range_p: None
single: False
time: 1551582914.22 (Mar 3)
tags: []

[Gallery]
None

[File Names]

[URLs]

[Messages]
'NoneType' object has no attribute 'findAll'
stop
Traceback (most recent call last):
File "utils", line 493, in start
File "utils", line 537, in start_
File "jmana_downloader", line 68, in read
File "jmana_downloader", line 62, in name
File "jmana_downloader", line 85, in get_title
AttributeError: 'NoneType' object has no attribute 'findAll'

Fail: jmana

done : https://jmana4.com/book/마술%20선배

목록을 읽어오지 못하는것 같습니다

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by cancerogenic** [comment]
아주 감사합니다
