### ISSUE TITLE
중복된 만화 리스트 자동/수동 갱신 혹은 제목 정렬기능...요청

### ISSUE THREAD

**Issue by bittet** [KurtBestor/Hitomi-Downloader-issues#609]
만화를 받다보면 한번에 받아지는 것이 아닌 매주 혹은 비정기적으로 받아서 봐야 합니다.
따라서 리스트를 남겨 놓습니다만...
보는 만화가 많아지면.... 이미 봤던 링크를 또 걸어버리곤 합니다.
(결국 실제로 보는건 50개인데... 리스트에는 같은 만화 링크가 3~4개씩 있는 경우가...)

그래서...
리스트에 기존에 같은 링크가 있는데 다시 또 받으라고 넣는다면...
해당 링크를 삭제하거나 갱신토록 해주면 될 것 같습니다...;;;
물론,  애초에 관리를 잘하면 되는 문제긴 합니다만...;;;;;;

정리하는 것도 일이라...ㅠㅠ

아니면... 제목단위로 소트 기능을 주면 쉽게 찾아서 지울 것 같습니다.  -.-;;

**Comment by KurtBestor** [comment]
참고해주세요:
- https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/232#issuecomment-419765649
- https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/491

**Comment by bittet** [comment]
> 
> 
> 참고해주세요:
> 
>     * [#232 (comment)](https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/232#issuecomment-419765649)
> 
>     * #491

F3 기능이 있네요.  이걸로 충분합니다. ㅎㅎ
감사합니다.
