### ISSUE TITLE
2.2a 에서 오류가 발생합니다 (내용)

### ISSUE THREAD

**Issue by kikinet88** [KurtBestor/Hitomi-Downloader-issues#61]
일단 망가 검색 중에

필요한 검색어를 넣고 검색중에

대략 653개 검색 될때쯤에

오류가 나면서 프로그램이 강제 종료가 되고 있습니다.

이전 버젼에서는 이러한 현상을 본적이 없는대

오늘 업데이트 하면서 처음 본 오류 입니다.

**Comment by KurtBestor** [comment]
검색 설정이 어떻게 되어있는지 스크린샷 찍어서 보여주실 수 있나요?

검색 설정 바꿔도 똑같이 오류 나나요?

**Comment by kikinet88** [comment]
섬네일 오류 인거같습니다
섬네일 해제 하니 오류 가 발생하지 않네요
지금 별별거 다 손대보고 있다가 방금 찾아냈습니다.

2018-02-22 20:13 GMT+09:00 Kurt Bestor <notifications@github.com>:

**Comment by kikinet88** [comment]
제 시스템 스크립트가 문제가 있어나 봅니다

리셋 시키고 섬네일 및 다른 검색 체제 리로드 시키니 정상 작동 됩니다..

그리고 리로드 시켜도 문제가 되는게

검색할때 테그 제외 시키는 명령어중 어느것이 문제인지는 모르나

-m 부분에서 오류가 발생하는거 같아요...

실례가 되지 않는다면 뜯어봐도 될가요...?

2018년 2월 22일 오후 8:15, 광폭격사 <kikinet88@gmail.com>님이 작성:

**Comment by KurtBestor** [comment]
오, 개발자신가 봐요!
네 마음껏 뜯어보셔도 됩니다.
원인을 알아내서 알려주시거나 아니면 코드 고쳐서 보내주시면 감사하겠습니다!
