### ISSUE TITLE
다운이 되지않습니다

### ISSUE THREAD

**Issue by wpfhfpr** [KurtBestor/Hitomi-Downloader-issues#610]
731759
703454
751456
730544
720464
111724
2428
718320

이번호들이

히토미 검색기를 통해 받은 자료중 계속 읽기중의 무한 반복현상이 일어나네요
원인이나 해결방법이 있을까요

제가 추측하기론 사이트 url을 직접 들어가봤을 때 nginx에러가 뜨네요. 이런적이없어서 비교까진 못하겠지만요.
다만 저현상도 gallaries를 reader로 바꾸면 감상할 수 있습니다. 
https://hitomi.la/galleries/718320.html->https://hitomi.la/reader/718320.html#1-

다운받는 방법이나 해결방법이 있으면 부디 ㅠㅠ

**Comment by KurtBestor** [comment]
해당 작업 `마우스 우 클릭` - `정보... (I)` 눌러서 나온 내용 보여주세요.

**Comment by wpfhfpr** [comment]
[새 텍스트 문서.txt](https://github.com/KurtBestor/Hitomi-Downloader-issues/files/2951005/default.txt)
