### ISSUE TITLE
네이버 원본 이미지 다운에 관해

### ISSUE THREAD

**Issue by roseark** [KurtBestor/Hitomi-Downloader-issues#612]
네이버 블로그에서 이미지 다운을 받을때
확장자에 '_blur' 라는 단어가 붙어서 다운이 됩니다.(ex : xx.jpg->xx.jpg_blur)
처음에는 원본 이미지가 따로 있는 것만 그런건가 했는데,
그렇지 않은 것도 있어서
아무래도 스마트 에디터로 작성된 글의 이미지를 받을 때 그런 것 같습니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview
