### ISSUE TITLE
최신버전의 속도가 느립니다

### ISSUE THREAD

**Issue by shameimaruaya123** [KurtBestor/Hitomi-Downloader-issues#613]
지금까지 굳이 별 문제 없이 잘 굴러가길래 2.1을 계속 쓰다가

이번에 2.6을 사용해봤는데요

같은 번호를 다운받아도 2.1에서는 바로 잡히고 바로 다운이 되는데

2.6은 읽는중~ 에서 다음으로 넘어가는데 시간이 좀 너무 오래걸리는거같습니다

뭔가 설정을 따로 건드려줘야하는건가요?

항상 잘 쓰고 있습니다 감사합니다.

**Comment by shameimaruaya123** [comment]
10분동안 망가 하나 제대로 못 잡다가 지우고 다시 까니까 또 제대로 빨리 돌아가네요..

글삭 어떻게 하는지 몰라서 그냥 두겠슴다..

**Comment by shameimaruaya123** [comment]
정상적으로 잘 될때도 있는데 '읽는중' 에서 다음으로 못넘어가는 경우가 자꾸 있네요.
혹시 몰라서 같은 망가를 2.1로 다운받아보니 제대로 다운이 됐습니다.
왜 이러는 걸까요 ㅠ

**Comment by KurtBestor** [comment]
해당 작업 마우스 우 클릭 - 정보... (I) 눌러서 나온 내용 보여주세요.
