### ISSUE TITLE
망가쇼미의 만화 중 몇몇 화의 파일이 그림 하나로 받아집니다.

### ISSUE THREAD

**Issue by kekhs46392** [KurtBestor/Hitomi-Downloader-issues#615]
그 장난감 인형은 사랑을 한다
12화에서 20화까지가 개개의 이미지로 받아지는게 아니고 하나의 이미지 파일로 받아지네요.

https://mangashow3.me/bbs/page.php?hid=manga_detail&manga_name=%EA%B7%B8+%EC%9E%A5%EB%82%9C%EA%B0%90+%EC%9D%B8%ED%98%95%EC%9D%80+%EC%82%AC%EB%9E%91%EC%9D%84+%ED%95%9C%EB%8B%A4

사이트에서 올릴때 그렇게 올린건지 아니면 다운로더의 문제인지는 잘 모르겠습니다.

**Comment by KurtBestor** [comment]
`뷰어로 보기` 눌러서 확인해주세요.

**Comment by kekhs46392** [comment]
감사합니다.
뷰어로 보기에서 보니 어떻게 올라왔는지가 보이네요.
보니까 다운로더 문제가 아니고, 사이트에서 올릴때 그렇게 올린 거네요.
