### ISSUE TITLE
파일을 많이 다운받다보면 종종 프로그램이 멈춥니다.

### ISSUE THREAD

**Issue by supermekadeathstalin** [KurtBestor/Hitomi-Downloader-issues#619]
멈추는거자체도 문제입니다만 강종하고 나면 다시 켜지질 않습니다.
계속 이미 히토미 다운로더가 실행중이라고 뜨는데 프로세스에도 없어서 컴퓨터 전체를 껏다 켜는거 외에는 해결책이 없습니다.

**Comment by wpfhfpr** [comment]
GOODBYEDPI.EXE 까지 꺼보셔유

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by supermekadeathstalin** [comment]
> GOODBYEDPI.EXE 까지 꺼보셔유

전 다운로더 쓸떄 그거 안켜요
