### ISSUE TITLE
질문 사항이 있습니다.

### ISSUE THREAD

**Issue by xlxlzl123** [KurtBestor/Hitomi-Downloader-issues#62]
전에 중복 다운로드 스킵을 건의했던 사용자인데요.

- 이미 다운로드 완료된 것도 무조건 덮어씌우는 문제 해결

이 문구를 리드미에서 보고서 제 건의사항이 추가된 줄 알았는데 계속 다운이 되더라구요 

1182527 이 번호를 계속 받아봤는데요 다운 받을 때 마다 이미 있는 파일이어도 계속 받더라구요.

압축 기능을 키면 작동이 안되나요? 압축을 안하면 빠르게 넘어가기는 하는데요 

전 토렌트에서 이미 있는 파일은 통과 시키는 그런 기능을 바란건데 혹시 제대로 전달이 안됬나 싶어서

올려봅니다. 다른 중요한 디버깅 같은게 있다면 천천히 해주세요

**Comment by KurtBestor** [comment]
네, 그 부분은 별로 중요하지 않은 것 같아 우선순위가 좀 밀렸네요. 좀 한가해지면 작업할 예정이예요.

**Comment by KurtBestor** [comment]
![lll](https://user-images.githubusercontent.com/14768120/36625275-cc8b13a0-195f-11e8-931d-7cd1d728f907.png)
이렇게 하면 처음 10페이지만 받아요.

**Comment by xlxlzl123** [comment]
개발자님 저렇게 해도 123번 작품이 받아지는데요 

~하고 숫자 사이에 스페이스 눌러도 계속 그럽니다.

**Comment by KurtBestor** [comment]
어떻게 쓰신건가요

스크린샷 보여주실 수 있나요?

~랑 숫자 사이에 스페이스는 넣든 넣지 않든 상관 없어요.

**Comment by xlxlzl123** [comment]
스크린샷을 첨부 키를 몰라서 못 올렸는데요 

1. 다운로드 창에 123을 입력후 옆에 히토미 아이콘이 뜨는 것을 확인

2. 다운로드 키 옆에 있는 페이지 지정 다운 키를 눌러 창을 띄움

3. ~ 10 이라고 입력후 확인을 누르면 123번 에반게리온 작품이 다운로드가 됨 

커맨드가 잘못 된건지 모르겠네요 123 치고 나서 페이지 지정 다운 창 띄우는 것 까지는 똑같은데 

그 다음 커맨드가 안먹히고 그냥 id 123번 작품이 다운로드 되니까요

**Comment by KurtBestor** [comment]
![pages](https://user-images.githubusercontent.com/14768120/36630253-c5385ecc-19a6-11e8-98db-1088da66fdab.png)
넹 123 다운로드되는 거 맞아요. 그 작품의 페이지를 1~10만 받는거예요.
아래는 그냥 다운로드 한 것, 위는 페이지를 지정해서 다운로드 한거예요.

**Comment by xlxlzl123** [comment]
아 그렇군요 알겠습니다
