### ISSUE TITLE
히토미 다운로드 안되는거 하나 있어서 올려봅니다

### ISSUE THREAD

**Issue by rlacks1237** [KurtBestor/Hitomi-Downloader-issues#622]
읽는 중... [Tatsu Tairagi] koi tamesi (644054)

version: 2.6
platform: Windows-10-10.0.17134
gal_num: [Tatsu Tairagi] koi tamesi (644054)
dir: 
zip: 
type: hitomi
artist: None
url: 644054
valid: True
done: False
range: None
range_p: None
single: True
time: 1552369910.76 (Mar 12)
tags: []

[Gallery]
갤러리 넘버: 644054

제목: koi tamesi

작가: tatsu tairagi

그룹: N/A

타입: manga

시리즈: N/A

캐릭터: N/A

태그: female:defloration, female:kimono

언어: Korean

[File Names]

[URLs]

[Messages]
********************************
Gallery number : 644054
Number of Threads : 64
********************************
Size (https://i.hitomi.la/galleries/644054/17.jpg): 0
Size (https://i.hitomi.la/galleries/644054/17.jpg): 0
Size (https://i.hitomi.la/galleries/644054/17.jpg): 0
size is too small; test:xxx
Traceback (most recent call last):
File "hitomi_downloader", line 1156, in download_hitomi
File "hitomi_downloader", line 167, in pop_img
File "downloader", line 234, in read_html
File "urllib3\poolmanager", line 146, in urlopen
File "urllib3\connectionpool", line 258, in urlopen
File "urllib3\util\retry", line 132, in increment
File "urllib3\connectionpool", line 240, in urlopen
File "urllib3\connectionpool", line 147, in _make_request
File "urllib3\connectionpool", line 363, in _validate_conn
File "urllib3\connection", line 172, in connect
File "urllib3\connection", line 83, in _new_conn
NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x25248C50>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

Traceback (most recent call last):
File "hitomi_downloader", line 1178, in download_hitomi
File "hiyobi_downloader", line 11, in pop_img_hiyobi
IndexError: list index out of range

get imgs from e(x)hentai: 644054
ehen_imgs(ex:False, url:644054)
Find_ehen(id:644054, ex:False)
Find in heroku...
not found in heroku
max_page = 21166
Brute-force search: 1
Brute-force search: 2
Brute-force search: 3
Brute-force search: 3.1
Brute-force search: 4.1
Brute-force search: 5.1
Brute-force search: 6.1
Brute-force search: 7.1
Brute-force search: 8.1
Brute-force search: 8.2
Brute-force search: 9.2
Brute-force search: 10.2
Brute-force search: 10.3
Brute-force search: 10.4
Brute-force search: 11.4
Brute-force search: 11.5
Brute-force search: 11.6
Brute-force search: 11.7
Brute-force search: 11.8
Brute-force search: 12.8
Brute-force search: 13.8
Brute-force search: 13.9
Brute-force search: 14.0
Brute-force search: 14.1
Brute-force search: 14.2
Brute-force search: 15.2
Brute-force search: 15.3
Brute-force search: 15.4
Brute-force search: 15.5
Brute-force search: 15.6
Brute-force search: 15.7
Brute-force search: 15.8
Brute-force search: 16.8
Brute-force search: 16.9
Brute-force search: 17.0
Brute-force search: 17.1
Brute-force search: 17.2
Brute-force search: 18.2
Brute-force search: 18.3
Brute-force search: 18.4
Brute-force search: 18.5
Brute-force search: 18.6
Brute-force search: 18.7
Brute-force search: 18.8
Brute-force search: 18.9
Brute-force search: 19.0
Brute-force search: 19.1
Brute-force search: 19.2
Brute-force search: 19.3
Brute-force search: 19.4
Brute-force search: 20.4
Brute-force search: 20.5
Brute-force search: 20.6
Brute-force search: 20.7
Brute-force search: 20.8
Brute-force search: 20.9
Brute-force search: 21.0
Brute-force search: 21.1
Brute-force search: 21.2
Brute-force search: 21.3
Brute-force search: 21.4
Brute-force search: 21.5
Brute-force search: 21.6
Brute-force search: 21.7
Brute-force search: 21.8
Brute-force search: 21.9
Brute-force search: 22.0
Brute-force search: 22.1
Brute-force search: 22.2
Brute-force search: 22.3
Brute-force search: 22.4
Brute-force search: 22.5
Brute-force search: 22.6
Brute-force search: 22.7
Brute-force search: 22.8
Brute-force search: 22.9
Brute-force search: 23.0
Brute-force search: 23.1
Brute-force search: 23.2
Brute-force search: 23.3
Brute-force search: 23.4
Brute-force search: 23.5
Brute-force search: 23.6
Brute-force search: 23.7
Brute-force search: 23.8
Brute-force search: 23.9
Brute-force search: 24.0
Brute-force search: 24.1
Brute-force search: 24.2
Brute-force search: 24.3
Brute-force search: 24.4
Brute-force search: 24.5
Brute-force search: 24.6
Brute-force search: 24.7
Brute-force search: 24.8
Brute-force search: 24.9
Brute-force search: 25.0
Brute-force search: 25.1
Brute-force search: 25.2
Brute-force search: 25.3
Brute-force search: 25.4
Brute-force search: 25.5
Brute-force search: 25.6
Brute-force search: 25.7
Brute-force search: 25.8
Brute-force search: 25.9
Brute-force search: 26.0
Brute-force search: 26.1
Brute-force search: 26.2
Brute-force search: 26.3
Brute-force search: 26.4
Brute-force search: 26.5
Brute-force search: 26.6
Brute-force search: 26.7
Brute-force search: 26.8
Brute-force search: 26.9
Brute-force search: 27.0
Brute-force search: 27.1
Brute-force search: 27.2
Brute-force search: 27.3
Brute-force search: 27.4
Brute-force search: 27.5
Brute-force search: 27.6
Brute-force search: 27.7
Brute-force search: 27.8
Brute-force search: 27.9
Brute-force search: 28.0
Brute-force search: 28.1
Brute-force search: 28.2
Brute-force search: 28.3
Brute-force search: 28.4
Brute-force search: 28.5
Brute-force search: 28.6
Brute-force search: 28.7
Brute-force search: 28.8
Brute-force search: 28.9
Brute-force search: 29.0
Brute-force search: 29.1
Brute-force search: 29.2
Brute-force search: 29.3
Brute-force search: 29.4
Brute-force search: 29.5
Brute-force search: 29.6
Brute-force search: 29.7
Brute-force search: 29.8
Brute-force search: 29.9
Brute-force search: 30.0
Brute-force search: 30.1
Brute-force search: 30.2
Brute-force search: 30.3
Brute-force search: 30.4
Brute-force search: 30.5
Brute-force search: 30.6
Brute-force search: 30.7
Brute-force search: 30.8
Brute-force search: 30.9
Brute-force search: 31.0
Brute-force search: 31.1
Brute-force search: 31.2
Brute-force search: 31.3
Brute-force search: 31.4
Brute-force search: 31.5
Brute-force search: 31.6
Brute-force search: 31.7
Brute-force search: 31.8
Brute-force search: 31.9
Brute-force search: 32.0
Brute-force search: 32.1
Brute-force search: 32.2
Brute-force search: 32.3
Brute-force search: 32.4
Brute-force search: 32.5
Brute-force search: 32.6
Brute-force search: 32.7
Brute-force search: 32.8
Brute-force search: 32.9
Brute-force search: 33.0
Brute-force search: 33.1
Brute-force search: 33.2
Brute-force search: 33.3
Brute-force search: 33.4
Brute-force search: 33.5
Brute-force search: 33.6
Brute-force search: 33.7
Brute-force search: 33.8
Brute-force search: 33.9
Brute-force search: 34.0
Brute-force search: 34.1
Brute-force search: 34.2
Brute-force search: 34.3
Brute-force search: 34.4
Brute-force search: 34.5
Brute-force search: 34.6
Brute-force search: 34.7
Brute-force search: 34.8
Brute-force search: 34.9
Brute-force search: 35.0
Brute-force search: 35.1
Brute-force search: 35.2
Brute-force search: 35.3
Brute-force search: 35.4
Brute-force search: 35.5
Brute-force search: 35.6
Brute-force search: 35.7
Brute-force search: 35.8
Brute-force search: 35.9
Brute-force search: 36.0
Brute-force search: 36.1
Brute-force search: 36.2
Brute-force search: 36.3
Brute-force search: 36.4
Brute-force search: 36.5
Brute-force search: 36.6
Brute-force search: 36.7
Brute-force search: 36.8
Brute-force search: 36.9
Brute-force search: 37.0
Brute-force search: 37.1
Brute-force search: 37.2
Brute-force search: 37.3
Brute-force search: 37.4
Brute-force search: 37.5
Brute-force search: 37.6
Brute-force search: 37.7
Brute-force search: 37.8
Brute-force search: 37.9
Brute-force search: 38.0
Brute-force search: 38.1
Brute-force search: 38.2
Brute-force search: 38.3
Brute-force search: 38.4
Brute-force search: 38.5
Brute-force search: 38.6
Brute-force search: 38.7
Brute-force search: 38.8
Brute-force search: 38.9
Brute-force search: 39.0
Brute-force search: 39.1
Brute-force search: 39.2
Brute-force search: 39.3
Brute-force search: 39.4
Brute-force search: 39.5
Brute-force search: 39.6
Brute-force search: 39.7
Brute-force search: 39.8
Brute-force search: 39.9
Brute-force search: 40.0
Brute-force search: 40.1
Brute-force search: 40.2
Brute-force search: 40.3
Brute-force search: 40.4
Brute-force search: 40.5
Brute-force search: 40.6
Brute-force search: 40.7
Brute-force search: 40.8
Brute-force search: 40.9
Brute-force search: 41.0
Brute-force search: 41.1
Brute-force search: 41.2
Brute-force search: 41.3
Brute-force search: 41.4
Brute-force search: 41.5
Brute-force search: 41.6
Brute-force search: 41.7
Brute-force search: 41.8
Brute-force search: 41.9
Brute-force search: 42.0
Brute-force search: 42.1
Brute-force search: 42.2
Brute-force search: 42.3
Brute-force search: 42.4
Brute-force search: 42.5
Brute-force search: 42.6
Brute-force search: 42.7
Brute-force search: 42.8
Brute-force search: 42.9
Brute-force search: 43.0
Brute-force search: 43.1
Brute-force search: 43.2
Brute-force search: 43.3
Brute-force search: 43.4
Brute-force search: 43.5
Brute-force search: 43.6
Brute-force search: 43.7
Brute-force search: 43.8
Brute-force search: 43.9
Brute-force search: 44.0
Brute-force search: 44.1
Brute-force search: 44.2
Brute-force search: 44.3
Brute-force search: 44.4
Brute-force search: 44.5
Brute-force search: 44.6
Brute-force search: 44.7
Brute-force search: 44.8
Brute-force search: 44.9
Brute-force search: 45.0
Brute-force search: 45.1
Brute-force search: 45.2
Brute-force search: 45.3
Brute-force search: 45.4
Brute-force search: 45.5
Brute-force search: 45.6
Brute-force search: 45.7
Brute-force search: 45.8
Brute-force search: 45.9
Brute-force search: 46.0
Brute-force search: 46.1
Brute-force search: 46.2
Brute-force search: 46.3
Brute-force search: 46.4
Brute-force search: 46.5
Brute-force search: 46.6
Brute-force search: 46.7
Brute-force search: 46.8
Brute-force search: 46.9
Brute-force search: 47.0
Brute-force search: 47.1
Brute-force search: 47.2
Brute-force search: 47.3
Brute-force search: 47.4
Brute-force search: 47.5
Brute-force search: 47.6
Brute-force search: 47.7
Brute-force search: 47.8
Brute-force search: 47.9
Brute-force search: 48.0
Brute-force search: 48.1
Brute-force search: 48.2
Brute-force search: 48.3
Brute-force search: 48.4
Brute-force search: 48.5
Brute-force search: 48.6
Brute-force search: 48.7
Brute-force search: 48.8
Brute-force search: 48.9
Brute-force search: 49.0
Brute-force search: 49.1
Brute-force search: 49.2
Brute-force search: 49.3
Brute-force search: 49.4
Brute-force search: 49.5
Brute-force search: 49.6
Brute-force search: 49.7
Brute-force search: 49.8
Brute-force search: 49.9
Brute-force search: 50.0
Brute-force search: 50.1
Brute-force search: 50.2
Brute-force search: 50.3
Brute-force search: 50.4
Brute-force search: 50.5
Brute-force search: 50.6
Brute-force search: 50.7
Brute-force search: 50.8
Brute-force search: 50.9
Brute-force search: 51.0
Brute-force search: 51.1
Brute-force search: 51.2
Brute-force search: 51.3
Brute-force search: 51.4
Brute-force search: 51.5
Brute-force search: 51.6
Brute-force search: 51.7
Brute-force search: 51.8
Brute-force search: 51.9
Brute-force search: 52.0
Brute-force search: 52.1
Brute-force search: 52.2
Brute-force search: 52.3
Brute-force search: 52.4
Brute-force search: 52.5
Brute-force search: 52.6
Brute-force search: 52.7
Brute-force search: 52.8
Brute-force search: 52.9
Brute-force search: 53.0
Brute-force search: 53.1
Brute-force search: 53.2
Brute-force search: 53.3
Brute-force search: 53.4
Brute-force search: 53.5
Brute-force search: 53.6
Brute-force search: 53.7
Brute-force search: 53.8
Brute-force search: 53.9
Brute-force search: 54.0
Brute-force search: 54.1
Brute-force search: 54.2
Brute-force search: 54.3
Brute-force search: 54.4
Brute-force search: 54.5
Brute-force search: 54.6
Brute-force search: 54.7
Brute-force search: 54.8
Brute-force search: 54.9
Brute-force search: 55.0
Brute-force search: 55.1
Brute-force search: 55.2
Brute-force search: 55.3
Brute-force search: 55.4
Brute-force search: 55.5
Brute-force search: 55.6
Brute-force search: 55.7
Brute-force search: 55.8
Brute-force search: 55.9
Brute-force search: 56.0
Brute-force search: 56.1
Brute-force search: 56.2
Brute-force search: 56.3
Brute-force search: 56.4
Brute-force search: 56.5
Brute-force search: 56.6
Brute-force search: 56.7
Brute-force search: 56.8
Brute-force search: 56.9
Brute-force search: 57.0
Brute-force search: 57.1
Brute-force search: 57.2
Brute-force search: 57.3
Brute-force search: 57.4
Brute-force search: 57.5
Brute-force search: 57.6
Brute-force search: 57.7
Brute-force search: 57.8
Brute-force search: 57.9
Brute-force search: 58.0
Brute-force search: 58.1
Brute-force search: 58.2
Brute-force search: 58.3
Brute-force search: 58.4
Brute-force search: 58.5
Brute-force search: 58.6
Brute-force search: 58.7
Brute-force search: 58.8
Brute-force search: 58.9
Brute-force search: 59.0
Brute-force search: 59.1
Brute-force search: 59.2
Brute-force search: 59.3
Brute-force search: 59.4
Brute-force search: 59.5
Brute-force search: 59.6
Brute-force search: 59.7
Brute-force search: 59.8
Brute-force search: 59.9
Brute-force search: 60.0
Brute-force search: 60.1
Brute-force search: 60.2
Brute-force search: 60.3
Brute-force search: 60.4
Brute-force search: 60.5
Brute-force search: 60.6
Brute-force search: 60.7
Brute-force search: 60.8
Brute-force search: 60.9
Brute-force search: 61.0
Brute-force search: 61.1
Brute-force search: 61.2
Brute-force search: 61.3
Brute-force search: 61.4
Brute-force search: 61.5
Brute-force search: 61.6
Brute-force search: 61.7
Brute-force search: 61.8
Brute-force search: 61.9
Brute-force search: 62.0
Brute-force search: 62.1
Brute-force search: 62.2
Brute-force search: 62.3
Brute-force search: 62.4
Brute-force search: 62.5
Brute-force search: 62.6
Brute-force search: 62.7
Brute-force search: 62.8
Brute-force search: 62.9
Brute-force search: 63.0
Brute-force search: 63.1
Brute-force search: 63.2
Brute-force search: 63.3
Brute-force search: 63.4
Brute-force search: 63.5
Brute-force search: 63.6
Brute-force search: 63.7
Brute-force search: 63.8
Brute-force search: 63.9
Brute-force search: 64.0
Brute-force search: 64.1
Brute-force search: 64.2
Brute-force search: 64.3
Brute-force search: 64.4
Brute-force search: 64.5
Brute-force search: 64.6
Brute-force search: 64.7
Brute-force search: 64.8
Brute-force search: 64.9
Brute-force search: 65.0
Brute-force search: 65.1
Brute-force search: 65.2
Brute-force search: 65.3
Brute-force search: 65.4
Brute-force search: 65.5
Brute-force search: 65.6
Brute-force search: 65.7
Brute-force search: 65.8
Brute-force search: 65.9
Brute-force search: 66.0
Brute-force search: 66.1
Brute-force search: 66.2
Brute-force search: 66.3
Brute-force search: 66.4
Brute-force search: 66.5
Brute-force search: 66.6
Brute-force search: 66.7
Brute-force search: 66.8
Brute-force search: 66.9
Brute-force search: 67.0
Brute-force search: 67.1
Brute-force search: 67.2
Brute-force search: 67.3
Brute-force search: 67.4
Brute-force search: 67.5
Brute-force search: 67.6
Brute-force search: 67.7
Brute-force search: 67.8
Brute-force search: 67.9
Brute-force search: 68.0
Brute-force search: 68.1
Brute-force search: 68.2
Brute-force search: 68.3
Brute-force search: 68.4
Brute-force search: 68.5
Brute-force search: 68.6
Brute-force search: 68.7
Brute-force search: 68.8
Brute-force search: 68.9
Brute-force search: 69.0
Brute-force search: 69.1
Brute-force search: 69.2
Brute-force search: 69.3
Brute-force search: 69.4
Brute-force search: 69.5
Brute-force search: 69.6
Brute-force search: 69.7
Brute-force search: 69.8
Brute-force search: 69.9
Brute-force search: 70.0
Brute-force search: 70.1
Brute-force search: 70.2
Brute-force search: 70.3
Brute-force search: 70.4
Brute-force search: 70.5
Brute-force search: 70.6
Brute-force search: 70.7
Brute-force search: 70.8
Brute-force search: 70.9
Brute-force search: 71.0
Brute-force search: 71.1
Brute-force search: 71.2
Brute-force search: 71.3
Brute-force search: 71.4
Brute-force search: 71.5
Brute-force search: 71.6
Brute-force search: 71.7
Brute-force search: 71.8
Brute-force search: 71.9
Brute-force search: 72.0
Brute-force search: 72.1
Brute-force search: 72.2
Brute-force search: 72.3
Brute-force search: 72.4
Brute-force search: 72.5
Brute-force search: 72.6
Brute-force search: 72.7
Brute-force search: 72.8
Brute-force search: 72.9
Brute-force search: 73.0
Brute-force search: 73.1
Brute-force search: 73.2
Brute-force search: 73.3
Brute-force search: 73.4
Brute-force search: 73.5
Brute-force search: 73.6
Brute-force search: 73.7
Brute-force search: 73.8
Brute-force search: 73.9
Brute-force search: 74.0
Brute-force search: 74.1
Brute-force search: 74.2
Brute-force search: 74.3
Brute-force search: 74.4
Brute-force search: 74.5
Brute-force search: 74.6
Brute-force search: 74.7
Brute-force search: 74.8
Brute-force search: 74.9
Brute-force search: 75.0
Brute-force search: 75.1
Brute-force search: 75.2
Brute-force search: 75.3
Brute-force search: 75.4
Brute-force search: 75.5
Brute-force search: 75.6
Brute-force search: 75.7
Brute-force search: 75.8
Brute-force search: 75.9
Brute-force search: 76.0
Brute-force search: 76.1
Brute-force search: 76.2
Brute-force search: 76.3
Brute-force search: 76.4
Brute-force search: 76.5
Brute-force search: 76.6
Brute-force search: 76.7
Brute-force search: 76.8
Brute-force search: 76.9
Brute-force search: 77.0
Brute-force search: 77.1
Brute-force search: 77.2
Brute-force search: 77.3
Brute-force search: 77.4
Brute-force search: 77.5
Brute-force search: 77.6
Brute-force search: 77.7
Brute-force search: 77.8
Brute-force search: 77.9
Brute-force search: 78.0
Brute-force search: 78.1
Brute-force search: 78.2
Brute-force search: 78.3
Brute-force search: 78.4
Brute-force search: 78.5
Brute-force search: 78.6
Brute-force search: 78.7
Brute-force search: 78.8
Brute-force search: 78.9
Brute-force search: 79.0
Brute-force search: 79.1
Brute-force search: 79.2
Brute-force search: 79.3
Brute-force search: 79.4
Brute-force search: 79.5
Brute-force search: 79.6
Brute-force search: 79.7
Brute-force search: 79.8
Brute-force search: 79.9
Brute-force search: 80.0
Brute-force search: 80.1
Brute-force search: 80.2
Brute-force search: 80.3
Brute-force search: 80.4
Brute-force search: 80.5
Brute-force search: 80.6
Brute-force search: 80.7
Brute-force search: 80.8
Brute-force search: 80.9
Brute-force search: 81.0
Brute-force search: 81.1
Brute-force search: 81.2
Brute-force search: 81.3
Brute-force search: 81.4
Brute-force search: 81.5
Brute-force search: 81.6
Brute-force search: 81.7
Brute-force search: 81.8
Brute-force search: 81.9
Brute-force search: 82.0
Brute-force search: 82.1
Brute-force search: 82.2
Brute-force search: 82.3
Brute-force search: 82.4
Brute-force search: 82.5
Brute-force search: 82.6
Brute-force search: 82.7
Brute-force search: 82.8
Brute-force search: 82.9
Brute-force search: 83.0
Brute-force search: 83.1
Brute-force search: 83.2
Brute-force search: 83.3
Brute-force search: 83.4
Brute-force search: 83.5
Brute-force search: 83.6
Brute-force search: 83.7
Brute-force search: 83.8
Brute-force search: 83.9
Brute-force search: 84.0
Brute-force search: 84.1
Brute-force search: 84.2
Brute-force search: 84.3
Brute-force search: 84.4
Brute-force search: 84.5
Brute-force search: 84.6
Brute-force search: 84.7
Brute-force search: 84.8
Brute-force search: 84.9
Brute-force search: 85.0
Brute-force search: 85.1
Brute-force search: 85.2
Brute-force search: 85.3
Brute-force search: 85.4
Brute-force search: 85.5
Brute-force search: 85.6
Brute-force search: 85.7
Brute-force search: 85.8
Brute-force search: 85.9
Brute-force search: 86.0
Brute-force search: 86.1
Brute-force search: 86.2
Brute-force search: 86.3
Brute-force search: 86.4
Brute-force search: 86.5
Brute-force search: 86.6
Brute-force search: 86.7
Brute-force search: 86.8
Brute-force search: 86.9
Brute-force search: 87.0
Brute-force search: 87.1
Brute-force search: 87.2
Brute-force search: 87.3
Brute-force search: 87.4
Brute-force search: 87.5
Brute-force search: 87.6
Brute-force search: 87.7
Brute-force search: 87.8
Brute-force search: 87.9
Brute-force search: 88.0
Brute-force search: 88.1
Brute-force search: 88.2
Brute-force search: 88.3
Brute-force search: 88.4
Brute-force search: 88.5
Brute-force search: 88.6
Brute-force search: 88.7
Brute-force search: 88.8
Brute-force search: 88.9
Brute-force search: 89.0
Brute-force search: 89.1
Brute-force search: 89.2
Brute-force search: 89.3
Brute-force search: 89.4
Brute-force search: 89.5
Brute-force search: 89.6
Brute-force search: 89.7
Brute-force search: 89.8
Brute-force search: 89.9
Brute-force search: 90.0
Brute-force search: 90.1
Brute-force search: 90.2
Brute-force search: 90.3
Brute-force search: 90.4
Brute-force search: 90.5
Brute-force search: 90.6
Brute-force search: 90.7
Brute-force search: 90.8
Brute-force search: 90.9
Brute-force search: 91.0
Brute-force search: 91.1
Brute-force search: 91.2
Brute-force search: 91.3
Brute-force search: 91.4
Brute-force search: 91.5
Brute-force search: 91.6
Brute-force search: 91.7
Brute-force search: 91.8
Brute-force search: 91.9
Brute-force search: 92.0
Brute-force search: 92.1
Brute-force search: 92.2
Brute-force search: 92.3
Brute-force search: 92.4
Brute-force search: 92.5
Brute-force search: 92.6
Brute-force search: 92.7
Brute-force search: 92.8
Brute-force search: 92.9
Brute-force search: 93.0
Brute-force search: 93.1
Brute-force search: 93.2
Brute-force search: 93.3
Brute-force search: 93.4
Brute-force search: 93.5
Brute-force search: 93.6
Brute-force search: 93.7
Brute-force search: 93.8
Brute-force search: 93.9
Brute-force search: 94.0
Brute-force search: 94.1
Brute-force search: 94.2
Brute-force search: 94.3
Brute-force search: 94.4
Brute-force search: 94.5
Brute-force search: 94.6
Brute-force search: 94.7
Brute-force search: 94.8
Brute-force search: 94.9
Brute-force search: 95.0
Brute-force search: 95.1
Brute-force search: 95.2
Brute-force search: 95.3
Brute-force search: 95.4
Brute-force search: 95.5
Brute-force search: 95.6
Brute-force search: 95.7
Brute-force search: 95.8
Brute-force search: 95.9
Brute-force search: 96.0
Brute-force search: 96.1
Brute-force search: 96.2
Brute-force search: 96.3
Brute-force search: 96.4
Brute-force search: 96.5
Brute-force search: 96.6
Brute-force search: 96.7
Brute-force search: 96.8
Brute-force search: 96.9
Brute-force search: 97.0
Brute-force search: 97.1
Brute-force search: 97.2
Brute-force search: 97.3
Brute-force search: 97.4
Brute-force search: 97.5
Brute-force search: 97.6
Brute-force search: 97.7
Brute-force search: 97.8
Brute-force search: 97.9
Brute-force search: 98.0
Brute-force search: 98.1
Brute-force search: 98.2
Brute-force search: 98.3
Brute-force search: 98.4
Brute-force search: 98.5
Brute-force search: 98.6
Brute-force search: 98.7
Brute-force search: 98.8
Brute-force search: 98.9
Brute-force search: 99.0
Brute-force search: 99.1
Brute-force search: 99.2
Brute-force search: 99.3
Brute-force search: 99.4
Brute-force search: 99.5
Brute-force search: 99.6
Brute-force search: 99.7
Brute-force search: 99.8
Brute-force search: 99.9
Brute-force search: 100.0
Brute-force search: 100.1
can not founded in 100 attempts
Traceback (most recent call last):
File "hitomi_downloader", line 1192, in download_hitomi
File "hitomi_downloader", line 1628, in ehen_imgs
TypeError: 'NoneType' object is not iterable

Read reader FAILED - auto
Traceback (most recent call last):
File "hitomi_downloader", line 1204, in download_hitomi
TypeError: 'NoneType' object is not iterable

Size (https://i.hitomi.la/galleries/644054/17.jpg): 0
Size (https://i.hitomi.la/galleries/644054/17.jpg): 0
Size (https://i.hitomi.la/galleries/644054/17.jpg): 0
size is too small; test:xxx
Traceback (most recent call last):
File "hitomi_downloader", line 1156, in download_hitomi
File "hitomi_downloader", line 167, in pop_img
File "downloader", line 234, in read_html
File "urllib3\poolmanager", line 146, in urlopen
File "urllib3\connectionpool", line 258, in urlopen
File "urllib3\util\retry", line 132, in increment
File "urllib3\connectionpool", line 240, in urlopen
File "urllib3\connectionpool", line 147, in _make_request
File "urllib3\connectionpool", line 363, in _validate_conn
File "urllib3\connection", line 172, in connect
File "urllib3\connection", line 83, in _new_conn
NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x07EF0630>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

Traceback (most recent call last):
File "hitomi_downloader", line 1178, in download_hitomi
File "hiyobi_downloader", line 11, in pop_img_hiyobi
IndexError: list index out of range

get imgs from e(x)hentai: 644054
ehen_imgs(ex:True, url:644054)
Find_ehen(id:644054, ex:True)
Find in heroku...
not found in heroku
max_page = 30883
Brute-force search: 1
Brute-force search: 2
Brute-force search: 3
Brute-force search: 4
Brute-force search: 5
Brute-force search: 6
Brute-force search: 7
Brute-force search: 8
Brute-force search: 9
Brute-force search: 10

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by wkd284** [comment]
> 
> 
> 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

문의자는아닙니다만...

시도 결과 다운이 가능합니다.

-------------------------
[Tatsu Tairagi] koi tamesi (644054)

version: 2.6
platform: Windows-10-10.0.17134
gal_num: https://hitomi.la/galleries/644054.html
dir: hitomi_downloaded\[Tatsu Tairagi] koi tamesi (644054)
zip: 
type: hitomi
artist: Tatsu Tairagi
url: https://hitomi.la/galleries/644054.html
valid: True
done: True
range: None
range_p: None
single: False
time: 1552375759.21 (Mar 12)
tags: []


[Gallery]
갤러리 넘버: 644054

제목: koi tamesi

작가: tatsu tairagi

그룹: N/A

타입: manga

시리즈: N/A

캐릭터: N/A

태그: female:defloration, female:kimono

언어: Korean


[File Names]
[0001] hitomi_downloaded\[Tatsu Tairagi] koi tamesi (644054)\17.jpg
[0002] hitomi_downloaded\[Tatsu Tairagi] koi tamesi (644054)\P177.jpg
[0003] hitomi_downloaded\[Tatsu Tairagi] koi tamesi (644054)\P178.jpg
[0004] hitomi_downloaded\[Tatsu Tairagi] koi tamesi (644054)\P179.jpg
[0005] hitomi_downloaded\[Tatsu Tairagi] koi tamesi (644054)\P180.jpg
[0006] hitomi_downloaded\[Tatsu Tairagi] koi tamesi (644054)\P181.jpg
[0007] hitomi_downloaded\[Tatsu Tairagi] koi tamesi (644054)\P182.jpg
[0008] hitomi_downloaded\[Tatsu Tairagi] koi tamesi (644054)\P183.jpg
[0009] hitomi_downloaded\[Tatsu Tairagi] koi tamesi (644054)\P184.jpg
[0010] hitomi_downloaded\[Tatsu Tairagi] koi tamesi (644054)\P185.jpg
[0011] hitomi_downloaded\[Tatsu Tairagi] koi tamesi (644054)\P186.jpg
[0012] hitomi_downloaded\[Tatsu Tairagi] koi tamesi (644054)\P187.jpg
[0013] hitomi_downloaded\[Tatsu Tairagi] koi tamesi (644054)\P188.jpg
[0014] hitomi_downloaded\[Tatsu Tairagi] koi tamesi (644054)\P189.jpg
[0015] hitomi_downloaded\[Tatsu Tairagi] koi tamesi (644054)\P190.jpg
[0016] hitomi_downloaded\[Tatsu Tairagi] koi tamesi (644054)\P191.jpg
[0017] hitomi_downloaded\[Tatsu Tairagi] koi tamesi (644054)\P192.jpg


[URLs]
[0001] https://la.hitomi.la/galleries/644054/17.jpg
[0002] https://la.hitomi.la/galleries/644054/P177.jpg
[0003] https://la.hitomi.la/galleries/644054/P178.jpg
[0004] https://la.hitomi.la/galleries/644054/P179.jpg
[0005] https://la.hitomi.la/galleries/644054/P180.jpg
[0006] https://la.hitomi.la/galleries/644054/P181.jpg
[0007] https://la.hitomi.la/galleries/644054/P182.jpg
[0008] https://la.hitomi.la/galleries/644054/P183.jpg
[0009] https://la.hitomi.la/galleries/644054/P184.jpg
[0010] https://la.hitomi.la/galleries/644054/P185.jpg
[0011] https://la.hitomi.la/galleries/644054/P186.jpg
[0012] https://la.hitomi.la/galleries/644054/P187.jpg
[0013] https://la.hitomi.la/galleries/644054/P188.jpg
[0014] https://la.hitomi.la/galleries/644054/P189.jpg
[0015] https://la.hitomi.la/galleries/644054/P190.jpg
[0016] https://la.hitomi.la/galleries/644054/P191.jpg
[0017] https://la.hitomi.la/galleries/644054/P192.jpg


[Messages]
********************************
Gallery number : 644054
Number of Threads : 64
********************************
Size (https://la.hitomi.la/galleries/644054/17.jpg): 1075779
FINAL SERVER : hitomi
ehen_url : None
imgs: 17
get_title__

Title :
[Tatsu Tairagi] koi tamesi (644054)

done : https://hitomi.la/galleries/644054.html
-------------------------

**Comment by rlacks1237** [comment]
감사합니다
