### ISSUE TITLE
각 화들의 숫자만 나오게 해주실 수 있나요? (작품명 안나오게)

### ISSUE THREAD

**Issue by karnies** [KurtBestor/Hitomi-Downloader-issues#625]
안녕하세요. 정말 감사히 잘 쓰고 있습니다.

간혹 만화중에 다음과 같이 각 편의 이름이 바뀌거나 오타가 있어서 순서가 뒤바뀌는 경우가 있어요.
![image](https://user-images.githubusercontent.com/46523031/54262557-c9485700-45b1-11e9-9b7d-3f92d87a94e7.png)

그래서 혹시, 제목은 안나오고, 1화, 2화, ...... , 10화, 11화 이런식으로 폴더 이름을 구성하게 옵션을 추가해준다거나 그럴실 계획은 없나요?

감사합니다.

**Comment by KurtBestor** [comment]
한 권이 두 개로 나뉘어 있다던가, 권 / 화가 섞여 있거나, 특별화 같은 게 있어서 고치지 않을 계획이에요.
