### ISSUE TITLE
망가쇼미 다운이 불가현상?

### ISSUE THREAD

**Issue by aksghkqhrl** [KurtBestor/Hitomi-Downloader-issues#626]
"읽는 중..." 으로는 되지만 10분정도 지나면 
![20190313_184048](https://user-images.githubusercontent.com/47558641/54269024-db30f680-45bf-11e9-92ea-768198ba9613.png)
이렇게 다운이 안됩니다.

바로 아래의 망가쇼미 다운이 안된다는 글에서 테스트버전을 사용하였습니다.

**Comment by hhhssj** [comment]
마우스 오른쪽 선택 화 다운로드는 되고 해당화를 직접 주소넣고 하면 안되는 것 같네요.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by hhhssj** [comment]
테스트해보니 해당화를 직접 주소 넣고해도 잘 다운 됩니다. 감사합니다.

**Comment by aksghkqhrl** [comment]
항상 감사합니다!
