### ISSUE TITLE
goodbyeDPI 오류문의 

### ISSUE THREAD

**Issue by fdaga** [KurtBestor/Hitomi-Downloader-issues#628]
기본 데이터 를 다운 받으면 이렇게 떠요
![1](https://user-images.githubusercontent.com/46779614/54273682-c0637f80-45c9-11e9-93a1-14dff746aacc.PNG)

![5](https://user-images.githubusercontent.com/46779614/54283340-21e31880-45e1-11e9-9f8d-27afc30c068b.PNG)

**Comment by KurtBestor** [comment]
다시 시도해도 안되나요?

**Comment by fdaga** [comment]
몇번다시시도 해서 해결했습니다.
