### ISSUE TITLE
다운로더가 작동도중에 꺼집니다,

### ISSUE THREAD

**Issue by jaejunghan** [KurtBestor/Hitomi-Downloader-issues#629]
대략 500개의 목록이 대부분이 픽시브인데 동시에 다시 제다운을 했습니다,

300개까지 다운이 완료되던 도중, 갑자기 꺼지고 컴퓨터폴더 에는 저장이 되있으나프로그램에는 전에 저장 된 상태로 나와있습니다.

왜이런가요?

쓰래드를 2로 낮추어도 이런문제가 발생합니다,,,

컴퓨터 amd2600과 16램입니다

**Comment by KurtBestor** [comment]
참고해주세요: #170
