### ISSUE TITLE
히토미에서 밴당하면 나타나는 증상이 어떻게 되나요?

### ISSUE THREAD

**Issue by xlxlzl123** [KurtBestor/Hitomi-Downloader-issues#63]
스레드를 18 정도로 두고 쓰고 있었는데

갑자기 다운 속도가 몇초에 0.1mb 씩 받아지는데 밴 당한건가요?

별로 받은 것 같지는 않은데 이상하네요

공유기 사용중인데 해결방법이 있을까요?

**Comment by KurtBestor** [comment]
히토미에서 몇만개 다운받아도 문제 없던 걸로 기억합니다.
아예 다운로드가 되지 않는 게 아닌, 속도가 느려지는 증상이라면 통신사에서 제한을 거는 게 아닐까요?

여기에서 속도 확인해보세요:
https://fast.com/en/

**Comment by xlxlzl123** [comment]
아 그냥 용량이 찬거였습니다. 감사합니다/
