### ISSUE TITLE
픽시브 우고이라 zip 저장시 animation.json

### ISSUE THREAD

**Issue by usagicore** [KurtBestor/Hitomi-Downloader-issues#630]
꿀뷰같은건 이 파일을 읽어서 우고이라를 zip파일로 저장해도 알아서 딜레이 맞춰서 재생하는데 압축파일에 이거 같이 끼워줄수 있을까요

https://www.pixiv.net/member_illust.php?mode=medium&illust_id=49319675
[animation.json.zip](https://github.com/KurtBestor/Hitomi-Downloader-issues/files/2968559/animation.json.zip)

**Comment by KurtBestor** [comment]
GIF나 WEBP 안 쓰는 이유가 있나요?
