### ISSUE TITLE
Bilibili 비디오 컬렉션 다운로드시 목록 전체 다운로드에 문제가 있음.

### ISSUE THREAD

**Issue by sandoai** [KurtBestor/Hitomi-Downloader-issues#631]
대단히 수고가 많으십니다.
아래 링크에 비디오 컬렉션 목록이 걸려있어서 동영상 다운로드 시도시
첨부의 이미지와 같이 전체 목록중 두개만 다운로드가 진행되고 나머지는 진행이 되지 않는 증상이 있습니다. 여유가 있을때, 확인을 부탁드립니다.
감사합니다
![ca](https://user-images.githubusercontent.com/48623629/54476232-29532d80-483e-11e9-8f11-75c5d1d7a5e6.PNG)

https://www.bilibili.com/video/av25066634

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/52, https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/418

**Comment by sandoai** [comment]
#52 참고하여 재 시도 하였으나, 하나만 다운로드 됩니다.
https://www.bilibili.com/video/av25066634

![캡처](https://user-images.githubusercontent.com/48623629/54506564-54459a80-4980-11e9-85d8-cbd3e2239d8e.PNG)

아래 링크로 시도하면 두개로 되네요.
https://www.bilibili.com/video/av25066634/?p=2

확인을 부탁드립니다. 감사합니다.

**Comment by KurtBestor** [comment]
다음과 같이 입력하면 두번째 영상만 받아요:
https://www.bilibili.com/video/av25066634/?p=2

다음과 같이 입력하면 세번째 영상만 받아요:
https://www.bilibili.com/video/av25066634/?p=3
