### ISSUE TITLE
플로팅 미리보기 여러장 설정 시 점점 커지는 현상

### ISSUE THREAD

**Issue by dnfnsisb** [KurtBestor/Hitomi-Downloader-issues#633]
![Cap 2019-03-17 21-59-22-640](https://user-images.githubusercontent.com/48648545/54491228-01c49980-4900-11e9-960c-9097694e5c95.jpg)

안녕하세요? 좋은 프로그램을 만들여 주셔서 감사합니다.

히토미 다운로드 하는데 사용하고 있는데

히토미 서처 에서 플로팅 여러장 미리보기 설정 시 스크린샷 처럼 점점 커지는 현상이 발생합니다.
사실 상 2번째 장 이후 부터는 너무 커져서 사용이 어렵습니다.

혹시 괜찮으실 때 확인해주시면 감사하겠습니다.

- 플로팅 미리보기 장수 (2,3,4장)에 관계없이 전부 동이한 현상이 일어납니다.

- 플로팅 미리보기 사이즈 (Small, Medium, Large) 경우 커지는 현상은 동일하나 
시작 사이즈가 Small 이면 마지막 4번째 사진은 Large에 비해 상대적으로 작습니다. 

히토미 콘솔 : 
Python 2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:22:17) [MSC v.1500 32 bit (Intel)]

QtGui.QApplication.desktop().screen().rect() 
PyQt4.QtCore.QRect(0, 0, 7680, 2160)

number = QtGui.QApplication.desktop().screenNumber(QtGui.QCursor.pos()) 

number, QtGui.QApplication.desktop().screen(number).rect() 
(0, PyQt4.QtCore.QRect(0, 0, 7680, 2160))

1번 모니터
QtGui.QCursor.pos() 
PyQt4.QtCore.QPoint(3725, 1357)

2번 모니터
QtGui.QCursor.pos() 
PyQt4.QtCore.QPoint(-1188, 875)

PC 상태 
![Cap 2019-03-17 22-02-12-885](https://user-images.githubusercontent.com/48648545/54491269-67188a80-4900-11e9-9087-9f655d1b7969.jpg)

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by dnfnsisb** [comment]
안녕하세요? 
플로팅 미리보기 잘 나옵니다. 감사합니다!

고치는데 시간내주셔서 고맙습니다 :)
