### ISSUE TITLE
다운로더에 저장되어있던 리스트가 사라졌는데 복구 가능한가요?

### ISSUE THREAD

**Issue by juddem002** [KurtBestor/Hitomi-Downloader-issues#637]
여태 다운로드 했었던 리스트가 안 뜨고 아래 안테나? 같은 부분 로딩이 계속 되고 있거든요.

뭐가 문제인지 모르겠는데...어떻게 해야 할까요?

**Comment by KurtBestor** [comment]
안테나가 뭔가요?

더 자세히 설명해주시거나 스크린샷 찍어서 보여주세요.

**Comment by juddem002** [comment]
![안테나](https://user-images.githubusercontent.com/45240670/54638278-05a61680-4ace-11e9-9830-5dce10b8293a.PNG)

잘 쓰고 저장&종료 했었는데 며칠 뒤에 다시 켜니까 리스트 싹 날아가고 저기 초록색 바만 좌에서 우로 계속 로딩되는거마냥 이동하고 있더라구요... 흑흑

만약 리스트를 못살린다면 리스트에 없더라도 다운로드 폴더에 같은 이름이 있으면 자동으로 중복인식하는지 알려주시면 감사하겠습니다.

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/598

**Comment by juddem002** [comment]
> 참고해주세요: #598
확인해봤는데 [실행파일 이름].ini 은 있는데 backup.ini 파일은 보이질 않네요 ㅠㅠ
[실행파일 이름].ini 파일이 남아있는데 읽지 못하고 있습니다 어떡하죠 ㅠㅠ

**Comment by KurtBestor** [comment]
그 이후에 다시 저장했다면 덮어씌워져서 사라져요.
