### ISSUE TITLE
질문)이헨, 익헨 관련

### ISSUE THREAD

**Issue by wlehd44** [KurtBestor/Hitomi-Downloader-issues#638]
안녕하세요. 관리자님 다운로더 잘 사용하고 있습니다.

사용 중 몇가지 의문이 있어 문의 드려요
1. 이헨,익헨에서 다운로드를 위해 주소를 기입하는데 다운이 안됩니다. 제가 잘못 사용중인건가요 아니면 다른 셋팅이 필요한건가요?
 예)https://e-hentai.org/g/618119/bef0a176d2/
2. 만약 위 주소로 기입하고 됩다면 이헨.익헨에서 따로 해줘야하는 것이 있는건가요? 포인트라던지

문의에 답변을 주시면 감사하겠습니다

**Comment by hellsung** [comment]
저도 같은 증상입니다.
![1](https://user-images.githubusercontent.com/48718589/54604017-1718ff80-4a89-11e9-8379-9616992999dd.png)
![2음](https://user-images.githubusercontent.com/48718589/54604018-18e2c300-4a89-11e9-96b5-eda430d76d65.png)

**Comment by Rounlet** [comment]
hellsung <- 저도 이 분과 같은 상황입니다. 익헨 주소를 넣어도 invalid가 뜨네요.

익헨에서 막은걸까요?

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by hellsung** [comment]
![EodzbTJf](https://user-images.githubusercontent.com/48718589/54614205-5f431c80-4a9f-11e9-98d6-51d7851ddca2.png)
오오 감사합니다!!

**Comment by wlehd44** [comment]
감사합니다 확인 완료했습니다
