### ISSUE TITLE
질문)이헨에 없고, 익헨에 있는 경우 다운 진행이 안됩니다

### ISSUE THREAD

**Issue by wlehd44** [KurtBestor/Hitomi-Downloader-issues#639]
귀찮게 해드린거 같아 죄송합니다

이번에도 아래와 같은 경우 발생해 이렇게 문의 드립니다

위 제목처럼 이헨(e-hentai.org)과 익헨(exhentai.org)에 동시에 존재한 자료인 경우에 주소를 이헨과 익헨 두 주소 중 어느 하나의 주소만 기입해도 다운이 가능합니다

예)https://e-hentai.org/g/618119/bef0a176d2/
     https://exhentai.org/g/618119/bef0a176d2/

하지만 이헨에는 존재하지 않고 익헨에만 존재하는 자료는 다운이 진행하지않고 '0'에 머물기만합니다

예)https://exhentai.org/g/1110773/84b2c2790d/

그저 렉이나 다른 요인이 있을 까, 1시간 동안 대기하고 있지만 별다른 변화는 없습니다

![캡처](https://user-images.githubusercontent.com/48654593/54629239-7d6a4600-4aba-11e9-851d-9029b7cd5abd.PNG)

정보가 필요하시면 말씀해주세요

**Comment by Rounlet** [comment]
저도 같은 현상입니다,

https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/638
어제 여기서 익헨 다운로드가 안 되는거에 대한 테스트 버전을 내주셨는데

https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview
이 수정본으로 다운로드를 계속해봐도 진행이 안되네요..

![gg](https://user-images.githubusercontent.com/47098778/54680431-2bbecb80-4b4d-11e9-9fff-acf41f083018.png)

**Comment by wlehd44** [comment]
지금은 정상적으로 다운이 가능합니다 어쩨서 그런건지 원인은 잘 모르겠습니다 
당시에는 안됬는데 오늘 컴퓨터 키고 프로그램 키니 자동으로 잘 받아지네요;;;
내용에 혼선을 줘서 죄송합니다
