### ISSUE TITLE
익헨의 논H 작품이 받아지지 않습니다.

### ISSUE THREAD

**Issue by lekim56** [KurtBestor/Hitomi-Downloader-issues#640]
주소 입력후 다운로드 누르니까 오류가 뜨네요.
오류메세지 주소에 앞쪽에 히토미 번호가 뜨는걸 보니, 히토미에 없어서 다운 못받는게 아닌가 싶습니다.
혹시 이것도 다운 가능하게 해주실 수 있을까요?

**Comment by wkd284** [comment]
아마 실패 정보랑 주소를 주셔야 정확한 답변을 얻을수 있지 않을까요?

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/643

**Comment by lekim56** [comment]
아주 잘 됩니다. 정말 감사합니다. ^^
