### ISSUE TITLE
망가쇼미 또 막혔나보네요

### ISSUE THREAD

**Issue by jinjins7** [KurtBestor/Hitomi-Downloader-issues#642]
다운로드가 안되고 들어가도 안들어가지네요.
찾아보니 직통ip있던데, 이것도 다운가능목록에 추가해주실 수 있나요?
https://188.214.128.5/
https://93.115.27.87/
만화 들가면 이런식으로 되네요
https://93.115.27.87/bbs/page.php?hid=manga_detail&manga_name=%ED%98%84%EC%9E%90%EC%9D%98+%EC%A0%9C%EC%9E%90%EB%A5%BC+%EC%9E%90%EC%B9%AD%ED%95%98%EB%8A%94+%ED%98%84%EC%9E%90
https://188.214.128.5/bbs/page.php?hid=manga_detail&manga_name=%ED%98%84%EC%9E%90%EC%9D%98+%EC%A0%9C%EC%9E%90%EB%A5%BC+%EC%9E%90%EC%B9%AD%ED%95%98%EB%8A%94+%ED%98%84%EC%9E%90

**Comment by karnies** [comment]
mangashow3.me 로 접속 되네요.

**Comment by jinjins7** [comment]
mangashow3.me 로 접속만 되지 다운은 안됩니다

**Comment by wlehd44** [comment]
안되는 현상이 있었다가 지금은 정상적으로 됩니다
안됬던게 갑자기 되서 저도 좀 의아하지만 저의 상황을 알려드리겠습니다

1. 주소는 mangashow5.me 사용 하시고
2. GoodByeDPI GUI 라는 프로그램 사용하고 있습니다
3. 대량으로 사용 중인 게 아닌가 합니다. 제가 다운받을 때 한 20개, 30개 만화을 다운 받고 있었습니다

위 상황에서 안되다가 시간이 지나니 자동으로 해결이 됬습니다

**Comment by wlehd44** [comment]
GoodByeDPI GUI 버전은 좀 낮은걸로 사용하세요 최근거는 잘 안되네요

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by alskdh** [comment]
> 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

잘 작동하는 것 같습니다

**Comment by jinjins7** [comment]
> 테스트 부탁 드려요 : https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

잘 작동하네요. 감사합니다.
