### ISSUE TITLE
사운드클라우드 mp3 받을때 질문

### ISSUE THREAD

**Issue by tofhdns1** [KurtBestor/Hitomi-Downloader-issues#644]
![20190321_004](https://user-images.githubusercontent.com/48782565/54734232-80ac2180-4be1-11e9-945e-e06a1741cd21.jpg)

저거 사진처럼 보이는 그림파일도 mp3 커버 태그로 저장해서 받을수있나요 
안된다면 저거 사진도 같이 다운받는쪽이라도 될까요

**Comment by KurtBestor** [comment]
`옵션` - `설정` - `고급 설정` - `음악 파일에 앨범아트 삽입` 에서 설정하실 수 있어요.

테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by tofhdns1** [comment]
> `옵션` - `설정` - `고급 설정` - `음악 파일에 앨범아트 삽입` 에서 설정하실 수 있어요.
> 
> 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

2개 받아봤는데 잘돼요 감사합니다
