### ISSUE TITLE
'완료된 작업 모두 제거' 기능 추가 옵션 건의입니다. 

### ISSUE THREAD

**Issue by hitoto77** [KurtBestor/Hitomi-Downloader-issues#646]
픽시브에서 한 작가의 작품들을 일괄 다운받고 몇가지 작품들을 추려서 삭제했습니다.
그 뒤 '완료된 작업 모두 제거'를 한 뒤, 다시 해당 작가의 링크로 일괄 받기 시전 시
삭제된 파일도 다시 다운로드 됩니다.

'완료된 작업 모두 제거'를 할 때 '잠금' 옵션을 만들어서 
완료된 작업 전체 제거 할 경우에도 '잠금'된 항목은 유지 될 수 있으면 좋겠습니다.
아니면 이미 있는 '태그'에 앞서 말한 '잠금' 기능을 추가해도 되지 않을까 싶습니다.

이 기능 있다면 개발자님의 프로그램을 픽시브 구독/관리 프로그램으로도 사용 할 수 있을 것 같아 굉장히 유용할 것 같습니다.

항상 잘 쓰고 있습니다. 감사합니다^^

**Comment by KurtBestor** [comment]
![image](https://user-images.githubusercontent.com/14768120/55283354-31fa4680-539c-11e9-918c-63eeed60bff2.png)

테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by hitoto77** [comment]
제가 너무 늦었네요...! 이미 정식 빌드에 올라갔군요. 테스트 해본 결과 이상 없습니다!
추가해주셔서 감사합니다!
