### ISSUE TITLE
자동 저장기능에 오류가 있는거같습니다.

### ISSUE THREAD

**Issue by aksghkqhrl** [KurtBestor/Hitomi-Downloader-issues#647]
![20190322_012814](https://user-images.githubusercontent.com/47558641/54768330-44f57400-4c42-11e9-8c8f-9292708c911d.png)

30분 간격으로 자동저장 오류가 있는거같아요 확인 부탁드리겠습니다!

![20190322_045739](https://user-images.githubusercontent.com/47558641/54781240-16d25d00-4c5f-11e9-9d3c-96d2487b4490.png)
그리고 노트북 사용중에 다운로드 받은 후 저장&종료시 이런 오류가 나옵니다.

일반 종료를 사용하면 재시작시 받은 리스트가 사라집니다.

항상 수고하십니다. 감사합니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview
