### ISSUE TITLE
페이지 내에 있는 망가들 다운로드 질문

### ISSUE THREAD

**Issue by vaindog** [KurtBestor/Hitomi-Downloader-issues#648]
예를들어 https://e-hentai.org/?page=1 이라고 치면 페이지 1에 나와있는 모든 자료를 받는건 불가능 한가요?
그리고 이헨 로그인 기능은 없나요?

**Comment by KurtBestor** [comment]
네, 너무 많이 다운로드하면 일시적으로 IP 밴 먹어요.
