### ISSUE TITLE
마루마루에서 동시에 여러 만화 다운로드시...

### ISSUE THREAD

**Issue by myBLV** [KurtBestor/Hitomi-Downloader-issues#65]
여러 만화 다운로드시 (zip 압축,원본삭제 옵션 사용) 종종 다른 만화와 섞여서 압축되네요.

예를들어 A와 B 만화를 동시에 다운로드하면 압축된 A만화 10화 부분에 B만화의 10화가 섞여서 압축 됩니다. 

2.2a 기준 입니다. 지금까지 썻을때는 이런 경우가 없었는데 이 버전의 경우에 대략 6개의 결과물중에 4개의 결과물이 이렇게 되었습니다.

**Comment by KurtBestor** [comment]
2.2b 버전에서 해결되었습니다.
