### ISSUE TITLE
관리자님 프로그램관련 문의드립니다

### ISSUE THREAD

**Issue by sangonkim** [KurtBestor/Hitomi-Downloader-issues#650]
@KurtBestor  
파이선 공부하는 학생입니다. 소스관련해서 질문좀 하고 싶은데 연락가능한 방법이 있을까요?

**Comment by KurtBestor** [comment]
이미 연락하고 계시네요. 여기에 문의해주세요.

**Comment by sangonkim** [comment]
답장 주셔서 감사합니다! 제가 이 프로그램을 꾀 긴 시간동안 써오면서 한번 이런 프로그램을 만들어 보고 싶다 생각했습니다. 그러나 아직 초보단계라 아직은 이런걸 제작하기에는 실력이 부족합니다.
그래서 혹시 가능하다면 소스를 제공받아 공부해 보고 싶습니다. 만약 제공해 주신다면 배포나 영리적 목적으로 절대 사용하지 않을 것을 약속 드립니다.

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/46

**Comment by sangonkim** [comment]
@kurtBestor
감사합니다! 잘쓰겠습니다.
