### ISSUE TITLE
트위치 다시보기 다운로드추가 건의 가능할까요?

### ISSUE THREAD

**Issue by siwkd2** [KurtBestor/Hitomi-Downloader-issues#652]
트위치 다시보기영상을 다운로드하고싶은데 현재 인터넷에 있는 트위치 다운로더들이 전부 작동하지 않아서 혹시 트위치 스크립트를 추가하실수 있는지 요청하는 바입니다

건의사항 읽어주셔서 감사합니다

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by siwkd2** [comment]
정상작동되는것으로 확인되었습니다 만들어주셔서 감사합니다
