### ISSUE TITLE
다운로더 자체에 vpn 기능이 있나요?

### ISSUE THREAD

**Issue by chbk256** [KurtBestor/Hitomi-Downloader-issues#655]
GoodbyeDPI 기능이 있는 건 알고 있는데 그 외 vpn 처럼 ip를 변조하는 방식의 기능도 있는지 궁금합니다. 컴알못인데다가 설명서에도 자세히 나와있지 않더군요.

**Comment by KurtBestor** [comment]
IP만 변경하는 목적이면 프록시를 쓰세요.

`옵션` - `설정` - `고급 설정` - `프록시` 에서 설정하실 수 있어요.

**Comment by chbk256** [comment]
현재는 프록시 밖에 없나보군요. 감사합니다. ㅎㅎ
