### ISSUE TITLE
시작시 오류메시지, 다운로드 실패시 파일생성, 특정 분류 작품 다운로드 불가

### ISSUE THREAD

**Issue by idvel6732** [KurtBestor/Hitomi-Downloader-issues#656]
ㆍ시작 시 잠시 후에 오류메시지가 뜹니다.
ㆍ특정 분류의 작품을 다운로드할 수 없습니다.
 (ex 익헨 웨스턴 분류 작품, 이것은 이번 익헨사이트 개편 이후라고 짐작해봅니다.)
ㆍ다운로드에 실패할시 파일이 생성됩니다.

![bandicam 2019-03-26 02-16-00-665](https://user-images.githubusercontent.com/34673734/54940320-dc720400-4f6d-11e9-854e-fb4d00c37bb7.jpg)

![bandicam 2019-03-26 02-16-21-542](https://user-images.githubusercontent.com/34673734/54940326-ded45e00-4f6d-11e9-97b0-a34c0d2fc614.jpg)

**Comment by KurtBestor** [comment]
어떤 버전 / OS 쓰시나요?

**Comment by idvel6732** [comment]
윈도우10 64비트입니다.

**Comment by KurtBestor** [comment]
[GoodbyeDPI](https://github.com/ValdikSS/GoodbyeDPI/releases/tag/0.1.5) 다운로드해서 `x86_64` 폴더의 `goodbyedpi.exe` 실행해보세요. 잘 작동 하나요?

**Comment by idvel6732** [comment]
네, 일단 실행 후에 오류메시지 뜨는 현상은 사라졌습니다.
웨스턴 분류 다운로드 안되는 것과 실패 시 파일이 생성되는건 여전하네요.

그리고 추가로 전에는 제목을 드래그해서 URL입력창에 URL을 입력하는게 가능했는데
어느 순간부터 안되던데 이 부분은 업데이트하면서 사라진 기능인가요?

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/643, https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/579

**Comment by idvel6732** [comment]
#643의 경우에는 테스트 버전을 깔면 되는건가요?

**Comment by KurtBestor** [comment]
네

**Comment by idvel6732** [comment]
감사합니다! 문제 3개 전부 해결했습니다.
