### ISSUE TITLE
이것은 무슨 에러인가요?

### ISSUE THREAD

**Issue by chbk256** [KurtBestor/Hitomi-Downloader-issues#657]
픽시브에서 검색 결과가 특히나 많은 키워드에서 뜨는 게 아닌가 추측됩니다만 일단 올려봅니다.

PixivError: {'user_message_details': {}, 'reason': u'', 'message': u'{"offset":["Offset must be no more than 5000"]}', 'user_message': u''}

version: 2.6
platform: Windows-10-10.0.17763
gal_num: ttps://www.pixiv.net/
dir: 
zip: 
type: pixiv
artist: None
url: ttps://www.pixiv.net/search.php?
valid: False
done: False
range: 1 ~ 100000
range_p: None
single: False
time: 1553600974.39 (Mar 26)
tags: []

[Gallery]
None

[File Names]

[URLs]

[Messages]
PIXIV_TYPE: search
Type: all
露出 (pixiv_search_露出)
read ugoira... 73838257
skip ugoira: hitomi_downloaded_pixiv\露出 (pixiv_search_露出)\73838257_p0.gif
read ugoira... 73802493
skip ugoira: hitomi_downloaded_pixiv\露出 (pixiv_search_露出)\73802493_p0.gif
read ugoira... 73799066
skip ugoira: hitomi_downloaded_pixiv\露出 (pixiv_search_露出)\73799066_p0.gif
read ugoira... 73792472
skip ugoira: hitomi_downloaded_pixiv\露出 (pixiv_search_露出)\73792472_p0.gif
read ugoira... 73743182
skip ugoira: hitomi_downloaded_pixiv\露出 (pixiv_search_露出)\73743182_p0.gif
read ugoira... 73681330
skip ugoira: hitomi_downloaded_pixiv\露出 (pixiv_search_露出)\73681330_p0.gif
read ugoira... 73678845
skip ugoira: hitomi_downloaded_pixiv\露出 (pixiv_search_露出)\73678845_p0.gif
read ugoira... 73651909
skip ugoira: hitomi_downloaded_pixiv\露出 (pixiv_search_露出)\73651909_p0.gif
read ugoira... 73648607
skip ugoira: hitomi_downloaded_pixiv\露出 (pixiv_search_露出)\73648607_p0.gif
read ugoira... 73635074
skip ugoira: hitomi_downloaded_pixiv\露出 (pixiv_search_露出)\73635074_p0.gif
read ugoira... 73620410
skip ugoira: hitomi_downloaded_pixiv\露出 (pixiv_search_露出)\73620410_p0.gif
read ugoira... 73619500
skip ugoira: hitomi_downloaded_pixiv\露出 (pixiv_search_露出)\73619500_p0.gif
read ugoira... 73608917
skip ugoira: hitomi_downloaded_pixiv\露出 (pixiv_search_露出)\73608917_p0.gif
read ugoira... 73489791
read ugoira... 73480202
read ugoira... 73459330
read ugoira... 73454769
read ugoira... 73427958
read ugoira... 73426443
read ugoira... 73426397
read ugoira... 73426104
read ugoira... 73423373
read ugoira... 73410711
read ugoira... 73390506
read ugoira... 73389410
read ugoira... 73244488
read ugoira... 73180260
read ugoira... 73102919
read ugoira... 73092199
read ugoira... 73076304
read ugoira... 73065160
read ugoira... 73062393
read ugoira... 73022054
read ugoira... 73017710
read ugoira... 72980768
read ugoira... 72968045
read ugoira... 72961791
read ugoira... 72939031
read ugoira... 72931274
read ugoira... 72920206
read ugoira... 72919844
read ugoira... 72909891
read ugoira... 72903850
read ugoira... 72866821
read ugoira... 72857178
read ugoira... 72848850
read ugoira... 72845420
read ugoira... 72830227
read ugoira... 72823519
read ugoira... 72808070
read ugoira... 72798673
read ugoira... 72734070
read ugoira... 72726653
read ugoira... 72708359
read ugoira... 72708273
read ugoira... 72708151
read ugoira... 72695693
read ugoira... 72683048
read ugoira... 72659703
read ugoira... 72649971
read ugoira... 72642276
read ugoira... 72638391
read ugoira... 72632905
read ugoira... 72601848
read ugoira... 72571434
read ugoira... 72552898
read ugoira... 72551761
read ugoira... 72524912
read ugoira... 72511927
read ugoira... 72507063
read ugoira... 72490346
read ugoira... 72477738
read ugoira... 72445159
read ugoira... 72433106
read ugoira... 72428096
read ugoira... 72396655
read ugoira... 72386621
read ugoira... 72380262
read ugoira... 72375363
read ugoira... 72359166
read ugoira... 72311799
read ugoira... 72267654
read ugoira... 72246395
read ugoira... 72229579
read ugoira... 72227764
read ugoira... 72211599
read ugoira... 72190351
read ugoira... 72180965
read ugoira... 72139053
read ugoira... 72138510
read ugoira... 72135687
read ugoira... 72113199
read ugoira... 72102507
read ugoira... 72100600
read ugoira... 72100578
read ugoira... 72097991
read ugoira... 72088003
read ugoira... 72087675
read ugoira... 72070793
read ugoira... 72069713
read ugoira... 72065560
read ugoira... 72061337
read ugoira... 72051292
read ugoira... 72041903
read ugoira... 72032745
read ugoira... 72023900
read ugoira... 72021429
read ugoira... 72010991
read ugoira... 72007770
read ugoira... 72003384
read ugoira... 71989695
read ugoira... 71973817
read ugoira... 71971917
read ugoira... 71967712
read ugoira... 71951762
read ugoira... 71933663
read ugoira... 71917511
read ugoira... 71905387
read ugoira... 71889949
read ugoira... 71877673
read ugoira... 71867404
read ugoira... 71861627
read ugoira... 71858191
read ugoira... 71809566
read ugoira... 71799821
read ugoira... 71778899
read ugoira... 71768231
read ugoira... 71751809
read ugoira... 71733186
read ugoira... 71726832
read ugoira... 71726768
read ugoira... 71726709
read ugoira... 71726583
read ugoira... 71726560
read ugoira... 71709291
read ugoira... 71699020
read ugoira... 71692054
read ugoira... 71664253
read ugoira... 71649951
read ugoira... 71629359
read ugoira... 71625901
read ugoira... 71605834
read ugoira... 71584427
read ugoira... 71571467
read ugoira... 71544841
read ugoira... 71531168
read ugoira... 71516269
read ugoira... 71512953
read ugoira... 71495769
read ugoira... 71480504
read ugoira... 71467268
read ugoira... 71454645
read ugoira... 71432303
read ugoira... 71401067
read ugoira... 71383262
read ugoira... 71383129
read ugoira... 71375468
read ugoira... 71367189
read ugoira... 71366459
read ugoira... 71352236
read ugoira... 71330122
read ugoira... 71330074
read ugoira... 71327194
read ugoira... 71315885
read ugoira... 71307173
read ugoira... 71304108
read ugoira... 71303494
read ugoira... 71292238
read ugoira... 71286681
read ugoira... 71251383
read ugoira... 71238597
read ugoira... 71229555
read ugoira... 71210480
read ugoira... 71203296
read ugoira... 71196806
read ugoira... 71182171
read ugoira... 71164366
read ugoira... 71159518
read ugoira... 71153695
read ugoira... 71147337
read ugoira... 71119591
read ugoira... 71115346
read ugoira... 71111195
read ugoira... 71106525
read ugoira... 71105879
read ugoira... 71088834
read ugoira... 71083684
read ugoira... 71080551
read ugoira... 71080492
read ugoira... 71079952
read ugoira... 71058821
read ugoira... 71058763
read ugoira... 71044975
read ugoira... 71022642
read ugoira... 71019464
read ugoira... 71005179
read ugoira... 70992351
read ugoira... 70977330
read ugoira... 70958506
read ugoira... 70956358
read ugoira... 70951607
read ugoira... 70948657
read ugoira... 70930520
read ugoira... 70858615
read ugoira... 70812243
read ugoira... 70787000
read ugoira... 70775278
read ugoira... 70773743
read ugoira... 70760691
read ugoira... 70755774
read ugoira... 70749664
read ugoira... 70745035
read ugoira... 70730375
read ugoira... 70729173
read ugoira... 70726100
read ugoira... 70719231
read ugoira... 70709936
read ugoira... 70703786
read ugoira... 70679037
read ugoira... 70620587
read ugoira... 70594506
read ugoira... 70584020
read ugoira... 70575186
read ugoira... 70548557
read ugoira... 70517089
read ugoira... 70510429
read ugoira... 70420551
read ugoira... 70395327
read ugoira... 70393511
read ugoira... 70392389
read ugoira... 70381754
read ugoira... 70381518
read ugoira... 70354160
read ugoira... 70324275
read ugoira... 70321914
read ugoira... 70312562
read ugoira... 70302480
read ugoira... 70298614
read ugoira... 70296577
read ugoira... 70291755
read ugoira... 70273800
read ugoira... 70242377
read ugoira... 70233475
read ugoira... 70209421
read ugoira... 70207693
read ugoira... 70173531
read ugoira... 70173147
read ugoira... 70165799
read ugoira... 70138726
read ugoira... 70132903
read ugoira... 70123305
read ugoira... 70123281
read ugoira... 70034216
read ugoira... 70027247
read ugoira... 70025249
read ugoira... 70018556
read ugoira... 70014641
read ugoira... 70010837
read ugoira... 70001778
read ugoira... 69989629
read ugoira... 69956680
read ugoira... 69941770
read ugoira... 69919530
read ugoira... 69913568
read ugoira... 69901792
{'user_message_details': {}, 'reason': u'', 'message': u'{"offset":["Offset must be no more than 5000"]}', 'user_message': u''}
retry...
{'user_message_details': {}, 'reason': u'', 'message': u'{"offset":["Offset must be no more than 5000"]}', 'user_message': u''}
retry...
{'user_message_details': {}, 'reason': u'', 'message': u'{"offset":["Offset must be no more than 5000"]}', 'user_message': u''}
retry...
{'user_message_details': {}, 'reason': u'', 'message': u'{"offset":["Offset must be no more than 5000"]}', 'user_message': u''}
retry...
{'user_message_details': {}, 'reason': u'', 'message': u'{"offset":["Offset must be no more than 5000"]}', 'user_message': u''}
retry...
{'user_message_details': {}, 'reason': u'', 'message': u'{"offset":["Offset must be no more than 5000"]}', 'user_message': u''}
retry...
{'user_message_details': {}, 'reason': u'', 'message': u'{"offset":["Offset must be no more than 5000"]}', 'user_message': u''}
retry...
{'user_message_details': {}, 'reason': u'', 'message': u'{"offset":["Offset must be no more than 5000"]}', 'user_message': u''}
retry...
{'user_message_details': {}, 'reason': u'', 'message': u'{"offset":["Offset must be no more than 5000"]}', 'user_message': u''}
retry...
{'user_message_details': {}, 'reason': u'', 'message': u'{"offset":["Offset must be no more than 5000"]}', 'user_message': u''}
retry...
stop
Traceback (most recent call last):
File "pixiv_downloader", line 166, in read
File "pixiv_downloader", line 371, in get_imgs
PixivError: {'user_message_details': {}, 'reason': u'', 'message': u'{"offset":["Offset must be no more than 5000"]}', 'user_message': u''}

Fail: pixiv

stop
done : ttps://www.pixiv.net/

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by chbk256** [comment]
감사합니다. 잘 됩니다. 다만 검색 결과 게시물 수가 몇 만개가 넘어갈 경우, 전부 받아지지 않는 것 같은데 이건 무료 계정의 페이지 제한 때문이겠죠?

**Comment by KurtBestor** [comment]
검색할 때 모바일 어플에서 사용하는 것과 같은 방식으로 검색하는데, 이게 게시물 5000개 제한이 있어서 그래요.

**Comment by chbk256** [comment]
그렇군요. 딱 하나 그래도 보완할 수 있는 아이디어를 내보자면

오래된 순서나 날짜 별로 검색하는 방법이 픽시브에 있는데

그렇게 검색 된 날짜의 페이지에서 부터 다운로드가 시작되게 하는 방법은 어떨까 생각합니다.

어쨌든 답변 감사합니다.

**Comment by KurtBestor** [comment]
모바일 버전에선 날짜 기간 지정을 못 해서 불가능해요.
