### ISSUE TITLE
제이마나 (8) 다운로드가 되지 않습니다

### ISSUE THREAD

**Issue by cancerogenic** [KurtBestor/Hitomi-Downloader-issues#658]
목록 주소를 입력해주세요: https://jmana8.com / book / %EC%A2%8B%EC%95%84%ED%95%98%EB%8A%94%20%EC%95%A0%EA%B0%80%20%EC%95%88%EA%B2%BD%EC%9D%84%20%EA%B9%9C%EB%B9%A1%ED%96%88%EB%8B%A4 / 125981

version: 2.6
platform: Windows-10-10.0.17134
gal_num: https://jmana8.com/book/%EC%A2%8B%EC%95%84%ED%95%98%EB%8A%94%20%EC%95%A0%EA%B0%80%20%EC%95%88%EA%B2%BD%EC%9D%84%20%EA%B9%9C%EB%B9%A1%ED%96%88%EB%8B%A4/125981
dir: 
zip: 
type: jmana
artist: None
url: https://jmana8.com/book/%EC%A2%8B%EC%95%84%ED%95%98%EB%8A%94%20%EC%95%A0%EA%B0%80%20%EC%95%88%EA%B2%BD%EC%9D%84%20%EA%B9%9C%EB%B9%A1%ED%96%88%EB%8B%A4/125981
valid: False
done: False
range: None
range_p: None
single: False
time: 1553636119.09 (Mar 27)
tags: []

[Gallery]
None

[File Names]

[URLs]

[Messages]
stop
Traceback (most recent call last):
File "hitomi_downloader_GUI", line 1239, in run
File "utils", line 208, in pop
IndexError

Fail: jmana

stop
done : https://jmana8.com/book/%EC%A2%8B%EC%95%84%ED%95%98%EB%8A%94%20%EC%95%A0%EA%B0%80%20%EC%95%88%EA%B2%BD%EC%9D%84%20%EA%B9%9C%EB%B9%A1%ED%96%88%EB%8B%A4/125981

**Comment by KurtBestor** [comment]
다음과 같이 목록 주소를 입력해야해요: https://jmana8.com/book/%EC%A2%8B%EC%95%84%ED%95%98%EB%8A%94%20%EC%95%A0%EA%B0%80%20%EC%95%88%EA%B2%BD%EC%9D%84%20%EA%B9%9C%EB%B9%A1%ED%96%88%EB%8B%A4

**Comment by cancerogenic** [comment]
감사합니다~
