### ISSUE TITLE
macOS용으로 컨버팅할 계획은 없으신가요?

### ISSUE THREAD

**Issue by Petenka315** [KurtBestor/Hitomi-Downloader-issues#659]
macOS에서 Wine을 통해 쓰는걸로는 한계가 있는 것 같습니다... 향후 macOS용으로도 개발하실 계획이 있으신가요?

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/580

**Comment by Petenka315** [comment]
> macOS에서 Wine을 통해 쓰는걸로는 한계가 있는 것 같습니다... 향후 macOS용으로도 개발하실 계획이 있으신가요?
