### ISSUE TITLE
혹시 지원되는 사이트 추가는 안되나요

### ISSUE THREAD

**Issue by rabirabin** [KurtBestor/Hitomi-Downloader-issues#66]
밤토끼라던가밤토끼라던가밤토끼라던가 흐......아 그리고 마루마루 다운로드 안되는거 몇개있네요 리벤지H 라는 만화도안되고

**Comment by KurtBestor** [comment]
밤토끼는 이미 지원하고있어요.

리벤지H는 암호가 걸려서 그런데,  https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/57 이거 참고해주세요.

**Comment by KurtBestor** [comment]
v2.2b에서 해결됨

**Comment by rabirabin** [comment]
감사합니다>ㅁ<
