### ISSUE TITLE
e-hentai 다운로드 오류

### ISSUE THREAD

**Issue by kescape** [KurtBestor/Hitomi-Downloader-issues#661]
항상 수고하십니다.
프로그램 잘 사용하고 있습니다.

몇 주 전부터 e-hentai 주소를 입력했을 때 Invalid 표시가 뜨며 다운이 안됩니다.
프로그램 경로에 'ehen_18.5434994915.html'과 같은 파일이 생기구요
동일한 파일이 숫자 부분만 바뀌며 생성됩니다.

파일 내용은 아래와 같습니다.

[ehen_18.5434994915.zip](https://github.com/KurtBestor/Hitomi-Downloader-issues/files/3013008/ehen_18.5434994915.zip)

![캡처](https://user-images.githubusercontent.com/48989053/55074617-16f5b100-50d4-11e9-99a9-d509307271d7.PNG)

감사합니다.

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/643

**Comment by kescape** [comment]
test 버전 잘 작동합니다
감사합니다
