### ISSUE TITLE
e-hentai 사이트에 명시된 제목 그대로 폴더명으로 만들 순 없을까요?

### ISSUE THREAD

**Issue by KorCustom** [KurtBestor/Hitomi-Downloader-issues#663]
일단 질문글 올리기 전에 좋은 프로그램 만들어 주셔서 감사합니다. 덕분에 잘 사용하고 있습니다.

프로그램을 통해 e-hentai에서 다운받을 때 폴더명 형식을 태그로 지정할 순 있지만 사이트에 명시된 제목 그대로 다운받을 순 없는 것 같습니다.
그래서 나름대로 최대한 비슷하게 설정해놓고 N/A가 뜨면 대체하며 사용했습니다.
그러나 불편한 점이 생겨 건의드립니다.

 사이트(e-hentai 한정)에 명시된 제목의 구성요소들이 누락되거나 복수의 artist를 표기할 수가 없습니다.

예를 들면 보통 형식이 (convention) [group (artist)] title (series) [language] 이런 순으로 되있는데 

convention 같은 경우(ex. C93, COMIC1☆10 등) 사이트 자체에서 태그기능이 지원안되서 무조건 수동으로 수정해줘야합니다.

 artist같은 경우엔 복수의 artist로 되어있고 (artist a, artist b) a보다 b가 검색하기에 수월한 메인 artist인 경우가 종종 있습니다.
 이 경우 전자의 artist만 입력되어 나중에 artist별로 구성할 때 처음 듣는 artist로 명시되어 다시 사이트에 가서 수정해야합니다.

 또한 좀 특수한 예를 들면 사이트에 올라와있는 제목은
[Taira Issui] Kana no Omocha | 카나의 장난감 (COMIC BAVEL 2019-04) [Korean] [Digital]
이지만 다운로더로 받으면 artist는 amano kazumi라 입력됩니다.
 왜냐하면 artist의 tag에 amano kazumi | taira issui 이라 되어있는데 두 분이 필명만 다른 동일한 인물라서 같이 입력되거나 작가가 작품에 표기한 artist명으로 입력되어야하는데 전자만 입력되어 수정해줘야합니다.

따라서 혹시 기능을 구현하실 수 있다면 사이트에 올라와있는 제목 그대로 긁어올 수 있는 기능을 추가해주셨으면 감사하겠습니다.

**Comment by KurtBestor** [comment]
히토미에서 파싱을 그렇게 해서 어쩔 수 없네요.

E(x)Hentai 에서 다운로드하려면 `옵션` - `설정` - `일반 설정` - `서버` 를 `수동`, `E-Hentai / ExHentai Server` 로 바꿔주세요.
