### ISSUE TITLE
2.6v 게시자 오류? 

### ISSUE THREAD

**Issue by xesgnik** [KurtBestor/Hitomi-Downloader-issues#667]
프로그램을 실행할 때마다"게시자를 알 수 없은 이 앱이 디바이스를 변경할 수 있도록 허용하시겠어요?" 메세지가 뜨네요. 

별로 큰 문제는 아닌데 이전 버전에서는 딱히 게시자 문제가 없었던거 같아서 올려봅니당!

**Comment by xesgnik** [comment]
그리고 프로그램 종료시 확인 메세지를 끌 수 있을까요? 오피스 프로그램처럼 저장할 게 있을 때에만 확인 메세지가 뜨면 좋겠습니다

**Comment by KurtBestor** [comment]
DPI 우회를 위해서 관리자권한이 필요한데, 그것때문에 나오는 경고창이에요.

**Comment by xesgnik** [comment]
아하, 알겠습니다! 저같은 경우에는 외국에서 사용중이라 DPI우회 꺼놓긴 했는데 아무래도 처음 로드할 때는 권한이 필요한가보네요.

이와 별개로, 혹시 삭제된 database에서 받은 작품같은 경우에 삭제된 갤러리라고 명시할 수 있는 방법이 있을까요? 외장하드 공간이 부족해서 정리할 때 아무래도 삭제된거 위주로 킵할려고 해서 삭제된거만 따로 카테고라이즈할 수 있으면 굉장히 편리할거 같네요. 감사합니당!

**Comment by KurtBestor** [comment]
> 그리고 프로그램 종료시 확인 메세지를 끌 수 있을까요? 오피스 프로그램처럼 저장할 게 있을 때에만 확인 메세지가 뜨면 좋겠습니다

테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by xesgnik** [comment]
감사합니다! 방금 테스트해봤는데 우선 처음 프로그램 실행할 때에는 잘 되는데,

1. 기본적으로 실행할 때나 뭐 다운로드 받을 때나 에러로그가 무지막지하게 쌓이네요.

Traceback (most recent call last):
  File "hitomi_downloader_GUI.py", line 3928, in thread_timer_event
  File "hitomi_downloader_GUI.py", line 2983, in isChanged
UnboundLocalError: local variable 'section' referenced before assignment

2. 일종의 엣지 케이스인거 같은데, 처음에 프로그램 실행 후 아무것도 안하고 프로그램 껐다가 다시 실행하면 실행이 안됩니다. 처음 실행 후 db 받아온 다음에는 두번째 실행할 때도 잘되요.

감사합니다!

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by xesgnik** [comment]
잘 되네요 ㅎㅎ 감사합니다!
