### ISSUE TITLE
망가쇼미에서 이 만화만 다운로드가 안됩니다

### ISSUE THREAD

**Issue by ben11094** [KurtBestor/Hitomi-Downloader-issues#668]
이 만화의 다른 편들은 모두 다운로드가 잘 되는데, 이편만 다운로드가 안되고 계속 로딩중이네요
정보에서는 이렇게 나옵니다

읽는 중... [이노우에 코하루] 사신 도련님과 검은 메이드 / 사신 도련님과 검은 메이드 67화 (1 / 1)

version: 2.6
platform: Windows-10-10.0.17763
gal_num: https://mangashow.me/bbs/board.php?bo_table=msm_manga&wr_id=550200
dir: 
zip: 
type: mangashow
artist: 이노우에 코하루
url: https://mangashow.me/bbs/page.php?hid=manga_detail&manga_name=%EC%82%AC%EC%8B%A0+%EB%8F%84%EB%A0%A8%EB%8B%98%EA%B3%BC+%EA%B2%80%EC%9D%80+%EB%A9%94%EC%9D%B4%EB%93%9C
valid: True
done: False
range: None
range_p: None
single: False
time: 1553930907.99 (Mar 30)
tags: []

[Gallery]
None

[File Names]

[URLs]

[Messages]
redirect: https://mangashow.me/bbs/page.php?hid=manga_detail&manga_name=%EC%82%AC%EC%8B%A0+%EB%8F%84%EB%A0%A8%EB%8B%98%EA%B3%BC+%EA%B2%80%EC%9D%80+%EB%A9%94%EC%9D%B4%EB%93%9C
dirFormat: [artist] title
[seed] 사신 도련님과 검은 메이드 67화 31400
wait... 사신 도련님과 검은 메이드 67화
Traceback (most recent call last):
File "capture", line 109, in capture
Exception: Timeout

[seed] 사신 도련님과 검은 메이드 67화 31400
wait... 사신 도련님과 검은 메이드 67화
Traceback (most recent call last):
File "capture", line 109, in capture
Exception: Timeout

[seed] 사신 도련님과 검은 메이드 67화 31400
wait... 사신 도련님과 검은 메이드 67화

**Comment by KurtBestor** [comment]
서버가 죽었네요.
