### ISSUE TITLE
망가쇼미가 마나모아로 사이트 개편을 할 조짐이 보이는데 가능하시다면 마나모아도 서비스해 주세요.

### ISSUE THREAD

**Issue by i20191243r3263754** [KurtBestor/Hitomi-Downloader-issues#669]
지금 당장은 사이트가 완성되진 않은 것 같은데, 만약 완성된 후 회원제 같은게 문제라면 트위치 다시보기 다운 프로그램인 TwitchLeecher 처럼 로그인 할 수 있는 것을 만들어서 대응해주시면 감사하겠습니다.

**Comment by aksghkqhrl** [comment]
혹시나 라는 마음에 마루마루도 추가를 해주셨으면 좋겠습니다 .. (__)

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by i20191243r3263754** [comment]
> 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

안 되네요..
ggodbye dpi 를 켜도 안 됩니다.
______________________________________________________________________________________________________
Invalid : [manamoa] https://manamoa.net / bbs / board.php?bo_table=manga&wr_id=818326

version: 2.6
platform: Windows-10-10.0.17134
gal_num: https://manamoa.net/bbs/board.php?bo_table=manga&wr_id=818326
dir: 
zip: 
type: manamoa
artist: None
url: https://manamoa.net/bbs/board.php?bo_table=manga&wr_id=818326
valid: False
done: False
range: None
range_p: None
single: True
time: 1554103420.04 (Apr 1)
tags: []
goodbyedpi: False
lock: False


[Gallery]
None


[File Names]



[URLs]



[Messages]
stop
Traceback (most recent call last):
File "utils", line 395, in __init__
File "manamoa_downloader", line 67, in init
File "constants", line 587, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 570, in wrapper
File "manamoa_downloader", line 134, in get_soup
File "manamoa_downloader", line 396, in read_html
File "downloader", line 253, in read_html
Exception: 404


Fail: manamoa

stop
done : https://manamoa.net/bbs/board.php?bo_table=manga&wr_id=818326

**Comment by wkd284** [comment]
가능합니다 사이트자체 문제인듯하네요

**Comment by KurtBestor** [comment]
@i20191243r3263754 

지금도 안 되나요?
