### ISSUE TITLE
망가쇼미가 폐쇄되고 마나모아로 변경되었습니다

### ISSUE THREAD

**Issue by siwkd2** [KurtBestor/Hitomi-Downloader-issues#670]
오늘 오후 9시 30분경으로 망가쇼미 싸이트가 폐쇄되고 마나모아로 싸이트 이전이 되었습니다

https://manamoa.net/ 주소 변경 부탁드립니다

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/669

**Comment by siwkd2** [comment]
> 참고해주세요: #669

작동결과 정상작동되는것으로 확인되었습니다 만들어주셔서감사합니다
