### ISSUE TITLE
호두코믹스 스크립트가 안보입니다...

### ISSUE THREAD

**Issue by dkskrtnskans30513** [KurtBestor/Hitomi-Downloader-issues#671]
F1 눌렀을때 나오는 주소 (https://drive.google.com/drive/folders/1FP0YZp7QyGDyOQ1nwILRIVT3kd58NYxo)로 들어가니까 호두코믹스가 안보이네요

지난번에 썼던 기억이 있는데 특별한 이유가 있어서 내리셨나요?

**Comment by KurtBestor** [comment]
![image](https://user-images.githubusercontent.com/14768120/55299393-ca143080-546d-11e9-8bf6-2c76adfea00c.png)

누가 신고했는지 정지되었네요.
