### ISSUE TITLE
마론마론 그룹의 작품의 삭제된 작품이 뜨질 않고 다운도 되질 않습니다

### ISSUE THREAD

**Issue by tjrjsgml148** [KurtBestor/Hitomi-Downloader-issues#676]
정확히는 익헨과 히토미에는 없고 히요비에만 있는 작품을 찾아 다운을 받는데 다운이 되지를 않아요 혹시나해서 검색 기능으로 찾아보았지만 삭제된 작품들이 뜨질 않네요

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/603, https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/279

**Comment by tjrjsgml148** [comment]
오오 됩니다 감사합니다
