### ISSUE TITLE
Nhentai stop supporting?

### ISSUE THREAD

**Issue by Kizero1998** [KurtBestor/Hitomi-Downloader-issues#678]
![image](https://user-images.githubusercontent.com/27686111/55383341-29e40780-5552-11e9-8c83-a893734bce58.png)
Nhentai has return invalid! recently, it's not that big of a deal but it's a bug non aless

**Comment by KurtBestor** [comment]
Right click on the task and press `Info... (I)`. Please show me what appears.

**Comment by Kizero1998** [comment]
![image](https://user-images.githubusercontent.com/27686111/55468059-c8449b80-562c-11e9-8b87-13c835bc12d1.png)
this error pop-up and I can't copy paste it for some reason.
![image](https://user-images.githubusercontent.com/27686111/55468264-36895e00-562d-11e9-9b70-9fd4f9069a8d.png)

**Comment by Kizero1998** [comment]
![image](https://user-images.githubusercontent.com/27686111/55468388-78b29f80-562d-11e9-9eaa-2afcd01392ad.png)
but now Nhentai is working again :o
