### ISSUE TITLE
네이버 웹툰중에 이 것은 안 받아지네요?

### ISSUE THREAD

**Issue by bittet** [KurtBestor/Hitomi-Downloader-issues#679]
https://comic.naver.com/webtoon/list.nhn?titleId=574303

이런 웹툰도 받으려면 어떻게 해야 하나요?

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by bittet** [comment]
> 
> 
> 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

매우 잘됩니다.  감사합니다.
