### ISSUE TITLE
다운로드 윈도우 작가 태그 복사

### ISSUE THREAD

**Issue by RaceDriverMIKU** [KurtBestor/Hitomi-Downloader-issues#68]
자까가 "N / A" 이고 그룹이 "일단 그룹임" 으로 된 갤러리의 작가 이름 복사를 하려고 하면
"일단 그룹임" 이 복사 안되고 "N / A" 가 복사 됩니다. 예전 업데이트 로그가 기억나는 대로라면 그룹만 태깅이 되어있고 작가는 N / A 로 되어있다면 그룹 이름을 복사 하는것의 의도대로 작동을 하는것으로 알고 있어서 이슈 올립니다.

**Comment by KurtBestor** [comment]
폴더명 형식에 group이 들어있지 않고 작가가 없을 때만 그룹명을 복사합니다.
폴더명 형식에 group이 들어있다면 작가명 복사시에 작가명만 복사합니다.

이건 좀 애매해서 일단은 그대로 두겠습니다.
