### ISSUE TITLE
뉴토끼가 다운이 안됩니다.

### ISSUE THREAD

**Issue by kamogun** [KurtBestor/Hitomi-Downloader-issues#680]
Can not determine type: https://newtoki8.net / comic / 180661

version: 2.6
platform: Windows-10-10.0.17134
gal_num: https://newtoki8.net/comic/180661
dir: 
zip: 
type: 
artist: None
url: https://newtoki8.net/comic/180661
valid: False
done: False
range: None
range_p: None
single: True
time: 1554207441.32 (Apr 2)
tags: []
goodbyedpi: False
lock: False

[Gallery]
None

[File Names]

[URLs]

[Messages]
Traceback (most recent call last):
File "hitomi_downloader_GUI", line 1234, in run
File "utils", line 209, in pop
IndexError

Fail: 

done : https://newtoki8.net/comic/180661

웹툰도 동일하네요.

스크립트과 다운로드(테스트) 버젼으로 했습니다.

**Comment by KurtBestor** [comment]
스크립트가 오래된 것 같네요.

참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/505

**Comment by kamogun** [comment]
수정하셨다는 스크립트로 다운 한건데.ㅠㅠㅠ

**Comment by KurtBestor** [comment]
예전에 다운로드한 거 아닌가요? 다시 스크립트 다운로드해서 해보세요.

참고로 재실행하면 다시 스크립트 넣어야해요.

**Comment by kamogun** [comment]
아... 스크립트를 같이 넣기만 해서는 안되고

다시 스크립트 메뉴에서 찾아서 실행해야 하네요.

지금 잘되네요.

귀찮게 해드려서 죄송해요.ㅠㅠ
