### ISSUE TITLE
https://manamoa.net/bbs/board.php?bo_table=manga&wr_id=845585 error~

### ISSUE THREAD

**Issue by satanlord1** [KurtBestor/Hitomi-Downloader-issues#682]
Can not determine type: https://manamoa.net / bbs / board.php?bo_table=manga&wr_id=845585

version: 2.6
platform: Windows-10-10.0.17134
gal_num: https://manamoa.net/bbs/board.php?bo_table=manga&wr_id=845585
dir: 
zip: 
type: 
artist: None
url: https://manamoa.net/bbs/board.php?bo_table=manga&wr_id=845585
valid: False
done: False
range: None
range_p: None
single: True
time: 1554320588.3 (Apr 4)
tags: []

[Gallery]
None

[File Names]

[URLs]

[Messages]
Traceback (most recent call last):
File "hitomi_downloader_GUI", line 1218, in run
File "utils", line 207, in pop
IndexError

Fail: 

done : https://manamoa.net/bbs/board.php?bo_table=manga&wr_id=845585

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/669

**Comment by ad2sx** [comment]
궁금한점 AI 에게 질문하기
https://newtoki.iwinv.net/ https://ruliweb.iwinv.net/ https://instiz.iwinv.net/ https://gmarket.iwinv.net/ https://aliexpress.iwinv.net/ https://theqoo.iwinv.net/ https://linkkf.iwinv.net/ https://facebook.iwinv.net/ https://paypay.iwinv.net/ https://etoland.iwinv.net/ https://auction.iwinv.net/ https://trends.iwinv.net/ https://asdasd.iwinv.net/ https://kangkas.iwinv.net/ https://lavikit.iwinv.net/ https://maplegg.iwinv.net/ https://kemono.iwinv.net/ https://redgifs.iwinv.net/ https://wikikr.iwinv.net/ https://yourgg.iwinv.net/ https://koreakr.iwinv.net/ https://capcut.iwinv.net/ https://snp500.iwinv.net/ https://shopee.iwinv.net/ https://namuwiki.iwinv.net/ https://novelpia.iwinv.net/ https://popcat.iwinv.net/ https://fiveguys.iwinv.net/ https://compose.iwinv.net/ https://jjang0u.iwinv.net/ https://anilife.iwinv.net/ https://mmtcld.iwinv.net/ https://tdgall.iwinv.net/ https://yakored.iwinv.net/ https://postype.iwinv.net/ https://manatoki.iwinv.net/ https://dctribe.iwinv.net/ https://blacktoon.iwinv.net/ https://munpia.iwinv.net/ https://snpetf.iwinv.net/ https://hygall.iwinv.net/ https://mingky.iwinv.net/ https://fanbox.iwinv.net/ https://skyscanner.iwinv.net/ https://flightaware.iwinv.net/ https://interpals.iwinv.net/ https://fconline.iwinv.net/ https://flextv.iwinv.net/ https://dcinside.iwinv.net/ https://mlbpark.iwinv.net/ https://eomisae.iwinv.net/ https://ecount.iwinv.net/ https://hiworks.iwinv.net/ https://laftel.iwinv.net/ https://toomics.iwinv.net/ https://mercari.iwinv.net/ https://iptime.iwinv.net/ https://mixamo.iwinv.net/ https://yandex.iwinv.net/ https://gsshop.iwinv.net/ https://toptoon.iwinv.net/ https://slrclub.iwinv.net/ https://dmitory.iwinv.net/ https://kmcert.iwinv.net/ https://lolchess.iwinv.net/ https://curseforge.iwinv.net/ https://hsreplay.iwinv.net/ https://mapleinven.iwinv.net/ https://c19670.iwinv.net/ https://a12893.iwinv.net/ https://b82893.iwinv.net/
