### ISSUE TITLE
유튜브 다운 시 60프레임이 다운이 안 되네요

### ISSUE THREAD

**Issue by listandtag** [KurtBestor/Hitomi-Downloader-issues#683]
https://www.youtube.com/watch?v=x0CRTDjMARo

품질에 720p60 밖에 없는데 30프레임으로 다운이 되네요.

60프레임 영상도 다운 받았으면 합니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by listandtag** [comment]
잘 되네요! 감사합니다.
