### ISSUE TITLE
[수정] 소설가가 되자나 녹턴노벨에서 다운로드 받은 텍스트 파일. 통합본 제일 위에 소설 제목명이 써지게 해줄순 없으신가요? 

### ISSUE THREAD

**Issue by bestkimchi1** [KurtBestor/Hitomi-Downloader-issues#684]
번역기 돌린뒤 제목을 복사해서 저장하는식으로 활용하고싶습니다.

**Comment by bestkimchi1** [comment]
> 1화,2화,3화 식으로 나눠진게 아니라
> 
> 제목명으로 된 파일 하나로 받고싶습니다

**Comment by bestkimchi1** [comment]
바라지 않는 불사의 모험자
구/오카노스구루

-------------------------------------------------------
변경에서 만년동급 모험자를 하고 있던 주인공, 렌트. 그는 운 나쁘고, 미궁의 안쪽에서 강대한 마물을 만나, 패배해, 그리고 눈치채면 골인《스켈리턴》이 되어 있었다. 이대로 거리에조차 넣지 않으면 고뇌한 결과, 그는 마물의 존재 진화의 일을 생각해 내, 우선 고기가 있는 몸을 손에 넣는 것을 목표로 해, 미궁에서 마물을 넘어뜨려 간다.
-------------------------------------------------------
n8577dn 공개일:2018-11-2108:06:11

========================================================================

    제 1화 프롤로그언덕/오카노스구루 공개일:2016/09/2222:34/2017/10/28 21:26 개고


제 1화 프롤로그

 -위험한, 죽는다.

이런식으로 나오게요

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by bestkimchi1** [comment]
감사합니다 잘되네요
