### ISSUE TITLE
마나모아 다운이 안됩니다.

### ISSUE THREAD

**Issue by aksghkqhrl** [KurtBestor/Hitomi-Downloader-issues#685]
#669 참고했습니다.

Can not determine type: https://manamoa.net / bbs / board.php?bo_table=manga&wr_id=854750

version: 2.6
platform: Windows-10-10.0.17763
gal_num: https://manamoa.net/bbs/board.php?bo_table=manga&wr_id=854750
dir: 
zip: 
type: 
artist: None
url: https://manamoa.net/bbs/board.php?bo_table=manga&wr_id=854750
valid: False
done: False
range: None
range_p: None
single: True
time: 1554462767.41 (Apr 5)
tags: []

[Gallery]
None

[File Names]

[URLs]

[Messages]
Traceback (most recent call last):
File "hitomi_downloader_GUI", line 1218, in run
File "utils", line 207, in pop
IndexError

Fail: 

done : https://manamoa.net/bbs/board.php?bo_table=manga&wr_id=854750

![0004](https://user-images.githubusercontent.com/47558641/55623914-4d6fb200-57df-11e9-93cd-6bf0a8a1a6bc.png)

**Comment by KurtBestor** [comment]
작업 정보 보니까 오래된 버전이네요.
테스트 버전에서 지원해요.

참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/669#issuecomment-478409786
