### ISSUE TITLE
갑자기 픽시브가 다운이 않됩니다.

### ISSUE THREAD

**Issue by EQeiE** [KurtBestor/Hitomi-Downloader-issues#686]
정확히 말씀드리면 밥먹고[1시간]와서 다시 탐색하고 있었는데 갑자기 다운이 안되네요...
혹시나 해서 유튜브, 익헨은 확인해봤으나 제대로 다운되었습니다.
로그입니다.

Error L: pixiv_https://www.pixiv.net / member.php?id=427664

[u'Traceback (most recent call last):\n File "pixiv_downloader", line 71, in init\n File "pixiv_downloader", line 310, in get_api\n File "FUCK(4)\\api", line 60, in login\n File "FUCK(4)\\api", line 92, in auth\nPixivError: [ERROR] auth() failed! check username and password.\nHTTP 400: {"has_error":true,"errors":{"system":{"message":"104:\\u7121\\u52b9\\u306a\\u30e6\\u30fc\\u30b6\\u30fc\\u30a2\\u30ab\\u30a6\\u30f3\\u30c8\\u3067\\u3059\\u3002","code":1508}}}\n']

version: 2.6
platform: Windows-10-10.0.17134
gal_num: https://www.pixiv.net/member.php?id=427664
dir: 
zip: 
type: pixiv
artist: None
url: https://www.pixiv.net/member.php?id=427664
valid: False
done: False
range: None
range_p: None
single: False
time: 1554472856.56 (Apr 5)
tags: []

[Gallery]
None

[File Names]

[URLs]

[Messages]
PIXIV_TYPE: user
stop
Traceback (most recent call last):
File "pixiv_downloader", line 71, in init
File "pixiv_downloader", line 310, in get_api
File "FUCK(4)\api", line 60, in login
File "FUCK(4)\api", line 92, in auth
PixivError: [ERROR] auth() failed! check username and password.
HTTP 400: {"has_error":true,"errors":{"system":{"message":"104:\u7121\u52b9\u306a\u30e6\u30fc\u30b6\u30fc\u30a2\u30ab\u30a6\u30f3\u30c8\u3067\u3059\u3002","code":1508}}}

Fail: pixiv

stop
done : https://www.pixiv.net/member.php?id=427664

--------------------------------------------------------------
그리고 같은 사항이 있나 찾던 중에 이건 다물어 보시길래 기제해봅니다

downloader.requests.utils.get_environ_proxies('https://pixiv.net')

 입력시

downloader.requests.utils.get_environ_proxies('https://pixiv.net') 

{}
이렇게 나옵니다. 번거롭게 해서 죄송합니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by momokoro1** [comment]
잘 됩니다!

**Comment by EQeiE** [comment]
잘 됩니다. 늦었지만 감사드립니다.
