### ISSUE TITLE
픽시브 코믹이 다운로드 되지 않습니다

### ISSUE THREAD

**Issue by laruka** [KurtBestor/Hitomi-Downloader-issues#687]
Invalid : [pixiv_comic] https://comic.pixiv.net / works / 4934

version: 2.6
platform: Windows-10-10.0.17134
gal_num: https://comic.pixiv.net/works/4934
dir: 
zip: 
type: pixiv_comic
artist: None
url: https://comic.pixiv.net/works/4934
valid: False
done: False
range: None
range_p: None
single: False
time: 1554482016.8 (Apr 6)
tags: []
goodbyedpi: True
lock: False

[Gallery]
None

[File Names]

[URLs]

[Messages]
'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
File "utils", line 505, in start
File "utils", line 549, in start_
File "pixiv_comic_downloader", line 73, in read
File "pixiv_comic_downloader", line 59, in name
File "pixiv_comic_downloader", line 103, in get_artist
AttributeError: 'NoneType' object has no attribute 'text'

Fail: pixiv_comic

done : https://comic.pixiv.net/works/4934

혹은 에피소드를 직접 다운받으려고 해도 에러가 발생합니다

Invalid : [pixiv_comic] https://comic.pixiv.net / viewer / stories / 42534

version: 2.6
platform: Windows-10-10.0.17134
gal_num: https://comic.pixiv.net/viewer/stories/42534
dir: 
zip: 
type: pixiv_comic
artist: None
url: https://comic.pixiv.net/works/4934
valid: False
done: False
range: None
range_p: None
single: False
time: 1554482020.52 (Apr 6)
tags: []
goodbyedpi: True
lock: False

[Gallery]
None

[File Names]

[URLs]

[Messages]
fix url: https://comic.pixiv.net/works/4934
'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
File "utils", line 505, in start
File "utils", line 549, in start_
File "pixiv_comic_downloader", line 73, in read
File "pixiv_comic_downloader", line 59, in name
File "pixiv_comic_downloader", line 103, in get_artist
AttributeError: 'NoneType' object has no attribute 'text'

Fail: pixiv_comic

done : https://comic.pixiv.net/viewer/stories/42534

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview
