### ISSUE TITLE
히토미 다운로드시 여러 작가명을 폴더에 넣을 수 있나요?

### ISSUE THREAD

**Issue by osmium-76** [KurtBestor/Hitomi-Downloader-issues#688]
예를들어 2명, 3명 이상 작가가 참가한 작품은 히토미 사이트에서 보면 작가명들을 모두 확인할 수 있습니다. 이를 히토미 다운로더로 받으면 첫 작가 이름만 나오고 나머지는 etc 처리가 되네요. 

설정에서 폴더명에 이들 작가명이 모두 나오게끔 형식을 추가해주실 수 있나요? 폴더 길이가 너무 길어져 힘들다면 다운받은 파일 내부에 아무 메모장같은걸 만들고, 그 파일 이름을 작가명 리스트로 할수 있게 하면 어떨까요? 윈도우 검색에서 작가를 찾을때 쓰고싶어서 그럽니다 ㅠㅠ

말하는건 간단하지만 어렵겠죠.. ㅠ 참고해주시면 감사하겠습니다. 항상 잘 사용하고있습니다

**Comment by osmium-76** [comment]
예를들어 https://hitomi.la/galleries/1391961.html 이런 작품을 다운받을 때, 해당 폴더 이름이나 그 폴더 안에 더미 파일을 만들고 작가명을 모두 적어서 윈도우즈 탐색기 검색을 이용하고 싶습니다

**Comment by KurtBestor** [comment]
`옵션 (Options)` - `설정` - `히토미 설정` - `갤러리 정보 파일 (info.txt) 생성` 체크해주세요.

**Comment by osmium-76** [comment]
감사합니다. 폴더 명에 바로 넣을수있다면 편했겠는데 그러면 파일명이 너무 길어지겠네요. 알려주신대로 잘 쓰겠습니다.
