### ISSUE TITLE
스크립트 적용은 재시작할때 마다 실행해야 하나요?

### ISSUE THREAD

**Issue by kamogun** [KurtBestor/Hitomi-Downloader-issues#689]
뉴토끼 스트립트로 잘 다운로드 되는데..

프로그램 재시작 하면 스크립트를 다시 찾아서 

실행해줘야 적용이 되네요..

한번만 적용하면 계속 적용 되게는 안 되는건가요??

**Comment by KurtBestor** [comment]
실행파일 경로에 `scripts` 폴더 만들고 스크립트 파일 (*.hds) 넣으면 시작할 때 실행하도록 했어요.

테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by kamogun** [comment]
스크립트 추가 잘 되네요 ~ 감사합니다~
