### ISSUE TITLE
동시 다운로드 갤러리 수

### ISSUE THREAD

**Issue by RaceDriverMIKU** [KurtBestor/Hitomi-Downloader-issues#69]
갤러리 하나당 동시 다운로드 수는 설정 가능한데, 동시에 다운받는 갤러리 수 조절 기능도 넣어주실 수 있으세요?

**Comment by KurtBestor** [comment]
한 프로세스에서 스레드를 너무 많이 생성하면 OS에서 막더라구요.

여러 갯수로 테스트 해봤는데, 안전하게 하려면 4개(갤러리 스레드) x 64개(서브 스레드) + a개(나머지 스레드) = (256 + a)개 정도가 최대 인 것 같아요. 4개 미만은 의미가 없을 것 같아서, 이 기능은 넣기 힘들 것 같네요.
