### ISSUE TITLE
링크 입력칸에 ~ 표시로 범위 지정 가능하게 해주세요.

### ISSUE THREAD

**Issue by jtrpc** [KurtBestor/Hitomi-Downloader-issues#691]
예를들어 http://xxxxx.xxxx.xxx/?id=1~100

으로 주소칸에 입력하면 100개가 리스트로 등록되면 좋을거같아요.

**Comment by KurtBestor** [comment]
필요한 이유가 있나요?

**Comment by jtrpc** [comment]
500개 정도 링크 복붙하면 뒤가 잘립니다.

텍스트 칸의 버퍼가 작아서 그런듯한데

2천개 정도 넘어가서 등록하면
어느순간 프로그램이 뻗어서 꺼집니다.

- 버퍼가 적어 500개씩 등록중
- 4번정도 하고나서 부터 이후 부터는 뻗을 확률 있음.

자동으로 리스트 등록해준다면 안뻗을거 같은 기분이 들었습니다.

**Comment by KurtBestor** [comment]
다은로더 목록에서 900개 이상은 권장하지 않아요. 참고해주세요: #170
