### ISSUE TITLE
invalid 로 에러링크 자동으로 삭제하는 옵션

### ISSUE THREAD

**Issue by jtrpc** [KurtBestor/Hitomi-Downloader-issues#692]
invalid 로 실패시 자동으로 리스트에서 삭제되는 옵션추가 건의드립니다.

찾아봐도 없는것 같네요.

**Comment by KurtBestor** [comment]
필요한 이유가 있나요?

**Comment by jtrpc** [comment]
하단 필터로 걸러준다음 삭제하면 되는데
에러되는걸 재시도 하는 옵션은 보여도
마나쇼미의 특정 링크를 들어가보니 이미지가 하나도 없는 링크글이 있는걸 확인했습니다.

올리다 실수한 글같은데
그런 링크를 자동으로 리스트에서 제외하지 않아서 그대로 쌓여있다보니 
삭제하기가 번거롭습니다.ㅠ
