### ISSUE TITLE
업데이트 후 DPI 우회 에러

### ISSUE THREAD

**Issue by chokofondue** [KurtBestor/Hitomi-Downloader-issues#694]
![image](https://user-images.githubusercontent.com/33277557/55680766-fb529c00-5958-11e9-83e3-19f66e6a93b8.png)

업데이트 후 DPI 우회를 ON하면 이렇게 나오네요.
어떻게 해결해야 하나요?

**Comment by KurtBestor** [comment]
재부팅해도 그대로인가요?

**Comment by chokofondue** [comment]
해결되었습니다.
그 날 재부팅도 해보고 했는데 안되다가 다음날 다시 해보니 에러없이 잘 됩니다.
