### ISSUE TITLE
사이트 추가 건의 드립니다

### ISSUE THREAD

**Issue by totle91** [KurtBestor/Hitomi-Downloader-issues#695]
안녕하세요, 히토미 다운로더 잘 쓰고 있습니다. 정말 감사합니다. 

다름이 아니고 https://hanime.tv/ 란 사이트도 혹시 추가 가능할까요??

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/1083

**Comment by totle91** [comment]
사이트 추가 해주셔서 감사합니다!
patreon.com 에서 조금이지만 후원하고 있습니다. 
더운데 건강 관리 잘 하세요~
 
-----Original Message-----
