### ISSUE TITLE
모바일용 만들어볼 생각은 없...?

### ISSUE THREAD

**Issue by kikinet88** [KurtBestor/Hitomi-Downloader-issues#696]
안드로이드용으로 하나 있음 딱 좋을듯 싶..
쿨럭..

그러고 보니 볼래라면 히토미 전용 툴이었는대..
이제는.. 배가 산으로...

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/416
