### ISSUE TITLE
소설가가 되자 녹턴노벨 다운로드 통합본 맨위에 공백이 있습니다.

### ISSUE THREAD

**Issue by bestkimchi1** [KurtBestor/Hitomi-Downloader-issues#698]
공백없이 바로 제목이 나오게 해주셨으면 합니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by bestkimchi1** [comment]
잘됩니다 감사합니다.
