### ISSUE TITLE
오류 질문 드립니다

### ISSUE THREAD

**Issue by jhy1235** [KurtBestor/Hitomi-Downloader-issues#699]
![제목 없음-2](https://user-images.githubusercontent.com/49421083/55767371-8e074e00-5ab3-11e9-8d0f-f18ca3dc567e.jpg)
분명 어제까지만 해도 잘됐는데 오늘 이거 뜨면서 갑자기 안되네요 ㅠㅠㅠ

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/554#issuecomment-465210491, https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/700
