### ISSUE TITLE
다운로드 중 작동 중지됩니다.

### ISSUE THREAD

**Issue by Sayat1** [KurtBestor/Hitomi-Downloader-issues#7]
![2017-12-25](https://user-images.githubusercontent.com/14584343/34327485-3aafb6a6-e909-11e7-8021-5b0ddab859e9.png)

로그 내용 : 
C:\Users\Sayat\Documents\hitomi_downloader_GUI.exe\PIL\TiffImagePlugin.py:709: UserWarning: Corrupt EXIF data.  Expecting to read 4 bytes but only got 0. 
C:\Users\Sayat\Documents\hitomi_downloader_GUI.exe\PIL\TiffImagePlugin.py:742: UserWarning: Corrupt EXIF data.  Expecting to read 4 bytes but only got 0.

**Comment by KurtBestor** [comment]
해당 문제 고쳤습니다. 다음 링크에서 패치판을 다운로드할 수 있습니다:

> [Link](https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview)

확인해주시면 감사하겠습니다.
