### ISSUE TITLE
마루마루 다운이 안됩니다

### ISSUE THREAD

**Issue by aaaasssdddd** [KurtBestor/Hitomi-Downloader-issues#70]
https://marumaru.in/b/manga/290401

다운 받으려고 하는데
maru_290401: reCAPTCHA

자꾸 이렇게 뜹니다.
왜이러는 걸까요?

뭘복사해서 올려야할지 모르겠어서 정보누르면 나오는걸 그냥 복사해서 올립니다.

여기 파일이 여러개 이기도 하고, 제가 프로그램을 잘 이해를 못해서 이거같기도 한데요. 비슷한거 올리신분 봤는데, 거기에 고친거라고 하시면서 파일을 총 3개 올리셨잖아요. 
Hitomi-Downloader-issues-Technical-Preview.tar
이런 파일 포함하셔서요! 근데 다받았는데 어떻게 쓰는건지를 모르겠어서.....하... 제스스로가 너무 답답하네요.

답변해주시면 감사하겠습ㄴ다. 너무 알고싶어서 찾다찾다 여기까지 들어왔네요.

maru_290401: reCAPTCHA

gal_num: https://marumaru.in/b/manga/290401
dir: 
zip: 
type: maru
artist: None
url: http://marumaru.in/b/manga/290401
valid: False
done: False
range: None
range_p: None

[File Names]

[URLs]

[Messages]
[1] 짐승계 사장님의 전속비서 01화: http://wasabisyrup.com/archives/fJ1SDG4WiIE
Traceback (most recent call last):
File "maru_downloader", line 85, in read
File "maru_downloader", line 268, in get_imgs_all
NotImplementedError: reCaptcha

stop
Traceback (most recent call last):
File "maru_downloader", line 102, in read
AttributeError: 'NoneType' object has no attribute 'quit'

Fail: maru

stop
done : https://marumaru.in/b/manga/290401

**Comment by KurtBestor** [comment]
![recaptcha](https://user-images.githubusercontent.com/14768120/38126755-7d08aad4-342d-11e8-870e-39d7ef88816d.png)

위와 같이 설정해주세요.

**Comment by aaaasssdddd** [comment]
감사합니다!!! 완전 잘되네영ㅇㅎㅋ
