### ISSUE TITLE
다운로드 속도가 말도안되게 느려졌습니다.

### ISSUE THREAD

**Issue by fbi9111** [KurtBestor/Hitomi-Downloader-issues#700]
10mb 짜리 파일을 받는데 1시간이 넘어도 완료가 되질 않고, 제자리 걸음하는 수준입니다.
무엇이 문제일까요?

이전(1주일 전) 까지는 잘 사용하다가 오늘 사용하려고 하니 이런 현상이 발생하였습니다.

exhentai와 hitome url을 넣어서 다운로드 시작을 했는데

다운로드 되고있는 만화의 정보를 눌러보니 url이 https://hybcomics.xyz/ 이곳으로 되어있네요.

정보 추가합니다

version: 2.6a
platform: Windows-10-10.0.17763
gal_num: [Freehand Tamashii] Event Hon no Matome (842092)
dir: hitomi_downloaded\[Freehand Tamashii] Event Hon no Matome (842092)
zip: 
type: hiyobi
artist: Freehand Tamashii
url: https://hybcomics.xyz/reader/842092
valid: False
done: True
range: None
range_p: None
single: False
time: 1554775389.57 (Apr 9)
tags: []
goodbyedpi: True
lock: False

**Comment by wpfhfpr** [comment]
저도 똑같은 증상 나오네요. 서버의 문제인가....

**Comment by 5hoho** [comment]
방법 알아냈습니다 옵션->설정 들어가셔서 히토미 탭에 서버를 수동으로
E-hentai / exhentai server로 바꿔주시면 됩니다.

**Comment by noname8** [comment]
E-hentai / exhentai server 에서 받으면 파일 해상도가 낮게 받아짐. 참고 하세요

**Comment by wkd284** [comment]
> 
> 
> E-hentai / exhentai server 에서 받으면 파일 해상도가 낮게 받아짐. 참고 하세요

그건 처음알았네요. 유의하겠습니다.

**Comment by wkd284** [comment]
히요비나, 익헨쪽으로 링크 돌려서 받아지는거 같아요. 확실히 히토미 서버문제인듯.

**Comment by KurtBestor** [comment]
![image](https://user-images.githubusercontent.com/14768120/55784283-3553a780-5aeb-11e9-9dde-97b83e3518ae.png)

히요비에서 히토미 이미지를 리다이렉트하는 식으로 그대로 가져다 써서, 히토미 측에서 막은 것 같네요.
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by otraa** [comment]
이제 잘 되네요 익헨 이헨 서버 쪽으로는 여전히 느리지만 히토미 서버는 확실히 빨라졌습니다. 원래보다 빠른것 같네요

**Comment by 5hoho** [comment]
테스트버전으로 하니까 잘됩니다~ 빠르네요

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/720
