### ISSUE TITLE
픽시브 다운로드가 안됩니다

### ISSUE THREAD

**Issue by bwcat2** [KurtBestor/Hitomi-Downloader-issues#701]
Error L: pixiv_https://www.pixiv.net / member.php?id=3420822

[u'Traceback (most recent call last):\n File "pixiv_downloader", line 81, in init\n File "pixiv_downloader", line 329, in get_api\n File "FUCK(4)\\api", line 60, in login\n File "FUCK(4)\\api", line 92, in auth\nPixivError: [ERROR] auth() failed! check username and password.\nHTTP 400: {"has_error":true,"errors":{"system":{"message":"104:\\u7121\\u52b9\\u306a\\u30e6\\u30fc\\u30b6\\u30fc\\u30a2\\u30ab\\u30a6\\u30f3\\u30c8\\u3067\\u3059\\u3002","code":1508}}}\n']

version: 2.6a
platform: Windows-10-10.0.17134
gal_num: https://www.pixiv.net/member.php?id=3420822
dir: 
zip: 
type: pixiv
artist: None
url: https://www.pixiv.net/member.php?id=3420822
valid: False
done: False
range: None
range_p: None
single: False
time: 1554800708.53 (Apr 9)
tags: []
goodbyedpi: True
lock: False

[Gallery]
None

[File Names]

[URLs]

[Messages]
PIXIV_TYPE: user
stop
Traceback (most recent call last):
File "pixiv_downloader", line 81, in init
File "pixiv_downloader", line 329, in get_api
File "FUCK(4)\api", line 60, in login
File "FUCK(4)\api", line 92, in auth
PixivError: [ERROR] auth() failed! check username and password.
HTTP 400: {"has_error":true,"errors":{"system":{"message":"104:\u7121\u52b9\u306a\u30e6\u30fc\u30b6\u30fc\u30a2\u30ab\u30a6\u30f3\u30c8\u3067\u3059\u3002","code":1508}}}

Fail: pixiv

stop
done : https://www.pixiv.net/member.php?id=3420822

3일전에 같은 증상으로 글이 올라왔길래 그 테스트 버젼으로 받았는데도 불구 안되네용...

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview
