### ISSUE TITLE
히토미는 되지만 e.h은 여전히 안되네요

### ISSUE THREAD

**Issue by jpdecade** [KurtBestor/Hitomi-Downloader-issues#702]
아래 덧글로 테스트 버전 올려주실걸로 해봤는데
히토미는 다운이 되지만 e.h은 파일을 받으려고 대기중까지만 뜨고 
다운로드 진행이 안되네요
확인부탁드립니다

**Comment by KurtBestor** [comment]
해당 작업 `마우스 우클릭` - `정보... (I)`  눌러서 나오는 내용 보여주세요.
