### ISSUE TITLE
업데이트 후 다운이 되질 않습니다

### ISSUE THREAD

**Issue by Vesgurd** [KurtBestor/Hitomi-Downloader-issues#703]
업데이트 전에는 잘됐는데 업데이트 한 후에 다운로드가 안되네요...

히토미 익헨 등등 전부 안됩니다 ㅠㅠ

**Comment by KurtBestor** [comment]
업데이트 문제는 아니고, 참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/700

구버전 쓰고 싶으시면 쓰세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/v2.6
