### ISSUE TITLE
테스트 버전이 실행이 안되네요

### ISSUE THREAD

**Issue by finain** [KurtBestor/Hitomi-Downloader-issues#707]
![dwadwdwdw](https://user-images.githubusercontent.com/49469063/55853078-7ce53c80-5b9a-11e9-996c-30bd8aac2bc7.JPG)
관리자 권한으로 실행해도 먹히질 않네요

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/530
