### ISSUE TITLE
다운이 되지않는 오류 질문드립니다.

### ISSUE THREAD

**Issue by wpfhfpr** [KurtBestor/Hitomi-Downloader-issues#709]
![image](https://user-images.githubusercontent.com/40918484/55867202-03127a80-5bbd-11e9-9cdb-333cd99c7421.png)
[에러 3.txt](https://github.com/KurtBestor/Hitomi-Downloader-issues/files/3063004/3.txt)
다음과 같이 주황색으로 미완되는 파일들이 존재합니다.
또한 다운로드가 진행이 안되는 것도 다수 존재하고 간혹 다운이 어정쩡하게 되는것조차 아니라
76바이트(실질적으로 아무파일도 아닌 단순한 제목만 있는 압축파일로 압축됨)로 다운이 완료되는 경우가 대다수 존재합니다.이는 어떻게 해결해야되는 걸까요
![image](https://user-images.githubusercontent.com/40918484/55867583-bb402300-5bbd-11e9-9af0-5457fbf193cf.png)
[76바이트.txt](https://github.com/KurtBestor/Hitomi-Downloader-issues/files/3063022/76.txt)

700번 글 테스트버전으로 해봤습니다. 아래버전도 똑같은 거같습니다.

**Comment by KurtBestor** [comment]
원본파일 삭제가 체크되어있으면 압축파일 삭제하고 다시 다운로드해야해요.

**Comment by wpfhfpr** [comment]
> 원본파일 삭제가 체크되어있으면 압축파일 삭제하고 다시 다운로드해야해요.

아!삭제를 계속해본뒤에도 같더라구요.죄송합니다 적어놨어여됬는데 ㅠ

**Comment by KurtBestor** [comment]
프로그램에서 삭제한 다음 다시 URL 입력해서 다운로드한 것 맞나요?

**Comment by KurtBestor** [comment]
삭제하지 않아도 `다시 시작`만 누르면 동작하게 바꿨어요. 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview
