### ISSUE TITLE
사이트 추가 건의입니다.

### ISSUE THREAD

**Issue by Euthanatos1** [KurtBestor/Hitomi-Downloader-issues#71]
밤토끼에서 다운받다 보니, 이미지가 깨져있는 경우가 많던데, 호두코믹스 추가는 안될까요?
밤토끼 이미지들도 거기서 퍼온게 많은 것 같습니다.
https://hoducomics.com/

**Comment by KurtBestor** [comment]
깨져있는 만화 이름을 알려주시면 도움 될 것 같네요.
