### ISSUE TITLE
마나모아 주소 변경 했습니다

### ISSUE THREAD

**Issue by geniussjt** [KurtBestor/Hitomi-Downloader-issues#712]
https://manamoa2.net/ 
이걸로 바뀌는것같습니다
근데 지금 이 주소로 다운 받아봤더니 다운이 안됩니다ㅠㅠ 
지원 꼭 부탁드립니다^^
암튼 편안하고 좋은 저녁 되세요

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by geniussjt** [comment]
KurtBestor님  작동 잘 됩니다^^정말 감사합니다
