### ISSUE TITLE
최신 버전이랑 아래 테스트 버전 둘다느려요

### ISSUE THREAD

**Issue by blakebella** [KurtBestor/Hitomi-Downloader-issues#713]
제목대로 둘다 써봐도 느리구
옵션 설정 히토미 서버 부분에서 수동하고 다른거 해봐도 다 똑같네요
왼쪽에 주황색 표시뜨면서 다운까지도 안되요

**Comment by KurtBestor** [comment]
주황색으로 실패하는 건 히토미 서버 문제인데, 사이트에서 봐도 간간히 엑박이 떠요. `다시 시작` 하시면 될거예요.
