### ISSUE TITLE
히토미 다운로드가 제대로 진행되지 않습니다

### ISSUE THREAD

**Issue by BlessingDev** [KurtBestor/Hitomi-Downloader-issues#714]
![image](https://user-images.githubusercontent.com/6939720/55878676-d9b31800-5bd7-11e9-8f91-e0293b7364cb.png)

히토미의 URL을 입력하여 갤러리를 등록했습니다.
그런데 분명 해당 갤러리가 히토미에 올라와 있음에도 불구하고 히요비에 연결하는가 하면 그마저도 제대로 다운로드되지 않습니다.
무슨 문제입니까?

**Comment by dsfasdsdfdsf** [comment]
히요비 사이트 들어가니까 많은 게시글에 이미지가 안보이는 현상 발생 했는데 히요미 운영자가 신경쓰지 않은 상황 그래서 그런 현상 발생 우클릭해서 사이트 들어가면 이미지 안뜨는 에러창이 나와요 히토미 다운로더 개발자가 히요미 상황 안보고 연동시켜나봐요

**Comment by dsfasdsdfdsf** [comment]
설정에 아이피 우회기능 끄세요 현재 히요미 아이피우회 때문에 에러가 발생한다네요

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/700
