### ISSUE TITLE
2.4 이후의 버전에서 webDav 드라이브로의 직접 다운로드가 안됩니다.

### ISSUE THREAD

**Issue by dryname** [KurtBestor/Hitomi-Downloader-issues#715]
NAS 드라이브를 webDav으로 추가하여 사용 중인데, 2.4까지는 해당 위치에서 다운로드를 시도하면 잘 됐는데 그 이후 버전에서는 오류가 발생하며 작동하지 않습니다.

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/539
