### ISSUE TITLE
최신 버전에 문제가 생겼는데 해결 방법을 알 수 있을까요?

### ISSUE THREAD

**Issue by Field12** [KurtBestor/Hitomi-Downloader-issues#718]
안녕하세요

제가 2~3일 전부터 히토미에 존재하는 파일을 링크 넣고 다운을 시도했는데

뜬금없이 히요비로 연결돼서 다운을 시도하더니 결국엔 다운을 못하고 노란색으로 뜨면서 멈춥니다

그래서 설정에 들어가서 DPI 우회를 끄고 시도해보니 이번엔 익헨으로 연결돼서 다운 시도를 하네요

익헨쪽으로 연결 된건 다운은 되는데 익헨은 다운을 좀 하면 정지를 먹다 보니 히토미에 연결해서 다운을 하고 싶은데 해결 방법이 있을까요?

**Comment by whgmlqja12** [comment]
비슷한 증상으로 긴급패치본으로 돌려서 일부 히토미 작품 다운받다가 중간에 뚝 멈춰버리는 경우도 있습니다...

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/700

주황색으로 실패하는 건 히토미 서버 문제인데, 사이트에서 봐도 간간히 엑박이 떠요. `다시 시작` 하시면 될거예요.

**Comment by Field12** [comment]
> 참고해주세요: #700
> 
> 주황색으로 실패하는 건 히토미 서버 문제인데, 사이트에서 봐도 간간히 엑박이 떠요. `다시 시작` 하시면 될거예요.

지우고 새로 올려주신 거로 다운해서 해보니 다시 히토미로 다운이 잘 되네요
늘 감사합니다
