### ISSUE TITLE
주황색 상태가 되면서 다운이 안됩니다

### ISSUE THREAD

**Issue by man9508** [KurtBestor/Hitomi-Downloader-issues#719]
몇칠전까지는 다 잘됬는데 어떤건 잘 되는데 대부분의 파일이 저 상태가 되면서 다운이 안됩니다(히토미 마크가 다른 H모양이 되면서요)
우회되서 다운되는거 같기는 한데...
도와주세요ㅠㅠ @ @

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/720
