### ISSUE TITLE
다운로드 안 되거나 멈추는 문제

### ISSUE THREAD

**Issue by KurtBestor** [KurtBestor/Hitomi-Downloader-issues#720]
수정했어요.

테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by Karl-K** [comment]
Test ver. 확인했습니다. 정상적으로 작동되고 있습니다.

**Comment by 5hoho** [comment]
잘되네요 기분탓인진 모르겠지만 기본데이터다운도 빨라진거같은 느낌

**Comment by wpfhfpr** [comment]
[76바이트.txt](https://github.com/KurtBestor/Hitomi-Downloader-issues/files/3068151/76.txt)
다른건 다해결됬는데 이게 안되네요.이건 해결방법이 있을까요?
히토미 자체 주소엔 들어가집니다. 다운이 진행이 안되네유

**Comment by KurtBestor** [comment]
@wpfhfpr 

테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by wpfhfpr** [comment]
제가 올린 번호는 이제 잘되네요 또 테스트해보고 말씀드리겠습니다.감사합니다!

**Comment by lhj5426** [comment]
2.6A의 공식 버전은 hitomi를 다운로드 할 수 없습니다.

 그러나 # 720 베타 버전에서는 정상적으로 다운로드 할 수 있습니다. 다시 업데이트됩니까?

**Comment by KurtBestor** [comment]
@lhj5426 

네, 기타 버그 수정 / 테스트 후에 조만간 업데이트 될 거예요.

**Comment by KurtBestor** [comment]
업데이트 완료: [v2.6b](https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/v2.6b)
