### ISSUE TITLE
픽시브 로그인테스트 통과가 안됩니다.

### ISSUE THREAD

**Issue by didau0721** [KurtBestor/Hitomi-Downloader-issues#722]
분명히 제 아이디와 비밀번호를 맞게 했는데 로그인테스트를 통과하지 못합니다.
계정을 한개 더 파서 해봤는데 방금 판 계정이었는데도 통과가 안됩니다.

유효하지 않은 계정 / 패스워드 입니다.
{"has_error":ture,"errors":{"system":
{"maessage":"access_denied","code":1508}}}

자꾸 이렇게만 뜨고 로그인이 되지 않습니다

**Comment by KurtBestor** [comment]
픽시브 앱에서 로그인은 되나요?

**Comment by didau0721** [comment]
픽시브앱은 쓰지 않고 픽시브 인터넷 사이트만 이용하고 있습니다, 앱으로 해야하나요?

**Comment by KurtBestor** [comment]
앱에서 로그인하는 것과 같은 방식이라 앱애서 어떻게 뜨는지 궁금해서요.

**Comment by didau0721** [comment]
아, 저 방금 다시해봤는데 그냥 되네요, 어제 컴퓨터에 문제가 있었나봐요, 앱으로 안해봤는데 컴퓨터 로그인만 되어도 잘 작동하는 것 같습니다.
