### ISSUE TITLE
exhen 문의드립니다

### ISSUE THREAD

**Issue by jpdecade** [KurtBestor/Hitomi-Downloader-issues#723]
기존 오류들을 모르고 계속 다운을 시도해서 그런지 509가 걸려버렸는데 이러면 다운로더로 다운 방법이 어려울까요?

**Comment by jpdecade** [comment]
version: 2.6a
platform: Windows-10-10.0.17763
gal_num: https://e-hentai.org/g/1227054/ef3c563ac0/
dir: [Homealone447] [Droid447] Xeno Wars - Rebel Uprising (1227054)
zip: 
type: ehen
artist: Homealone447
url: https://e-hentai.org/g/1227054/ef3c563ac0
valid: True
done: False
range: None
range_p: None
single: False
time: 1555038292.9 (Apr 12)
tags: []
goodbyedpi: False
lock: False

509 걸린 뒤 상태 입니다

**Comment by KurtBestor** [comment]
시간 지나면 풀려요.

아니면 `옵션` - `설정` - `고급 설정` - `프록시` 쓰시면 돼요.

참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/720

**Comment by jpdecade** [comment]
> 시간 지나면 풀려요.
> 
> 아니면 `옵션` - `설정` - `고급 설정` - `프록시` 쓰시면 돼요.
> 
> 참고해주세요: #720
프록시를 체크해봤는데 아이피는 아무 아이피나 쓰면 ㅚ나요? 변경하고 해봤는데 
예르를면 0/100 이상태로 0 에서 계속 멈춰있습니다. 다른걸 건드려줘야할까요?

**Comment by jpdecade** [comment]
> 시간 지나면 풀려요.
> 
> 아니면 `옵션` - `설정` - `고급 설정` - `프록시` 쓰시면 돼요.
> 
> 참고해주세요: #720

프록시 IP 찾아서 ㅍ포트랑 같이 넣어줘도 다운이 안되네요.
다른 방법이 있을까요?
기다리면 풀린다고 하셨는데 3일째 똑같은 상태라서요....ㅠㅜ

**Comment by KurtBestor** [comment]
무료 프록시 같은 경우는 E(x)Hentai에서 막은 게 많아서, 안 될 경우가 많아요.

아니면 IP를 바꾸세요.
