### ISSUE TITLE
크롤러서버 오류 

### ISSUE THREAD

**Issue by kikinet88** [KurtBestor/Hitomi-Downloader-issues#725]
관리자님 지금 크롤러 서버 오류가 많습니다
아래에 올라온 오류 와 동일하네요

업데이트 하셔야할듯 싶음...

아참.. 이메일 까먹었으니.. -_-;; 이멜좀..

**Comment by KurtBestor** [comment]
확인해봤는데 이상은 없네요.. 원격으로 해서 그런가요?

CMD 창 클릭하셔서 멈춰있긴 하던데, 우클릭하면 풀어져요.

**Comment by kikinet88** [comment]
모바일게임 돌리실거 있으면
돌리세요
자원이 남아돔 ㅋ

2019년 4월 12일 (금) 18:28, Kurt Bestor <notifications@github.com>님이 작성:
