### ISSUE TITLE
트위터 다운로드중에 마음함을(좋아요)를 다운로드할수있게 해주세요

### ISSUE THREAD

**Issue by HighLithol** [KurtBestor/Hitomi-Downloader-issues#726]
트위터 ♥눌러놓은 것들을 다운할수 있는 기능이 있다면 좋겠습니다

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview
