### ISSUE TITLE
검색결과에서 이미 다운받은 파일들을 가릴수도 있었으면 좋겠습니다.

### ISSUE THREAD

**Issue by GNEELS** [KurtBestor/Hitomi-Downloader-issues#728]
언제나 프로그램 유용하게 잘 쓰고 있습니다. 꾸벅

이미 받은 파일을 중복표시해주는게 아니라 아예 가릴수도 있었으면 좋겠습니다. 아니면 검색이 완료될때 다운받지 않은 파일들만 가장 위로 모아서 한눈에 볼 수 있어도 좋을것같습니다.

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/400#issuecomment-453401831

**Comment by GNEELS** [comment]
이미 있었네요. 감사합니다.
