### ISSUE TITLE
스크립트 관련

### ISSUE THREAD

**Issue by retol** [KurtBestor/Hitomi-Downloader-issues#729]
https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/521
개별사이트 이슈관련 스크립트, 위의 스크립트가 모두 같은 링크로 되어있는데
해당 링크 내용이 소유자의 휴지통에 있다고 안들어가져요. 복구 부탁드려도 될까요

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/wiki/Scripts

**Comment by retol** [comment]
감사합니다!
