### ISSUE TITLE
pixiv 다운로드가 안되네요

### ISSUE THREAD

**Issue by luminarie1** [KurtBestor/Hitomi-Downloader-issues#73]
Error L:pixiv_https://www.pixiv.net/member.php?id=23181416

라고 뜨면서 픽시브 다운로드가 안되네요
설명서에 있는 pixiv_23181416 이런식으로 검색해도 다운로드가 안되구요

혹시 제가 잘못 하고 있는게 있나요?

**Comment by KurtBestor** [comment]
맞게 하셨는데요, 혹시 외국에 사시나요?

**Comment by luminarie1** [comment]
아뇨 서울 거주중입니다

**Comment by luminarie1** [comment]
히토미나 다른 사이트들은 잘 되는데 픽시브만 안되서요 ㅠㅠ 
다른 픽시브 다운로더도 정상인데...

**Comment by KurtBestor** [comment]
해당 작업 우클릭 후 정보... 눌러서 나오는 내용 보내주시면 분석해볼게요.

**Comment by luminarie1** [comment]
Error L: pixiv_https://www.pixiv.net / member_illust.php?id=242010

gal_num: https://www.pixiv.net/member_illust.php?id=242010
dir: 
zip: 
type: pixiv
artist: None
url: https://www.pixiv.net/member_illust.php?id=242010
valid: False
done: False
range: None
range_p: None


[File Names]



[URLs]



[Messages]
PIXIV_TYPE: user
stop
Traceback (most recent call last):
File "pixiv_downloader", line 61, in init
File "pixiv_downloader", line 261, in get_api
PixivError: requests POST https://oauth.secure.pixiv.net/auth/token error: HTTPSConnectionPool(host='oauth.secure.pixiv.net', port=443): Max retries exceeded with url: /auth/token (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x22AF40B0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',)))

Fail: pixiv

stop
done : https://www.pixiv.net/member_illust.php?id=242010

감사합니다 센세

**Comment by KurtBestor** [comment]
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

이거 되는지 테스트 부탁드려요.

**Comment by luminarie1** [comment]
빨간글씨로 읽는중... 에서 바뀌질 않네요 ㅠ

**Comment by luminarie1** [comment]
읽는 중... https://www.pixiv.net / member.php?id=361249

gal_num: https://www.pixiv.net/member.php?id=361249
dir: 
zip: 
type: pixiv
artist: None
url: https://www.pixiv.net/member.php?id=361249
valid: False
done: False
range: None
range_p: None


[File Names]



[URLs]



[Messages]
PIXIV_TYPE: user
stop
Traceback (most recent call last):
File "pixiv_downloader", line 61, in init
File "pixiv_downloader", line 264, in get_api
NameError: global name 'traceback' is not defined

Fail: pixiv

stop
done : https://www.pixiv.net/member.php?id=361249

이라고 나옵니다
