### ISSUE TITLE
마나 모아 다운로드에 문제가 있는 것 갖습니다

### ISSUE THREAD

**Issue by grave9** [KurtBestor/Hitomi-Downloader-issues#731]
저는 다운로드 밧으면 압축하기를 합니다 그런대
 [우오야마] 양아치 군과 흰지팡이 걸
[후지모토 타츠키] 체인쏘맨(전기톱맨)
[.] 영민 0명으로 시작하는 변경 영주님
[히노 토모유키] 나만 들어가는 숨겨진 던전~몰래단련해서 세계최강~
이박에 여러가지가   1장씩 모자르게 나오고 zip일이 된다음 주황색이 됩니다

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by grave9** [comment]
여러 가지 확인해보니 많이 괜찮아졌습니다
근대 몇몇 작품 더파이팅 
어째서냐 나이토
신극의 소마
새벽의 연화
등 몇몇 작풍이 아까 말 씀 드린 거처럼 같은 증상을 보이는 것 같습니다
(신극의 소마16장  새벽의 연화14장 어째서냐 나이토1장 차이로 아까 적은대로의 차이를 보입니다 )
ps 대단하시네요 사진도 업고 글만 적 어렸는데 홱홱 해결하시게 감 사이 잘 쓰고 있습니다

**Comment by KurtBestor** [comment]
해당 작업 `마우스 우클릭` - `정보... (I)` 눌러서 보시면 다운로드가 되지 않은 파일은 빨간색으로 표시되어있어요.
살펴봤는데 마나모아 서버 문제인 것 같아요.
문제 있는 화들 들어가보니 다음과 같이 뜨네요:
![image](https://user-images.githubusercontent.com/14768120/56095911-67666e80-5f1c-11e9-8ddb-2d44a7538588.png)

**Comment by grave9** [comment]
아~
설명감사드립니다
아휴 늦은 시간인데 답장 감사드려요👍


2019년 4월 15일 (월) 오전 1:19, Kurt Bestor <notifications@github.com>님이 작성:
