### ISSUE TITLE
설정이 제대로 작동되지 않습니다

### ISSUE THREAD

**Issue by mk4352** [KurtBestor/Hitomi-Downloader-issues#734]
히토미 다운로드하는데 이번 업뎃부터 전부터 타이틀 by 아티스트 였는데 [아티스트] 타이틀 로 나옵니다

**Comment by mk4352** [comment]
거기다가 이제보니 멋대로 히토미가 아니라 이헨으로 다운해놨네요;;

**Comment by mk4352** [comment]
설정이 문제가 아니라 히토미가 아니라 익헨으로 다운되는 문제였습니다 죄송합니다;;

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/720
