### ISSUE TITLE
사이트 전체를 다운받는 기능은 없을까요?

### ISSUE THREAD

**Issue by SHxXxJ** [KurtBestor/Hitomi-Downloader-issues#736]
사이트가 망할것을 대비해서 제 개인하드에 전부 보관하고 싶은데
사이트에 있는 모든 만화를 다운받는 기능은 없을까요?

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/351#issuecomment-447619182
