### ISSUE TITLE
질문) 파일을 2000개 이상을 받으려면 어떻게 하나요?

### ISSUE THREAD

**Issue by e50gun** [KurtBestor/Hitomi-Downloader-issues#737]
Gelbooru 이용하고있습니다.

이용해보니 한번받을때 2000개이상은 안되는것 같던데, 해결법을 알려주실 수 있을까요.

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/382#issuecomment-450846793

**Comment by e50gun** [comment]
도움이 많이 됬습니다 감사합니다
