### ISSUE TITLE
안녕하세요, 개발자가 언어 팩을 가지고 있습니까?이 소프트웨어를 중국어 간체로 번역하고 싶습니다.

### ISSUE THREAD

**Issue by lhj5426** [KurtBestor/Hitomi-Downloader-issues#738]
이 소프트웨어를 자주 사용합니다.이 소프트웨어를 중국어 간체로 번역하고 싶습니다.

**Comment by KurtBestor** [comment]
다음 파일을 번역해주시면 추가해볼게요: [tr_dic.txt](https://github.com/KurtBestor/Hitomi-Downloader-issues/files/3079469/tr_dic.txt)


다음과 같이 적혀져 있는 파일을:
```
기본 데이터 다운로드
Download Default data
```
다음과 같이 수정하시면 돼요:
```
기본 데이터 다운로드
下载默认数据
```

**Comment by lhj5426** [comment]
안녕하세요. 개발자, 저는 이미 텍스트를 번역했습니다. 드릴게요.
[tr_dic.txt](https://github.com/KurtBestor/Hitomi-Downloader-issues/files/3082710/tr_dic.txt)

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by lhj5426** [comment]
[tr_dic.txt](https://github.com/KurtBestor/Hitomi-Downloader-issues/files/3083161/tr_dic.txt)

개발자 덕분에 몇 가지 잘못된 번역을 수정했습니다.

또한 번역문을 업데이트하십시오.

50 개 주사 커커스 검색
Search in splits for 50 each

 이 기능은 무엇을 의미합니까? 나는 그것을 이해하지 못합니다. 결코 사용한 적이 없어서 번역하는 방법을 모르겠습니다.

**Comment by KurtBestor** [comment]
`50개씩 끊어서 검색` - 체크하지 않으면 검색기에서 검색할 때 1000개 씩 끊어서 검색해요.

**Comment by lhj5426** [comment]
개발자가 귀하의 설명을 한 후에,이 기능은 검색 항목의 수를 제한하는 데 사용된다는 것을 알고 있습니다.

함수를 시스템에 모르는 누락 된 항목을 이미 번역했습니다.
[tr_dic.txt](https://github.com/KurtBestor/Hitomi-Downloader-issues/files/3084184/tr_dic.txt)

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by lhj5426** [comment]
[tr_dic.txt](https://github.com/KurtBestor/Hitomi-Downloader-issues/files/3088124/tr_dic.txt)
개발자에게 감사드립니다! ! !

사고가 없다면, 이것이 내 마무리 일 것입니다. 다양한 기능. 프로젝트 테스트.


중국화의 학위는 98 %

**Comment by lhj5426** [comment]
![BaiduShurufa_2019-4-17_14-11-5](https://user-images.githubusercontent.com/30548000/56264927-aa8e3080-611a-11e9-92d4-80125be65867.png)
중국어 간체이든 영어이든 비어 있습니다. 2.6A 2.6B가 변경되었습니다.

이 기능에 무엇이 있어야합니까? ?

**Comment by 5hoho** [comment]
lhj5426//
Search = 검색순서 (搜索顺序)
 Nomal (보통 一般)
 Revers (거꾸로 反)
중국어 몰라서 번역기 사용함
혹시 몰라서 영어로도 
![확인](https://user-images.githubusercontent.com/49427447/56267043-ae28b400-6128-11e9-94a5-07b3bf8ad851.jpg)

**Comment by KurtBestor** [comment]
다음 참고해서: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

다음 파일 번역해주세요: [tr_dic.txt](https://github.com/KurtBestor/Hitomi-Downloader-issues/files/3088342/tr_dic.txt)

**Comment by lhj5426** [comment]
[tr_dic.txt](https://github.com/KurtBestor/Hitomi-Downloader-issues/files/3088635/tr_dic.txt)
작가 합쳐서 불러오기
Load all artists together

저장 폴더에 있는 모든 작가 불러오기
Load all artists in the download folder

연결 프로그램 변경
Choose the program to use to open

새 언어 파일

분류에 관한 섹션은 중국어 간체로 번역되었습니다.

그러나

이 3 함수를 찾지 못했습니다. 함수의 특정 의미를 이해하지 못합니다. 그래서 그것을 번역하지 않았습니다.

추천 아티스트도 있습니다. 여기에 공백이 있습니다.이 세 가지 번역이 이에 해당합니까? ? ?
![BaiduShurufa_2019-4-17_16-40-28](https://user-images.githubusercontent.com/30548000/56273633-afa9aa80-612f-11e9-8c99-49118ebcf4df.png)

**Comment by KurtBestor** [comment]
![image](https://user-images.githubusercontent.com/14768120/56277465-5ea1b280-613f-11e9-9015-dc81094d725b.png)

![image](https://user-images.githubusercontent.com/14768120/56277447-547fb400-613f-11e9-996c-fd496aa2af36.png)

![image](https://user-images.githubusercontent.com/14768120/56277480-63fefd00-613f-11e9-8b20-dc71724c6a83.png)

**Comment by lhj5426** [comment]
[tr_dic.txt](https://github.com/KurtBestor/Hitomi-Downloader-issues/files/3089248/tr_dic.txt)

연결 프로그램 변경
Choose the program to use to open


문제 개발자

이 기능은 이미 이해되고 번역되었습니다.

-------------------------------------
이 2 가지 기능에 대해서


작가 합쳐서 불러오기
Load all artists together

저장 폴더에 있는 모든 작가 불러오기
Load all artists in the download folder

나는 정말로 무엇을해야할지 모른다.

이 두 장소가 남아 있다는 느낌이 들지 않습니까?
------------------------------------------------

![asd1](https://user-images.githubusercontent.com/30548000/56283141-724f1800-6143-11e9-90b1-d9a5f2615f5e.gif)

**Comment by KurtBestor** [comment]
Ctrl + Alt + C 눌러서 콘솔창 띄우고
콘솔에 다음과 같이 입력해서 나오는 내용 각각 알려주세요:
```
for font in QtGui.QFontDatabase().families(QtGui.QFontDatabase.Korean): print unicode(font.toUtf8(), 'utf8')
```
```
for font in QtGui.QFontDatabase().families(QtGui.QFontDatabase.SimplifiedChinese): print unicode(font.toUtf8(), 'utf8')
```

**Comment by lhj5426** [comment]
나는 프로그래머가 아니며 콘솔이 무엇인지 이해하지 못한다.


CMD라면 유감입니다.
![BaiduShurufa_2019-4-17_19-51-3](https://user-images.githubusercontent.com/30548000/56285586-281d6500-614a-11e9-967c-ff9a33c81bbe.png)

**Comment by lhj5426** [comment]
![BaiduShurufa_2019-4-17_19-54-46](https://user-images.githubusercontent.com/30548000/56285807-ad087e80-614a-11e9-8a5e-1f0b8b032df6.png)
UI에서 어떤 글꼴이 잘 보이는지 묻는 것입니까?

**Comment by KurtBestor** [comment]
다음 내용 입력한 다음 나오는 내용 알려주세요:
```
exec(u"s = u''\nfor font in QtGui.QFontDatabase().families(QtGui.QFontDatabase.Korean):\n s += u'\\n' + unicode(font.toUtf8(), 'utf8')\ns += '\\n\\n\\n'\nfor font in QtGui.QFontDatabase().families(QtGui.QFontDatabase.SimplifiedChinese):\n s += u'\\n' + unicode(font.toUtf8(), 'utf8')\nwith open('fonts.txt', 'w') as f:\n f.write(s.encode('utf8'))\nos.startfile('fonts.txt')")
```

**Comment by lhj5426** [comment]
실행 후 팝업 됨
DFHeiMedium-B5
DFPHeiMedium-B5
Malgun Gothic
Malgun Gothic Semilight
杯水怀心字幕体



DFHeiMedium-B5
DFPHeiMedium-B5
Fixedsys
Malgun Gothic Semilight
Microsoft YaHei UI
Microsoft YaHei UI Light
SimSun-ExtB
System
Terminal
仿宋
华文中宋
华文仿宋
华文宋体
华文彩云
华文新魏
华文楷体
华文琥珀
华文细黑
华文行楷
华文隶书
宋体
幼圆
微软雅黑
微软雅黑 Light
思源黑体 CN Medium
思源黑体 HW Bold
新宋体
方正中雅宋_GBK
方正兰亭粗黑_GBK
方正准圆_GBK
方正喵鸣
方正大标宋_GBK
方正姚体
方正小标宋_GBK
方正楷体_GBK
方正稚艺_GBK
方正粗圆_GBK
方正舒体
杯水怀心字幕体
楷体
等线
等线 Light
迷你简卡通
隶书
黑体

**Comment by KurtBestor** [comment]
다음 내용 입력한 다음 나오는 내용 알려주세요:
```
print unicode(QtGui.QFont().family().toUtf8(),'utf8')
```

**Comment by lhj5426** [comment]
![BaiduShurufa_2019-4-17_21-40-33](https://user-images.githubusercontent.com/30548000/56292271-7423d600-6159-11e9-939a-99554ce8cc32.png)
이쪽으로

**Comment by KurtBestor** [comment]
다음 참고해서: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

다음 파일 번역해주세요: [tr_dic.txt](https://github.com/KurtBestor/Hitomi-Downloader-issues/files/3089985/tr_dic.txt)

**Comment by lhj5426** [comment]
[tr_dic.txt](https://github.com/KurtBestor/Hitomi-Downloader-issues/files/3090075/tr_dic.txt)

증가한 항목 번역 완료

**Comment by lhj5426** [comment]
![image](https://user-images.githubusercontent.com/30548000/56295689-bb14ca00-615f-11e9-83d9-6893ab3abc58.png)
이 부분의 텍스트를 발견하지 못했습니다.

이 기능을 제가 다 써본 적이 없어요. 하하.

**Comment by lhj5426** [comment]
![image](https://user-images.githubusercontent.com/30548000/56295850-fadbb180-615f-11e9-9b7b-4009a790c4cd.png)

이 두 줄 텍스트도 없다

사실 이런 거의 상용되지 않는 기능번역은 번역을 안 하면 다 나쁘지 않을 거예요.

근데 약간 강박증이 있어요.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

번역은 여기까지면 충분할 것 같네요.

수고하셨습니다! 정보 부분에 이름 적어드렸어요:
![image](https://user-images.githubusercontent.com/14768120/56298757-b0f9c800-616d-11e9-9cf3-2a79f23f45cc.png)

**Comment by lhj5426** [comment]
개발자


드디어 중국어로 편하게 할 수 있어요.

**Comment by lhj5426** [comment]
Errors occurredx
See the logfile'J:\hitomi downloader GUI test
（4）\hitomi_downloader_GUl.exe.log'for details


Traceback (most recent call last):
  File "hitomi_downloader_GUI.py", line 4395, in <module>
NameError: name 'dupFinderWindow' is not defined

방금 실행 오류를 다운로드하고 있습니다.

다른 프로세스를 시작할 수 없음을 직접 오픈합니다


로그 내용입니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by lhj5426** [comment]
테스트 OK. 문제 없어요.
 수고했어
