### ISSUE TITLE
폴더명 형식 설정할때 마나모아 밖에 안되는 것 같아요

### ISSUE THREAD

**Issue by Secondary2838** [KurtBestor/Hitomi-Downloader-issues#739]
저장 폴더를 임의로 설정하고 
저장폴더 밑에 폴더명 형식을 설정하는게 있는데
저는 작가명을 지우고 다운받는게 좋아서 지우고 다운 받고 있는데
[artist] title 이런식으로 된거를 [artist]를 지우고 title만 적혀있는 걸 폴더 제목으로 받고 싶은데
마나모아는 폴더명 형식을 바꾸니까 잘 되는데 jmana나 다른 것들은 잘 적용이 안되는 것 같아요
한번 확인부탁드려요

**Comment by KurtBestor** [comment]
Jmana도 되게 수정했어요.
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview
