### ISSUE TITLE
밤 토 ! 끼 토밤토끼! 다운이안되염!

### ISSUE THREAD

**Issue by rabirabin** [KurtBestor/Hitomi-Downloader-issues#74]
마루마루나 꺼토미처럼 그냥 하면되는거아닌가요? ㅠㅡㅠ

**Comment by rabirabin** [comment]
밤토끼 마루마루처럼 리스트 쫙나와있게 해서 통째로 다운해봤는데 안되고 한 화 들어가서 다운눌러봤는데 안되염

**Comment by rabirabin** [comment]
저녁쯤에 올려드릴게요!! 지금 일하고있어서 ㅠㅠㅠㅠㅠㅠ

**Comment by rabirabin** [comment]
![20180402_202819](https://user-images.githubusercontent.com/34975196/38194743-734d4408-36b4-11e8-8ae2-6e1a5e8842c0.png)

**Comment by KurtBestor** [comment]
URL을 복사할 때 무슨 브라우저 쓰셨나요

**Comment by KurtBestor** [comment]
일단 이걸로 테스트 부탁드려요:

https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

만약 다운로드가 안되면 해당 작업 우클릭 후 정보... 눌러서 나오는 내용 보내주세요.

**Comment by rabirabin** [comment]
죄송한댐 내일 꼭 알려드릴게요 일이밀려서 ㅠㅠㅠㅠㅠㅠㅠㅠ

**Comment by rabirabin** [comment]
어! 이건되요!!!!!!!!!!!!!!!!!!!!
