### ISSUE TITLE
마나모아 에서 같은 파일명일 경우 다운되지 않습니다

### ISSUE THREAD

**Issue by luku756** [KurtBestor/Hitomi-Downloader-issues#740]
마나모아에서 파일명이 중복되었을 경우 제대로 인식되지 않는 경우를 발견했습니다.

![캡처](https://user-images.githubusercontent.com/43954535/56144843-15861d00-5fde-11e9-8889-9d6134478b11.PNG)
![캡처2](https://user-images.githubusercontent.com/43954535/56144851-174fe080-5fde-11e9-8074-640a1096d6dd.PNG)

이름은 같지만 업로드 측의 실수(?)로, 둘은 다른 편입니다.
3.5편이 두개 있는데 하나만 인식되네요. 
간혹 이런 경우가 있는데 아래 이슈에서는 인식은 되지만 한 폴더에 저장된다고 착각했는데, 다시 찾아보니 아예 인식이 되지 않는 것 같네요.

위 경우에서는 앞쪽을 무시하고 뒤쪽에 있는 편이 인식되었습니다.
위 경우는 실수로 보입니다만 '번외편' 같은 경우 그냥 번외편 이라는 이름으로 업로드되는 경우가 꽤 잦습니다. 번외편 1~10이 전부 번외편 으로 올라갑니다.

예시 만화의 주소입니다.
https://manamoa2.net/bbs/page.php?hid=manga_detail&manga_name=%EB%82%98+%EC%9D%B4%EC%99%B8+%EC%9D%B8%EB%A5%98%EC%A0%84%EC%9B%90+%EB%B0%B1%ED%95%A9

**Comment by KurtBestor** [comment]
다음 것들처럼 중복된 화는 스킵하게 만든건데, 문제가 생기네요:
https://manamoa2.net/bbs/page.php?hid=manga_detail&manga_name=피치걸
https://manamoa2.net/bbs/page.php?hid=manga_detail&manga_name=프리티%20페이스
https://manamoa2.net/bbs/page.php?hid=manga_detail&manga_name=프리킥
https://manamoa2.net/bbs/page.php?hid=manga_detail&manga_name=황혼%20메모랜덤
https://manamoa2.net/bbs/page.php?hid=manga_detail&manga_name=황제와%20환관

번외편이 같은 이름으로 여러 개 올라온 만화가 어떤 게 있는지 알려주실 수 있나요?
