### ISSUE TITLE
다운로드 오류 관련 문의드립니다

### ISSUE THREAD

**Issue by siwkd2** [KurtBestor/Hitomi-Downloader-issues#741]
엑스비디오 다운로드중 제목이 매우 길거나 제목중에 링크가 포함된경우

제목 : Korean couple home sex - Watch Full: http://jpbabe.com

이런걸 추가할시 다운로더가 갑자기 렉이걸리더니 다운로드가 되지 않는현상이 일어납니다

시간나시면 업데이트 부탁드립니다 문의사항 읽어주셔서 감사합니다

**Comment by siwkd2** [comment]
https://www.xvideos.com/video22601523/korean_couple_home_sex_-_watch_full_http_jpbabe.com

엑스비디오 다운로드중 제목이 매우 길거나 제목중에 링크가 포함된경우 다운로더가 갑자기 렉이걸리더니 다운로드가 되지 않는현상이 일어납니다
 
> 시간나시면 업데이트 부탁드립니다 문의사항 읽어주셔서 감사합니다

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by siwkd2** [comment]
> 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

작동 잘됩니다 업데이트 해주셔서 감사합니다

한가지 걸리는게 있다면 이런 제목에 링크가 첨부된 영상을 2~3개 연속으로 다운받을시 팅기는점이 있기는하나 간격을 두고 다운로드하면 별문제는 없을것같습니다
