### ISSUE TITLE
특정 PC에서는 정상 다운로드가 되지 않는 것 같습니다.

### ISSUE THREAD

**Issue by GH6** [KurtBestor/Hitomi-Downloader-issues#745]
같은 OS에 같은 네트워크를 사용하고 있는데 어떤 컴퓨터는 hitomi에서 바로 다운로드가 되는데 어떤 컴퓨터에서는 e-hentai에서 다운로드가 됩니다.
분명 Hitomi에서도 동일제목, 동일번호를 가지고 있습니다.
또, 가끔은 hyobi에서도 받아진적이 있고, hitomi에서는 받아진 적이 없습니다.
내가 어떻게 해야 합니까?

**Comment by KurtBestor** [comment]
최신버전 맞나요?

**Comment by GH6** [comment]
> 
> 
> 최신버전 맞나요?

네, 맞습니다.

**Comment by KurtBestor** [comment]
확인해주세요:
1. `옵션` - `설정` - `히토미 설정` - `서버` 를 `자동` 으로 변경
2. `옵션` - `설정` - `고급 설정` - `DPI 우회` 킴

그래도 안 되면 hitomi 에서 다운로드 안 된 작업 `마우스 우클릭` - `정보... (I)` 눌러서 나온 내용 보여주세요.
