### ISSUE TITLE
현재 호두 어른아이 닷컴등 웹툰 다운로드 사이트는 지원 중단하신건가요?

### ISSUE THREAD

**Issue by inchaos4315** [KurtBestor/Hitomi-Downloader-issues#746]
이슈들중 '웹툰'키워드로 검색하여 나온 사이트들중

https://toonkor.live/
https://hodu57.com/
https://adulti66.com/

등등.. 웹툰 제공해주는 사이트를 이용하면 

Can not determine type: https://~~~

하는 결과가 나오네요 ㅜ

https://github.com/KurtBestor/Hitomi-Downloader-issues#supported-sites

에서도 확인이 불가하고

웹툰 사이트들은 지원 중단하신건가요?

혹시 지원해주시는 사이트 목록에 없는

웹툰 다운로드 가능 사이트가 있나요?

**Comment by KurtBestor** [comment]
`도움말` - `사용법... (F1)` - `스크립트` 봐주세요.

참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/729

**Comment by inchaos4315** [comment]
아 감사합니다 웹툰 키워드로 이것저것 검색 했었는데 저런 방법이었군요 ㅜㅠ 감사합니다 감사합니다

**Comment by kingsangsu** [comment]
호두코믹스 주소 https://yajasoo.net/
