### ISSUE TITLE
많이 사용했더니 Gelbooru에서 차단당한거같은데 어떡하나요...

### ISSUE THREAD

**Issue by e50gun** [KurtBestor/Hitomi-Downloader-issues#747]
다운로더는 물론이고

인터넷에서 접속자체가 막힌거같네요.

해결법이라던가... 알수있을까요..?

**사이트에 연결할 수 없음 연결이 재설정되었습니다.
다음 방법을 시도해 보세요.

연결 확인
프록시 및 방화벽 확인
Windows 네트워크 진단 프로그램 실행
ERR_CONNECTION_RESET**

ㅠㅠ

**Comment by KurtBestor** [comment]
해당 작업 `마우스 우클릭` - `정보... (I)` 눌러서 나온 내용 보여주세요.

**Comment by e50gun** [comment]
답변감사드립니다. 다운받은게 하도 많고 완료한  후에 다 완료된작업 제거한후라 말씀하신정보를 알 수가 없네요...

**Comment by KurtBestor** [comment]
DPI 우회 끄고 들어가봤더니 저도 그렇게 뜨네요.

설정에서 DPI 우회 키셨나요?

**Comment by e50gun** [comment]
배포하신 프로그램 그대로 아무것도 안만지고사용했어요... DPI 우회가 뭔지도 모릅니다.

**Comment by e50gun** [comment]
지금보니까 꺼져있네요......
