### ISSUE TITLE
스크립트 변경후 다운이 되지않습니다.

### ISSUE THREAD

**Issue by ggobugy** [KurtBestor/Hitomi-Downloader-issues#751]
안녕하세요
뉴토끼 사이트가 11로 변경되어
![캡처](https://user-images.githubusercontent.com/49754332/56360458-a566d980-621f-11e9-99db-935a2ccba8e0.PNG)

이렇게 스크립트를 수정 후 다운을 시도했지만 다운이 되지않아 문의 드립니다.

아래처럼 오류메세지가 뜹니다. 

![123213](https://user-images.githubusercontent.com/49754332/56360502-cdeed380-621f-11e9-8ced-72be2af20d98.PNG)

**Comment by KurtBestor** [comment]
다음과 같이 목록 주소를 입력해주세요: https://newtoki11.net/comic/229748

`[0-9]` 로 되어있는 부분은 `[0-11]`로 바꾸지 않으셔도 돼요. 바꾸면 오히려 newtoki12.net 이 인식 안 돼요.

**Comment by ggobugy** [comment]
해결했습니다. 정말 감사합니다.
