### ISSUE TITLE
4월이후 히토미 갤러리중 일부 검색이 안되는 갤러리가 있습니다. 

### ISSUE THREAD

**Issue by dcie** [KurtBestor/Hitomi-Downloader-issues#752]
https://히요비.asia/reader/354281#1-

https://hitomi.la/galleries/354281.html

https://히요비.asia/reader/1377997#1-

https://hitomi.la/galleries/1377997.html

4월이후 기본데이터나 삭제된 데이터에서 검색이 안되는 갤러리 넘버가 제법 있습니다.

위에 넘버는 검색기로는 찾을수 없지만 히요비 홈페이지에서 검색하면 바로 나와서

다운로드 가능합니다. 

검색기에서 누락된 갤러리가 있으면 추가로 피드백 드리겠습니다. 

항상 

감사합니다.

**Comment by KurtBestor** [comment]
1381776은 검색 되네요. `기본 데이터`가 오래되면 안 보일 수 있어요. `메뉴` - `기본 데이터 다운로드...` 눌러서 업데이트해주세요.

354281은 최근에 삭제된 것 같은데, `삭제된 데이터`는 거의 일주일 단위로 업데이트되니 참고해주세요.
