### ISSUE TITLE
크롤러 서버 임시 다운 (내용필)

### ISSUE THREAD

**Issue by kikinet88** [KurtBestor/Hitomi-Downloader-issues#755]
서버 작업중입니다

20일 오전 06시에 재오픈됩니다

그전까지 데이터 다운로드 안됩니다

관리자님이 켜두신다면 다행이지만

일단 제 서버가 지금 하드웨어 교체로 오프라인 상태라서

서버를 켜둘수가 없습니다

**Comment by KurtBestor** [comment]
데이터 서버는 안 꺼지니까 다운로드는 가능해요. 잠깐 정도는 끄셔도 아무 문제 없어요. 감사합니다.
