### ISSUE TITLE
히요비에서 일부 만화가 다운되지 않습니다.

### ISSUE THREAD

**Issue by ChoiHaNoel** [KurtBestor/Hitomi-Downloader-issues#758]
https://hiyobi.me/info/10000114
https://hiyobi.me/info/10000107
https://hiyobi.me/info/10000109

이 세작품을 받고 싶은데 저번엔 404, 이번엔 주황색으로 다운이 되지 않습니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by ChoiHaNoel** [comment]
> 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

잘 작동합니다. 감사합니다.
