### ISSUE TITLE
소설가가 되자 관련 건의입니다..

### ISSUE THREAD

**Issue by teril43** [KurtBestor/Hitomi-Downloader-issues#759]
소설가가 되자 사이트 추가 및 빠른 기능개선에 감사드립니다.

제목 밑으로 소위 Ncode라고 불리는 되자 특유의 소설 분류 번호가 붙으면

좋을 것 같습니다.

예시
대상 = https://ncode.syosetu.com/n1795cg/
Ncode = n1795cg

**Comment by KurtBestor** [comment]
붙으면 좋은 이유가 있나요?

**Comment by teril43** [comment]
> 붙어 좋은 이유가 있습니까?

검색이 편해집니다. 

대체로 사용자들은 번역기를 돌려 사용하리라 생각됩니다만,

방식에 따라 제목만을 번역해서 저장했을 경우 원문을 알 수 없게 되기 때문에

큰 도움이 됩니다.

번역한 걸 역 번역할 시 검색이 안 되는 경우도 있거든요..

일어실력이 될 경우에는 번역문으로 원문을 유추할 수도 있으나 아무래도 Ncode가 있는 쪽이 편하지요.

**Comment by KurtBestor** [comment]
제목은 파일명에 들어가니 상관 없지 않을까요?
