### ISSUE TITLE
파일 받을 때 이미지 사이즈 문의/건의사항

### ISSUE THREAD

**Issue by aoahrvl** [KurtBestor/Hitomi-Downloader-issues#76]
이헨에서 긁어온 주소는 이미지를 원본크기로 저장하지 않네요
더 큰 크기의 이미지가 존재하긴 하는데, 이헨 자체 웹뷰어에 표시되는 사이즈만 받더라구요..

제가 사용법을 모르는건지.. 아니면 원래 압축이미지만 받도록 설정되어있는건지?
혹시 지원하고 있지 않다면 추가하실 생각은 없는가 하여 들릅니다

글고 혹시 후원안받으시나요?ㅎ;

**Comment by KurtBestor** [comment]
네, 현재는 뷰어에서 보이는 이미지를 받습니다.

원본 이미지 다운로드 기능은 나중에 추가될 수도 있습니다. 지금은 우선순위가 그리 높지 않네요.

후원은 현재 따로 받고 있지 않습니다.
