### ISSUE TITLE
버전 관련 질문드립니다.

### ISSUE THREAD

**Issue by ixkatan** [KurtBestor/Hitomi-Downloader-issues#760]
일반적으로 업데이트되는 2.6a 2.6b 이런 파일들과

테크니컬 프리뷰 파일은 어떤 차이가 있는건가요?

그리고 다운받은 기록이 있는 파일은 상단 왼쪽에 체크표시가 뜨는데

버전을 업데이트할 경우 해당 체크표시가 사라져버려서 곤란하네요

체크표시를 유지하는 방법이 혹시 있을까요?

**Comment by KurtBestor** [comment]
`Technical preview` 는 정식 버전 업데이트 이후에 자잘한 버그나 기능 수정이 이루어진 버전이에요.

`자동 업데이트` 하시거나 실행파일을 덮어 씌우시면 설정이 유지돼요.

**Comment by ixkatan** [comment]
게시물 삭제 부탁드립니다.
