### ISSUE TITLE
호두 토끼 같은 웹툰 다운 못하나요??

### ISSUE THREAD

**Issue by g4560** [KurtBestor/Hitomi-Downloader-issues#761]
마나모아 유툽은 다되는데 위에 있는 사이트들은 다운이 안되네요..
어떻게 하면 다운 할수잇나요?? 궁금해서 회원 가입했습니다

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/746
