### ISSUE TITLE
간혹 '디렉터리가 올바르지 않습니다'라는 경고창이 뜨면서 파일이 열리지 않습니다.

### ISSUE THREAD

**Issue by edgv** [KurtBestor/Hitomi-Downloader-issues#762]
다운로드받았을때 다운로드는 다된상태에서 노란색? 글씨가 초록색으로 바뀌지 않습니다.

이경우 폴더로 들어가서 파일을 열면 '디렉터리가 올바르지 않습니다'라는 경고창이 뜨고 파일이 열리질 않습니다.

이 경고창이 한번 뜬 작품의 경우에는 다시 다운로드 받아도 똑같은 현상이 발생합니다.

**Comment by KurtBestor** [comment]
해당 작업 `마우스 우클릭` - `정보... (I)` 눌러서 나온 내용 보여주세요.
