### ISSUE TITLE
히토미 애니의 다운로드가 진행되지가 않습니다

### ISSUE THREAD

**Issue by Reusy** [KurtBestor/Hitomi-Downloader-issues#763]
히토미 만화는 잘 다운되는데 애니쪽만 다운이 되지가 않네요

Helter Skelter： Hakudaku no Mura 3 (4352)

version: 2.6b
platform: Windows-10-10.0.17134
gal_num: https://hitomi.la/galleries/4352.html
dir: hitomi_downloaded
zip: 
type: hitomi
artist: None
url: https://hitomi.la/galleries/4352.html
valid: False
done: True
range: None
range_p: None
single: True
time: 1555786860.38 (Apr 21)
tags: []
goodbyedpi: True
lock: False

[Gallery]
None

[File Names]
[0001] hitomi_downloaded\Helter Skelter： Hakudaku no Mura 3 (4352).mp4

[URLs]
[0001] https://streaming.hitomi.la/videos/helter-skelter-hakudaku-no-mura-3.mp4

[Messages]
********************************
Gallery number : 4352
Number of Threads : 64
********************************
Size (https://la.hitomi.la/galleries/4352/02.png): 0 status: None
Size (https://aa.hitomi.la/galleries/4352/02.png): 1121333 status: 200
anime
get_title__
downloader_v3 fail... p[0 / 1]
Traceback (most recent call last):
File "downloader_v3", line 57, in run
Exception: Not partial content: 403

valid=False 1
done : https://hitomi.la/galleries/4352.html

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by Reusy** [comment]
잘 다운 되네요! 감사합니다
