### ISSUE TITLE
히토미와 익헨 파일명과 검색기 건의사항

### ISSUE THREAD

**Issue by Rounlet** [KurtBestor/Hitomi-Downloader-issues#764]
안녕하세요, 거듭 발전하는 히토미 다운로더가 이젠 없으면 안될 수준까지 올라왔습니다. 
라이센스 비용 받으셔도 될거 같은데..ㅋ

다른건 아니고 건의사항 하나가 있습니다.
아시다시피 다운로더 설정에 보면 파일명 형식을 사용자가 설정하는 부분이 있습니다.

예를 들어,
[artist][group] title (id) 이런 식으로 설정해서 여태껏 다운받았는데
이 형식을 조금이라도 벗어나게 되면 검색기에서 이미 다운로드된 것들을 인식하지 못합니다.

파일명 설정을 애초에 통일하면 문제가 없겠습니다만 정리를 하다보니
기존에 받은 자료는 많고 파일명을 일일이 바꿔주기 힘들어서 
다시 다운로드 받자니 너무 비효율 적이고..

차라리 저 (id)부분만 동일하다면 검색기에서 이미 다운로드된 것으로 표시될 수 있게끔 
업데이트를 해보시면 어떨까 제안드립니다.

ps. 익헨 다운로드가 리사이징된 이미지를 다운로드하던데, 

Source Nexus : Unlocks the Original Images functionality on E-Hentai Galleries. This allows you to browse the original, non-resampled version of a gallery directly.

이 기능을 열면 원본크기로 다운로드 가능한가요?

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/1240#issuecomment-843747402
