### ISSUE TITLE
익헨도 검색기에 나타나게 하는 기능 추가하는 건 어떨까요?

### ISSUE THREAD

**Issue by shopinclude** [KurtBestor/Hitomi-Downloader-issues#765]
생각보다 절차대로 해도 접속 안 되는 사람들이 많은데, 익헨 접속 못하는 사람들에게 유용할 것 같습니다. 한번 기능 건의는 드려봅니다.

**Comment by KurtBestor** [comment]
E-hentai 나 Hitomi.la 에 대부분 있으니 필요 없을 것 같아요.

**Comment by shopinclude** [comment]
아무래도 히토미에는 익헨에 있는 서양 쪽 아트가 거의 없으니까요. 익헨에만 존재하는 자료들도 확실히 있고... 이헨의 경우 검열되는 작품들이 많기도 하고요. 어쨌든 답변 감사합니다.
