### ISSUE TITLE
관리자님 사이트 추가 건의드려도 될까요? 

### ISSUE THREAD

**Issue by dcie** [KurtBestor/Hitomi-Downloader-issues#768]
해당 사이트 추가 건의드립니다. 

https://www.iwara.tv/

픽시브 사이트처럼 주소만 입력하면

게시물을 올린 사람 자료가 한번에 다운로드 가능하게 

추가해주시면 감사하겠습니다.

항상 

감사합니다.

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/675

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/1098
