### ISSUE TITLE
저장 장소를 바꿨는데 로드가 이상합니다.

### ISSUE THREAD

**Issue by cjstkd135** [KurtBestor/Hitomi-Downloader-issues#769]
전에쓰던 컴퓨터에서 새컴퓨터로 저장장소를 바꾸었는데, 리스트의 절반 정도만 정상적으로 뜨고 나머지는 다시 처음부터 다운받는 듯한 현상이 일어나서 최신버전에서는 꺼져서 읽을 수 가 없습니다.

**Comment by KurtBestor** [comment]
리스트에 작업 갯수가 얼마나 되나요?

**Comment by cjstkd135** [comment]
1500개 정도된거 같아요

**Comment by KurtBestor** [comment]
다운로더 목록에서 900개 이상은 권장하지 않아요. 참고해주세요: #170
