### ISSUE TITLE
사이트 추가 건의드립니다

### ISSUE THREAD

**Issue by sorksnrnsi** [KurtBestor/Hitomi-Downloader-issues#77]
flickr.com 가 추가된다면 좋을거 같습니다.

웬만한 사이트들은 긁을만한 방법들이 다 있는데, 플리커만 한번에 긁는 방법을 못찾겠더라구요...

혹시 가능하시다면 플리커도 고려부탁드립니다.

**Comment by KurtBestor** [comment]
찾아봤는데, 다음과 같은 프로그램들이 이미 있네요:
http://getbulkr.com/
http://flickrdownloader.laboone.net/

두 개 모두 원본 이미지는 다운로드 받을 수 없더군요,, 따로 결제를 해야되네요.

그래서 한번 만들어 보았습니다. 테스트 부탁드려요:
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

로그인을 하지 않으면 Safe level이 Safe인 것만 보이고 Moderate이나 Restricted인 게 안보이더라구요. 그래서 기본적으로 로그인하도록 만들었습니다.
계정에 설정된 Safe level대로 다운로드합니다.

**Comment by sorksnrnsi** [comment]
로그인 후에 계정 연결하니 매우 잘 작동하는 것 같습니다.
가장큰 원본 사이즈로 받아지는 것 같네요.
테스트 버전이라 그런지 다운로드시에 윈도우 디펜더에서 차단을 당해서 끄고 받았습니다.

별 문제없이 작동하는 것 같습니다.

혹시나 한 가지 더 추가해 주실 수 있으시다면,
현재는 사진이 업로드 날짜와는 다르게 섞여 있는데,
다른 사이트 이미지를 긁었을 때처럼 파일명 앞에 날짜 등을 기록해서 순서대로 정렬될 수 있도록 하는 기능이 있었으면 더 좋을 것 같습니다.

매우 빠른 피드백 감사드립니다.

**Comment by KurtBestor** [comment]
파일에 적힌 숫자 순대로 날짜 맞지 않나요?

**Comment by sorksnrnsi** [comment]
https://www.flickr.com/photos/110264433@N05/

테스트로 몇 군대를 긁어보고 이쪽이 사진양이 적어 예시로 들었습니다.

가장 최근의 사진이 2017년 9월 26일 사진인데,

파일명은 36658910143.jpg 입니다.

최근 업로드된 사진일수록 숫자가 커서 뒷쪽에 정렬되는줄 알았는데, 

https://www.flickr.com/photos/110264433@N05/34516064804/in/dateposted/
2017년 6월 17일

https://www.flickr.com/photos/110264433@N05/34737265522/in/dateposted/
2017년 5월 26일

위 두 사진의 경우처럼 날짜가 더 과거의 것인데도 불구하고 파일명의 숫자가 높은 경우가 존재하는 것 같습니다.

어떤규칙으로 파일명이 정해지는지는 모르겠지만, 최근에 업로드 된 사진일수록 파일명에 따라 순서가 뒤죽박죽으로 섞이는 것 같습니다.

업로드 날짜와 촬영 날짜가 다른 경우가 존재하기 때문에, 이것과도 파일 순서를 비교해봤는데,
이 규칙으로도 순서가 달랐습니다.


플리커 원본 사진을 받을 수 있는 것만으로도 감사합니다. 바쁘실텐데 일일히 신경써주셔서 감사합니다.

**Comment by KurtBestor** [comment]
그렇군요,, 고친 버전입니다:
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

같은 날에 순서가 섞일 수도 있지만 하루 정도는 별 상관 없을 것 같아 이대로 가려고 합니다. 시간단위 넣기에는 지저분해질 것 같아서요.

**Comment by sorksnrnsi** [comment]
테스트 완료했습니다. 잘 작동하는 것 같습니다. 감사합니다.
