### ISSUE TITLE
SNS 질문과 고급설정 내 크기조절/이미지 포맷변환 관련...

### ISSUE THREAD

**Issue by realfeel87** [KurtBestor/Hitomi-Downloader-issues#770]
히토미 다운로더 언제나 충성충성입니다!
사용하다보니 궁금한 점이 있어서 이렇게 글남깁니다.

현재 SNS의 비공개 계정의 다운로드는 불가한걸로 알고 있습니다.
어떤 원리로 다운로드가 되는건지는 잘 모르겠지만...
그 비공개 계정과 자신의 계정이 서로 팔로우 되어 있다면, 다운로드가 가능하지 않을까 하는...
단순한 생각에 이렇게 질문글 남깁니다.

즉, 히토미 다운로더 설정 내에 각각 개인의 SNS 계정을 동기화 시켜 놓는다면, 비공개 계정도 다운로드가 가능하지 않을까...?? 하는 단순한 생각에 이렇게 여쭈워봅니당..

두번째로, 고급 설정 질문입니다.
현재 고급 설정 기능 중에서도 "크기 조절" 기능과 "이미지 포맷 변환" 기능을 체크 하며 사용 중입니다.
해당 기능들이 다운로드 되는 모든 이미지 파일에 해당되는 옵션인지 궁금하며,
맞다면, 사이트 마다 개별 설정은 불가한지 여쭤봅니다...

또, GIF 움짤로 댓글달때, 용량 초과 때문에 못다는 일이 발생하곤 하는데,,, 
혹시 다운 받은 GIF파일의 화질을 낮추는 기능은 가능한지 여쭤봅니당..

**Comment by KurtBestor** [comment]
1. 로그인 기능은 천천히 구현할게요.
2. 모든 사이트에 동일하게 적용되고, 개별 설정은 불가능해요.
3. GIF가 오래된 포맷이기도 하고, 압축하는 방법이 여러가지라서 현재는 구현하지 않을 계획이에요.
