### ISSUE TITLE
사이트 추가 건의 드립니다.

### ISSUE THREAD

**Issue by sigher89** [KurtBestor/Hitomi-Downloader-issues#771]
https://mana08.com/

마나79라는 사이트인데 마나모아보다 정리가 잘되있고, 업데이트도 빠르네요
주소는 mana01~08 순으로 바꾸는것 같은데, 거의 바뀌진 않네요.

**Comment by sigher89** [comment]
위 주소 메인은 광고가 좀 민망하네요..
https://mana08.com/board/webtoon/toonlist/sca/1
만화목록있는 게시판인데..  해당 URL로 확인해보시는게 좋을 것 같습니다.

**Comment by KurtBestor** [comment]
내부적으로 지원하는 사이트 (Manamoa, Jmana) 와 스크립트에서 지원하는 사이트 (Adulti, HoduComics, Newtoki) 에서 없는 작품이 있나요?

**Comment by sigher89** [comment]
고생많으십니다.

일단 두사이트에서 없는 작품들이 있고 기존에 올라온 작품들에서 중간중간 비는 화나 깨지는 이미지들이 있는 반면에 모든 만화를 다 확인한것은 아니지만 대체로 다 떠있긴 합니다..
