### ISSUE TITLE
히토미 받은거 검색할수 있게 태그 기능이 가능할까요?

### ISSUE THREAD

**Issue by cul9** [KurtBestor/Hitomi-Downloader-issues#772]
원래 손크로로 다운받아서 분류하는데

다운로더가 넘 좋아서^^;; 작품수가 감당이 안되네요

검색할수 있도록 태그 기능 추가 해주실수 있을까요?
파일명에는 길어지니까 안되겠고

월별로 메모장 파일생성해서 제목 아티스트 그룹 태그 이렇게  만들면 어떨지요?

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/688, https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/454
