### ISSUE TITLE
히토미 애니 대신 이미지가 받아지는 갤러리가 있습니다. 

### ISSUE THREAD

**Issue by dcie** [KurtBestor/Hitomi-Downloader-issues#774]
https://hitomi.la/galleries/1116.html

https://hitomi.la/galleries/907.html

관리자님 위 2개 갤러리는 

검색기에서는 애니로 검색되지만 실제 다운받으면 이미지로 다운로드 됩니다.

버그인것 같아 신고해 봅니다. 

항상

감사합니다.

**Comment by KurtBestor** [comment]
애니메이션은 삭제되면 다운로드 못하는데 리스트에 들어갔네요. 앞으로 삭제된 데이터에서 애니메이션은 빠질거예요.
