### ISSUE TITLE
Abzome님 작품이 넘버링으로는 다운로드가되는데 검색이안됩니당..

### ISSUE THREAD

**Issue by zenkou123** [KurtBestor/Hitomi-Downloader-issues#777]
넘버로 다운로드한 파일정보에서도 artist Abzome님으로 표시되있는데 검색기에서만 안나옵니다.. 
기본이랑 삭제된 둘다해봤어요

**Comment by i20191243r3263754** [comment]
검색기 기본데이터 다운로드 하심?

**Comment by zenkou123** [comment]
당연히했죠 혹시나 데이터 꺠졋을까봐 기본 삭제된 둘다 3번씩다시받아봤는데도 안나와요

**Comment by KurtBestor** [comment]
해당 작품 번호나 제목이 어떻게 되나요?

**Comment by zenkou123** [comment]
제가 넘버알고있어서 받는데성공한작품은 1350705고 이게 시리즈물인데 전에 나머지시리즈도 있는걸 분명히봤엇는데 삭제되있어서 다운로더로 받으려고하니까 안되더라구요
전부 작가명 abzome에요

**Comment by KurtBestor** [comment]
히토미엔 Non-H 가 없어요. E(x)Hentai 에서 검색해주세요: https://e-hentai.org/?f_search=abzome

**Comment by zenkou123** [comment]
전에 히토미에 올라왔어서 나올줄 알았는데.. 논h로 삭제된건 아예 없나보네요 감사합니당
