### ISSUE TITLE
Anrakugai 그룹이 검색 안됩니다

### ISSUE THREAD

**Issue by wooeorbs** [KurtBestor/Hitomi-Downloader-issues#779]
https://exhentai.org/?f_search=Anrakugai
여기 보면 알겠지만 히토미 다운로더에는 검색이 안되네요
Non-h나 검색 안되는 카테고리 그런게 아닙니다. 그랬으면 익헨에 검색했습니다.
물론 익헨에 검색해서 주소를 뽑으면 되는데
히토미나 히요비에도 검색이 되는데 히토미 다운로더에만 안그러니 그렇습니다

**Comment by KurtBestor** [comment]
히토미나 히요비에서 검색 안 되네요.

**Comment by wooeorbs** [comment]
> 히토미나 히요비에서 검색 안 되네요.

http://la.hitmoe.com/-/group/anrakugai-all-1.html
https://hiyobi.me/search/group:anrakugai
검색이 됩니다!

**Comment by KurtBestor** [comment]
다 삭제된 데이터에 들어가 있네요.

참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/279#issuecomment-433671751
