### ISSUE TITLE
트위터 일부가 다운이 안됩니다

### ISSUE THREAD

**Issue by jaejunghan** [KurtBestor/Hitomi-Downloader-issues#781]
冥土黄泉 (@meido_yomi)

version: 2.6b
platform: Windows-10-10.0.17134
gal_num: https://twitter.com/meido_yomi
dir: hitomi_downloaded_twitter\冥土黄泉 (@meido_yomi)
zip: 
type: twitter
artist: None
url: https://twitter.com/meido_yomi
valid: True
done: True
range: None
range_p: None
single: False
time: 1556110543.46 (Apr 24)
tags: []
goodbyedpi: False
lock: False

[Gallery]
None

[File Names]

[URLs]

[Messages]
max_pos=None, imgs=0
can not load json: No JSON object could be decoded
can not load json: No JSON object could be decoded
can not load json: No JSON object could be decoded
can not load json: No JSON object could be decoded
can not load json: No JSON object could be decoded
can not load json: No JSON object could be decoded
can not load json: No JSON object could be decoded
can not load json: No JSON object could be decoded
can not load json: No JSON object could be decoded
can not load json: No JSON object could be decoded
can not load json: No JSON object could be decoded
can not load json: No JSON object could be decoded
can not load json: No JSON object could be decoded
can not load json: No JSON object could be decoded
can not load json: No JSON object could be decoded
can not load json: No JSON object could be decoded
can not load json: No JSON object could be decoded
can not load json: No JSON object could be decoded
can not load json: No JSON object could be decoded
can not load json: No JSON object could be decoded
can not load json: No JSON object could be decoded
can not load json: No JSON object could be decoded
can not load json: No JSON object could be decoded
can not load json: No JSON object could be decoded
can not load json: No JSON object could be decoded
can not load json: No JSON object could be decoded
can not load json: No JSON object could be decoded
can not load json: No JSON object could be decoded
can not load json: No JSON object could be decoded
can not load json: No JSON object could be decoded
can not load json: No JSON object could be decoded
can not load json: No JSON object could be decoded
can not load json: No JSON object could be decoded
can not load json: No JSON object could be decoded
can not load json: No JSON object could be decoded
can not load json: No JSON object could be decoded
can not load json: No JSON object could be decoded
can not load json: No JSON object could be decoded
can not load json: No JSON object could be decoded
can not load json: No JSON object could be decoded
can not load json: No JSON object could be decoded
can not load json: No JSON object could be decoded
can not load json: No JSON object could be decoded
can not load json: No JSON object could be decoded
can not load json: No JSON object could be decoded
can not load json: No JSON object could be decoded
can not load json: No JSON object could be decoded
can not load json: No JSON object could be decoded
can not load json: No JSON object could be decoded
can not load json: No JSON object could be decoded
can not load json: No JSON object could be decoded
can not load json: No JSON object could be decoded
can not load json: No JSON object could be decoded
can not load json: No JSON object could be decoded
can not load json: No JSON object could be decoded
can not load json: No JSON object could be decoded
can not load json: No JSON object could be decoded
can not load json: No JSON object could be decoded
can not load json: No JSON object could be decoded
can not load json: No JSON object could be decoded
can not load json: No JSON object could be decoded
can not load json: No JSON object could be decoded
can not load json: No JSON object could be decoded
can not load json: No JSON object could be decoded
can not load json: No JSON object could be decoded
can not load json: No JSON object could be decoded
can not load json: No JSON object could be decoded
can not load json: No JSON object could be decoded
can not load json: No JSON object could be decoded
can not load json: No JSON object could be decoded
can not load json: No JSON object could be decoded
can not load json: No JSON object could be decoded
can not load json: No JSON object could be decoded
can not load json: No JSON object could be decoded
can not load json: No JSON object could be decoded
can not load json: No JSON object could be decoded
can not load json: No JSON object could be decoded
can not load json: No JSON object could be decoded
can not load json: No JSON object could be decoded
can not load json: No JSON object could be decoded
can not load json: No JSON object could be decoded
can not load json: No JSON object could be decoded
can not load json: No JSON object could be decoded
can not load json: No JSON object could be decoded
can not load json: No JSON object could be decoded
can not load json: No JSON object could be decoded
can not load json: No JSON object could be decoded
can not load json: No JSON object could be decoded
can not load json: No JSON object could be decoded
can not load json: No JSON object could be decoded
can not load json: No JSON object could be decoded
can not load json: No JSON object could be decoded
can not load json: No JSON object could be decoded
can not load json: No JSON object could be decoded
can not load json: No JSON object could be decoded
can not load json: No JSON object could be decoded
can not load json: No JSON object could be decoded
can not load json: No JSON object could be decoded
can not load json: No JSON object could be decoded
can not load json: No JSON object could be decoded
can not load json: No JSON object could be decoded
can not load json: No JSON object could be decoded
can not load json: No JSON object could be decoded
can not load json: No JSON object could be decoded
can not load json: No JSON object could be decoded
can not load json: No JSON object could be decoded
can not load json: No JSON object could be decoded
can not load json: No JSON object could be decoded
can not load json: No JSON object could be decoded
can not load json: No JSON object could be decoded
can not load json: No JSON object could be decoded
can not load json: No JSON object could be decoded
can not load json: No JSON object could be decoded
can not load json: No JSON object could be decoded
can not load json: No JSON object could be decoded
can not load json: No JSON object could be decoded
can not load json: No JSON object could be decoded
can not load json: No JSON object could be decoded
can not load json: No JSON object could be decoded
can not load json: No JSON object could be decoded
can not load json: No JSON object could be decoded
can not load json: No JSON object could be decoded
can not load json: No JSON object could be decoded
can not load json: No JSON object could be decoded
can not load json: No JSON object could be decoded
can not load json: No JSON object could be decoded
can not load json: No JSON object could be decoded
can not load json: No JSON object could be decoded
done : https://twitter.com/meido_yomi

**Comment by jaejunghan** [comment]
사진이 0장으로 뜹니다

**Comment by KurtBestor** [comment]
비공개  계정은 지원하지 않아요.

**Comment by jaejunghan** [comment]
> 비공개 계정은 지원하지 않아요.

해당 계정은 비공개가 아닙니다, 트위터에 들어가면 해당계정의 미디어에 있는 이미지가 다뜹니다

**Comment by KurtBestor** [comment]
비공개 맞아요.
