### ISSUE TITLE
프로그램 1개를 돌리면 리스트에서 3개를 읽던데

### ISSUE THREAD

**Issue by jaejunghan** [KurtBestor/Hitomi-Downloader-issues#782]
n개를 돌리면 3n개를 읽나요? 아니면 몇개를 돌리던 프로그램 총합해서 3개만 읽는 건가요?

프로그램 4개를 동시에 돌리는데 스크룰 내리는것도 버거워 합니다

**Comment by jaejunghan** [comment]
6코어 렘16기가 입니다

**Comment by KurtBestor** [comment]
한 프로그램 당 4개를 읽어요.

프로그램 여러 개를 동시에 키는 건 권장하지 않아요.
