### ISSUE TITLE
기능 건의 입니다.

### ISSUE THREAD

**Issue by naninore** [KurtBestor/Hitomi-Downloader-issues#783]
정말 덕분에 너무 잘 사용하고 있습니다. 압도적으로 감사드리며 몇 가지 건의사항을 말씀드리고자 합니다.

1. 저장과 로드가 백단위로 넘어가니 느려집니다. 수정되지 않은 부분은 저장 및 로드에서 제외하고 이전버전을 유지하는 방향으로 부탁합니다.

2. 다운사이트별 분리를 할 수 있게 부탁드립니다. 소트 분류에 추가해주시거나 크롬처럼 탭을 분류할 수 있게 부탁드립니다.

3. 랜덤 오픈기능을 넣어주셨으면 합니다. 다운받은 파일 목록 중 랜덤으로 하나를 오픈하는 기능을 말하는 겁니다.

잘 부탁드립니다.

**Comment by KurtBestor** [comment]
사이트별 분리는 좌측 하단 `정렬 기준...` 이나 `도움말` - `사용법... (F1)` - `다운로더 목록 필터링` 을 참고해주세요.

나머지는 나중에 고려해볼게요.
