### ISSUE TITLE
플로팅 미리보기가 뭔가요?

### ISSUE THREAD

**Issue by karnies** [KurtBestor/Hitomi-Downloader-issues#785]
질문 올려도 되나요?

설정에 플로팅 미리보기 크기설정이 있는데, 이게 뭐에요??

**Comment by KurtBestor** [comment]
![image](https://user-images.githubusercontent.com/14768120/56707486-09276000-6754-11e9-832c-803ca3d9734a.png)

위와 같이 썸네일에 마우스 커서 올리면 뜨는 미리보기예요.
