### ISSUE TITLE
마나모아 다운로드 관련 오류 문의 드립니다.

### ISSUE THREAD

**Issue by bhkim0115** [KurtBestor/Hitomi-Downloader-issues#786]
https://manamoa.net/bbs/page.php?hid=manga_detail&manga_name=고양이 절의 치온 씨

상기 주소와 같이 주소에 뛰어쓰기가 들어가 있는경우 첨부한 사진과 같이 오류가 나면서
정상적으로 다운로드가 진행되지 않습니다. 

![제목 없음-2](https://user-images.githubusercontent.com/49972127/56712106-3f6eda80-6768-11e9-836a-84d436642215.jpg)

**Comment by KurtBestor** [comment]
주소 복사할 때 어떤 브라우저 쓰시나요?

**Comment by bhkim0115** [comment]
익스플로어를 사용합니다...

**Comment by KurtBestor** [comment]
익스플로러에서도 되게 바꿨어요. 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview
