### ISSUE TITLE
히토미 다운 관련 질문이 있습니다

### ISSUE THREAD

**Issue by iaray3112** [KurtBestor/Hitomi-Downloader-issues#787]
다운로더로 히토미의 Game CG를 받으려고 했는데
[읽는 중]이 끝나 다운이 시작되니 이헨에서 받아지는거더라구요(마크가 히토미의 h에서 eh로 바뀜)
그래서 어느정도 다운 받아지다가 프로그램 사용으로 일정시간 ip밴을 당하네요
재시도 해보면 invalid 뜨면서 다운 실패가 되구요 
이럴 때는 어떻게 해야하나요?

**Comment by KurtBestor** [comment]
해당 작업 `마우스 우클릭` - `정보... (I)` 눌러서 나온 내용 보여주세요.
