### ISSUE TITLE
소설가가 되자 파일 다운로드 오류 관련 문의드립니다

### ISSUE THREAD

**Issue by homagood** [KurtBestor/Hitomi-Downloader-issues#788]
개별 다운로드까지는 되는데 통합본으로 만드는 단계에서 주황색으로 바뀌고 진행이 안 됩니다.
다른 소설은 다 잘 되는데 유독 이 소설만 안 되네요. 파일의 양이나 뭐 그런 문제도 아닌 것 같은데...
아래는 해당 파일의 정보입니다. 맨 아래에 오류 정보가 있습니다

[YU-Ri] 雪音ちゃんの異世界転生 〜私、転生したら吸血鬼になっちゃった！？相手の血を飲んだら相手の能力がコピーできる！？私がお願いしたのは想像を現実化する魔法なんだけど！？〜(仮)

version: 2.6b
platform: Windows-10-10.0.16299
gal_num: https://ncode.syosetu.com/n4824ev/
dir: hitomi_downloaded_syosetu\[YU-Ri] 雪音ちゃんの異世界転生 〜私、転生したら吸血鬼になっちゃった！？相手の血を飲んだら相手の能力がコピーできる！？私がお願いしたのは想像を現実化する魔法なんだけど！？〜(仮)
zip: 
type: syosetu
artist: None
url: https://ncode.syosetu.com/n4824ev/
valid: False
done: True
range: None
range_p: None
single: False
time: 1556202536.98 (Apr 25)
tags: []
goodbyedpi: True
lock: False

[Gallery]
None

[File Names]

[파일 목록. 길어서 생략했습니다]

[URLs]

[파일 목록. 길어서 생략했습니다]

get_session
single: False
Traceback (most recent call last):
File "utils", line 646, in start_
File "syosetu_downloader", line 113, in post_processing
IOError: [Errno 2] No such file or directory: u'hitomi_downloaded_syosetu\\[YU-Ri] \u96ea\u97f3\u3061\u3083\u3093\u306e\u7570\u4e16\u754c\u8ee2\u751f \u301c\u79c1\u3001\u8ee2\u751f\u3057\u305f\u3089\u5438\u8840\u9b3c\u306b\u306a\u3063\u3061\u3083\u3063\u305f\uff01\uff1f\u76f8\u624b\u306e\u8840\u3092\u98f2\u3093\u3060\u3089\u76f8\u624b\u306e\u80fd\u529b\u304c\u30b3\u30d4\u30fc\u3067\u304d\u308b\uff01\uff1f\u79c1\u304c\u304a\u9858\u3044\u3057\u305f\u306e\u306f\u60f3\u50cf\u3092\u73fe\u5b9f\u5316\u3059\u308b\u9b54\u6cd5\u306a\u3093\u3060\u3051\u3069\uff01\uff1f\u301c(\u4eee)\\[merged] [YU-Ri] \u96ea\u97f3\u3061\u3083\u3093\u306e\u7570\u4e16\u754c\u8ee2\u751f \u301c\u79c1\u3001\u8ee2\u751f\u3057\u305f\u3089\u5438\u8840\u9b3c\u306b\u306a\u3063\u3061\u3083\u3063\u305f\uff01\uff1f\u76f8\u624b\u306e\u8840\u3092\u98f2\u3093\u3060\u3089\u76f8\u624b\u306e\u80fd\u529b\u304c\u30b3\u30d4\u30fc\u3067\u304d\u308b\uff01\uff1f\u79c1\u304c\u304a\u9858\u3044\u3057\u305f\u306e\u306f\u60f3\u50cf\u3092\u73fe\u5b9f\u5316\u3059\u308b\u9b54\u6cd5\u306a\u3093\u3060\u3051\u3069\uff01\uff1f\u301c(\u4eee).txt'

done : https://ncode.syosetu.com/n4824ev/

**Comment by homagood** [comment]
혹시 도움이 될까 싶어 해당 소설 사이트도 적습니다.
https://ncode.syosetu.com/n4824ev/

**Comment by KurtBestor** [comment]
제목이 너무 길어서 발생하는 문제인데, 적당히 자르도록 했어요.
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by homagood** [comment]
잘 되네요! 감사합니다
