### ISSUE TITLE
프로그램 작동이 중지됩니다.

### ISSUE THREAD

**Issue by smarthe** [KurtBestor/Hitomi-Downloader-issues#789]
![error](https://user-images.githubusercontent.com/49991546/56750478-d5355480-67be-11e9-8ac8-27407e67d84b.png)
프로그램 실행시 85% 구간에서 작동이 중지됩니다.
hitomi_downloader_GUI.ini 이 약 300mb정도 됩니다. 해당 파일을 지우면 될 것 같지만
프로그램에서 리스트를 보는게 편하기 때문에 제거하고 싶지 않습니다
다른 방법이 있을까요?

**Comment by KurtBestor** [comment]
hitomi_downloader_GUI.ini 파일 보내주시면 HDT 파일로 분할해서 보내드릴게요.

900개 이상은 권장하지 않아요. 참고해주세요: #170

**Comment by smarthe** [comment]
알려주셔서 감사합니다, ini 파일 제거하니 실행이 됩니다, HDT 파일로 분활해서 주시는건 말씀만으로 감사합니다.
