### ISSUE TITLE
히토미에서 다운로드 받은 후에 태그가 txt 파일로 따로 저장됐으면 좋겠네요

### ISSUE THREAD

**Issue by bhidulgi** [KurtBestor/Hitomi-Downloader-issues#79]
hitomi roller 쓸 때 있던 기능인데 이런 기능도 있었으면 좋겠네욤

**Comment by KurtBestor** [comment]
어떤 용도로 필요한가요?

**Comment by bhidulgi** [comment]
태그 검색해서 보고 싶을때 쓰려구요 ㅎㅎ;

**Comment by KurtBestor** [comment]
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

해당 기능 추가했습니다. 테스트 부탁드려요.
