### ISSUE TITLE
니코동 영상이 고화질로 다운이 안되네요

### ISSUE THREAD

**Issue by Matosan** [KurtBestor/Hitomi-Downloader-issues#793]
이코노미 시간대가 있어서 저화질로 다운받아지는건 아는데
프로그램에 옵션 -> 니코동 들어가면 사용자의 니코동 계정이 입력되는것이 있는데
만약에 사용자 계정이 프리미엄이면 다운받을때 프리미엄이 적용되어서
고화질로 받아지는것이 아닌지 여쭤보고싶습니다.
프리미엄을 결제후에 했는데도 여전히 저화질로 받아지기집니다.

**Comment by KurtBestor** [comment]
제가 지금 계정이 없어서 테스트해볼 수 없는데 혹시 계정 테스트용으로 제공해주실 분 계시면 연락해주세요.

**Comment by Matosan** [comment]
> 제가 지금 계정이 없어서 테스트해볼 수 없는데 혹시 계정 테스트용으로 제공해주실 분 계시면 연락해주세요.

이메일 적어주시면 그쪽으로 보내드릴께요

**Comment by KurtBestor** [comment]
admin@kurtbestor.net

**Comment by KurtBestor** [comment]
mangrovn@gmail.com

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by Matosan** [comment]
> 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

5월8일 23시27분 테스트 진행했고 이코노미 계정으로 고화질로 시청하기위해서는 익일 02시부터 가능 한데 지금 테스트 해보니 정상적으로 고화질로 다운로드되는 걸 확인했습니다. 니코동 계정은 처음 프로그램 실행하고 옵션에들어가서 계정을 입력하고 프로그램을 저장 & 종료를 하고 다시 프로그램을 실행해서 다운로드 했습니다.
