### ISSUE TITLE
트위터 플텍은 절대 다운로드 못하나요?

### ISSUE THREAD

**Issue by knife9707** [KurtBestor/Hitomi-Downloader-issues#798]
자물쇠 걸린 계정은 서로 팔로우중이라 트위터에서 보는건 가능한데 다운로드가 안되네요ㅠㅠ
픽시브처럼 로그인한다거나..트위터api? 같은걸로는 불가능할까요 ?

**Comment by open-mindt** [comment]
저도 건의 했던 내용인데.. 개발자분께서 개발해 주시리라 믿고 기다리고 있습니다.

급하시면 크롬 확장으로 우선 받아놓으세요.. 
전체 받기, 원하는 것만 받기, 일정기간 받기 다 됩니다.

https://chrome.google.com/webstore/detail/twitter-media-downloader/cblpjenafgeohmnjknfhpdbdljfkndig

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/754
