### ISSUE TITLE
이미지 set 다운받을때 동일 파일명이면 덮어씌우기가 되는 현상

### ISSUE THREAD

**Issue by zmgkgp** [KurtBestor/Hitomi-Downloader-issues#80]
https://exhentai.org/g/1205874/50f9a9cd06/

위 주소 다운로드를 하면 원래 159개의 이미지가 다운로드 되어야 하지만 약 41개만 다운로드가 됩니다.

확인해보니 파일네임이 01_.jpg 이런식이여서 중복처리가 안되는것같아요

이름이 겹쳐도 01_ (1).jpg 이런식으로 다운로드 되게 구현해주시면 정말 감사하겠습니다 ㅠㅠ

**Comment by KurtBestor** [comment]
![newcanvas1a](https://user-images.githubusercontent.com/14768120/38763854-5a45576e-3fdf-11e8-89d0-f0c21a0f03c3.png)

위와 같이 설정해주세요.

**Comment by zmgkgp** [comment]
감사합니다!!!
