### ISSUE TITLE
DPI 우회가 안됩니다.

### ISSUE THREAD

**Issue by karnies** [KurtBestor/Hitomi-Downloader-issues#800]
![image](https://user-images.githubusercontent.com/46523031/57007159-84d84f80-6c21-11e9-826e-d4a2f1b7edaf.png)

이렇게 뜨면서 안되네요.
재부팅 해도 안되요 ㅠㅠ 2.6b입니다.

**Comment by KurtBestor** [comment]
다음 링크에서 `goodbyedpi-0.1.5.zip` 다운로드해서 압축 풀고:
https://github.com/ValdikSS/GoodbyeDPI/releases/tag/0.1.5

32bit OS는 `x86/goodbyedpi.exe`, 64bit OS는 `x86_64/goodbyedpi.exe` 실행시켜서 어떻게 나오는지 보여주세요.
