### ISSUE TITLE
Loading screen

### ISSUE THREAD

**Issue by 201501001ValentinoRP** [KurtBestor/Hitomi-Downloader-issues#801]
this list is successful, some are still pending (4 hours without results), and errors (invalid). how to handle it?
here is the picture.
thank you developer for make this software.
![nf 2](https://user-images.githubusercontent.com/37302914/57023461-4f9d2300-6c5c-11e9-8e4d-010870bc7c34.png)
![nf](https://user-images.githubusercontent.com/37302914/57023462-4f9d2300-6c5c-11e9-86f3-2bdc4f9fecf4.png)

**Comment by KurtBestor** [comment]
Please use the test version:
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

If it's still broken, please tell me.

**Comment by 201501001ValentinoRP** [comment]
Thank you for your answer. I hope best for your success.

Sent from Mail for Windows 10

**Comment by 201501001ValentinoRP** [comment]
Hello Dev, can I suggest you to add this link to your software?
http://hgamecg.com/
Thank you for your advances.

Sent from Mail for Windows 10

**Comment by KurtBestor** [comment]
Please see: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/744
