### ISSUE TITLE
니코동 다운로드 문제

### ISSUE THREAD

**Issue by highbee123** [KurtBestor/Hitomi-Downloader-issues#805]
니코동 유로채널 영상을 다운로드 하고 싶은데 설정에서 로그인 입력해도 다운로드가 안됩니다.
기능 추가가 안된건지 오류가 있는건지 궁금합니다

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/793
