### ISSUE TITLE
Jmana  사이트가 업데이트 이후에도 다운이 안되네요.

### ISSUE THREAD

**Issue by dlfmaqmf** [KurtBestor/Hitomi-Downloader-issues#808]
Invalid : [jmana] https://jmana17.com / book / %EC%9A%B8%EB%B3%B4%20%EA%B2%81%EC%9F%81%EC%9D%B4%20%EC%A0%9C%EA%B0%88%EA%B3%B5%EB%AA%85

version: 2.6b
platform: Windows-10-10.0.17763
gal_num: https://jmana17.com/book/%EC%9A%B8%EB%B3%B4%20%EA%B2%81%EC%9F%81%EC%9D%B4%20%EC%A0%9C%EA%B0%88%EA%B3%B5%EB%AA%85
dir: 
zip: 
type: jmana
artist: None
url: https://jmana17.com/book/%EC%9A%B8%EB%B3%B4%20%EA%B2%81%EC%9F%81%EC%9D%B4%20%EC%A0%9C%EA%B0%88%EA%B3%B5%EB%AA%85
valid: False
done: False
range: None
range_p: None
single: False
time: 1556935707.83 (May 4)
tags: []
goodbyedpi: True
lock: False

[Gallery]
None

[File Names]

[URLs]

[Messages]
'NoneType' object has no attribute 'findAll'
stop
Traceback (most recent call last):
File "utils", line 507, in start
File "utils", line 551, in start_
File "jmana_downloader", line 68, in read
File "jmana_downloader", line 62, in name
File "jmana_downloader", line 85, in get_title
AttributeError: 'NoneType' object has no attribute 'findAll'

Fail: jmana

done : https://jmana17.com/book/%EC%9A%B8%EB%B3%B4%20%EA%B2%81%EC%9F%81%EC%9D%B4%20%EC%A0%9C%EA%B0%88%EA%B3%B5%EB%AA%85

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by dlfmaqmf** [comment]
일단 다운은 되는데 몇개 받은 뒤에꺼는 다시 인식이 안되는 경우가 있는거 같아요.
