### ISSUE TITLE
뉴토끼 작품중 몇몇 에러가 생깁니다. 

### ISSUE THREAD

**Issue by kamogun** [KurtBestor/Hitomi-Downloader-issues#809]
예를 들어

https://newtoki12.net/comic/109651

다운로드 하면

로그 보면

마지막 50화가 에러 생기네요.

다름 작품도 몇몇개는 에러가 생겨서 완료가 안되네요.

**Comment by KurtBestor** [comment]
사이트에서 직접 봐도 에러 뜨네요.
