### ISSUE TITLE
이제 검색기에서 언어선택 못하나요?

### ISSUE THREAD

**Issue by zmgkgp** [KurtBestor/Hitomi-Downloader-issues#81]
![default](https://user-images.githubusercontent.com/38368912/38763806-6bc1980a-3fde-11e8-97be-5d860c4933ce.png)

원래 제 기억에 검색기에서 한국어 선택이 가능했던거로 기억하는데 어느순간 업데이트 하니까 사라졌더라고요 ㅜㅜ 만들어주시면 정말 감사하겠습니다...

**Comment by KurtBestor** [comment]
1. 검색어에 korean 입력하시거나
2. 오른쪽 위에 분홍색 돋보기 아이콘 눌러서 고급 검색으로 바꾸세요

**Comment by zmgkgp** [comment]
감사합니다!!!
