### ISSUE TITLE
스레드수가 32를 넘어가면 느려지다가 멈춰버립니다.

### ISSUE THREAD

**Issue by GNEELS** [KurtBestor/Hitomi-Downloader-issues#811]
좋은 프로그램 감사합니다. 꾸벅

16분할까지는 잘 다운로드되지만 32분할하면 5분쯤 다운받다가 멈춰버립니다. 노트북에서도 확인해보니 마찬가지였는데 노트북과 데스크탑에서 동시에 실행해서 각자 16분할로 다운로드를 시작하면 한쪽이 멈춰버리고 다른쪽도 오래가지 않아 멈춰버립니다.

공인 ip를 몇번 바꿔줘도 동일한 증상이 발생하며 프로그램을 실행하고 16분할로 다운받을때도 처음 몇분간은 기세좋게 5mb/s씩도 속도가 나와주다가 차츰 느려지면서 0.1mb/s까지도 느려졌다가 2mb/s까지 올랐다 내리기를 반복합니다. 16분할로 받다가 느려졌을때 분할수를 32로 늘려줘도 속도가 늘어나지는 않고 16분할과 동일하게 유지되다가 오히려 멈춰버리기도 합니다. 얼마전에 최신버전으로 업데이트하기전부터도 그랬습니다.

히요비 떄문에 느려진 이후로 원래 속도가 이렇게 나오는건가요, 아니면 히토미에서 차단이 되는걸까요, 아니면 이용자수가 많아지면서 사이트가 버벅이는걸까요? 지인에게 확인을 부탁하거나 공공장소에서 사이트에 접속해볼 배짱이 없어서 다른곳에서 해보지는 못했지만 저만 발생하는 증상인가요?

**Comment by KurtBestor** [comment]
`Shift + Esc` 누르면 작동하는 스레드 갯수 확인할 수 있어요.
히토미의 경우에 스레드를 16개 넘게 해도 동일해요.

같은 네트워크에서 프로그램 두개 동시에 실행하려면 스레드 수를 8개씩으로 맞춰야해요.
