### ISSUE TITLE
오늘 아침부터 마나모아가 다운이 안됩니다.

### ISSUE THREAD

**Issue by pitchlatte** [KurtBestor/Hitomi-Downloader-issues#813]
히토미 버전은 2.6b 최신버전입니다.

아침부터 한참 읽는중으로 뜨다가 에러나면서 파일을 못가져옵니다.

확인 부탁드립니다.

**Comment by sternenlichtkinder** [comment]
version: 2.6b
platform: Windows-10-10.0.17134
gal_num: https://manamoa3.net/bbs/page.php?hid=manga_detail&manga_id=4291
dir: 
zip: 
type: manamoa
artist: None
url: https://manamoa3.net/bbs/page.php?hid=manga_detail&manga_id=4291
valid: True
done: False
range: None
range_p: None
single: False
time: 1557027533.31 (May 5)
tags: []
goodbyedpi: True
lock: False


[Gallery]
None


[File Names]



[URLs]



[Messages]
Cloudflare protection
Cloudflare protection
Cloudflare protection

메시지 상으로는 클라우드플레어에 계속 막히는거 같습니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by pitchlatte** [comment]
> 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

테스트 완료했습니다. 잘 됩니다. 감사합니다!

**Comment by sternenlichtkinder** [comment]
현재 다운로드 가능합니다만, 마나모아 자체에서 Cloudflare가 동작하고 있지 않습니다. 테스트버전이 아닌 릴리즈 버전으로 실행해도 다운로드가 가능하네요.
