### ISSUE TITLE
익헨 원본 다운로드에 대하여

### ISSUE THREAD

**Issue by Rounlet** [KurtBestor/Hitomi-Downloader-issues#817]
다른 이슈에서 익헨 다운로드는 리샘플링된 자료만 다운로드 받는다고 본 적이 있는데,

전 그게 일반 이헨 계정에서만 해당되는 줄 알고 도네이션 후 원본으로 보는 기능을 열었습니다.

흠.. 그래도 여전히 리샘플링된 자료만 받더라구요. 제가 이해한 메커니즘이 틀렸나봅니다.

원본으로 익헨을 다운로드 받는 방법이 있나요?

**Comment by KurtBestor** [comment]
로그인 기능이 없어서 현재는 불가능해요.

**Comment by KurtBestor** [comment]
@VanTuz5 @bloodza @nikin78 

다음과 같이 쿠키 불러와서 로그인 할 수 있어요:
- `옵션` - `설정...` - `고급 설정` - `쿠키` - `불러오기...`

사이트에서 보이는 이미지 크기대로 다운로드해요.

[여기](https://e-hentai.org/uconfig.php)에서 다음과 같이 설정하면 원본 이미지를 다운로드해요:
![image](https://user-images.githubusercontent.com/14768120/74756731-6169b880-52b8-11ea-8af3-f0f42c0cc814.png)

테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by Rounlet** [comment]
@KurtBestor 

![주석 2020-02-25 185544](https://user-images.githubusercontent.com/47098778/75235975-74bcdc80-5800-11ea-9817-8f67796f9d85.png)

이헨일 경우 잘 적용되서 진행됩니다만 익헨의 경우는 안 되더군요.

아 그리고 속도 문제도 있어요. 

일부러 그랩 간격 때문에 설정해놓으신 건가요?

**Comment by KurtBestor** [comment]
안 되는 작업 정보 보여주세요.

속도가 더 느려졌나요? 어떻게 바뀌었나요?

**Comment by Rounlet** [comment]
익헨은 다시 해보니까 되네요.. 아까랑 똑같은 과정이었는데 이상하네..

속도 문제 같은 경우는

![주석 2020-02-25 214404](https://user-images.githubusercontent.com/47098778/75248748-1996e400-5818-11ea-9a31-7a45e7a57436.png)
![주석 2020-02-25 214422](https://user-images.githubusercontent.com/47098778/75248752-1b60a780-5818-11ea-867f-a0eb5b0cb8a3.png)

한 이미지 다운로드가 끝나면 속도가 0으로 수렴했다가 
그 다음 이미지에서 다시 100~200 정도로 다운로드 받아요.

픽시브같은 경우는 안정적으로

![주석 2020-02-25 214717](https://user-images.githubusercontent.com/47098778/75248892-6aa6d800-5818-11ea-8272-fb94b547218a.png)

이 정도 속도가 나오는데 반해서 상대적으로 느리다고 느껴지네요.

**Comment by KurtBestor** [comment]
Pixiv는 16 장씩 동시에 받는데, E(x)Hentai는 1 장씩 받아서 (+ 페이지 로딩 시간) 그래요.

예전엔 여러 장 동시에 받았는데 가끔씩 제대로 안 받아지는 문제가 있어서 1 장으로 바뀌었어요.

**Comment by nikin78** [comment]
로그인 기능이 드디어 추가되었나 보군요. 다만 테스트 버전 주신 걸 다운 받으려니 윈도우에서 다음과 같은 트로이목마가 발견되었다고 다운로드가 안 되네요;;
Trojan:Win32/Detplock

**Comment by KurtBestor** [comment]
오진이라고 답변 받았어요:
![image](https://user-images.githubusercontent.com/14768120/75522666-de7df600-5a4d-11ea-9389-22f90aaa9263.png)

네, GP 소모해서 아카이브 다운로드 하는 건 사이트에서 직접 할 수 있으니까요.
