### ISSUE TITLE
픽시브 다운이 2000p까지만 됩니다

### ISSUE THREAD

**Issue by idroto** [KurtBestor/Hitomi-Downloader-issues#820]
예를들어 특정 캐릭터로 키워드 검색을 했을때 2천장이 넘어갈 경우

2천장 까지만 다운이 되고 뒤에 자료들은 다운이 안됩니다

한번에 2천장씩만 되는거 같은데 이것도 한계를 늘릴 수 없을까요?

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/382#issuecomment-450846793

**Comment by idroto** [comment]
잘되네요 감사합니다!!
