### ISSUE TITLE
간혹 검색기에서 제대로 검색이 안되는 작품이 있습니다.

### ISSUE THREAD

**Issue by myayusyo** [KurtBestor/Hitomi-Downloader-issues#822]
https://hitomi.la/galleries/1259515.html

이 작품의 경우 첨엔 그룹:N/A 등록됐지만, 이후에 그룹:Ankake Cha-Han 으로 수정되었는데,

검색기에서는 아직도 N/A 그룹으로 등록되어 검색이 되지 않습니다.

이외에도 간혹 한둘 씩 검색기에서 수정이 안되서 검색이 안되는 경우를 본 기억이 있어서 버그인가 하고 글 남깁니다.

**Comment by KurtBestor** [comment]
이제 제대로 검색 될거예요. `기본 데이터 다운로드...` 눌러서 데이터 업데이트 해주세요.
