### ISSUE TITLE
히토미 anime 다운이 안됩니다

### ISSUE THREAD

**Issue by eins11** [KurtBestor/Hitomi-Downloader-issues#824]
다운로드 창에 주황색으로 되면서 다운로드가 안되요

**Comment by KurtBestor** [comment]
해당 작업 `마우스 우클릭` - `정보... (I)` 눌러서 나온 내용 보여주세요.

**Comment by eins11** [comment]
Aikagi 1 (5103)

version: 2.6b
platform: Windows-7-6.1.7601-SP1
gal_num: [N/A] Aikagi 1 (5103)
dir: hitomi_downloaded
zip: 
type: hitomi
artist: None
url: https://hitomi.la/galleries/5103.html
valid: False
done: True
range: None
range_p: None
single: True
time: 1557467897.96 (May 10)
tags: []
goodbyedpi: False
lock: False


[Gallery]
갤러리 넘버: 5103

제목: Aikagi 1

작가: N/A

그룹: N/A

타입: anime

시리즈: N/A

캐릭터: N/A

태그: mosaic censorship, female:big breasts, female:blowjob, female:cosplaying, female:defloration, female:nakadashi, female:nurse, female:schoolgirl, female:swimsuit

언어: English


[File Names]
[0001] hitomi_downloaded\Aikagi 1 (5103).mp4


[URLs]
[0001] https://streaming.hitomi.la/videos/aikagi-1.mp4


[Messages]
********************************
Gallery number : 5103
Number of Threads : 64
********************************
Size (https://aa.hitomi.la/galleries/5103/05.png): 154 status: 403
Size (https://la.hitomi.la/galleries/5103/05.png): 0 status: None
Size (https://ba.hitomi.la/galleries/5103/05.png): 751268 status: 200
anime
get_title__
downloader_v3 fail... p[0 / 1]
Traceback (most recent call last):
File "downloader_v3", line 57, in run
Exception: Not partial content: 403

valid=False 1
done : #-*- [N/A] Aikagi 1 (5103)


file name이 빨간글씨로 되어있어요

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/763
