### ISSUE TITLE
마나모아 다운이 안되네요

### ISSUE THREAD

**Issue by Picstory** [KurtBestor/Hitomi-Downloader-issues#829]
테스트로 받아본 만화입니다.
주소를 넣으면 목록과 이미지수는 카운트 하는데 이미지는 다운로드 하지 못하고 주황색으로 변합니다.

version: 2.6b
platform: Windows-10-10.0.17763
gal_num: https://manamoa.net/bbs/page.php?hid=manga_detail&manga_id=10275
dir: hitomi_downloaded_manamoa\[히로타 신타로] 괴충의 여름
zip: 
type: manamoa
artist: 히로타 신타로
url: https://manamoa.net/bbs/page.php?hid=manga_detail&manga_id=10275
valid: False
done: True
range: None
range_p: None
single: False
time: 1557470546.67 (May 10)
tags: []
goodbyedpi: True
lock: False

[Gallery]
None

[Messages]
dirFormat: [artist] title
[seed] 괴충의 여름 전편 0
[seed] 괴충의 여름 후편 0

Fail : \\?\\\Mac\Home\Downloads\hitomi_downloader_GUI\hitomi_downloaded_manamoa\[히로타 신타로] 괴충의 여름\괴충의 여름 전편\0026.jpeg
Traceback (most recent call last):
File "downloader", line 674, in download
IOError: [Errno 22] invalid mode ('wb') or filename: u'\\\\?\\\\\\Mac\\Home\\Downloads\\hitomi_downloader_GUI\\hitomi_downloaded_manamoa\\[\ud788\ub85c\ud0c0 \uc2e0\ud0c0\ub85c] \uad34\ucda9\uc758 \uc5ec\ub984\\\uad34\ucda9\uc758 \uc5ec\ub984 \uc804\ud3b8\\0026.jpeg'

**Comment by KurtBestor** [comment]
`[File Names]` 와 `[URLs]` 가 어떻게 되어있나요?
