### ISSUE TITLE
인스타 다운이 안되네요

### ISSUE THREAD

**Issue by BloodSim** [KurtBestor/Hitomi-Downloader-issues#83]
작업정보내용 복사했습니다

Reading error: insta_official_lvlz8_

gal_num: insta_official_lvlz8_
dir: 
zip: 
type: insta
artist: Lovelyz 공식 인스타그램입니다,
url: https://www.instagram.com/official_lvlz8_
valid: False
done: False
range: None
range_p: None

[File Names]

[URLs]

[Messages]
Traceback (most recent call last):
File "hitomi_downloader", line 1031, in download_instagram
File "insta_downloader", line 115, in get_nodes
Exception: can not download json! None

Fail: insta

done : insta_official_lvlz8_

**Comment by KurtBestor** [comment]
인스타그램에서 내부 데이터 구조를 바꿨네요.
그리고 API limit도 시간당 5000번에서 200번으로 줄였구요.
참고: https://techcrunch.com/2018/04/02/instagram-api-limit/

덕분에 다른 여러 앱들도 제대로 작동을 안하는 상태입니다.
앞으로 더 힘들어질 듯 하네요.

일단 고쳐보려고 시도 중입니다.

**Comment by BloodSim** [comment]
그래서그런거였군요..

고생많으십니다^^

**Comment by KurtBestor** [comment]
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

고쳤습니다. 테스트 부탁드려요.
