### ISSUE TITLE
크롤러 관련 문의

### ISSUE THREAD

**Issue by kikinet88** [KurtBestor/Hitomi-Downloader-issues#830]
지금 크롤러 서버가
일정 기간? 되면 꺼지더군요
그냥 무한으로 돌릴수 없을까요..
이거 가끔 꺼진거 까먹고 안키면... ㅡㅡ;;
사실 귀찬...
요즘 서버 접속을 잘 안하는 편이라..

**Comment by KurtBestor** [comment]
메일 주세요
