### ISSUE TITLE
offline 이라고 뜨면서 다운이 되지 않습니다

### ISSUE THREAD

**Issue by jaejunghan** [KurtBestor/Hitomi-Downloader-issues#832]
지금 이렇게 github에 쓰고있는것도 인터넷 되니까 쓸수 있는건데

![githun](https://user-images.githubusercontent.com/41049446/57559808-a58d6b80-73be-11e9-8926-c5da96feb1c9.PNG)
이러면서 그이후로 넘어가질 않습니다

**Comment by jaejunghan** [comment]
계속 대기중이고 이후로 되지 않습니다 하드 디스크의 문제는 아닌거 같습니다 다른 외장하드에 시도해도 4개의 목록만 실행하고 이후 되지 않습니다

**Comment by jaejunghan** [comment]
이후 저장 종료후 다시키면 위에 대기중인 4목록 진행후 다시 대기중인 목록은 읽지 않습니다

**Comment by jaejunghan** [comment]
혹시나 ip벤이거나 컴퓨터의 문제인줄 알고 포멧했는데도 계속저럽니다

**Comment by jaejunghan** [comment]
위에사진에는 픽시브만 저렇게 나와있는데 트위터에도 마찬가지로 4개만 처리하고 작동하지 않습니다

그래서 포멧해도 ip변하지 않길레 vpn켯더니 offline이 꺼지고 픽시브와 트위터가 정상적으로 다운됩니다 ..

**Comment by jaejunghan** [comment]
vpn없이 사용할수 없을까요? 4개만 처러하고 계속 대기중인게 너무 불편합니다

**Comment by KurtBestor** [comment]
다음 테스트 버전으로 덮어씌우고 실행시켜서 `Ctrl+L` 눌러서 나오는 내용 알려주세요:
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by jaejunghan** [comment]
아예 아이피를 바꿔서 변한아이피로 불편한점 올립니다  트위터는 동시에 4개가되는데 픽시브는 4개의 동시목록이 작동하고 4개중에 하나라도 완료가 안되면 될때까지 대기타다가 4개완료되면 다음 4개의 작업을 합니다.

Checking for updates... HitomiDownloader
Checking for updates... version_check.txt

귩돂뤝얜퇂솬뒯퐬뛓킔졌받멼쾶묃냦쳳띫요롊퍊렡똄튳컠깨뙚렬켃쀻훻셜닦팭띍숆턃놑앪긟랪쉆쉝볶촒됵햔럯탤젚팩쯔쨐멃쌛쵼쒉뮚꽊궈쌯국궽쩠됪졧쨽쪆뀧퇇풓퇱엩쉊뽚첾쒰숧웏읧릠텡믎큨챽뭃옦눦쀦굛

4.8.6 / 4.11.2 / 4.16.3
Font: Gulim -> 맑은 고딕
Supported Image Formats: ['bmp', 'pbm', 'pgm', 'png', 'ppm', 'xbm', 'xpm']
v2.6b (latest : v2.6b)
Encodings: ['cp949', 'mbcs', 'ascii', 'utf-8', 'ascii']
GoodbyeDPI activated

Styles:
    Windows
    WindowsXP
    WindowsVista
    Motif
    CDE
    Plastique
    Cleanlooks

start GoodbyeDPI
Number of Threads : 4
