### ISSUE TITLE
마나모아 다운로드시 리사이징된 이미지로 받아집니다.

### ISSUE THREAD

**Issue by kin9834** [KurtBestor/Hitomi-Downloader-issues#834]
마루마루나 이전에는 원본 사이즈로 받아졌는데 얼마전부터 리사이징된 이미지(가로  622 etc)로 받아집니다.

**Comment by jinjins7** [comment]
설정/고급 에서 리사이징 옵션 걸려있는거 아닐까요

**Comment by KurtBestor** [comment]
해당 작업 `마우스 우클릭` - `정보... (I)` 눌러서 나온 내용 보여주세요.
