### ISSUE TITLE
제컴이 윈도우 10 64비트인데

### ISSUE THREAD

**Issue by jaejunghan** [KurtBestor/Hitomi-Downloader-issues#835]
32비트하고 차이가 있나요?

**Comment by jinjins7** [comment]
https://kin.naver.com/qna/detail.nhn?d1id=1&dirId=10301&docId=326436809&qb=MzLruYTtirggNjTruYTtirgg7LCo7J20&enc=utf8&section=kin&rank=2&search_sort=0&spq=0
이거 함 읽어보시면 될 것 같네요
