### ISSUE TITLE
저장할 시 자꾸 jpg로 저장이 되네요

### ISSUE THREAD

**Issue by jjmelo19** [KurtBestor/Hitomi-Downloader-issues#838]
다운로더는 감사하게 잘 이용하고 있습니다 근데 파일을 저장할때 jpg가 아닌 원본으로 저장할 수 있는 방법은 없을까요? 그리고 고급설정에 보면 화질 몇%라고 나와 있던데 이건 무슨 뜻인가요? 항상 수고하십니다 개발자님

**Comment by i20191243r3263754** [comment]
jpg가 원본이면 jpg로 저장 돼요. 화질은 %만큼의 화질로 낮춰서 파일 용량을 낮추는 거고요

**Comment by KurtBestor** [comment]
서버에 있는 이미지 원본 파일이 JPEG라서 `*.jpg` 로 받는 거예요.

JPEG를 PNG로 변환한다고 해서 화질이 좋아지진 않아요.
