### ISSUE TITLE
혹시 핀터레스트는 추가해주실 생각 없으신가용..?

### ISSUE THREAD

**Issue by bwcat2** [KurtBestor/Hitomi-Downloader-issues#84]
https://www.pinterest.co.kr/
히토미 다운로더를 자료수집용으로 활용하고있는 사람인데
자료가 굉장히 많은 핀터레스트 다운로드 기능을 추가 해주실수 없으신지 조심스레 건의 해봅니다..
보드를 일괄 다운로드하게 하면 좋을것같은데

**Comment by KurtBestor** [comment]
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

테스트 부탁드려요.

**Comment by bwcat2** [comment]
아이고 ㅠ 핀터레스트 업데이트가 되고 나서야 확인했네요. 죄송합니다. 사용법이 어떻게 되냐요?

**Comment by KurtBestor** [comment]
흠,, 그새 막혔네요.
나중에 시간 나면 고칠게요.

**Comment by bwcat2** [comment]
뉑

**Comment by KurtBestor** [comment]
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

테스트 부탁드려요.
