### ISSUE TITLE
네이버 웹툰에서 받아지지 않는 작품이 있습니다

### ISSUE THREAD

**Issue by metalbear13** [KurtBestor/Hitomi-Downloader-issues#840]
최근에 다운로더 잘 사용하고 있습니다 감사합니다

네이버웹툰에서 로그인 이후에 볼수 있는 작품이 받아지지 않는 것 같습니다

https://comic.naver.com/webtoon/list.nhn?titleId=670143&weekday=wed

Invalid : [navertoon] https://comic.naver.com / webtoon / list.nhn?titleId=670143&weekday=wed

version: 2.6b
platform: Windows-10-10.0.17763
gal_num: https://comic.naver.com/webtoon/list.nhn?titleId=670143&weekday=wed
dir: 
zip: 
type: navertoon
artist: None
url: https://comic.naver.com/webtoon/list.nhn?titleId=670143&weekday=wed
valid: False
done: False
range: None
range_p: None
single: True
time: 1557673403.87 (May 13)
tags: []
goodbyedpi: True
lock: False

[Gallery]
None

[File Names]

[URLs]

[Messages]
stop
Traceback (most recent call last):
File "utils", line 412, in __init__
File "navertoon_downloader", line 46, in init
File "constants", line 615, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 598, in wrapper
File "navertoon_downloader", line 118, in get_pages
AttributeError: 'NoneType' object has no attribute 'text'

Fail: navertoon

stop
done : https://comic.naver.com/webtoon/list.nhn?titleId=670143&weekday=wed

**Comment by i20191243r3263754** [comment]
로그인 기능이 없으니 로그인 이후에 볼 수 있는 건 당연히 다운이 안 될 껍니다. 크롬 확장 프로그램이나 다른 프로그램 이용하셔서 다운하시거나, 몇주 기다렸다가 다운하세요.

**Comment by KurtBestor** [comment]
19세 웹툰이라 로그인이 필요해요. 아직 로그인은 지원하지 않아요.
