### ISSUE TITLE
웹툰(호두코믹스,뉴토끼) 질문이요..

### ISSUE THREAD

**Issue by wksi22** [KurtBestor/Hitomi-Downloader-issues#841]
현재 호두코믹스랑 뉴토끼가 주소가 바껴서 스크립트사이트에 올라와있는 파일로 하면 안되는 상황입니다.
그래서 replace urls라는 스크립트까지 사용해봤지만 적용이 안되네요
궁금한게
기존 뉴토끼 스크립트에서 [0:9]는 newtoki9.com 사이트를 표현하는건가요??
그래서 다운로더 프로그램을 열고
1.스크립트 파일에 hodu.hds를 다운받아 열고
2.replace urls로 newtoki9.com->newtoki13.com
이렇게 바꾸는거 맞나요??ㅠ

**Comment by KurtBestor** [comment]
[0-9]* 는 [정규 표현식](https://ko.wikipedia.org/wiki/%EC%A0%95%EA%B7%9C_%ED%91%9C%ED%98%84%EC%8B%9D)이에요. 그냥 스크립트 파일만 넣으면 돼요.
다시 시도해서 안되면 해당 작업 `마우스 우클릭` - `정보... (I)` 눌러서 나온 내용 보여주세요.

**Comment by wksi22** [comment]
뉴토끼 다시 하니까 잘되네요..
