### ISSUE TITLE
프로그램의 속도를 빠르게 할수 없나요?

### ISSUE THREAD

**Issue by jaejunghan** [KurtBestor/Hitomi-Downloader-issues#842]
저희집 인터넷이 kt기가 인터넷이고 최소 500mbps를 넘습니다. 고용량을 다운받을때지만,,

히토미 다운로더로 픽시브와 트위터만 가져와서 짤긁고 있는데 하루에서 대략 4000개의 목록을 작업해야하다보니 불편한 점이 있어서 글을 올립니다,

밑에나오는 속도는 오늘 한번 다운받은 목록을 제다운 받았을때 나오는 속도입니다. 저에게 중요한건 파일 다운속도보단 읽는속도이기때문입니다.

프로그램을 돌릴때 작업관리자로 인터넷 속도를 보면 받는 속도가 대략 11mbps정도 됩니다.
개인적인 질문입니다만, 리스트에있는 작업목록들중 4개만 동시에 작업하는데 혹시 그수를 늘릴수 없나요? 늘렷을 경우 요구하는 인터넷 속도가 지금보다 증가할수 있나요?

또한 히토미 다운로더를 3개를 키면 동시에 작업하는 목록수는 12개여만 하는데 4개만 작업하는것 같습니다, 왜냐하면 속도가 3개를 키면 33mbps가 나와야 하지만 11mbps만 나오기 때문입니다. 

그래서 저의 요지는 프로그램을 돌릴떄 동시에 처리하는 목록수를 늘리며, 그로인해 요구 인터넷 속도가 커지길 바라는 바입니다.

혹여나 안된다면  이유좀 알려주시면 안되겠습니까? 나중에 제가 소스를 받아서 제껄로 만들고자 해서입니다

+)프로그램은 ssd에 두고, 저장 파일 위치는 외장hdd에 둘때와 프로그램도 역시 외장hdd에 둘때의 차이점이 있나요? 읽는속도라던가 다운속도라던가,,

**Comment by KurtBestor** [comment]
최대 4개만 동시에 다운로드하게 한 이유:
- 사람이 실제로 웹페이지를 보는 것과 비슷하게 해서 크롤링임을 숨기기 위해서
- 컴퓨터 자원을 아끼기 위해서
- OS의 스레드 갯수 제한
- 안정성

여러 개를 동시에 켜서 다운로드하는 건 권장하지 않아요.
하드디스크 속도는 보통 다운로드 속도보다 훨씬 빠르기 때문에, SSD/HDD 둘 다 그다지 차이는 없을 거예요.

**Comment by jaejunghan** [comment]
> * 
> * 안정성

크롤링을 숨기고자하는 이유는 ip벤때문인가요?
os의 스레드 갯수제한은 개인마다 다른가요?

**Comment by KurtBestor** [comment]
IP 밴도 있고, 계정 밴, Rate Limit 등 여러가지 있어요.
대부분의 사이트에 적용되어있어요.

스레드 갯수 제한은 OS의 스레드 스택 사이즈에 따라서 달라요.
