### ISSUE TITLE
히토미 404작품

### ISSUE THREAD

**Issue by a600640** [KurtBestor/Hitomi-Downloader-issues#843]
히토미 오늘 올라온 작품이 삭제되어서 404가 되었습니다 
삭제된데이터 갱신 가능 할까요?
작품:https://hitomi.la/galleries/1414506.html

**Comment by KurtBestor** [comment]
삭제된 데이터에는 히토미 서버나 히요비 서버에 이미지 파일이 남아있는 것만 들어가요.

**Comment by a600640** [comment]
삭제된 데이터를 다운받아도 안뜨면 없는거죠?

**Comment by KurtBestor** [comment]
갱신하는데 시간이 좀 걸리긴 하는데, 이 경우는 서버에서 이미지 파일이 아예 삭제돼서 나중에라도 추가가 되진 않을거예요.
대신 URL 이나 번호를 직접 입력해서 E(x)Hentai 에서 다운로드 할 수는 있어요.

**Comment by whgmlqja12** [comment]
저렇게 주로 삭제되는 대상은 주로 와니 매거진껀가 쾌락천, 실락천, 제로스였나 암튼 거기서 주로 활동하는 작가류께 대부분인데 대표적으로 메메나 호문쿨루스 같은 작가가튼게 걸러집니다. 익헨도 최근에야 그게 조금 풀려서 나오는 편인데 정 다운받고 싶으시다면 엔헨타이 가서 검색하시고 받으시면 됩니다. 엔헨도 다운로더가 지원하니까요.
