### ISSUE TITLE
소설가가되자 수정된 날짜도 반영되게 해주세요

### ISSUE THREAD

**Issue by a123qqb** [KurtBestor/Hitomi-Downloader-issues#845]
소설 받으면 안에 제목 우측에 날짜가 표시되는데
수정된 날짜는 표시가 안 되서 구분이 안 가네요
2016/04/10 09:46 （改）
이렇게 되어있고 저 （改）에 마우스 가져다대면
수정된 날짜가 표시 되는 형식인데
이게 텍스트에도 같이 저장되게 할 수는 없나요?

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by a123qqb** [comment]
와 너무 잘 되요 감사합니다 ㅎㅎ
