### ISSUE TITLE
백그라운드 프로세스 문제

### ISSUE THREAD

**Issue by jpdecade** [KurtBestor/Hitomi-Downloader-issues#847]
윈도우 10 사용중입니다.
관리자 권한으로 이용중인데 제대로 다운로더 종료를 했는데
컴퓨터 종료시 히토미 다운로더 때문에 걸리더군요.
작업 관리자에 보니 백그라운드에 다운로드를 종료해도 여전히 상주해 있는데
프로그램 종료를 하면 백그라운드 프로세스도 같이 종료할수는 없는건가요?

**Comment by KurtBestor** [comment]
종료되어야 정상인데, 작업관리자 스크린샷 찍어서 보여주실 수 있나요?

**Comment by jpdecade** [comment]
> 종료되어야 정상인데, 작업관리자 스크린샷 찍어서 보여주실 수 있나요?

![image](https://user-images.githubusercontent.com/49438209/57967219-158b8b00-7997-11e9-9d4e-3d4cb6cbc5b5.png)

이쪽에 덧글 다시 답니다.

확인 부탁드립니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by jpdecade** [comment]
동작에는 이상 없으며 종료시

저장&종료 -> 백그라운드 프로세스 종료됨.
종료 -> 여전히 백그라운드에 프로세스 생성됨.

종료시 차이인듯 싶습니다.
확인 부탁드립니다.


> 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by jpdecade** [comment]
테스트 이상없습니다.
프로세스 잘 죽네요 고생하셨습니다.
감사합니다.

> 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview
