### ISSUE TITLE
마나모아 다운이 안되네요

### ISSUE THREAD

**Issue by soulk123** [KurtBestor/Hitomi-Downloader-issues#848]
아까까지만 해도 잘 이용했는데 일어나서 만화 다운받으려니까 안되네요... 확인 한번만 해주세요

Invalid : [manamoa] https://manamoa3.net / bbs / board.php?bo_table=manga&wr_id=1108358

version: 2.6c
platform: Windows-10-10.0.17134
gal_num: https://manamoa3.net/bbs/board.php?bo_table=manga&wr_id=1108358
dir: 
zip: 
type: manamoa
artist: None
url: https://manamoa3.net/bbs/board.php?bo_table=manga&wr_id=1108358
valid: False
done: False
range: None
range_p: None
single: True
time: 1558088452.55 (May 17)
tags: []
goodbyedpi: False
lock: False

[Gallery]
None

[File Names]

[URLs]

[Messages]
Cloudflare protection
Cloudflare protection
Cloudflare protection
Cloudflare protection
stop
Traceback (most recent call last):
File "utils", line 412, in __init__
File "manamoa_downloader", line 80, in init
File "constants", line 616, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 599, in wrapper
File "manamoa_downloader", line 151, in get_soup
File "clf", line 56, in session
File "clf", line 48, in wait
Exception: Recaptcha

Fail: manamoa

stop
done : https://manamoa3.net/bbs/board.php?bo_table=manga&wr_id=1108358

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview
