### ISSUE TITLE
백그라운드 프로세스 문제2

### ISSUE THREAD

**Issue by jpdecade** [KurtBestor/Hitomi-Downloader-issues#849]
![asd](https://user-images.githubusercontent.com/49438209/57927794-1adecc00-78ea-11e9-85d6-befe40cb8c24.png)

사진이 제대로 올라가는지 모르겠네요.
안보이는 프로세스는 그냥 지운거니 무시하시고 맨 밑에 보시면 됩니다.

백그라운드 프로세스에 살아있다면 앱에도 살아있어야 하는데...
일단 이번 업데이트부터 그런게 아니라 예전 처음버전부터 계속 이랬네요.

**Comment by KurtBestor** [comment]
똑같은 주제로 새로 만들면 복잡해지니 앞으론 https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/847 에 댓글로 달아주세요.
