### ISSUE TITLE
제목이 같은 동영상 다운로드

### ISSUE THREAD

**Issue by fangal** [KurtBestor/Hitomi-Downloader-issues#850]
제목이 같은 동영상의 파일을 다운로드를 다운받으면 강제적으로 덮어씌우기가 됩니다. 
예)pornhub의 cosplay
자동으로 덮어씌워지지 않게 하는 방법이 있을까요?

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/233
