### ISSUE TITLE
픽시브 작품수 2000개가 넘어갈때

### ISSUE THREAD

**Issue by ryunlion** [KurtBestor/Hitomi-Downloader-issues#852]
작품수 2000개가 넘어가는 작가 항목이 히토미 다운로더를 종료했다가 다시 실행했을 때 빈칸으로 나오는 현상이 있습니다. 

전부터 있던 것인지 모르겠네요

**Comment by KurtBestor** [comment]
스크린샷 찍어서 보여주세요,

**Comment by ryunlion** [comment]
![1](https://user-images.githubusercontent.com/50749799/57972742-88b5f100-79d9-11e9-8373-f4a5ee101d62.png)

![2](https://user-images.githubusercontent.com/50749799/57972743-8f446880-79d9-11e9-93e1-3e5589f5cc56.png)

이렇습니다

**Comment by ryunlion** [comment]
다운받은 픽시브 주소는 여깁니다. 
https://www.pixiv.net/member.php?id=11374250

**Comment by ryunlion** [comment]
![3](https://user-images.githubusercontent.com/50749799/57977964-f7c53100-7a3d-11e9-9d9b-9a249d133cf4.png)
막 등록했을 때 2000번에서 목록이 끝나있어서일까요

**Comment by KurtBestor** [comment]
다시 다운로드 한 다음, 저장 후 종료하고 다시 켜서 `Ctrl + L` 눌러서 나온 내용 보여주세요.

**Comment by ryunlion** [comment]
![4](https://user-images.githubusercontent.com/50749799/57984951-c24f3080-7a9b-11e9-9e38-293ce8b796bf.png)
