### ISSUE TITLE
작동 방식 문의 드립니다.

### ISSUE THREAD

**Issue by mita5549** [KurtBestor/Hitomi-Downloader-issues#853]
![image](https://user-images.githubusercontent.com/45882353/57947249-5cd33680-7919-11e9-8b62-6d3258c52665.png)

 링크 주소를 입력하고, 다운로드 버튼을 누르면,
 위와 같은 팝업 창이 출력 되었다가 꺼지기를 약 2회 정도 반복합니다.

 1회에 링크 주소를, 2회에 목록을 띄우는 것 같은데,
 결과적으로 다운로드는 제대로 됩니다만, 이전 버전에서는 저런 증상이 없었거든요.ㅠㅠ
 혹시 뭔가 잘못되었나요?

 사용 프로그램 버전은 05 18의 최신 테스트 버전입니다.
 https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by KurtBestor** [comment]
마나모아에서 Cloudflare DDoS protection 을 켰는데, 이걸 우회하기 위해서 1~2 번 켜져요.

protection이 꺼지면 예전과 동일하게 작동할 거예요.

나중에 더 좋은 방법 생기면 바뀔 거예요.

**Comment by mita5549** [comment]
그렇군요! 답변 감사합니다.
보안 내려놨더니 뭔가 잘못 작동하는 것으로 착각했어요.
