### ISSUE TITLE
히토미 / 익헨 다운받을 때 일본어 제목

### ISSUE THREAD

**Issue by nateray42** [KurtBestor/Hitomi-Downloader-issues#855]
![image](https://user-images.githubusercontent.com/47944877/57977206-731ee680-7a2e-11e9-9fee-6ad2a2c67fc1.png)

프로그램 잘 쓰고 있어요!

다름이 아니라, 익헨에서 다운을 받으면 영어제목으로 다운이 되는데, 혹시 일본어 제목으로 다운받는 방안도 고려해보신 적이 있으신지요?

이중으로 정리하려니 약간 힘이 드네요 ㅠㅜ

적극 검토해주시면 감사하겠습니다!!

**Comment by nateray42** [comment]
음 아니면 아예 일어제목으로만 다운받게 할 수도 있나요...? 영어제목은 별 필요 없어서...

**Comment by KurtBestor** [comment]
@Pseudo-Ray @lardmaker @fdsa1538 

테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

![image](https://user-images.githubusercontent.com/14768120/72700391-1bbdb100-3b8f-11ea-8cd5-5385c754758e.png)

**Comment by fdsa1538** [comment]
한동안 망가랑 담쌓아서 늦게봤네요 죄송해요
제목이 긴것은 100자 제한 때문에 짤려서 나와요 혹시나 싶어 세보니까 정확히 100자더군요
기능 만들어주셔서 감사합니다

**Comment by KurtBestor** [comment]
@fdsa1538 참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/272

**Comment by Pseudo-Ray** [comment]
안녕하세요!! 덕분에 만들어주신 기능 잘 쓰고 있습니다!!

그런데 다름이 아니라, 익헨에서 일어 제목으로 받을 때 반정도는 정상적으로 받아지나, 반정도는 아예 서버에 연결이 되지 않는 듯 합니다 ㅠㅜ 

염치없지만, 혹시 확인해 주실수 있으신가요?
