### ISSUE TITLE
문의드립니다

### ISSUE THREAD

**Issue by ldh7680** [KurtBestor/Hitomi-Downloader-issues#858]
다운로드 목록이 700개 가량 되는데
중복 되는게 엄청 난거 같아서 정리를 좀 하고 싶습니다
동일한 목록을 지우는 방법이 따로 있나요?
아니면 중복된 항목을 알 수 있는 방법이라도 있을까요?

**Comment by siwkd2** [comment]
f3누르고 dup: 입력하면 중복된거 주루룩뜹니다

**Comment by ldh7680** [comment]
이런 간단한 방법이....감사합니다^^
