### ISSUE TITLE
히토미 검색 기능에서 태그에 누락이 있습니다.

### ISSUE THREAD

**Issue by luku756** [KurtBestor/Hitomi-Downloader-issues#859]
기본 데이터를 받았을 때 일부 태그에 누락이 있습니다.
태그가 10개인데 8개만 표시되네요. 없는 태그로 검색을 해 봤더니 검색 목록에 나타나지 않았습니다.

특정 태그를 가지고 검색했을 경우 실제 사이트에서 보는 것보다 확연하게 작품 수가 적어서 뭐지 싶어서 보다가 발견했습니다.

![1](https://user-images.githubusercontent.com/43954535/57986073-08f85700-7aab-11e9-96f6-68238a713a4e.PNG)
![2](https://user-images.githubusercontent.com/43954535/57986074-08f85700-7aab-11e9-8e0c-1aa1565d307c.PNG)

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/822

**Comment by luku756** [comment]
기본 데이터 받기를 해도 같은 문제가 발생합니다.
위 경우도 새로 기본데이터 받기 한 직후에 시도한 경우이고, 지금도 다시 해보니 아래처럼 나오네요.

![2](https://user-images.githubusercontent.com/43954535/58115565-53a5da80-7c35-11e9-9644-5cb2df4b9a55.PNG)
![1](https://user-images.githubusercontent.com/43954535/58115566-53a5da80-7c35-11e9-94c0-36893335c442.PNG)


버전은 2.6c 입니다.
처음에 예시로 들었던 경우는 지금은 또 검색되네요. 기본데이터를 받을 때 일부 태그가 누락되는게 아닐까 싶습니다.

**Comment by KurtBestor** [comment]
히토미에서 바로 받아오는게 아니라 중간에 태그가 바뀌면 데이터에 반영되는데 하루정도 걸려요.

며칠 지나도 안 바뀌는 게 있으면 알려주세요.
