### ISSUE TITLE
'이름을 얻는 도중 실패했습니다' 라는 오류 해결법 있나요?

### ISSUE THREAD

**Issue by pachini00** [KurtBestor/Hitomi-Downloader-issues#86]
작업정보에 이런 내용도 있어요
[Messages]
Traceback (most recent call last):
File "hitomi_downloader", line 1003, in download_instagram
File "insta_downloader", line 59, in get_name
File "fucking_encoding", line 116, in clean_title
LookupError: unknown encoding: cp65001

Windows 10 RS4 사용중입니다. 유니코드 때문에 RS4 기능중에
'세계 언어 지원을 위해 Unicode UTF-8 사용' 기능을 사용하고 있습니다.
이 설정을 해제하면 사용가능 합니다만..
지금 환경이 이 기능을 사용해야하는 환경이라
혹시 해결법 있을까 해서 글 남깁니다..

**Comment by KurtBestor** [comment]
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

이건 어떤가요?

**Comment by pachini00** [comment]
와 ㄷㄷ 한방에 해결입니다!
오류 없이 깔끔하게 잘 받아집니다!!
감사합니다!!

혹시 버전업이 될 결우 이렇게 문의 해서 받아야 합니까?

**Comment by KurtBestor** [comment]
새 버전이 나오면 프로그램을 실행할 때 업데이트 할 건지 물어봅니다.
또는 도움말 - 버전 확인... 에서 확인하실 수 있어요.
