### ISSUE TITLE
목록 처리가 잘되지 않습니다

### ISSUE THREAD

**Issue by jaejunghan** [KurtBestor/Hitomi-Downloader-issues#861]
https://blog.naver.com/jaejung999/221541817929

github에 동영상을 올릴수없어서 블로그에 업로드 해봤습니다,

4개 단위로 나눠서 4개가 처리되기 전까지는 그다음에있는목록을 읽지 않습니다

해당 로그입니다.

Checking for updates... HitomiDownloader
Checking for updates... version_check.txt

똁될랜됻굶벇숯볓쨌깿쾢뺭염쵼켹뒝픰눘즶쾸탭심킔툤륌촳뫱콨쿟엔홎깥졗쟃굼첊쳟넁엞덦돤뀯폽홱쵵얦녔걅팫뉗뀼붘둨뺃륁즤뭈동젵왝뻝폶센뉡뙯풻힌첕빇젬봀낉훃멓퀫뫐헨줎멳껈삚냜봙휶툕꺂릠뽵뮗각

4.8.6 / 4.11.2 / 4.16.3
Font: Gulim -> 맑은 고딕
Supported Image Formats: ['bmp', 'pbm', 'pgm', 'png', 'ppm', 'xbm', 'xpm']
v2.6c (latest : v2.6c)
Encodings: ['cp949', 'mbcs', 'ascii', 'utf-8', 'ascii']

Styles:
    Windows
    WindowsXP
    WindowsVista
    Motif
    CDE
    Plastique
    Cleanlooks

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/842#issuecomment-492189221

**Comment by jaejunghan** [comment]
방금 동영상 찍은거는 1개의 프로그램만 돌리는건데 이상합니다

**Comment by KurtBestor** [comment]
한개든 두개든 최대 동시 4개의 작업만 처리해요.
