### ISSUE TITLE
Hentai Foundry 사이트에 대하여

### ISSUE THREAD

**Issue by Rounlet** [KurtBestor/Hitomi-Downloader-issues#862]
우선 사이트 추가해주신 노고 감사드립니다. 
ㅜㅠ 거의 기대도 안하고 있었는데..

기쁜 마음으로 쓰려는데 문제점을 하나 발견했습니다.
https://www.hentai-foundry.com/pictures/user/tuan-hollaback 
이 사이트를 예시로 설명드리자면

갤러리에는 89개의 이미지가 있는데 다운로드 받는 숫자는 12개에 불과합니다.
아마도 제 생각에는 로그인을 하지 않을 경우, 화면 좌측 상단에 있는 필터 기능이 자동으로 검열설정 되서 노출도가 심한 이미지는 아예 화면에 띄우는 것조차 안하는 듯 합니다.

다행히 로그인 후 필터에 가서 개인 설정을 해놓고 보면 
모두 정상적으로 열람 가능합니다.

수정 부탁드립니다!

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by Rounlet** [comment]
89개 이미지 모두 다운로드 잘 됩니다~ Good works!
