### ISSUE TITLE
소설가가되자 긴 이름은 다운이 안 되네요

### ISSUE THREAD

**Issue by a123qqb** [KurtBestor/Hitomi-Downloader-issues#863]
https://ncode.syosetu.com/n2351en/

https://novel18.syosetu.com/n0488bm/

위에 것들은 이름이 길어서인지 중간에 다운로드가 멈춰버리네요

https://ncode.syosetu.com/n2764dv/

이것도 이름이 길어서인지 주황색으로 뜨네요

아, 그리고 중복 처리가 궁금합니다.
작가들이 이미 쓴 부분을 고치면 자동으로 인식하고 다운 받나요?
아니면 수동으로 이미 받은걸 지우고 다시 받아야 하나요?

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

어떤 화가 수정됐으면 수동으로 지우고 다시 받아야 해요.

**Comment by a123qqb** [comment]
https://novel18.syosetu.com/n2351en/

이건 여전히 주황색으로 뜨는데 이름이 너무 길어서 병합이 안 되는게 아닌가 합니다.

**Comment by a123qqb** [comment]
주황색 뜨는것 해결했습니다
아예 폴더 이름을 줄여서 전체 길이가 250자 안쪽으로 들어가게 하니깐 정상적으로 초록색으로 끝나네요.
감사합니다.
