### ISSUE TITLE
소설가가되자 다운로드 폴더명 수정 가능한가요?

### ISSUE THREAD

**Issue by a123qqb** [KurtBestor/Hitomi-Downloader-issues#865]
소설가가되자 폴더명 설정에 n0000xx 인 소설주소가 들어가게 만들어주실 수 없으신가요?
개고본이 있으면 수동으로 삭제하고 다시 받아야 하는데 주소가 같이 표시되면 찾기 편할거 같아서요.
되도록이면 맨 앞이나 이름 바로 뒤가 좋을거 같아 보입니다.
[n0000xx][이름] 소설제목
[이름][n0000xx] 소설제목
이런 형식으로요

**Comment by KurtBestor** [comment]
해당 작업 `마우스 우클릭` - `링크 주소 복사 (C)` 하면 주소 복사돼요.

참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/759
