### ISSUE TITLE
사이트 추가 건의드립니다.

### ISSUE THREAD

**Issue by e50gun** [KurtBestor/Hitomi-Downloader-issues#868]
https://rule34.xxx/

건의 드려 봅니다.

**Comment by KurtBestor** [comment]
rule34 사이트가 여러개인데, 어떤 사이트를 추가하면 좋을지 투표 부탁드려요:
<p><a href="https://api.gh-polls.com/poll/01EPMJWZPQ1HA87BYX5404M892/rule34hentai.net/vote"><img src="https://api.gh-polls.com/poll/01EPMJWZPQ1HA87BYX5404M892/rule34hentai.net" alt=""></a>
<a href="https://api.gh-polls.com/poll/01EPMJWZPQ1HA87BYX5404M892/rule34.paheal.net/vote"><img src="https://api.gh-polls.com/poll/01EPMJWZPQ1HA87BYX5404M892/rule34.paheal.net" alt=""></a>
<a href="https://api.gh-polls.com/poll/01EPMJWZPQ1HA87BYX5404M892/rule34.us/vote"><img src="https://api.gh-polls.com/poll/01EPMJWZPQ1HA87BYX5404M892/rule34.us" alt=""></a>
<a href="https://api.gh-polls.com/poll/01EPMJWZPQ1HA87BYX5404M892/rule34.xxx/vote"><img src="https://api.gh-polls.com/poll/01EPMJWZPQ1HA87BYX5404M892/rule34.xxx" alt=""></a>
<a href="https://api.gh-polls.com/poll/01EPMJWZPQ1HA87BYX5404M892/rule34.xyz/vote"><img src="https://api.gh-polls.com/poll/01EPMJWZPQ1HA87BYX5404M892/rule34.xyz" alt=""></a></p>

**Comment by KurtBestor** [comment]
제일 많은 표를 얻은 Rule34.xxx 추가했어요. 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview
