### ISSUE TITLE
겔부루는 어떻게 다운하는건가요?

### ISSUE THREAD

**Issue by lacoon12** [KurtBestor/Hitomi-Downloader-issues#869]
겔부루의 태그 aomushi_(mushamusha) 이고

https://gelbooru.com/index.php?page=post&s=list&tags=aomushi_%28mushamusha%29&pid=84
주소인데

이거를 다운로더 url란에 입력하고 오른쪽에 페이지 설정해줬는데 

제가잘못하는건가바여 질문드립니다...

**Comment by KurtBestor** [comment]
`옵션 (Options)` - `설정` - `고급 설정` - `DPI 우회` 키세요.

**Comment by lacoon12** [comment]
> `옵션 (Options)` - `설정` - `고급 설정` - `DPI 우회`

감사합니다 개발에 노고가 많으십니다
