### ISSUE TITLE
중복 이미지 찾기 기능 건의사항

### ISSUE THREAD

**Issue by Rounlet** [KurtBestor/Hitomi-Downloader-issues#871]
현재 중복 이미지 창은 왼쪽에 중복된 이미지 목록이 나오고
오른쪽에는 목록에서 클릭한 이미지가 출력되고 있습니다.

제가 건의드리고 싶은 것은 이 오른쪽 출력창인데요. 
크기를 임의로 키우고 싶어도 왼쪽으로 확장은 불가능하고 
오른쪽으로 드래그할 경우 숨기기가 되더군요.

한마디로 왼쪽으로 드래그 시 크기가 확장되었으면 좋겠습니다.
그리고 원래 있던 왼쪽 목록 창은 하단에 스크롤바를 만들어 파일명을 보는데 지장이 없도록 하면 더 좋을 것 같습니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by Rounlet** [comment]
아이고.. 피드백해주신줄 모르고 있었네요.

테스트해본 결과 그대로 반영해주셨습니다!! 덕분에 프로그래밍이라는 작업을 다시 보고 있습니다.

감사합니다~
