### ISSUE TITLE
히토미 삭제작품 다운로더로도 404뜨네요

### ISSUE THREAD

**Issue by lordguys** [KurtBestor/Hitomi-Downloader-issues#872]
3167322구요 리더로 바꿔도 안뜨고 히토미 다운로더로도 404 뜨네요

어떻게 해야 찾을수 있나요?

찾아주실수 있나요?

**Comment by lordguys** [comment]
> 3167322구요 리더로 바꿔도 안뜨고 히토미 다운로더로도 404 뜨네요

> 어떻게 해야 찾을수 있나요??

**Comment by KurtBestor** [comment]
그런 번호의 작품은 없어요.

현재 가장 최신 번호는 1420939 이에요.

**Comment by lordguys** [comment]
제가 2017년 5월쯤에 본거라 3167322는 확실히 기억하는데

그럼 2017년 5월 전 작품은 거의 대부분 다운로더로 받을수 있는거죠?

**Comment by whgmlqja12** [comment]
404오류는 주로 와니 매거진 산하 잡지물이나 몇몇 서클 작품 관련이 주인데 아마 그거에 걸려서 히토미에도 안올라온게 아닌가 싶네요. 단순 잡지나 동인지 수준이라면 엔헨타이에서 찾을수 있는데 아티스트 cg라면 익헨에서 찾는 방법 외엔 없을듯. 거기에도 없으면 다운못하는거구요

**Comment by KurtBestor** [comment]
익헨에 올라오는 순서대로 번호가 지정되는데요, 3167322 는 그것보다 한참 큰 수라서 있을 수가 없어요.

확실히 기억하는 이유가 있나요?

**Comment by lordguys** [comment]
제가 2년전에 직접 주소창에 써서 들어가봤어서요.

2년전에 3으로 시작하는 7자리 품번 몇개 본걸로 기억 하는데

제가 착각한 걸수도 있구요. 아무튼 둘다 답변 ㄳ
