### ISSUE TITLE
계속 Hitomi Downloader 가 Offline 으로 유지됩니다.  help wanted

### ISSUE THREAD

**Issue by Saebyeol98** [KurtBestor/Hitomi-Downloader-issues#873]
프로그램을 다시 다운을 받아도 OFFLINE으로 표시되고 백신상에서도 예외처리로 프로그램을 넣었음에도 불구하고 계속 Offline 으로 표시됩니다
![tempsnip](https://user-images.githubusercontent.com/19588853/58221658-57795000-7d4e-11e9-95ca-69f6e06efb14.png)
예외 처리를 이렇게 해놨음에도 불구하고
아래 사진과 같이 뜹니다.
![image](https://user-images.githubusercontent.com/19588853/58221671-619b4e80-7d4e-11e9-88ea-3000db0463d9.png)
이유가 뭔지 궁금합니다
개발자님 도와주세요 
@KurtBestor

**Comment by KurtBestor** [comment]
`Ctrl + L` 눌러서 나오는 내용 보여주세요.
