### ISSUE TITLE
스크립트 추가 요청

### ISSUE THREAD

**Issue by meloncafe** [KurtBestor/Hitomi-Downloader-issues#875]
[gw.zip](https://github.com/KurtBestor/Hitomi-Downloader-issues/files/3212087/gw.zip)

굿즈 공방이라는 사이트 다운로드 스크립트 입니다.
다운로더 클래스의 정확한 스펙을 몰라서 썸네일은 안나오지만 다운로드는 가능합니다.
PDF로 등록된 게시물만 다운로드 가능합니다.

**Comment by KurtBestor** [comment]
예제 주소가 어떻게 되나요? 사이트 구조를 모르겠네요.

**Comment by meloncafe** [comment]
며칠동안 사이트 접속이 안되네요
접속이 정상적으로 될 때 다시 올리겠습니다.
