### ISSUE TITLE
우회 에러

### ISSUE THREAD

**Issue by naritaman** [KurtBestor/Hitomi-Downloader-issues#876]
![K-015](https://user-images.githubusercontent.com/35300701/58271060-263c6680-7dc6-11e9-9754-4f91d51e24da.png)
며칠전부터 우회 불가 현상이 발생하고 있습니다.

이로 인해 다운로드 목록에 이미지와 페이지 수가 뜨지않고있습니다.

설정에서 DPI우회를 클릭하여도 다시 위 첨부 이미지가 다시 뜹니다.

**Comment by naritaman** [comment]
테스트버전으로 하여도 마찬가지입니다.

**Comment by KurtBestor** [comment]
재부팅해도 안 되나요?

**Comment by naritaman** [comment]
네 그렇습니다. 재부팅하여도 DPI우회가 활성화되지 않습니다.

**Comment by naritaman** [comment]
며칠간 재부팅해도 안되었는데 오늘 해보니 정상적으로 우회됩니다.

코멘트 감사합니다.
