### ISSUE TITLE
 이미지 수가 2000장이 넘어가면 끊겨버리네요

### ISSUE THREAD

**Issue by thiswho3** [KurtBestor/Hitomi-Downloader-issues#877]
픽시브나 산카쿠에서 다운로드 할때, 2000개 이상의 이미지는 2000개에서 끊겨버리고 더는 다운로드가 안되네요. 선택적으로 2000장 넘게 전부 다 다운로드하도록 변경할 수 있을까요?

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/382#issuecomment-450846793
