### ISSUE TITLE
니코동 프리미엄인데 고화질 다운로드가 안됩니다

### ISSUE THREAD

**Issue by satsumaimo1** [KurtBestor/Hitomi-Downloader-issues#878]
프리미엄 계정 사용중인데 이코노미 시간대에는 고화질 다운로드가 안됩니다
ini파일을 열어보니 비밀번호가 얽맔옭뺆으로 입력되어있습니다
#793 답변 보고 다시 삭제하고 재설치해서 계정 넣고 저장해봤는데도 안되고
비밀번호에 특수문자를 제거해보고 다시 해도 해상도640X360으로만 다운됩니다

**Comment by KurtBestor** [comment]
설정파일에 들어있는 비밀번호는 외부에서 읽지 못하게 암호화 되어있어요.
해당 다운로드 작업 `마우스 우 클릭` - `정보... (I)` 눌러서 나온 내용 보여주세요.

**Comment by satsumaimo1** [comment]
version: 2.6c
platform: Windows-7-6.1.7601-SP1
gal_num: https://www.nicovideo.jp/watch/sm25936420
dir: hitomi_downloaded_nico
zip: 
type: nico
artist: None
url: https://www.nicovideo.jp/watch/sm25936420
valid: True
done: True
range: None
range_p: None
single: True
time: 1559445058.15 (Jun 2)
tags: []
goodbyedpi: True
lock: False


[Gallery]
None


[File Names]
[0001] hitomi_downloaded_nico\REVOLVER (Sang it)【luz】.mp4


[URLs]
[0001] http://pa1212365f5.dmc.nico/vod/ht2_nicovideo/nicovideo-sm25936420_fdb24ab211c7781c5566db619b66f75ba6c1b630be517e487db3b7372f3b99ef?ht2_nicovideo=6-1PuN1ttqU7_1559445059280.sp60mq_psgbic_1i2l6t2ovz2b1


[Messages]
done : https://www.nicovideo.jp/watch/sm25936420

이코노미 이전 시간대에는 정상적으로 고화질로 다운로드가 됩니다

**Comment by KurtBestor** [comment]
제가 지금 계정이 없어서 테스트해볼 수 없는데 혹시 계정 테스트용으로 제공해주실 분 계시면 연락해주세요.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by satsumaimo1** [comment]
올려주신 걸로 테스트해봤는데 잘 됩니다 감사합니다!
