### ISSUE TITLE
2.6c버전부터 매크로를 이용한 접근이 불가능하네요

### ISSUE THREAD

**Issue by hihellou** [KurtBestor/Hitomi-Downloader-issues#879]
우선 프로그램 만들어주신것에 대해 무한한 감사를 드립니다.

다름아니고 2.5버전때까지만해도 윈도우 매크로를 이용해서 url 추가를 반자동으로 추가해 다운로드를 하도록 사용해 왔는데,

이번 버전부터 매크로를 이용한 다운로더 클릭이나 입력같은게 전부 막힌것같습니다.

혹시 이것이 기능상 문제를 일으켜서 막은건지, 아니면 무슨이유가 있었는지 혹은 버근지 확인부탁드립니다.

**Comment by KurtBestor** [comment]
[v2.6b](https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/v2.6b) 는 어떤가요?

**Comment by hihellou** [comment]
2.6버전 전부 같은 증상입니다.

**Comment by hihellou** [comment]
> [v2.6b](https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/v2.6b) 는 어떤가요?

전부 확인해보았고, 2.6버전 전부 같은 증상입니다. 2.5버전은 접근은 잘되나, 다운로드 오류가 뜨는군요.
기존에 키매크로를 이용해 사용중이었습니다.

**Comment by KurtBestor** [comment]
v2.5 관리자 권한으로 실행해서 되는지 확인해주세요.

**Comment by hihellou** [comment]
> v2.5 관리자 권한으로 실행해서 매크로 되는지 확인해주세요.

어 안됩니다. 신기하네요. 관리자로 실행해서 매크로를 사용하면 접근이 불가능하고

관리자로 실행하는게 아니면 접근이 되네요.

**Comment by hihellou** [comment]
> v2.5 관리자 권한으로 실행해서 매크로 되는지 확인해주세요.

매크로를 관리자모드로 실행하니 2.6버전도 접근이 가능합니다. 해결이 된거같습니다. 감사합니다.
