### ISSUE TITLE
'데이터를 다운로드하는 중에 실패했습니다' 라고 뜹니다. 

### ISSUE THREAD

**Issue by jibek1234** [KurtBestor/Hitomi-Downloader-issues#88]
아마도 원인은.. 압축파일에 있던 실행파일을 실행시켜서 그 상태에서 데이터를 다운받다가 오류가 생긴것 같습니다. 

중간에 갑자기 뻑나서 꺼졌거든요... 

그래서 압축을 풀고 실행파일을 실행시킨후에 데이터를 다운받으려니까 저런 메세지가 뜨는군요. 

혹시몰라서 오류메세지 디테일도 복붙해봅니다..

제 잘못이긴한데 어떻게 해야할지 감이 안와서요. 

혹시 몰라서 밑의 디테일에 나온것처럼 system32에서 hitomi data 파일을 삭제해봤는데도 똑같더군요. 

Traceback (most recent call last):
  File "hitomi_searcher", line 149, in download_json
  File "hitomi_searcher", line 290, in download_json_
  File "os", line 157, in makedirs
WindowsError: [Error 5] : u'C:\\WINDOWS\\system32\\hitomi_data'

**Comment by KurtBestor** [comment]
실행파일을 D드라이브에 옮기고 해보세요

**Comment by jibek1234** [comment]
아.. 감사합니다. 실행파일을 다른 드라이브에 옮겨서 실행하니까 되는군요. 네트워크 드라이브에 파일 박아놓고 실행했었는데 c드라이브에서 실행한걸로 취급했었나보네요. 겁나 빠른 피드백 감사합니다~
