### ISSUE TITLE
픽시브 로그인 오류 때문에 다운이 안됩니다

### ISSUE THREAD

**Issue by maybe74** [KurtBestor/Hitomi-Downloader-issues#880]
![K-001](https://user-images.githubusercontent.com/39132326/58372232-a9d88d80-7f55-11e9-9ffc-76fcdd8d14b4.png)

예전에는 잘 됐는데 오랜만에 다운 받으려니까 오류가 뜨네요

그래서 확실하게 로그인 정보를 입력했는데도 계속 같은 오류가 뜹니다

![K-002](https://user-images.githubusercontent.com/39132326/58372250-edcb9280-7f55-11e9-999c-1e41b7a2cb6e.png)

제 계정이 픽시브 계정이 아니라 구글 연동 계정인데 이거랑 관계가 있을까요?

방금도 해봤는데 픽시브에서는 로그인 잘됩니다

**Comment by KurtBestor** [comment]
네, 구글 연동 계정은 안 돼요.

**Comment by maybe74** [comment]
최근 버전 말고 예전버전엔 따로 로그인 기능 없이 다운 잘 되지 않았나요??
다운용 픽시브 계정을 따로 하나 파야겠군요

**Comment by jaejunghan** [comment]
저도 구글 계정으로 하는데 픽시브 사이트에 구글계정으로 들어가셔서 유저설정에 자신 픽시브 아이디 있을거에요 비밀번호하고 그거 메모장에 입력하셔서 다운로더에 로그인하시면 됩니다, 아이디가 보통 user_****이런식이에요

**Comment by maybe74** [comment]
오 진짜 되네요 답변 감사드립니다!! ㅎㅎ
