### ISSUE TITLE
pc에서 사용 할  수 없는 프로그램이라고 뜹니다

### ISSUE THREAD

**Issue by pichunt** [KurtBestor/Hitomi-Downloader-issues#881]
처음에는 잘 받아서 써는데요.갑자기 어느날 부터 픽시브에서 다운 받은 움짤을 변환하는 단계에 들어서면 윈도우 알림으로 pc에서 사용 할 수 없는 프로그램이라고 나옵니다. 그 이후에는 히토미 다운로더 작동이 안되고요.. 이게 무슨 문제일까요?
정확히 말하면 이 pc에서 이앱을 사용 할 수 없다고 뜨네요

**Comment by pichunt** [comment]
처음에는 잘 받아서 써는데요.갑자기 어느날 부터 픽시브에서 다운 받은 움짤을 변환하는 단계에 들어서면 윈도우 알림으로 pc에서 사용 할 수 없는 프로그램이라고 나옵니다. 그 이후에는 히토미 다운로더 작동이 안되고요.. 이게 무슨 문제일까요?

**Comment by KurtBestor** [comment]
`%temp%` 경로에 가면 `ffmpeg.exe` 파일이 있을텐데요, 이거 보내주세요.

**Comment by pichunt** [comment]
%temp%는 어디가서 찾아야 하냐요?

**Comment by pichunt** [comment]
이거 첨부를 어떻게 해야 하는지 모르겠는데요. 누르면 pc에서 사용 할 수 없는 앱이라고 뜨네요

**Comment by KurtBestor** [comment]
드래그 & 드랍 하면 돼요.

**Comment by pichunt** [comment]
[ffmpeg.zip](https://github.com/KurtBestor/Hitomi-Downloader-issues/files/3243341/ffmpeg.zip)

**Comment by KurtBestor** [comment]
OS가 어떻게 되나요?

**Comment by pichunt** [comment]
답변 늦어서 죄송 해요 윈도우 에요

**Comment by KurtBestor** [comment]
XP / 7 / 10 어떤 건가요?
32bit / 64bit 중 어떤 건가요?
