### ISSUE TITLE
Wine / Linux Support

### ISSUE THREAD

**Issue by NO-ob** [KurtBestor/Hitomi-Downloader-issues#885]
Not an issue but I just wanted to say this works on linux using wine, you may want to add it to the homepage.

**Comment by KurtBestor** [comment]
Thanks! But it doesn't work properly on Wine. It's too buggy and slow. It's better off using Windows natively.

**Comment by aniketjs** [comment]
Wish this a native version for linux. I hate having to use wine for this.

**Comment by keshavbhatt** [comment]
With wine its laggy, i recommend ultimate-media-downloader as alternative.
