### ISSUE TITLE
니코동 다운로드 오류

### ISSUE THREAD

**Issue by listandtag** [KurtBestor/Hitomi-Downloader-issues#886]
https://www.nicovideo.jp/watch/1474485011

해당 영상은 커뮤니티를 팔로우해야만 볼 수 있는 영상입니다.

팔로우는 그냥 클릭 하나만 하면 바로 되는 건데

다운로더에 아이디를 쳐도 인식을 못 하네요.

**Comment by KurtBestor** [comment]
해당 다운로드 작업 `마우스 우 클릭` - `정보... (I)` 눌러서 나온 내용 보여주세요.

**Comment by listandtag** [comment]
Invalid : [nico] https://www.nicovideo.jp / watch / 1474485011

version: 2.6c
platform: Windows-7-6.1.7601-SP1
gal_num: https://www.nicovideo.jp/watch/1474485011
dir: 
zip: 
type: nico
artist: None
url: https://www.nicovideo.jp/watch/1474485011
valid: False
done: False
range: None
range_p: None
single: True
time: 1559122262.49 (May 29)
tags: []
goodbyedpi: False
lock: False


[Gallery]
None


[File Names]



[URLs]



[Messages]
nico retry...
nico retry...
Could not retrieve video info
stop
Traceback (most recent call last):
File "utils", line 522, in start
File "utils", line 566, in start_
File "nico_downloader4", line 75, in read
File "nico_downloader4", line 95, in get_video
File "nndownload", line 345, in request_video
FormatNotAvailableException: Could not retrieve video info

Fail: nico

done : https://www.nicovideo.jp/watch/1474485011

**Comment by KurtBestor** [comment]
다른 영상은 되나요?

**Comment by listandtag** [comment]
커뮤니티나 팔로우 제한 동영상은 이것밖에 모릅니다 일단은.
일반 영상들이야 당연히 잘 됩니다.

**Comment by KurtBestor** [comment]
재현을 할 수 없어서 테스트 해볼 수 없는데 어떻게해야 볼 수 있나요?

**Comment by listandtag** [comment]
https://com.nicovideo.jp/community/co2291182
니코동 아이디로 로그인하고 이 커뮤니티에 팔로우 신청을 넣으면 바로 팔로우됩니다.
그러면 저 영상이 보입니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by listandtag** [comment]
예아 잘됩니다.
