### ISSUE TITLE
단순히 궁금한점이 있습니다.

### ISSUE THREAD

**Issue by aksghkqhrl** [KurtBestor/Hitomi-Downloader-issues#893]
다운로더를 사용할때 가끔은 웹사이트를 열어서 다운로드하고

또 가끔은 다운로더에서 바로 다운을 해버리는데 기준이 어떻게되는건가요?

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/853
