### ISSUE TITLE
제이마나가 다운로드 되지 않네요.

### ISSUE THREAD

**Issue by dlfmaqmf** [KurtBestor/Hitomi-Downloader-issues#894]
Invalid : [jmana] https://jmana15.com / book / %EB%82%98%ED%8C%94%EA%BD%83%EA%B3%BC%20%EC%B9%B4%EC%84%B8%20%EC%94%A8

version: 2.6c
platform: Windows-10-10.0.17763
gal_num: https://jmana15.com/book/%EB%82%98%ED%8C%94%EA%BD%83%EA%B3%BC%20%EC%B9%B4%EC%84%B8%20%EC%94%A8
dir: 
zip: 
type: jmana
artist: 타카시마 히로미
url: https://jmana15.com/book/%EB%82%98%ED%8C%94%EA%BD%83%EA%B3%BC%20%EC%B9%B4%EC%84%B8%20%EC%94%A8
valid: False
done: False
range: None
range_p: None
single: False
time: 1559342407.98 (Jun 1)
tags: []
goodbyedpi: True
lock: False

[Gallery]
None

[File Names]

[URLs]

[Messages]
dirFormat: [artist] title
fuckkk...
Traceback (most recent call last):
File "constants", line 599, in wrapper
File "jmana_downloader", line 152, in get_imgs_page
KeyError: 'src'

stop
Traceback (most recent call last):
File "utils", line 522, in start
File "utils", line 566, in start_
File "jmana_downloader", line 73, in read
File "jmana_downloader", line 221, in get_imgs
File "constants", line 616, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 599, in wrapper
File "jmana_downloader", line 152, in get_imgs_page
KeyError: 'src'

Fail: jmana

done : https://jmana15.com/book/%EB%82%98%ED%8C%94%EA%BD%83%EA%B3%BC%20%EC%B9%B4%EC%84%B8%20%EC%94%A8

확인 좀 부탁드릴께요.
항상 잘 쓰고 있어요! 감사해요!

**Comment by dlfmaqmf** [comment]
제이마나 테스트 멜로 보내주신걸 해봤는데 여전히 작동하지 않아요.


Invalid : [jmana] https://jmana15.com / book / %EB%82%98%ED%8C%94%EA%BD%83%EA%B3%BC%20%EC%B9%B4%EC%84%B8%20%EC%94%A8

version: 2.6c
platform: Windows-10-10.0.17763
gal_num: https://jmana15.com/book/%EB%82%98%ED%8C%94%EA%BD%83%EA%B3%BC%20%EC%B9%B4%EC%84%B8%20%EC%94%A8
dir: 
zip: 
type: jmana
artist: 타카시마 히로미
url: https://jmana15.com/book/%EB%82%98%ED%8C%94%EA%BD%83%EA%B3%BC%20%EC%B9%B4%EC%84%B8%20%EC%94%A8
valid: False
done: False
range: None
range_p: None
single: False
time: 1559555252.86 (Jun 3)
tags: []
goodbyedpi: True
lock: False


[Gallery]
None


[File Names]



[URLs]



[Messages]
dirFormat: [artist] title
fuckkk...
Traceback (most recent call last):
File "constants", line 599, in wrapper
File "jmana_downloader", line 152, in get_imgs_page
KeyError: 'src'

stop
Traceback (most recent call last):
File "utils", line 522, in start
File "utils", line 566, in start_
File "jmana_downloader", line 73, in read
File "jmana_downloader", line 221, in get_imgs
File "constants", line 616, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 599, in wrapper
File "jmana_downloader", line 152, in get_imgs_page
KeyError: 'src'


Fail: jmana

done : https://jmana15.com/book/%EB%82%98%ED%8C%94%EA%BD%83%EA%B3%BC%20%EC%B9%B4%EC%84%B8%20%EC%94%A8

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by dlfmaqmf** [comment]
아 확인해보니까 잘 되네요 ㅎ 감사합니다!!!

**Comment by dlfmaqmf** [comment]
Invalid : [jmana] https://jmana15.com / book / %EB%82%98%EC%9D%98%20%EC%8B%A0%EB%B6%80

version: 2.6c
platform: Windows-10-10.0.17763
gal_num: https://jmana15.com/book/%EB%82%98%EC%9D%98%20%EC%8B%A0%EB%B6%80
dir: 
zip: 
type: jmana
artist: None
url: https://jmana15.com/book/%EB%82%98%EC%9D%98%20%EC%8B%A0%EB%B6%80
valid: False
done: False
range: None
range_p: None
single: False
time: 1559817534.11 (Jun 6)
tags: []
goodbyedpi: True
lock: False


[Gallery]
None


[File Names]



[URLs]



[Messages]
'NoneType' object has no attribute 'findAll'
stop
Traceback (most recent call last):
File "utils", line 522, in start
File "utils", line 566, in start_
File "jmana_downloader", line 69, in read
File "jmana_downloader", line 63, in name
File "jmana_downloader", line 96, in get_artist
AttributeError: 'NoneType' object has no attribute 'findAll'

Fail: jmana

done : https://jmana15.com/book/%EB%82%98%EC%9D%98%20%EC%8B%A0%EB%B6%80

죄송한테 ㅜ 제이마나가 다시 안되기 시작하네요 ㅜ
혹시 방법이 없을까요?

**Comment by dlfmaqmf** [comment]
Invalid : [jmana] https://jmana15.com / book / %EC%8B%A0%EB%B6%80%20%EC%9D%B4%EC%95%BC%EA%B8%B0

version: 2.6c
platform: Windows-10-10.0.17763
gal_num: https://jmana15.com/book/%EC%8B%A0%EB%B6%80%20%EC%9D%B4%EC%95%BC%EA%B8%B0
dir: 
zip: 
type: jmana
artist: None
url: https://jmana15.com/book/%EC%8B%A0%EB%B6%80%20%EC%9D%B4%EC%95%BC%EA%B8%B0
valid: False
done: False
range: None
range_p: None
single: False
time: 1559818301.28 (Jun 6)
tags: []
goodbyedpi: True
lock: False


[Gallery]
None


[File Names]



[URLs]



[Messages]
'NoneType' object has no attribute 'findAll'
stop
Traceback (most recent call last):
File "utils", line 529, in start
File "utils", line 573, in start_
File "jmana_downloader", line 69, in read
File "jmana_downloader", line 63, in name
File "jmana_downloader", line 96, in get_artist
AttributeError: 'NoneType' object has no attribute 'findAll'

Fail: jmana

done : https://jmana15.com/book/%EC%8B%A0%EB%B6%80%20%EC%9D%B4%EC%95%BC%EA%B8%B0

메일로 온 테스트 프로그램으로도 여전히 다운로드가 안되네요.
시간되실때 확인해주시면 감사합니다!

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by dlfmaqmf** [comment]
다시 잘되네요! 감사합니다!!!

**Comment by bhkim0115** [comment]
설치해서 주소붙여 넣은후 실행했는데 여전히 않됩니다....

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by bhkim0115** [comment]
https://jmana16.com/book/%EC%A0%9C%20%EC%97%AC%EC%B9%9C%EC%9D%80%20%EC%B5%9C%EA%B3%A0%EC%9E%85%EB%8B%88%EB%8B%A4!/101798

알려주신 링크따라 파일 다운받아서 기존 설치 폴더에 설치후 위 주소를 입력했지만 에러표시가 나면서 
멈추네요...

**Comment by KurtBestor** [comment]
다음과 같이 목록 주소를 입력해주세요: https://jmana16.com/book/%EC%A0%9C%20%EC%97%AC%EC%B9%9C%EC%9D%80%20%EC%B5%9C%EA%B3%A0%EC%9E%85%EB%8B%88%EB%8B%A4!
