### ISSUE TITLE
페이스북 다운로드가 정상적으로 되지 않습니다

### ISSUE THREAD

**Issue by ixkatan** [KurtBestor/Hitomi-Downloader-issues#897]
거의 대부분의 페이스북 페이지에서 비슷한 증상이 나타나는데

주소를 입력하고 다운버튼을 누르면 로딩이 좀 되는가 싶다가

invaild 어쩌고 하는 빨간 글씨가 뜨면서 에러가 뜹니다

예전엔 정상적으로 됐었는데 최근들어 갑자기 이러네요 ㅠㅠ

**Comment by KurtBestor** [comment]
해당 작업 `마우스 우 클릭` - `정보... (I)` 눌러서 나온 내용 보여주세요.

**Comment by ixkatan** [comment]
Invalid : [facebook] https://www.facebook.com / yurisa123

version: 2.6c
platform: Windows-10-10.0.17134
gal_num: https://www.facebook.com/yurisa123
dir: 
zip: 
type: facebook
artist: None
url: https://www.facebook.com/yurisa123
valid: False
done: False
range: None
range_p: None
single: False
time: 1559684894.94 (Jun 5)
tags: []
goodbyedpi: True
lock: False


[Gallery]
None


[File Names]



[URLs]



[Messages]
'NoneType' object has no attribute 'findAll'
stop
Traceback (most recent call last):
File "utils", line 522, in start
File "utils", line 566, in start_
File "facebook_downloader2", line 78, in read
File "facebook_downloader2", line 151, in get_imgs
AttributeError: 'NoneType' object has no attribute 'findAll'

Fail: facebook

done : https://www.facebook.com/yurisa123

**Comment by KurtBestor** [comment]
로그인이 필요한 계정은 지원하지 않아요.

**Comment by ixkatan** [comment]
게시물 삭제 부탁드립니다.
