### ISSUE TITLE
폴더명 형식 관련 건의사항입니다.

### ISSUE THREAD

**Issue by Grimja** [KurtBestor/Hitomi-Downloader-issues#898]
안녕하세요.
개발해주신 덕분에 잘 쓰고 있습니다만, 아쉬운 부분이 있어 건의드리고자 합니다.

1. 폴더명 형식(ZIP파일 형식)에서 가능한 **태그 목록**을 지원 페이지 및 Readme에도 적어주셨으면 합니다.

기본 설정에도 몇 가지 방식이 있지만, 사용자가 커스텀 하기에는 어느 태그까지 가능한지 정도는 알려주셨으면 합니다.
프리셋에서 더 설정하고 싶어도, 이 밖에 지원하는 태그가 있는지 알 수가 없습니다.
원하는 예시 : 페이지 수, 패러디 명 등

2. 폴더명 형식 변경한 뒤에도 기존에 다운받은 파일은 인식 가능하게끔 했으면 좋겠습니다.

버그인지는 모르겠으나 가끔 폴더명 형식을 변경한 이후에는 변경 전 형식으로 다운받은 파일들을 인식하지 못합니다.

예) [artist] title (id) 형식으로 받았는데 
여기에 다른 태그를 추가하면, 기존 형식으로 받았던 파일들과 안받은 파일들을 구분하지 못함.

3. 사소한 건의사항인데, Corrupt 태그를 '부패'에서 '타락'으로 바꿔주세요.

항상 응원합니다.

감사합니다.

**Comment by KurtBestor** [comment]
1. 폴더명 형식 콤보박스에서 오른쪽 화살표 눌러서 나오는 키워드가 전부예요.

2. 인식이 안 된다는 게 무슨 뜻인가요?

3. 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by neuprin** [comment]
저도 2번과 같은 비슷한 문제가 있네요. 예전에는 [작가1, Etc] 같은 형식의 네이밍 패턴이엇는데 [작가1, 작가2] 같은식으로 바뀌면서 같은 작품(갤러리 넘버)임에도 불과하고 다른 작품이라고 인식하는 경우가 있는거 같습니다. 예전 네이밍 패턴에 대한 backward compatibility나 아예 갤러리 넘버로 고유 작품이라 인식하거나 하는 식이어야 될거 같습니다.
