### ISSUE TITLE
엄청 많은 url 추가에 대한 문제

### ISSUE THREAD

**Issue by neuprin** [KurtBestor/Hitomi-Downloader-issues#90]
819가 넘어갈 시 819개만 더해지는 문제가 있습니다.

여기까지는 괜찮은데 초록색(완료) 작업이 어느정도의 수를 넘어서면(일정한 수치는 없습니다. 크기의 문제일 것 같습니다.) 튕깁니다. 수천개의 url을 백개씩 받기는 어려워서 리폿합니다.

**Comment by KurtBestor** [comment]
1. 검색기에서 820개 이상 추가가 안 된다
2. URL 하나 하나를 입력해서 추가하는데 목록에 820개 이상 추가가 안 된다
3. URL 여러개를 모아서 주소창에 한번에 쓰고 추가하는데 820개 이상 추가가 안 된다

어떤 건가요?
확인해본 결과 1, 2번은 제 환경에선 문제 없이 되네요.

사용하는 운영체제, 비트가 어떻게 되나요?

**Comment by neuprin** [comment]
3번이요.

운영체제는 windows 10 home 64 bit입니다.

완료된 작업이 많을 경우 다운로더가 튕기는 현상도 있는데 이건 어떻게 설명해드려야 할지 모르겠네요

**Comment by KurtBestor** [comment]
820개 이상 추가가 안되는 문제는 아마 주소창의 문자길이 제한때문에 그럴거예요.

https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

이건 어떤가요? 이것도 튕기나요?
그리고 우측 하단의 진행 표시줄에 뭐라고 뜨나요? ERR라고 뜨나요, 아니면 %수치가 보이나요?

**Comment by neuprin** [comment]
잠시 출장을 갔었던지라 대답이 늦어졌네요. 일단 주신 버전으로는 이상하게도 안 튕기네요 733개가 넘어가는데도 안 튕기는 걸 보면 그렇게 봐도 상관 없을 꺼 같습니다. 현재 버전으로는 확인 못 했습니다.
