### ISSUE TITLE
익헨에서 다운시 밴걸리는데 피할수 있는방법이 있을까요?

### ISSUE THREAD

**Issue by qwer1322** [KurtBestor/Hitomi-Downloader-issues#900]
익헨에서 다운시
Your IP address has been temporarily banned for excessive pageloads which indicates that you are using automated mirroring/harvesting software. The ban expires in 3 days and 16 hours

라면서 밴당하는데 해결법이 있을까요?
다운로드 속도 제한을 걸어봐도 마찬가지네요

**Comment by KurtBestor** [comment]
[여기](https://e-hentai.org/home.php) 들어가서 `Reset Limit` 클릭해주세요.

**Comment by qwer1322** [comment]
![1](https://user-images.githubusercontent.com/51334651/59118082-481f1700-898a-11e9-8cc4-97f150015950.png)

아예 사이트 자체가 안들어가지게 밴이 됩니다...

**Comment by KurtBestor** [comment]
얼마나 다운로드하면 밴 되나요?

**Comment by qwer1322** [comment]
150~200장 내외같습니다

**Comment by KurtBestor** [comment]
`옵션 (Options)` - `설정 (Preferences)...` - `일반 설정` - `스레드` 를 1로 줄여보세요.

**Comment by qwer1322** [comment]
해결 되었습니다 감사합니다
