### ISSUE TITLE
미리보기가 보이지 않습니다.

### ISSUE THREAD

**Issue by nonname13** [KurtBestor/Hitomi-Downloader-issues#901]
dpi우회가 안된다고 뜨고 에러에서 goodbye_dpi line 72  와 goodbye_dpi line 203이 뜨네요.
https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/800
위 링크와 비슷해보여서 0.1.5다운로드후 결과에서는
block passive 1
fragment http 2 
fragment persistent http 2 
fragment https 2 
hoSt 1
host no space 1
mix host 1
http allports 0
http persistent nowait 1
dns redirect 0
dnsv6 redirect 0

라고 뜨네요..

**Comment by KurtBestor** [comment]
GoodbyeDPI 실행했을 때 어떻게 나오는지 스크린샷 찍어서 보여주세요.

**Comment by nonname13** [comment]
> GoodbyeDPI 실행했을 때 어떻게 나오는지 스크린샷 찍어서 보여주세요.

![g](https://user-images.githubusercontent.com/51406534/59037561-79c1b080-88ac-11e9-965b-3a05d276c346.png)

**Comment by KurtBestor** [comment]
재부팅한 다음 `옵션` - `설정` - `고급 설정` - `DPI 우회` 키고 어떻게 나오는지 스크린샷 찍어서 보여주세요,

**Comment by nonname13** [comment]
> 재부팅한 다음 `옵션` - `설정` - `고급 설정` - `DPI 우회` 키고 어떻게 나오는지 스크린샷 찍어서 보여주세요,

늦어서 죄송합니다
![dpi](https://user-images.githubusercontent.com/51406534/59510999-1a891f00-8ef0-11e9-8849-b7bec0c7b2be.png)
 이렇게 뜹니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by nonname13** [comment]
> 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

![dpi2](https://user-images.githubusercontent.com/51406534/59550870-6e0c7300-8fab-11e9-963c-d74916ee3ec0.png)

이번엔 이렇게 에러뜨네요.

**Comment by KurtBestor** [comment]
음.. 이상하네요.

GoodbyeDPI 따로 실행해서 하는 수 밖에 없겠어요.

**Comment by nonname13** [comment]
> 음.. 이상하네요.
> 
> GoodbyeDPI 따로 실행해서 하는 수 밖에 없겠어요.
 
아 그렇게 해도 되는군요. 일단을 그렇게 써야겠네요. 놋북이 어느순간부터 별의별에러(신규데이터 다운불가 등등) 다일으키는데 어쩔수없는듯하네요 ㅋㅋ
