### ISSUE TITLE
트위터, 인스타그램 동영상 다운 문제

### ISSUE THREAD

**Issue by open-mindt** [KurtBestor/Hitomi-Downloader-issues#903]
트위터에 새로 올라온 것들이 있나 하고 여러 작업을 다시 시작 걸어 놓으면
새로 올라온 동영상이 있는데 다운이 받아지지 않는 것들이 있어서
작업 정보를 보니
```
Falid to read video:696474884340199424
Traceback (most recent call last):
File "twitter_downloader", line 264, in get_videos
File "tweepy\binder", line 250, in _call
File "tweepy\binder", line 232, in execute
RateLimitError: [{u'message': u'Rate limit exceeded', u'code': 88}]
```
이런 에러 메세지들이 주르륵 있는 것을 볼 수 있습니다.  과도한 접속이 원인 인가 봅니다.

그리고 인스타그램에서 영상만 올린 포스트는 영상 다운이 잘 되는데.
영상과 사진이 같이 올려져 있는 포스트나 영상이 여러개인 포스트에서는 
영상을 다운 받지 않고 영상의 스냅샷 사진만 받아지고 있습니다. 
확인 부탁드립니다.

**Comment by KurtBestor** [comment]
해당 버그가 발생하는 인스타그램 계정 알려주실 수 있나요?

**Comment by open-mindt** [comment]
https://www.instagram.com/sein_unni/

이 계정이 한 포스트에 영상과 사진이 함께 자주 올라 와서. 확인하기 쉽습니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by open-mindt** [comment]
인스타그램은 잘 받아 지는 것을 확인했습니다.

트위터 같은 경우에는 작업을 다시 시작했을때  그 계정의 최신 트윗이 동영상일 경우에
Invalid : [twitter] 에러가 나고 작업 정보에는 아래와 같은 메세지가 출력됩니다.

```
[Messages]
max_pos=None, imgs=0
skip: F:\Twitter\--- (@---------)\[19-06-05] 1136123044689195009_p0.mp4
local variable 'img' referenced before assignment
stop
Traceback (most recent call last):
File "utils", line 529, in start
File "utils", line 573, in start_
File "twitter_downloader", line 42, in read
File "twitter_downloader", line 243, in get_imgs
UnboundLocalError: local variable 'img' referenced before assignment

Fail: twitter
```

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by open-mindt** [comment]
다시 올려주신 것은 위의 에러가 문제 없이 잘 작동 됩니다. 속도가 많이 빨라져서 정말 좋네요.

근데.. 여러개의 작업을 한꺼번에 다시 시작을 걸어 놓았을때.. 몇몇의 작업이 이런 메세지를 내면서
에러가 납니다.  물론 다시 시작을 하면 해결 되긴 합니다.
```[Messages]
max_pos=None, imgs=0
404
stop
Traceback (most recent call last):
File "utils", line 529, in start
File "utils", line 573, in start_
File "twitter_downloader", line 42, in read
File "twitter_downloader", line 208, in get_imgs
File "downloader", line 340, in read_html
Exception: 404

Fail: twitter
```

추가로.. 종료할때 나오는 로고에는 버전이 v2.5c 로 나옵니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by open-mindt** [comment]
모든게 잘 되는 것 같습니다. 정말 감사합니다.
