### ISSUE TITLE
유튜브 다운로드시 깨지는 문제가 있습니다(일부 영상만)

### ISSUE THREAD

**Issue by siwkd2** [KurtBestor/Hitomi-Downloader-issues#904]
모든 영상이 다 그런건 아닙니다

https://www.youtube.com/watch?v=mLzNk_FfHjg

이영상만 변환중 깨지는 현상이 발견되었습니다

확인해보니 영상비율이 21:9 인지라 여기서 변환하는 과정에서 깨지는걸로 확인이 됩니다

혹시 해결가능하시다면 패치부탁드립니다

읽어주셔서 감사합니다

**Comment by KurtBestor** [comment]
해당 작업 `마우스 우클릭` - `정보... (I)` 눌러서 나오는 내용 보여주세요.

**Comment by siwkd2** [comment]
> 해당 작업 `마우스 우클릭` - `정보... (I)` 눌러서 나오는 내용 보여주세요.

[MV] Gummy(거미) _ Alone(혼자)

version: 2.6c
platform: Windows-7-6.1.7601-SP1
gal_num: https://www.youtube.com/watch?v=mLzNk_FfHjg
dir: hitomi_downloaded_youtube
zip: 
type: youtube
artist: 1theK (원더케이)
url: https://www.youtube.com/watch?v=mLzNk_FfHjg
valid: True
done: True
range: None
range_p: None
single: True
time: 1559896272.23 (Jun 7)
tags: []
goodbyedpi: True
lock: False


[Gallery]
None


[File Names]
[0001] hitomi_downloaded_youtube\[MV] Gummy(거미) _ Alone(혼자).mp4
[0002] hitomi_downloaded_youtube\[MV] Gummy(거미) _ Alone(혼자).srt


[URLs]
[0001] https://r8---sn-3u-20nl.googlevideo.com/videoplayback?id=o-AE7J9YtCODCsXOyBWqpXnSrEEPpVnIVZm79z7ZUbLJLq&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C271%2C278%2C313%2C394%2C395%2C396%2C397%2C398&itag=271&source=youtube&requiressl=yes&mm=31%2C29&mn=sn-3u-20nl%2Csn-3u-bh2e7&ms=au%2Crdu&mv=m&pl=18&ei=2SD6XPSdI5DsgAOMiLGQDQ&initcwndbps=1778750&mime=video%2Fwebm&gir=yes&clen=45912501&dur=279.988&lmt=1552943383588238&mt=1559896126&fvip=8&keepalive=yes&c=WEB&txp=5531432&ip=221.164.122.234&ipbits=0&expire=1559917881&sparams=ip%2Cipbits%2Cexpire%2Cid%2Caitags%2Csource%2Crequiressl%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cei%2Cinitcwndbps%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&key=yt8&signature=AAA4A561F40E42A86255F4E9AD72EEFDD8F9876F.6540DD4CA27C58D54382BB0C37C7DCB23FF27E7A&ratebypass=yes


[Messages]
[None][0fps][50kbps] webm opus ─ 249 - audio only (DASH audio)
[None][0fps][70kbps] webm opus ─ 250 - audio only (DASH audio)
[None][0fps][128kbps] m4a mp4a.40.2 ─ 140 - audio only (DASH audio)
[None][0fps][128kbps] webm vorbis ─ 171 - audio only (DASH audio)
[None][0fps][160kbps] webm opus ─ 251 - audio only (DASH audio)
[108p][0fps][None] mp4 None ─ 160 - 256x108 (144p)
[108p][0fps][None] mp4 None ─ 394 - 256x108 (144p)
[178p][0fps][None] mp4 None ─ 133 - 426x178 (240p)
[108p][0fps][None] webm None ─ 278 - 256x108 (144p)
[178p][0fps][None] mp4 None ─ 395 - 426x178 (240p)
[178p][0fps][None] webm None ─ 242 - 426x178 (240p)
[268p][0fps][None] mp4 None ─ 396 - 640x268 (360p)
[268p][0fps][None] mp4 None ─ 134 - 640x268 (360p)
[268p][0fps][None] webm None ─ 243 - 640x268 (360p)
[358p][0fps][None] mp4 None ─ 397 - 854x358 (480p)
[358p][0fps][None] webm None ─ 244 - 854x358 (480p)
[358p][0fps][None] mp4 None ─ 135 - 854x358 (480p)
[536p][0fps][None] mp4 None ─ 398 - 1280x536 (720p)
[536p][0fps][None] mp4 None ─ 136 - 1280x536 (720p)
[536p][0fps][None] webm None ─ 247 - 1280x536 (720p)
[804p][0fps][None] mp4 None ─ 137 - 1920x804 (1080p)
[804p][0fps][None] webm None ─ 248 - 1920x804 (1080p)
[1070p][0fps][None] webm None ─ 271 - 2560x1070 (1440p)
[1606p][0fps][None] webm None ─ 313 - 3840x1606 (2160p)
[268p][0fps][96kbps] mp4 mp4a.40.2 ─ 18 - 640x268 (medium)


# stream_final <youtube_dl_test.Video object at 0x2AD19FD0> 271 - 2560x1070 (1440p) 1070p webm None 0fps
stream is not valid
# stream_final <youtube_dl_test.Video object at 0x2AD19D50> 137 - 1920x804 (1080p) 804p mp4 None 0fps
stream is not valid
# stream_final <youtube_dl_test.Video object at 0x2AD19CB0> 248 - 1920x804 (1080p) 804p webm None 0fps
stream is not valid
# stream_final <youtube_dl_test.Video object at 0x2AD190D0> 398 - 1280x536 (720p) 536p mp4 None 0fps
stream is not valid
# stream_final <youtube_dl_test.Video object at 0x2AD19210> 136 - 1280x536 (720p) 536p mp4 None 0fps
stream is not valid
# stream_final <youtube_dl_test.Video object at 0x2AD19090> 247 - 1280x536 (720p) 536p webm None 0fps
stream is not valid
# stream_final <youtube_dl_test.Video object at 0x2AD19BD0> 397 - 854x358 (480p) 358p mp4 None 0fps
stream is not valid
# stream_final <youtube_dl_test.Video object at 0x2AD191D0> 244 - 854x358 (480p) 358p webm None 0fps
# stream_final <youtube_dl_test.Video object at 0x2AD19370> 135 - 854x358 (480p) 358p mp4 None 0fps
stream is not valid
# stream_final <youtube_dl_test.Video object at 0x2AD191D0> 244 - 854x358 (480p) 358p webm None 0fps
stream is not valid
# stream_final <youtube_dl_test.Video object at 0x2AD19250> 396 - 640x268 (360p) 268p mp4 None 0fps
# stream_final <youtube_dl_test.Video object at 0x2AD193B0> 18 - 640x268 (medium) 268p mp4 mp4a.40.2 0fps
stream is not valid
# stream_final <youtube_dl_test.Video object at 0x2AD19250> 396 - 640x268 (360p) 268p mp4 None 0fps
stream is not valid
# stream_final <youtube_dl_test.Video object at 0x2AD19E50> 134 - 640x268 (360p) 268p mp4 None 0fps
stream is not valid
# stream_final <youtube_dl_test.Video object at 0x2AD19E70> 243 - 640x268 (360p) 268p webm None 0fps
stream is not valid
# stream_final <youtube_dl_test.Video object at 0x2AD19C50> 133 - 426x178 (240p) 178p mp4 None 0fps
stream is not valid
# stream_final <youtube_dl_test.Video object at 0x2AD19150> 395 - 426x178 (240p) 178p mp4 None 0fps
stream is not valid
# stream_final <youtube_dl_test.Video object at 0x2AD19F50> 242 - 426x178 (240p) 178p webm None 0fps
stream is not valid
# stream_final <youtube_dl_test.Video object at 0x21AAF890> 160 - 256x108 (144p) 108p mp4 None 0fps
stream is not valid
# stream_final <youtube_dl_test.Video object at 0x21AAF6D0> 394 - 256x108 (144p) 108p mp4 None 0fps
stream is not valid
# stream_final <youtube_dl_test.Video object at 0x2AD19270> 278 - 256x108 (144p) 108p webm None 0fps
stream is not valid
[None][0fps][50kbps] webm opus ─ 249 - audio only (DASH audio)
[None][0fps][70kbps] webm opus ─ 250 - audio only (DASH audio)
[None][0fps][128kbps] m4a mp4a.40.2 ─ 140 - audio only (DASH audio)
[None][0fps][128kbps] webm vorbis ─ 171 - audio only (DASH audio)
[None][0fps][160kbps] webm opus ─ 251 - audio only (DASH audio)
[108p][0fps][None] mp4 None ─ 160 - 256x108 (144p)
[108p][0fps][None] mp4 None ─ 394 - 256x108 (144p)
[178p][0fps][None] mp4 None ─ 133 - 426x178 (240p)
[108p][0fps][None] webm None ─ 278 - 256x108 (144p)
[178p][0fps][None] mp4 None ─ 395 - 426x178 (240p)
[178p][0fps][None] webm None ─ 242 - 426x178 (240p)
[268p][0fps][None] mp4 None ─ 396 - 640x268 (360p)
[268p][0fps][None] mp4 None ─ 134 - 640x268 (360p)
[268p][0fps][None] webm None ─ 243 - 640x268 (360p)
[358p][0fps][None] mp4 None ─ 397 - 854x358 (480p)
[358p][0fps][None] webm None ─ 244 - 854x358 (480p)
[358p][0fps][None] mp4 None ─ 135 - 854x358 (480p)
[536p][0fps][None] mp4 None ─ 398 - 1280x536 (720p)
[536p][0fps][None] mp4 None ─ 136 - 1280x536 (720p)
[536p][0fps][None] webm None ─ 247 - 1280x536 (720p)
[804p][0fps][None] mp4 None ─ 137 - 1920x804 (1080p)
[804p][0fps][None] webm None ─ 248 - 1920x804 (1080p)
[1070p][0fps][None] webm None ─ 271 - 2560x1070 (1440p)
[1606p][0fps][None] webm None ─ 313 - 3840x1606 (2160p)
[268p][0fps][96kbps] mp4 mp4a.40.2 ─ 18 - 640x268 (medium)


# stream_final <youtube_dl_test.Video object at 0x26450F10> 271 - 2560x1070 (1440p) 1070p webm None 0fps
[None][0fps][50kbps] webm opus ─ 249 - audio only (DASH audio)
[None][0fps][70kbps] webm opus ─ 250 - audio only (DASH audio)
[None][0fps][128kbps] m4a mp4a.40.2 ─ 140 - audio only (DASH audio)
[None][0fps][128kbps] webm vorbis ─ 171 - audio only (DASH audio)
[None][0fps][160kbps] webm opus ─ 251 - audio only (DASH audio)
[268p][0fps][96kbps] mp4 mp4a.40.2 ─ 18 - 640x268 (medium)

[None][0fps][128kbps] m4a mp4a.40.2 ─ 140 - audio only (DASH audio)
[268p][0fps][96kbps] mp4 mp4a.40.2 ─ 18 - 640x268 (medium)

[None][0fps][128kbps] m4a mp4a.40.2 ─ 140 - audio only (DASH audio)

# stream_audio 128kbps m4a mp4a.40.2
https://r8---sn-3u-20nl.googlevideo.com/videoplayback?id=o-AE7J9YtCODCsXOyBWqpXnSrEEPpVnIVZm79z7ZUbLJLq&itag=140&source=youtube&requiressl=yes&mm=31%2C29&mn=sn-3u-20nl%2Csn-3u-bh2e7&ms=au%2Crdu&mv=m&pl=18&ei=2SD6XPSdI5DsgAOMiLGQDQ&initcwndbps=1778750&mime=audio%2Fmp4&gir=yes&clen=4533189&dur=280.055&lmt=1552943192509866&mt=1559896126&fvip=8&keepalive=yes&c=WEB&txp=5531432&ip=221.164.122.234&ipbits=0&expire=1559917881&sparams=ip%2Cipbits%2Cexpire%2Cid%2Citag%2Csource%2Crequiressl%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cei%2Cinitcwndbps%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&key=yt8&signature=39841135239F4A1DFC16295C8FD63C52187D6943.9280CE3330CC6E495804308C6BD9F7D5A731F4C6&ratebypass=yes
Resolution: 1070p
Codec: vp9 / None
Abr: None
Subtype: webm
FPS: 0

Download audio: https://r8---sn-3u-20nl.googlevideo.com/videoplayback?id=o-AE7J9YtCODCsXOyBWqpXnSrEEPpVnIVZm79z7ZUbLJLq&itag=140&source=youtube&requiressl=yes&mm=31%2C29&mn=sn-3u-20nl%2Csn-3u-bh2e7&ms=au%2Crdu&mv=m&pl=18&ei=2SD6XPSdI5DsgAOMiLGQDQ&initcwndbps=1778750&mime=audio%2Fmp4&gir=yes&clen=4533189&dur=280.055&lmt=1552943192509866&mt=1559896126&fvip=8&keepalive=yes&c=WEB&txp=5531432&ip=221.164.122.234&ipbits=0&expire=1559917881&sparams=ip%2Cipbits%2Cexpire%2Cid%2Citag%2Csource%2Crequiressl%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cei%2Cinitcwndbps%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&key=yt8&signature=39841135239F4A1DFC16295C8FD63C52187D6943.9280CE3330CC6E495804308C6BD9F7D5A731F4C6&ratebypass=yes
Convert: C:\hitomi_downloaded_youtube\[MV] Gummy(거미) _ Alone(혼자).webm
rename (1): hitomi_downloaded_youtube\F6D18029_a.tmp -> C:\hitomi_downloaded_youtube\tmpA6F24637_a.weba
rename (1): C:\hitomi_downloaded_youtube\[MV] Gummy(거미) _ Alone(혼자).webm -> C:\hitomi_downloaded_youtube\tmpA6F24637_v.webm
-y -i tmpA6F24637_a.weba -i tmpA6F24637_v.webm -c copy -strict experimental -preset ultrafast -shortest tmpA6F24637_o.mp4
[code]
0
[out]
ffmpeg version 4.1 Copyright (c) 2000-2018 the FFmpeg developers
built with gcc 8.2.1 (GCC) 20181017
configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth
libavutil 56. 22.100 / 56. 22.100
libavcodec 58. 35.100 / 58. 35.100
libavformat 58. 20.100 / 58. 20.100
libavdevice 58. 5.100 / 58. 5.100
libavfilter 7. 40.101 / 7. 40.101
libswscale 5. 3.100 / 5. 3.100
libswresample 3. 3.100 / 3. 3.100
libpostproc 55. 3.100 / 55. 3.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'tmpA6F24637_a.weba':
Metadata:
major_brand : dash
minor_version : 0
compatible_brands: iso6mp41
creation_time : 2019-03-18T21:06:25.000000Z
Duration: 00:04:40.06, start: 0.000000, bitrate: 129 kb/s
Stream #0:0(eng): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 4 kb/s (default)
Metadata:
creation_time : 2019-03-18T21:06:25.000000Z
handler_name : ISO Media file produced by Google Inc. Created on: 03/18/2019.
Input #1, matroska,webm, from 'tmpA6F24637_v.webm':
Metadata:
encoder : google/video-file
Duration: 00:04:39.99, start: 0.000000, bitrate: 1311 kb/s
Stream #1:0(eng): Video: vp9 (Profile 0), yuv420p(tv, bt709), 2560x1070, SAR 1:1 DAR 256:107, 23.98 fps, 23.98 tbr, 1k tbn, 1k tbc (default)
Output #0, mp4, to 'tmpA6F24637_o.mp4':
Metadata:
major_brand : dash
minor_version : 0
compatible_brands: iso6mp41
encoder : Lavf58.20.100
Stream #0:0(eng): Video: vp9 (Profile 0) (vp09 / 0x39307076), yuv420p(tv, bt709), 2560x1070 [SAR 1:1 DAR 256:107], q=2-31, 23.98 fps, 23.98 tbr, 16k tbn, 1k tbc (default)
Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 4 kb/s (default)
Metadata:
creation_time : 2019-03-18T21:06:25.000000Z
handler_name : ISO Media file produced by Google Inc. Created on: 03/18/2019.
Stream mapping:
Stream #1:0 -> #0:0 (copy)
Stream #0:0 -> #0:1 (copy)
Press [q] to stop, [?] for help
frame= 6713 fps=0.0 q=-1.0 Lsize= 49353kB time=00:04:39.96 bitrate=1444.1kbits/s speed= 626x 
video:44788kB audio:4375kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.386981%

Convert success: True
rename (1): C:\hitomi_downloaded_youtube\[MV] Gummy(거미) _ Alone(혼자).webm
rename ext .webm --> .mp4
done : https://www.youtube.com/watch?v=mLzNk_FfHjg

**Comment by KurtBestor** [comment]
영상 파일 보내주시면 분석해볼게요.
