### ISSUE TITLE
히토미 탐색기에서 미리보기 이미지가 안뜨는 현상이 있습니다

### ISSUE THREAD

**Issue by siwkd2** [KurtBestor/Hitomi-Downloader-issues#906]
히토미 미리보기에서 검색하면 특정 작가나 그룹이 아닌 작품들중 랜덤으로 미리보기 이미지가 뜨지않습니다

버그때문에 그런건가요?

**Comment by KurtBestor** [comment]
`옵션 (Options)` - `설정 (Preferences)...` - `고급 설정` - `DPI 우회` 키셨나요?

**Comment by dwindlepower** [comment]
저도 DPI우회를 켰는데도 오류가 생기면서 안됬는데 https://github.com/ValdikSS/GoodbyeDPI/releases
에서 다운받았더니 됩니다.

**Comment by siwkd2** [comment]
아 dpi우회 체크가 안되어있네요

감사합니다
