### ISSUE TITLE
자동 다운로드가 가능한가요?

### ISSUE THREAD

**Issue by zd-hk** [KurtBestor/Hitomi-Downloader-issues#909]
예를 들어 히토미에서 어떤 작가를 등록해 놓으면 업데이트 될 때마다 다운로드 받는다던가
마나모아에 만화가 올라오면 자동으로 받는다던가 하는 식으로요.
미리 받아 놓고 쾌적하게 보고 싶은데 가능할까요?

**Comment by KurtBestor** [comment]
불가능해요.

**Comment by zd-hk** [comment]
그런 기능 추가도 안되는 건가요ㅠㅠ 알겠습니다ㅠㅠㅠ
