### ISSUE TITLE
겔부루 다운 이미지 갯수 제한문제

### ISSUE THREAD

**Issue by kimnet328** [KurtBestor/Hitomi-Downloader-issues#91]
안녕하세요. 최근에 겔부루에서 이미지들을 다운로드 하려고 URL을 붙여넣기 해서 다운을 받으려고 하는데 이상하게 2000개 제한인지 2000개밖에 다운로드가 되지 않고 있습니다. 제가 받고 싶은 이미지 태그에는 대략적으로 9500가지의 사진이 있어서 다운을 받으려고 하지만 1페이지 부터해서 2000장밖에 받아지지 않고 나머지는 어떻게 받아야하는지 모르겠습니다. 일단 도움말을 보아하니 페이지를 지정해서 다운로드를 받을수 있다고는 하는데 겔부루 같은 경우는 URL에 어떻게 페이지를 넣는지 잘 모르겠네요. 예를 들어서 https://gelbooru.com/index.php?page=post&s=list&tags=1boy 1~50 이렇게 하면 되나요?

**Comment by KurtBestor** [comment]
기본값은 2000개로 정해놓았어요.

앞에서부터 3000개를 다운 받고 싶으면 다음과 같이 하면 돼요:
1. 주소 입력
2. 다운로드 버튼 우클릭 - [페이지 지정 다운로드]
3. "~3000" 입력 후 OK
