### ISSUE TITLE
웹툰사이트 추가 문의드립니다.

### ISSUE THREAD

**Issue by NANARANG** [KurtBestor/Hitomi-Downloader-issues#912]
사실..
사이트추가 해달라고 요청하는게 개발자 입장에서는 얼마나 번거로우실지.. 가늠도 안되지만..
염치불구하고  다음웹툰이 추가될수있는지 문의드려요

네이버웹툰도 항상 잘 다운받아져서, 
업뎃되는 날에 다음웹툰이 추가되지않았을까, 또는 다른사용자분이 요청하지않았을까 싶어
조용히 기다렸는데, 다른분들은 다음웹툰을 이용안하시는건지... 요청글도 없네요

기다리다 지쳐서 요청 한번 해보려구요 ㅎㅎ
다음웹툰도 추가 가능할까요..?

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview
