### ISSUE TITLE
pornhub,xvideos 링크 넣으면 invalid뜹니다

### ISSUE THREAD

**Issue by ahnnton** [KurtBestor/Hitomi-Downloader-issues#913]
Invalid:[pornhub} https://......
이런식으로 나옵니다.  6월 5일까지는 제대로 됐었던걸로 기억합니다.
감사히 잘쓰고있습니다.

**Comment by starfrut** [comment]
goodbyedpi 프로그램 키고 돌려보세요

다운로더에 자체우회되는줄 알았는데 막힌건지 안되고 따로 켜놓고 하니깐 잘되네

**Comment by KurtBestor** [comment]
`옵션 (Options)` - `설정 (Preferences)...` - `고급 설정` - `DPI 우회` 키셨나요?

**Comment by ahnnton** [comment]
설정은 처음 받았을때 이후로 만진적은 없습니다. 
지금은 또 별도의 우회프로그램 없이도 잘 되네요....
일시적인 연결 오류였을 수 도 있는것 같습니다. 다시 문제가 생기면 문의하겠습니다.
감사합니다

**Comment by zephy8181** [comment]
현재 같은 증상을 겪고있습니다. 고급설정에 DPI우회 켠상태, 끈상태, 켜고 goodbyedpi 켠상태, 끄고 goodbyedpi 켠상태 모두 해보았지만 Invalid:[xvideo] https://.... 가 붉게 출력되네요.
