### ISSUE TITLE
기능 추가 요청에 관한 건

### ISSUE THREAD

**Issue by miraclehoshi** [KurtBestor/Hitomi-Downloader-issues#915]
매번 수고가 많으십니다.

1. 닫기 시 자동으로 트레이 이동 기능이 있으면 좋겠습니다.

이젠 히토미 다운로더를 부팅과 함께 켜고 윈도우 업데이트와 함께 종료하는 수준이 되었습니다.
이런 점에서 닫기 버튼을 누르면 종료가 뜨고, 그게 아닌 트레이로 넘기기 위해선 컨트롤 + H를 눌러야만 하는 점은 매우 불편합니다. 종료시 자동으로 트레이 전환 기능을 추가해 주심을 건의드립니다.

2. 검색기 상에서 폴더를 열수 있도록 해 주십시오.
현재 검색기서는 기존에 받아있던 동인지의 폴더를 열 방법이 없습니다.
다운로드 되어 있다고 표시될 경우 다운로드 폴더를 열어 직접 찾아가야 하는 점은 불편합니다.
또한 프로그램 메인에 나오는 동인지가 500건이 넘어 스크롤만으로는 찾기도 힘듭니다.

검색 중 만약 보유중인 파일이 보일경우, 검색기의 목록에서 바로 열 수 있도록 추가해 주시는 것은 어떨까 싶습니다.

검색 목록 좌측 썸네일 이미지를 누를 경우, 이미 다운로드 되어 있는 경우에
갤러리 정보 창이 아닌 다운로드된 폴더가 열리게끔 하는 것도 좋을 것 같습니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

`옵션 (Options)` - `설정 (Preferences)...` - `고급 설정` - `시스템 트레이` 에서 설정할 수 있어요.
다운로드 표시 누르면 폴더 열려요.

**Comment by miraclehoshi** [comment]
문제 없이 정상적으로 잘 됩니다 감사합니다. 2번의 경우 체크표시 누르면 폴더 뜨는걸 이번에 알았습니다 ㅜㅜ 감사합니다
