### ISSUE TITLE
마나모아 다운로드시에

### ISSUE THREAD

**Issue by aksghkqhrl** [KurtBestor/Hitomi-Downloader-issues#916]
하나의 만화가 아닌 한 페이지 전체의 만화를 불러와 다운로드하는건 불가능한가요?

**Comment by aksghkqhrl** [comment]
> 
> 
> 하나의 만화가 아닌 한 페이지 전체에 있는 만화를 불러와 다운로드하는건 불가능한가요?

**Comment by KurtBestor** [comment]
목록 주소를 입력해주세요.
