### ISSUE TITLE
DPI 우회시 에러문구 뜨면서 미리보기 안떠요

### ISSUE THREAD

**Issue by LoveBlonde** [KurtBestor/Hitomi-Downloader-issues#917]
> 
![이향](https://user-images.githubusercontent.com/39547069/59153913-28c6dd80-8aa1-11e9-90ce-57161dd44a2b.png)

이렇게 뜨고 에러문구는 다른 사람들이랑 비슷하게 뜨는거같습니다. 

DPI우회 켰습니다

**Comment by LoveBlonde** [comment]
![이향2](https://user-images.githubusercontent.com/39547069/59154014-d1763c80-8aa3-11e9-9099-89e1ecb80850.png)
에러문구입니다

**Comment by KurtBestor** [comment]
재부팅해도 그대로인가요?

**Comment by LoveBlonde** [comment]
> 재부팅해도 그대로인가요?

네 그대로입니다 다른 분들은 재부팅하면 제대로되던데 저만 유독 이런 증상이 지속되네요

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by LoveBlonde** [comment]
> 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

잘됩니다 감사합니당 close 해두겠습니다.
