### ISSUE TITLE
크롤러 전용 미니 서버 완

### ISSUE THREAD

**Issue by kikinet88** [KurtBestor/Hitomi-Downloader-issues#918]
지금 크롤러 자체가 메모리 리소스를 많이 먹는걸로 보였습니다.
그래서 지금 슬림 PC 예전에 만들다 만것에다가
아래와 같이 조립 해서 테스트를 위해 대기중입니다.

CPU: i3 4세대
RAM: 16GB 8x2
SSD: Msata 64GB (S3)

저전력 으로 사용하여 120W 아답터를 사용합니다.
윈도우는 순정 윈10 IOT 로 설치 했습니다.

장시간 운용 과 더불어 저전력이라 현제 운용하는 시스템보단
환경이 더 좋을듯 합니다.

관리자님 생각해보시고 답변 주시면 이메일로 어드민 드리겠습니

**Comment by KurtBestor** [comment]
네 충분한 것 같네요. 감사합니다. 메일 주세요.
