### ISSUE TITLE
수고많으십니다 개발자님 데이터누락이 있는거 같습니다

### ISSUE THREAD

**Issue by ahruddid2** [KurtBestor/Hitomi-Downloader-issues#919]
기본데이터 다운로드 한뒤에 검색이 잘되지만..

옛날자료가 검색으로 나오질 않는군요.. 

akatsuki myuuto 이 작가님의 korean (한국어) 자료가 히토미사이트에서는 제대로 뜨지만

프로그램으로 검색하였을때 4개밖에 뜨지않습니다.

원래는 최소 10개이상 떠야되는데 말이죠

다른작가도 마찬가지입니다.. 데이터누락이 생각보다 많습니다. 

해결방법이 있다면 알려주세요.

**Comment by KurtBestor** [comment]
![image](https://user-images.githubusercontent.com/14768120/59180509-1bdce380-8ba0-11e9-97e5-fc06453454ee.png)

테스트 해보니 저는 잘 뜨네요. 검색기 스크린샷으로 찍어서 보여주세요.

**Comment by ahruddid2** [comment]
![image](https://user-images.githubusercontent.com/51593188/59200150-8e66b700-8bd2-11e9-8194-3762071e1cbf.png)

**Comment by ahruddid2** [comment]
![image](https://user-images.githubusercontent.com/51593188/59200228-b7874780-8bd2-11e9-9682-d9c3f42ef603.png)
요렇게 나옵니다..

**Comment by KurtBestor** [comment]
`loli` 태그가 있는 게 안 나오는 것 같은데 `옵션` - `설정` - `히토미` - `제외 태그` 가 어떻게 되어있는지 확인해주세요.

**Comment by ahruddid2** [comment]
맞네요.. 죄송합니다 ㅠㅠ 저의 불찰입니다. 감사합니다
