### ISSUE TITLE
2.2a 때와 지금 새버전과 이게 오류 인건지..

### ISSUE THREAD

**Issue by kikinet88** [KurtBestor/Hitomi-Downloader-issues#92]
오랜만에 뵙겠습니다.. -ㅁ-

2.2a 버젼때 보면
히토미 다운받을시  # manga 식으로 폴더가 생성 됬어는대

이번 버젼 에서는 폴더가 생성되지 않고
파일 명이 바뀌 더라구요..

저만 그런건지.. 아니면 버젼에서 바뀐건지..
궁금 합니다..

그리고 업데이트 계속 뜨는걸 막는 방법은 없을까요?
솔직히 구버젼이 저에게 더 좋던... -ㅁ-;;

**Comment by KurtBestor** [comment]
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

고친 버전입니다. 테스트 부탁드려요.

이전 버전이 더 좋다고 하셨는데, 어떤 면에서 그런지 알 수 있을까요?

**Comment by newtype0222** [comment]
테스트 버전은 정상적으로 작동합니다. 피드백 감사합니다.
