### ISSUE TITLE
삭제된 데이터 검색이 안됩니다

### ISSUE THREAD

**Issue by comsclub** [KurtBestor/Hitomi-Downloader-issues#921]
매번 수고하십니다

최근에 올라왔던 작품들이 다시 검색해보니 검색창에서 검색이 안되길래 문의드립니다

검색창에서 삭제된 데이터 다운로드로 최신화는 당연히 했습니다

구체적으로 검색이 안되는것들로는 1426111, 1426753, 1424839 등등입니다

그런데 이것들이 프로그램상의 검색으로는 안나오는데

galleries/1426111.html

이런식의 주소를 복사 붙여넣기 해서 다운받는건 되는건 또 됩니다

요컨데 검색창에선 안뜨는데 다운받는건 가능한 상황입니다

제가 설정을 뭘 잘못건드려서 그런건지 아니면 프로그램상의 문제가 있는건지 궁금합니다

항상 감사합니다

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/752#issuecomment-484909383
