### ISSUE TITLE
클릭 문제

### ISSUE THREAD

**Issue by sae193** [KurtBestor/Hitomi-Downloader-issues#922]
선생님 안녕하세요

프로그래밍을 배우는 학생입니다

다름이 아니라 제가 주소를 자동으로 입력하는 프로그램을 만들었습니다.

( 사이트 주소 복사 - 탭 닫기 - 마우스 커서 이동 - 왼쪽 마우스 클릭 - 붙여넣기 -엔터 - 반복)

하지만 히토미다운로더 왼쪽 마우스 클릭이 먹지를 않아서 

왼쪽 마우스가 아닌 오른쪽 마우스 클릭 - P 입력 - 엔터 로 바꾸어 실행 했는데 되지 않았습니다.

크롬과 유토렌트에서 실험했을 때는 잘 되었는데 히토미다운로더에서는 잘 되지 않아

혹시 일부러 막아두었는지 궁금해서 글을 쓰게 되었습니다.

(
덕분에 많은 양의 자료를 빠르게 다운받을 수 있었습니다. ^^
정말 감사합니다.
)

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/879
