### ISSUE TITLE
유투브 다운로드시 변환 과정이 안됩니다..

### ISSUE THREAD

**Issue by ShizuKR** [KurtBestor/Hitomi-Downloader-issues#923]
유투브 다운로드를 받으면, 잘 받고 마지막에 변환하는 과정에서

[현재 PC에서는 이 앱을 실행할 수 없습니다. PC 버전을 찾으려면 소프트웨어 관리자에게 문의하세요]

라는 메세지가 나옵니다.

버전은 2.6c구요...

타 사이트 영상들은 잘 되는데 이상하게 유투브만 안되네요...

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/881

**Comment by ShizuKR** [comment]
temp 폴더는 없고 tmp 폴더만 있는데, 이 안에 ffmpeg 파일은 없습니다... 컴퓨터 전체 검색을 해보니 하이퍼스핀 폴더 안에 있긴 하던데 찾으시는게 이건 아닐거 같구요...

운영체제는 윈10 64비트 입니다

**Comment by KurtBestor** [comment]
`Ctrl + Alt + C` 눌러서 콘솔 띄우고 다음 입력한 다음 `Enter` 눌러서 나온 내용 알려주세요:
```
__import__('ffmpeg').exe
```

**Comment by ShizuKR** [comment]
[ffmpeg.zip](https://github.com/KurtBestor/Hitomi-Downloader-issues/files/3292675/ffmpeg.zip)

**Comment by ShizuKR** [comment]
사용자 폴더 검색해보니 파일이 하나 나오고 용량도 비슷한거 같아서 이거 올립니다... 일단 저는 기존 프로그램 삭제하고 최신버전 재설치를 해볼게요.. 감사합니다.

**Comment by ShizuKR** [comment]
1080p는 안되는데 720p는 되네요.. 부분 해결이긴 한데 잘 쓰겠습니다..
