### ISSUE TITLE
웹툰 사이트 추가해줄 수 있나요?

### ISSUE THREAD

**Issue by ajsrkfmfgkwk** [KurtBestor/Hitomi-Downloader-issues#924]
다음웹툰도 네이버웹툰처럼 다운로드해서 볼 수 있게 할 수 있나요?

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/912

**Comment by KurtBestor** [comment]
https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/912#issuecomment-537749598
