### ISSUE TITLE
xvideos 링크 invalid 출력문제

### ISSUE THREAD

**Issue by tdi2020** [KurtBestor/Hitomi-Downloader-issues#925]
아래쪽에 이슈가 있지만 질문자분이 해결되신 것 같고,저는 동일 증상을 오늘 겪어서 올립니다.

-영상을 정상 다운로드 하던 때의 상황은, goodbyedpi가 켜져있고, 고급설정에 DPI우회도 켜져있었습니다.

-xvideo에서 여러영상을 받던 중, 몇개 이상으로 대기중인 링크들이 모두 붉게 Invalid 되었습니다.
(저는 pornhub 테스트결과 잘 작동하고 있습니다.)

-고급설정에 DPI우회 켠상태 + 끈상태 + 켜고 goodbyedpi 켠상태 + 끄고 goodbyedpi 켠상태 
네가지 경우를 모두 테스트 해보았지만 Invalid:[xvideo] https://.... 가 붉게 출력되네요.

**Comment by tdi2020** [comment]
존경하는 개발자님! 
제가 테스트 해본 결과 업로더의 페이지로 들어가 (ex = https://www.xvideos.com/profiles/업로더아이디) 
업로더가 올린 동영상의 썸네일 우클릭 후 주소를 긁어올 경우, [ xvideos.com/profiles/경로 ] 로 주소가 읽어지면서 invalid가 뜨고 다운이 되지 않는것을 확인하였습니다. 
(신기한건... 그 방식으로 추가했을때도 되는건 됐다는건데 왜그런지는 잘 모르겠습니다.)

아무튼 해결하려면 현재로서는 업로더 페이지 상의 썸네일에서 바로 우클릭으로 주소를 긁는게 아니라, 
일일이 썸네일을 눌러서 들어간 후 주소를 긁으면 일단 다운로드가 작동되며 
다시 해당 업로더 페이지로 가서 또 그걸 반복하면 일단 영상 다운로드는 됩니다.

**Comment by KurtBestor** [comment]
해당 작업 `마우스 우 클릭` - `정보... (I)` 눌러서 나온 내용 보여주세요.

**Comment by tdi2020** [comment]
Invalid : [xvideo] https://www.xvideos.com / prof-video-click / upload / forss008 / 27369843 / asia_fox_160606_0420_couple_chaturbate

version: 2.6c
platform: Windows-7-6.1.7601-SP1
gal_num: https://www.xvideos.com/prof-video-click/upload/forss008/27369843/asia_fox_160606_0420_couple_chaturbate
dir: 
zip: 
type: xvideo
artist: None
url: https://www.xvideos.com/prof-video-click/upload/forss008/27369843/asia_fox_160606_0420_couple_chaturbate
valid: False
done: False
range: None
range_p: None
single: True
time: 1560501001.07 (Jun 14)
tags: []
goodbyedpi: True
lock: False


[Gallery]
None


[File Names]



[URLs]



[Messages]
stop
Traceback (most recent call last):
File "utils", line 423, in __init__
File "xvideo_downloader", line 46, in id
File "xvideo_downloader", line 13, in get_id
IndexError: list index out of range

Fail: xvideo

stop
done : https://www.xvideos.com/prof-video-click/upload/forss008/27369843/asia_fox_160606_0420_couple_chaturbate

**Comment by tdi2020** [comment]
그리고 vimeo 영상도 다운로드가 잘 되다가 Invalid가 뜨면서 안되기 시작해서 이것도 아래에 정보 남겨놓겠습니다.

**Comment by tdi2020** [comment]
Invalid : [vimeo] https://vimeo.com / 241327220

version: 2.6c
platform: Windows-7-6.1.7601-SP1
gal_num: https://vimeo.com/241327220
dir: 
zip: 
type: vimeo
artist: None
url: https://vimeo.com/241327220
valid: False
done: False
range: None
range_p: None
single: True
time: 1560500900.39 (Jun 14)
tags: []
goodbyedpi: True
lock: False


[Gallery]
None


[File Names]



[URLs]



[Messages]
fuckkk...
Traceback (most recent call last):
File "constants", line 599, in wrapper
File "vimeo_downloader", line 57, in get_video
TypeError: sequence index must be integer, not 'str'

stop
Traceback (most recent call last):
File "utils", line 522, in start
File "utils", line 566, in start_
File "vimeo_downloader", line 35, in read
File "constants", line 616, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 599, in wrapper
File "vimeo_downloader", line 57, in get_video
TypeError: sequence index must be integer, not 'str'


Fail: vimeo

done : https://vimeo.com/241327220

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

Vimeo의 경우는 로그인해야 볼 수 있는 거라 현재는 안 돼요.

**Comment by tdi2020** [comment]
아 그렇군요! 정말 잘 됩니다!! ㅠㅠ 항상 감사합니다!!
