### ISSUE TITLE
이전 버젼에 대한 관리자님의 질문 답변

### ISSUE THREAD

**Issue by kikinet88** [KurtBestor/Hitomi-Downloader-issues#93]
1. 안정성
2.0 ~ 2.2 a 까지는 실질적으로 안정성이 좋음
주 사용처는 일단 히토미 와 픽시브 

다운받을시 폴더명 () 코드 제거하면 중복 된건 미완료로서 사용
주로 2.2 버젼에서는 이문제로 튕김은 없음
신버젼에서 튕김현상 확인 (이유는 .. 음.. 아마 중복 된 파일명 과의 오류?)

2. 윈도우 및 에뮬 윈도우 호환성
새버젼은 제가 아직 다 써본게 아니라 모르겠지만
유독 1.9 부터 2.2 까지 중에 2.2 버젼은 타 운영체제에서 호환성이 좋았음
즉 리눅스 에서 윈도우 에뮬 사용해서 쓸경우
다른버젼은 튕기거나 하는대 2.2 부터는 튕기지 않음(간혹 시스템다운 증상도...)

일단 제가 사용 할때 시스템 사양은 이렇습니다.
나스 겸 데이터 FTP 형으로 운영 하기에
사양은 E5-2670 v2 x 2 // DDR3 ECC REG 90GB // HDD 6TB or PCIE SSD 1TB 
문제는 프로그램 상에서
자료 목록 불러오기중 대략 1천개가 넘어가면 다운되는 증상이 간혹 발생합니다.
자주 그러는건 아니고 간혹 이긴한대
신버젼 에서부터는 거의.. 응답없음 으로 떠서 좀 난처 했습니다..

현제 사용중인 운영체제는 윈서버 2016 과 윈10 프로 웤스 입니다 

윈서버 2012 에서는 이런 증상이 없던데.. 다시 다운그레이드 할까 생각중...

하여튼 제작 해주셔서 감사합니다
예전에 티카페 라는 곳에서 일반 제작자 분이 간단하게 만들어서 주셨는대
어느날 갑자기 제작자분이 사라지시고..
쓸만한 프로그램 찾다가.. 딱 이거다 하는 마음이...
후원 이나 이런거 있으면 하겠...
그냥 공짜로 쓰면서 그럴려니 미안해서... ㅠㅠ

**Comment by KurtBestor** [comment]
목록 하나에 대략 메모리 2MB 정도가 들고, 이 프로그램은 32비트용 프로그램이라 2기가 정도 밖에 메모리를 쓰지 못해요. 그래서 이론상 천개 넘게는 저장 / 불러오기가 안될거예요. 저장하고 불러올 때 데이터를 생각하면 그 반절인 500개를 넘기지 않는 게 좋아요.
필요 없는 건 목록에서 지우시는 게 좋을 것 같아요.

후원은 생각해 봤는데, 떳떳한 프로그램이 아니다 보니 양심상 꺼려지네요. 마음만 감사히 받을게요.

**Comment by kikinet88** [comment]
64비트용 의뢰 드립니다!!!!
흐흐흐

2018년 5월 9일 (수) 14:31, Kurt Bestor <notifications@github.com>님이 작성:
