### ISSUE TITLE
페이지 주소를 입력해도 전체 다운로드가 안됩니다.

### ISSUE THREAD

**Issue by aksghkqhrl** [KurtBestor/Hitomi-Downloader-issues#932]
![0001](https://user-images.githubusercontent.com/47558641/59564717-1cd0b200-9085-11e9-8b14-48372bced7e5.png)

Invalid : [manamoa] https://manamoa4.net / bbs / board.php?bo_table=manga

version: 2.6c
platform: Windows-10-10.0.17763
gal_num: https://manamoa4.net/bbs/board.php?bo_table=manga
dir: 
zip: 
type: manamoa
artist: None
url: https://manamoa4.net/bbs/board.php?bo_table=manga
valid: False
done: False
range: None
range_p: None
single: True
time: 1560690745.64 (Jun 16)
tags: []
goodbyedpi: True
lock: False

[Gallery]
None

[File Names]

[URLs]

[Messages]
Cloudflare protection
stop
Traceback (most recent call last):
File "utils", line 419, in __init__
File "manamoa_downloader", line 82, in init
File "manamoa_downloader", line 61, in get_title_page
AttributeError: 'NoneType' object has no attribute 'findAll'

Fail: manamoa

stop
done : https://manamoa4.net/bbs/board.php?bo_table=manga

말씀하신 그대로 입력을 하였는데 안되네요 .. ㅠㅠ! 천천히 확인 부탁드리겠습니다

**Comment by KurtBestor** [comment]
다음과 같이 목록 주소를 입력해주세요: https://manamoa.net/bbs/page.php?hid=manga_detail&manga_id=9972
