### ISSUE TITLE
소설 다운시 여러개의 개별 다운이 아닌 통합 1개 파일 다운기능 추가 건의드립니다

### ISSUE THREAD

**Issue by q2343454** [KurtBestor/Hitomi-Downloader-issues#936]
소설가가 되자 사이트나 https://syosetu.com/
녹턴 노벨 사이트 등등 https://noc.syosetu.com/

소설 다운 사이트들에서 다운시에 소설들이 개별적으로 다운됩니다

작가가 10편을 연재하면 10개의 텍스트 파일로 다운되는 걸
1개의 텍스트 파일로 합쳐서 통합본으로 다운 받을 수 있는 기능이 있었으면 합니다

통합본으로 한번에 합치면 번역기 돌리기도 편하고 한번에 읽기도 편하니
통합본 기능이 있었으면 좋겠습니다

**Comment by KurtBestor** [comment]
모두 다운로드 된 후에 `[merged] ~.txt` 라는 이름의 통합본도 생겨요.

**Comment by q2343454** [comment]
헉 이미 있는 기능이었군요 감사합니다
