### ISSUE TITLE
기본 데이터 다운로드가 잘 안되네요.

### ISSUE THREAD

**Issue by Revena** [KurtBestor/Hitomi-Downloader-issues#938]
안녕하세요. 항상 감사히 쓰고 있습니다.

요 며칠 동안 데이터 다운로드를 할 때 다운로드 진행이 안되고 있습니다.

어떨때는 또 다운로드가 진행이 되긴 되는데, 대부분이 이런 상태 입니다.
도움과 해결 부탁드립니다. ( _ _)

![190619_00](https://user-images.githubusercontent.com/39665056/59764304-7bd93580-92d6-11e9-8fc2-b387fa4c88cf.PNG)

**Comment by kikinet88** [comment]
음 저는 사용중 이상이 없는대..
혹시 우회 프로그램 쓰고 계신지 궁금합니다.
아니면 프로그램을 삭제후 다시 받아 보시는것도..
현제로선 크롤러서버 잘 돌아가는 중입니다

**Comment by Revena** [comment]
우회 프로그램은 딱히 사용하진않습니다.
다만 사용할때 히토미다운로더 옵션에선 꺼놓고, 따로 굿바이dpi 를 실행해서 사용중입니다.
윈도우 10 포멧한지 얼마안됐고, 잘 사용하다 최근 몇일사이에 이러해서..
글쎄요 뭐가 문제인지는 모르겠네요.

일단 말씀주신대로 프로그램을 다시 받아서 사용하는데
지금 리플 단 시점에선 다운이 잘 받아집니다. 이대로 잘 됐으면 좋겠네요.

**Comment by Revena** [comment]
음... 지금은 또 안받아지네요.
지금시간대에만 안받아지는 걸까요 흠.....뭐지...

**Comment by Revena** [comment]
21:00 ~ 24:00 시간대에 다운로드가 안되는것 같습니다.
