### ISSUE TITLE
네이버 웹툰이 다운이 안됩니다

### ISSUE THREAD

**Issue by geniussjt** [KurtBestor/Hitomi-Downloader-issues#939]

**Comment by geniussjt** [comment]
Invalid : [navertoon] https://comic.naver.com / webtoon / list.nhn?titleId=718707&weekday=thu

version: 2.6c
platform: Windows-10-10.0.17763
gal_num: https://comic.naver.com/webtoon/list.nhn?titleId=718707&weekday=thu
dir: 
zip: 
type: navertoon
artist: None
url: https://comic.naver.com/webtoon/list.nhn?titleId=718707&weekday=thu
valid: False
done: False
range: None
range_p: None
single: True
time: 1560955198.7 (Jun 19)
tags: []
goodbyedpi: True
lock: False


[Gallery]
None


[File Names]



[URLs]



[Messages]
stop
Traceback (most recent call last):
File "utils", line 419, in __init__
File "navertoon_downloader", line 46, in init
File "constants", line 616, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 599, in wrapper
File "navertoon_downloader", line 126, in get_pages
Exception: artist not found


Fail: navertoon

stop
done : https://comic.naver.com/webtoon/list.nhn?titleId=718707&weekday=thu

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by geniussjt** [comment]
잘 됩니다 감사합니다^^
