### ISSUE TITLE
E-Hentai 다운로드가 안됩니다.

### ISSUE THREAD

**Issue by kimnet328** [KurtBestor/Hitomi-Downloader-issues#94]
안녕하세요. 최근에 사용중에 다른 사이트들은 다운로드에 딱히 문제가 없는데 이상하게 E-Hentai만 다운로드가 안되는 현상이 있었습니다. 처음에는 IP밴당한줄 알고 IP도 바꿔보고 여러짓을 다 해봤는데 다운로드가 안됩니다. 정확히 말하자면 계속 읽는중에만 멈춰있습니다. 무엇이 문제인가요?

**Comment by KurtBestor** [comment]
다른 버전은 되나요?

**Comment by KurtBestor** [comment]
오랫동안 답이 없으셔서 닫습니다
