### ISSUE TITLE
jmana 다운로드가 되지 않습니다.

### ISSUE THREAD

**Issue by luku756** [KurtBestor/Hitomi-Downloader-issues#944]
https://jmana19.com/book/%EB%84%A4%20%EB%B2%88%EC%A7%B8%EB%8A%94%20%EC%8B%AB%EC%9D%80%20%EC%A3%BD%EC%9D%8C%EC%86%8D%EC%84%B1%20%EB%A7%88%EC%88%A0%EC%82%AC

위 만화를 다운받으려 했는데 되지 않습니다.
현재 제이마나 들어가서 보이는 몇가지 만화를 전부 시도해 봤는데 다운이 되지 않네요...

확인해주시면 감사하겠습니다.

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/894
