### ISSUE TITLE
이거는 무슨 오류인가요?

### ISSUE THREAD

**Issue by aksghkqhrl** [KurtBestor/Hitomi-Downloader-issues#946]
![0001](https://user-images.githubusercontent.com/47558641/59895796-ded6e380-9420-11e9-9cea-72b7a9c27a73.png)

다운로드 하면서 다운로드 했던 목록을 편집하면 팅기는 오류가 있는거같아요

![0003](https://user-images.githubusercontent.com/47558641/59896280-ec8d6880-9422-11e9-96a3-af8bbc12736a.png)
![0004](https://user-images.githubusercontent.com/47558641/59896281-ec8d6880-9422-11e9-884f-f4bdffb73d40.png)

저 에러가 뜬 이후로 재부팅하고 다시 시작했을때부터는 다운로드가 안되네요

**Comment by KurtBestor** [comment]
참고해주세요: #848
