### ISSUE TITLE
[건의]  저장에 대해

### ISSUE THREAD

**Issue by Karl-K** [KurtBestor/Hitomi-Downloader-issues#948]
관리자님 저장 기능을 통한 검색에 대해 생각을 해보았는데, 다운로드 중(또는 끝난) 목록에 있는 것들 뿐 아니라 즐겨찾기에 있는 목록(작가이름 등)도 저장되게 해주실 수는 없나요?

감사합니다.

**Comment by KurtBestor** [comment]
이해가 안 되는데 좀 더 자세히 설명해주세요. 검색기 즐겨찾기에 있는 목록이라면 이미 저장돼요.

**Comment by Karl-K** [comment]
음.. 작가 추천을 사용해보려 하니 저장 폴더에 있는 작품들을 분석하게 되어있던데, 제가 못 찾은 것인지 모르겠지만 검색기 즐겨찾기는 내보내면 .bmk 파일로 저장되는데 저장 폴더에서 받아올 수 있는 형식은 .txt더군요. 어떻게 해야 하는지 방법을 알려주실 수 있나요?

**Comment by KurtBestor** [comment]
즐겨찾기는 내보내고 가져오는 기능만 있지, 작품 번호 목록을 txt 파일로 저장하는 기능은 없어요.
