### ISSUE TITLE
작가 추천 기능 향상을 위해 약간 추가기능이 필요합니다

### ISSUE THREAD

**Issue by aria1th** [KurtBestor/Hitomi-Downloader-issues#95]
다운로드 받은 다음 정리를 따로 하거나 외장 하드에 옮겨두어서 신경망 학습 데이터가 부족할 수 있는데, 이를 해결하려면 두가지가 있을 것 같습니다.

1. 따로 참조 목록을 txt 등으로 저장해서 그곳에 추가할 수 있게 함
2. ( 숫자 ) 형식의 빈 폴더를 만들어서 인식

2번은 대충 구현했습니다. 
[눈동자_머신러닝용.zip](https://github.com/KurtBestor/Hitomi-Downloader-issues/files/1987151/_.zip)

1번은 직관적이지 않아서 좀 그렇긴 한데, 비슷한 추가 기능이 있으면 좋겠습니다.

**Comment by KurtBestor** [comment]
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

테스트 부탁드려요.
