### ISSUE TITLE
소설가가 되자 파일 오류 관련 문의드립니다

### ISSUE THREAD

**Issue by homagood** [KurtBestor/Hitomi-Downloader-issues#950]
이 소설인데... https://ncode.syosetu.com/n6655fk/

최신 버전으로 하면 다운로드 자체가 멈춰버리고 혹시나 해서

https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/788
여기서 오류 수정된 버전으로 해봐도 통합이 안 되네요. 

version: 2.6c
platform: Windows-10-10.0.16299
gal_num: https://ncode.syosetu.com/n6655fk/
dir: hitomi_downloaded_syosetu\[QI] バニーガールエルフを啜るレオタードヴァンパイアを見るメイドマーメイドとチャイナドレスサキュバスに育てられた前世が男のYシャツ縞々パンツフェアリーエンジェ
zip: 
type: syosetu
artist: None
url: https://ncode.syosetu.com/n6655fk/
valid: False
done: True
range: None
range_p: None
single: False
time: 1561208531.12 (Jun 22)
tags: []
goodbyedpi: True
lock: False
---
[Messages]
get_session
single: False
Traceback (most recent call last):
File "utils", line 674, in start_
File "syosetu_downloader", line 125, in post_processing
IOError: [Errno 2] No such file or directory: u'C:\\Users\\awj\\Downloads\\hitomi_downloader_GUI_test (2)\\hitomi_downloaded_syosetu\\[QI] \u30d0\u30cb\u30fc\u30ac\u30fc\u30eb\u30a8\u30eb\u30d5\u3092\u555c\u308b\u30ec\u30aa\u30bf\u30fc\u30c9\u30f4\u30a1\u30f3\u30d1\u30a4\u30a2\u3092\u898b\u308b\u30e1\u30a4\u30c9\u30de\u30fc\u30e1\u30a4\u30c9\u3068\u30c1\u30e3\u30a4\u30ca\u30c9\u30ec\u30b9\u30b5\u30ad\u30e5\u30d0\u30b9\u306b\u80b2\u3066\u3089\u308c\u305f\u524d\u4e16\u304c\u7537\u306eY\u30b7\u30e3\u30c4\u7e1e\u3005\u30d1\u30f3\u30c4\u30d5\u30a7\u30a2\u30ea\u30fc\u30a8\u30f3\u30b8\u30a7\\[0005] \u9762\u767d\u3044\u8a71\u306e\u6761\u4ef6(\u500b\u4eba\u7684\u504f\u898b\u610f\u898b)1\u3064\u3001fair\u3064\u307e\u308a\u8aad\u8005\u3082\u7b46\u8005\u306b\u3082\u516c\u6b63\u306a\u60c5\u5831\u304c\u3042\u308b\u30022\u3064\u3001joy\u3064\u307e\u308a\u5f79\u8005\u304c\u697d\u3057\u305d\u3046\u30023\u3064\u3001test\u3064\u307e\u308a\u8a66\u7df4\u304c\u3042\u308b\u3002\u304a\u307e\u3051\u3067\u30a8\u30ed\u3044\u3068\u304b\u5143\u6c17\u306b\u306a\u308b\u3068\u304b\u4f7f.txt'

최신 버전은 로그를 띄울 수 없는 것 같아 구버전 로그를 적었습니다.
이것도 파일 이름 너무 길어서 나타나는 문제인가요??

**Comment by KurtBestor** [comment]
https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/950 에 나와있는대로 테스트 버전으로 시도해서 나오는 작업 정보를 보여주세요.

로그가 안 띄워진다는 게 어떤 의미인가요?
