### ISSUE TITLE
안녕하세요 니코동 영상이 다운 안됩니다.

### ISSUE THREAD

**Issue by tizmvkdnj** [KurtBestor/Hitomi-Downloader-issues#951]
이 영상을 다운 받을려 하는데 다운이 안되네요.
혹시 몰라 다른 영상 10개 정도를 받아 보았는데도 안됩니다.
그림 영상류라 최소 1시간에서 최대 6시간짜리 입니다.
항상 애용하고 있습니다

Invalid : [nico] https://live2.nicovideo.jp / watch / lv320705509?ref=community

version: 2.6c
platform: Windows-10-10.0.17134
gal_num: https://live2.nicovideo.jp/watch/lv320705509?ref=community
dir: 
zip: 
type: nico
artist: None
url: https://live2.nicovideo.jp/watch/lv320705509?ref=community
valid: False
done: False
range: None
range_p: None
single: True
time: 1561291182.94 (Jun 23)
tags: []
goodbyedpi: True
lock: False

[Gallery]
None

[File Names]

[URLs]

[Messages]
nico retry...
nico retry...
Could not retrieve video info
stop
Traceback (most recent call last):
File "utils", line 522, in start
File "utils", line 566, in start_
File "nico_downloader4", line 75, in read
File "nico_downloader4", line 95, in get_video
File "nndownload", line 345, in request_video
FormatNotAvailableException: Could not retrieve video info

Fail: nico

done : https://live2.nicovideo.jp/watch/lv320705509?ref=community

**Comment by KurtBestor** [comment]
니코니코 생방송은 지원하지 않아요.
