### ISSUE TITLE
마나모아 다운로드 안됩니다

### ISSUE THREAD

**Issue by glrmfoa** [KurtBestor/Hitomi-Downloader-issues#954]
읽는 중... 마왕님 리트라이! / 마왕님 리트라이! 10화 (1 / 1)

version: 2.6c
platform: Windows-10-10.0.18362
gal_num: https://manamoa8.net/bbs/board.php?bo_table=manga&wr_id=775947
dir: 
zip: 
type: manamoa
artist: 미노타케 아마루
url: https://manamoa8.net/bbs/page.php?hid=manga_detail&manga_id=10166
valid: True
done: False
range: None
range_p: None
single: False
time: 1561441222.83 (Jun 25)
tags: []
goodbyedpi: True
lock: False

[Gallery]
None

[File Names]

[URLs]

[Messages]
redirect: https://manamoa8.net/bbs/page.php?hid=manga_detail&manga_id=10166
dirFormat: title
[seed] 마왕님 리트라이! 10화 301650
wait... 마왕님 리트라이! 10화

읽는 중 만 뜨고 다운이 안됩니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by tlzmflt** [comment]
테스트로 해 봤는데 안됩니다.

**Comment by glrmfoa** [comment]
됩니다 감사합니다.
