### ISSUE TITLE
히토미사이트에서 다운로드 받다보면 블루스크린이 뜨거나 컴퓨터가 강제 재부팅이 됩니다.

### ISSUE THREAD

**Issue by dlfmadjqtdma0** [KurtBestor/Hitomi-Downloader-issues#955]
안녕하세요.
좋은프로그램 정말 잘쓰고 있습니다. 감사합니다.
근데 다름이아니라, 프로그램을 사용하다보니 문제가 발생했습니다.

히토미 다운로더를 사용하여 히토미 사이트에있는 만화를 다운로드 하다보면 강제 재부팅이 되거나 블루스크린이 뜰때가 있습니다.
주로 나오는 블루스크린 코드는 whea_uncorrectable_error 혹은 DPC_WATCHDOG_VIOLATION 입니다.
문제가 계속 발생하여, 메인보드 교체하고 렘 교체하였습니다.
파워는 슈퍼플라워 750w입니다. 뻥파워 아닙니다.
그런데도 동일증상이네요.
혹시 뭐가 문제인지 알수있을까요
윈도우도 포맷후 재설치해봤습니다.

그리고 히토미 다운로더 사용할때 하나 다운받고 다운 완료되면 다시 다른하나 다운받고 이런식으로 다운로드해야하나요
아니면 그냥 한꺼번에 동시에 다운로드 받아도 되는건가요
전자처럼하나 후자처럼하나 블루스크린이 발생하는건 똑같지만 어떤식으로 다운받아야 좋은지 알수있을까요?

그리고 히토미 다운로더 hdd에 두고 사용하는게 좋나요 ssd에 두고서 사용하는게 좋나요?

**Comment by KurtBestor** [comment]
원인은 재현해볼 수 없어서 모르겠네요.
동시에 다운로드해도 문제 없어요.
HDD / SSD 는 딱히 상관 없어요.

**Comment by zxcvbmm** [comment]
블루스크린은 원인이 정말 각양각색이고 전문가라도 자세한 로그가 없으면 해결이 불가능합니다. 제가 추천드리는 방법은 윈도우를 재설치하시거나 버츄얼박스같은 가상프로그램을 쓰는것입니다. 윈도우 재설치로 솔직히 해결될듯합니다.
