### ISSUE TITLE
마나모아가 중간에 다운로드가 중단됩니다

### ISSUE THREAD

**Issue by Renian2** [KurtBestor/Hitomi-Downloader-issues#956]
읽는 중... [후쿠다 신이치] 그 장난감 인형은 사랑을 한다 / 그 장난감 인형은 사랑을 한다 4화 (4 / 26)

version: 2.6c
platform: Windows-10-10.0.17134
gal_num: https://manamoa8.net/bbs/page.php?hid=manga_detail&manga_id=10095
dir: 
zip: 
type: manamoa
artist: 후쿠다 신이치
url: https://manamoa8.net/bbs/page.php?hid=manga_detail&manga_id=10095
valid: True
done: False
range: None
range_p: None
single: False
time: 1561462958.53 (Jun 25)
tags: []
goodbyedpi: True
lock: False

[Gallery]
None

[File Names]

[URLs]

[Messages]
dirFormat: [artist] title
[seed] 그 장난감 인형은 사랑을 한다 1화 0
[seed] 그 장난감 인형은 사랑을 한다 2화 0
[seed] 그 장난감 인형은 사랑을 한다 3화 0
[seed] 그 장난감 인형은 사랑을 한다 4화 34630
[seed] 그 장난감 인형은 사랑을 한다 4화 34630
[seed] 그 장난감 인형은 사랑을 한다 4화 34630

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by Renian2** [comment]
위에거는 해결됬는데 다른것을 또 다운받으려하니 또 생깁니다.


Invalid : [manamoa] https://manamoa9.net / bbs / page.php?hid=manga_detail&manga_id=1507

version: 2.6c
platform: Windows-10-10.0.17134
gal_num: https://manamoa9.net/bbs/page.php?hid=manga_detail&manga_id=1507
dir: 
zip: 
type: manamoa
artist: 아카사카 아카
url: https://manamoa9.net/bbs/page.php?hid=manga_detail&manga_id=1507
valid: False
done: False
range: None
range_p: None
single: False
time: 1561630724.81 (Jun 27)
tags: []
goodbyedpi: True
lock: False


[Gallery]
None


[File Names]



[URLs]



[Messages]
dirFormat: [artist] title
[seed] 카구야님은 고백 받고 싶어 0-1화 0
[seed] 카구야님은 고백 받고 싶어 0-2화 0
[seed] 카구야님은 고백 받고 싶어 0-3화 0
[seed] 카구야님은 고백 받고 싶어 0-4화 0
[seed] 카구야님은 고백 받고 싶어 0-5화 0
[seed] 카구야님은 고백 받고 싶어 0-6화 0
[seed] 카구야님은 고백 받고 싶어 0-7화 0
[seed] 카구야님은 고백 받고 싶어 0-8화 0
[seed] 카구야님은 고백 받고 싶어 0-9화 0
[seed] 카구야님은 고백 받고 싶어 0-10화 0
[seed] 카구야님은 고백 받고 싶어 특별편 0
[seed] 카구야님은 고백 받고 싶어 1화 0
[seed] 카구야님은 고백 받고 싶어 2화 0
[seed] 카구야님은 고백 받고 싶어 3화 0
[seed] 카구야님은 고백 받고 싶어 4화 0
[seed] 카구야님은 고백 받고 싶어 5화 0
[seed] 카구야님은 고백 받고 싶어 6화 0
[seed] 카구야님은 고백 받고 싶어 7화 0
[seed] 카구야님은 고백 받고 싶어 8화 0
[seed] 카구야님은 고백 받고 싶어 9화 0
[seed] 카구야님은 고백 받고 싶어 10화 0
[seed] 카구야님은 고백 받고 싶어 10.5화 0
[seed] 카구야님은 고백 받고 싶어 11화 0
[seed] 카구야님은 고백 받고 싶어 12화 0
[seed] 카구야님은 고백 받고 싶어 13화 0
[seed] 카구야님은 고백 받고 싶어 14화 0
[seed] 카구야님은 고백 받고 싶어 15화 0
[seed] 카구야님은 고백 받고 싶어 16화 0
[seed] 카구야님은 고백 받고 싶어 특별편2화 0
[seed] 카구야님은 고백 받고 싶어 17화 0
[seed] 카구야님은 고백 받고 싶어 18화 0
[seed] 카구야님은 고백 받고 싶어 19화 0
[seed] 카구야님은 고백 받고 싶어 20화 0
[seed] 카구야님은 고백 받고 싶어 21화 0
[seed] 카구야님은 고백 받고 싶어 22화 0
[seed] 카구야님은 고백 받고 싶어 23화 0
[seed] 카구야님은 고백 받고 싶어 24화 0
[seed] 카구야님은 고백 받고 싶어 25화 0
[seed] 카구야님은 고백 받고 싶어 26화 0
[seed] 카구야님은 고백 받고 싶어 27화 0
[seed] 카구야님은 고백 받고 싶어 28화 0
[seed] 카구야님은 고백 받고 싶어 29화 0
[seed] 카구야님은 고백 받고 싶어 30화 0
[seed] 카구야님은 고백 받고 싶어 31화 0
[seed] 카구야님은 고백 받고 싶어 32화 0
[seed] 카구야님은 고백 받고 싶어 33화 0
[seed] 카구야님은 고백 받고 싶어 34화 0
[seed] 카구야님은 고백 받고 싶어 35화 0
[seed] 카구야님은 고백 받고 싶어 36화 0
[seed] 카구야님은 고백 받고 싶어 37화 0
[seed] 카구야님은 고백 받고 싶어 38화 0
[seed] 카구야님은 고백 받고 싶어 39화 0
[seed] 카구야님은 고백 받고 싶어 40화 0
[seed] 카구야님은 고백 받고 싶어 41화 0
[seed] 카구야님은 고백 받고 싶어 42화 0
[seed] 카구야님은 고백 받고 싶어 43화 0
[seed] 카구야님은 고백 받고 싶어 44화 0
[seed] 카구야님은 고백 받고 싶어 45화 0
[seed] 카구야님은 고백 받고 싶어 46화 0
[seed] 카구야님은 고백 받고 싶어 47화 0
[seed] 카구야님은 고백 받고 싶어 48화 0
[seed] 카구야님은 고백 받고 싶어 49화 0
[seed] 카구야님은 고백 받고 싶어 50화 0
[seed] 카구야님은 고백 받고 싶어 51화 0
[seed] 카구야님은 고백 받고 싶어 52화 0
[seed] 카구야님은 고백 받고 싶어 53화 0
[seed] 카구야님은 고백 받고 싶어 다크니스 0
[seed] 카구야님은 고백 받고 싶어 54화 0
[seed] 카구야님은 고백 받고 싶어 55화 0
[seed] 카구야님은 고백 받고 싶어 56화 0
[seed] 카구야님은 고백 받고 싶어 57화 0
[seed] 카구야님은 고백 받고 싶어 58화 0
[seed] 카구야님은 고백 받고 싶어 59화 0
[seed] 카구야님은 고백 받고 싶어 60화 0
[seed] 카구야님은 고백 받고 싶어 61화 0
[seed] 카구야님은 고백 받고 싶어 62화 0
[seed] 카구야님은 고백 받고 싶어 63화 0
[seed] 카구야님은 고백 받고 싶어 64화 0
[seed] 카구야님은 고백 받고 싶어 65화 0
[seed] 카구야님은 고백 받고 싶어 66화 0
[seed] 카구야님은 고백 받고 싶어 67화 0
[seed] 카구야님은 고백 받고 싶어 68화 0
[seed] 카구야님은 고백 받고 싶어 69화 0
[seed] 카구야님은 고백 받고 싶어 70화 0
[seed] 카구야님은 고백 받고 싶어 71화 0
[seed] 카구야님은 고백 받고 싶어 72화 0
[seed] 카구야님은 고백 받고 싶어 73화 0
[seed] 카구야님은 고백 받고 싶어 다크니스2화 0
[seed] 카구야님은 고백 받고 싶어 74화 0
[seed] 카구야님은 고백 받고 싶어 75화 0
[seed] 카구야님은 고백 받고 싶어 76화 0
[seed] 카구야님은 고백 받고 싶어 77화 0
[seed] 카구야님은 고백 받고 싶어 78화 0
[seed] 카구야님은 고백 받고 싶어 79화 0
[seed] 카구야님은 고백 받고 싶어 80화 0
[seed] 카구야님은 고백 받고 싶어 81화 0
[seed] 카구야님은 고백 받고 싶어 82화 0
[seed] 카구야님은 고백 받고 싶어 83화 0
[seed] 카구야님은 고백 받고 싶어 84화 0
[seed] 카구야님은 고백 받고 싶어 85화 0
[seed] 카구야님은 고백 받고 싶어 86화 0
[seed] 카구야님은 고백 받고 싶어 87화 0
[seed] 카구야님은 고백 받고 싶어 88화 0
[seed] 카구야님은 고백 받고 싶어 89화 0
[seed] 카구야님은 고백 받고 싶어 90화 0
[seed] 카구야님은 고백 받고 싶어 91화 0
[seed] 카구야님은 고백 받고 싶어 92화 0
[seed] 카구야님은 고백 받고 싶어 93화 0
[seed] 카구야님은 고백 받고 싶어 94화 0
[seed] 카구야님은 고백 받고 싶어 95화 0
[seed] 카구야님은 고백 받고 싶어 96화 0
[seed] 카구야님은 고백 받고 싶어 97화 0
[seed] 카구야님은 고백 받고 싶어 98화 0
[seed] 카구야님은 고백 받고 싶어 99화 0
[seed] 카구야님은 고백 받고 싶어 번외편 0
[seed] 카구야님은 고백 받고 싶어 100화 0
[seed] 카구야님은 고백 받고 싶어 101화 0
[seed] 카구야님은 고백 받고 싶어 102화 0
[seed] 카구야님은 고백 받고 싶어 103화 0
[seed] 카구야님은 고백 받고 싶어 104화 0
[seed] 카구야님은 고백 받고 싶어 105화 0
[seed] 카구야님은 고백 받고 싶어 106화 0
[seed] 카구야님은 고백 받고 싶어 107화 0
[seed] 카구야님은 고백 받고 싶어 108화 0
[seed] 카구야님은 고백 받고 싶어 109화 0
[seed] 카구야님은 고백 받고 싶어 110화 0
[seed] 카구야님은 고백 받고 싶어 111화 0
[seed] 카구야님은 고백 받고 싶어 112화 0
[seed] 카구야님은 고백 받고 싶어 113화 0
[seed] 카구야님은 고백 받고 싶어 114화 0
[seed] 카구야님은 고백 받고 싶어 115화 0
[seed] 카구야님은 고백 받고 싶어 116화 0
[seed] 카구야님은 고백 받고 싶어 117화 0
[seed] 카구야님은 고백 받고 싶어 118화 0
[seed] 카구야님은 고백 받고 싶어 119화 0
[seed] 카구야님은 고백 받고 싶어 120화 0
[seed] 카구야님은 고백 받고 싶어 121화 0
[seed] 카구야님은 고백 받고 싶어 122화 0
[seed] 카구야님은 고백 받고 싶어 123화 0
[seed] 카구야님은 고백 받고 싶어 124화 0
[seed] 카구야님은 고백 받고 싶어 125화 0
[seed] 카구야님은 고백 받고 싶어 126화 0
[seed] 카구야님은 고백 받고 싶어 127화 4280
[seed] 카구야님은 고백 받고 싶어 127화 4280
[seed] 카구야님은 고백 받고 싶어 127화 4280
[seed] 카구야님은 고백 받고 싶어 127화 4280
[seed] 카구야님은 고백 받고 싶어 127화 4280
[seed] 카구야님은 고백 받고 싶어 127화 4280
[seed] 카구야님은 고백 받고 싶어 127화 4280
[seed] 카구야님은 고백 받고 싶어 127화 4280
fuckkk...
Traceback (most recent call last):
File "constants", line 599, in wrapper
File "manamoa_downloader", line 280, in get_imgs_page
File "capture", line 34, in capture
File "phantomjs", line 91, in get
File "FUCK(5)\remote\webdriver", line 333, in get
File "FUCK(5)\remote\webdriver", line 319, in execute
File "FUCK(5)\remote\remote_connection", line 374, in execute
File "FUCK(5)\remote\remote_connection", line 402, in _request
File "urllib3\request", line 72, in request
File "urllib3\request", line 150, in request_encode_body
File "urllib3\poolmanager", line 326, in urlopen
File "urllib3\connectionpool", line 641, in urlopen
File "urllib3\util\retry", line 368, in increment
File "urllib3\connectionpool", line 603, in urlopen
File "urllib3\connectionpool", line 389, in _make_request
File "urllib3\connectionpool", line 307, in _raise_timeout
ReadTimeoutError: HTTPConnectionPool(host=u'127.0.0.1', port=49458): Read timed out. (read timeout=<object object at 0x027784A8>)

stop
Traceback (most recent call last):
File "utils", line 535, in start
File "utils", line 579, in start_
File "manamoa_downloader", line 128, in read
File "manamoa_downloader", line 257, in get_imgs
File "constants", line 616, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 599, in wrapper
File "manamoa_downloader", line 280, in get_imgs_page
File "capture", line 34, in capture
File "phantomjs", line 91, in get
File "FUCK(5)\remote\webdriver", line 333, in get
File "FUCK(5)\remote\webdriver", line 319, in execute
File "FUCK(5)\remote\remote_connection", line 374, in execute
File "FUCK(5)\remote\remote_connection", line 402, in _request
File "urllib3\request", line 72, in request
File "urllib3\request", line 150, in request_encode_body
File "urllib3\poolmanager", line 326, in urlopen
File "urllib3\connectionpool", line 641, in urlopen
File "urllib3\util\retry", line 368, in increment
File "urllib3\connectionpool", line 603, in urlopen
File "urllib3\connectionpool", line 389, in _make_request
File "urllib3\connectionpool", line 307, in _raise_timeout
ReadTimeoutError: HTTPConnectionPool(host=u'127.0.0.1', port=49458): Read timed out. (read timeout=<object object at 0x027784A8>)


Fail: manamoa

done : https://manamoa9.net/bbs/page.php?hid=manga_detail&manga_id=1507

**Comment by KurtBestor** [comment]
다시 시도해도 안 되나요?
