### ISSUE TITLE
트위치 클립 다운받을 때 폴더명 오류

### ISSUE THREAD

**Issue by skelwarrior** [KurtBestor/Hitomi-Downloader-issues#958]
해결제안만 읽으셔도 됩니다.

문제사항>

트위치 클립 제목이 마침표(.)로 끝날 때,

ex. 안녕하세요. 

다운로드 임시폴더명 끝에 마침표.가 들어가는데, 

이것이 접근과 삭제 불가능한 폴더로 만드는 오류를 발생시킵니다.

(왜냐면 아마도, 파일명과 확장자명을 구분할 때 쓰여야 할 기호가 폴더에 쓰였기 때문일 것입니다. 일반적으로 폴더 생성시에 폴더명 끝에는 마침표를 쓸 수 없습니다.)

때문에 다운로드도 완료되지 않고, 영상도 그 접근불가의 폴더 속에 가둬지게 되며, 일반 사람들로서는 도저히 해당 폴더를 어떻게 할 수가 없게 됩니다.

(명령 프롬프트에서 폴더명을 "ren 폴더명~1 a" 등으로, 도스창에서 폴더명이 축약되는 것을 이용하여, 간신히 이름 변경 뒤에 삭제하거나 접근하여 영상을 꺼낼 수 있습니다. 원래의 마침표가 들어간 폴더명으로는 이름변경이 불가합니다. )

해결제안>

파일 제목 마지막에 마침표 . 가 들어갈 때, 
(즉, 트위치 클립 제목을 긁어올 때 '마지막 글자'가 마침표(.)이면)
　(즉, 중간에 마침표가 오는 것은 상관이 없으니, 마침표(.)가 마지막 글자인 경우에만,)
　　(왜냐면 클립명에 "아니 이것은...." 등 .이 들어가는 경우는 마지막 글자 외에도 많으므로)

이것을 'ㄱ 한자 5번'인 유니코드 기호 -> ．이것으로 변경하도록 조치하여 주시면 오류가 없고 잘 작동할 것 같습니다.

물음표?가 들어갈 때 ㄱ 한자 9번인 유니코드 기호 ->？이것으로 변경토록 한 것 처럼 말입니다.

**Comment by skelwarrior** [comment]
설띵충이라 괄호 많은 것은 안자랑

**Comment by KurtBestor** [comment]
해당 영상 링크 알려주세요.

**Comment by skelwarrior** [comment]
https://clips.twitch.tv/IntelligentSavoryArtichokeOSsloth

2019년 6월 27일 (목) 오후 5:30, Kurt Bestor <notifications@github.com>님이 작성:

**Comment by skelwarrior** [comment]
> 해당 영상 링크 알려주세요.

https://clips.twitch.tv/IntelligentSavoryArtichokeOSsloth

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by skelwarrior** [comment]
> 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview
아주 좋습니다. 잘 작동합니다. 감사합니다.
