### ISSUE TITLE
2.6b -> 2.6c 업글 후 목록을 읽다가 자동으로 종료가되어요.

### ISSUE THREAD

**Issue by gimanan** [KurtBestor/Hitomi-Downloader-issues#959]
업글하라구 해서 업글 하였는데,

2.6b에선 잘만 불러와지던 다운로드 목록들이

2.6c에서는 77프로쯤 왔을때 갑자기 종료가되어 실행이 되지 않습니다.

어느 경고창 하나도 안뜨구요 -0-;; 어떻게 된걸까요

**Comment by KurtBestor** [comment]
실행파일 경로에 있는 `*.ini`  파일 보내주시면 분석해볼게요.

**Comment by gimanan** [comment]
> 실행파일 경로에 있는 `*.ini` 파일 보내주시면 분석해볼게요.

이메일 주소 좀 주시겠어욥 늦게 답장해서 죄송합니다.

**Comment by KurtBestor** [comment]
mangrovn@gmail.com

**Comment by gimanan** [comment]
> [mangrovn@gmail.com](mailto:mangrovn@gmail.com)

메일 보냈읍니다!

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by gimanan** [comment]
> 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

역시 똑같이 종료됩니다 ㅠ_ㅠ;;

**Comment by KurtBestor** [comment]
디스플레이 DPI가 어떻게 되나요?

**Comment by gimanan** [comment]
> 디스플레이 DPI가 어떻게 되나요?

저어;; DPI를 확인하진 못하겠으나 그냥 1920X1080 쓰고 있습니다;;
