### ISSUE TITLE
작가추천기능 zip 파일

### ISSUE THREAD

**Issue by quiving** [KurtBestor/Hitomi-Downloader-issues#96]
작가추천기능이 폴더만 인식하는 것 같은데 zip파일도 인식하게 해주실 수 있나요?
정말 놀라운 신기능 추가해주셔서 감사합니다.

**Comment by KurtBestor** [comment]
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

패치판입니다.
