### ISSUE TITLE
픽시브 설정란에 있는 "포함 태그"는 무슨 기능이죠?

### ISSUE THREAD

**Issue by Dumbisted** [KurtBestor/Hitomi-Downloader-issues#961]
제목 그대로입니다. 히토미 란의 "제외 태그"는 무슨 기능인지 바로 알 수 있는데 픽시브 란의 "포함 태그"는 무슨 기능인지 모르겠군요. 도움말에도 언급되지 않은 듯 해서 질문합니다.

**Comment by KurtBestor** [comment]
해당 태그가 포함된 게시물만 다운로드하는 기능이에요.

**Comment by Dumbisted** [comment]
그런 기능이였군요. 설명해주셔서 감사합니다!
