### ISSUE TITLE
유투브 MP3로 다운로드가 안됩니다. 

### ISSUE THREAD

**Issue by sjsjsj2345** [KurtBestor/Hitomi-Downloader-issues#965]
MP4는 잘만 다운로드 되는데 MP3는 다운로드가 안됩니다. 
좀 예전부터 그랬던것 같긴 한데 언제쯤 고쳐질지 몰라 남겨봅니다.
Invalid: 링크가 뜨고 되지 않습니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by sjsjsj2345** [comment]
되네요. 감사합니다.
