### ISSUE TITLE
작가 이름 대문자로 다운 받을 수는 없나요??

### ISSUE THREAD

**Issue by maybe74** [KurtBestor/Hitomi-Downloader-issues#97]
2.2a 버전 =   Akagi Asahito - Kaichou to Rankou [1213791] [N / A]
2.3   버전 =  akagi asahito - Kaichou to Rankou [1213791] [N／A]

2.3 버전 부터 작가 이름이 소문자로 나오네요

설정 - 폴더명 형식에서 대문자로 바꿔봐도 그대로 소문자로 다운 받아집니다

기능상 큰 문제가 있는 건 아니지만 깔끔하게 정리하는 걸 좋아해서...

아니면 기능이 있는데 제가 모르는 건가요?? ㅠㅠ

**Comment by KurtBestor** [comment]
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

패치판입니다.

**Comment by maybe74** [comment]
그렇게 큰 문제도 아닌데 답변해주셔서 감사합니다!!
