### ISSUE TITLE
호두코믹스 다운이 안됩니다

### ISSUE THREAD

**Issue by bitess** [KurtBestor/Hitomi-Downloader-issues#970]
hodu스크립트 실행하고 하나 잡아서 다운받았는데  invalid 뜨고 작동이 안됩니다.

replace_urls 실행해서 현재 호두코믹스 주소로 바꿔도 안됐습니다.

스크립트파일 열어서 봐도 무슨 문제인지 모르겠어서 올립니다.

invalid 뜬 파일의 정보입니다.

Invalid : [hodu] https://hodu76.com / webtoon / view / 92867

version: 2.6c
platform: Windows-10-10.0.17134
gal_num: https://hodu76.com/webtoon/view/92867
dir: 
zip: 
type: hodu
artist: None
url: https://hodu76.com/webtoon/view/92867
valid: False
done: False
range: None
range_p: None
single: True
time: 1561990671.6 (Jul 1)
tags: []
goodbyedpi: True
lock: False

[Gallery]
None

[File Names]

[URLs]

[Messages]
stop
Traceback (most recent call last):
File "utils", line 412, in __init__
File "dynamic_module_0", line 45, in init
File "dynamic_module_0", line 52, in id
IndexError: list index out of range

Fail: hodu

stop
done : https://hodu76.com/webtoon/view/92867

**Comment by KurtBestor** [comment]
목록 주소를 입력해주세요.

**Comment by bitess** [comment]
해결됐습니다 감사합니다
