### ISSUE TITLE
검색기에서 받아져 있는 파일은 폴더로 바로 가는 버튼이 있으면 좋겠습니다.

### ISSUE THREAD

**Issue by jinjins7** [KurtBestor/Hitomi-Downloader-issues#971]
이 점이 추가되면 정말 좋겠습니다.
검색기에서 받아져 있다고 체크 표시 뜬 것은 검색기 결과에 다운로드 목록에 뜨는 것처럼 폴더로 바로 가는 버튼이 있으면 좋겠습니다.
항상 프로그램 잘 쓰고 있습니다 진심으로 감사드립니다.

**Comment by KurtBestor** [comment]
체크 표시 누르면 폴더 열려요.

**Comment by jinjins7** [comment]
엌 그래요? 매번 다운로드 누르고 폴더 눌렀는데..
감삼다!
