### ISSUE TITLE
번호 추출 버그 있습니다

### ISSUE THREAD

**Issue by zxcvbmm** [KurtBestor/Hitomi-Downloader-issues#972]
저는 파일을 모으기에 하드 용량이 부족하여 히토미 번호를 추출하여 텍스트로 보관하고 있습니다.
그리고 이 번호로 신경망을 통해 작품을 추천받고 있구요.

그런데 작품중에서 모두 일련번호가 6~7자리로 저장되는데 가끔 번호가 2자리로 너무 짧게 보관되는경우가 있습니다.

그 번호로 검색되는 폴더와 텍스트파일을 보니 이런 유형입니다.

-- 이하 메모장 내용 --

갤러리 넘버: 1199861

제목: Itsumi erika (33) -Shota no Seishi to One-san no Ranshi -

작가: derauea

그룹: yakiniku tabetai

타입: doujinshi

시리즈: girls und panzer

캐릭터: erika itsumi

태그: female:big breasts, female:defloration, female:impregnation, female:mind control, female:nakadashi, female:rape, female:sole female, female:x-ray, incest, male:bbm, male:dilf, male:glasses, male:shota

언어: Korean

-- 이하 메모장 내용 끝 --

 제가 가진 파일중 33이 들어가는걸 모두 검색해본 결과 메모장과 폴더에 33이 들어간것은 저게 딱 하나였습니다. 나머지는 모두 해상도나 이미지 제목에 순서 개념으로 33이 들어간 경우였습니다. 
 그리고 1199861 번호는 추출되지 않았습니다.

솔직히 이렇게 추출되는 파일은 매우 극소수이고 제가 그냥 메모장을 수정하면 그만이긴 합니다. 그래도 개발자님이 만든 프로그램이 완벽했으면 하는 바램에 리폿합니다. 

개발자님의 노고 정말 감사합니다. 히토미 다운로드 지원프로그램은 많고 각양각색이지만 이것만큼 편리하고 우수한것은 없습니다. 

좋은하루되세요.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by zxcvbmm** [comment]
제가 고기잡이배를 타서 6개월간 테스트를 못할것같습니다. 어쩌다가 운이좋으면 랩탑 사용이 가능할 때 테스트해보겠습니다.

2019년 7월 3일 (수) 오후 1:30, Kurt Bestor <notifications@github.com>님이 작성:
