### ISSUE TITLE
마나모아 다운이 안됩니다

### ISSUE THREAD

**Issue by glaxyeye** [KurtBestor/Hitomi-Downloader-issues#974]
![20190703_015603](https://user-images.githubusercontent.com/52464635/60531663-70eebe00-9d36-11e9-9320-48fad821614f.jpg)

이렇게 뜨면서 안되는데 왜이러는거죠? 버전은 2.6입니다

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by nightow** [comment]
> 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

위의 gui_test버전으로 실행해봤는데
https://manamoa.net/bbs/board.php?bo_table=manga&wr_id=837393 의 url을 실행하면
![error](https://user-images.githubusercontent.com/26591435/61997738-3e3fa780-b0e1-11e9-9e06-8ea20bbbd2ae.png)
동일하게 에러가 납니다.
