### ISSUE TITLE
마나모아 몇몇 만화가 다운하면 검은 파일만 받아집니다.

### ISSUE THREAD

**Issue by furada1469** [KurtBestor/Hitomi-Downloader-issues#975]
정상적인 화가 많은데 몇몇 화는 이미지가 몇개는 정상이지만
몇개는 검은 파일만 받아집니다. 확인부탁드려요 수고하세요

**Comment by KurtBestor** [comment]
해당 화 주소 알려주세요.

**Comment by furada1469** [comment]
아 죄송합니다.. 제 컴터 문제 였네요 ㅠㅠ 포멧하고 다시 해보니 정상으로 받아집니다
번거롭게 해드려서 죄송해요 ㅠㅠ
