### ISSUE TITLE
기본 데이터 다운로드 오류

### ISSUE THREAD

**Issue by aria1th** [KurtBestor/Hitomi-Downloader-issues#977]
![캡처](https://user-images.githubusercontent.com/35677394/60700476-0060c080-9f33-11e9-84ed-876e34ae8c78.PNG)

![image](https://user-images.githubusercontent.com/35677394/60700504-18384480-9f33-11e9-8255-278ba009c954.png)

삭제된 데이터 다운로드는 정상적으로 됩니다

**Comment by KurtBestor** [comment]
기본 데이터 다운로드 속도 개선하려고 서버 수정하다가 잠깐 실수했었어요. 지금은 제대로 될 거예요.

속도 개선 버전 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

4 배 정도 빠를거예요.
