### ISSUE TITLE
프로그램 실행관련해서 문의남깁니다.

### ISSUE THREAD

**Issue by dpfffneldk** [KurtBestor/Hitomi-Downloader-issues#979]
안녕하세요 다운로더를 잘 쓰고있는 유저입니다.

그동안 다운로더를 잘 사용해오다가 오늘 갑작스럽게 프로그램 실행이 안되어 문의드립니다.

증상은 시작시 다운로드한 리스트(?) 로딩이 98%정도중에 멈춤현상이 잠깐 있고 이후 프로그램이

종료되는 증상입니다.

로그도 같이 첨부합니다. 

Traceback (most recent call last):
  File "hitomi_downloader_GUI.py", line 3088, in closeEvent
MemoryError

게시판에 같은 이유로 문제가 된 과거 사례를 검색해보았지만 

나오지 않아서 직접 문의드리게됐습니다.

**Comment by dpfffneldk** [comment]
현상의 원인이 다운로드 목록이 과도하게 많아서 일어난것을 확인했습니다.

혹시 다운로더를 실행하지않고 다운로드목록을 삭제하는 방법이 있나요?

hitomi_downloader_GUI.ini 파일을 열어서 목록을 수정하는 방법을 생각하고 있긴한데 

파일을 여는데 오래걸려서 그런지 계속 응답없음이 뜨네요

**Comment by KurtBestor** [comment]
다운로드 작업 목록이 몇 개나 되나요?

메모장이면 메뉴바에서 `서식` - `자동 줄 바꿈` 을 체크 해제하고 열면 돼요.

별로 권장하는 방법은 아니에요. 잘못 수정할 수도 있으니 백업해두세요.

**Comment by killenqwe** [comment]
![bandicam 2023-03-07 01-17-26-643](https://user-images.githubusercontent.com/82053844/224363496-aacb68a8-fd7c-441b-b999-93a9b2dd06fd.jpg)
ㅈ저는이렇게뜨는데 그뒤로 목록이 안뜨느데 해결방법므요
