### ISSUE TITLE
다운로드 경로설정 관련 질문

### ISSUE THREAD

**Issue by newtype0222** [KurtBestor/Hitomi-Downloader-issues#98]
안녕하세요. 항상 잘 쓰고 있습니다.

다름이 아니라 다운로드 경로설정에 대해서 질문드립니다.
버전 업데이트 전까지 
다운로드 경로는 hitomi_downloaded
폴더이름은 artist] title (id) 를 설정하고, 고급설정에서 폴더는 압축하고 삭제하는 것으로 해두었습니다.
(이게 정확하지는 않습니다. 하도 오래전에 설정해두고 건든적이 없어서...)

보통 다운을 받으면 # doujinshi 처럼 대분류로 된 폴더에 artist] title (id) 인 폴더가 생겼다가 삭제되고 압축파일만 남는 식으로 저장이 됐었는데요.
그런데 버전 업데이트 후 뭘 잘못 만졌는지 파일이 # type / artist] title (id) 로 만들어지는 겁니다.
당연히 분류도 자동으로 안 되서 일일히 손으로 해야하구요.

그래서 다운로드 경로를 hitomi_downloaded/# type 으로 해봤더니 # type 이란 폴더가 생기고 거기에 저장이 되더군요 ㅎㅎ

readme.txt 파일도 읽어봤지만 딱히 해결책을 찾을 수는 없어서 여기에 글을 남깁니다.

경로설정 혹은 폴더이름 설정을 어떻게 바꿔야 예전처럼 # type 폴더별로 분류가 되고 압축파일은 artist] title (id) 형식으로 저장이 될까요? 

부디 문제해결을 위한 도움을 부탁드리겠습니다.

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/92
