### ISSUE TITLE
산카쿠 다운로드가 갑자기 안됩니다.

### ISSUE THREAD

**Issue by dolco2** [KurtBestor/Hitomi-Downloader-issues#980]
하루 전까지만 해도 잘 됐었는데
갑자기 이상해졌네요;;
컴맹이라 '정보'보기해서 
뜨는거 다 긁어왔습니다.

무슨 로그인 실패라고 하는데...
애시당초 로그인 할 일이 있었나요;;

Invalid : [sankaku] https://chan.sankakucomplex.com / post / show / 14092999

version: 2.6c
platform: Windows-8.1-6.3.9600
gal_num: https://chan.sankakucomplex.com/post/show/14092999
dir: 
zip: 
type: sankaku
artist: None
url: https://chan.sankakucomplex.com/post/show/14092999
valid: False
done: False
range: None
range_p: None
single: True
time: 1562452016.2 (Jul 7)
tags: []
goodbyedpi: False
lock: False

[Gallery]
None

[File Names]

[URLs]

[Messages]
login... 2
Failed to login Traceback (most recent call last):
File "sankaku_login", line 66, in login_
Exception: https://chan.sankakucomplex.com/user/login

login... 0
Failed to login Traceback (most recent call last):
File "sankaku_login", line 66, in login_
Exception: https://chan.sankakucomplex.com/user/login

login... 1
Failed to login Traceback (most recent call last):
File "sankaku_login", line 66, in login_
Exception: https://chan.sankakucomplex.com/user/login

login... 3
Failed to login Traceback (most recent call last):
File "sankaku_login", line 66, in login_
Exception: https://chan.sankakucomplex.com/user/login

login... 1
Failed to login Traceback (most recent call last):
File "sankaku_login", line 66, in login_
Exception: https://chan.sankakucomplex.com/user/login

login... 1
Failed to login Traceback (most recent call last):
File "sankaku_login", line 66, in login_
Exception: https://chan.sankakucomplex.com/user/login

login... 3
Failed to login Traceback (most recent call last):
File "sankaku_login", line 66, in login_
Exception: https://chan.sankakucomplex.com/user/login

login... 2
Failed to login Traceback (most recent call last):
File "sankaku_login", line 66, in login_
Exception: https://chan.sankakucomplex.com/user/login

login... 3
Failed to login Traceback (most recent call last):
File "sankaku_login", line 66, in login_
Exception: https://chan.sankakucomplex.com/user/login

login... 3
Failed to login Traceback (most recent call last):
File "sankaku_login", line 66, in login_
Exception: https://chan.sankakucomplex.com/user/login

login... 1
Failed to login Traceback (most recent call last):
File "sankaku_login", line 66, in login_
Exception: https://chan.sankakucomplex.com/user/login

login... 0
Failed to login Traceback (most recent call last):
File "sankaku_login", line 66, in login_
Exception: https://chan.sankakucomplex.com/user/login

login... 2
Failed to login Traceback (most recent call last):
File "sankaku_login", line 66, in login_
Exception: https://chan.sankakucomplex.com/user/login

login... 1
Failed to login Traceback (most recent call last):
File "sankaku_login", line 66, in login_
Exception: https://chan.sankakucomplex.com/user/login

login... 2
Failed to login Traceback (most recent call last):
File "sankaku_login", line 66, in login_
Exception: https://chan.sankakucomplex.com/user/login

login... 1
Failed to login Traceback (most recent call last):
File "sankaku_login", line 66, in login_
Exception: https://chan.sankakucomplex.com/user/login

stop
Traceback (most recent call last):
File "utils", line 412, in __init__
File "sankaku_downloader", line 56, in init
File "sankaku_login", line 42, in login
Exception: Failed to login

Fail: sankaku

stop
done : https://chan.sankakucomplex.com/post/show/14092999

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

그리고 개별 게시물은 다운로드 지원하지 않아요.

**Comment by dolco2** [comment]
아주 잘 됩니다. 항상 감사합니다.
