### ISSUE TITLE
몇 시간 전에 산카쿠 문의드렸던 사람입니다.

### ISSUE THREAD

**Issue by dolco2** [KurtBestor/Hitomi-Downloader-issues#981]
Issues에 이런글 써도 되는지 모르겠지만
일단은 알려드려야겠다 싶어서 써요.

아까 제시해 주신 버전 깔고서 1차례 태그 다운로드를 성공했는데
두번째로 하려니까 또 다시 비슷한 문제가 뜨더라구요..

그래서 원래 있던거 (안 지워놨었음) 로 다시 바꿔서
다운로드 하니까 또 되네요...
이렇게 한번씩 바꿔서 해야될 판;;;;

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by dolco2** [comment]
일단 태그 다운로드 3회 연속으로 성공은 했습니다. 감사합니다.
