### ISSUE TITLE
About the searcher

### ISSUE THREAD

**Issue by TidusFH** [KurtBestor/Hitomi-Downloader-issues#983]
I know its called hitomi searcher and all but seeing how it is able to download things from ehentai/exhentai,nhentai is it possible to make it search stuff from these sites and not only from hitomi? Or isnt something that is possible?

**Comment by KurtBestor** [comment]
Searcher searches only from hitomi.la. Other sites are not supported in the Searcher currently, but it would be possible in the future.

**Comment by TidusFH** [comment]
> Searcher searches only from hitomi.la. Other sites are not supported in the Searcher currently, but it would be possible in the future.

Thanks for the info, would really support the development to make the searcher support other sites aside of hitomi since it would be  really usefull
