### ISSUE TITLE
산카쿠 문의드렸던 사람입니다.

### ISSUE THREAD

**Issue by dolco2** [KurtBestor/Hitomi-Downloader-issues#984]
아 이게 진짜 ㅋㅋ;;;
정상 작동 된다고 말씀드리고 스레드 닫자마자
다시 똑같은 문제가 발생하네요 
프로그램이 문제가 아니라 웹페이지에서 무슨 조치를 취한게 아닐까요?

아무튼
원래 있던거1
문의 드리고 받은거2
재문의 드리고 받은거3
으로 돌려가면서 쓰고 있습니다.

**Comment by KurtBestor** [comment]
3은 1, 2 모두 시도하는 거라 1, 2 중 하나가 된다면 3도 될거예요.
