### ISSUE TITLE
익헨 다운로드가 불가능합니다

### ISSUE THREAD

**Issue by ggoke123** [KurtBestor/Hitomi-Downloader-issues#985]
최근 히토미 다운이 자꾸 다 익헨으로 자동 변경되서,
다운되길래 그려러니 했는데

그러다보니, 익헨에서 24시간? 벤을 당했습니다.
그리고 그 이후, 익헨 다운로드가 불가능한 상황입니다.
익헨 자체는 잘 들어가지는 상황이고요..

어떻게 해야할까요

**Comment by ggoke123** [comment]
오늘 나갔다가 실행을 해보니 3일 벤? 을 먹었습니다
이유는 지속적인 머신을 통한 다운로드 시도라는데.. ㅠㅠ..
특별히 익헨 시도를 한것도 아닌데 무엇이 문제일까요?

**Comment by KurtBestor** [comment]
`옵션 (Options)` - `설정 (Preferences)...` - `고급 설정` - `DPI 우회` 를 키세요.
