### ISSUE TITLE
검색기 옵션에 중복제거기능은 어떻게 작동하는건가요?

### ISSUE THREAD

**Issue by supermekadeathstalin** [KurtBestor/Hitomi-Downloader-issues#988]
제목이 같은것을 걸러내는건가요?
그러면 제목이 같은데 번역이 진행중이거나 해서 페이지수가 부족한경우는 어떻게 되는건가요?

**Comment by KurtBestor** [comment]
제일 먼저 검색된 작품 (최근 작품) 만 보여요.

제목, 언어, 작가명이 같은 경우에 같은 작품이라고 판단해요.
