### ISSUE TITLE
히토미 긁어올때 파일이름에 태그도 같이 긁어올수 있었으면 좋겠어여

### ISSUE THREAD

**Issue by korithing** [KurtBestor/Hitomi-Downloader-issues#989]
지금은 파일이름에 작가 제목 번호 이렇게만 긁어와서 넣는데
옵션에서 해당 작품의 태그도 같이 긁어와서 파일이름에 넣을 수 있게 했으면 좋겠어여
HDoujin Downloader 에서는 파일이름에 작가/서클/제목/태그등등 옵션을 내가 원하는 순서대로 편집하는 기능이 있어서 분류하기 쉬웠는데 여기도 그런 기능 있으면 좋을거 같네영

프로그램은 매우 잘 쓰고 있스빈다 화이팅

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/688

**Comment by korithing** [comment]
> 참고해주세요: #688

내용 확인했어요! 피드백 감사합니다
근데 txt파일로 저장하기보다는 폴더나 zip파일 이름에 태그를 박을 수 있었으면 좋겠어요!

**Savan**_**Mochi x Mochi!**_Ahegao ♀, Big Breasts ♀, Blowjob ♀, Glasses ♂, Hairy ♀, Hairy ♂, Hotpants ♀, Impregnation ♀, Kissing ♀, Leg Lock ♀

요런 식으로 작가_제목_태그_ 폴더 이름에 바로 태그를 넣을 수 있으면 나중에 정리할때 너무 편하더라구여. 그리고 언어도(Korean, English 등등) 넣으면 더 좋을 수 있을거 같아여. 감사합니다.

**Comment by KurtBestor** [comment]
언어나 그룹명, 타입, 시리즈 등도 폴더명 형식에 지정할 수 있어요.
콤보박스 우측 화살표 눌러서 예제를 보세요.

태그는 폴더명 길이제한 때문에 넣을 수 없어요.

**Comment by korithing** [comment]
> 언어나 그룹명, 타입, 시리즈 등도 폴더명 형식에 지정할 수 있어요.
> 콤보박스 우측 화살표 눌러서 예제를 보세요.
> 
> 태그는 폴더명 길이제한 때문에 넣을 수 없어요.

아 그렇근영 ㅜㅜ 감사합니다

**Comment by Dumbisted** [comment]
그러면 태그 전체를 파일/폴더 이름에 넣는 대신 목표 태그를 입력해서 그 태그가 식별되었다면 그것만 제목 내에 표시하는 방식이면 어떨까요?

예를 들어서 작품 내에 Tankoubon 태그가 있다면 그것만 파일/폴더 이름에 추가하는 식으로요.

**Comment by korithing** [comment]
p{margin-top:0;margin-bottom:0}
    


    그것도 나쁘지는 않은데 한꺼번에 대량으로 긁은 다음에 나중에 분리할때는 가급적이면 태그가 다 살아있는게 좋더라구요.


--------- 원본 메일 ---------

    
        보낸사람: KapHwan <notifications@github.com>
        받는사람: KurtBestor/Hitomi-Downloader-issues <Hitomi-Downloader-issues@noreply.github.com>
        
            참조: korithing <namtang-2000@hanmail.net>, Author <author@noreply.github.com>
        
        날짜: 19.07.20 19:14 GMT +0900
        제목: Re: [KurtBestor/Hitomi-Downloader-issues] 히토미 긁어올때 파일이름에 태그도 같이 긁어올수 있었으면 좋겠어여 (
        
        
    
    
        그러면 태그 전체를 파일/폴더 이름에 넣는 대신 목표 태그를 입력해서 그 태그가 식별되었다면 그것만 제목 내에 표시하는 방식이면 어떨까요?

예를 들어서 작품 내에 Tankoubon 태그가 있다면 그것만 파일/폴더 이름에 추가하는 식으로요.
