### ISSUE TITLE
searcher에서 태그 필터링은 불가능한가요?

### ISSUE THREAD

**Issue by aramath** [KurtBestor/Hitomi-Downloader-issues#99]
제가 기피하는 태그가 워낙 많아서 일일히 눈으로 골라내기가 힘드네요.

searcher 창에서도 태그 기피 및 검열 기능이 있으면 좋겠습니다.

혹시 이미 있는데 제가 발견 못한건가요?

**Comment by KurtBestor** [comment]
도움말 - 사용법을 참고해주세요.
