### ISSUE TITLE
파일이 깨져서 받아집니다.

### ISSUE THREAD

**Issue by carNYmelo** [KurtBestor/Hitomi-Downloader-issues#990]
다운로더 너무 잘 쓰고있습니다. 하지만 최근 다운로드한 결과물이 깨져서 속상하네요.

히토미에서 직빵으로 다운받아도 깨진 이미지인것으로 보아 파일에 문제가 있어보이긴 합니다. 하지만 READ ONLINE 으로는 안깨지고 잘 봐져요. 특정 작가의 작품들만의 문제인것 같기도 합니다. 꽤 오류파일이 많아서 몇가지만 예시로 올리겠습니다.

1403084 1207367 1377220

코드따라가보시면 아실 수 있는데, Setoran 그룹만 안됩니다. (다른작가것도 있지만 소수입니다) 혹시나 해결방안이 있으시면 답변 부탁드립니다. 다시한번 수고에 감사와 존경의 마음을 전합니다.

**Comment by KurtBestor** [comment]
어떤 이미지 뷰어 쓰시나요?
