### ISSUE TITLE
검색할때 미리보기 이미지가 안나옵니다 

### ISSUE THREAD

**Issue by FRT222** [KurtBestor/Hitomi-Downloader-issues#991]
메인화면에서 다운 받은 목록에서는 미리보기 이미지가 나오는데 검색할때 모든 작품의 미리보기 이미지가 안나옵니다 ㅜㅜ

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/906
