### ISSUE TITLE
검색기 추가 기능 제안

### ISSUE THREAD

**Issue by Rounlet** [KurtBestor/Hitomi-Downloader-issues#998]
검색기를 통해 작품을 검색하게 되면, 히토미 다운로드 폴더에 있는 작품일 경우, 체크표시를 통해 이미 다운로드 됐음을 확인할 수 있습니다.

하지만 이 폴더에서 벗어나 다른 폴더에 옮길 경우, 이 체크 표시가 사라져서 중복 다운로드하는 경우가 종종 있습니다.

그래서 히토미 갤러리 번호를 옵션 값을 저장하는 파일처럼 따로 관리해서 히토미 다운로드 폴더에 없더라도 이미 다운로드된 작품인 것을 확인할 수 있었으면 좋겠습니다.

그리고 이 업데이트 이전의 작품들 같은 경우, [이미 다운로드] 버튼을 추가해서 보유 목록에 추가하는 기능을 마련해주신다면 이 다운로더를 통해서 전체적인 관리가 이루어 질 수 있을 것 같습니다.

점점 커져가는 다운로더를 보고 이거 글로벌 진출하게 되는건 아닐까 걱정될 정도로 뿌듯합니다.
우리나라만 알고 있어야하는데..ㅋ

**Comment by KurtBestor** [comment]
깔끔한 방법이 없고 지저분해질까봐 아마 넣지 않을거예요.

문제가 많아요:
1. 갤러리 번호 목록 파일을 어떻게 저장하고 읽어들일 것인지
1. 목록 파일과 다운로드 폴더를 어떻게 동기화할지 (한 쪽이 삭제되면 어떻게 동기화할지)
1. 목록 파일에서 삭제하고 싶은 작품이 있을 경우에 어떻게 할지
1. 검색기에서 이미 다운로드한 작품 체크표시를 눌렀을 때 어떻게 동작할지
1. 다운로드 폴더가 바뀌었을 때 어떻게 동작할지
1. 목록 파일과 다운로드 폴더 두 개를 관리해야하는 불편함
